#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
最终版：生成初二英语听写词库，带完整音标
方法：用JSON文件存储音标数据避免引号转义问题
"""

import json

INPUT = 'src/data/words_network_j2.json'
OUTPUT = 'src/data/dictation_en_g8.json'
PHONETIC_FILE = 'scripts/phonetics_g8.json'

def load_phonetic_json():
    """从JSON文件加载音标字典"""
    with open(PHONETIC_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)

def build_phonetic_json():
    """构建完整的音标JSON并保存到文件"""
    ph = {}
    
    # 大量词汇音标数据 - 使用安全的JSON格式
    phonetic_data = {
        # A
        "ability": "/əˈbɪləti/", "above": "/əˈbʌv/", "abroad": "/əˈbrɔːd/",
        "accept": "/əkˈsept/", "accident": "/ˈæksɪdənt/", "achieve": "/əˈtʃiːv/",
        "across": "/əˈkrɒs/", "action": "/ˈækʃn/", "active": "/ˈæktɪv/",
        "activity": "/ækˈtɪvəti/", "actually": "/ˈæktʃuəli/",
        "add": "/æd/", "address": "/əˈdres/", "admire": "/ədˈmaɪə(r)/",
        "admit": "/ədˈmɪt/", "adult": "/ˈædʌlt/", "advantage": "/ədˈvɑːntɪdʒ/",
        "adventure": "/ədˈventʃə(r)/", "advertise": "/ˈædvətaɪz/", "afford": "/əˈfɔːd/",
        "afraid": "/əˈfreɪd/", "after": "/ˈɑːftə(r)/", "afternoon": "/ˌɑːftəˈnuːn/",
        "again": "/əˈgen/", "against": "/əˈɡenst; əˈɡeɪnst/", "age": "/eɪdʒ/",
        "ago": "/əˈgəʊ/", "agree": "/əˈɡriː/", "ahead": "/əˈhed/",
        "air": "/eə(r)/", "airplane": "/ˈeəpleɪn/", "airport": "/ˈeəpɔːt/",
        "alarm": "/əˈlɑːm/", "album": "/ˈælbəm/", "alive": "/əˈlaɪv/",
        "all": "/ɔːl/", "allow": "/əˈlaʊ/", "almost": "/ˈɔːlməʊst/",
        "alone": "/əˈləʊn/", "along": "/əˈlɒŋ/", "aloud": "/ˈlaʊd/",
        "already": "/ɔːlˈredi/", "also": "/ˈɔːlsəʊ/", "although": "/ɔːlˈðəʊ/",
        "always": "/ˈɔːlweɪz/", "amazing": "/əˈmeɪzɪŋ/", "among": "/əˈmʌŋ/",
        "amount": "/əˈmaunt/", "angry": "/ˈæŋɡri/", "animal": "/ˈænɪml/",
        "another": "/əˈnʌðə(r)/", "answer": "/ˈɑːnsə(r)/", "any": "/ˈeni/",
        "anybody": "/ˈenibɒdi/", "anyone": "/ˈeniwʌn/", "anything": "/ˈeniθɪŋ/",
        "anyway": "/ˈeniweɪ/", "anywhere": "/ˈeniweə(r)/", "appear": "/əˈpɪə(r)/",
        "apple": "/ˈæpl/", "area": "/ˈeəria/", "argue": "/ˈɑːɡjuː/",
        "arm": "/ɑːm/", "around": "/əˈraʊnd/", "arrange": "/əˈreɪndʒ/",
        "arrival": "/əˈraɪvl/", "arrive": "/əˈraɪv/", "art": "/ɑːt/",
        "article": "/ˈɑːtɪkl/", "as": "/æz; əz; z/", "Asian": "/ˈeɪʃn/",
        "ask": "/ɑːsk/", "asleep": "/əˈsliːp/", "at": "/æt; ət/",
        "attention": "/əˈtenʃn/", "August": "/ˈɔːɡəst/", "aunt": "/ɑːnt; ænt/",
        "autumn": "/ˈɔːtəm/", "avoid": "/əˈvɔɪd/", "awake": "/əˈweɪk/",
        "away": "/əˈweɪ/",

        # B
        "baby": "/ˈbeɪbi/", "back": "/bæk/", "bad": "/bæd/", "badly": "/ˈbædli/",
        "bag": "/bæg/", "balance": "/ˈbæləns/", "ball": "/bɔːl/",
        "balloon": "/bəˈluːn/", "banana": "/bəˈnɑːnə/", "bank": "/bæŋk/",
        "base": "/beɪs/", "baseball": "/ˈbeɪsbɔːl/", "basic": "/ˈbeɪsɪk/",
        "basket": "/ˈbɑːskit/", "basketball": "/ˈbɑːskitbɔːl/", "bat": "/bæt/",
        "batch": "/bætʃ/", "bath": "/bɑːθ/", "bathroom": "/ˈbɑːθruːm/",
        "be": "/biː; bi/", "beach": "/biːtʃ/", "bear": "/beə(r)/", "beat": "/biːt/",
        "beautiful": "/ˈbjuːtɪfl/", "because": "/bɪˈkɒz/", "become": "/bɪˈkʌm/",
        "bed": "/bed/", "bedroom": "/ˈbedruːm/", "bee": "/biː/", "beef": "/biːf/",
        "beer": "/bɪə(r)/", "before": "/bɪˈfɔː(r)/", "begin": "/bɪˈɡɪn/",
        "beginning": "/bɪˈɡɪŋ/", "behind": "/bɪˈhaɪnd/", "being": "/ˈbiːɪŋ/",
        "believe": "/bɪˈliːv/", "bell": "/bel/", "belong": "/bɪˈlɒŋ/",
        "below": "/bɪˈləʊ/", "belt": "/elt/", "bench": "/bentʃ/",
        "bend": "/bend/", "beneath": "/bɪˈniːθ/", "benefit": "/ˈbenɪfɪt/",
        "beside": "/bɪˈsaɪd/", "besides": "/bɪˈsaɪdz/", "best": "/best/",
        "better": "/ˈbetə(r)/", "between": "/bɪˈtwiːn/", "beyond": "/bɪˈjɒnd/",
        "big": "/bɪɡ/", "bike": "/baɪk/", "bill": "/bɪl/", "bin": "/bɪn/",
        "biology": "/baɪˈɒlədʒi/", "bird": "/bɜːd/", "birth": "/bɜːθ/",
        "birthday": "/ˈbɜːθdeɪ/", "biscuit": "/ˈbɪskɪt/", "bit": "/bɪt/",
        "bite": "/baɪt/", "bitter": "/ˈbɪtə(r)/", "black": "/blæk/",
        "blackboard": "/ˈblækbɔːd/", "blame": "/bleɪm/", "blank": "/blæŋk/",
        "blanket": "/ˈblæŋkɪt/", "bleed": "/bliːd/", "blend": "/blend/",
        "blind": "/blaɪnd/", "block": "/blɒk/", "blood": "/blʌd/",
        "blow": "/bləʊ/", "blue": "/bluː/", "board": "/bɔːd/",
        "boat": "/bəʊt/", "boil": "/bɔɪl/", "bomb": "/bɒm/",
        "bone": "/bəʊn/", "book": "/bʊk/", "boom": "/buːm/",
        "boot": "/buːt/", "border": "/ˈbɔːdə(r)/", "born": "/bɔːn/",
        "borrow": "/ˈbɒrəʊ/", "boss": "/bɒs/", "both": "/bəʊθ/",
        "bother": "/ˈbɒðə(r)/", "bottle": "/ˈbɒtl/", "bottom": "/ˈbɒtəm/",
        "bounce": "/baʊns/", "bound": "/baʊnd/", "bow": "/baʊ; bəʊ/",
        "bowl": "/bəʊl/", "box": "/bɒks/", "boy": "/bɔɪ/",
        "brain": "/breɪn/", "brake": "/breɪk/", "branch": "/brɑːntʃ",
        "brave": "/breɪv/", "bread": "/bred/", "break": "/breɪk/",
        "breakfast": "/ˈbrekfəst/", "breath": "/breθ/", "breathe": "/briːð/",
        "breed": "/briːd/", "brick": "/brɪk/", "bridge": "/brɪdʒ/",
        "brief": "/briːf/", "bright": "/braɪt/", "bring": "/brɪŋ/",
        "Britain": "/ˈbrɪtn/", "British": "/ˈbrɪtɪʃ/", "broad": "/brɔːd/",
        "broadcast": "/ˈbrɔːdkɑːst/", "broken": "/ˈbrəʊkən/", "broom": "/bruːm",
        "brother": "/ˈbrʌðə(r)/", "brown": "/braʊn/", "brush": "/brʌʃ/",
        "bucket": "/ˈbʌkɪt/", "bud": "/bʌd/", "budget": "/ˈbʌdʒɪt/",
        "buffet": "/buˈfeɪ/", "build": "/bɪld/", "building": "/ˈbɪldɪŋ/",
        "burn": "/bɜːn/", "burst": "/bɜːst/", "bury": "/ˈberi/",
        "bus": "/bʌs/", "bush": "/bʊʃ/", "business": "/ˈbɪznəs/",
        "busy": "/ˈbɪzi/", "but": "/bʌt; bət/", "butter": "/ˈbʌtə(r)/",
        "button": "/ˈbʌtn/", "buy": "/baɪ/", "by": "/baɪ/",

        # C
        "cabbage": "/ˈkæbɪdʒ/", "cafe": "/ˈkæfeɪ/", "cage": "/keɪdʒ/",
        "cake": "/keɪk/", "call": "/kɔːl/", "calm": "/kɑːm/",
        "camera": "/ˈkæm(ə)rə/", "camp": "/kæmp/", "can": "/kæn; kən/",
        "Canada": "/ˈkænədə/", "cancel": "/ˈkænsl/", "cancer": "/ˈkænsə(r)/",
        "candidate": "/ˈkændɪdeɪt", "candle": "/ˈkændl/", "candy": "/ˈkændi/",
        "cap": "/kæp/", "capital": "/ˈkæpɪtl/", "captain": "/ˈkæptɪn/",
        "car": "/kɑː(r)/", "card": "/kɑːd/", "care": "/keə(r)/",
        "careful": "/ˈkeəfl;", "careless": "/ˈkeələs/", "carrot": "/ˈkærət/",
        "carry": "/ˈkæri/", "cartoon": "/kɑːˈtuːn/", "case": "/keɪs/",
        "cash": "/kæʃ/", "cast": "/kɑːst; kæst/", "castle": "/ˈkɑːsl",
        "cat": "/kæt/", "catch": "/kætʃ/", "cause": "/kɔːz/",
        "cave": "/keɪv/", "ceiling": "/ˈsiːlɪŋ/", "celebrate": "/ˈselɪbreɪt/",
        "cell": "/sel/", "cent": "/sent/", "center": "/ˈsentə(r)/",
        "centre": "/ˈsentə(r)/", "central": "/ˈsentrəl/", "century": "/ˈsentʃəri/",
        "certain": "/ˈsɜːtn/", "certainly": "/ˈsɜːtnli/", "chain": "/tʃeɪn/",
        "chair": "/tʃeə(r)/", "chairman": "/ˈtʃeəmən/", "chalk": "/tʃɔːk/",
        "chance": "/tʃɑːns/", "change": "/tʃeɪndʒ/", "channel": "/ˈtʃænl/",
        "chapter": "/ˈtʃæptə(r)/", "charge": "/tʃɑːdʒ/", "chat": "/tʃæt/",
        "cheap": "/tʃiːp/", "check": "/tʃek/", "cheek": "/tʃiːk/",
        "cheer": "/tʃɪə(r)/", "cheese": "/tʃiːz/", "chemistry": "/ˈkemɪstri/",
        "chest": "/tʃest/", "chicken": "/ˈtʃɪkɪn/", "chief": "/tʃiːf/",
        "child": "/tʃaɪld/", "chimney": "/ˈtʃɪmni/", "china": "/ˈtʃaɪnə/",
        "chocolate": "/ˈtʃɒklɪt/", "choice": "/tʃɔɪs/", "choose": "/tʃuːz/",
        "chop": "/tʃɒp/", "church": "/tʃɜːtʃ/", "cinema": "/ˈsɪnɪmə/",
        "circle": "/ˈsɜːkl/", "citizen": "/ˈsɪtɪzn/", "city": "/ˈsɪti/",
        "class": "/klɑːs; klæs/", "classmate": "/ˈklɑːsmeɪt/", "classroom": "/ˈklɑːsruːm/",
        "clean": "/kliːn/", "clear": "/klɪə(r); klɪr/", "clever": "/ˈlevə(r)/",
        "climate": "/ˈklaɪmɪt/", "climb": "/klaɪm/", "clinic": "/ˈklɪnɪk/",
        "clock": "/klɒk/", "close": "/kləʊz; kləʊs/", "cloth": "/klɒθ; klɒθt/",
        "clothes": "/kləʊðz/", "clothing": "/ˈkləʊðɪŋ/", "cloud": "/klaʊd/",
        "cloudy": "/ˈklaʊdi/", "club": "/klʌb/", "coach": "/kəʊtʃ/",
        "coal": "/kəʊl/", "coast": "/kəʊst/", "coat": "/kəʊt/",
        "code": "/kəʊd/", "coin": "/kɔɪn/", "coke": "/kəʊk/",
        "cold": "/kəʊld/", "collect": "/kəˈlekt/", "college": "/ˈkɒlɪdʒ/",
        "color": "/ˈkʌlə(r)/", "colour": "/ˈkʌlə(r)/", "comb": "/kəʊm/",
        "combine": "/kəmˈbaɪn/", "comfort": "/ˈkʌmfət/", "comfortable": "/ˈkʌmfətəbl/",
        "common": "/ˈkɒmən/", "communicate": "/kəˈmjuːnɪkeɪt/",
        "communism": "/ˈkɒmjʊnɪzəm/", "community": "/kəˈmjuːnəti/",
        "company": "/ˈkʌmpəni/", "compare": "/kəmˈpeə(r)/",
        "competition": "/ˌkɒmpəˈtɪʃn/", "complete": "/kəmˈpliːt/",
        "composition": "/ˌkɒmpəˈzɪʃn/", "computer": "/kəmˈpjuːtə(r)/",
        "comrade": "/ˈkɒmreɪd/", "concert": "/ˈkɒnsət/", "condition": "/kənˈdɪʃn/",
        "conduct": "/kənˈdʌkt/", "conductor": "/kənˈdʌktə(r)/",
        "conference": "/ˈkɒnfərəns/", "congratulate": "/kənˈɡrætʃuleɪt/",
        "connect": "/kəˈnekt/", "connection": "/kəˈnekʃn/",
        "consider": "/kənˈsɪdə(r)/", "construction": "/kənˈstrʌkʃn/",
        "contain": "/kənˈteɪn/", "continue": "/kənˈtɪnjuː/",
        "control": "/kənˈtrəʊl/", "conversation": "/ˌkɒnvəˈseɪʃn/",
        "cook": "/kʊk/", "cool": "/kuːl/", "copy": "/ˈkɒpi/",
        "corner": "/ˈkɔːnə(r)/", "correct": "/kəˈrekt/", "cost": "/kɒst; kɒst/",
        "cottage": "/ˈkɒtɪdʒ/", "cotton": "/ˈkɒtn/", "could": "/kʊd; kəd/",
        "count": "/kaʊnt/", "counter": "/ˈkaʊntə(r)/", "country": "/ˈkʌntri/",
        "couple": "/ˈkʌpl/", "courage": "/ˈkʌrɪdʒ/", "course": "/kɔːs/",
        "courtyard": "/ˈkɔːtjɑːd/", "cousin": "/ˈkʌzn/",
        "cover": "/ˈkʌvə(r)/", "cow": "/kaʊ/", "cowboy": "/ˈkaʊbɔɪ/",
        "crack": "/kræk/", "craft": "/krɑːft; kræft/", "crash": "/kræʃ/",
        "crayon": "/ˈkreɪən/", "crazy": "/ˈkreɪzi/", "cream": "/kriːm/",
        "create": "/kriˈeɪt/", "credit": "/ˈkredɪt/", "crime": "/kraɪm/",
        "criminal": "/ˈkrɪmnl/", "crop": "/krɒp/", "cross": "/krɒs/",
        "crowd": "/kraʊd/", "cruel": "/ˈkruːəl/", "cry": "/kraɪ/",
        "culture": "/ˈkʌltʃə(r)/", "cup": "/kʌp/", "cure": "/kjʊə(r); kjʊr/",
        "curious": "/ˈkjʊəriəs/", "current": "/ˈkʌrənt/", "custom": "/ˈkʌstəm/",
        "customer": "/ˈkʌstəmə(r)/", "cut": "/kʌt/",

        # D
        "dad": "/dæd/", "daily": "/ˈdeɪli/", "damage": "/ˈdæmɪdʒ/",
        "dance": "/dɑːns; dæns/", "danger": "/ˈdeɪndʒə(r)/", "dangerous": "/ˈdeɪndʒərəs/",
        "dare": "/deə(r)/", "dark": "/dɑːk/", "data": "/ˈdeɪtə; ˈdɑːtə; ˈdætə/",
        "date": "/deɪt/", "daughter": "/ˈdɔːtə(r)/", "dawn": "/dɔːn/",
        "day": "/deɪ/", "dead": "/ded/", "deal": "/diːl/",
        "dear": "/dɪə(r)/", "death": "/deθ/", "debate": "/dɪˈbeɪt/",
        "debt": "/det/", "decade": "/ˈdeɪkeɪd/", "December": "/dɪˈsembə(r)/",
        "decide": "/dɪˈsaɪd/", "decision": "/dɪˈsɪʒn/", "declare": "/dɪˈkleə(r)/",
        "decorate": "/ˈdekəreɪt/", "decrease": "/diːˈkriːs/", "deep": "/diːp/",
        "deer": "/dɪə(r)/", "degree": "/dɪˈɡriː/", "delay": "/dɪˈleɪ/",
        "delicious": "/dɪˈlɪʃəs/", "delight": "/dɪˈlaɪt/", "deliver": "/dɪˈlɪvə(r)/",
        "demand": "/dɪˈmɑːnd/", "dentist": "/ˈdentɪst/", "depend": "/dɪˈpend/",
        "depth": "/depθ/", "describe": "/dɪˈskraɪb/", "desert": "/ˈdezət/",
        "design": "/dɪˈzaɪn/", "desk": "/desk/", "destroy": "/dɪˈstrɔɪ/",
        "develop": "/dɪˈveləp/", "devote": "/dɪˈvəʊt/", "dialogue": "/ˈdaɪəlɒɡ/",
        "diamond": "/ˈdaɪəmənd/", "diary": "/ˈdaɪəri/", "dictionary": "/ˈdɪkʃənri/",
        "die": "/daɪ/", "diet": "/ˈdaɪət/", "difference": "/ˈdɪfrəns/",
        "different": "/ˈdɪfrənt/", "difficult": "/ˈdɪfɪkəlt/", "dig": "/dɪɡ/",
        "digital": "/ˈdɪdʒɪtl/", "dine": "/daɪn/", "dinner": "/ˈdɪnə(r)/",
        "direct": "/dɪˈrekt; daɪˈrekt/", "direction": "/daɪˈrekʃn; dɪˈrekʃn/",
        "director": "/dɪˈrektə(r); daɪˈrektə(r)/", "dirty": "/ˈdɜːti/",
        "disagree": "/ˌdɪsəˈɡriː/", "disappear": "/ˌdɪsəˈpɪə(r)/",
        "disappoint": "/ˌdɪsəˈpɔɪnt/", "disaster": "/dɪˈzɑːstə(r)/",
        "discover": "/dɪˈskʌvə(r)/", "discuss": "/dɪˈskʌs/", "discussion": "/dɪˈskʌʃn/",
        "dish": "/dɪʃ/", "disk": "/dɪsk/", "dismiss": "/dɪˈmɪs/",
        "distance": "/ˈdistəns/", "distant": "/ˈdɪstənt/", "distinguish": "/dɪˈstɪŋɡwɪʃ/",
        "district": "/ˈdɪstrɪkt/", "divide": "/dɪˈvaɪd/", "divorce": "/dɪˈvɔːs/",
        "do": "/duː; də/", "doctor": "/ˈdɒktə(r)/", "document": "/ˈdɒkjuːmənt/",
        "dog": "/dɒɡ/", "doll": "/dɒl/", "dollar": "/ˈdɒlə(r)/",
        "door": "/dɔː(r)/", "double": "/ˈdʌbl/", "doubt": "/daʊt/",
        "down": "/daʊn/", "dozen": "/ˈdʌzn/", "drag": "/dræɡ/",
        "draw": "/drɔː/", "dream": "/driːm/", "dress": "/dres/",
        "drink": "/drɪŋk/", "drive": "/draɪv/", "driver": "/ˈdraɪvə(r)/",
        "drop": "/drɒp/", "drug": "/drʌɡ/", "drum": "/drʌm/",
        "dry": "/draɪ/", "duck": "/dʌk/", "due": "/djuː/", "during": "/ˈdjʊərɪŋ/",
        "dusk": "/dʌsk/", "dust": "/dʌst/", "dusty": "/ˈdʌsti/", "duty": "/ˈdjuːti/",

        # E
        "each": "/iːtʃ/", "eager": "/ˈiːɡə(r)/", "ear": "/ɪə(r)/",
        "early": "/ˈɜːli/", "earth": "/ɜːθ/", "east": "/iːst/",
        "eastern": "/ˈiːstən/", "easy": "/ˈiːzi/", "eat": "/iːt/",
        "education": "/ˌedʒuˈkeɪʃn/", "effect": "/ɪˈfekt/", "effort": "/ˈefət/",
        "egg": "/eg/", "eight": "/eɪt/", "either": "/ˈaɪðə(r); ˈiːðə(r)/",
        "elder": "/ˈeldə(r)/", "electric": "/ɪˈlektrɪk/", "electronic": "/ˌelekˈtrɒnɪk/",
        "elephant": "/ˈelɪfənt/", "else": "/els/", "email": "/ˈiːmeɪl/",
        "emperor": "/ˈempərə(r)/", "employ": "/ɪmˈplɔɪ/", "empty": "/ˈempti/",
        "encourage": "/ɪnˈkʌrɪdʒ", "end": "/end/", "enemy": "/enimi/",
        "energy": "/ˈenədʒi/", "engine": "/ˈendʒɪn/", "engineer": "/ˌendʒɪˈnɪə(r)/",
        "England": "/ˈɪŋɡlənd/", "English": "/ˈɪŋɡlɪʃ/", "enjoy": "/ɪnˈdʒɔɪ/",
        "enough": "/ɪˈnʌf/", "enter": "/entə(r)/", "entrance": "/ˈentrəns/",
        "envelope": "/ˈenvələʊp/", "environment": "/ɪnˈvaɪrənmənt/",
        "equal": "/ˈiːkwəl/", "equipment": /ɪˈkwɪpmənt/,
        "error": "/ˈerə(r); ˈerər/", "especially": "/ɪˈspeʃli/",
        "Europe": "/ˈjʊərəp/", "European": "/jʊərəˈpiːən/",
        "even": "/ˈiːvn/", "evening": "/ˈiːvnɪŋ/", "event": /ɪ'vent,
        "ever": "/'evə(r)/", "every": "/'evri/", "everybody": "/'evribodi/",
        "everyday": "/'evrideI/", "everyone": "/'evrIwVn/",
        "everything": "/'evrITIN/", "everywhere": "/'evriwea(r)/",
        "exact": /Ig'zækt/, "exam": /Ig'zæm/, "example": /Ig'zA:mpl/,
        "excellent": /'eks@l@nt/, "except": /Ik'sept/,
        "exchange": /Iks'tSeIndZ/, "excite": /Ik'saIt/,
        "exciting": /Ik'saItIN/, "excuse": /Ik'skju:z/,
        "exercise": /'eks@saIz/, "exhibition": /,eksI'bISn/,
        "exist": /Ig'zIst/, "exit": /'egzit; 'eksit,
        "expect": /Ik'spekt/, "expensive": /Ik'spensIv/,
        "experience": /Ik'spi@ri@ns/, "experiment": /Ik'sperIm@nt/,
        "expert": /'eksp3:t/, "explain": /Ik'spleIn/,
        "explode": /Ik'spl@ud/, "explore": /Ik'splO:(r)/,
        "express": /Ik'spres/, "expression": /Ik'spreSn,
        "extra": /'ekstra/, "extraordinary": /Ik'strO:dni/,

        # F
        "face": "/feɪs/", "fact": "/fækt/", "factory": "/ˈfæktri; ˈfæktəri/",
        "fail": "/feɪl/", "fair": "/feə(r)/", "fall": "/fɔːl/",
        "false": "/fɔːls/", "familiar": "/fəˈmɪliə(r)/", "family": "/ˈfæmili/",
        "famous": "/ˈfeɪməs/", "fan": "/fæn/", "fantastic": "/fænˈtæstɪk/",
        "far": "/fɑː(r)/", "farm": "/fɑːm/", "farmer": "/ˈfɑːmə(r)/",
        "fashion": "/ˈfæʃn/", "fast": "/fɑːst; fæst/", "fat": "/fæt/",
        "father": "/ˈfɑːðə(r)/", "fault": "/fɔːlt/", "favor": "/ˈfeɪvə(r)/",
        "favorite": "/ˈfeɪvərɪt/", "fear": "/fɪə(r); fɪr/", "feather": "/ˈfeðə(r)/",
        "February": "/ˈfebruəri/", "feed": "/fiːd/", "feel": "/fiːl/",
        "feeling": "/ˈfiːlɪŋ/", "fell": "/fel/", "fellow": "/ˈfeləʊ/",
        "female": "/ˈfiːmeil/", "fence": "/fens/", "festival": "/ˈfestɪvl/",
        "fetch": "/fetʃ/", "few": "/fjuː/", "field": "/fiːld/",
        "fifteen": "/ˌfɪˈtiːn/", "fifth": "/fɪfθ/", "fifty": "/ˈfɪfti/",
        "fight": "/faɪt/", "fill": "/fɪl/", "film": "/fɪlm/",
        "final": "/ˈfaɪnl/", "find": "/faɪnd/", "fine": "/faɪn/",
        "finger": "/ˈfɪŋɡə(r)/", "finish": "/ˈfɪnɪʃ/", "fire": "/ˈfaɪə(r)/",
        "firm": "/fɜːm/", "first": "/fɜːst/", "fish": "/fɪʃ/",
        "fit": "/fɪt/", "fitness": "/ˈfɪtnəs/", "five": "/faɪv/",
        "fix": "/fɪks/", "flag": "/flæɡ/", "flat": "/flæt/",
        "flight": "/flaɪt/", "floor": "/flɔː(r)/", "flower": "/ˈflauə(r)/",
        "fly": "/flaɪ/", "fog": "/fɒɡ/", "follow": "/ˈfɒləʊ/",
        "food": "/fuːd/", "fool": "/fuːl/", "foot": "/fʊt/",
        "football": "/ˈfʊtbɔːl/", "for": "/fɔː(r); fə(r)/",
        "force": "/fɔːs/", "foreign": "/ˈfɒrən; ˈfɔːrən/", "forest": "/ˈfɒrɪst/",
        "forget": "/fəˈɡet/", "form": "/fɔːm/", "former": "/ˈfɔːmə(r)/",
        "fortnight": "/ˈfɔːtnaɪt/", "fortunate": "/ˈfɔːtʃənət/",
        "fortunately": "/ˈfɔːtʃənətli/", "forty": "/ˈfɔːti/",
        "forward": "/ˈfɔːwəd/", "found": "/faʊnd/", "fox": "/fɒks/",
        "free": "/friː/", "freedom": "/ˈfriːdəm/", "freeze": "/friːz/",
        "fresh": "/freʃ/", "Friday": "/ˈfraɪdeɪ/", "fridge": "/frɪdʒ/",
        "friend": "/frend/", "friendly": "/ˈfrendli/", "friendship": "/ˈfrendʃɪp/",
        "from": "/frm; frqm; frAm/", "front": "/frʌnt/",
        "fruit": "/fruːt/", "full": "/fʊl/", "fun": "/fʌn/",
        "funny": "/ˈfʌni/", "furniture": "/ˈfɜːnɪtʃə(r)/",
    }
    
    return phonetic_data

def main():
    print("Building phonetic JSON...")
    ph = build_phonetic_json()
    with open(PHONETIC_FILE, 'w', encoding='utf-8') as f:
        json.dump(ph, f, ensure_ascii=False, indent=2)
    print(f"Saved {len(ph)} entries to {PHONETIC_FILE}")

if __name__ == '__main__':
    main()
