#!/usr/bin/env python3
"""
小学英语单词联想网络生成器
用 DeepSeek API 批量生成联想、形近词、记忆口诀
输出: src/data/words_network.json
"""

import json
import time
import os
import re
import urllib.request
import urllib.error
from pathlib import Path

# ──────────────────────────────────────────────
# 配置
# ──────────────────────────────────────────────
API_KEY = "REDACTED_DEEPSEEK_KEY"
API_URL = "https://api.deepseek.com/v1/chat/completions"
OUT_FILE = Path(__file__).parent.parent / "src/data/words_network.json"
PROGRESS_FILE = Path(__file__).parent / "_word_network_progress.json"
BATCH_SIZE = 30
DELAY_SECONDS = 2  # 批次间隔

# ──────────────────────────────────────────────
# 完整词表（用户提供的576词 + PEP补充词）
# ──────────────────────────────────────────────
WORD_LIST = [
    # 一、COLOUR
    ("blue","蓝色（的）","colour","high"),
    ("green","绿色（的）","colour","high"),
    ("red","红色（的）","colour","high"),
    ("yellow","黄色（的）","colour","high"),
    ("orange","橙色（的）","colour","high"),
    ("purple","紫色（的）","colour","mid"),
    ("white","白色（的）","colour","high"),
    ("black","黑色（的）","colour","high"),
    ("brown","棕色（的）","colour","mid"),
    # 二、SCHOOL
    ("school","学校","school","high"),
    ("book","书","school","high"),
    ("chair","椅子","school","high"),
    ("class","班","school","high"),
    ("desk","书桌","school","high"),
    ("student","学生","school","high"),
    ("teacher","老师","school","high"),
    ("office","办公室","school","mid"),
    ("gym","体育馆","school","mid"),
    ("classroom","教室","school","high"),
    ("blackboard","黑板","school","mid"),
    ("school bus","校车","school","mid"),
    ("lights","灯","school","mid"),
    ("lesson","课","school","mid"),
    ("card","卡片","school","mid"),
    # 三、STATIONERY
    ("notebook","笔记本","stationery","high"),
    ("paper","纸","stationery","high"),
    ("pencil","铅笔","stationery","high"),
    ("pencil case","笔袋","stationery","mid"),
    ("pen","钢笔","stationery","high"),
    ("eraser","橡皮","stationery","high"),
    ("ruler","尺子","stationery","high"),
    ("marker","水彩笔","stationery","mid"),
    ("scissors","剪刀","stationery","mid"),
    ("envelope","信封","stationery","low"),
    ("stamp","邮票","stationery","low"),
    ("glue","胶水","stationery","mid"),
    # 四、NUMBERS
    ("number","数字","numbers","high"),
    ("zero","零","numbers","high"),
    ("one","一","numbers","high"),
    ("two","二","numbers","high"),
    ("three","三","numbers","high"),
    ("four","四","numbers","high"),
    ("five","五","numbers","high"),
    ("six","六","numbers","high"),
    ("seven","七","numbers","high"),
    ("eight","八","numbers","high"),
    ("nine","九","numbers","high"),
    ("ten","十","numbers","high"),
    ("eleven","十一","numbers","high"),
    ("twelve","十二","numbers","high"),
    ("thirteen","十三","numbers","mid"),
    ("fourteen","十四","numbers","mid"),
    ("fifteen","十五","numbers","mid"),
    ("sixteen","十六","numbers","mid"),
    ("seventeen","十七","numbers","mid"),
    ("eighteen","十八","numbers","mid"),
    ("nineteen","十九","numbers","mid"),
    ("twenty","二十","numbers","high"),
    ("thirty","三十","numbers","mid"),
    ("forty","四十","numbers","mid"),
    ("fifty","五十","numbers","mid"),
    ("sixty","六十","numbers","mid"),
    ("seventy","七十","numbers","mid"),
    ("eighty","八十","numbers","mid"),
    ("ninety","九十","numbers","mid"),
    ("hundred","百","numbers","mid"),
    ("thousand","千","numbers","mid"),
    ("first","第一","numbers","high"),
    ("second","第二","numbers","high"),
    ("third","第三","numbers","high"),
    ("fourth","第四","numbers","mid"),
    ("fifth","第五","numbers","mid"),
    ("sixth","第六","numbers","mid"),
    ("seventh","第七","numbers","mid"),
    ("eighth","第八","numbers","mid"),
    ("ninth","第九","numbers","mid"),
    ("tenth","第十","numbers","mid"),
    # 五、FAMILY
    ("family","家庭","family","high"),
    ("father","爸爸","family","high"),
    ("dad","爸爸","family","high"),
    ("mother","妈妈","family","high"),
    ("mum","妈妈","family","high"),
    ("aunt","姨/姑妈","family","mid"),
    ("uncle","叔/舅舅","family","mid"),
    ("cousin","表兄妹","family","mid"),
    ("nephew","侄子","family","low"),
    ("niece","侄女","family","low"),
    ("brother","哥/弟","family","high"),
    ("sister","姐/妹","family","high"),
    ("daughter","女儿","family","mid"),
    ("son","儿子","family","mid"),
    ("grandpa","爷爷/外公","family","high"),
    ("grandma","奶奶/外婆","family","high"),
    # 六、BODY PARTS
    ("body","身体","body","high"),
    ("arm","胳膊","body","high"),
    ("ear","耳朵","body","high"),
    ("eye","眼睛","body","high"),
    ("face","脸","body","high"),
    ("foot","脚","body","high"),
    ("hand","手","body","high"),
    ("head","头","body","high"),
    ("leg","腿","body","high"),
    ("mouth","嘴","body","high"),
    ("nose","鼻子","body","high"),
    ("elbow","胳膊肘","body","mid"),
    ("finger","手指","body","high"),
    ("shoulder","肩膀","body","mid"),
    ("stomach","肚子","body","mid"),
    ("knee","膝盖","body","mid"),
    ("toe","脚趾","body","mid"),
    ("ankle","脚踝","body","mid"),
    ("wrist","手腕","body","mid"),
    # 七、HOME
    ("home","家","home","high"),
    ("bathroom","卫生间","home","mid"),
    ("bed","床","home","high"),
    ("bedroom","卧室","home","high"),
    ("kitchen","厨房","home","high"),
    ("living room","客厅","home","high"),
    ("room","房间","home","high"),
    ("house","房子","home","high"),
    ("door","门","home","high"),
    ("window","窗户","home","high"),
    ("bathtub","浴缸","home","low"),
    ("ceiling","天花板","home","low"),
    ("dish","盘子","home","mid"),
    ("refrigerator","电冰箱","home","mid"),
    ("sink","洗涤槽","home","low"),
    ("stove","炉灶","home","low"),
    ("toilet","厕所","home","mid"),
    ("wall","墙","home","mid"),
    ("lamp","灯","home","mid"),
    ("closet","橱柜","home","low"),
    ("dresser","化妆台","home","low"),
    ("shower","淋浴","home","mid"),
    ("couch","长沙发","home","low"),
    ("towel","毛巾","home","mid"),
    # 八、CLOTHES
    ("blouse","女衬衫","clothes","low"),
    ("clothes","衣服","clothes","high"),
    ("dress","连衣裙","clothes","high"),
    ("pants","裤子","clothes","high"),
    ("shirt","衬衣","clothes","high"),
    ("shorts","短裤","clothes","high"),
    ("skirt","短裙","clothes","high"),
    ("T-shirt","T恤衫","clothes","high"),
    ("socks","袜子","clothes","high"),
    ("pajamas","睡衣裤","clothes","mid"),
    ("gloves","手套","clothes","mid"),
    ("boots","靴子","clothes","mid"),
    ("jacket","夹克","clothes","mid"),
    ("scarf","围巾","clothes","mid"),
    ("sweater","毛衣","clothes","mid"),
    ("swimsuit","游泳衣","clothes","mid"),
    ("sandals","凉鞋","clothes","mid"),
    ("mittens","连指手套","clothes","low"),
    # 九、TIME
    ("year","年","time","high"),
    ("time","时间","time","high"),
    ("day","天","time","high"),
    ("week","周","time","high"),
    ("morning","早上","time","high"),
    ("noon","中午","time","high"),
    ("evening","晚上","time","high"),
    ("night","夜晚","time","high"),
    ("today","今天","time","high"),
    ("tomorrow","明天","time","high"),
    ("birthday","生日","time","high"),
    ("holiday","假日","time","mid"),
    ("Christmas","圣诞节","time","mid"),
    # 十、DAYS
    ("Monday","星期一","days","high"),
    ("Tuesday","星期二","days","high"),
    ("Wednesday","星期三","days","high"),
    ("Thursday","星期四","days","high"),
    ("Friday","星期五","days","high"),
    ("Saturday","星期六","days","high"),
    ("Sunday","星期日","days","high"),
    # 十一、MONTHS
    ("January","一月","months","high"),
    ("February","二月","months","high"),
    ("March","三月","months","high"),
    ("April","四月","months","high"),
    ("May","五月","months","high"),
    ("June","六月","months","high"),
    ("July","七月","months","high"),
    ("August","八月","months","high"),
    ("September","九月","months","high"),
    ("October","十月","months","high"),
    ("November","十一月","months","high"),
    ("December","十二月","months","high"),
    # 十二、SEASONS
    ("season","季节","seasons","high"),
    ("spring","春天","seasons","high"),
    ("summer","夏天","seasons","high"),
    ("fall","秋天","seasons","high"),
    ("winter","冬天","seasons","high"),
    # 十三、PEOPLE
    ("people","人们","people","high"),
    ("boy","男孩","people","high"),
    ("girl","女孩","people","high"),
    ("doctor","医生","people","high"),
    ("friend","朋友","people","high"),
    ("neighbor","邻居","people","mid"),
    ("waiter","男服务员","people","mid"),
    ("waitress","女服务员","people","mid"),
    ("actor","男演员","people","mid"),
    ("actress","女演员","people","mid"),
    ("baby","婴儿","people","high"),
    ("child","孩子","people","high"),
    ("man","男人","people","high"),
    ("woman","女人","people","high"),
    ("singer","歌手","people","mid"),
    # 十四、SHAPES
    ("shape","形状","shapes","high"),
    ("circle","圆圈","shapes","high"),
    ("line","直线","shapes","high"),
    ("rectangle","长方形","shapes","mid"),
    ("square","方形","shapes","high"),
    ("triangle","三角形","shapes","high"),
    # 十五、FOOD
    ("breakfast","早饭","food","high"),
    ("lunch","午饭","food","high"),
    ("supper","晚饭","food","high"),
    ("meat","肉","food","high"),
    ("pork","猪肉","food","mid"),
    ("chicken","鸡肉","food","high"),
    ("beef","牛肉","food","mid"),
    ("lamb","羔羊肉","food","mid"),
    ("cookies","饼干","food","mid"),
    ("flour","面粉","food","low"),
    ("sugar","糖","food","mid"),
    ("egg","鸡蛋","food","high"),
    ("snack","零食","food","mid"),
    ("oil","油","food","low"),
    ("salt","盐","food","low"),
    # 十六、NATURE
    ("sky","天空","nature","high"),
    ("cloud","云","nature","high"),
    ("beach","海滩","nature","mid"),
    ("boat","船","nature","high"),
    ("lake","湖","nature","mid"),
    ("ocean","海洋","nature","mid"),
    ("wind","风","nature","mid"),
    ("mountain","山","nature","mid"),
    ("rock","岩石","nature","mid"),
    ("tree","树","nature","high"),
    ("river","河","nature","mid"),
    ("grass","草","nature","high"),
    ("flower","花","nature","high"),
    ("leaves","树叶","nature","mid"),
    ("farm","农场","nature","mid"),
    ("field","田地","nature","mid"),
    ("mud","泥","nature","low"),
    ("pond","池塘","nature","low"),
    ("sand","沙","nature","mid"),
    ("rose","玫瑰","nature","mid"),
    ("star","星星","nature","high"),
    ("sun","太阳","nature","high"),
    ("snow","雪","nature","high"),
    ("rain","雨","nature","high"),
    # 十七、PLACE
    ("corner","角落","place","mid"),
    ("park","公园","place","high"),
    ("playground","游乐场","place","high"),
    ("shop","商店","place","high"),
    ("world","世界","place","mid"),
    ("city","城市","place","mid"),
    ("hall","大厅","place","mid"),
    ("hotel","饭店","place","mid"),
    ("street","街道","place","mid"),
    ("restaurant","餐馆","place","mid"),
    ("market","市场","place","mid"),
    ("mall","商业街","place","mid"),
    # 十八、OTHER NOUNS
    ("fun","乐趣","misc","high"),
    ("letter","信","misc","mid"),
    ("song","歌曲","misc","high"),
    ("umbrella","雨伞","misc","mid"),
    ("thing","东西","misc","high"),
    ("card","卡片","misc","mid"),
    ("ticket","车票","misc","mid"),
    ("trip","旅行","misc","mid"),
    ("party","聚会","misc","high"),
    ("story","故事","misc","high"),
    ("surprise","意外惊喜","misc","mid"),
    ("car","小汽车","misc","high"),
    ("computer","计算机","misc","high"),
    ("toy","玩具","misc","high"),
    ("camera","照相机","misc","mid"),
    ("picture","照片","misc","high"),
    ("postcard","明信片","misc","low"),
    ("gift","礼物","misc","high"),
    ("movie","电影","misc","high"),
    ("music","音乐","misc","high"),
    ("snowball","雪球","misc","mid"),
    ("snowman","雪人","misc","mid"),
    ("violin","小提琴","misc","mid"),
    # 十九、ADJECTIVES
    ("cold","冷的","adjective","high"),
    ("happy","高兴的","adjective","high"),
    ("hot","热的","adjective","high"),
    ("hungry","饿的","adjective","high"),
    ("sad","伤心的","adjective","high"),
    ("thirsty","渴的","adjective","mid"),
    ("old","老的","adjective","high"),
    ("young","年轻的","adjective","high"),
    ("delicious","好吃的","adjective","mid"),
    ("favourite","最喜爱的","adjective","mid"),
    ("lovely","可爱的","adjective","mid"),
    ("new","新的","adjective","high"),
    ("nice","好的","adjective","high"),
    ("late","晚的","adjective","high"),
    ("short","矮的","adjective","high"),
    ("tall","高的","adjective","high"),
    ("right","正确的","adjective","high"),
    ("wrong","错误的","adjective","high"),
    ("bad","坏的","adjective","high"),
    ("beautiful","漂亮的","adjective","high"),
    ("best","最好的","adjective","high"),
    ("better","更好的","adjective","high"),
    ("special","特别的","adjective","mid"),
    ("easy","容易的","adjective","high"),
    ("fast","快的","adjective","high"),
    ("hard","难的","adjective","high"),
    ("loud","响亮的","adjective","mid"),
    ("quick","快速的","adjective","mid"),
    ("quiet","安静的","adjective","high"),
    ("slow","缓慢的","adjective","high"),
    # 二十、ADVERBS
    ("once","一次","adverb","mid"),
    ("well","好地","adverb","high"),
    ("together","一起","adverb","high"),
    ("never","从来没有","adverb","high"),
    ("sometimes","有时","adverb","high"),
    ("always","总是","adverb","high"),
    ("early","早地","adverb","high"),
    ("finally","最后","adverb","mid"),
    ("soon","不久","adverb","mid"),
    ("then","然后","adverb","high"),
    ("very","非常","adverb","high"),
    # 二十一、WEATHER
    ("warm","温暖的","weather","high"),
    ("snowy","下雪的","weather","mid"),
    ("rainy","下雨的","weather","mid"),
    ("sunny","晴朗的","weather","high"),
    ("windy","刮风的","weather","mid"),
    ("cloudy","多云的","weather","mid"),
    # 二十二、VERBS
    ("draw","画","verb","high"),
    ("hear","听见","verb","high"),
    ("know","知道","verb","high"),
    ("show","给…看","verb","high"),
    ("walk","走","verb","high"),
    ("listen","听","verb","high"),
    ("meet","遇到","verb","high"),
    ("miss","想念","verb","mid"),
    ("need","需要","verb","high"),
    ("put","放","verb","high"),
    ("smell","闻","verb","mid"),
    ("take","拿","verb","high"),
    ("write","写","verb","high"),
    ("wear","穿","verb","high"),
    ("eat","吃","verb","high"),
    ("find","找到","verb","high"),
    ("go","去","verb","high"),
    ("help","帮助","verb","high"),
    ("learn","学习","verb","high"),
    ("like","喜欢","verb","high"),
    ("love","爱","verb","high"),
    ("play","玩","verb","high"),
    ("see","看见","verb","high"),
    ("sleep","睡觉","verb","high"),
    ("read","读","verb","high"),
    ("buy","买","verb","high"),
    ("come","来","verb","high"),
    ("hurt","伤","verb","mid"),
    ("jump","跳","verb","high"),
    ("leave","离开","verb","high"),
    ("look","看","verb","high"),
    ("run","跑","verb","high"),
    ("send","寄","verb","mid"),
    ("sit","坐","verb","high"),
    ("stand","站","verb","high"),
    ("bring","带来","verb","high"),
    ("cook","做饭","verb","high"),
    ("fall","摔倒","verb","high"),
    ("give","给","verb","high"),
    ("invite","邀请","verb","mid"),
    ("open","打开","verb","high"),
    ("skate","滑冰","verb","mid"),
    ("ski","滑雪","verb","mid"),
    ("think","想","verb","high"),
    ("visit","参观","verb","mid"),
    ("wash","洗","verb","high"),
    ("call","打电话","verb","high"),
    ("carry","搬运","verb","mid"),
    ("fly","飞","verb","high"),
    ("forget","忘记","verb","high"),
    ("lie","躺","verb","mid"),
    ("swim","游泳","verb","high"),
    ("remember","记得","verb","mid"),
    ("tell","告诉","verb","high"),
    ("wake","叫醒","verb","mid"),
    ("clean","打扫","verb","high"),
    ("teach","教","verb","high"),
    ("watch","观看","verb","high"),
    # 二十三、DIRECTIONS
    ("beside","在旁边","preposition","mid"),
    ("above","在上面","preposition","mid"),
    ("below","在下面","preposition","mid"),
    ("under","在下面","preposition","high"),
    ("near","附近","preposition","high"),
    ("inside","里面","preposition","mid"),
    ("outside","外面","preposition","mid"),
    ("behind","在后面","preposition","high"),
    ("left","左边","direction","high"),
    ("right","右边","direction","high"),
    ("east","东","direction","mid"),
    ("south","南","direction","mid"),
    ("west","西","direction","mid"),
    ("north","北","direction","mid"),
    # 二十五、ANIMALS
    ("chicken","鸡","animal","high"),
    ("cow","奶牛","animal","high"),
    ("duck","鸭子","animal","high"),
    ("pig","猪","animal","high"),
    ("cat","猫","animal","high"),
    ("dog","狗","animal","high"),
    ("sheep","绵羊","animal","high"),
    ("bird","鸟","animal","high"),
    ("rabbit","兔子","animal","high"),
    ("horse","马","animal","high"),
    ("snake","蛇","animal","mid"),
    ("wing","翅膀","animal","mid"),
    ("tail","尾巴","animal","mid"),
    ("lion","狮子","animal","mid"),
    ("tiger","老虎","animal","high"),
    ("elephant","大象","animal","high"),
    ("kangaroo","袋鼠","animal","mid"),
    ("monkey","猴子","animal","high"),
    ("wolf","狼","animal","mid"),
    ("camel","骆驼","animal","mid"),
    ("giraffe","长颈鹿","animal","mid"),
    ("panda","熊猫","animal","high"),
    ("zebra","斑马","animal","mid"),
    ("dragon","龙","animal","mid"),
    # 二十六、TRANSPORT
    ("bike","自行车","transport","high"),
    ("car","小汽车","transport","high"),
    ("truck","大卡车","transport","mid"),
    ("bus","公共汽车","transport","high"),
    ("taxi","出租车","transport","high"),
    ("airplane","飞机","transport","high"),
    ("train","火车","transport","high"),
    ("ship","轮船","transport","mid"),
    ("bell","铃铛","misc","mid"),
    # PEP补充词（运动/食物/水果/常用）
    ("basketball","篮球","sports","high"),
    ("football","足球","sports","high"),
    ("volleyball","排球","sports","mid"),
    ("baseball","棒球","sports","mid"),
    ("tennis","网球","sports","mid"),
    ("ping-pong","乒乓球","sports","high"),
    ("swimming","游泳","sports","high"),
    ("running","跑步","sports","high"),
    ("ball","球","sports","high"),
    ("sport","运动","sports","high"),
    ("apple","苹果","fruit","high"),
    ("banana","香蕉","fruit","high"),
    ("orange","橙子","fruit","high"),
    ("grape","葡萄","fruit","mid"),
    ("watermelon","西瓜","fruit","high"),
    ("strawberry","草莓","fruit","mid"),
    ("peach","桃子","fruit","mid"),
    ("pear","梨","fruit","mid"),
    ("rice","米饭","food","high"),
    ("noodles","面条","food","high"),
    ("bread","面包","food","high"),
    ("milk","牛奶","food","high"),
    ("water","水","food","high"),
    ("juice","果汁","food","high"),
    ("tea","茶","food","high"),
    ("coffee","咖啡","food","mid"),
    ("pizza","披萨","food","mid"),
    ("hamburger","汉堡","food","mid"),
    ("cake","蛋糕","food","high"),
    ("ice cream","冰激凌","food","high"),
    ("chocolate","巧克力","food","mid"),
    ("yes","是","response","high"),
    ("no","不","response","high"),
    ("please","请","response","high"),
    ("thank you","谢谢","response","high"),
    ("sorry","对不起","response","high"),
    ("hello","你好","greeting","high"),
    ("hi","你好","greeting","high"),
    ("goodbye","再见","greeting","high"),
    ("bye","再见","greeting","high"),
    ("good","好的","adjective","high"),
    ("great","很好的","adjective","high"),
    ("little","小的","adjective","high"),
    ("big","大的","adjective","high"),
    ("small","小的","adjective","high"),
    ("long","长的","adjective","high"),
    ("many","许多","adjective","high"),
    ("much","很多","adjective","high"),
    ("more","更多","adjective","high"),
    ("less","更少","adjective","mid"),
    ("same","相同的","adjective","mid"),
    ("different","不同的","adjective","mid"),
    ("colour","颜色","colour","high"),
    ("size","尺寸","adjective","mid"),
    ("have","有","verb","high"),
    ("make","制作","verb","high"),
    ("want","想要","verb","high"),
    ("get","得到","verb","high"),
    ("use","使用","verb","high"),
    ("say","说","verb","high"),
    ("ask","问","verb","high"),
    ("answer","回答","verb","high"),
    ("talk","说话","verb","high"),
    ("speak","说","verb","high"),
    ("name","名字","misc","high"),
    ("age","年龄","misc","high"),
    ("address","地址","misc","mid"),
    ("phone","电话","misc","high"),
    ("weather","天气","weather","high"),
    ("temperature","温度","weather","mid"),
    ("map","地图","misc","mid"),
    ("globe","地球仪","misc","mid"),
    ("earth","地球","nature","mid"),
    ("country","国家","place","mid"),
    ("China","中国","place","high"),
    ("English","英语","school","high"),
    ("Chinese","中文","school","high"),
    # ── PEP扩充：蔬菜 vegetable ──
    ("vegetable","蔬菜","food","high"),
    ("carrot","胡萝卜","food","high"),
    ("potato","土豆","food","high"),
    ("tomato","番茄","food","high"),
    ("corn","玉米","food","high"),
    ("bean","豆子","food","mid"),
    ("pea","豌豆","food","mid"),
    ("mushroom","蘑菇","food","mid"),
    ("cucumber","黄瓜","food","mid"),
    ("cabbage","白菜","food","mid"),
    ("onion","洋葱","food","mid"),
    ("garlic","大蒜","food","low"),
    ("pepper","辣椒","food","mid"),
    ("soup","汤","food","high"),
    ("salad","沙拉","food","mid"),
    ("sandwich","三明治","food","mid"),
    ("hot dog","热狗","food","mid"),
    ("popcorn","爆米花","food","mid"),
    ("candy","糖果","food","high"),
    ("honey","蜂蜜","food","mid"),
    ("butter","黄油","food","mid"),
    ("cheese","奶酪","food","mid"),
    ("yogurt","酸奶","food","mid"),
    ("lemon","柠檬","fruit","mid"),
    ("mango","芒果","fruit","mid"),
    ("cherry","樱桃","fruit","mid"),
    ("melon","哈密瓜","fruit","mid"),
    ("coconut","椰子","fruit","low"),
    # ── 更多动物 ──
    ("fish","鱼","animal","high"),
    ("frog","青蛙","animal","high"),
    ("butterfly","蝴蝶","animal","mid"),
    ("bee","蜜蜂","animal","high"),
    ("ant","蚂蚁","animal","high"),
    ("spider","蜘蛛","animal","mid"),
    ("parrot","鹦鹉","animal","mid"),
    ("swan","天鹅","animal","mid"),
    ("eagle","老鹰","animal","mid"),
    ("owl","猫头鹰","animal","mid"),
    ("penguin","企鹅","animal","high"),
    ("dolphin","海豚","animal","mid"),
    ("shark","鲨鱼","animal","mid"),
    ("whale","鲸鱼","animal","mid"),
    ("bear","熊","animal","high"),
    ("fox","狐狸","animal","high"),
    ("deer","鹿","animal","mid"),
    ("squirrel","松鼠","animal","mid"),
    ("hamster","仓鼠","animal","mid"),
    ("turtle","乌龟","animal","mid"),
    ("crab","螃蟹","animal","mid"),
    ("shrimp","虾","animal","mid"),
    # ── 学校/课程 ──
    ("subject","科目","school","high"),
    ("math","数学","school","high"),
    ("science","科学","school","high"),
    ("art","美术","school","high"),
    ("music","音乐","school","high"),
    ("PE","体育","school","high"),
    ("history","历史","school","mid"),
    ("geography","地理","school","mid"),
    ("library","图书馆","place","high"),
    ("textbook","教科书","school","mid"),
    ("dictionary","字典","school","mid"),
    ("chalk","粉笔","stationery","mid"),
    ("exam","考试","school","high"),
    ("test","测试","school","high"),
    ("grade","成绩/年级","school","high"),
    ("score","分数","school","mid"),
    ("homework","家庭作业","school","high"),
    ("project","项目","school","mid"),
    ("practice","练习","school","mid"),
    ("study","学习","school","high"),
    ("understand","理解","school","mid"),
    ("question","问题","school","high"),
    ("mistake","错误","school","mid"),
    ("correct","正确的","adjective","high"),
    # ── 健康/身体 ──
    ("sick","生病的","health","high"),
    ("healthy","健康的","health","high"),
    ("medicine","药","health","mid"),
    ("hospital","医院","place","high"),
    ("nurse","护士","people","high"),
    ("toothache","牙痛","health","mid"),
    ("headache","头痛","health","mid"),
    ("fever","发烧","health","mid"),
    ("cold","感冒","health","high"),
    ("cough","咳嗽","health","mid"),
    ("exercise","锻炼","health","high"),
    ("rest","休息","health","high"),
    ("wash","洗","verb","high"),
    ("brush","刷","verb","high"),
    ("teeth","牙齿","body","high"),
    ("hair","头发","body","high"),
    ("skin","皮肤","body","mid"),
    ("bone","骨头","body","mid"),
    ("heart","心脏/心","body","high"),
    ("blood","血","body","mid"),
    ("breath","呼吸","body","mid"),
    ("weight","体重","body","mid"),
    ("height","身高","body","mid"),
    # ── 家居/房间 ──
    ("sofa","沙发","home","high"),
    ("carpet","地毯","home","mid"),
    ("curtain","窗帘","home","mid"),
    ("pillow","枕头","home","mid"),
    ("blanket","毯子","home","mid"),
    ("mirror","镜子","home","mid"),
    ("shelf","架子","home","mid"),
    ("box","盒子","home","high"),
    ("bag","包","misc","high"),
    ("basket","篮子","misc","high"),
    ("bottle","瓶子","misc","high"),
    ("cup","杯子","home","high"),
    ("glass","玻璃杯","home","high"),
    ("plate","盘子","home","high"),
    ("bowl","碗","home","high"),
    ("fork","叉子","home","high"),
    ("knife","刀","home","high"),
    ("spoon","勺子","home","high"),
    ("pot","锅","home","mid"),
    ("pan","平底锅","home","mid"),
    # ── 自然/环境 ──
    ("forest","森林","nature","mid"),
    ("jungle","丛林","nature","mid"),
    ("desert","沙漠","nature","mid"),
    ("island","岛","nature","mid"),
    ("valley","山谷","nature","low"),
    ("waterfall","瀑布","nature","mid"),
    ("cave","山洞","nature","mid"),
    ("rainbow","彩虹","nature","high"),
    ("thunder","雷","nature","mid"),
    ("lightning","闪电","nature","mid"),
    ("storm","暴风雨","nature","mid"),
    ("fog","雾","nature","mid"),
    ("ice","冰","nature","high"),
    ("fire","火","nature","high"),
    ("smoke","烟","nature","mid"),
    ("air","空气","nature","high"),
    ("ground","地面","nature","high"),
    ("soil","土壤","nature","mid"),
    ("seed","种子","nature","mid"),
    ("root","根","nature","mid"),
    ("branch","树枝","nature","mid"),
    ("leaf","叶子","nature","high"),
    ("fruit","水果","fruit","high"),
    ("forest","森林","nature","mid"),
    ("moon","月亮","nature","high"),
    ("planet","行星","nature","mid"),
    ("space","太空","nature","mid"),
    # ── 地点/场所 ──
    ("zoo","动物园","place","high"),
    ("museum","博物馆","place","mid"),
    ("cinema","电影院","place","mid"),
    ("bank","银行","place","mid"),
    ("post office","邮局","place","mid"),
    ("fire station","消防站","place","mid"),
    ("police station","警察局","place","mid"),
    ("airport","机场","place","high"),
    ("station","车站","place","high"),
    ("harbour","港口","place","low"),
    ("town","城镇","place","mid"),
    ("village","村庄","place","mid"),
    ("farm","农场","place","mid"),
    ("factory","工厂","place","mid"),
    ("church","教堂","place","low"),
    # ── 情感/性格 ──
    ("angry","生气的","emotion","high"),
    ("excited","兴奋的","emotion","high"),
    ("worried","担心的","emotion","mid"),
    ("surprised","惊讶的","emotion","mid"),
    ("scared","害怕的","emotion","high"),
    ("bored","无聊的","emotion","mid"),
    ("tired","疲倦的","emotion","high"),
    ("proud","骄傲的","emotion","mid"),
    ("nervous","紧张的","emotion","mid"),
    ("calm","平静的","emotion","mid"),
    ("kind","友好的","adjective","high"),
    ("brave","勇敢的","adjective","mid"),
    ("clever","聪明的","adjective","high"),
    ("lazy","懒的","adjective","mid"),
    ("honest","诚实的","adjective","mid"),
    ("polite","礼貌的","adjective","mid"),
    ("shy","害羞的","adjective","mid"),
    ("funny","有趣的","adjective","high"),
    ("serious","严肃的","adjective","mid"),
    ("strong","强壮的","adjective","high"),
    ("weak","虚弱的","adjective","mid"),
    # ── 动词扩充 ──
    ("cut","切","verb","high"),
    ("push","推","verb","high"),
    ("pull","拉","verb","high"),
    ("throw","扔","verb","high"),
    ("catch","接住","verb","high"),
    ("kick","踢","verb","high"),
    ("hit","打","verb","high"),
    ("pour","倒","verb","mid"),
    ("mix","混合","verb","mid"),
    ("bake","烤","verb","mid"),
    ("grow","生长","verb","high"),
    ("plant","种植","verb","high"),
    ("water","浇水","verb","high"),
    ("pick","摘","verb","mid"),
    ("dig","挖","verb","mid"),
    ("build","建造","verb","high"),
    ("fix","修理","verb","mid"),
    ("break","打破","verb","high"),
    ("drop","掉落","verb","high"),
    ("share","分享","verb","high"),
    ("save","节省/救","verb","mid"),
    ("try","尝试","verb","high"),
    ("win","赢","verb","high"),
    ("lose","输/丢失","verb","high"),
    ("start","开始","verb","high"),
    ("finish","完成","verb","high"),
    ("stop","停止","verb","high"),
    ("wait","等待","verb","high"),
    ("change","改变","verb","high"),
    ("return","返回","verb","mid"),
    ("choose","选择","verb","mid"),
    ("follow","跟随","verb","mid"),
    ("join","加入","verb","mid"),
    ("enjoy","享受","verb","high"),
    ("hope","希望","verb","high"),
    ("wish","祝愿","verb","high"),
    ("wonder","想知道","verb","mid"),
    ("laugh","笑","verb","high"),
    ("cry","哭","verb","high"),
    ("smile","微笑","verb","high"),
    ("shout","喊叫","verb","mid"),
    ("wave","挥手","verb","mid"),
    ("nod","点头","verb","mid"),
    ("shake","摇","verb","mid"),
    ("touch","触摸","verb","high"),
    ("hold","握住","verb","high"),
    ("turn","转","verb","high"),
    ("pass","通过/传递","verb","high"),
    ("practice","练习","verb","high"),
    ("count","数数","verb","high"),
    ("measure","测量","verb","mid"),
    # ── 形容词扩充 ──
    ("dirty","脏的","adjective","high"),
    ("clean","干净的","adjective","high"),
    ("dry","干的","adjective","high"),
    ("wet","湿的","adjective","high"),
    ("light","轻的/明亮的","adjective","high"),
    ("heavy","重的","adjective","high"),
    ("thick","厚的","adjective","mid"),
    ("thin","薄的/瘦的","adjective","high"),
    ("wide","宽的","adjective","mid"),
    ("narrow","窄的","adjective","mid"),
    ("far","远的","adjective","high"),
    ("cheap","便宜的","adjective","mid"),
    ("expensive","贵的","adjective","mid"),
    ("free","免费的/自由的","adjective","mid"),
    ("busy","忙的","adjective","high"),
    ("full","满的","adjective","high"),
    ("empty","空的","adjective","high"),
    ("flat","平的","adjective","mid"),
    ("round","圆的","adjective","high"),
    ("sharp","锋利的","adjective","mid"),
    ("smooth","光滑的","adjective","mid"),
    ("rough","粗糙的","adjective","mid"),
    ("soft","软的","adjective","high"),
    ("dark","黑暗的","adjective","high"),
    ("bright","明亮的","adjective","high"),
    ("loud","大声的","adjective","mid"),
    ("low","低的","adjective","high"),
    ("high","高的","adjective","high"),
    ("deep","深的","adjective","mid"),
    ("wide","宽的","adjective","mid"),
    ("strange","奇怪的","adjective","mid"),
    ("lucky","幸运的","adjective","mid"),
    ("popular","受欢迎的","adjective","mid"),
    ("important","重要的","adjective","high"),
    ("interesting","有趣的","adjective","high"),
    ("useful","有用的","adjective","mid"),
    ("safe","安全的","adjective","high"),
    ("dangerous","危险的","adjective","mid"),
    # ── 科技/现代 ──
    ("internet","互联网","technology","mid"),
    ("website","网站","technology","mid"),
    ("keyboard","键盘","technology","mid"),
    ("mouse","鼠标","technology","high"),
    ("screen","屏幕","technology","high"),
    ("tablet","平板","technology","mid"),
    ("video","视频","technology","high"),
    ("photo","照片","technology","high"),
    ("robot","机器人","technology","mid"),
    ("program","程序","technology","low"),
    ("app","应用","technology","mid"),
    ("message","消息","technology","high"),
    ("call","通话","technology","high"),
    ("download","下载","technology","low"),
    # ── 时间副词 ──
    ("hour","小时","time","high"),
    ("minute","分钟","time","high"),
    ("second","秒","time","high"),
    ("ago","以前","time","high"),
    ("later","以后","time","high"),
    ("before","在...之前","time","high"),
    ("after","在...之后","time","high"),
    ("during","在...期间","time","mid"),
    ("yesterday","昨天","time","high"),
    ("last","上一个","time","high"),
    ("next","下一个","time","high"),
    ("still","还；仍然","adverb","mid"),
    ("already","已经","adverb","mid"),
    ("just","刚刚","adverb","high"),
    ("yet","还没","adverb","mid"),
    ("again","再次","adverb","high"),
    ("also","也","adverb","high"),
    ("too","也","adverb","high"),
    ("only","只","adverb","high"),
    ("really","真的","adverb","high"),
    ("probably","可能","adverb","mid"),
    ("maybe","也许","adverb","high"),
    # ── 常用名词 ──
    ("idea","想法","misc","high"),
    ("way","方法/路","misc","high"),
    ("part","部分","misc","high"),
    ("side","侧面","misc","mid"),
    ("kind","种类","misc","high"),
    ("type","类型","misc","mid"),
    ("list","清单","misc","mid"),
    ("word","单词","misc","high"),
    ("sentence","句子","misc","high"),
    ("paragraph","段落","misc","low"),
    ("page","页","misc","high"),
    ("chapter","章节","misc","low"),
    ("sound","声音","misc","high"),
    ("voice","声音","misc","high"),
    ("noise","噪音","misc","mid"),
    ("light","光","nature","high"),
    ("colour","颜色","colour","high"),
    ("weight","重量","misc","mid"),
    ("size","大小","misc","mid"),
    ("age","年龄","misc","high"),
    ("price","价格","misc","mid"),
    ("news","新闻","misc","mid"),
    ("information","信息","misc","mid"),
    ("answer","答案","misc","high"),
    ("problem","问题","misc","high"),
    ("result","结果","misc","mid"),
    ("reason","原因","misc","mid"),
    ("example","例子","misc","mid"),
    ("plan","计划","misc","mid"),
    ("rule","规则","misc","mid"),
    ("team","队伍","sports","high"),
    ("game","游戏/比赛","sports","high"),
    ("match","比赛","sports","mid"),
    ("winner","赢家","sports","mid"),
    ("player","选手","sports","high"),
    ("race","比赛","sports","mid"),
    ("court","球场","sports","mid"),
    ("field","操场","sports","mid"),
    ("score","得分","sports","mid"),
    ("goal","目标/进球","sports","high"),
    # ── 交通扩充 ──
    ("road","道路","transport","high"),
    ("bridge","桥","transport","mid"),
    ("tunnel","隧道","transport","mid"),
    ("traffic","交通","transport","mid"),
    ("driver","司机","people","mid"),
    ("passenger","乘客","people","mid"),
    ("pilot","飞行员","people","mid"),
    ("captain","船长/队长","people","mid"),
    ("subway","地铁","transport","high"),
    ("helicopter","直升机","transport","mid"),
    ("rocket","火箭","transport","mid"),
    # ── 职业/人物 ──
    ("police","警察","people","high"),
    ("firefighter","消防员","people","high"),
    ("farmer","农民","people","high"),
    ("scientist","科学家","people","mid"),
    ("engineer","工程师","people","mid"),
    ("artist","艺术家","people","mid"),
    ("writer","作家","people","mid"),
    ("cook","厨师","people","high"),
    ("baker","面包师","people","mid"),
    ("librarian","图书管理员","people","low"),
    ("reporter","记者","people","mid"),
    # ── 节日/文化 ──
    ("festival","节日","culture","high"),
    ("Halloween","万圣节","culture","mid"),
    ("Easter","复活节","culture","low"),
    ("Thanksgiving","感恩节","culture","low"),
    ("New Year","新年","culture","high"),
    ("tradition","传统","culture","low"),
    ("culture","文化","culture","mid"),
    ("flag","旗帜","culture","mid"),
    ("poem","诗","culture","mid"),
    ("fairy tale","童话","culture","mid"),
    # ── 数学/形状扩充 ──
    ("add","加","math","high"),
    ("subtract","减","math","mid"),
    ("multiply","乘","math","mid"),
    ("divide","除","math","mid"),
    ("equal","等于","math","high"),
    ("half","一半","math","high"),
    ("quarter","四分之一","math","mid"),
    ("total","总计","math","mid"),
    ("average","平均","math","low"),
    ("angle","角度","math","mid"),
    ("length","长度","math","mid"),
    ("width","宽度","math","mid"),
    ("height","高度","math","mid"),
    ("area","面积","math","mid"),
    ("volume","体积","math","low"),
    ("oval","椭圆","shapes","mid"),
    ("star","星形","shapes","high"),
    ("diamond","菱形","shapes","mid"),
    ("cube","正方体","shapes","mid"),
    ("sphere","球体","shapes","mid"),
    ("cylinder","圆柱","shapes","low"),
    # ── 音乐/艺术 ──
    ("piano","钢琴","music","high"),
    ("guitar","吉他","music","high"),
    ("drum","鼓","music","high"),
    ("flute","长笛","music","mid"),
    ("trumpet","小号","music","low"),
    ("song","歌曲","music","high"),
    ("dance","舞蹈","music","high"),
    ("sing","唱歌","verb","high"),
    ("paint","画画","verb","high"),
    ("draw","画画","verb","high"),
    ("perform","表演","verb","mid"),
    ("concert","音乐会","music","mid"),
    ("stage","舞台","misc","mid"),
    ("audience","观众","misc","mid"),
]

# ──────────────────────────────────────────────
# 所有单词（仅词形），供 AI 约束联想范围
# ──────────────────────────────────────────────
ALL_WORDS = sorted(set(w for w, *_ in WORD_LIST))

def call_deepseek(prompt: str) -> str:
    payload = json.dumps({
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.3,
        "max_tokens": 4000,
    }).encode("utf-8")
    req = urllib.request.Request(
        API_URL,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {API_KEY}",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    return data["choices"][0]["message"]["content"]

def generate_batch(batch: list[tuple]) -> dict:
    """
    batch: list of (word, meaning, category, freq)
    返回 {word: {...}} 字典
    """
    words_str = "\n".join(f"- {w} ({m})" for w, m, *_ in batch)
    all_words_sample = ", ".join(ALL_WORDS[:200])  # 给AI一个词表范围样本

    prompt = f"""你是一位小学英语教学专家。请为以下单词生成联想学习网络，用于帮助中国小学生记忆英语单词。

**单词列表**（格式：单词 中文意思）：
{words_str}

**重要约束**：
1. associations（联想词）必须只从以下小学词汇范围内选取：{all_words_sample}...
2. confusables（形近/音近易混词）必须只从以上词汇范围内选取，选拼写相差1-2个字母的词
3. example_sentence 要简短（不超过8个单词），适合小学生

**输出格式**（严格JSON数组，不要有任何其他文字）：
[
  {{
    "word": "单词",
    "associations": ["相关词1", "相关词2", "相关词3"],
    "confusables": ["易混词1", "易混词2"],
    "example": "A simple example sentence.",
    "memory_tip": "简短的中文记忆口诀（10字以内）"
  }},
  ...
]

只输出JSON，不要解释，不要markdown代码块。"""

    raw = call_deepseek(prompt)
    # 清理可能的 markdown 包裹
    raw = re.sub(r"^```(?:json)?\s*", "", raw.strip())
    raw = re.sub(r"\s*```$", "", raw)
    raw = raw.strip()

    items = json.loads(raw)
    result = {}
    for item in items:
        if isinstance(item, dict) and "word" in item:
            result[item["word"].lower()] = item
    return result

def build_network():
    # 加载已有进度
    progress = {}
    if PROGRESS_FILE.exists():
        progress = json.loads(PROGRESS_FILE.read_text(encoding="utf-8"))
        print(f"✅ 已有进度：{len(progress)} 个词")

    # 分批处理
    pending = [(w, m, c, f) for w, m, c, f in WORD_LIST if w.lower() not in progress]
    print(f"📋 待处理：{len(pending)} 个词，已完成：{len(progress)} 个词")

    total_batches = (len(pending) + BATCH_SIZE - 1) // BATCH_SIZE
    for i in range(0, len(pending), BATCH_SIZE):
        batch = pending[i:i + BATCH_SIZE]
        batch_num = i // BATCH_SIZE + 1
        print(f"\n🔄 批次 {batch_num}/{total_batches}：处理 {[w for w,*_ in batch][:5]}...")

        try:
            result = generate_batch(batch)
            progress.update(result)
            # 保存进度
            PROGRESS_FILE.write_text(
                json.dumps(progress, ensure_ascii=False, indent=2),
                encoding="utf-8"
            )
            print(f"   ✓ 成功生成 {len(result)} 个词，累计 {len(progress)} 个")
        except Exception as e:
            print(f"   ✗ 批次失败：{e}")
            print("   ⏸ 等待5秒后继续...")
            time.sleep(5)
            continue

        if i + BATCH_SIZE < len(pending):
            time.sleep(DELAY_SECONDS)

    # 合并词表基础信息 + AI生成内容
    network = {}
    word_meta = {w.lower(): (m, c, f) for w, m, c, f in WORD_LIST}

    for w_lower, (meaning, category, freq) in word_meta.items():
        ai_data = progress.get(w_lower, {})
        # 寻找原始词的大小写形式
        original_word = next((w for w, *_ in WORD_LIST if w.lower() == w_lower), w_lower)

        # tier 分级
        tier = 1 if freq == "high" else (2 if freq == "mid" else 3)

        network[w_lower] = {
            "word": original_word,
            "meaning": meaning,
            "category": category,
            "tier": tier,
            "frequency": freq,
            "associations": ai_data.get("associations", []),
            "confusables": ai_data.get("confusables", []),
            "example": ai_data.get("example", ""),
            "memory_tip": ai_data.get("memory_tip", ""),
        }

    # 写出最终文件
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    output = {
        "meta": {
            "total": len(network),
            "generated_at": time.strftime("%Y-%m-%d"),
            "version": "primary_school_v1",
        },
        "words": network,
    }
    OUT_FILE.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\n🎉 完成！共 {len(network)} 个词 → {OUT_FILE}")

if __name__ == "__main__":
    build_network()
