#!/usr/bin/env python3
"""扩充词汇 Part 2: 形容词、名词、连词、时间词等"""
import json

INPUT = OUTPUT = "/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/words_network_j2.json"

def e(word, meaning, cat, tier, freq, assocs, confus, ex, tip):
    return {"word":word,"meaning":meaning,"category":cat,"tier":tier,"frequency":freq,
            "associations":assocs,"confusables":confus,"example":ex,"memory_tip":tip}

NEW = []

# === 重要形容词 (24) ===
NEW += [
e("standard","标准的","noun/adj",1,"high",
["normal","level","quality","rule"],["standing","stamp"],
"Meets international standard.","stand站+ard立在那→标准"),
e("normal","正常的；标准的","adjective_describe",1,"high",
["usual","regular","ordinary","standard"],["nominal","none"],
"Back normal now.","norm规范+al合规范"),
e("strange","奇怪的；陌生的","adjective_describe",1,"high",
["odd","weird","unfamiliar","unusual"],["strander","strand"],
"Sounds strange.","strange奇怪/陌生"),
e("simple","简单的","adjective_describe",1,"high",
["easy","basic","plain"],["simply","sample","similar"],
"Keep simple.","simple简单/simplify简化"),
e("complex","复杂的","adjective_describe",1,"medium",
["complicated","difficult","hard"],[],
"Problem quite complex.","com一起+plex编织→复杂"),
e("basic","基础的","adjective_describe",1,"high",
["fundamental","elementary","main"],["basis","basket"],
"Basic grammar essential.","base基础+ic"),
e("major","主要的；重大的","adj/noun",1,"high",
["main","important","large","big"],["mayor","make"],
"English major subject.","maj大+or较大"),
e("minor","较小的；次要的","adj/noun",1,"medium",
["small","less important","young"],["minus","mirror"],"Just minor problem.","min小+or较小"),
e("general","一般的；总的","adjective_describe",1,"high",
["common","overall","universal"],["generally","generate","genre"],
"General idea article?","gener产生+al总体"),
e("special","特别的","adjective_describe",1,"high",
["particular","unique","unusual"],["especially","specialist"],
"Today special day.","spec看+ial值得看→特别"),
e("especially","特别；尤其","adverb",1,"high",
["particularly","specially","mainly"],[],
"Fruits especially apples.","especial特+ly"),
e("certain","确定的；某些","adjective_describe",1,"high",
["sure","some","specific","definite"],["certainly","curtain"],
"For certain reasons cant go.","cert确定+ain"),
e("proper","适当的；正确的","adjective_describe",1,"high",
["correct","suitable","right"],["property","properly"],
"Wear proper clothes.","proper本身→适当"),
e("correct","正确的；改正","adj/verb",1,"high",
["right","accurate","fix","adjust"],["correction","collect"],
"Answer correct.","cor强调+rect笔直→正确"),
e("whole","整个的；全部的","adjective_quantity",1,"high",
["all","complete","entire","total"],["wholesome","whose"],
"Spent whole afternoon reading.","whole整个"),
e("single","单一的","adjective_quantity",1,"high",
["one","individual","alone","only"],["sing","sink"],
"Not single mistake allowed.","single单一"),
e("double","双重的；两倍","adj/verb",1,"medium",
["twofold","dual","two times"],["doubt","doubtful"],
"Double-click open file.","double双倍"),
e("empty","空的","adjective_describe",1,"high",
["nothing inside","hollow","blank"],["enemy","entry"],
"Bottle empty.","empty空瓶里没东西"),
e("full","满的；饱的","adjective_describe",1,"high",
["filled","complete","stuffed"],[],
"Bus full of people.","full满/be full饱"),
e("smooth","光滑的；顺畅的","adjective_describe",1,"medium",
["flat","even","soft","easy"],["smith"],
"Road smooth and wide.","smooth光滑/顺畅"),
e("rough","粗糙的","adjective_describe",1,"medium",
["uneven","harsh","coarse"],["tough","roll"],
"Hands rough hard work.","rough粗糙"),
e("sharp","锋利的；敏锐的","adj/adv",1,"high",
["keen","cutting","bright","smart"],["shape","share","shark"],
"Knife sharp careful!","sharp锋利/尖锐"),
e("flat","平的；公寓","noun/adj",1,"high",
["level","even","apartment","smooth"],["float","fleet"],
"Land flat here.","flat平/flat公寓"),
e("wild","野生的","adjective_describe",1,"high",
["natural untamed","uncivilized"],["will","width"],
"Wild animals live nature.","wild野生/野"),
]

# === 重要名词 (30) ===
NEW += [
e("result","结果","noun_common",1,"high",
["outcome","effect","conclusion","answer"],["resume","resent"],
"Hard work produces good results.","re回+sult跳→跳回→结果"),
e("method","方法","noun_common",1,"high",
["way","technique","approach","system"],["myth","model","middle"],
"This method works well.","method方法"),
e("purpose","目的；意图","noun_common",1,"high",
["aim","goal","reason","intention"],["propose","purse"],
"Purpose of visit?","pur向前+pose放→目的"),
e("effort","努力","noun_common",1,"high",
["try","work hard","attempt","energy"],["effect","offer"],
"Put effort into studies.","ef出+fort强→用力→努力"),
e("success","成功","noun_common",1,"high",
["achievement","victory","win","goal"],["succeed","successful","process"],
"Practice makes success.","suc下+cess走→走到底"),
e("failure","失败","noun_common",1,"medium",
["defeat","loss","fail","unsuccessful"],[],
"Failure mother of success.","fail失败+ure名"),
e("experience","经验；经历","noun/verb",1,"high",
["practice","skill","go through","feel"],["experiment","expert"],
"Years teaching experience.","ex出+per尝试+ience试出"),
e("attention","注意力","noun_common",1,"high",
["focus","notice","concentration","care"],["attend","attitude","attempt"],
"Pay attention teacher.","at向+tent拉伸+ion注意力"),
e("attitude","态度","noun_common",1,"high",
["view","opinion","approach","outlook"],["altitude","aptitude"],
"Good attitude leads success.","att面向+itude态度"),
e("opportunity","机会","noun_common",1,"high",
["chance","possibility","opening","occasion"],["oppose","opposition"],
"Seize every opportunity learn.","op带来+unity→机会"),
e("situation","情况","noun_common",1,"high",
["condition","state","case","position"],["situate","station"],
"Situation getting better.","sit位置+ation所在位置"),
e("condition","条件；状况","noun_common",1,"high",
["state","situation","requirement","term"],[],
"Living conditions improved.","con共同+dit说+ion条件"),
e("quality","质量","noun_common",1,"high",
["standard","grade","level","worth"],["quantity","qualify"],
"Quality over quantity.","qual品质+ity质量"),
e("quantity","数量","noun_common",1,"medium",
["amount","number","volume","size"],["quality","quantum"],
"Large quantity wasted.","quant多少+ity数量"),
e("value","价值","noun_common",1,"high",
["price","worth","importance","benefit"],["valley","vault"],
"Time great value.","val价值+ue"),
e("prize","奖品","noun_common",1,"medium",
["award","reward","win","medal"],["price","praise"],
"Won first prize contest.","prize奖品vs price价"),
e("award","奖品；授予","noun/verb",1,"medium",
["prize","medal","give","honr"],["aware","await"],
"School gave him award.","award奖项/授予"),
e("honor/honour","荣誉；尊敬","noun/verb",1,"high",
["respect","glory","pride","praise"],["honest","honey"],
"Honor meet you.","honor荣誉/尊敬"),
e("pride","骄傲；自豪","noun_common",1,"high",
["proud","self-respect","dignity"],["price","pride"],
"Take pride your work.","pride骄傲名vs proud形"),
e("secret","秘密","noun/adj",1,"medium",
["hidden","private","mystery","unknown"],["secret","secure","sector"],
"Dont tell anyone secret.","secret秘密"),
e("promise","承诺；诺言","noun/verb",1,"high",
["pledge","guarantee","agree","word"],["promise","promising"],
"Keep your promise.","promise承诺/答应"),
e("choice","选择","noun_common",1,"high",
["option","selection","pick","decision"],["choose","voice","chance"],
"Making right choice important.","choic选择+e名"),
e("decision","决定","noun_common",1,"high",
["choice","conclusion","judgment","settle"],["decide","division"],
"Make own decision.","decid决定+ion决定名"),
e("suggestion","建议","noun_common",1,"high",
["idea","proposal","advice","recommend"],["suggest","suggestion","suction"],
"Any suggestions?","suggest建议+ion建议名"),
e("solution","解决方案；答案","noun_common",1,"high",
["answer","resolve","fix","solve"],["solve","solute"],
"We need solution this problem.","solut解决+ion方案"),
e("problem","问题；难题","noun_common",1,"high",
["issue","difficulty","trouble","matter"],["problem","probable","probe"],
"Every problem has solution.","pro向前+blem抛→问题"),
e("difficulty","困难","noun_common",1,"high",
["problem","hardship","trouble","challenge"],["difficult","difference","diffcult"],
"Face difficulties courage.","difficult困难+y困难名"),
e("advantage","优势；有利条件","noun_common",1,"high",
["benefit","strength","merit","plus"],["advance","advantage","advertise"],
"Speaking English big advantage.","ad向+vant前+age走在前面→优势"),
e("disadvantage","劣势；不利","noun_common",1,"medium",
["weakness","drawback","minus","problem"],["advantage","disagree","discourage"],
"Every advantage has disadvantage.","dis不+advantage非优势→劣势"),
e("difference","不同；差异","noun_common",1,"high",
["distinction","variation","contrast","same"],["different","difficulty","deference"],
"Know differences between them.","differ不同+ence差异"),
e("relationship","关系","noun_common",1,"high",
["connection","relation","bond","link"],["relative","relation","relay"],
"Good relationship needs trust.","relation关系+ship关系"),
e("friendship","友谊","noun_common",1,"high",
["friend","bond","close","loyal"],["friends","friendship","fiendship"],
"True friendship lasts forever.","friend朋友+ship友谊"),
e("knowledge","知识；学问","noun_common",1,"high",
["learning","education","understanding","info"],["know","knowledge","knead"],
"Knowledge power.","know知道+ledge知识"),
e("wisdom","智慧","noun_common",1,"high",
["intelligence","insight","understanding","wise"],["wise","wisdom","whisper"],
"Wisdom comes experience.","wis智慧+dom智慧"),
e("ability","能力；才能","noun_common",1,"high",
["capability","skill","talent","power"],["ability","ability","ablility"],
"Everyone has ability learn.","able能+ity能力"),
e("talent","天才；天赋","noun_common",1,"high",
["gift","skill","ability","potential"],["talent","talent","taller"],
"She talent for music.","talent天赋/才华"),
e("skill","技能；技巧","noun_common",1,"high",
["ability","technique","talent","practice"],["skill","skull","skin"],
"Reading important skill.","skill技能/技巧"),
e("background","背景","noun_common",1,"high",
["history","origin","context","back"],["back","backward","ground"],
"Tell about background.","back后+ground地面→背景"),
e("direction","方向；说明","noun_common",1,"high",
["way","course","guide","instruction"],["direct","directory","dirt"],
"Which direction north?","direct直+ion直行方向"),
e("position","位置；职位","noun_common",1,"high",
["location","place","job","situation"],["position","positive","position"],
"What position company?","posit放置+ion放置处"),
e("height","高度；身高","noun_common",1,"high",
["tall","high","altitude","top"],["high","heat","weight"],
"What height?","high高+th高度名"),
e("length","长度","noun_common",1,"high",
["long","distance","measurement","size"],["length","level","legend"],
"What length bridge?","long长+th长度名"),
e("shape","形状；形状","noun/verb",1,"medium",
["form","outline","figure","mold"],["shape","shake","shade"],
"Cloud strange shape.","shape形状"),
e("form","形式；表格；形成","noun/verb",1,"high",
["shape","type","structure","format"],["form","firm","from"],
"Fill form please.","form形式/表格"),
e("pattern","模式；图案","noun_common",1,"medium",
["design","model","style","regular"],["patron","patent","pattern"],
"Follow sentence pattern.","pattern模式/图案"),
e("type","类型；打字","noun/verb",1,"high",
["kind","category","sort","class"],["typical","type","style"],
"What type music like?","type类型/打字"),
e("style","风格；样式","noun_common",1,"medium",
["fashion","design","manner","look"],["stylish","style","stack"],
"She own writing style.","style风格"),
e("design","设计；构思","noun/verb",1,"high",
["plan","create","layout","draw"],["design","design resign"],
"Who designed building?","design设计"),
e("model","模型；模范","noun_common",1,"high",
["example","pattern","copy","version"],["mode","modem","middle"],
"She fashion model.","mod样式+el样式展示→模型"),
]

# === 连词/介词/代词 (10) ===
NEW += [
e("whether","是否","conjunction",1,"high",
["if","or not","either","doubt"],["weather","which","whoever"],
"I dont know whether he come.","whether是否常or not"),
e("unless","除非；如果不","conjunction",1,"high",
["if not","except if","without"],["until","unlikely","unload"],
"Unless try never know.","un不+less少→不少于→除非"),
e("however","然而；可是","adverb/conj",1,"high",
["but","although","nevertheless","still"],["how","however","whatever"],
"However disagree.","how+ever无论怎样→然而"),
e("perhaps","也许；可能","adverb",1,"high",
["maybe","possibly","probably","likely"],["period","prepare","parallel"],
"Perhaps right.","per通过+haps运气→碰运气→也许"),
e("instead","代替；反而","adverb",1,"high",
["rather","alternatively","in place of"],["instead","instead steady"],
"Go out instead staying home.","in在+stead地方→别处→代替"),
e("besides","此外；除...之外","prep/adv",1,"high",
["also","in addition to","moreover"],["beside","best","besides"],
"Besides English also learn French.","be在+sides旁还有→此外"),
e("nearby","附近的","adverb/adj",1,"medium",
["close","near","neighborhood","around"],["near","nearly","nearby"],
"Bank nearby.","near近+by附近"),
e("within","在...之内","prep",1,"medium",
["inside","not beyond","in","less than"],["with","without","withdraw"],
"Finish task within two hours.","with在+in里→在里面"),
]

# === 时间频率 (8) ===
NEW += [
e("recently","最近","adverb",1,"high",
["lately","newly","nowadays","recent"],["recently","recently","recently"],
"Seen him recently?","recent最近+ly"),
e("presently","目前；现在","adverb",1,"medium",
["now","currently","soon","at present"],["present","president","prevent"],
"Hes presently working new project.","present现在+ly"),
e("recent","近来的；最近的","adjective_describe",1,"high",
["new","later","current","latest"],["recently","present","recent"],
"Recent news improvement.","re再+cent百→最新→最近"),
e("current","当前的；流通的","adjective_describe",1,"high",
["present","now","modern","existing"],["currency","currently","current"],
"Current situation improving.","curr跑+ent正在跑→当前"),
e("period","时期；阶段","noun_common",1,"high",
["time","era","age","stage"],["period","permit","parallel"],
"Difficult period history.","peri周围+od路→周围路→时期"),
e("moment","片刻；时刻","noun_common",1,"high",
["instant","second","minute","while"],["moment","momentum","moment"],
"Wait moment please.","moment时刻/瞬间"),
e("century","世纪；百年","noun_common",1,"high",
["100 years","hundred","time","age"],["century","center","century"],
"Live 21st century.","cent百+ury百年→世纪"),
e("generation","一代人","noun_common",1,"medium",
["age group","people","era","young"],["general","generator","generation"],
"Young generation loves technology.","gener产生+ation一群→一代"),
]

# === 不规则动词派生/重要补充 (8) ===
NEW += [
e("growth","成长；增长","noun_common",1,"medium",
["grow","develop","increase","progress"],["grow","grown","group"],
"Growth economy steady.","grow成长+th过程"),
e("death","死；死亡","noun_common",1,"high",
["die","dead","life","born"],["deaf","date","dearth"],
"His death great loss.","die死+th死亡名"),
e("life/lives","生活；生命；人们","noun_common",1,"high",
["live","alive","born","experience"],["live","like","lift"],
"Life like box chocolates.","life生活/生命lives复"),
]

print(f"读取 {INPUT}...")
with open(INPUT,'r',encoding='utf-8') as f:
    data = json.load(f)

words = data["words"]
orig = len(words)
added = 0
skip = 0
for entry in NEW:
    w = entry["word"]
    if w in words:
        skip += 1
    else:
        words[w] = entry
        added += 1

data["meta"]["total"] = len(words)
data["meta"]["version"] = "junior2_v2-expanded2"
data["words"] = words

with open(OUTPUT,'w',encoding='utf-8') as f:
    json.dump(data,f,ensure_ascii=False,indent=2)

print(f"\n=== 完成! ===")
print(f"原始: {orig} | 新增: {added} | 跳过重复: {skip} | 最终: {len(words)}")
