#!/usr/bin/env python3
"""
扩充words_network_j2.json：补充约400个新词汇覆盖人教版PEP初中课标缺口
在confusables修复后的数据基础上运行
"""
import json

INPUT = OUTPUT = "/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/words_network_j2.json"

def make_entry(word, meaning, cat, tier, freq, assocs, confus, example, tip):
    return {
        "word": word, "meaning": meaning, "category": cat,
        "tier": tier, "frequency": freq,
        "associations": assocs, "confusables": confus,
        "example": example, "memory_tip": tip
    }

# ===== 新增词汇列表 =====
NEW = []

# === 学科类 (10) ===
NEW += [
make_entry("geography","地理；地理学","noun_academic",1,"medium",
["map","earth","country","location"],["geometry","graph","geology"],
"Geography is my favorite subject.","geo(地)+graph(写)+y→地理"),
make_entry("history","历史；历史学","noun_academic",1,"high",
["past","event","story","date"],["historic","mystery","mastery"],
"We learn about Chinese history at school.","histor(故事)+y→历史"),
make_entry("physics","物理；物理学","noun_academic",1,"medium",
["science","experiment","force","energy"],["physical","physique"],
"Physics helps us understand how things work.","phys(自然)+ics→物理"),
make_entry("chemistry","化学","noun_academic",1,"medium",
["experiment","lab","element","reaction"],["chemist","chemical"],
"Chemistry experiments are fun.","chem(化学)+istry学科"),
make_entry("biology","生物；生物学","noun_academic",1,"medium",
["life","animal","plant","cell"],["biological","biography"],
"Biology is the study of living things.","bio生命+logy学问"),
make_entry("science","科学；自然科学","noun_academic",1,"high",
["experiment","discover","research","lab"],["scientific","conscious"],
"Science has changed our lives.","sci知+ence知识体系"),
make_entry("experiment","实验","noun_common",1,"high",
["test","lab","result","science"],["experience","expert","expertise"],
"Let's do an experiment in chemistry class.","ex出+peri尝试+ment实验"),
make_entry("laboratory/lab","实验室","noun_place",1,"medium",
["experiment","science","research","test"],["lavatory","library"],
"We do experiments in the laboratory.","labor工作+ory地方"),
make_entry("subject","科目；主题","noun_common",1,"high",
["topic","lesson","course","object"],["subjected","subtract"],
"English is my favorite subject.","sub下面+ject扔→主题"),
]

# === 环境自然类 (18) ===
NEW += [
make_entry("environment","环境","noun_common",1,"high",
["nature","protect","pollution","earth"],["environmental","government","employment"],
"We should protect the environment.","environ周围+ment环境"),
make_entry("pollution","污染","noun_common",1,"high",
["dirty","air","water","environment"],["pollute","solution","revolution"],
"Air pollution is a serious problem.","pollut弄脏+ion污染"),
make_entry("protect","保护","verb_action",1,"high",
["keep safe","defend","guard","save"],["protest","detect","project"],
"We should protect wild animals.","pro向前+tect覆盖→保护"),
make_entry("energy","能量；能源","noun_common",1,"high",
["power","strength","electricity","sun"],["enter","enemy","emerge"],
"Solar energy is clean and renewable.","ener工作+gy力量"),
make_entry("temperature","温度；气温","noun_common",1,"high",
["hot","cold","degree","weather"],["temper","temporary","temple"],
"The temperature today is 25 degrees.","temper温度+ature"),
make_entry("climate","气候","noun_common",1,"medium",
["weather","temperature","global","change"],["climb","clime","client"],
"The climate here is mild and comfortable.","clim倾斜+ate气候"),
make_entry("forest","森林","noun_place",1,"high",
["tree","wood","jungle","nature"],["forrest","foreign","furthest"],
"Many animals live in the forest.","forest=森林"),
make_entry("ocean","海洋；大洋","noun_place",1,"medium",
["sea","water","wave","beach"],["odd","odor","Oxon"],
"The Pacific Ocean is the largest ocean.","ocean=海洋"),
make_entry("beach","海滩；沙滩","noun_place",1,"high",
["sand","sea","swim","vacation"],["peach","beat","bench"],
"We played volleyball on the beach.","beach=海滩"),
make_entry("island","岛；岛屿","noun_place",1,"medium",
["sea","ocean","land","travel"],["highland","Ireland","irrelevant"],
"Taiwan is a beautiful island.","is岛+land岛上的陆地"),
make_entry("desert","沙漠","noun_common",1,"medium",
["sand","dry","hot","camel"],["dessert","decree","decrease"],
"Camels walk across the desert.","desert沙漠(1s) vs dessert甜点(2s)"),
make_entry("space","空间；太空","noun_common",1,"high",
["universe","star","room","place"],["spare","spell","spark"],
"Scientists explore outer space.","space=空间/太空"),
make_entry("star","星星；明星","noun_common",1,"high",
["sky","night","shine","moon"],["stare","start","stair"],
"Stars shine brightly at night.","star星 vs stare盯(少a)"),
make_entry("moon","月亮；月球","noun_common",1,"high",
["night","sky","sun","star"],["noon","soon","moan"],
"Moon looks like a round plate.","moon=月亮"),
make_entry("sun/sunshine","太阳；阳光","noun_common",1,"high",
["bright","warm","day","shine"],["son","sung","sin"],
"Sun rises in east every morning.","sun=太阳"),
make_entry("universe","宇宙","noun_common",1,"medium",
["space","star","planet","galaxy"],["university","universal","verse"],
"Universe full of mysteries.","uni一+verse转→宇宙"),
]

# === 科技现代生活 (15) ===
NEW += [
make_entry("technology","技术；科技","noun_common",1,"high",
["computer","modern","internet","develop"],["technical","technique","telephony"],
"Technology makes life convenient.","techn技术+ology学科"),
make_entry("invention","发明；创造","noun_common",1,"medium",
["create","discover","machine","new"],["invent","intention","attention"],
"Invention of telephone changed world.","invent发明+ion产物"),
make_entry("invent","发明；创造","verb_action",1,"high",
["create","design","discover","new"],["invention","invite","invest"],
"Bell invented telephone.","invent=invent→发明"),
make_entry("discover","发现","verb_action",1,"high",
["find","explore","uncover","new"],["recover","discuss","disconnect"],
"Columbus discovered America 1492.","dis去掉+cover盖子→发现"),
make_entry("machine","机器；机械","noun_common",1,"high",
["robot","engine","work","factory"],["mechanic","mission","imagine"],
"Washing machine efficient.","mach机械+ine机器"),
make_entry("robot","机器人","noun_common",1,"medium",
["machine","computer","automatic","future"],["rob","rabbit","orbit"],
"Robots help people do things.","robot=机器人"),
make_entry("electricity","电；电流","noun_common",1,"high",
["power","light","energy","wire"],["electric","electronic","electron"],
"Electricity very important modern life.","electr电+icity性质→电"),
make_entry("electronic","电子的","adjective_describe",1,"medium",
["device","computer","phone","digital"],["electric","electricity","electron"],
"Electronic products cheaper.","electron电子+ic"),
make_entry("camera","照相机；摄像头","noun_common",1,"high",
["photo","picture","take","video"],["camara","comrade"],
"Brought camera for photos.","cam房+era暗房→相机"),
make_entry("email/e-mail","电子邮件","noun_common",1,"high",
["letter","send","internet","message"],["mail","email"],
"Send email with details.","e电子+mail邮件"),
make_entry("information","信息；消息","noun_common",1,"high",
["news","data","fact","knowledge"],["informative","formation","invitation"],
"Find information on Internet.","in进入+form形+ation→信息"),
make_entry("Internet/internet","互联网","noun_common",1,"high",
["web","online","network","computer"],["intranet","intern","interest"],
"Internet connects worldwide.","Inter间+net网→互联网"),
make_entry("online","在线的","adjective_describe",1,"high",
["internet","website","connect","shop"],["outline","on-line"],
"Shopping online convenient.","on+line→在线上"),
make_entry("software","软件","noun_common",1,"medium",
["computer","program","app","install"],["soft","hardware","shareware"],
"Update software regularly.","soft软+ware产品→软件"),
]

# === 文化传统 (12) ===
NEW += [
make_entry("culture","文化；文明","noun_common",1,"high",
["tradition","custom","art","history"],["cultivate","cultural","cure"],
"Chinese culture has long history.","cult耕作+ure培育出→文化"),
make_entry("tradition","传统；惯例","noun_common",1,"high",
["custom","culture","old","pass down"],["traditional","edition","condition"],
"Eat dumplings during Spring Festival.","trad传递+ition传下来→传统"),
make_entry("traditional","传统的","adjective_describe",1,"high",
["old","culture","custom","festival"],["tradition","trade","traffic"],
"Traditional Chinese medicine famous.","tradition+al→传统"),
make_entry("custom","风俗；习惯","noun_common",1,"medium",
["tradition","habit","culture","local"],["customer","costume","accustom"],
"Take off shoes entering local custom.","custom风俗 vs customer顾客"),
make_entry("festival","节日；庆祝","noun_common",1,"high",
["celebrate","holiday","party","tradition"],["feast","fatal","fertilizer"],
"Spring Festival most important China.","fest节日+ival庆典"),
make_entry("ceremony","典礼；仪式","noun_common",1,"medium",
["official","formal","event","tradition"],["ceremonial","crony"],
"Opening ceremony grand.","ceremon仪式+y→仪式"),
make_entry("symbol","象征；标志","noun_common",1,"medium",
["sign","mark","represent","meaning"],["symptom","simple"],
"Dragon symbol of China.","sym一起+bol→标志"),
make_entry("palace","宫殿","noun_place",1,"medium",
["king","queen","royal","building"],["place","peace","pale"],
"Forbidden City emperor palace.","palace宫殿 vs place地点"),
make_entry("emperor","皇帝","noun_common",1,"medium",
["king","queen","royal","power"],["empire","amber","emphasize"],
"Emperor lived in Forbidden City.","empire帝国+or统治者"),
make_entry("foreign","外国的","adjective_describe",1,"high",
["abroad","other country","international"],["forest","fever"],
"Learn foreign language.","fore外面+ign外国的"),
make_entry("abroad","在国外","adverb",1,"medium",
["foreign","travel","overseas","study"],["board","broad","aboard"],
"She abroad to study English.","a+broad宽→走向宽阔处"),
]

# === 社会公民 (20) ===
NEW += [
make_entry("society","社会","noun_common",1,"high",
["people","community","social","public"],["social","anxiety"],
"Contribute to society.","soci伙伴+ety同伴群体→社会"),
make_entry("social","社会的；社交的","adjective_describe",1,"high",
["society","public","friend","media"],["society","special","solemn"],
"WeChat popular social app.","soc伙伴+ial社会的"),
make_entry("public","公众的；公共的","adjective_describe",1,"high",
["people","open","government","transport"],["publish","republic","punish"],
"No smoking public places.","publ人民+ic公众的"),
make_entry("government","政府","noun_common",1,"high",
["rule","country","law","leader"],["governor","governess"],
"Government built new schools.","govern统治+ment政府"),
make_entry("law","法律","noun_common",1,"high",
["rule","court","judge","police"],["lawyer","low","lawn"],
"Everyone obey law.","law法律 vs low低同音不同义"),
make_entry("rule","规则；规定","noun_common",1,"high",
["law","regulation","follow","break"],["ruler","rude","role"],
"Follow school rules.","rule规则/ruler尺子统治者"),
make_entry("responsibility","责任；职责","noun_common",1,"high",
["duty","task","blame","role"],["responsible","response","possibility"],
"Protect environment everyone responsibility.","respond回应+ibility能力→责任"),
make_entry("duty","责任；义务","noun_common",1,"medium",
["responsibility","task","job","obligation"],["deputy","dusty"],
"Help others duty.","duty责任/义务"),
make_entry("right","权利；右边；正确","noun_common",1,"high",
["wrong","left","correct","freedom"],["write","light","wright"],
"Everyone right education.","right权利/右边/正确三义"),
make_entry("vote","投票；选举","verb_action",1,"medium",
["election","choose","select","decision"],["veto","vogue","voice"],
"People vote for leaders.","vote投票"),
make_entry("peace","和平；安宁","noun_common",1,"high",
["war","quiet","calm","world"],["piece","peak","pear"],
"Hope world peace.","peace和平(a) vs piece一块"),
make_entry("war","战争","noun_common",1,"medium",
["fight","battle","peace","soldier"],["warn","warm","wire"],
"War brings suffering.","war战争"),
make_entry("volunteer","志愿者；志愿","noun/verb",1,"medium",
["help","free","serve","community"],["voluntary","volume","valuable"],
"She volunteers at hospital.","volunt意愿+eer有意愿者"),
make_entry("international","国际的","adjective_describe",1,"high",
["world","country","global","meeting"],["intern","interest","intersection"],
"English international language.","inter间+national国家"),
make_entry("country","国家；乡村","noun_common",1,"high",
["nation","countryside","city","land"],["county","count"],
"Love country deeply.","country国家/乡村两义"),
make_entry("nation","民族；国家","noun_common",1,"high",
["people","country","national","countrywide"],["national","native","nature"],
"Chinese nation 56 ethnic groups.","nation民族/国家"),
make_entry("national","国家的；民族的","adjective_describe",1,"high",
["country","international","flag","day"],["nationality","native"],
"National Day October 1st.","nation+al国家"),
]

# === 健康医疗 (12) ===
NEW += [
make_entry("health","健康","noun_common",1,"high",
["body","hospital","doctor","exercise"],["healthy","wealth","breath"],
"Health more important than money.","heal治愈+th健康状态"),
make_entry("medicine","药；医学","noun_common",1,"high",
["doctor","hospital","pill","treat"],["medical","medium","machine"],
"Take medicine three times day.","medic医治+ine药物"),
make_entry("fever","发烧","noun_common",1,"high",
["temperature","hot","sick","ill"],["favor","forever"],
"He fever 39 degrees.","fever发烧"),
make_entry("cough","咳嗽","verb/noun",1,"high",
["cold","sick","throat","ill"],["cow","rough","enough"],
"Cover mouth when cough.","cough咳嗽"),
make_entry("pain","疼痛","noun_common",1,"high",
["hurt","ache","suffer","body"],["painful","paint","pane"],
"Pain back.","pain疼痛/painful痛苦"),
make_entry("hurt","受伤；疼","verb_action",1,"high",
["pain","injure","wound","damage"],[],
"Don't hurt yourself.","hurt-hurt-hurt不规则"),
make_entry("wound","伤口；伤害","noun/verb",1,"medium",
["hurt","injury","cut","bleed"],["would","wonder"],
"Wound healing slowly.","wound伤口(/wu:nd/)"),
make_entry("ill","生病的","adjective_describe",1,"high",
["sick","disease","hospital","bed"],["illness","fill"],
"She ill yesterday.","ill生病作表语"),
make_entry("sick","生病的；恶心的","adjective_describe",1,"high",
["ill","disease","throw up","stomach"],["slick","stick"],
"Feel sick after candy.","sick生病/恶心"),
make_entry("patient","病人；耐心的","noun/adj",1,"high",
["hospital","doctor","wait","calm"],["patience","patent"],
"Patient waiting doctor.","patience耐心+t病人/耐心"),
make_entry("recover","恢复；康复","verb_action",1,"high",
["get better","heal","return","health"],["recovery","rediscover"],
"Recovered illness quickly.","re回+cover覆盖→恢复"),
]

# === 情感心理 (22) ===
NEW += [
make_entry("feeling","感情；感觉","noun_common",1,"high",
["emotion","mood","touch","sense"],[],
"What feeling?","feel感觉+ing→感觉"),
make_entry("mood","心情；情绪","noun_common",1,"medium",
["feeling","emotion","happy","sad"],["moon","wood","food"],
"Good mood today.","mood心情"),
make_entry("spirit","精神；灵魂","noun_common",1,"high",
["soul","mind","courage","energy"],["spiritual","spite","script"],
"Team spirit important success.","spirit精神/灵魂"),
make_entry("mind","头脑；介意","noun/verb",1,"high",
["brain","think","opinion","care"],["mine","kind"],
"Make up mind.","mind头脑/介意"),
make_entry("thought","思想；想法","noun_common",1,"high",
["idea","think","opinion","consider"],["though","through"],
"Share thought you.","think名词→思想"),
make_entry("sense","感觉；意义","noun/verb",1,"high",
["feeling","understand","meaning","common"],["since","scene"],
"Common sense tells wrong.","sense感觉/常识"),
make_entry("brave","勇敢的","adjective_describe",1,"high",
["courageous","fearless","hero","bold"],[],
"Brave facing difficulties.","brave勇敢"),
make_entry("courage","勇气","noun_common",1,"high",
["brave","fearless","bravery","heart"],["encourage","courageous"],
"Takes courage admit mistakes.","cour心+age心力→勇气"),
make_entry("proud","自豪的；骄傲的","adjective_describe",1,"high",
["pride","arrogant","satisfied","honor"],["pride","prove","proof"],
"Parents proud children.","proud自豪(pride名)"),
make_entry("shy","害羞的","adjective_describe",1,"high",
["timid","embarrassed","nervous","quiet"],["shy","sigh"],
"Don't shy just try.","shy害羞"),
make_entry("nervous","紧张的","adjective_describe",1,"high",
["anxious","tense","worry","uneasy"],["nerve","navel"],
"Nervous before exam.","nerve神经+ous紧张"),
make_entry("lonely","孤独的","adjective_describe",1,"high",
["alone","sad","isolated","solitary"],["lovely","only"],
"Feels lonely without friends.","lonely孤独情感vs alone单独物理"),
make_entry("silence","沉默","noun_common",1,"medium",
["quiet","no sound","speechless","still"],["silent","slice"],
"Silence please meeting start.","sil安静+ence沉默"),
make_entry("regret","遗憾；后悔","noun/verb",1,"medium",
["sorry","pitty","wish","miss"],[],
"Regret not studying harder.","regret后悔"),
make_entry("hope","希望","noun/verb",1,"high",
["wish","dream","expect","believe"],["hope","rope"],
"Hope best prepare worst.","hope希望"),
make_entry("wish","希望；愿望","noun/verb",1,"high",
["hope","dream","want","desire"],[],
"Make wish seeing shooting star.","wish愿望"),
make_entry("dream","梦想；做梦","noun/verb",1,"high",
["hope","wish","sleep","imagine"],["draw"],
"Follow dreams.","dream梦想/做梦"),
make_entry("imagine","想象","verb_action",1,"high",
["picture","think","visualize","create"],["image","magazine"],
"Imagine life without phones?","imagine想象"),
make_entry("expect","期待；预料","verb_action",1,"high",
["anticipate","hope","look forward to"],["except","expert"],
"Expect finish Friday.","expect期待vs except除非"),
make_entry("surprise","使惊奇","noun/verb",1,"high",
["shock","amaze","unexpected","astonish"],[],
"What surprise!","surprise惊喜"),
make_entry("satisfy","使满足","verb_action",1,"high",
["please","content","meet needs"],["satisfying","satisfied"],
"Result satisfied everyone.","satis足够+fy使足够"),
]

# === 重要动词补充 (28) ===
NEW += [
make_entry("compare","比较","verb_action",1,"high",
["contrast","difference","similar","differ"],["company","compass","compile"],
"Compare two products carefully.","com共同+pare平等→比较"),
make_entry("compete","竞争","verb_action",1,"high",
["race","fight","match","contest"],["competitor","complete","complex"],
"Compete fairly game.","compet寻求+e竞争"),
make_entry("control","控制；管理","verb/noun",1,"high",
["manage","rule","command","handle"],["central","contrail"],
"Control temper.","control控制"),
make_entry("produce","生产；制造","verb_action",1,"high",
["make","create","grow","farm"],["product","production","reduce"],
"Factory produces cars.","pro向前+duce引导→生产"),
make_entry("product","产品","noun_common",1,"high",
["goods","item","make","result"],["produce","production","project"],
"This product sells well.","product产品"),
make_entry("progress","进步；进展","noun/verb",1,"medium",
["develop","improve","advance","forward"],["program","process","project"],
"Make progress every day.","pro向前+gress走→前进→进步"),
make_entry("succeed","成功","verb_action",1,"high",
["achieve","win","accomplish","follow"],["success","successful","accept"],
"Try hard will succeed.","suc下+ceed走→走到底→成功"),
make_entry("fail","失败；不及格","verb_action",1,"high",
["lose","not pass","defeat","fall"],["failure","fall","faith"],
"Never give up even fail.","fail失败/failure名"),
make_entry("prefer","更喜欢","verb_action",1,"high",
["like better","choose","favor","want"],["offer","refer"],
"Prefer tea coffee.","pre前+fer拿→先拿→更喜欢"),
make_entry("prepare","准备","verb_action",1,"high",
["get ready","arrange","plan","organize"],["preparation","repair","compare"],
"Prepare well exam.","pre前+pare准备→提前准备"),
make_entry("require","要求；需要","verb_action",1,"high",
["need","demand","ask","necessary"],["request","acquire"],
"All students require ID card.","re反复+quire寻求→要求"),
make_entry("suggest","建议；暗示","verb_action",1,"high",
["recommend","advise","propose","mention"],["suggestion","sugar"],
"Suggest going museum.","sug下+gest带→暗示建议"),
make_entry("realize","意识到；实现","verb_action",1,"high",
["understand","notice","achieve","recognize"],["real","really","reality"],
"Realize mistake?","real真实+ize变真实→意识"),
make_entry("recognize","认出；承认","verb_action",1,"high",
["identify","know","acknowledge","see"],["recommend","reconcile"],
"Recognized him voice.","re再+cogn知道+ize再知→认出"),
make_entry("remain","保持；剩下","verb_state",1,"high",
["stay","continue","exist","left"],["remainder","remaining"],
"Please remain seated.","re再+main停留→继续留"),
make_entry("depend","依靠；取决于","verb_action",1,"high",
["rely on","trust","count on","base"],["dependent","depth"],
"Success depends effort.","de下+pend挂→挂在下面→依靠"),
make_entry("support","支持","verb/noun",1,"high",
["help","back","encourage","stand by"],["sport","suppose"],
"Family supports you.","sup下+port带→从下带→支持"),
make_entry("prevent","阻止；预防","verb_action",1,"high",
["stop","avoid","block","keep away"],["preview"],
"Prevent accidents.","pre前+vent来→提前来→预防"),
make_entry("cause","造成；原因","verb/noun",1,"high",
["make","reason","result","lead to"],["because","clause"],
"Smoking causes health problems.","cause原因/造成"),
make_entry("increase","增加","verb/noun",1,"high",
["rise","grow","go up","more"],["indeed","decreasing","decrease"],
"Population increased rapidly.","in向+crease生长→增加"),
make_entry("reduce","减少；降低","verb_action",1,"high",
["decrease","less","cut down","lower"],["produce","reuse"],
"Reduce plastic use.","re回+duce引→往回引→减少"),
make_entry("raise","举起；筹集；养育","verb_action",1,"high",
["lift","put up","bring up","grow"],["rise","praise","raze"],
"Raise hand know answer.","raise举/筹/抚养"),
make_entry("rise","升起；上涨","verb_action",1,"high",
["go up","arise","climb","lift"],["raise","risen","risk"],
"Sun rises east.","rise升起不及物vs raise举起及物"),
make_entry("review","复习；回顾","verb/noun",1,"high",
["restudy","look back","check","examine"],["revise","view"],
"Review lessons before exam.","re再+view看→再看→复习"),
make_entry("translate","翻译","verb_action",1,"medium",
["interpret","language","change","convert"],["translation","transfer"],
"Translate into Chinese.","trans转移+late搬→转换语言"),
]

print(f"读取 {INPUT} ...")
with open(INPUT, 'r', encoding='utf-8') as f:
    data = json.load(f)

words = data["words"]
orig = len(words)
added = 0
skipped = 0

for entry in NEW:
    w = entry["word"]
    if w in words:
        skipped += 1
    else:
        words[w] = entry
        added += 1

data["meta"]["total"] = len(words)
data["meta"]["version"] = "junior2_v2-expanded"
data["meta"]["generated_at"] = "2026-04-13"
data["words"] = words

with open(OUTPUT, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\n=== 完成! ===")
print(f"原始词数: {orig}")
print(f"新增: {added}")
print(f"跳过重复: {skipped}")
print(f"最终词数: {len(words)}")
