#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
补全 dictation_en_g8.json 中所有缺少真实音标的词汇
使用规则匹配 + 大量内置音标
"""

import json, re

INPUT = 'src/data/dictation_en_g8.json'
OUTPUT = 'src/data/dictation_en_g8.json'

# 超大音标库 - 覆盖几乎所有常见英语单词
PHON = {}

def add(words, ph):
    for w in words:
        PHON[w] = ph

# A
add(['a','able','about','above','abroad','absent','accept','accident','achieve',
     'across','action','active','activity','actually','add','address','admire','admit',
     'adult','advance','advantage','adventure','advertise','afford','afraid','after',
     'afternoon','again','against','age','ago','agree','ahead','air','airplane','airport',
     'alarm','album','alive','all','allow','almost','alone','along','aloud','already',
     'also','although','always','am','amazing','among','amount','an','and','angry',
     'animal','another','answer','any','anybody','anyone','anything','anyway','anywhere',
     'appear','apple','April','area','argue','arm','around','arrange','arrival','arrive',
     'art','article','as','asian','ask','asleep','at','attention','August','aunt','autumn',
     'avoid','awake','away'], 'PH_A')

PHON.update({
    # A - 精确音标
    'a':"/eɪ; ə/",'able':"/'eɪbl/",'about':"/ə'baut/",
    'above':"/ə'bʌv/",'abroad':"/ə'brɔːd/",'absent':/"'æbsnt/",
    'accept':"/ək'sept/",'accident':/"'æksɪdənt/",'achieve':"/ə'tʃiːv/",
    'across':"/ə'krɒs/",'action':/"'ækʃn/",'active':/"'æktɪv/",
    'activity':"/æk'tɪvəti/",'actually':/"'æktʃuəli/",
    'add':"/æd/",'address':"/ə'dres/",'admire':"/əd'maɪə(r)/",
    'admit':"/əd'mɪt/",'adult':/"'ædʌlt/",'advance':"/əd'vɑːns/",
    'advantage':"/əd'vɑːntɪdʒ/",'adventure':"/əd'ventʃə(r)/",
    'advertise':/"'ædvətaɪz/",'afford':"/ə'fɔːd/",
    'afraid':"/ə'freɪd/",'after':/"'ɑːftə(r)/",'afternoon':"/ˌɑːftə'nuːn/",
    'again':"/ə'gen/",'against':"/ə'ɡenst; ə'ɡeɪnst/",
    'age':"/eɪdʒ/",'ago':"/ə'gəʊ/",'agree':"/ə'ɡriː/",
    'ahead':"/ə'hed/",'air':"/eə(r)/",
    'airplane':/"'eəpleɪn/",'airport':/"'eəpɔːt/",
    'alarm':"/ə'lɑːm/",'album':/"'ælbəm/",
    'alive':"/ə'laɪv/",'all':"/ɔːl/",
    'allow':"/ə'laʊ/",'almost':/"'ɔːlməʊst/",
    'alone':"/ə'ləʊn/",'along':"/ə'lɒŋ/",
    'aloud':"/'laʊd/",'already':"/ɔːl'redi/",
    'also':/"'ɔːlsəʊ/",'although':"/ɔːl'ðəʊ/",
    'always':/"'ɔːlweɪz/",'am':"/em; əm;",
    'amazing':"/ə'meɪzɪŋ/",'among':"/ə'mʌŋ/",
    'amount':"/ə'maunt/",'an':"/æn; ən/",
    'and':"/ænd; ən; n/",
    'angry':/"'æŋɡri/",
    'animal':/"'ænɪml/",'another':"/ə'nʌðə(r)/",
    'answer':/"'ɑːnsə(r)/",'any':/"'eni/",
    'anybody':/"'enibɒdi/",'anyone':/"'eniwʌn/",
    'anything':/"'eniθɪŋ/",'anyway':/"'eniweɪ/",
    'anywhere':/"'eniweə(r)/",
    'appear':"/ə'pɪə(r)/",'apple':/"'æpl/",
    'April':/"'eɪprəl/",
    'area':/"'eəria/",
    'argue':/"'ɑːɡjuː/",
    'arm':"/ɑːm/",
    'around':"/ə'raʊnd/",
    'arrange':"/ə'reɪndʒ/",
    'arrival':"/ə'raɪvl/",
    'arrive':"/ə'raɪv/",
    'art':"/ɑːt/",
    'article':/"'ɑːtɪkl/",
    'as':"/æz; əz; z/",
    'Asian':/"'eɪʃn/",
    'ask':"/ɑːsk/",
    'asleep':"/ə'sliːp/",
    'at':"/æt; ət/",
    'attention':"/ə'tenʃn/",
    'August':/"'ɔːɡəst/",
    'aunt':"/ɑːnt; ænt/",
    'autumn':/"'ɔːtəm/",
    'avoid':"/ə'vɔɪd/",
    'awake':"/ə'weɪk/",
    'away':"/ə'weɪ/",
})

# B
PHON.update({
    'baby':"/ˈbeɪbi/",'back':"/bæk/",'background':"/ˈbækɡraʊnd/",
    'bad':"/bæd/",'badly':"/ˈbædli/",'bag':"/bæg/",
    'balance':"/ˈbæləns/",'balcony':"/ˈbælkəni/",'ball':"/bɔːl/",
    'balloon':"/bə'luːn/",'bamboo':"/bæm'buː/",
    'banana':"/bə'nɑːnə/",'bank':"/bæŋk/",
    'base':"/beɪs/",'baseball':/"'beɪsbɔːl/",
    'basic':"/ˈbeɪsɪk/",'basin':"/ˈbeɪsn/",
    'basket':/"'bɑːskit/",'basketball':/"'bɑːskitbɔːl/",
    'bat':"/bæt/",'batch':"/bætʃ/",
    'bath':"/bɑːθ/",'bathroom':"/ˈbɑːθruːm/",
    'be':"/biː; bi/",
    'beach':"/biːtʃ/",'bean':"/biːn/",
    'bear':"/beə(r)/",'beat':"/biːt/",
    'beautiful':"/ˈbjuːtɪfl/",'because':"/bɪ'kɒz/",
    'become':"/bɪ'kʌm/",'bed':"/bed/",
    'bedroom':"/ˈbedruːm/",'bee':"/biː/",
    'beef':"/biːf/",'beer':"/bɪə(r)/",
    'before':"/bɪ'fɔː(r)/", 'begin':"/bɪ'ɡɪn/",
    'beginning':"/bɪ'ɡɪŋ/",'behaviour':"/bɪ'heɪvjə(r)/",
    'behind':"/bɪ'haɪnd/",'being':"/'biːɪŋ/",
    'believe':"/bɪ'liːv/",'bell':"/bel/",
    'belong':"/bɪ'lɒŋ/",'below':"/bɪ'ləʊ/",
    'belt':"/belt/",'bench':"/bentʃ/",
    'bend':"/bend/",'beneath':"/bɪ'niːθ/",
    'benefit':"/ˈbenɪfɪt/",'beside':"/bɪ'saɪd/",
    'besides':"/bɪ'saɪdz/",'best':"/best/",
    'better':"/ˈbetə(r)/",'between':"/bɪ'twiːn/",
    'beyond':"/bɪ'jɒnd/",'big':"/bɪɡ/",
    'bike':"/baɪk/",'bill':"/bɪl/",
    'bin':"/bɪn/",'biology':"/baɪ'ɒlədʒi/",
    'bird':"/bɜːd/",'birth':"/bɜːθ/",
    'birthday':"/'bɜːθdeɪ/",'biscuit':"/ˈbɪskɪt/",
    'bit':"/bɪt/",'bite':"/baɪt/",
    'bitter':"/'bɪtə(r)/",'black':"/blæk/",
    'blackboard':"/ˈblækbɔːd/",'blame':"/bleɪm/",
    'blank':"/blæŋk/",'blanket':"/ˈblæŋkɪt/",
    'bleed':"/bliːd/",'blend':"/blend/",
    'blind':"/blaɪnd/",'block':"/blɒk/",
    'blood':"/blʌd/",'blow':"/bləʊ/",
    'blue':"/bluː/",'board':"/bɔːd/",
    'boat':"/bəʊt/",'boil':"/bɔɪl/",
    'bomb':"/bɒm/",'bone':"/bəʊn/",
    'book':"/bʊk/",'boom':"/buːm/",
    'boot':"/buːt/",'border':/"'bɔːdə(r)/",
    'born':"/bɔːn/",'borrow':"/'bɒrəʊ/",
    'boss':"/bɒs/",'both':"/bəʊθ/",
    'bother':"/'bɒðə(r)/",'bottle':"/'bɒtl/",
    'bottom':"/ˈbɒtəm/",'bounce':"/baʊns/",
    'bound':"/baʊnd/",'bow':"/baʊ; bəʊ/",
    'bowl':"/bəʊl/",'box':"/bɒks/",
    'boy':"/bɔɪ/",'brain':"/breɪn/",
    'brake':"/breɪk/",'branch':"/brɑːntʃ; bræntʃ/",
    'brave':"/breɪv/",'bread':"/bred/",
    'break':"/breɪk/",'breakfast':/"'brekfəst/",
    'breath':"/breθ/",'breathe":"/briːð/",
    'breed':"/briːd/",'brick':"/brɪk/",
    'bridge':"/brɪdʒ/",'brief':"/briːf/",
    'bright':"/braɪt/",'bring':"/brɪŋ/",
    'Britain':/"'brItn/",'British':/"'brItIS/",
    'broad':"/brɔːd/",'broadcast':/"'brɔːdkA:st; 'brɔːdkæst/",
    'broken':"/'br@Uk@n/",'broom':"/bru:m; brUm/",
    'brother':/"'brAD@(r)/",'brown':"/braUn/",
    'brush':"/brVS/",'bucket':"/'bAkIt/",
    'bud':"/bAd/",'budget':"/'bAdZIt/",
    'buffet':"/bu'feI; b@'feI/",
    'build':"/bIld/",'building':/"'bIldIN/",
    'burn':"/b3:n/",'burst':"/b3:st/",
    'bury':"/'beri/",'bus':"/bAs/",
    'bush':"/bUS/",'business':/"'bIzn@s/",
    'busy':"/'bIzi/",'but':"/bAt; b@t/",
    'butter':"/'bAt@(r)/",'button':"/'bVtn/",
    'buy':"/baI/",'by':"/baI/",
})

# C-G (批量添加常用词)
PHON.update({
    'cabbage':"/'kæbIdZ/",'cafe':"/'kæfeI/",
    'cage':"/keIdZ/",'cake':"/keIk/",
    'call':"/kO:l/",'calm':"/kA:m/",
    'camera':"/'kæm(r)@",'camp':"/kæmp/",
    'can':"/kæn; k@n/",'Canada':"/'kæn@d@/",
    'cancel':"/'kænsl/",'cancer':"/'kæns@(r)/",
    'candidate':"/'kændIdeIt; 'kændId@t/",
    'candle':"/'kændl/",'candy':"/'kændi/",
    'cap':"/kæp/",'capital':"/'kæpItl/",
    'captain':"/'kæptIn/",'car':"/kA:(r)/",
    'card':"/kA:d/",'care':"/ke@(r)/",
    'careful':"/'ke@fl;",'careless':"/'ke@l@s/",
    'carrot':"/'kær@t/",'carry':"/'kæri/",
    'cartoon':"/kA:'tu:n/",'case':"/keIs/",
    'cash':"/kæS/",'cast':"/kA:st; kæst/",
    'castle':/"'kAsl; 'kæsl/",
    'cat':"/kæt/",'catch':"/kætS/",
    'cause':"/kO:z/",'cave':"/keIv/",
    'ceiling':"/'si:lIN/",'celebrate':"/'selibreit/",
    'cell':"/sel/",'cent':"/sent/",
    'center':/'sent@(r)/,
    'central':/'sentr@l/,
    'centre':/'sent@(r)/,
    'century':/'sentS@ri/,
    'certain':/'s3:tn/,
    'certainly':/'s3:tnli/,
    'chain':"/tSeIn/",
    'chair':"/tSe@(r)/",
    'chairman':"/'tSe@m@n/",
    'chalk':"/tSO:k/",
    'chance':"/tSA:ns/",
    'change':"/tSeIndZ/",
    'changeable':"/'tSeIndZ@bl/",
    'channel':"/'tSænl/",
    'chapter':"/'tæpt@(r)/",
    'charge':"/tSA:dZ/",
    'chat':"/tSæt/",
    'cheap':"/tSi:p/",
    'check':"/tSek/",
    'cheek':"/tSi:k/",
    'cheer':"/tSI@(r)/",
    'cheese':"/tSi:z/",
    'chemistry':"/'kemIstri/",
    'chest':"/tSest/",
    'chicken':"/'tSIkIn/",
    'chief':"/tSi:f/",
    'child':"/tSaIld/",
    'chimney':"/'tSImni/",
    'china':"/'tSaIna/",
    'chocolate':"/'tSQklIt/",
    'choice':"/tSOIs/",
    'choose':"/tSu:z/",
    'chop':"/tSQp/",
    'church':"/tS3:tS/",
    'cinema':"/'sInIm@/",
    'circle':"/'s3:kl/",
    'citizen':"/'sItIzn/",
    'city':"/'sIti/",
    'class':"/klA:s;",
    'classmate':"/'klA:smeIt/",
    'classroom':"/'klA:sru:m/",
    'clean':"/kli:n/",
    'clear':"/klI@(r); klIr/",
    'clever':"/'lev@(r)/",
    'climate':"/'klaImIt/",
    'climb':"/klaIm/",
    'clinic':"/'klInIk/",
    'clock':"/klQk/",
    'close':"/kl@Uz; kl@s/",
    'cloth':"/klQT; klO:T/",
    'clothes':"/kl@UDz/",
    'clothing':"/'kl@UDIN/",
    'cloud':"/klaUd/",
    'cloudy':"/'klaUdi/",
    'club':"/klVb/",
    'coach':"/k@UtS/",
    'coal':"/k@Ul/",
    'coast':"/k@ust/",
    'coat':"/k@ut/",
    'code':"/k@ud/",
    'coin':"/kOIn/",
    'coke':"/k@uk/",
    'cold':"/k@uld/",
    'collect':"/k@'lekt/",
    'college':"/'kqlIdZ/",
    'color':"/'kVl@(r)/",
    'colour':"/'kVl@(r)/",
    'comb':"/k@um/",
    'combine':"/k@m'bain/",
    'comfort':"/'kVmf@t/",
    'comfortable':"/'kVmf@t@bl/",
    'common':"/'kQm@n/",
    'communicate':"/k@'mju:nikeit/",
    'communication':"/k@ˌmju:nI'keISn/",
    'communism':"/'kQmjUnIz@m/",
    'community':"/k@'mju:n@ti/",
    'company':"/'kVmp@ni/",
    'compare':"/k@m'pe@(r)/",
    'competition':"/ˌkQmp@'tISn/",
    'complete':"/k@m'pli:t/",
    'composition':"/ˌkQmp@'zISn/",
    'computer':"/k@m'pju:t@(r)/",
    'comrade':"/'kQmrid/",
    'concert':"/'kQns@t/",
    'condition':"/k@n'dISn/",
    'conduct':"/k@n'dVkt/",
    'conductor':"/k@n'dVkt@(r)/",
    'conference':"/'kQnf@r@ns/",
    'congratulate':"/k@n'grætSuleit/",
    'connect':"/k@'nekt/",
    'connection':"/k@'nekSn/",
    'conquer':"/'kQNk@(r)/",
    'consider':"/k@n'sId@(r)/",
    'construction':"/k@n'strVkSn/",
    'contain':"/k@'teIn/",
    'continue':"/k@n'tInju:/",
    'control':"/k@n'tr@Ul/",
    'conversation':"/ˌkQnvə'seISn/",
    'cook':"/kuk/",
    'cool':"/ku:l/",
    'copy':"/'kQpi/",
    'corner':"/'kO:n@(r)/",
    'correct':"/k@'rekt/",
    'cost':"/kQst; kO:st/",
    'cottage':"/'kqtIdZ/",
    'cotton':"/'kQtn/",
    'could':"/kud; k@d/",
    'count':"/kaUnt/",
    'counter':"/'kaunt@(r)/",
    'country':"/'kVntri/",
    'couple':"/'kvpl/",
    'courage':"/'kVrIdZ/",
    'course':"/kO:s/",
    'courtyard':"/'kO:tjA:d/",
    'cousin':"/'kVzn/",
    'cover':"/'kAv@(r)/",
    'cow':"/kaU/",
    'cowboy':"/'kaUbOI/",
    'crack':"/kræk/",
    'craft':"/krA:ft; kræft/",
    'crash':"/kræS/",
    'crayon':"/'kreI@n/",
    'crazy':"/'kreIzi/",
    'cream':"/kri:m/",
    'create':"/kri'eIt/",
    'credit':"/'kredIt/",
    'crime':"/kraIm/",
    'criminal':"/'krIml/",
    'crop':"/krQp/",
    'cross':"/krQs/",
    'crowd':"/kraUd/",
    'cruel':"/'kru:@l/",
    'cry':"/kraI/",
    'culture':"/'kVltSa(r)/",
    'cup':"/kAp/",
    'cure':"/kjU@(r)/",
    'curious':"/'kjU@ri@s/",
    'current':"/'kVr@nt/",
    'custom':"/'kVst@m/",
    'customer':"/'kVst@m@(r)/",
    'cut':"/kAt/",

    # D
    'dad':"/dæd/",
    'daily':"/'deIli/",
    'damage':"/'dæmIdZ/",
    'dance':"/dA:ns; dæns/",
    'danger':/"'deIndZ@(r)/",
    'dangerous':"/'deIndZ@r@s/",
    'dare':"/dea(r)/",
    'dark':"/dA:k/",
    'data':/"'deIt@; 'dA:t@; 'dæt@/",
    'date':"/deIt/",
    'daughter':"/'dO:t@(r)/",
    'dawn':"/dO:n/",
    'day':"/deI/",
    'dead':"/ded/",
    'deal':"/di:l/",
    'dear':"/dI@(r)/",
    'death':"/deT/",
    'debate':"/dI'beIt/",
    'debt':"/det/",
    'decade':"/'dekeId/",
    'December':"/dI'semb@(r)/",
    'decide':"/dI'saId/",
    'decision':"/dI'sIZn/",
    'declare':"/dI'kle@(r)/",
    'decorate':"/'dek@reit/",
    'decrease':"/di:'kri:s/",
    'deep':"/di:p/",
    'deer':"/dI@(r)/",
    'degree':"/dI'gri:/",
    'delay':"/dI'leI/",
    'delicious':"/dI'lIS@s/",
    'delight':"/dI'laIt/",
    'deliver':"/dI'lIv@(r)/",
    'demand':"/dI'mA:nd/",
    'dentist':"/'dentIst/",
    'depend':"/dI'pend/",
    'depth':"/depT/",
    'describe':"/dI'skraIb/",
    'desert':"/'dez@t/",
    'design':"/dI'zaIn/",
    'desk':"/desk/",
    'destroy':"/dI'strOI/",
    'develop':"/dI'vel@p/",
    'devote':"/dI'v@ut/",
    'dialogue':"/'daI@lQg/",
    'diamond':"/'daI@m@nd/",
    'diary':"/'daIari/",
    'dictionary':"/'dIkS@nri/",
    'die':"/daI/",
    'diet':"/'daI@t/",
    'difference':"/'dIf@ns/",
    'different':"/'dIf@r@nt/",
    'difficult':"/'dIfIk@lt/",
    'dig':"/dIg/",
    'digital':"/'dIdZItl/",
    'dine':"/daIn/",
    'dinner':"/'din@(r)/",
    'direct':"/dI'rekt; daI'rekt/",
    'direction':"/daI'rekSn; dI'rekSn/",
    'director':"/dI'rekt@(r); daI'rekt@(r)/",
    'dirty':"/'d3:ti/",
    'disagree':",dIs@'gri:",
    'disappear':",dIs@'pIa(r)/,
    'disappoint':",dIs@'pOInt/,
    'disaster':"/dI'zA:st@(r)/",
    'discover':"/dI'skAv@(r)/",
    'discuss':"/dI'skVs/",
    'discussion':"/dI'skVSn/",
    'dish':"/dIS/",
    'disk':"/dIsk/",
    'dismiss':"/dI'mIs/",
    'distance':"/'dist@ns/",
    'distant':"/'dist@nt/",
    'distinguish':"/dI'stINgwIS/",
    'district':"/'dIstrIkt/",
    'divide':"/dI'vaId/",
    'divorce':"/dI'vO:s/",
    'do':"/du:/; d@/",
    'doctor':"/'dQkt@(r)/",
    'document':"/'dQkjum@nt/",
    'dog':"/dQg/",
    'doll':"/dQl/",
    'dollar':"/'dQl@(r)/",
    'door':"/dO:(r)/",
    'double':"/'dVbl/",
    'doubt':"/daUt/",
    'down':"/daUn/",
    'dozen':"/'d@zn/",
    'drag':"/dræg/",
    'draw':"/drO:/",
    'dream':"/dri:m/",
    'dress':"/dres/",
    'drink':"/drINk/",
    'drive':"/draIv/",
    'driver':"/'draIv@(r)/",
    'drop':"/drQp/",
    'drug':"/drVg/",
    'drum':"/drVm/",
    'dry':"/draI/",
    'duck':"/dVk/",
    'due':"/dju:/",
    'during':"/'djU@rIN/",
    'dusk':"/dVsk/",
    'dust':"/dVst/",
    'dusty':"/'dVsti/",
    'duty':"/'dju:ti/",

    # E
    'each':"/i:tS/",
    'eager':"/'i:g@(r)/",
    'ear':"/Ia(r)/",
    'early':"/'3:li/",
    'earth':"/3:T/",
    'east':"/i:st/",
    'eastern':"/'i:st@n/",
    'easy':"/'i:zi/",
    'eat':"/i:t/",
    'education':"/ˌedZu'eISn/",
    'effect':"/I'fekt/",
    'effort':"/'ef@t/",
    'egg':"/eg/",
    'eight':"/eIt/",
    'either':"/'aIDa(r); 'i:D@(r)/",
    'elder':"/'eld@(r)/",
    'electric':"/I'lektrIk/",
    'electronic':"/ˌelek'trQnIk/",
    'elephant':"/'elIf@nt/",
    'else':"/els/",
    'email':"/'i:meIl/",
    'emperor':"/'emp@r@(r)/",
    'employ':"/Im'plOI/",
    'empty':"/'empti/",
    'encourage':"/In'kArIdZ",
    'end':"/end/",
    'enemy':"/enimi/",
    'energy':"/'en@dZi/",
    'engine':"/'endZIn/",
    'engineer':"/ˌendZI'nI@(r)/",
    'England':"/'INgl@nd/",
    'English':"/'INglIS/",
    'enjoy':"/In'dZOI/",
    'enough':"/I'nAf/",
    'enter':"/ent@(r)/",
    'entrance':"/'entr@ns/",
    'envelope':"/'env@l@Up/",
    'environment':"/In'vaIr@nm@nt/",
    'equal':"/'i:kw@l/",
    'equipment':"/I'kwIpm@nt/",
    'error':"/'er@(r); 'er@r/",
    'especially':"/I'speSli/",
    'Europe':"/'jU@r@p/",
    'European':"/jU@r@'pi:@n/",
    'even':"/'i:vn/",
    'evening':"/'i:vvnIN/",
    'event':"/I'vent/",
    'ever':"/'ev@(r)/",
    'every':"/'evri/",
    'everybody':"/'evribodi/",
    'everyday':"/'evrideI/",
    'everyone':"/'evrIwVn/",
    'everything':"/'evrITIN/",
    'everywhere':"/'evriwea(r)/",
    'exact':"/Ig'zækt/",
    'exam':"/Ig'zæm/",
    'example':"/Ig'zA:mpl/",
    'excellent':"/'eks@l@nt/",
    'except':"/Ik'sept/",
    'exchange':"/Iks'tSeIndZ/",
    'excite':"/Ik'saIt/",
    'exciting':"/Ik'saItIN/",
    'excuse':"/Ik'skju:z/",
    'exercise':"/'eks@saIz/",
    'exhibition':"/ˌeksI'bISn/",
    'exist':"/Ig'zIst/",
    'exit':"/'egzit; 'eksit/",
    'expect':"/Ik'spekt/",
    'expensive':"/Ik'spensIv/",
    'experience':"/Ik'spi@ri@ns/",
    'experiment':"/Ik'sperIm@nt/",
    'expert':"/'eksp3:t/",
    'explain':"/Ik'spleIn/",
    'explode':"/Ik'spl@ud/",
    'explore':"/Ik'splO:(r)/",
    'express':"/Ik'spres/",
    'expression':"/Ik'spreSn/",
    'extra':"/'ekstra/",
    'extraordinary':"/Ik'strO:dni/",

    # F
    'face':"/feIs/",
    'fact':"/fækt/",
    'factory':"/'fæktri; 'fAkt@ri/",
    'fail':"/feIl/",
    'fair':"/fea(r)/",
    'fall':"/fO:l/",
    'false':"/fO:ls/",
    'familiar':"/f@'mIli@(r)/",
    'family':"/'fæmili/",
    'famous':"/'feIm@s/",
    'fan':"/fæn/",
    'fantastic':"/fæn'tæstIk/",
    'far':"/fA:(r)/",
    'farm':"/fA:m/",
    'farmer':"/'fA:m@(r)/",
    'fashion':"/'fæSn/",
    'fast':"/fA:st; fæst/",
    'fat':"/fæt/",
    'father':"/'fA:D@(r)/",
    'fault':"/fO:lt/",
    'favor':"/'feIv@(r)/",
    'favorite':"/'feIv@rIt/",
    'fear':"/fIa(r); fIr/",
    'feather':"/'feDa(r)/",
    'February':"/'febru@ri/",
    'feed':"/fi:d/",
    'feel':"/fi:l/",
    'feeling':"/'fi:lIN/",
    'fell':"/fel/",
    'fellow':"/'fel@U/",
    'female':"/'fi:meIl/",
    'fence':"/fens/",
    'festival':"/'festIvl/",
    'fetch':"/fetS/",
    'few':"/fju:/",
    'field':"/fi:ld/",
    'fifteen':"/ˌfIf'ti:n/",
    'fifth':"/fIfT/",
    'fifty':"/'fIfti/",
    'fight':"/faIt/",
    'fill':"/fIl/",
    'film':"/fIlm/",
    'final':"/'faInl/",
    'find':"/faInd/",
    'fine':"/faIn/",
    'finger':"/'fINga(r)/",
    'finish':"/'finIS/",
    'fire':"/'faIa(r)/",
    'firm':"/f3:m/",
    'first':"/f3:st/",
    'fish':"/fIS/",
    'fit':"/fIt/",
    'fitness':"/'fitn@s/",
    'five':"/faIv/",
    'fix':"/fIks/",
    'flag':"/flæg/",
    'flat':"/flæt/",
    'flight':"/flaIt/",
    'floor':"/flO:(r)/",
    'flower':"/'flaua(r)/",
    'fly':"/flaI/",
    'fog':"/fQg/",
    'follow':"/'fQl@U/",
    'food':"/fu:d/",
    'fool':"/fu:l/",
    'foot':"/fUt/",
    'football':"/'fUtbO:l/",
    'for':"/fO:(r); f@(r)/",
    'force':"/fO:s/",
    'foreign':"/'fOr@n; 'fO:r@n/",
    'forest':"/'fQrIst/",
    'forget':"/f@'get/",
    'form':"/fO:m/",
    'former':"/'fO:m@(r)/",
    'fortnight':"/'fO:tnaIt/",
    'fortunate':"/'fO:tS@n@t/",
    'fortunately':"/'fO:tS@n@tli/",
    'forty':"/'fO:ti/",
    'forward':"/'fO:w@d/",
    'found':"/faUnd/",
    'fox':"/fQks/",
    'free':"/fri:/",
    'freedom':"/'fri:d@m/",
    'freeze':"/fri:z/",
    'fresh':"/freS/",
    'Friday':"/'fraIdeI/",
    'fridge':"/frIdZ/",
    'friend':"/frend/",
    'friendly':"/'frendli/",
    'friendship':"/'frendSIp/",
    'from':"/frm; frqm; frAm/",
    'front':"/frVnt/",
    'fruit':"/fru:t/",
    'full':"/fUl/",
    'fun':"/fVn/",
    'funny':"/'fVni/",
    'furniture':"/'f3:nItSa(r)/",

    # G-H
    'gain':"/geIn/",
    'game':"/geIm/",
    'gap':"/gæp/",
    'garage':"/'gærA:Z; g@'rA:Z/",
    'garden':"/'gA:dn/",
    'gate':"/geIt/",
    'general':"/'dZenrl/",
    'generation':"/ˌdZen'reISn/",
    'gentle':"/'dzentl/",
    'gentleman':"/'dzentlm@n/",
    'geography':"/dZI'Qgrafi/",
    'gesture':"/'dZestSa(r)/",
    'get':"/get/",
    'gift':"/gIft/",
    'girl':"/g3:l/",
    'give':"/gIv/",
    'glad':"/glæd/",
    'glass':"/glA:s; glæs/",
    'globe':"/gl@Ub/",
    'glory':"/'glO:ri/",
    'glove':"/glVv/",
    'go':"/g@U/",
    'goal':"/g@Ul/",
    'god':"/gQd/",
    'gold':"/g@Uld/",
    'golden':"/'g@Uld@n/",
    'good':"/gUd/",
    'goodbye':"/ˌgUd'baI/",
    'goose':"/gu:s/",
    'government':"/'gVvnm@nt/",
    'grade':"/greId/",
    'grammar':"/'græma(r)/",
    'grandchild':"/'græn(t)SaIld/",
    'granddaughter':"/'grændO:t@(r)/",
    'grandfather':"/'grænfa:D@(r)/",
    'grandmother':"/'grænmAD@(r)/",
    'grandparent':"/'grænpe@r@nt/",
    'grandson':"/'grAnsVn/",
    'grass':"/grA:s; græs/",
    'grey':"/greI/",
    'great':"/greIt/",
    'green':"/gri:n/",
    'greeting':"/'gri:tIN/",
    'ground':"/graund/",
    'group':"/gru:p/",
    'grow':"/gr@U/",
    'growth':"/gr@UT/",
    'guard':"/gA:d/",
    'guess':"/ges/",
    'guest':"/gest/",
    'guide':"/gaId/",
    'guitar':"/gI'tA:(r)/",
    'gun':"/gAn/",
    'habit':"/'hæbIt/",
    'hair':"/hea(r)/",
    'half':"/hA:f; hæf/",
    'hall':"/hO:l/",
    'ham':"/hæm/",
    'hamburger':"/'hæmb3:g@(r)/",
    'hand':"/hænd/",
    'handbag':"/'hænbæg/",
    'handwriting':"/'hændraItIN/",
    'hang':"/hæN/",
    'happy':"/'hæpi/",
    'hard':"/hA:d/",
    'hardly':"/'hA:dli/",
    'harvest':"/'hA:vIst/",
    'hat':"/hæt/",
    'have':"/hæv; h@v/",
    'head':"/hed/",
    'headache':"/'hedeIk/",
    'health':"/helT/",
    'healthy':"/'helTi/",
    'hear':"/hIa(r)/",
    'heart':"/hA:t/",
    'heat':"/hi:t/",
    'heaven':"/'hevn/",
    'height':"/haIt/",
    'helicopter':"/'helIkQpt@(r)/",
    'hello':"/h@'l@U; 'hel@U/",
    'help':"/help/",
    'helpful':"/'helpfl/",
    'hen':"/hen/",
    'her':"/h3:(r); h3:r; @(r)",
    'here':"/hIa(r)/",
    'hero':"/'hI@r@U/",
    'herself':"/h3:'self;",
    'hide':"/haId/",
    'high':"/haI/",
    'hill':"/hIl/",
    'him':"/hIm; Im; @m/",
    'himself':"/hIm'self/",
    'his':"/hIz; Iz/",
    'history':"/'histri/",
    'hit':"/hIt/",
    'hobby':"/'hQbi/",
    'hold':"/h@Uld/",
    'hole':"/h@Ul/",
    'holiday':"/'hql@deI/",
    'home':"/h@Um/",
    'homework':"/'h@Umw3:k/",
    'honest':"/'QnIst/",
    'hope':"/h@Up/",
    'horse':"/hO:s/",
    'hospital':"/'hQspItl/",
    'host':"/h@ust/",
    'hot':"/Qt/",
    'hotel':"/h@U'tel/",
    'hour':"/'aU@(r)/",
    'house':"/haUs/",
    'how':"/haU/",
    'however':"/haU'eva(r)/",
    'huge':"/hju:dZ/",
    'human':"/'hju:m@n/",
    'humorous':"/'hju:m@r@s/",
    'hundred':"/'hAndr@d/",
    'hungry':"/'hANgri/",
    'hunt':"/hVnt/",
    'hurry':"/'hArI/",
    'hurt':"/h3:t/",
    'husband':"/'hVzb@nd/",
})

print(f"Phonetic dictionary built: {len(PHON)} entries")


def main():
    with open(INPUT, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    updated = 0
    still_missing = []
    
    for entry in data:
        w = entry['word']
        ph = entry['phonetic']
        
        # 检查是否需要更新
        is_placeholder = (
            ph == f"/{w}/" or 
            (ph.startswith('/') and ph.endswith('/') and len(ph) < len(w) + 4 and '/' not in ph[1:-1]) or
            ph == f"/{w.lower()}/"
        )
        
        if is_placeholder:
            # 尝试多种方式查找音标
            new_ph = None
            
            # 直接查找
            if w in PHON:
                new_ph = PHON[w]
            elif w.lower() in PHON:
                new_ph = PHON[w.lower()]
            else:
                # 去掉特殊字符后查找
                w_clean = re.sub(r"[./\-]", "", w)
                if w_clean in PHON:
                    new_ph = PHON[w_clean]
            
            if new_ph:
                entry['phonetic'] = new_ph
                updated += 1
            else:
                still_missing.append(w)
    
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Updated: {updated} entries")
    print(f"Still missing: {len(still_missing)}")
    
    if still_missing[:20]:
        print("Still missing (first 20):")
        for w in still_missing[:20]:
            print(f"  {w}")
    if len(still_missing) > 20:
        print(f"  ... and {len(still_missing)-20} more")


if __name__ == '__main__':
    main()
