#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
补全 dictation_en_g8.json 中缺少真实音标的词汇
"""

import json

INPUT = '/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/dictation_en_g8.json'
OUTPUT = '/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/dictation_en_g8.json'

# 大量补充音标
EXTRA_PHONETICS = {
    'Internet/internet': "/'ɪntənet/",
    'allow': "/əˈlaʊ/",
    'arrive': "/əˈraɪv/",
    'as long as': "/æz lɒŋ æz/",
    'as soon as': "/æz suːn æz/",
    'at least': "/æt liːst/",
    'bed': "/bed/",
    'belong': "/bɪˈlɒŋ/",
    'belt': "/belt/",
    'blend': "/blend/",
    'break down': "/breɪk daʊn/",
    'buy': "/baɪ/",
    'celebration': "/ˌselɪˈbreɪʃn/",
    'center': "/ˈsentə(r)/",
    'century': "/ˈsentʃəri/",
    'ceremony': "/ˈserəməni/",
    'certain': "/ˈsɜːtn/",
    'certificate': "/səˈtɪfɪkət/",
    'chair': "/tʃeə(r)/",
    'chalk': "/tʃɔːk/",
    'chance': "/tʃɑːns/",
    'change': "/tʃeɪndʒ/",
    'channel': "/ˈtʃænl/",
    'chapter': "/ˈtʃæptə(r)/",
    'charge': "/tʃɑːdʒ/",
    'cheap': "/tʃiːp/",
    'checkout': "/ˈtʃekaʊt/",
    'cheer': "/tʃɪə(r)/",
    'chemistry': "/ˈkemɪstri/",
    'chess': "/tʃes/",
    'child': "/tʃaɪld/",
    'choice': "/tʃɔɪs/",
    'church': "/tʃɜːtʃ/",
    'circle': "/ˈsɜːkl/",
    'citizen': "/ˈsɪtɪzn/",
    'city': "/ˈsɪti/",
    'claim': "/kleɪm/",
    'class': "/klɑːs; klæs/",
    'classmate': "/ˈklɑːsmeɪt/",
    'classroom': "/ˈklɑːsruːm/",
    'clear': "/klɪə(r); klɪr/",
    'clever': "/ˈlevə(r)/",
    'climate': "/ˈklaɪmɪt/",
    'clothes': "/kləʊðz/",
    'cloudy': "/ˈklaʊdi/",
    'club': "/klʌb/",
    'clue': "/kluː/",
    'coach': "/kəʊtʃ/",
    'coat': "/kəʊt/",
    'coin': "/kɔɪn/",
    'cold': "/kəʊld/",
    'come across': "/kʌm əˈkrɒs/",
    'comfort': "/ˈkʌmft/",
    'common': "/ˈkɒmən/",
    'communicate': "/kəˈmjuːnɪkeɪt/",
    'company': "/ˈkʌmpəni/",
    'compete': "/kəmˈpiːt/",
    'complain': "/kəmˈpleɪn/",
    'complex': "/ˈkɒmpleks; kəmˈpleks/",
    'composition': "/ˌkɒmpəˈzɪʃn/",
    'condition': "/kənˈdɪʃn/",
    'confuse': "/kənˈfjuːz/",
    'congratulation': "/kənˌɡrætʃuˈleɪʃn/",
    'connect': "/kəˈnekt/",
    'connection': "/kəˈnekʃn/",
    'consist': "/kənˈsɪst/",
    'construct': "/kənˈstrʌkt/",
    'consume': "/kənˈsjuːm/",
    'contain': "/kənˈteɪn/",
    'contribute': "/kənˈtrɪbjuːt/",
    'convenient': "/kənˈviːniənt/",
    'conversation': "/ˌkɒnvəˈseɪʃn/",
    'convince': "/kənˈvɪns/",
    'cookie': "/ˈkʊki/",
    'cool': "/kuːl/",
    'cooperate': "/kəʊˈɒpəreɪt/",
    'corner': "/ˈkɔːnə(r)/",
    'correction': "/kəˈrekʃn/",
    'country': "/ˈkʌntri/",
    'coupon': "/ˈkuːpɒn/",
    'courage': "/ˈkʌrɪdʒ/",
    'course': "/kɔːs/",
    'cousin': "/ˈkʌzn/",
    'cow': "/kaʊ/",
    'crash': "/kræʃ/",
    'crossing': "/ˈkrɒsɪŋ/",
    'cruel': "/ˈkruːəl/",
    'cure': "/kjʊə(r); kjʊr/",
    'current': "/ˈkʌrənt/",
    'custom': "/ˈkʌstəm/",
    'customer': "/ˈkʌstəmə(r)/",
    'dad': "/dæd/",
    'dairy': "/ˈdeəri/",
    'damage': "/ˈdæmɪdʒ/",
    'dare': "/deə(r)/",
    'daughter': "/ˈdɔːtə(r)/",
    'day': "/deɪ/",
    'dead': "/ded/",
    'deal with': "/diːl wɪð/",
    'decline': "/dɪˈklaɪn/",
    'dedicate': "/ˈdedɪkeɪt/",
    'deep': "/diːp/",
    'deeply': "/ˈdiːpli/",
    'define': "/dɪˈfaɪn/",
    'degree': "/dɪˈɡriː/",
    'delay': "/dɪˈleɪ/",
    'delicious': "/dɪˈlɪʃəs/",
    'delight': "/dɪˈlaɪt/",
    'deliver': "/dɪˈlɪvə(r)/",
    'demand': "/dɪˈmɑːnd/",
    'deny': "/dɪˈnaɪ/",
    'depart': "/dɪˈpɑːt/",
    'deposit': "/dɪˈpɒzɪt/",
    'depress': "/dɪˈpres/",
    'depth': "/depθ/",
    'derive': "/dɪˈraɪv/",
    'desert': "/ˈdezət/",
    'deserve': "/dɪˈzɜːv/",
    'design': "/dɪˈzaɪn/",
    'desire': "/dɪˈzaɪə(r)/",
    'desk': "/desk/",
    'despair': "/dɪˈspeə(r)/",
    'destroy': "/dɪˈstrɔɪ/",
    'detail': "/ˈdiːteɪl/",
    'detect': "/dɪˈtekt/",
    'dialogue': "/ˈdaɪəlɒɡ/",
    'diamond': "/ˈdaɪəmənd/",
    'dictionary': "/ˈdɪkʃənri/",
    'diet': "/ˈdaɪət/",
    'difference': "/ˈdɪfrəns/",
    'different': "/ˈdɪfrənt/",
    'difficult': "/ˈdɪfɪkəlt/",
    'digital': "/ˈdɪdʒɪtl/",
    'dine': "/daɪn/",
    'dinner': "/ˈdɪnə(r)/",
    'direct': "/dɪˈrekt; daɪˈrekt/",
    'direction': "/daɪˈrekʃn; dɪˈrekʃn/",
    'director': "/dɪˈrektə(r); daɪˈrektə(r)/",
    'dirty': "/ˈdɜːti/",
    'disappoint': "/ˌdɪsəˈpɔɪnt/",
    'disaster': "/dɪˈzɑːstə(r)/",
    'discuss': "/dɪˈskʌs/",
    'discussion': "/dɪˈskʌʃn/",
    'disease': "/dɪˈziːz/",
    'dish': "/dɪʃ/",
    'disk': "/dɪsk/",
    'dismiss': "/dɪˈmɪs/",
    'distance': "/ˈdɪstəns/",
    'distant': "/ˈdɪstənt/",
    'distinguish': "/dɪˈstɪŋɡwɪʃ/",
    'district': "/ˈdɪstrɪkt/",
    'divide': "/dɪˈvaɪd/",
    'divorce': "/dɪˈvɔːs/",
    'do': "/duː; də/",
    'document': "/ˈdɒkjumənt/",
    'dog': "/dɒɡ/",
    'doll': "/dɒl/",
    'dollar': "/ˈdɒlə(r)/",
    'door': "/dɔː(r)/",
    'double': "/ˈdʌbl/",
    'doubt': "/daʊt/",
    'down': "/daʊn/",
    'dozen': "/ˈdʌzn/",
    'drag': "/dræɡ/",
    'draw': "/drɔː/",
    'dream': "/driːm/",
    'dress': "/dres/",
    'drink': "/drɪŋk/",
    'drive': "/draɪv/",
    'drop': "/drɒp/",
    'drug': "/drʌɡ/",
    'drum': "/drʌm/",
    'dry': "/draɪ/",
    'duck': "/dʌk/",
    'due': "/djuː/",
    'during': "/ˈdjʊərɪŋ/",
    'each': "/iːtʃ/",
    'eager': "/ˈiːɡə(r)/",
    'ear': "/ɪə(r)/",
    'early': "/ˈɜːli/",
    'east': "/iːst/",
    'eastern': "/ˈiːstən/",
    'easy': "/ˈiːzi/",
    'eat': "/iːt/",
    'effect': "/ɪˈfekt/",
    'egg': "/eg/",
    'eight': "/eɪt/",
    'either': "/ˈaɪðə(r); ˈiːðə(r)/",
    'elder': "/ˈeldə(r)/",
    'electric': "/ɪˈlektrɪk/",
    'electronic': "/ˌelekˈtrɒnɪk/",
    'elephant': "/ˈelɪfənt/",
    'else': "/els/",
    'email': "/ˈiːmeɪl/",
    'emperor': "/ˈempərə(r)/",
    'employ': "/ɪmˈplɔɪ/",
    'empty': "/ˈempti/",
    'end': "/end/",
    'enemy': "/enimi/",
    'energy': "/ˈenədʒi/",
    'engine': "/ˈendʒɪn/",
    'engineer': "/ˌendʒɪˈnɪə(r)/",
    'England': "/ˈɪŋɡlənd/",
    'English': "/ˈɪŋɡlɪʃ/",
    'enjoy': "/ɪnˈdʒɔɪ/",
    'enter': "/entə(r)/",
    'entrance': "/ˈentrəns/",
    'envelope': "/ˈenvələʊp/",
    'environment': "/ɪnˈvaɪrənmənt/",
    'equal': "/ˈiːkwəl/",
    'equipment': "/ɪˈkwɪpmənt/",
    'error': "/ˈerə(r); ˈerər/",
    'especially': "/ɪˈspeʃli/",
    'Europe': "/ˈjʊərəp/",
    'European': "/jʊərəˈpiːən/",
    'even': "/ˈiːvn/",
    'evening': "/ˈiːvnɪŋ/",
    'event': /ɪ'vent/,
    'ever': '/'ev@(r)/,
    'every': '/'evri/,
    'everybody': '/'evribodi/',
    'everyday': /'evrideI/,
    'everyone': /'evrIwVn/,
    'everything': /'evrITIN/,
    'everywhere': /'evriwea(r)/,
    'exact': /Ig'zækt/,
    'exam': /Ig'zæm/,
    'example': /Ig'zA:mpl/,
    'excellent': /'eks@l@nt/,
    'except': /Ik'sept/,
    'exchange': /Iks'tSeIndZ/,
    'excite': /Ik'saIt/,
    'exciting': /Ik'saItIN/,
    'excuse': /Ik'skju:z/,
    'exercise': /'eks@saIz/,
    'exhibition': /,eksI'bISn/,
    'exist': /Ig'zIst/,
    'exit': /'egzIt; 'eksIt/,
    'expect': /Ik'spekt,
    'expensive': /Ik'spensIv/,
    'experience': /Ik'spi@ri@ns/,
    'experiment': /Ik'sperIm@nt/,
    'expert': /'eksp3:t,
    'explain': /Ik'spleIn/,
    'explorer': /Ik'splO:r@(r)/,
    'express': /Ik'spres/,
    'expression': /Ik'spreSn; ek'spreSn/,
    'extra': /'ekstra/,
    'extraordinary': /Ik'strO:dni/,
    'face': /feIs/, 'fact': /fækt/, 'factory': /'fæktri; 'fAkt@ri/, 'fail': /feIl/, 'fair': /fea(r)/, 'fall': /fO:l/, 'false': /fO:ls/,
    'familiar': /f@'mIlIa(r)/, 'family': /'fæmili/, 'famous': /'feIm@s/, 'fan': /fæn/, 'fantastic': /fæn'tæstIk/, 'far': /fA:(r)/, 'farm': /fA:m/, 'farmer': /'fA:m@(r)/, 'fashion': /'fæSn/, 'fast': /fA:st; fæst/, 'fat': /fæt/, 'father': /'fA:D@(r)/, 'fault': /fO:lt/, 'favor': /'feIv@(r)/, 'favorite': /'feIv@rIt/, 'feather': /'feDa(r)/, 'February': /'febru@ri/, 'feed': /fi:d/, 'feel': /fi:l/, 'feeling': /'fi:lIN/, 'fell': /fel/, 'fellow': /'fel@U/, 'female': /'fi:meIl/, 'fence': /fens/, 'festival': /'festIvl/, 'fetch': /fetS/, 'few': /fju:/, 'field': /fi:ld/, 'fifteen': /,fIf'ti:n/, 'fifth': /fIfT/, 'fifty': /'fIfti/, 'fight': /faIt/, 'fill': /fIl/, 'film': /fIlm/, 'final': /'faInl/, 'find': /faInd/, 'fine': /faIn/, 'finish': /'finIS/, 'fire': /'faIa(r)/, 'firm': /f3:m/, 'first': /f3:st/, 'fish': /fIS/, 'fit': /fIt/, 'fitness': /'fitn@s/, 'five': /faIv/, 'fix': /fIks/, 'flag': /flæg/, 'flat': /flæt/, 'flight': /flaIt/, 'floor': /flO:(r)/, 'flower': /'flaua(r)/, 'fog': /fQg/, 'follow': /'fQl@U/, 'food': /fu:d/, 'fool': /fu:l/, 'foot': /fUt/, 'football': /'fUtbO:l/, 'for': /fO:(r); f@(r)/, 'force': /fO:s/, 'forest': /'fQrIst/, 'forget': /f@'get/, 'form': /fO:m/, 'former': /'fO:m@(r)/, 'fortnight': /'fO:tnaIt/, 'fortunate': /'fO:tS@n@t/, 'fortunately': /'fO:tS@n@tli/, 'forty': /'fO:ti/, 'found': /faUnd/, 'free': /fri:/, 'freedom': /'fri:d@m/, 'freeze': /fri:z/, 'Friday': /'fraIdeI/, 'fridge': /frIdZ/, 'friend': /frend/, 'friendly': /'frendli/, 'friendship': /'frendSIp/, 'from': /frm; frqm; frAm/, 'front': /frVnt/, 'fruit': /fru:t/, 'full': /fUl/, 'fun': /fVn/, 'funny': /'fVni/, 'furniture': /'f3:nItSa(r)/,
    'gain': /geIn/, 'game': /geIm/, 'gap': /gæp/, 'garage': /'gærA:Z; g@'rA:Z/, 'garden': /'gA:dn/, 'gate': /geIt/, 'general': /'dZenrl/, 'generation': /,dZen'reISn/, 'gentle': /'dzentl/, 'gentleman': /'dzentlm@n/, 'geography': /dZI'Qgrafi/, 'gesture': /'dZestSa(r)/, 'get': /get/, 'gift': /gIft/, 'girl': /g3:l/, 'give': /gIv/, 'glad': /glæd/, 'glass': /glA:s; glæs/, 'globe': /gl@Ub/, 'glory': /'glO:ri/, 'glove': /glVv/, 'go': /g@U/, 'goal': /g@Ul/, 'god': /gQd/, 'gold': /g@Uld/, 'golden': /'g@Uld@n/, 'good': /gUd/, 'goodbye': /ˌgUd'baI/, 'goose': /gu:s/, 'government': /'gVvnm@nt/, 'grade': /greId/, 'grammar': /'græma(r)/, 'grandchild': /'græn(t)SaIld/, 'granddaughter': /'grændO:t@(r)/, 'grandfather': /'grænfa:D@(r)/, 'grandmother': /'grænmAD@(r)/, 'grandparent': /'grænpe@r@nt/, 'grandson': /'grAnsVn/, 'grass': /grA:s; græs/, 'grey': /greI/, 'great': /greIt/, 'green': /gri:n/, 'greeting': /'gri:tIN/, 'ground': /graund/, 'group': /gru:p/, 'growth': /gr@UT/, 'guard': /gA:d/, 'guess': /ges/, 'guest': /gest/, 'guide': /gaId/, 'guitar': /gI'tA:(r)/, 'gun': /gAn/, 'habit': /'hæbIt/, 'hair': /hea(r)/, 'half': /hA:f; hæf/, 'hall': /hO:l/, 'ham': /hæm/, 'hamburger': /'hæmb3:g@(r)/, 'hand': /hænd/, 'handbag': /'hænbæg/, 'handwriting': /'hændraItIN/, 'hang': /hæN/, 'happy': /'hæpi/, 'hard': /hA:d/, 'harvest': /'hA:vIst/, 'hat': /hæt/, 'have': /hæv; h@v/, 'head': /hed/, 'health': /helT/, 'healthy': /'helTi/, 'hear': /hIa(r)/, 'heart': /hA:t/, 'heat': /hi:t/, 'heaven': /'hevn/, 'height': /haIt/, 'helicopter': /'helIkQpt@(r)/, 'hello': /h@'l@U/, 'help': /help/, 'helpful': /'helpfl/, 'her': /h3:(r); h3:r/, 'here': /hIa(r)/, 'hero': /'hI@r@U/, 'hide': /haId/, 'high': /haI/, 'hill': /hIl/, 'him': /hIm/, 'himself': /hIm'self/, 'his': /hIz; Iz/, 'history': /'histri/, 'hit': /hIt/, 'hobby': /'hQbi/, 'hold': /h@Uld/, 'hole': /h@Ul/, 'home': /h@Um/, 'homework': /'h@Umw3:k/, 'honest': /'QnIst/, 'hope': /h@Up/, 'horse': /hO:s/, 'hospital': /'hQspItl/, 'host': /h@ust/, 'hot': /Qt/, 'hotel': /h@U'tel/, 'hour': /'aU@(r)/, 'house': /haUs/, 'how': /haU/, 'huge': /hju:dZ/, 'humorous': /'hju:m@r@s/, 'hundred': /'hAndr@d/, 'hungry': /'hANgri/, 'hunt': /hVnt/, 'hurry': /'hArI/, 'husband': /'hVzb@nd/,
}

def main():
    with open(INPUT, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    updated = 0
    still_missing = []
    
    for entry in data:
        w = entry['word']
        ph = entry['phonetic']
        
        # 检查是否需要更新（占位符格式）
        if ph == f"/{w}/" or '/{w}' in ph or ph.startswith(f'/{{'):
            if w in EXTRA_PHONETICS:
                entry['phonetic'] = EXTRA_PHONETICS[w]
                updated += 1
            else:
                still_missing.append(w)
    
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Updated: {updated} entries")
    print(f"Still missing phonetics: {len(still_missing)}")
    if still_missing[:20]:
        print("Still missing (first 20):", still_missing[:20])
    if len(still_missing) > 20:
        print(f"... and {len(still_missing)-20} more")

if __name__ == '__main__':
    main()
