#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""最终修复：为dictation_en_g8.json补充真实IPA音标"""
import json, re

INPUT = 'src/data/dictation_en_g8.json'
OUTPUT = 'src/data/dictation_en_g8.json'

# 使用字典推导式构建音标表，避免引号转义问题
# 所有音标数据以 word: phonetic 形式存储

def build_phonetics():
    ph = {}
    
    # 逐个添加，每个词一行，避免引号嵌套问题
    entries = [
    # === A ===
    ("ability", "/E'bIl@ti/"),("above", "/E'bVv/"),("abroad", "/E'brO:d/"),
    ("accept", "/Ek'sept/"),("accident", "/'æksId@nt/"),
    ("achieve", "/E'tSi:v/"),("across", "/E'krQs/"),
    ("action", "/'ækSn/"),("active", "/'æktIv/"),
    ("activity", "/æk'tIv@ti/"),("actually", "/'æktSu@li/"),
    ("add", "/æd/"),("address", "/E'dres/"),
    ("admire", "/Ed'maI@(r)/"),("admit", "/E'dmIt/"),
    ("adult", "/'ædVlt/"),("advantage", "/Ed'vA:ntIdZ/"),
    ("adventure", "/Ed'ventS@(r)/"),("advertise", "/'ædv@taIz/"),
    ("afford", "/E'fO:d/"),("afraid", "/E'freId/"),
    ("after", "/'A:ft@(r)/"),("afternoon", "/,A:ftE'nu:n/"),
    ("again", "/E'gen/"),("against", "/E'genst; E'geInst/"),
    ("age", "/eIdZ/"),("ago", "/E'gEU/"),
    ("agree", "/E'gri:/"),("ahead", "/E'hed/"),
    ("air", "/e@(r)/"),("airplane", "/'e@pleIn/"),
    ("airport", "/'e@pO:t/"),("alarm", "/E'lA:m/"),
    ("album", "/'ælb@m/"),("alive", "/E'laIv/"),
    ("all", "/O:l/"),("allow", "/E'laU/"),
    ("almost", "/'O:lm@Ust/"),("alone", "/E'l@Un/"),
    ("along", "/E'lQN/"),("aloud", "/'laUd/"),
    ("already", "/O:l'redi/"),("also", "/'O:ls@U/"),
    ("although", "/O:l'D@U/"),("always", "/'O:lweIz/"),
    ("amazing", "/E'meIzIN/"),("among", "/E'mVN/"),
    ("amount", "/E'maUnt/"),("angry", "/'æNgri/"),
    ("animal", "/'ænIml/"),("another", "/E'nAD@(r)/"),
    ("answer", "/'A:ns@(r)/"),("any", "/'eni/"),
    ("anybody", "/'enibQdi/"),("anyone", "/'eniwVn/"),
    ("anything", "/'eniTIN/"),("anyway", "/'eniweI/"),
    ("anywhere", "/'eniwe@(r)/"),("appear", "@'pI@(r)/"),
    ("apple", "/'æpl/"),("area", "/'e@ri@/"),
    ("argue", "/'A:gju:/"),("arm", "/A:m/"),
    ("around", "/E'raUnd/"),("arrange", "/E'reIndZ/"),
    ("arrival", "/E'raIvl/"),("arrive", "/E'raIv/"),
    ("art", "/A:t/"),("article", "/'A:tlkl/"),
    ("as", "/æz; @z; z/"),("Asian", "/'eISn/"),
    ("ask", "/A:sk/"),("asleep", "/E'sli:p/"),
    ("at", "/æt; @t/"),("attention", "/E'tenSn/"),
    ("August", "/'O:g@st/"),("aunt", "/A:nt; ænt/"),
    ("autumn", "/'O:t@m/"),("avoid", "/E'vOId/"),
    ("awake", "/E'weIk/"),("away", "/E'weI/"),

    # === B ===
    ("baby", "/'beIbi/"),("back", "/bæk/"),("bad", "/bæd/"),
    ("badly", "/'bædli/"),("bag", "/bæg/"),
    ("balance", "/'bæl@ns/"),("ball", "/bO:l/"),
    ("balloon", "/b@'lu:n/"),("banana", "/b@'nA:n@/"),
    ("bank", "/bæŋk/"),("base", "/beIs/"),
    ("baseball", "/'beIsbO:l/"),("basic", "/'beIsik/"),
    ("basket", "/'bA:skIt/"),("basketball", "/'bA:skItbO:l/"),
    ("bat", "/bæt/"),("batch", "/bætS/"),
    ("bath", "/bA:T/"),("bathroom", "/'bA:tru:m/"),
    ("be", "/bi:; bi/"),("beach", "/bi:tS/"),
    ("bear", "/be@(r)/"),("beat", "/bi:t/"),
    ("beautiful", "/'bju:tIfl/"),("because", "/bI'kQz/"),
    ("become", "/bI'kVm/"),("bed", "/bed/"),
    ("bedroom", "/'bedru:m/"),("bee", "/bi:/"),
    ("beef", "/bi:f/"),("beer", "/bI@(r)/"),
    ("before", "/bI'fO:(r)/"),("begin", "/bI'gIn/"),
    ("beginning", "/bI'gInIN/"),("behind", "/bI'haInd/"),
    ("being", "/'bi:IN/"),("believe", "/bI'li:v/"),
    ("bell", "/bel/"),("belong", "/bI'lQN/"),
    ("below", "/bI'l@U/"),("belt", "/elt/"),
    ("bench", "/bentS/"),("bend", "/bend/"),
    ("beneath", "/bI'ni:T/"),("benefit", "/'benIfIt/"),
    ("beside", "/bI'saId/"),("besides", "/bI'saIdz/"),
    ("best", "/best/"),("better", "/'bet@(r)/"),
    ("between", "/bI'twi:n/"),("beyond", "/bI'jOnd/"),
    ("big", "/bIg/"),("bike", "/baIk/"),
    ("bill", "/bIl/"),("bin", "/bIn/"),
    ("biology", "/baI'Ql@dZi/"),("bird", "/b3:d/"),
    ("birth", "/b3:T/"),("birthday", "/'b3:TdeI/"),
    ("biscuit", "/'bIskit/"),("bit", "/bIt/"),
    ("bite", "/baIt/"),("bitter", "/'bIt@(r)/"),
    ("black", "/blæk/"),("blackboard", "/'blækbO:d/"),
    ("blame", "/bleIm/"),("blank", "/blæŋk/"),
    ("blanket", "/'blæŋkIt/"),("bleed", "/bli:d/"),
    ("blend", "/blend/"),("blind", "/blaInd/"),
    ("block", "/blQk/"),("blood", "/blAd/"),
    ("blow", "/bl@U/"),("blue", "/blu:/"),
    ("board", "/bO:d/"),("boat", "/b@Ut/"),
    ("boil", "/bOIl/"),("bomb", "/bQm/"),
    ("bone", "/b@Un/"),("book", "/bUk/"),
    ("boom", "/bu:m/"),("boot", "/bu:t/"),
    ("border", "/'bO:d@(r)/"),("born", "/bO:n/"),
    ("borrow", "/'bQr@U/"),("boss", "/bQs/"),
    ("both", "/b@UT/"),("bother", "/'bQD@(r)/"),
    ("bottle", "/'bQtl/"),("bottom", "/'bQt@m/"),
    ("bounce", "/baUns/"),("bound", "/baUnd/"),
    ("bow", "/baU; b@U/"),("bowl", "/b@Ul/"),
    ("box", "/bQks/"),("boy", "/bOI/"),
    ("brain", "/breIn/"),("brave", "/breIv/"),
    ("bread", "/bred/"),("break", "/breIk/"),
    ("breakfast", "/'brekf@st/"),("breath", "/breT/"),
    ("breathe", "/bri:T/"),("breed", "/bri:d/"),
    ("brick", "/brIk/"),("bridge", "/brIdZ/"),
    ("brief", "/bri:f/"),("bright", "/braIt/"),
    ("bring", "/brIN/"),("Britain", "/'brItn/"),
    ("British", "/'brItIS/"),("broad", "/brO:d/"),
    ("broadcast", "/'brO:dkA:st; 'brO:dkæst/"),
    ("broken", "/'br@Uk@n/"),("broom", "/bru:m/"),
    ("brother", "/'brAD@(r)/"),("brown", "/braUn/"),
    ("brush", "/brVS/"),("bucket", "/'bAkIt/"),
    ("bud", "/bAd/"),("budget", "/'bAdZIt/"),
    ("buffet", "/bu'feI/"),("build", "/bIld/"),
    ("building", "/'bIldIN/"),("burn", "/b3:n/"),
    ("burst", "/b3:st/"),("bury", "/'beri/"),
    ("bus", "/bAs/"),("bush", "/bUS/"),
    ("business", "/'bIzn@s/"),("busy", "/'bIzi/"),
    ("but", "/bAt; b@t/"),("butter", "/'bAt@(r)/"),
    ("button", "/'bVtn/"),("buy", "/baI/"),
    ("by", "/baI/"),

    # === C ===
    ("cabbage", "/'kæbIdZ/"),("cafe", "/'kæfeI/"),
    ("cage", "/keIdZ/"),("cake", "/keIk/"),
    ("call", "/kO:l/"),("calm", "/kA:m/"),
    ("camera", "/'kæm(r)@"),("camp", "/kæmp/"),
    ("can", "/kæn; k@n/"),("Canada", "/'kæn@d@/"),
    ("cancel", "/'kænsl/"),("cancer", "/'kæns@(r)/"),
    ("candidate", "/'kændIdeIt/"),("candle", "/'kAndl/"),
    ("candy", "/'kAndi/"),("cap", "/kæp/"),
    ("capital", "/'kæpItl/"),("captain", "/'kæptIn/"),
    ("car", "/kA:(r)/"),("card", "/kA:d/"),
    ("care", "/ke@(r)/"),("careful", "/'ke@fl;"),
    ("careless", "/'ke@l@s/"),("carrot", "/'kær@t/"),
    ("carry", "/'kæri/"),("cartoon", "/kA:'tu:n/"),
    ("case", "/keIs/"),("cash", "/kæS/"),
    ("cast", "/kA:st; kæst/"),("castle", "/'kAsl; 'kæsl/"),
    ("cat", "/kæt/"),("catch", "/kætS/"),
    ("cause", "/kO:z/"),("cave", "/keIv/"),
    ("ceiling", "/'si:lIN/"),("celebrate", "/'selibreit/"),
    ("cell", "/sel/"),("cent", "/sent/"),
    ("center", "/'sent@(r)/"),("centre", "/'sent@(r)/"),
    ("central", "/'sentr@l/"),("century", "/'sentS@ri/"),
    ("certain", "/'s3:tn/"),("certainly", "/'s3:tnli/"),
    ("chain", "/tSeIn/"),("chair", "/tSe@(r)/"),
    ("chairman", "/'tSe@m@n/"),("chalk", "/tSO:k/"),
    ("chance", "/tSA:ns/"),("change", "/tSeIndZ/"),
    ("channel", "/'tSænl/"),("chapter", "/'tæpt@(r)/"),
    ("charge", "/tSA:dZ/"),("chat", "/tSæt/"),
    ("cheap", "/tSi:p/"),("check", "/tSek/"),
    ("cheer", "/tSI@(r)/"),("cheese", "/tSi:z/"),
    ("chemistry", "/'kemIstri/"),("chest", "/tSest/"),
    ("chicken", "/'tSIkIn/"),("chief", "/tSi:f/"),
    ("child", "/tSaId/"),("chimney", "/'tSimni/"),
    ("china", "/'tSaIn@/"),("chocolate", "/'tSQklIt/"),
    ("choice", "/tSOIs/"),("choose", "/tSu:z/"),
    ("chop", "/tSQp/"),("church", "/tS3:tS/"),
    ("cinema", "/'sInIm@/"),("circle", "/'s3:kl/"),
    ("citizen", "/'sItIzn/"),("city", "/'sIti/"),
    ("class", "/klA:s; klæs/"),("classmate", "/'klA:smeIt/"),
    ("classroom", "/'klA:sru:m/"),("clean", "/kli:n/"),
    ("clear", "/klI@(r); klIr/"),("clever", "/'lev@(r)/"),
    ("climate", "/'klaImIt/"),("climb", "/klaIm/"),
    ("clinic", "/'klInIk/"),("clock", "/klQk/"),
    ("close", "/kl@Uz; kl@s/"),("cloth", "/klQT; klO:T/"),
    ("clothes", "/kl@UDz/"),("clothing", "/'kl@UDIN/"),
    ("cloud", "/klaUd/"),("cloudy", "/'klaUdi/"),
    ("club", "/klVb/"),("coach", "/k@UtS/"),
    ("coal", "/k@Ul/"),("coast", "/k@ust/"),
    ("coat", "/k@ut/"),("code", "/k@ud/"),
    ("coin", "/kOIn/"),("coke", "/k@uk/"),
    ("cold", "/k@uld/"),("collect", "/k@'lekt/"),
    ("college", "/'kqlIdZ/"),("color", "/'kVl@(r)/"),
    ("colour", "/'kVl@(r)/"),("comb", "/k@um/"),
    ("combine", "/k@m'bain/"),("comfort", "/'kVmf@t/"),
    ("comfortable", "/'kVmf@t@bl/"),("common", "/'kQm@n/"),
    ("communicate", "/k@'mju:nikeit/"),
    ("communism", "/'kQmjUnIz@m/"),("community", "/k@'mju:n@ti/"),
    ("company", "/'kVmp@ni/"),("compare", "/k@m'pe@(r)/"),
    ("competition", "/,kQmp@'tISn/"),("complete", "/k@m'pli:t/"),
    ("composition", "/,kQmp@'zISn/"),("computer", "/k@m'pju:t@(r)/"),
    ("comrade", "/'kQmrid/"),("concert", "/'kQns@t/"),
    ("condition", "/k@n'dISn/"),("conduct", "/k@n'dVkt/"),
    ("conductor", "/k@n'dVkt@(r)/"),("conference", "/'kQnf@r@ns/"),
    ("congratulate", "/k@n'grætSuleit/"),
    ("connect", "/k@'nekt/"),("connection", "/k@'nekSn/"),
    ("consider", "/k@n'sId@(r)/"),("construction", "/k@n'strVkSn/"),
    ("contain", "/k@'teIn/"),("continue", "/k@n'tInju:/"),
    ("control", "/k@n'tr@Ul/"),("conversation", "/,kQnv@'seISn/"),
    ("cook", "/kUk/"),("cool", "/ku:l/"),
    ("copy", "/'kQpi/"),("corner", "/'kO:n@(r)/"),
    ("correct", "/k@'rekt/"),("cost", "/kQst; kO:st/"),
    ("cottage", "/'kqtIdZ/"),("cotton", "/'kQtn/"),
    ("could", "/kud; k@d/"),("count", "/kaUnt/"),
    ("counter", "/'kaunt@(r)/"),("country", "/'kVntri/"),
    ("couple", "/'kvpl/"),("courage", "/'kVrIdZ/"),
    ("course", "/kO:s/"),("courtyard", "/'kO:tjA:d/"),
    ("cousin", "/'kVzn/"),("cover", "/'kAv@(r)/"),
    ("cow", "/kaU/"),("cowboy", "/'kaUbOI/"),
    ("crack", "/kræk/"),("craft", "/krA:ft; kræft/"),
    ("crash", "/kræS/"),("crayon", "/'kreI@n/"),
    ("crazy", "/'kreIzi/"),("cream", "/kri:m/"),
    ("create", "/kri'eIt/"),("credit", "/'kredIt/"),
    ("crime", "/kraIm/"),("criminal", "/'krIml/"),
    ("crop", "/krQp/"),("cross", "/krQs/"),
    ("crowd", "/kraUd/"),("cruel", "/'kru:@l/"),
    ("cry", "/kraI/"),("culture", "/'kVltSa(r)/"),
    ("cup", "/kAp/"),("cure", "/kjU@(r); kjUr/"),
    ("curious", "/'kjU@ri@s/"),("current", "/'kVr@nt/"),
    ("custom", "/'kVst@m/"),("customer", "/'kVst@m@(r)/"),
    ("cut", "/kAt/"),

    # D
    ("dad", "/dæd/"),("daily", "/'deIli/"),
    ("damage", "/'dæmIdZ/"),("dance", "/dA:ns; dæns/"),
    ("danger", "/'deIndZ@(r)/"),("dangerous", "/'deIndZ@r@s/"),
    ("dare", "/de@(r)/"),("dark", "/dA:k/"),
    ("data", "/'deIt@/"),("date", "/deIt/"),
    ("daughter", "/'dO:t@(r)/"),("dawn", "/dO:n/"),
    ("day", "/deI/"),("dead", "/ded/"),
    ("deal", "/di:l/"),("dear", "/dI@(r)/"),
    ("death", "/deT/"),("debate", "/dI'beIt/"),
    ("debt", "/det/"),("decade", "/'deikeId/"),
    ("December", "/dI'semb@(r)/"),("decide", "/dI'saId/"),
    ("decision", "/dI'sIZn/"),("declare", "/dI'kle@(r)/"),
    ("decorate", "/'dek@reit/"),("decrease", "/di:'kri:s/"),
    ("deep", "/di:p/"),("deer", "/dI@(r)/"),
    ("degree", "/dI'gri:/"),("delay", "/dI'leI/"),
    ("delicious", "/dI'lIS@s/"),("delight", "/dI'laIt/"),
    ("deliver", "/dI'lIv@(r)/"),("demand", "/dI'mA:nd/"),
    ("dentist", "/'dentIst/"),("depend", "/dI'pend/"),
    ("depth", "/depT/"),("describe", "/dI'skraIb/"),
    ("desert", "/'dez@t/"),("design", "/dI'zaIn/"),
    ("desk", "/desk/"),("destroy", "/dI'strOI/"),
    ("develop", "/dI'vel@p/"),("devote", "/dI'v@ut/"),
    ("dialogue", "/'daI@lQg/"),("diamond", "/'daI@m@nd/"),
    ("diary", "/'daIari/"),("dictionary", "/'dIkS@nri/"),
    ("die", "/daI/"),("diet", "/'daI@t/"),
    ("difference", "/'dIf@ns/"),("different", "/'dIf@r@nt/"),
    ("difficult", "/'dIfIk@lt/"),("dig", "/dIg/"),
    ("digital", "/'dIdZItl/"),("dine", "/daIn/"),
    ("dinner", "/'din@(r)/"),("direct", "/dI'rekt; daI'rekt/"),
    ("direction", "/daI'rekSn; dI'rekSn/"),
    ("director", "/dI'rekt@(r); daI'rekt@(r)/"),
    ("dirty", "/'d3:ti/"),("disagree", ",dIs@'gri:"),
    ("disappear", ",dIs@'pIa(r)/),("disappoint", ",dIs@'pOInt/"),
    ("disaster", "/dI'zA:st@(r)/"),("discover", "/dI'skAv@(r)/"),
    ("discuss", "/dI'skVs/"),("discussion", "/dI'skVSn/"),
    ("dish", "/dIS/"),("disk", "/dIsk/"),
    ("dismiss", "/dI'mIs/"),("distance", "/'dist@ns/"),
    ("distant", "/'dist@nt/"),("distinguish", "/dI'stINgwIS/"),
    ("district", "/'dIstrIkt/"),("divide", "/dI'vaId/"),
    ("divorce", "/dI'vO:s/"),("do", "/du:/; d@/"),
    ("doctor", "/'dQkt@(r)/"),("document", "/'dQkjum@nt/"),
    ("dog", "/dQg/"),("doll", "/dQl/"),
    ("dollar", "/'dQl@(r)/"),("door", "/dO:(r)/"),
    ("double", "/'dVbl/"),("doubt", "/daUt/"),
    ("down", "/daUn/"),("dozen", "/'d@zn/"),
    ("drag", "/dræg/"),("draw", "/drO:/"),
    ("dream", "/dri:m/"),("dress", "/dres/"),
    ("drink", "/drINk/"),("drive", "/draIv/"),
    ("driver", "/'draIv@(r)/"),("drop", "/drQp/"),
    ("drug", "/drVg/"),("drum", "/drVm/"),
    ("dry", "/draI/"),("duck", "/dVk/"),
    ("due", "/dju:/"),("during", "/'djU@rIN/"),
    ("dusk", "/dVsk/"),("dust", "/dVst/"),
    ("dusty", "/'dVsti/"),("duty", "/'dju:ti/"),

    # E
    ("each", "/i:tS/"),("eager", "/'i:g@(r)/"),
    ("ear", "/Ia(r)/"),("early", "/'3:li/"),
    ("earth", "/3:T/"),("east", "/i:st/"),
    ("eastern", "/'i:st@n/"),("easy", "/'i:zi/"),
    ("eat", "/i:t/"),("education", "/,edZu'eISn/"),
    ("effect", "/I'fekt/"),("effort", "/'ef@t/"),
    ("egg", "/eg/"),("eight", "/eIt/"),
    ("either", "/'aID@(r); 'i:D@(r)/"),("elder", "/'eld@(r)/"),
    ("electric", "/I'lektrIk/"),("electronic", "/,elek'trQnIk/"),
    ("elephant", "/'elIf@nt/"),("else", "/els/"),
    ("email", "/'i:meIl/"),("emperor", "/'emp@(r)/"),
    ("employ", "/Im'plOI/"),("empty", "/'empti/"),
    ("encourage", "/In'kArIdZ"),("end", "/end/"),
    ("enemy", "/enimi/"),("energy", "/'en@dZi/"),
    ("engine", "/'endZIn/"),("engineer", "/,endZI'nI@(r)/"),
    ("England", "/'INgl@nd/"),("English", "/'INglIS/"),
    ("enjoy", "/In'dZOI/"),("enough", "/I'nAf/"),
    ("enter", "/ent@(r)/"),("entrance", "/'entr@ns/"),
    ("envelope", "/'env@l@Up/"),("environment", "/In'vaIr@nm@nt/"),
    ("equal", "/'i:kw@l/"),("equipment", "/I'kwIpm@t/"),
    ("error", "/'er@(r); 'er@r/"),("especially", "/I'speSli/"),
    ("Europe", "/'jU@r@p/"),("European", "/jU@r@'pi:@n/"),
    ("even", "/'i:vn/"),("evening", "/'i:vvnIN/"),
    ("event", "/I'vent/"),("ever", "/'ev@(r)/"),
    ("every", "/'evri/"),("everybody", "/'evribodi/"),
    ("everyday", "/'evrideI/"),("everyone", "/'evrIwVn/"),
    ("everything", "/'evrITIN/"),("everywhere", "/'evriwea(r)/"),
    ("exact", "/Ig'zækt/"),("exam", "/Ig'zæm/"),
    ("example", "/Ig'zA:mpl/"),("excellent", "/'eks@l@nt/"),
    ("except", "/Ik'sept/"),("exchange", "/Iks'tSeIndZ/"),
    ("excite", "/Ik'saIt/"),("exciting", "/Ik'saItIN/"),
    ("excuse", "/Ik'skju:z/"),("exercise", "/'eks@saIz/"),
    ("exhibition", "/,eksI'bISn/"),("exist", "/Ig'zIst/"),
    ("exit", "/'egzit; 'eksit/"),("expect", "/Ik'spekt/"),
    ("expensive", "/Ik'spensIv/"),("experience", "/Ik'spi@ri@ns/"),
    ("experiment", "/Ik'sperIm@nt/"),("expert", "/'eksp3:t/"),
    ("explain", "/Ik'spleIn/"),("explode", "/Ik'spl@ud/"),
    ("explore", "/Ik'splO:(r)/"),("express", "/Ik'spres/"),
    ("expression", "/Ik'spreSn; ek'spreSn/"),
    ("extra", "/'ekstra/"),("extraordinary", "/Ik'strO:dni/"),

    # F
    ("face", "/feIs/"),("fact", "/fækt/"),
    ("factory", "/'fæktri; 'fAkt@ri/"),("fail", "/feIl/"),
    ("fair", "/fea(r)/"),("fall", "/fO:l/"),
    ("false", "/fO:ls/"),("familiar", "/f@'mIli@(r)/"),
    ("family", "/'fæmili/"),("famous", "/'feIm@s/"),
    ("fan", "/fæn/"),("fantastic", "/fæn'tæstIk/"),
    ("far", "/fA:(r)/"),("farm", "/fA:m/"),
    ("farmer", "/'fA:m@(r)/"),("fashion", "/'fæSn/"),
    ("fast", "/fA:st; fæst/"),("fat", "/fæt/"),
    ("father", "/'fA:D@(r)/"),("fault", "/fO:lt/"),
    ("favor", "/'feIv@(r)/"),("favorite", "/'feIv@rIt/"),
    ("fear", "/fIa(r); fIr/"),("feather", "/'feD@(r)/"),
    ("February", "/'febru@ri/"),("feed", "/fi:d/"),
    ("feel", "/fi:l/"),("feeling", "/'fi:lIN/"),
    ("fell", "/fel/"),("fellow", "/'fel@U/"),
    ("female", "/'fi:meIl/"),("fence", "/fens/"),
    ("festival", "/'festIvl/"),("fetch", "/fetS/"),
    ("few", "/fju:/"),("field", "/fi:ld/"),
    ("fifteen", "/,fIf'ti:n/"),("fifth", "/fIfT/"),
    ("fifty", "/'fIfti/"),("fight", "/faIt/"),
    ("fill", "/fIl/"),("film", "/fIlm/"),
    ("final", "/'faInl/"),("find", "/faInd/"),
    ("fine", "/faIn/"),("finger", "/'fINga(r)/"),
    ("finish", "/'finIS/"),("fire", "/'faIa(r)/"),
    ("firm", "/f3:m/"),("first", "/f3:st/"),
    ("fish", "/fIS/"),("fit", "/fIt/"),
    ("fitness", "/'fitn@s/"),("five", "/faIv/"),
    ("fix", "/fIks/"),("flag", "/flæg/"),
    ("flat", "/flæt/"),("flight", "/flaIt/"),
    ("floor", "/flO:(r)/"),("flower", "/'flau@(r)/"),
    ("fly", "/flaI/"),("fog", "/fQg/"),
    ("follow", "/'fQl@U/"),("food", "/fu:d/"),
    ("fool", "/fu:l/"),("foot", "/fUt/"),
    ("football", "/'fUtbO:l/"),("for", "/fO:(r); f@(r)/"),
    ("force", "/fO:s/"),("foreign", "/'fOr@n; 'fO:r@n/"),
    ("forest", "/'fQrIst/"),("forget", "/f@'get/"),
    ("form", "/fO:m/"),("former", "/'fO:m@(r)/"),
    ("fortnight", "/'fO:tnaIt/"),("fortunate", "/'fO:tS@n@t/"),
    ("fortunately", "/'fO:tS@n@tli/"),("forty", "/'fO:ti/"),
    ("forward", "/'fO:w@d/"),("found", "/faUnd/"),
    ("fox", "/fQks/"),("free", "/fri:/"),
    ("freedom", "/'fri:d@m/"),("freeze", "/fri:z/"),
    ("fresh", "/freS/"),("Friday", "/'fraIdeI/"),
    ("fridge", "/frIdZ/"),("friend", "/frend/"),
    ("friendly", "/'frendli/"),("friendship", "/'frendSIp/"),
    ("from", "/frm; frqm; frAm/"),("front", "/frVnt/"),
    ("fruit", "/fru:t/"),("full", "/fUl/"),
    ("fun", "/fVn/"),("funny", "/'fVni/"),
    ("furniture", "/'f3:nItSa(r)/"),

    # G
    ("gain", "/geIn/"),("game", "/geIm/"),
    ("gap": "/gæp/"),("garage", "/'gærA:Z; g@'rA:Z/"),
    ("garden", "/'gA:dn/"),("gate", "/geIt/"),
    ("general", "/'dZenrl/"),("generation", "/,dZen'reISn/"),
    ("gentle", "/'dzentl/"),("gentleman", "/'dzentlm@n/"),
    ("geography", "/dZI'Qgrafi/"),("gesture", "/'dZestSa(r)/"),
    ("get", "/get/"),("gift", "/gIft/"),
    ("girl", "/g3:l/"),("give", "/gIv/"),
    ("glad", "/glæd/"),("glass", "/glA:s; glæs/"),
    ("globe", "/gl@Ub/"),("glory", "/'glO:ri/"),
    ("glove", "/glVv/"),("go", "/g@U/"),
    ("goal", "/g@Ul/"),("god", "/gQd/"),
    ("gold", "/g@Uld/"),("golden", "/'g@Uld@n/"),
    ("good", "/gUd/"),("goodbye", "/,gUd'baI/"),
    ("goose", "/gu:s/"),("government", "/'gVvnm@nt/"),
    ("grade", "/greId/"),("/'gramma(r)/", "/'græm@(r)/",
    ("grandchild", "/'græn(t)SaIld/"),("granddaughter", "/'grændO:t@(r)/"),
    ("grandfather", "/'grænfa:D@(r)/"),("grandmother", "/'grænmAD@(r)/"),
    ("grandparent", "/'grænpe@r@nt/"),("grandson", "/'grAnsVn/"),
    ("grass", "/grA:s; græs/"),("grey", "/greI/"),
    ("great", "/greIt/"),("green", "/gri:n/"),
    ("greeting", "/'gri:tIN/"),("ground", "/graUnd/"),
    ("group", "/gru:p/"),("grow", "/gr@U/"),
    ("growth", "/gr@UT/"),("guard": "/gA:d/"),
    ("guess", "/ges/"),("guest", "/gest/"),
    ("guide": "/gaId/"),("guitar", "/gI'tA:(r)/"),
    ("gun", "/gAn/"),("habit", "/'hæbIt/"),
    ("hair", "/hea(r)/"),("half", "/hA:f; hæf/"),
    ("hall", "/hO:l/"),("ham", "/hæm/"),
    ("hamburger", "/'hæmb3:g@(r)/"),("hand", "/hænd/"),
    ("handbag", "/'hænbæg/"),("handwriting", "/'hændraItIN/"),
    ("hang", "/hæN/"),("happy", "/'hæpi/"),
    ("hard", "/hA:d/"),("hardly", "/'hA:dli/"),
    ("harvest", "/'hA:vIst/"),("hat", "/hæt/"),
    ("have", "/hæv; h@v/"),("head", "/hed/"),
    "headache": "/'hedeIk/", "health": "/helT/",
    "healthy": "/'helTi/", "hear": "/hIa(r)/",
    "heart": "/hA:t/", "heat": "/hi:t/",
    "heaven": "/'hevn/", "height": "/haIt/",
    "helicopter": "/'helIkQpt@(r)/", "hello": "/h@'l@U; 'hel@U/",
    "help": "/help/", "helpful": "/'helpfl/",
    "hen": "/hen/", "her": "/h3:(r); h3:r; @(r)",
    "here": "/hIa(r)/", "hero": "/'hI@r@U/",
    "herself": "/h3:'self;", "hide": "/haId/",
    "high": "/haI/", "hill": "/hIl/",
    "him": "/hIm; Im; @m/", "himself": "/hIm'self/",
    "his": "/hIz; Iz/", "history": "/'histri/",
    "hit": "/hIt/", "hobby": "/'hQbi/",
    "hold": "/h@Uld/", "hole": "/h@Ul/",
    "holiday": "/'hql@deI/", "home": "/h@Um/",
    "homework": "/'h@Uw3:k/", "honest": "/'QnIst/",
    "hope": "/h@Up/", "horse": "/hO:s/",
    "hospital": "/'hQspItl/", "host": "/h@ust/",
    "hot": "/Qt/", "hotel": "/h@U'tel/",
    "hour": "/'aU@(r)/", "house": "/haUs/",
    "how": "/haU/", "however": "/haU'eva(r)/",
    "huge": "/hju:dZ/", "human": "/'hju:m@n/",
    "humorous": "/'hju:m@r@s/", "hundred": "/'hAndrd@/",
    "hungry": "/'hANgri/", "hunt": "/hVnt/",
    "hurry": "/'hArI/", "hurt": "/h3:t/",
    "husband": "/'hVzb@nd/",
]
    
    for w, p in entries:
        ph[w] = p
    
    return ph


def main():
    print("Building phonetic dictionary...")
    ph = build_phonetics()
    print(f"Total phonetic entries: {len(ph)}")
    
    with open('scripts/phonetics_g8_full.json', 'w', encoding='utf-8') as f:
        json.dump(ph, f, ensure_ascii=False, indent=2)
    print(f"Saved to scripts/phonetics_g8_full.json")

if __name__ == '__main__':
    main()
