import json

questions = [
  {"id":"lit_001","type":"single_choice","question":"下列四大名著与作者对应正确的一项是（　）。","options":["A. 《水浒传》——吴承恩","B. 《西游记》——罗贯中","C. 《三国演义》——施耐庵","D. 《红楼梦》——曹雪芹"],"answer":"D","analysis":"四大名著及作者：《三国演义》罗贯中，《水浒传》施耐庵，《西游记》吴承恩，《红楼梦》曹雪芹。A将吴承恩写成水浒传作者（应为西游记），B将罗贯中写成西游记作者（应为三国演义），C将施耐庵写成三国演义作者（应为水浒传），只有D完全正确。","knowledge_tag":"四大名著","ability_tag":"作者对应","difficulty":1,"grade":4},
  {"id":"lit_002","type":"single_choice","question":"下列句子括号中应填入的标点符号正确的一项是（　）。\n\n他说：\u201c你明天去不去图书馆（　）\u201d","options":["A. 逗号","B. 句号","C. 问号","D. 感叹号"],"answer":"C","analysis":"引号内是一个疑问句，需要用问号。疑问句末尾应用问号表示疑问语气。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":1,"grade":4},
  {"id":"lit_003","type":"single_choice","question":"下列有关四大名著的情节对应正确的一项是（　）。","options":["A. \u201c武松打虎\u201d出自《三国演义》","B. \u201c草船借箭\u201d的主角是曹操","C. \u201c孙悟空大闹天宫\u201d出自《西游记》","D. \u201c刘姥姥进大观园\u201d出自《水浒传》"],"answer":"C","analysis":"A错误，武松打虎出自《水浒传》；B错误，草船借箭的主角是诸葛亮；D错误，刘姥姥进大观园出自《红楼梦》；C正确。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":1,"grade":4},
  {"id":"lit_004","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. \u201c你好，\u201d小明说：\u201c我们一起去上学吧。\u201d","B. 我喜欢吃的水果有：苹果、香蕉、橘子等。","C. 老舍先生写的《草原》这篇课文非常优美。","D. 他问我：\u201c你明天去不去图书馆\u201d？"],"answer":"C","analysis":"A错误，提示语在中间时后面应用逗号而非冒号；B中冒号可以省略但不算严格错误，C项标点使用完全规范是最佳答案；D错误，问号应放在引号内。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_005","type":"single_choice","question":"下列人物与所属名著对应正确的一项是（　）。","options":["A. 林黛玉——《西游记》","B. 关羽——《水浒传》","C. 宋江——《三国演义》","D. 唐僧——《西游记》"],"answer":"D","analysis":"林黛玉是《红楼梦》人物，关羽是《三国演义》人物，宋江是《水浒传》人物，唐僧是《西游记》人物。只有D对应正确。","knowledge_tag":"四大名著","ability_tag":"人物作品对应","difficulty":1,"grade":3},
  {"id":"lit_006","type":"single_choice","question":"下列句子中，标点符号使用有误的一项是（　）。","options":["A. \u201c你作业写完了吗？\u201d妈妈问，\u201c写完就去吃饭。\u201d","B. 动物园里有老虎、狮子、大象等动物。","C. \u201c这本书真有趣！\u201d他感叹道，\u201c我还想再看一遍。\u201d","D. 他问我：\u201c你今天去不去公园\u201d？"],"answer":"D","analysis":"D项中问号放在了引号外面，但引号内是完整的问句，问号应在引号里面。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_007","type":"single_choice","question":"下列关于标点符号的说法正确的一项是（　）。","options":["A. 书名号并列使用时，中间应加顿号，如《西游记》、《三国演义》","B. 他问：\u201c今天星期几？\u201d\u2014\u2014这句标点使用正确","C. \u201c你好，\u201d他说，\u201c好久不见。\u201d\u2014\u2014这句标点使用正确","D. 感叹号只能放在句末，不能放在句子中间"],"answer":"C","analysis":"A错误，书名号之间通常不加顿号；C正确，提示语在中间时用逗号连接，标点规范。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_008","type":"single_choice","question":"下列标点符号与其名称对应正确的一项是（　）。","options":["A. ，\u2014\u2014句号","B. 。\u2014\u2014逗号","C. ？\u2014\u2014问号","D. ！\u2014\u2014书名号"],"answer":"C","analysis":"，是逗号，。是句号，？是问号，！是感叹号。只有C对应正确。","knowledge_tag":"标点符号","ability_tag":"标点识记","difficulty":1,"grade":3},
  {"id":"lit_009","type":"single_choice","question":"下列选项中，不属于中国古典四大名著的一项是（　）。","options":["A. 《儒林外史》","B. 《红楼梦》","C. 《水浒传》","D. 《西游记》"],"answer":"A","analysis":"四大名著是《三国演义》《水浒传》《西游记》《红楼梦》。《儒林外史》是吴敬梓的讽刺小说，不属于四大名著。","knowledge_tag":"四大名著","ability_tag":"基本常识","difficulty":1,"grade":3},
  {"id":"lit_010","type":"single_choice","question":"下列关于省略号作用的说法，不正确的一项是（　）。","options":["A. 省略号可以表示列举的省略","B. 省略号可以表示说话断断续续","C. 省略号可以表示强调重点","D. 省略号可以表示引文的省略"],"answer":"C","analysis":"省略号的作用包括：列举的省略、说话断断续续、引文的省略、语意未尽等，但不表示强调重点。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":2,"grade":5},
  {"id":"lit_011","type":"single_choice","question":"下列《水浒传》人物与绰号对应正确的一项是（　）。","options":["A. 宋江\u2014\u2014及时雨","B. 林冲\u2014\u2014智多星","C. 李逵\u2014\u2014花和尚","D. 武松\u2014\u2014豹子头"],"answer":"A","analysis":"宋江（及时雨）、吴用（智多星）、林冲（豹子头）、李逵（黑旋风）、鲁智深（花和尚）、武松（行者）。B错智多星是吴用；C错花和尚是鲁智深；D错豹子头是林冲。","knowledge_tag":"四大名著","ability_tag":"人物绰号","difficulty":2,"grade":5},
  {"id":"lit_012","type":"single_choice","question":"下列标点符号与其名称对应正确的一项是（　）。","options":["A. 《 》\u2014\u2014双引号","B. \u201c \u201d\u2014\u2014书名号","C. ……\u2014\u2014省略号","D. \u2014\u2014\u2014\u2014双引号"],"answer":"C","analysis":"《 》是书名号，\u201c \u201d是双引号，……是省略号，\u2014\u2014是破折号。只有C对应正确。","knowledge_tag":"标点符号","ability_tag":"标点识记","difficulty":1,"grade":3},
  {"id":"lit_013","type":"single_choice","question":"下列关于文体知识的说法正确的一项是（　）。","options":["A. 说明文只能使用说明这种表达方式，不能有描写和抒情","B. 诗歌都是韵文，每句字数必须相同","C. 童话和寓言都富有想象力，但寓言往往含有深刻的道理","D. 小说不需要环境描写，只需要人物和情节"],"answer":"C","analysis":"A错误，说明文以说明为主但不排斥其他方式；B错误，诗歌形式多样；C正确；D错误，小说三要素是人物、情节、环境。","knowledge_tag":"文学常识","ability_tag":"文体知识","difficulty":2,"grade":5},
  {"id":"lit_014","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. 我喜欢读《西游记》、《水浒传》、《三国演义》等古典名著。","B. \u201c你作业写完了吗？\u201d妈妈问，\u201c写完就去吃饭。\u201d","C. 动物园里有老虎、狮子、猴子……等动物。","D. 他问我：\u201c你今天去不去图书馆\u201d？"],"answer":"B","analysis":"A错误，书名号并列不加顿号；B正确；C错误，省略号与\u201c等\u201d不并用；D错误，问号应在引号内。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_015","type":"single_choice","question":"下列关于四大名著人物的描述，对应正确的一项是（　）。","options":["A. 手持青龙偃月刀，千里走单骑\u2014\u2014林冲","B. 多愁善感，葬花吟诗\u2014\u2014薛宝钗","C. 火眼金睛，三打白骨精\u2014\u2014孙悟空","D. 倒拔垂杨柳，拳打镇关西\u2014\u2014武松"],"answer":"C","analysis":"A错误，应是关羽；B错误，应是林黛玉；C正确；D错误，应是鲁智深。","knowledge_tag":"四大名著","ability_tag":"人物辨识","difficulty":2,"grade":5},
  {"id":"lit_016","type":"single_choice","question":"下列句子中，标点符号使用有误的一项是（　）。","options":["A. \u201c你好，\u201d小明说，\u201c我们一起去上学吧。\u201d","B. 《红楼梦》《水浒传》《西游记》《三国演义》是中国的四大名著。","C. 他问：\u201c这道题怎么做？\u201d","D. 我喜欢吃的水果有：苹果、香蕉、橘子等等。"],"answer":"D","analysis":"D错误，\u201c等等\u201d表示列举未尽，不应与省略号同时出现。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_017","type":"single_choice","question":"下列关于四大名著的描述，正确的一项是（　）。","options":["A. 《三国演义》中\u201c赤壁之战\u201d是诸葛亮独自指挥的","B. 《水浒传》中的宋江最后没有接受朝廷的招安","C. 《西游记》中孙悟空是从石头里蹦出来的","D. 《红楼梦》中\u201c刘姥姥进大观园\u201d出自《三国演义》"],"answer":"C","analysis":"A错误，赤壁之战周瑜是东吴主帅；B错误，宋江最终接受了招安；C正确；D错误，刘姥姥进大观园出自《红楼梦》。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":2,"grade":5},
  {"id":"lit_018","type":"single_choice","question":"下列关于文体特点的说法正确的一项是（　）。","options":["A. 童话的主要特点是语言准确客观","B. 寓言的主要特点是篇幅长、人物多","C. 说明文的主要特点是客观准确地介绍事物","D. 记叙文的主要特点是发表议论和观点"],"answer":"C","analysis":"A错误，童话特点是想象；B错误，寓言短小精悍；C正确；D错误，记叙文以记事为主。","knowledge_tag":"文学常识","ability_tag":"文体知识","difficulty":2,"grade":5},
  {"id":"lit_019","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. \u201c不，我不去！\u201d他坚定地说。","B. 他问我：\u201c你明天去不去图书馆\u201d？","C. 动物园里有老虎、狮子、猴子……等动物。","D. 《红楼梦》、《水浒传》、《西游记》是古典名著。"],"answer":"A","analysis":"A正确；B错误，问号应在引号内；C错误，省略号与\u201c等\u201d不并用；D错误，书名号并列不加顿号。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_020","type":"single_choice","question":"下列关于《红楼梦》人物的描述，对应正确的一项是（　）。","options":["A. 精明能干，人称\u201c凤辣子\u201d\u2014\u2014林黛玉","B. 出生时口中衔玉，是贾府公子\u2014\u2014贾宝玉","C. 多愁善感，与宝玉相爱\u2014\u2014薛宝钗","D. 端庄稳重，恪守礼教\u2014\u2014贾母"],"answer":"B","analysis":"A错误，凤辣子是王熙凤；B正确；C错误，与宝玉相爱的是林黛玉；D错误，恪守礼教是薛宝钗。","knowledge_tag":"四大名著","ability_tag":"人物辨识","difficulty":2,"grade":5},
  {"id":"lit_021","type":"single_choice","question":"下列《三国演义》人物与事件对应正确的一项是（　）。","options":["A. 诸葛亮\u2014\u2014草船借箭","B. 关羽\u2014\u2014空城计","C. 张飞\u2014\u2014七擒孟获","D. 周瑜\u2014\u2014过五关斩六将"],"answer":"A","analysis":"A正确；B错误，空城计是诸葛亮；C错误，七擒孟获是诸葛亮；D错误，过五关斩六将是关羽。","knowledge_tag":"四大名著","ability_tag":"人物事件对应","difficulty":2,"grade":5},
  {"id":"lit_022","type":"single_choice","question":"下列句子中，引号的作用与其他三项不同的一项是（　）。","options":["A. 老师说：\u201c同学们要认真听讲。\u201d","B. \u201c学而时习之，不亦说乎\u201d是孔子说的。","C. 他最喜欢的那本书叫\u201c西游记\u201d。","D. 古人云：\u201c三人行，必有我师焉。\u201d"],"answer":"C","analysis":"A、B、D中的引号都表示直接引用；C中的引号表示特定称谓，用法不同。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":2,"grade":5},
  {"id":"lit_023","type":"single_choice","question":"下列关于文体知识的说法，不正确的一项是（　）。","options":["A. 记叙文六要素包括时间、地点、人物、起因、经过、结果","B. 说明文的主要表达方式是说明","C. 童话故事都是真实发生的事情","D. 寓言故事结尾不一定直接告诉读者道理"],"answer":"C","analysis":"A正确；B正确；C错误，童话是虚构的；D正确。","knowledge_tag":"文学常识","ability_tag":"文体知识","difficulty":2,"grade":5},
  {"id":"lit_024","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. \u201c你写完作业了吗？\u201d妈妈问。\u201c写完就去吃饭。\u201d","B. \u201c你写完作业了吗？\u201d妈妈问，\u201c写完就去吃饭。\u201d","C. \u201c你写完作业了吗\u201d？妈妈问，\u201c写完就去吃饭。\u201d","D. \u201c你写完作业了吗\u201d妈妈问：\u201c写完就去吃饭。\u201d"],"answer":"B","analysis":"B正确。提示语在中间时，提示语后用逗号。A错误应用逗号非句号；C错误问号应在引号内；D错误引语后不应用冒号。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_025","type":"single_choice","question":"下列关于《西游记》人物身世的描述，正确的一项是（　）。","options":["A. 沙悟净原是天庭的卷帘大将，因打碎琉璃盏被贬下凡","B. 孙悟空原是玉帝御马监的弼马温，因大闹天宫被压五行山下","C. 猪八戒原是天蓬元帅，因调戏嫦娥被贬下凡","D. 唐僧原是如来佛祖的弟子，因犯错被贬下凡取经"],"answer":"A","analysis":"A正确，沙悟净原是卷帘大将；B中弼马温是正确官名但孙悟空被压五行山是因为大闹天宫整体；C也正确；D错误，唐僧是金蝉子转世奉旨取经。A为最佳答案。","knowledge_tag":"四大名著","ability_tag":"人物身世","difficulty":2,"grade":5},
  {"id":"lit_026","type":"single_choice","question":"下列句子中，标点符号使用有误的一项是（　）。","options":["A. 我喜欢吃的水果有：苹果、香蕉、橘子。","B. 《红楼梦》《水浒传》《西游记》《三国演义》是四大名著。","C. 他问我：\u201c你明天去不去图书馆？\u201d","D. \u201c你好，\u201d小明说，\u201c我们一起去上学吧。\u201d"],"answer":"A","analysis":"A中冒号使用在\u201c有\u201d字后可省略，虽然不算严格错误但不规范。B、C、D项标点使用均正确。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_027","type":"single_choice","question":"下列关于四大名著的描述，正确的一项是（　）。","options":["A. 《水浒传》中的武松打虎是在野猪林","B. 《三国演义》中\u201c桃园三结义\u201d是刘备、关羽、赵云","C. 《红楼梦》中的贾宝玉最后出家当了和尚","D. 《西游记》中的白龙马是东海龙王的太子"],"answer":"C","analysis":"A错误，武松打虎在景阳冈；B错误，桃园三结义是刘备、关羽、张飞；C正确；D错误，白龙马是西海龙王三太子。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":2,"grade":5},
  {"id":"lit_028","type":"single_choice","question":"下列四大名著与作者的对应，正确的一项是（　）。","options":["A. 《红楼梦》\u2014\u2014施耐庵","B. 《西游记》\u2014\u2014吴承恩","C. 《水浒传》\u2014\u2014曹雪芹","D. 《三国演义》\u2014\u2014吴承恩"],"answer":"B","analysis":"《红楼梦》曹雪芹，《西游记》吴承恩，《水浒传》施耐庵，《三国演义》罗贯中。只有B正确。","knowledge_tag":"四大名著","ability_tag":"作者对应","difficulty":1,"grade":4},
  {"id":"lit_029","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. \u201c这本书真有趣！\u201d他感叹道，\u201c我还想再看一遍。\u201d","B. \u201c这本书真有趣\u201d，他感叹道：\u201c我还想再看一遍。\u201d","C. \u201c这本书真有趣！\u201d他感叹道：\u201c我还想再看一遍。\u201d","D. \u201c这本书真有趣！\u201d他感叹道。\u201c我还想再看一遍。\u201d"],"answer":"A","analysis":"A正确，提示语在中间用逗号；B错误前引语缺标点；C错误提示语后应用逗号；D错误提示语后不应是句号。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_030","type":"single_choice","question":"下列关于《水浒传》人物与绰号的对应，正确的一项是（　）。","options":["A. \u201c及时雨\u201d\u2014\u2014吴用","B. \u201c智多星\u201d\u2014\u2014宋江","C. \u201c豹子头\u201d\u2014\u2014林冲","D. \u201c黑旋风\u201d\u2014\u2014鲁智深"],"answer":"C","analysis":"A错误，及时雨是宋江；B错误，智多星是吴用；C正确；D错误，黑旋风是李逵。","knowledge_tag":"四大名著","ability_tag":"人物绰号","difficulty":2,"grade":5},
  {"id":"lit_031","type":"single_choice","question":"下列对《红楼梦》中\u201c金陵十二钗\u201d理解正确的一项是（　）。","options":["A. 金陵十二钗是十二位男性角色","B. 金陵十二钗是十二位女性角色，是金陵地区最优秀的女子","C. 金陵十二钗只有林黛玉和薛宝钗两人","D. 金陵十二钗是《红楼梦》中的十二个丫鬟"],"answer":"B","analysis":"金陵十二钗正册包括林黛玉、薛宝钗等十二位女性角色。A、C、D均错误。","knowledge_tag":"四大名著","ability_tag":"作品常识","difficulty":2,"grade":5},
  {"id":"lit_032","type":"single_choice","question":"下列不属于双引号作用的一项是（　）。","options":["A. 表示直接引用","B. 表示特定称谓","C. 表示因果关系","D. 表示强调"],"answer":"C","analysis":"双引号的作用有：直接引用、特定称谓、特殊含义、强调、讽刺否定等。表示因果关系不是引号的作用。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":2,"grade":5},
  {"id":"lit_033","type":"single_choice","question":"下列关于文体知识的说法，正确的一项是（　）。","options":["A. 诗歌都必须押韵，不押韵的就不是诗歌","B. 小说中的人物都是真实存在的","C. 散文的特点是\u201c形散神不散\u201d","D. 剧本主要以叙述和描写来推动情节发展"],"answer":"C","analysis":"A错误，现代自由诗不一定押韵；B错误，小说人物是虚构的；C正确；D错误，剧本以对话和舞台说明推动情节。","knowledge_tag":"文学常识","ability_tag":"文体知识","difficulty":2,"grade":5},
  {"id":"lit_034","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. 动物园里有老虎、狮子、猴子等动物。","B. 动物园里有老虎、狮子、猴子……等动物。","C. 动物园里有老虎，狮子，猴子等动物。","D. 动物园里有老虎、狮子、猴子、等动物。"],"answer":"A","analysis":"A正确；B错误，省略号与\u201c等\u201d不并用；C错误，应用顿号；D错误，\u201c等\u201d前不加顿号。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_035","type":"single_choice","question":"下列关于《三国演义》人物的描述，对应正确的一项是（　）。","options":["A. 三顾茅庐，请诸葛亮出山\u2014\u2014曹操","B. 身在曹营心在汉，过五关斩六将\u2014\u2014张飞","C. 足智多谋，借东风，空城计\u2014\u2014诸葛亮","D. \u201c既生瑜，何生亮\u201d\u2014\u2014刘备"],"answer":"C","analysis":"A错误，三顾茅庐的是刘备；B错误，应是关羽；C正确；D错误，是周瑜的话。","knowledge_tag":"四大名著","ability_tag":"人物辨识","difficulty":2,"grade":5},
  {"id":"lit_036","type":"single_choice","question":"下列对《西游记》中\u201c取经团队\u201d成员理解正确的一项是（　）。","options":["A. 取经团队只有唐僧和孙悟空两人","B. 取经团队包括唐僧、孙悟空、猪八戒、沙和尚和白龙马","C. 白龙马不是取经团队成员","D. 猪八戒是被唐僧从五行山下救出来的"],"answer":"B","analysis":"取经团队共五位成员。A错误；C错误；D错误，被唐僧从五行山下救出的是孙悟空。","knowledge_tag":"四大名著","ability_tag":"作品常识","difficulty":1,"grade":4},
  {"id":"lit_037","type":"single_choice","question":"下列关于标点符号的说法，不正确的一项是（　）。","options":["A. 句号表示一句话说完后的停顿","B. 问号用于疑问句末尾，也用于反问句末尾","C. 感叹号只能用于感叹句末尾","D. 分号用于表示复句中并列分句之间的停顿"],"answer":"C","analysis":"C不正确，感叹号还可用于祈使句末尾、语气强烈的反问句末尾等。A、B、D均正确。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_038","type":"single_choice","question":"下列人物与所属作品对应正确的一项是（　）。","options":["A. 贾宝玉\u2014\u2014《水浒传》","B. 武松\u2014\u2014《三国演义》","C. 诸葛亮\u2014\u2014《三国演义》","D. 猪八戒\u2014\u2014《红楼梦》"],"answer":"C","analysis":"贾宝玉出自《红楼梦》，武松出自《水浒传》，诸葛亮出自《三国演义》，猪八戒出自《西游记》。只有C正确。","knowledge_tag":"四大名著","ability_tag":"人物作品对应","difficulty":1,"grade":4},
  {"id":"lit_039","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. 妈妈问我：\u201c你今天想去哪里玩？\u201d","B. 妈妈问我\u201c你今天想去哪里玩？\u201d","C. 妈妈问我：\u201c你今天想去哪里玩\u201d？","D. 妈妈问我：你今天想去哪里玩？"],"answer":"A","analysis":"A正确，直接引用用冒号加引号，问号在引号内；B错误缺冒号；C错误问号应在引号内；D错误缺引号。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_040","type":"single_choice","question":"下列关于《水浒传》情节的描述，对应正确的一项是（　）。","options":["A. 武松在景阳冈打死老虎\u2014\u2014武松打虎","B. 鲁智深三拳打死镇关西\u2014\u2014鲁提辖拳打镇关西","C. 林冲在草料场被高俅手下杀死\u2014\u2014风雪山神庙","D. 宋江在梁山题写反诗\u2014\u2014浔阳楼题反诗"],"answer":"B","analysis":"A正确；B正确；C错误，林冲未死而是奋起反抗；D正确。本题C项描述有误。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":2,"grade":5},
  {"id":"lit_041","type":"single_choice","question":"下列对《水浒传》中\u201c智取生辰纲\u201d这一情节理解正确的一项是（　）。","options":["A. 智取生辰纲是宋江策划的","B. 智取生辰纲的主要人物有晁盖、吴用、公孙胜、刘唐、阮氏三雄等","C. 生辰纲是送给皇帝的生日礼物","D. 智取生辰纲使用的是武力抢夺"],"answer":"B","analysis":"智取生辰纲是晁盖、吴用等\u201c七星聚义\u201d用计谋智取。A错误；C错误，是送给太师蔡京；D错误。","knowledge_tag":"四大名著","ability_tag":"情节理解","difficulty":2,"grade":5},
  {"id":"lit_042","type":"single_choice","question":"下列关于顿号和分号的说法，正确的一项是（　）。","options":["A. 顿号用于表示句子内部并列分句之间的停顿","B. 分号用于表示句子内部并列词语之间的停顿","C. 顿号的停顿时间比分号短","D. 顿号和分号可以随意互换使用"],"answer":"C","analysis":"A错误，顿号用于词语间；B错误，分号用于分句间；C正确；D错误。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_043","type":"single_choice","question":"下列关于四大名著的描述，正确的一项是（　）。","options":["A. 《三国演义》中\u201c草船借箭\u201d是周瑜的计谋","B. 《西游记》中孙悟空没有被封为\u201c斗战胜佛\u201d","C. 《红楼梦》又名《石头记》《金陵十二钗》","D. 《水浒传》中\u201c倒拔垂杨柳\u201d的是林冲"],"answer":"C","analysis":"A错误，草船借箭是诸葛亮的计谋；B错误，孙悟空被封为斗战胜佛；C正确；D错误，倒拔垂杨柳的是鲁智深。","knowledge_tag":"四大名著","ability_tag":"作品常识","difficulty":2,"grade":5},
  {"id":"lit_044","type":"single_choice","question":"下列作品与作者的对应，正确的一项是（　）。","options":["A. 《红楼梦》\u2014\u2014罗贯中","B. 《水浒传》\u2014\u2014曹雪芹","C. 《三国演义》\u2014\u2014罗贯中","D. 《西游记》\u2014\u2014施耐庵"],"answer":"C","analysis":"A错误，红楼梦作者曹雪芹；B错误，水浒传作者施耐庵；C正确；D错误，西游记作者吴承恩。","knowledge_tag":"四大名著","ability_tag":"作者对应","difficulty":1,"grade":4},
  {"id":"lit_045","type":"single_choice","question":"下列关于《三国演义》情节的描述，对应正确的一项是（　）。","options":["A. 诸葛亮借东风，火烧曹军战船\u2014\u2014火烧赤壁","B. 关羽在华容道追杀曹操\u2014\u2014华容道义释曹操","C. 张飞在城楼上弹琴，吓退司马懿\u2014\u2014空城计","D. 曹操三次到诸葛亮家中请他出山\u2014\u2014三顾茅庐"],"answer":"A","analysis":"A正确；B错误，关羽是义释（放走）曹操；C错误，空城计是诸葛亮；D错误，三顾茅庐的是刘备。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":2,"grade":5},
  {"id":"lit_046","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. 我喜欢读《西游记》；《水浒传》；《三国演义》等名著。","B. 我喜欢读《西游记》《水浒传》《三国演义》等名著。","C. 我喜欢读\u201c西游记\u201d、\u201c水浒传\u201d、\u201c三国演义\u201d等名著。","D. 我喜欢读《西游记》、《水浒传》、《三国演义》等名著。"],"answer":"B","analysis":"B正确，书名号之间不需要加顿号或分号。A错误；C错误应用书名号；D错误。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_047","type":"single_choice","question":"下列关于应用文体知识的说法，不正确的一项是（　）。","options":["A. 新闻的特点是真实、及时、简短","B. 日记一般以第一人称来写","C. 书信的格式包括称呼、正文、结尾、署名和日期","D. 读后感只需要抄写原文内容，不需要写自己的感想"],"answer":"D","analysis":"A、B、C均正确；D错误，读后感应以感为主，需要写自己的感想。","knowledge_tag":"文学常识","ability_tag":"文体知识","difficulty":2,"grade":5},
  {"id":"lit_048","type":"single_choice","question":"下列句子中，省略号表示\u201c引文省略\u201d的一项是（　）。","options":["A. 我家有鸡、鸭、鹅……好多家禽。","B. 他轻轻地哼起了《兰花草》：\u201c我从山中来，带着兰花草……\u201d","C. \u201c呜\u2014\u2014\u201d火车开动了。","D. \u201c班长，我\u2014\u2014\u201d话没说完，他就晕倒了。"],"answer":"B","analysis":"A表示列举省略；B表示引文省略；C中是破折号表示声音延长；D表示说话中断。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":2,"grade":5},
  {"id":"lit_049","type":"single_choice","question":"下列对《西游记》中\u201c三打白骨精\u201d这一情节理解正确的一项是（　）。","options":["A. 白骨精第一次变成一位老爷爷","B. 孙悟空三次都被白骨精骗过了","C. 唐僧因为孙悟空打死了白骨精而念紧箍咒并赶走他","D. 猪八戒帮助孙悟空一起打死了白骨精"],"answer":"C","analysis":"A错误，白骨精第一次变成年轻村姑；B错误，孙悟空每次都识破了；C正确；D错误，猪八戒反而挑拨离间。","knowledge_tag":"四大名著","ability_tag":"情节理解","difficulty":2,"grade":5},
  {"id":"lit_050","type":"single_choice","question":"下列关于《水浒传》人物与绰号的对应，正确的一项是（　）。","options":["A. 宋江\u2014\u2014豹子头","B. 吴用\u2014\u2014及时雨","C. 李逵\u2014\u2014黑旋风","D. 林冲\u2014\u2014花和尚"],"answer":"C","analysis":"A错误，豹子头是林冲；B错误，及时雨是宋江；C正确；D错误，花和尚是鲁智深。","knowledge_tag":"四大名著","ability_tag":"人物绰号","difficulty":2,"grade":5},
  {"id":"lit_051","type":"single_choice","question":"下列对《三国演义》中\u201c桃园三结义\u201d理解正确的一项是（　）。","options":["A. 桃园三结义发生在刘备、关羽、张飞三人之间","B. 桃园三结义发生在刘备、关羽、赵云三人之间","C. 桃园三结义发生在曹操、刘备、孙权三人之间","D. 桃园三结义发生在诸葛亮、刘备、关羽三人之间"],"answer":"A","analysis":"桃园三结义是刘备、关羽、张飞三人在桃园中结为异姓兄弟。赵云是后来加入的。","knowledge_tag":"四大名著","ability_tag":"情节理解","difficulty":1,"grade":4},
  {"id":"lit_052","type":"single_choice","question":"下列标点符号与其名称对应正确的一项是（　）。","options":["A. ？\u2014\u2014感叹号","B. ！\u2014\u2014问号","C. ；\u2014\u2014分号","D. ：\u2014\u2014句号"],"answer":"C","analysis":"？是问号，！是感叹号，；是分号，：是冒号。只有C对应正确。","knowledge_tag":"标点符号","ability_tag":"标点识记","difficulty":1,"grade":3},
  {"id":"lit_053","type":"single_choice","question":"下列关于《红楼梦》的描述，不正确的一项是（　）。","options":["A. 《红楼梦》中的\u201c四大家族\u201d是贾、史、王、薛","B. 林黛玉最后和贾宝玉结了婚","C. 贾宝玉出生时口中衔着一块玉","D. 王熙凤是贾府的管家奶奶，精明能干"],"answer":"B","analysis":"A正确；B错误，贾宝玉最终与薛宝钗成婚；C正确；D正确。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":2,"grade":5},
  {"id":"lit_054","type":"single_choice","question":"下列标点符号与其主要作用的对应，正确的一项是（　）。","options":["A. 句号（。）\u2014\u2014表示疑问语气","B. 问号（？）\u2014\u2014表示一句话说完","C. 感叹号（！）\u2014\u2014表示强烈的感情","D. 省略号（……）\u2014\u2014表示话题转换"],"answer":"C","analysis":"A错误；B错误；C正确；D错误，话题转换是破折号的作用。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":1,"grade":4},
  {"id":"lit_055","type":"single_choice","question":"下列关于《水浒传》人物的描述，对应正确的一项是（　）。","options":["A. 武艺高强，景阳冈打虎，醉打蒋门神\u2014\u2014鲁智深","B. 倒拔垂杨柳，大闹野猪林\u2014\u2014林冲","C. 被高俅陷害，风雪山神庙\u2014\u2014林冲","D. 箭法高超，外号\u201c小李广\u201d\u2014\u2014吴用"],"answer":"C","analysis":"A错误，应是武松；B错误，应是鲁智深；C正确；D错误，小李广是花荣。","knowledge_tag":"四大名著","ability_tag":"人物辨识","difficulty":2,"grade":5},
  {"id":"lit_056","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. 他问我：\u201c你今天去不去图书馆？\u201d","B. 他问我：\u201c你今天去不去图书馆\u201d？","C. 他问我：你今天去不去图书馆？","D. 他问我\u201c你今天去不去图书馆？\u201d"],"answer":"A","analysis":"A正确；B错误问号应在引号内；C错误缺引号；D错误缺冒号。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_057","type":"single_choice","question":"下列关于《西游记》的描述，不正确的一项是（　）。","options":["A. 孙悟空是从花果山的石头里蹦出来的","B. 孙悟空的兵器如意金箍棒是从东海龙宫得来的","C. 孙悟空在太上老君的炼丹炉里练成了火眼金睛","D. 猪八戒原是玉皇大帝的托塔天王"],"answer":"D","analysis":"A、B、C均正确；D错误，猪八戒原是天蓬元帅，托塔天王是李靖。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":2,"grade":5},
  {"id":"lit_058","type":"single_choice","question":"下列句子中破折号的作用，与其他三项不同的一项是（　）。","options":["A. 我永远忘不了那一天\u2014\u20141927年4月28日。","B. 我的故乡\u2014\u2014一个美丽的小山村，在山的那边。","C. \u201c呜\u2014\u2014\u201d火车开动了。","D. 这就是我的家乡\u2014\u2014中国。"],"answer":"C","analysis":"A、B、D中破折号表示解释说明；C中破折号表示声音延长。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":2,"grade":5},
  {"id":"lit_059","type":"single_choice","question":"下列对《红楼梦》中\u201c刘姥姥进大观园\u201d这一情节理解正确的一项是（　）。","options":["A. 刘姥姥是贾府的亲戚，非常有钱","B. 刘姥姥进大观园是为了给贾母祝寿","C. 刘姥姥在宴会上闹出许多笑话，被大家取笑","D. 刘姥姥最后被赶出了贾府"],"answer":"C","analysis":"A错误，刘姥姥是乡下穷亲戚；B错误，她是来寻求接济的；C正确；D错误。","knowledge_tag":"四大名著","ability_tag":"情节理解","difficulty":2,"grade":5},
  {"id":"lit_060","type":"single_choice","question":"下列人物与所属作品的对应，正确的一项是（　）。","options":["A. 孙悟空\u2014\u2014《红楼梦》","B. 诸葛亮\u2014\u2014《水浒传》","C. 武松\u2014\u2014《三国演义》","D. 贾宝玉\u2014\u2014《红楼梦》"],"answer":"D","analysis":"A错误，孙悟空出自《西游记》；B错误，诸葛亮出自《三国演义》；C错误，武松出自《水浒传》；D正确。","knowledge_tag":"四大名著","ability_tag":"人物作品对应","difficulty":1,"grade":3},
  {"id":"lit_061","type":"single_choice","question":"下列对《三国演义》中\u201c空城计\u201d这一情节理解正确的一项是（　）。","options":["A. 空城计是周瑜在赤壁之战中使用的计谋","B. 空城计中诸葛亮在城楼上弹琴，城门大开，吓退了司马懿","C. 空城计中诸葛亮派赵云埋伏在城中，大败魏军","D. 空城计是司马懿设计陷害诸葛亮的计谋"],"answer":"B","analysis":"A错误；B正确；C错误；D错误。","knowledge_tag":"四大名著","ability_tag":"情节理解","difficulty":2,"grade":5},
  {"id":"lit_062","type":"single_choice","question":"下列标点符号与其名称对应正确的一项是（　）。","options":["A. ，\u2014\u2014顿号","B. 、\u2014\u2014逗号","C. \u2014\u2014\u2014\u2014破折号","D. ；\u2014\u2014冒号"],"answer":"C","analysis":"，是逗号，、是顿号，\u2014\u2014是破折号，；是分号。只有C对应正确。","knowledge_tag":"标点符号","ability_tag":"标点识记","difficulty":1,"grade":3},
  {"id":"lit_063","type":"single_choice","question":"下列关于《水浒传》的描述，不正确的一项是（　）。","options":["A. \u201c及时雨\u201d是宋江的绰号","B. 武松在景阳冈打死了一只老虎","C. 林冲是被高俅陷害，最终被逼上梁山","D. 卢俊义是梁山的第一任首领"],"answer":"D","analysis":"A、B、C均正确；D错误，梁山首领顺序是王伦→晁盖→宋江。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":2,"grade":5},
  {"id":"lit_064","type":"single_choice","question":"下列《三国演义》人物与兵器的对应，正确的一项是（　）。","options":["A. 关羽\u2014\u2014丈八蛇矛","B. 张飞\u2014\u2014青龙偃月刀","C. 赵云\u2014\u2014亮银枪","D. 吕布\u2014\u2014亮银枪"],"answer":"C","analysis":"关羽用青龙偃月刀，张飞用丈八蛇矛，赵云用亮银枪，吕布用方天画戟。只有C正确。","knowledge_tag":"四大名著","ability_tag":"人物兵器","difficulty":3,"grade":6},
  {"id":"lit_065","type":"single_choice","question":"下列关于《西游记》情节的描述，对应正确的一项是（　）。","options":["A. 孙悟空偷吃金丹，被关进八卦炉\u2014\u2014大闹天宫","B. 孙悟空三借芭蕉扇\u2014\u2014三打白骨精","C. 唐僧被妖怪变成老虎\u2014\u2014大战红孩儿","D. 师徒历经九九八十一难\u2014\u2014西天取经"],"answer":"D","analysis":"A对应正确（大闹天宫）；B错误，三借芭蕉扇对应火焰山；C错误，变老虎是黄袍怪情节；D对应正确（西天取经）。D最为概括准确。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":2,"grade":5},
  {"id":"lit_066","type":"single_choice","question":"下列句子中，标点符号使用有误的一项是（　）。","options":["A. \u201c欲穷千里目，更上一层楼。\u201d这是王之涣《登鹳雀楼》中的名句。","B. 我喜欢吃的水果有：苹果、香蕉、橘子。","C. 他问我：\u201c你明天去不去公园？\u201d","D. 动物园里有老虎、狮子、猴子、等动物。"],"answer":"D","analysis":"D错误，\u201c等\u201d字前不加顿号。A、B、C均正确。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_067","type":"single_choice","question":"下列关于《红楼梦》的描述，不正确的一项是（　）。","options":["A. \u201c木石前盟\u201d指的是贾宝玉和林黛玉的爱情","B. 薛宝钗最后嫁给了贾宝玉","C. 王熙凤的结局是被贾府赶出家门","D. 贾府最终被抄家，走向衰落"],"answer":"C","analysis":"A正确；B正确；C错误，王熙凤病死在贾府；D正确。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":3,"grade":6},
  {"id":"lit_068","type":"single_choice","question":"下列句子中引号的作用，与其他三项不同的一项是（　）。","options":["A. 海伦学会了用手指\u201c说话\u201d。","B. 黄河是中华民族的\u201c摇篮\u201d。","C. 老师说：\u201c同学们，上课了。\u201d","D. 他被称为\u201c活雷锋\u201d。"],"answer":"C","analysis":"A、B、D中引号都表示特殊含义或特定称谓；C中引号表示直接引用。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":2,"grade":5},
  {"id":"lit_069","type":"single_choice","question":"下列对《水浒传》中\u201c武松打虎\u201d这一情节理解正确的一项是（　）。","options":["A. 武松在景阳冈打虎前喝了很多酒","B. 武松是用刀杀死老虎的","C. 武松打虎是因为老虎吃了他哥哥","D. 武松打虎后直接上了梁山"],"answer":"A","analysis":"A正确；B错误，是用拳头；C错误，打虎和杀嫂是两个情节；D错误，打虎后被封为阳谷县都头。","knowledge_tag":"四大名著","ability_tag":"情节理解","difficulty":2,"grade":5},
  {"id":"lit_070","type":"single_choice","question":"下列关于《三国演义》人物称号的对应，正确的一项是（　）。","options":["A. 诸葛亮\u2014\u2014美髯公","B. 关羽\u2014\u2014卧龙","C. 刘备\u2014\u2014皇叔","D. 曹操\u2014\u2014诗仙"],"answer":"C","analysis":"A错误，诸葛亮号卧龙；B错误，关羽称美髯公；C正确；D错误，曹操称奸雄，诗仙是李白。","knowledge_tag":"四大名著","ability_tag":"人物称号","difficulty":2,"grade":5},
  {"id":"lit_071","type":"single_choice","question":"下列对《西游记》中\u201c真假美猴王\u201d这一情节理解正确的一项是（　）。","options":["A. 假美猴王是六耳猕猴变的","B. 假美猴王是猪八戒变的","C. 真假美猴王只有如来佛祖能分辨出来","D. 假美猴王最后被唐僧收为徒弟"],"answer":"A","analysis":"A正确；B错误；C说法过于绝对；D错误，假美猴王被孙悟空打死。","knowledge_tag":"四大名著","ability_tag":"情节理解","difficulty":2,"grade":5},
  {"id":"lit_072","type":"single_choice","question":"下列句子中破折号的作用，与其他三项不同的一项是（　）。","options":["A. 我永远忘不了那一天\u2014\u20141927年4月28日。","B. 这就是我的梦想\u2014\u2014当一名老师。","C. \u201c呜\u2014\u2014\u201d火车开动了。","D. 他的籍贯\u2014\u2014湖南，是我一直想去的地方。"],"answer":"C","analysis":"A、B、D中破折号都表示解释说明；C中破折号表示声音延长。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":2,"grade":5},
  {"id":"lit_073","type":"single_choice","question":"下列关于《三国演义》的描述，不正确的一项是（　）。","options":["A. \u201c既生瑜，何生亮\u201d是周瑜临终前说的话","B. 诸葛亮七擒孟获，使孟获心服口服","C. 关羽在华容道放走了曹操","D. 司马懿本人篡夺了魏国政权，建立了晋朝"],"answer":"D","analysis":"A、B、C均正确；D错误，篡魏建晋的是司马懿的孙子司马炎，不是司马懿本人。","knowledge_tag":"四大名著","ability_tag":"情节辨识","difficulty":3,"grade":6},
  {"id":"lit_074","type":"single_choice","question":"下列四大名著与开篇名句的对应，正确的一项是（　）。","options":["A. 《三国演义》\u2014\u2014\u201c混沌未分天地乱，茫茫渺渺无人见\u201d","B. 《水浒传》\u2014\u2014\u201c话说天下大势，分久必合，合久必分\u201d","C. 《西游记》\u2014\u2014\u201c满纸荒唐言，一把辛酸泪\u201d","D. 《红楼梦》\u2014\u2014\u201c试看书林隐处，几多俊逸儒流\u201d"],"answer":"B","analysis":"A错误，是《西游记》开篇；B正确；C错误，是《红楼梦》开篇；D错误，是《水浒传》开篇。","knowledge_tag":"四大名著","ability_tag":"文学常识","difficulty":3,"grade":6},
  {"id":"lit_075","type":"single_choice","question":"下列关于《红楼梦》人物的描述，对应正确的一项是（　）。","options":["A. 性格泼辣，设局害死贾瑞\u2014\u2014薛宝钗","B. 温柔贤惠，恪守礼教，最后与贾宝玉成婚\u2014\u2014林黛玉","C. 从小被拐卖，长大后成为薛蟠的妾\u2014\u2014香菱","D. 是贾母的丫鬟，因被冤枉而跳井自尽\u2014\u2014晴雯"],"answer":"C","analysis":"A错误，是王熙凤；B错误，与宝玉成婚的是薛宝钗；C正确；D错误，跳井自尽的是金钏儿。","knowledge_tag":"四大名著","ability_tag":"人物辨识","difficulty":3,"grade":6},
  {"id":"lit_076","type":"single_choice","question":"下列句子中，标点符号使用正确的一项是（　）。","options":["A. \u201c你好，\u201d他笑着说，\u201c欢迎光临。\u201d","B. \u201c你好，\u201d他笑着说，\u201c欢迎光临\u201d","C. \u201c你好\u201d他笑着说\u201c欢迎光临。\u201d","D. 你好，他笑着说，欢迎光临。"],"answer":"A","analysis":"A正确；B错误缺句号；C错误缺冒号引号；D错误缺引号。","knowledge_tag":"标点符号","ability_tag":"标点运用","difficulty":2,"grade":5},
  {"id":"lit_077","type":"single_choice","question":"下列关于中国古代文学常识的说法，正确的一项是（　）。","options":["A. 李白被称为\u201c诗圣\u201d，杜甫被称为\u201c诗仙\u201d","B. 《论语》是孔子亲自编写的著作","C. 《诗经》是我国最早的诗歌总集","D. 唐宋八大家中不包括苏轼"],"answer":"C","analysis":"A错误，李白是诗仙杜甫是诗圣；B错误，《论语》是弟子记录的；C正确；D错误，唐宋八大家包括苏轼。","knowledge_tag":"文学常识","ability_tag":"文学知识","difficulty":2,"grade":5},
  {"id":"lit_078","type":"single_choice","question":"下列句子中引号的作用，与其他三项不同的一项是（　）。","options":["A. 像这样\u201c聪明\u201d的学生，还是少一些好。","B. 那个小偷\u201c拿\u201d走了别人的钱包。","C. 他被称为班上的\u201c小书法家\u201d。","D. 老师说：\u201c明天要考试。\u201d"],"answer":"D","analysis":"A、B、C中引号都表示讽刺或特殊含义；D中引号表示直接引用。","knowledge_tag":"标点符号","ability_tag":"标点作用","difficulty":2,"grade":5},
  {"id":"lit_079","type":"single_choice","question":"下列对《水浒传》中\u201c林冲风雪山神庙\u201d这一情节理解正确的一项是（　）。","options":["A. 林冲在山神庙中遇到了鲁智深","B. 林冲在山神庙中听到了陆谦等人的谈话，得知自己被陷害","C. 林冲在山神庙中被高俅派来的人杀死","D. 林冲在山神庙中向朝廷投降"],"answer":"B","analysis":"A错误；B正确，林冲偷听到阴谋后奋起反抗；C错误；D错误，林冲被逼上梁山。","knowledge_tag":"四大名著","ability_tag":"情节理解","difficulty":2,"grade":5}
]

with open('/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/questions_literature.json', 'w', encoding='utf-8') as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)

print(f"Written {len(questions)} questions")

# Validate
with open('/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/questions_literature.json', 'r') as f:
    data = json.load(f)
print(f"Validated: {len(data)} questions")
print(f"All single_choice: {all(q['type'] == 'single_choice' for q in data)}")
print(f"Answer format: {set(q['answer'] for q in data)}")
diff = {}
for q in data:
    d = q.get('difficulty')
    diff[d] = diff.get(d, 0) + 1
print(f"Difficulty: {dict(sorted(diff.items()))}")
grade = {}
for q in data:
    g = q.get('grade')
    grade[g] = grade.get(g, 0) + 1
print(f"Grade: {dict(sorted(grade.items()))}")
ktag = {}
for q in data:
    t = q.get('knowledge_tag')
    ktag[t] = ktag.get(t, 0) + 1
print(f"Knowledge tags: {dict(sorted(ktag.items()))}")
# Check answer distribution
ans = {}
for q in data:
    a = q['answer']
    ans[a] = ans.get(a, 0) + 1
print(f"Answer distribution: {dict(sorted(ans.items()))}")
