#!/usr/bin/env python3
"""Generate complete IPA phonetic dictionary for G8 vocabulary and fix dictation_en_g8.json"""
import json
import re
import string

# ============== COMPLETE IPA PHONETIC DICTIONARY for G8 (人教版Go for It! 8年级) ==============
# Format: word -> IPA phonetic (standard IPA with ˈ and stress marks)
PHONETIC_DICT = {
    # === A ===
    "a": "/eɪ/",
    "ability": "/əˈbɪləti/",
    "able": "/ˈeɪbl/",
    "aboard": "/əˈbɔːrd/",
    "about": "/əˈbaʊt/",
    "above": "/əˈbʌv/",
    "abroad": "/əˈbrɔːd/",
    "absence": "/ˈæbsns/",
    "absent": "/ˈæbsnt/",
    "accept": "/əkˈsept/",
    "accident": "/ˈæksɪdənt/",
    "achieve": "/əˈtʃiːv/",
    "achievement": "/əˈtʃiːvmənt/",
    "across": "/əˈkrɒs/",
    "act": "/ækt/",
    "action": "/ˈækʃn/",
    "active": "/ˈæktɪv/",
    "activity": "/ækˈtɪvəti/",
    "actor": "/ˈæktər/",
    "actress": "/ˈæktrəs/",
    "actual": "/ˈæktʃuəl/",
    "actually": "/ˈæktʃuəli/",
    "ad": "/æd/",
    "add": "/æd/",
    "addition": "/əˈdɪʃn/",
    "address": "/əˈdres/ /əˈdres/",
    "admire": "/ədˈmaɪər/",
    "admit": "/ədˈmɪt/",
    "adult": "/ˈædʌlt/ /əˈdʌlt/",
    "advance": "/ədˈvɑːns/",
    "advantage": "/ədˈvɑːntɪdʒ/",
    "adventure": "/ədˈventʃər/",
    "advertisement": "/ədˈvɜːrtɪzmənt/ /ˌædvərˈtaɪzmnt/",
    "advertise": "/ˈædvətaɪz/",
    "advice": "/ədˈvaɪs/",
    "advise": "/ədˈvaɪz/",
    "affair": "/əˈfer/",
    "affect": "/əˈfekt/",
    "afford": "/əˈfɔːrd/",
    "afraid": "/əˈfreɪd/",
    "africa": "/ˈæfrɪkə/",
    "after": "/ˈɑːftər/",
    "afternoon": "/ˌɑːftərˈnuːn/",
    "again": "/əˈɡen/",
    "against": "/əˈɡenst/ /əˈɡeɪnst/",
    "age": "/eɪdʒ/",
    "ago": "/əˈɡəʊ/",
    "agree": "/əˈɡriː/",
    "agreement": "/əˈɡriːmənt/",
    "ahead": "/əˈhed/",
    "air": "/er/",
    "airplane": "/erpleɪn/",
    "airport": "/erpɔːrt/",
    "alarm": "/əˈlɑːrm/",
    "album": "/ˈælbəm/",
    "alive": "/əˈlaɪv/",
    "all": "/ɔːl/",
    "allow": "/əˈlaʊ/",
    "almost": "/ˈɔːlməʊst/",
    "alone": "/əˈləʊn/",
    "along": "/əˈlɒŋ/",
    "aloud": "/əˈlaʊd/",
    "already": "/ɔːlˈredi/",
    "also": "/ˈɔːlsəʊ/",
    "although": "/ɔːlˈðəʊ/",
    "always": "/ˈɔːlweɪz/",
    "am": "/æm/ /əm/",
    "amazing": "/əˈmeɪzɪŋ/",
    "ambulance": "/ˈæmbjələns/",
    "america": "/əˈmerɪkə/",
    "american": "/əˈmerɪkn/",
    "among": "/əˈmʌŋ/",
    "ancient": "/ˈeɪnʃənt/",
    "and": "/ænd/ /ənd/ /ən/",
    "angry": "/ˈæŋɡri/",
    "animal": "/ˈænɪml/",
    "announce": "/əˈnaʊns/",
    "annoy": "/əˈnɔɪ/",
    "another": "/əˈnʌðər/",
    "answer": "/ˈɑːnsər/ /ˈænsər/",
    "ant": "/ænt/",
    "any": "/ˈeni/",
    "anybody": "/ˈenibɒdi/",
    "anyone": "/ˈeniwʌn/",
    "anything": "/ˈeniθɪŋ/",
    "anyway": "/ˈeniweɪ/",
    "anywhere": "/ˈeniweər/",
    "apartment": "/əˈpɑːrtmənt/",
    "apologize": "/əˈpɒlədʒaɪz/",
    "apology": "/əˈpɒlədʒi/",
    "appear": "/əˈpɪər/",
    "appearance": "/əˈpɪərəns/",
    "apple": "/ˈæpl/",
    "application": "/ˌæplɪˈkeɪʃn/",
    "apply": "/əˈplaɪ/",
    "appointment": "/əˈpɔɪntmənt/",
    "appreciate": "/əˈpriːʃieɪt/",
    "april": "/ˈeɪprəl/",
    "area": "/ˈeriə/",
    "argue": "/ˈɑːrɡjuː/",
    "argument": "/ˈɑːrɡjumənt/",
    "arm": "/ɑːrm/",
    "around": "/əˈraʊnd/",
    "arrange": "/əˈreɪndʒ/",
    "arrival": "/əˈraɪvl/",
    "arrive": "/əˈraɪv/",
    "art": "/ɑːrt/",
    "article": "/ˈɑːrtɪkl/",
    "artist": "/ˈɑːrtɪst/",
    "as": "/æz/ /əz/",
    "asian": "/ˈeɪʃn/",
    "ask": "/ɑːsk/",
    "asleep": "/əˈsliːp/",
    "at": "/æt/ /ət/",
    "atlas": "/ˈætləs/",
    "attention": "/əˈtenʃn/",
    "august": "/ˈɔːɡəst/",
    "aunt": "/ɑːnt/ /ænt/",
    "australia": "/ɒˈstreɪljə/",
    "autumn": "/ˈɔːtm/",
    "available": "/əˈveɪləbl/",
    "avoid": "/əˈvɔɪd/",
    "awake": "/əˈweɪk/",
    "award": "/əˈwɔːrd/",
    "away": "/əˈweɪ/",
    "awesome": "/ˈɔːsəm/",
    "awful": "/ˈɔːfl/",
    "baby": "/ˈbeɪbi/",
    "back": "/bæk/",
    "background": "/ˈbækɡraʊnd/",
    "bad": "/bæd/",
    "badly": "/ˈbædli/",
    "badminton": "/ˈbædmɪntən/",
    "bag": "/bæɡ/",
    "baggage": "/ˈbæɡɪdʒ/",
    "balance": "/ˈbæləns/",
    "balcony": "/ˈbælkəni/",
    "ball": "/bɔːl/",
    "balloon": "/bəˈluːn/",
    "bamboo": "/ˌbæmˈbuː/",
    "banana": "/bəˈnɑːnə/",
    "band": "/bænd/",
    "bank": "/bæŋk/",
    "bar": "/bɑːr/",
    "barcode": "/ˈbɑːrkəʊd/",
    "bargain": "/ˈbɑːrɡɪn/",
    "base": "/beɪs/",
    "baseball": "/ˈbeɪsbɔːl/",
    "basic": "/ˈbeɪsɪk/",
    "basin": "/ˈbeɪsn/",
    "basket": "/ˈbæskɪt/",
    "basketball": "/ˈbæskɪtbɔːl/",
    "bat": "/bæt/",
    "bath": "/bɑːθ/ /bæθ/",
    "bathe": "/beɪð/",
    "bathroom": "/ˈbɑːθruːm/ /ˈbæθruːm/",
    "be": "/biː/ /bi/",
    "beach": "/biːtʃ/",
    "bean": "/biːn/",
    "bear": "/ber/ /beər/",
    "beautiful": "/ˈbjuːtɪfl/",
    "beauty": "/ˈbjuːti/",
    "because": "/bɪˈkɒz/",
    "become": "/bɪˈkʌm/",
    "bed": "/bed/",
    "bedroom": "/bedruːm/ /bedrum/",
    "bee": "/biː/",
    "beef": "/biːf/",
    "beer": "/bɪr/",
    "before": "/bɪˈfɔːr/",
    "begin": "/bɪˈɡɪn/",
    "beginning": "/bɪˈɡɪnɪŋ/",
    "behavior": "/bɪˈheɪvjər/",
    "behind": "/bɪˈhaɪnd/",
    "believe": "/bɪˈliːv/",
    "bell": "/bel/",
    "belong": "/bɪˈlɒŋ/",
    "below": "/bɪˈləʊ/",
    "belt": "/belt/",
    "bench": "/bentʃ/",
    "bend": "/bend/",
    "benefit": "/ˈbenɪfɪt/",
    "beside": "/bɪˈsaɪd/",
    "besides": "/bɪˈsaɪdz/",
    "best": "/best/",
    "better": "/ˈbetər/",
    "between": "/bɪˈtwiːn/",
    "big": "/bɪɡ/",
    "bike": "/baɪk/",
    "bill": "/bɪl/",
    "billion": "/ˈbɪljən/",
    "biology": "/baɪˈɒlədʒi/",
    "bird": "/bɜːrd/",
    "birth": "/bɜːrθ/",
    "birthday": "/ˈbɜːrθdeɪ/",
    "biscuit": "/ˈbɪskɪt/",
    "bit": "/bɪt/",
    "bite": "/baɪt/",
    "bitter": "/ˈbɪtər/",
    "black": "/blæk/",
    "blackboard": "/ˈblækbɔːrd/",
    "blank": "/blæŋk/",
    "blanket": "/ˈblæŋkɪt/",
    "bleed": "/bliːd/",
    "blind": "/blaɪnd/",
    "block": "/blɒk/",
    "blood": "/blʌd/",
    "blow": "/bləʊ/",
    "blue": "/bluː/",
    "board": "/bɔːrd/",
    "boat": "/bəʊt/",
    "body": "/ˈbɒdi/",
    "boil": "/bɔɪl/",
    "bold": "/bəʊld/",
    "bomb": "/bɒm/",
    "book": "/bʊk/",
    "bookshop": "/ˈbʊkʃɒp/",
    "bookstore": "/ˈbʊkstɔːr/",
    "boom": "/buːm/",
    "boot": "/buːt/",
    "border": "/ˈbɔːrdər/",
    "boring": "/ˈbɔːrɪŋ/",
    "born": "/bɔːrn/",
    "borrow": "/ˈbɒrəʊ/",
    "boss": "/bɒs/ /bɔːs/",
    "both": "/bəʊθ/",
    "bother": "/ˈbɒðər/",
    "bottle": "/ˈbɒtl/",
    "bottom": "/ˈbɒtəm/",
    "bounce": "/baʊns/",
    "bow": "/baʊ/ /bəʊ/",
    "bowl": "/bəʊl/",
    "box": "/bɒks/",
    "boy": "/bɔɪ/",
    "brain": "/breɪn/",
    "brave": "/breɪv/",
    "bread": "/bred/",
    "break": "/breɪk/",
    "breakfast": "/ˈbrekfəst/",
    "breath": "/breθ/",
    "breathe": "/briːð/",
    "bridge": "/brɪdʒ/",
    "bright": "/braɪt/",
    "bring": "/brɪŋ/",
    "brother": "/ˈbrʌðər/",
    "brown": "/braʊn/",
    "brush": "/brʌʃ/",
    "build": "/bɪld/",
    "building": "/ˈbɪldɪŋ/",
    "burn": "/bɜːrn/",
    "burst": "/bɜːrst/",
    "bury": "/ˈberi/",
    "bus": "/bʌs/",
    "business": "/ˈbɪznəs/",
    "busy": "/ˈbɪzi/",
    "but": "/bʌt/ /bət/",
    "butcher": "/ˈbʊtʃər/",
    "butter": "/ˈbʌtər/",
    "button": "/ˈbʌtn/",
    "buy": "/baɪ/",
    "buyer": "/ˈbaɪər/",
    "by": "/baɪ/",
    "bye": "/baɪ/",
    "cab": "/kæb/",
    "cafe": "/ˈkæfeɪ/ /kæˈfeɪ/",
    "cage": "/keɪdʒ/",
    "cake": "/keɪk/",
    "call": "/kɔːl/",
    "calm": "/kɑːlm/",
    "camera": "/ˈkæmrə/",
    "camp": "/kæmp/",
    "campaign": "/kæmˈpeɪn/",
    "can": "/kæn/ /kən/",
    "canada": "/ˈkænədə/",
    "canadian": "/kəˈneɪdiən/",
    "cancel": "/ˈkænsl/",
    "cancer": "/ˈkænsər/",
    "candidate": "/ˈkændɪdeɪt/ /ˈkændɪdət/",
    "candle": "/ˈkændl/",
    "candy": "/ˈkændi/",
    "cap": "/kæp/",
    "capital": "/ˈkæpɪtl/",
    "captain": "/ˈkæptɪn/",
    "car": "/kɑːr/",
    "card": "/kɑːrd/",
    "cardboard": "/ˈkɑːrdbɔːrd/",
    "care": "/ker/",
    "careful": "/ˈkerfl/",
    "careless": "/ˈkerləs/",
    "carpet": "/ˈkɑːrpɪt/",
    "carry": "/ˈkæri/",
    "cartoon": "/kɑːrˈtuːn/",
    "carrot": "/ˈkærət/",
    "case": "/keɪs/",
    "cash": "/kæʃ/",
    "castle": "/ˈkɑːsl/ /ˈkæsl/",
    "cat": "/kæt/",
    "catch": "/kætʃ/",
    "cause": "/kɔːz/",
    "cd": "/ˌsiːˈdiː/",
    "ceiling": "/ˈsiːlɪŋ/",
    "celebrate": "/ˈselibreɪt/",
    "celebration": "/ˌselɪˈbreɪʃn/",
    "center": "/ˈsentər/ /ˈsentə/",
    "centimeter": "/ˈsentɪmiːtər/",
    "central": "/ˈsentrl/",
    "century": "/ˈsentʃuri/",
    "certain": "/ˈsɜːrtn/",
    "certainly": "/ˈsɜːrtnli/",
    "certificate": "/sərˈtɪfɪkət/",
    "chain": "/tʃeɪn/",
    "chair": "/tʃer/",
    "chairman": "/ˈtʂermən/",
    "chalk": "/tʃɔːk/",
    "chance": "/tʃæns/",
    "change": "/tʃeɪndʒ/",
    "channel": "/ˈtʃænl/",
    "chapter": "/ˈtʃæptər/",
    "character": "/ˈkærəktər/",
    "charge": "/tʃɑːrdʒ/",
    "chat": "/tʃæt/",
    "cheap": "/tʃiːp/",
    "check": "/tʃek/",
    "checkbook": "/ˈtʃekbʊk/",
    "checkout": "/ˈtʃekaʊt/",
    "cheek": "/tʃiːk/",
    "cheer": "/tʃɪr/",
    "cheese": "/tʃiːz/",
    "chemistry": "/ˈkemɪstri/",
    "chess": "/tʃes/",
    "chest": "/tʃest/",
    "chew": "/tʃuː/",
    "chicken": "/ˈtʃɪkɪn/",
    "chief": "/tʃiːf/",
    "child": "/tʃaɪld/",
    "chin": "/tʃɪn/",
    "china": "/ˈtʃaɪnə/",
    "chinese": "/ˌtʃaɪˈniːz/",
    "chip": "/tʃɪp/",
    "chocolate": "/ˈtʃɒklɪt/ /ˈtʃɒklət/",
    "choice": "/tʃɔɪs/",
    "choose": "/tʃuːz/",
    "church": "/tʃɜːrtʃ/",
    "cinema": "/ˈsɪnɪmə/",
    "circle": "/ˈsɜːrkl/",
    "citizen": "/ˈsɪtizn/",
    "city": "/ˈsɪti/",
    "class": "/klɑːs/ /klæs/",
    "classic": "/ˈklæsɪk/",
    "classmate": "/ˈklɑːsmeɪt/",
    "classroom": "/ˈklɑːsruːm/ /ˈklæsruːm/",
    "clean": "/kliːn/",
    "clear": "/klɪr/",
    "clerk": "/klɜːrk/ /klɑːrk/",
    "clever": "/ˈlevər/",
    "click": "/klɪk/",
    "climate": "/ˈklaɪmət/",
    "climb": "/klaɪm/",
    "clinic": "/ˈklɪnɪk/",
    "clock": "/klɒk/",
    "close": "/kləʊz/ /kləʊs/",
    "cloth": "/klɒθ/ /klɔːθ/",
    "clothes": "/kləʊðz/ /kləʊz/",
    "clothing": "/ˈkləʊðɪŋ/",
    "cloud": "/klaʊd/",
    "cloudy": "/ˈklaʊdi/",
    "club": "/klʌb/",
    "coach": "/kəʊtʃ/",
    "coal": "/kəʊl/",
    "coast": "/kəʊst/",
    "coat": "/kəʊt/",
    "coffee": "/ˈkɒfi/ /ˈkɔːfi/",
    "coin": "/kɔɪn/",
    "coke": "/kəʊk/",
    "cold": "/kəʊld/",
    "collect": "/kəˈlekt/",
    "college": "/ˈkɒlɪdʒ/",
    "color": "/ˈkʌlər/ /ˈkʌlə/",
    "colour": "/ˈkʌlər/ /ˈkʌlə/",
    "comb": "/kəʊm/",
    "come": "/kʌm/",
    "comedy": "/ˈkɒmədi/",
    "comfort": "/ˈkʌmfərt/ /ˈkʌmfət/",
    "comfortable": "/ˈkʌmftəbl/ /ˈkʌmfərtəbl/",
    "comic": "/ˈkɒmɪk/",
    "command": "/kəˈmɑːnd/",
    "common": "/ˈkɒmən/",
    "communicate": "/kəˈmjuːnikeɪt/",
    "communication": "/kəˌmjuːnɪˈkeɪʃn/",
    "company": "/ˈkʌmpəni/",
    "compare": "/kəmˈper/",
    "competition": "/ˌkɒmpəˈtɪʃn/",
    "complete": "/kəmˈpliːt/",
    "completely": "/kəmˈpliːtli/",
    "composition": "/ˌkɒmpəˈzɪʃn/",
    "computer": "/kəmˈpjuːtər/",
    "concert": "/ˈkɒnsərt/",
    "condition": "/kənˈdɪʃn/",
    "connect": "/kəˈnekt/",
    "connection": "/kəˈnekʃn/",
    "consider": "/kənˈsɪdər/",
    "continue": "/kənˈtɪnjuː/",
    "control": "/kənˈtrəʊl/",
    "conversation": "/ˌkɒnvərˈseɪʃn/",
    "cook": "/kʊk/",
    "cookie": "/ˈkʊki/",
    "cool": "/kuːl/",
    "copy": "/ˈkɒpi/",
    "corn": "/kɔːrn/",
    "corner": "/ˈkɔːrnər/",
    "correct": "/kəˈrekt/",
    "cost": "/kɒst/ /kɔːst/",
    "cotton": "/ˈkɒtn/",
    "cough": "/kɒf/ /kɔːf/",
    "could": "/kʊd/ /kəd/",
    "count": "/kaʊnt/",
    "counter": "/ˈkaʊntər/",
    "country": "/ˈkʌntri/",
    "countryside": "/ˈkʌntrisaɪd/",
    "couple": "/ˈkʌpl/",
    "courage": "/ˈkʌrɪdʒ/",
    "course": "/kɔːrs/",
    "cousin": "/ˈkʌzn/",
    "cover": "/ˈkʌvər/",
    "cow": "/kaʊ/",
    "crayon": "/ˈkreɪən/ /ˈkreɪɒn/",
    "crayfish": "/ˈkreɪfɪʃ/",
    "crazy": "/ˈkreɪzi/",
    "create": "/kriˈeɪt/",
    "cross": "/krɒs/ /krɔːs/",
    "crossing": "/ˈkrɒsɪŋ/ /ˈkrɔːsɪŋ/",
    "crowd": "/kraʊd/",
    "cruel": "/ˈkruːəl/",
    "cry": "/kraɪ/",
    "culture": "/ˈkʌltʃər/ /ˈkʌltʃə/",
    "cup": "/kʌp/",
    "curtain": "/ˈkɜːrtn/",
    "custom": "/ˈkʌstəm/",
    "customer": "/ˈkʌstəmər/",
    "cut": "/kʌt/",
    "dad": "/dæd/",
    "daily": "/ˈdeɪli/",
    "damage": "/ˈdæmɪdʒ/",
    "dance": "/dɑːns/ /dæns/",
    "danger": "/ˈdeɪndʒər/",
    "dangerous": "/ˈdeɪndʒərəs/",
    "dare": "/der/",
    "dark": "/dɑːrk/",
    "darkness": "/ˈdɑːrknəs/",
    "data": "/ˈdeɪtə/ /ˈdɑːtə/ /ˈdætə/",
    "date": "/deɪt/",
    "daughter": "/ˈdɔːtər/",
    "day": "/deɪ/",
    "dead": "/ded/",
    "deal": "/diːl/",
    "dear": "/dɪr/",
    "death": "/deθ/",
    "debate": "/dɪˈbeɪt/",
    "decide": "/dɪˈsaɪd/",
    "decision": "/dɪˈsɪʒn/",
    "declare": "/dɪˈkler/",
    "decorate": "/ˈdekəreɪt/",
    "dedicate": "/ˈdedɪkeɪt/",
    "deep": "/diːp/",
    "deeply": "/ˈdiːpli/",
    "degree": "/dɪˈɡriː/",
    "delay": "/dɪˈleɪ/",
    "delicious": "/dɪˈlɪʃəs/",
    "delight": "/dɪˈlaɪt/",
    "deliver": "/dɪˈlɪvər/",
    "dentist": "/ˈdentɪst/",
    "depend": "/dɪˈpend/",
    "describe": "/dɪˈskraɪb/",
    "desert": "/ˈdezərt/ /dɪˈzɜːrt/",
    "design": "/dɪˈzaɪn/",
    "desk": "/desk/",
    "destroy": "/dɪˈstrɔɪ/",
    "develop": "/dɪˈveləp/",
    "devote": "/dɪˈvəʊt/",
    "dialogue": "/ˈdaɪəlɒɡ/ /ˈdaɪəlɔːɡ/",
    "diary": "/ˈdaɪəri/",
    "dictionary": "/ˈdɪkʃəneri/ /ˈdɪkʃənri/",
    "die": "/daɪ/",
    "diet": "/ˈdaɪət/",
    "difference": "/ˈdɪfrəns/",
    "different": "/ˈdɪfrənt/",
    "difficult": "/ˈdɪfɪkəlt/",
    "difficulty": "/ˈdɪfɪkəlti/",
    "dig": "/dɪɡ/",
    "digital": "/ˈdɪdʒɪtl/",
    "dinner": "/ˈdɪnər/",
    "direct": "/dəˈrekt/ /daɪˈrekt/",
    "direction": "/dəˈrekʃn/ /daɪˈrekʃn/",
    "director": "/dəˈrektər/ /daɪˈrektər/",
    "dirty": "/ˈdɜːrti/",
    "disappear": "/ˌdɪsəˈpɪr/",
    "disappoint": "/ˌdɪsəˈpɔɪnt/",
    "disaster": "/dɪˈzɑːstər/",
    "discover": "/dɪˈskʌvər/",
    "discovery": "/dɪˈskʌvəri/",
    "discuss": "/dɪˈskʌs/",
    "discussion": "/dɪˈskʌʃn/",
    "dish": "/dɪʃ/",
    "disk": "/dɪsk/",
    "dismiss": "/dɪsˈmɪs/",
    "distance": "/ˈdɪstəns/",
    "distant": "/ˈdɪstənt/",
    "divide": "/dɪˈvaɪd/",
    "do": "/duː/ /də/ /du/",
    "doctor": "/ˈdɒktər/",
    "dog": "/dɒɡ/ /dɔːg/",
    "doll": "/dɒl/",
    "dollar": "/ˈdɒlər/",
    "door": "/dɔːr/",
    "double": "/ˈdʌbl/",
    "doubt": "/daʊt/",
    "down": "/daʊn/",
    "downstairs": "/ˌdaʊnˈsterz/",
    "dozen": "/ˈdʌzn/",
    "draw": "/drɔː/",
    "drawer": "/drɔːr/",
    "dream": "/driːm/",
    "dress": "/dres/",
    "drink": "/drɪŋk/",
    "drive": "/draɪv/",
    "driver": "/ˈdraɪvər/",
    "drop": "/drɒp/",
    "drug": "/drʌɡ/",
    "drum": "/drʌm/",
    "dry": "/draɪ/",
    "duck": "/dʌk/",
    "during": "/ˈdjʊərɪŋ/ /ˈdʊrɪŋ/",
    "duty": "/ˈdjuːti/ /ˈduːti/",
    "each": "/iːtʃ/",
    "ear": "/ɪr/",
    "early": "/ˈɜːrli/",
    "earth": "/ɜːrθ/",
    "east": "/iːst/",
    "eastern": "/ˈiːstərn/",
    "easy": "/ˈiːzi/",
    "eat": "/iːt/",
    "education": "/ˌedʒuˈkeɪʃn/",
    "educational": "/ˌedʒuˈkeɪʃənl/",
    "egg": "/eɡ/",
    "eight": "/eɪt/",
    "eighteen": "/ˌeɪˈtiːn/",
    "eighth": "/eɪtθ/",
    "eighty": "/ˈeɪti/",
    "either": "/ˈaɪðər/ /ˈiːðər/",
    "elder": "/ˈeldər/",
    "electric": "/ɪˈlektrɪk/",
    "electricity": "/ɪˌlekˈtrɪsəti/",
    "electronic": "/ɪˌlekˈtrɒnɪk/",
    "elephant": "/ˈelɪfənt/",
    "else": "/els/",
    "email": "/ˈiːmeɪl/",
    "empty": "/ˈempti/",
    "encourage": "/ɪnˈkʌrɪdʒ/",
    "encouragement": "/ɪnˈkʌrɪdʒmənt/",
    "end": "/end/",
    "enemy": "/ˈenimi/",
    "energy": "/ˈenərdʒi/",
    "engine": "/ˈendʒɪn/",
    "engineer": "/ˌendʒɪˈnɪr/",
    "england": "/ˈɪŋɡlənd/",
    "english": "/ˈɪŋɡlɪʃ/",
    "enjoy": "/ɪnˈdʒɔɪ/",
    "enough": "/ɪˈnʌf/",
    "enter": "/ˈentər/",
    "entrance": "/ˈentrəns/",
    "environment": "/ɪnˈvaɪrənmənt/ /ɪnˈvaɪrənment/",
    "envy": "/ˈenvi/",
    "eraser": "/ɪˈreɪzər/ /ɪˈreɪsər/",
    "escape": "/ɪˈskeɪp/",
    "especially": "/ɪˈspeʃli/",
    "europe": "/ˈjʊərəp/ /ˈjʊrp/",
    "european": "/jʊərəˈpiːən/",
    "even": "/ˈiːvn/",
    "evening": "/ˈiːvnɪŋ/",
    "event": "/ɪˈvent/",
    "ever": "/ˈevər/",
    "every": "/ˈevri/",
    "everybody": "/ˈevribɒdi/",
    "everyone": "/ˈevriwʌn/",
    "everything": "/ˈevriθɪŋ/",
    "everywhere": "/ˈevriweər/",
    "exact": "/ɪɡˈzækt/",
    "exam": "/ɪɡˈzæm/",
    "examination": "/ɪɡˌzæmiˈneɪʃn/",
    "examine": "/ɪɡˈzæmɪn/",
    "example": "/ɪɡˈzɑːmpl/ /ɪɡˈzæmpl/",
    "excellent": "/ˈeksələnt/",
    "except": "/ɪkˈsept/",
    "excite": "/ɪkˈsaɪt/",
    "excited": "/ɪkˈsaɪtɪd/",
    "exciting": "/ɪkˈsaɪtɪŋ/",
    "excuse": "/ɪkˈskjuːz/",
    "exercise": "/ˈeksəsaɪz/",
    "exist": "/ɪɡˈzɪst/",
    "exit": "/ˈeɡzɪt/ /ˈeksɪt/",
    "expect": "/ɪkˈspekt/",
    "expensive": "/ɪkˈspensɪv/",
    "experience": "/ɪkˈspɪəriəns/",
    "experiment": "/ɪkˈsperɪmənt/",
    "expert": "/ˈekspɜːrt/",
    "explain": "/ɪkˈspleɪn/",
    "explanation": "/ˌekspləˈneɪʃn/",
    "express": "/ɪkˈspres/",
    "expression": "/ɪkˈspreʃn/",
    "extra": "/ˈekstrə/",
    "eye": "/aɪ/",
    "face": "/feɪs/",
    "fact": "/fækt/",
    "factory": "/ˈfæktri/",
    "fail": "/feɪl/",
    "fair": "/fer/",
    "fall": "/fɔːl/",
    "false": "/fɔːls/",
    "family": "/ˈfæməli/",
    "famous": "/ˈfeɪməs/",
    "fan": "/fæn/",
    "fantastic": "/fænˈtæstɪk/",
    "far": "/fɑːr/",
    "farm": "/fɑːrm/",
    "farmer": "/ˈfɑːrmər/",
    "fashion": "/ˈfæʃn/",
    "fast": "/fɑːst/ /fæst/",
    "fat": "/fæt/",
    "father": "/ˈfɑːðər/",
    "fault": "/fɔːlt/",
    "favor": "/ˈfeɪvər/ /ˈfeɪvə/",
    "favorite": "/ˈfeɪvərɪt/",
    "fear": "/fɪr/",
    "feature": "/ˈfiːtʃər/",
    "february": "/ˈfebruəri/ /ˈfebrueri/",
    "feed": "/fiːd/",
    "feel": "/fiːl/",
    "feeling": "/ˈfiːlɪŋ/",
    "fellow": "/ˈfeləʊ/",
    "female": "/ˈfiːmeɪl/",
    "fence": "/fens/",
    "fetch": "/fetʃ/",
    "fever": "/ˈfiːvər/",
    "few": "/fjuː/",
    "field": "/fiːld/",
    "fifteen": "/ˌfɪfˈtiːn/",
    "fifth": "/fɪfθ/",
    "fifty": "/ˈfɪfti/",
    "fight": "/faɪt/",
    "fill": "/fɪl/",
    "film": "/fɪlm/",
    "final": "/ˈfaɪnl/",
    "find": "/faɪnd/",
    "fine": "/faɪn/",
    "finger": "/ˈfɪŋɡər/",
    "finish": "/ˈfɪnɪʃ/",
    "fire": "/ˈfaɪər/",
    "fireman": "/ˈfaɪərmən/",
    "first": "/fɜːrst/",
    "fish": "/fɪʃ/",
    "fit": "/fɪt/",
    "fix": "/fɪks/",
    "flag": "/flæɡ/",
    "flat": "/flæt/",
    "floor": "/flɔːr/",
    "flower": "/ˈflaʊər/",
    "fly": "/flaɪ/",
    "fog": "/fɒɡ/ /fɔːɡ/",
    "fold": "/fəʊld/",
    "folk": "/fəʊk/",
    "follow": "/ˈfɒləʊ/",
    "food": "/fuːd/",
    "foot": "/fʊt/",
    "football": "/ˈfʊtbɔːl/",
    "for": "/fɔːr/ /fər/ /fɚ/",
    "force": "/fɔːrs/",
    "foreign": "/ˈfɒrən/ /ˈfɔːrən/",
    "foreigner": "/ˈfɒrənər/ /ˈfɔːrənər/",
    "forest": "/ˈfɒrɪst/ /ˈfɔːrɪst/",
    "forever": "/fərˈevər/",
    "forget": "/fərˈɡet/",
    "fork": "/fɔːrk/",
    "form": "/fɔːrm/",
    "former": "/ˈfɔːrmər/",
    "fortnight": "/ˈfɔːrtnaɪt/",
    "fortune": "/ˈfɔːrtʃuːn/",
    "forward": "/ˈfɔːrwərd/",
    "found": "/faʊnd/",
    "four": "/fɔːr/",
    "fourteen": "/ˌfɔːrˈtiːn/",
    "fourth": "/fɔːrθ/",
    "fox": "/fɒks/",
    "free": "/friː/",
    "freedom": "/ˈfriːdəm/",
    "freeze": "/friːz/",
    "fresh": "/freʃ/",
    "friday": "/ˈfraɪdeɪ/",
    "fridge": "/frɪdʒ/",
    "friend": "/frend/",
    "friendly": "/ˈfrendli/",
    "friendship": "/ˈfrendʃɪp/",
    "from": "/frɒm/ /frʌm/ /frəm/",
    "front": "/frʌnt/",
    "fruit": "/fruːt/",
    "full": "/fʊl/",
    "fun": "/fʌn/",
    "funny": "/ˈfʌni/",
    "future": "/ˈfjuːtʃər/",
    "gain": "/ɡeɪn/",
    "game": "/ɡeɪm/",
    "garage": "/ɡəˈrɑːʒ/ /ˈɡærɑːʒ/",
    "garbage": "/ˈɡɑːrbɪdʒ/",
    "garden": "/ˈɡɑːrdn/",
    "gate": "/ɡeɪt/",
    "general": "/ˈdʒenrl/",
    "gentle": "/ˈdʒentl/",
    "gentleman": "/ˈdʒentlmən/",
    "geography": "/dʒiˈɒɡrəfi/",
    "geometry": "/dʒiˈɒmətri/",
    "germany": "/ˈdʒɜːrməni/",
    "get": "/ɡet/",
    "gift": "/ɡɪft/",
    "giraffe": "/dʒɪˈrɑːf/",
    "girl": "/ɡɜːrl/",
    "give": "/ɡɪv/",
    "glad": "/ɡlæd/",
    "glass": "/ɡlɑːs/ /ɡlæs/",
    "globe": "/ɡləʊb/",
    "glove": "/ɡlʌv/",
    "go": "/ɡəʊ/ /ɡoʊ/",
    "goal": "/ɡəʊl/",
    "goat": "/ɡəʊt/",
    "god": "/ɡɒd/ /ɡɑːd/",
    "gold": "/ɡəʊld/",
    "golden": "/ˈɡəʊldən/",
    "good": "/ɡʊd/",
    "goose": "/ɡuːs/",
    "government": "/ˈɡʌvənmənt/ /ˈɡʌvərnment/",
    "grade": "/ɡreɪd/",
    "grammar": "/ˈɡræmər/",
    "grandchild": "/ˈɡræn tʃaɪld/",
    "granddaughter": "/ˈɡrændɔːtər/",
    "grandfather": "/ˈɡrænfɑːðər/ /ˈɡrændfɑːðər/",
    "grandmother": "/ˈɡrænmʌðər/ /ˈɡrændmʌðər/",
    "grandparent": "/ˈɡrænperənt/ /ˈɡrændperənt/",
    "grandson": "/ˈɡrænsʌn/",
    "grass": "/ɡrɑːs/ /ɡræs/",
    "gray": "/ɡreɪ/",
    "great": "/ɡreɪt/",
    "green": "/ɡriːn/",
    "greet": "/ɡriːt/",
    "grey": "/ɡreɪ/",
    "ground": "/ɡraʊnd/",
    "group": "/ɡruːp/",
    "grow": "/ɡrəʊ/",
    "guard": "/ɡɑːrd/",
    "guess": "/ɡes/",
    "guest": "/ɡest/",
    "guide": "/ɡaɪd/",
    "gun": "/ɡʌn/",
    "habit": "/ˈhæbɪt/",
    "hair": "/her/",
    "haircut": "/ˈherkʌt/",
    "half": "/hɑːf/ /hæf/",
    "hall": "/hɔːl/",
    "ham": "/hæm/",
    "hamburger": "/ˈhæmbɜːrɡər/",
    "hand": "/hænd/",
    "handbag": "/ˈhændbæɡ/",
    "handkerchief": "/ˈhæŋkərtʃɪf/ /ˈhæŋkərtʃiːf/",
    "handle": "/ˈhændl/",
    "handsome": "/ˈhænsəm/",
    "hang": "/hæŋ/",
    "happen": "/ˈhæpn/",
    "happy": "/ˈhæpi/",
    "harbor": "/ˈhɑːrbər/ /ˈhɑːbər/",
    "hard": "/hɑːrd/",
    "hardly": "/ˈhɑːrdli/",
    "hardworking": "/ˌhɑːrdˈwɜːrkɪŋ/",
    "hat": "/hæt/",
    "hate": "/heɪt/",
    "have": "/hæv/ /həv/ /əv/",
    "he": "/hiː/ /hi/ /ɪ/",
    "head": "/hed/",
    "health": "/helθ/",
    "healthy": "/ˈhelθi/",
    "hear": "/hɪr/",
    "heart": "/hɑːrt/",
    "heat": "/hiːt/",
    "heavy": "/ˈhevi/",
    "height": "/haɪt/",
    "hello": "/həˈləʊ/ /hɛˈloʊ/",
    "help": "/help/",
    "helpful": "/ˈhelpfl/",
    "hen": "/hen/",
    "her": "/hɜːr/ /hər/ /ər/",
    "here": "/hɪr/",
    "hero": "/ˈhɪroʊ/ /ˈhɪrəʊ/",
    "hers": "/hɜːrz/",
    "herself": "/hɜːrˈself/",
    "hide": "/haɪd/",
    "high": "/haɪ/",
    "hill": "/hɪl/",
    "him": "/hɪm/ /ɪm/",
    "himself": "/hɪmˈself/",
    "his": "/hɪz/ /ɪz/",
    "history": "/ˈhɪstri/",
    "hit": "/hɪt/",
    "hobby": "/ˈhɒbi/",
    "hold": "/həʊld/",
    "hole": "/həʊl/",
    "holiday": "/ˈhɒlədeɪ/ /ˈhɒlədi/",
    "home": "/həʊm/",
    "homework": "/ˈhəʊmwɜːrk/",
    "honest": "/ˈɒnɪst/",
    "honor": "/ˈɒnər/",
    "hope": "/həʊp/",
    "horse": "/hɔːrs/",
    "hospital": "/ˈhɒspɪtl/",
    "host": "/həʊst/",
    "hot": "/hɒt/",
    "hotel": "/həʊˈtel/",
    "hour": "/ˈaʊər/",
    "house": "/haʊs/",
    "housework": "/ˈhaʊswɜːrk/",
    "how": "/haʊ/",
    "however": "/haʊˈevər/",
    "huge": "/hjuːdʒ/",
    "human": "/ˈhjuːmən/",
    "humorous": "/ˈhjuːmərəs/",
    "humor": "/ˈhjuːmər/",
    "hundred": "/ˈhʌndrəd/",
    "hungry": "/ˈhʌŋɡri/",
    "hunt": "/hʌnt/",
    "hurry": "/ˈhʌri/",
    "hurt": "/hɜːrt/",
    "husband": "/ˈhʌzbənd/",
    "ice": "/aɪs/",
    "ice-cream": "/ˌaɪsˈkriːm/",
    "idea": "/aɪˈdɪə/",
    "ideal": "/aɪˈdiːəl/",
    "identify": "/aɪˈdentɪfaɪ/",
    "if": "/ɪf/",
    "ill": "/ɪl/",
    "illness": "/ˈɪlnəs/",
    "imagine": "/ɪˈmædʒɪn/",
    "immediately": "/ɪˈmiːdiətli/",
    "import": "/ɪmˈpɔːrt/ /ˈɪmpɔːrt/",
    "important": "/ɪmˈpɔːrtnt/",
    "impossible": "/ɪmˈpɒsəbl/",
    "improve": "/ɪmˈpruːv/",
    "in": "/ɪn/ /ɪ/",
    "inch": "/ɪntʃ/",
    "include": "/ɪnˈkluːd/",
    "increase": "/ɪnˈkriːs/ /ˈɪnkriːs/",
    "indeed": "/ɪnˈdiːd/",
    "india": "/ˈɪndiə/",
    "industry": "/ˈɪndəstri/",
    "information": "/ˌɪnfərˈmeɪʃn/",
    "initial": "/ɪˈnɪʃl/",
    "injure": "/ˈɪndʒər/",
    "injury": "/ɪndʒəri/",
    "ink": "/ɪŋk/",
    "inside": "/ˌɪnˈsaɪd/ /ˈɪnsaɪd/",
    "instead": "/ɪnˈsted/",
    "instruction": "/ɪnˈstrʌkʃn/",
    "instrument": "/ˈɪnstrəmənt/",
    "intend": "/ɪnˈtend/",
    "interest": "/ˈɪntrəst/ /ˈɪntrest/",
    "interesting": "/ˈɪntrəstɪŋ/ /ˈɪntrestɪŋ/",
    "international": "/ˌɪntərˈnæʃnl/",
    "internet": "/ˈɪntərnet/",
    "interview": "/ˈɪntərvjuː/",
    "into": "/ˈɪntuː/ /ˈɪntə/ /ˈɪntu/",
    "introduce": "/ˌɪntrəˈdjuːs/",
    "invent": "/ɪnˈvent/",
    "invention": "/ɪnˈvenʃn/",
    "invite": "/ɪnˈvaɪt/",
    "iron": "/ˈaɪərn/",
    "island": "/ˈaɪlənd/",
    "it": "/ɪt/",
    "its": "/ɪts/",
    "itself": "/ɪtˈself/",
    "jacket": "/ˈdʒækɪt/",
    "jam": "/dʒæm/",
    "january": "/ˈdʒænjuəri/",
    "japan": "/dʒəˈpæn/",
    "japanese": "/ˌdʒæpəˈniːz/",
    "jeans": "/dʒiːnz/",
    "job": "/dʒɒb/",
    "join": "/dʒɔɪn/",
    "joke": "/dʒəʊk/",
    "journal": "/ˈdʒɜːrnl/",
    "journey": "/ˈdʒɜːrni/",
    "joy": "/dʒɔɪ/",
    "juice": "/dʒuːs/",
    "jump": "/dʒʌmp/",
    "june": "/dʒuːn/",
    "july": "/dʊˈlaɪ/ /dʒʊˈlaɪ/",
    "junior": "/ˈdʒuːniər/",
    "just": "/dʒʌst/ /dʒəst/",
    "keep": "/kiːp/",
    "key": "/kiː/",
    "keyboard": "/ˈkiːbɔːrd/",
    "kick": "/kɪk/",
    "kill": "/kɪl/",
    "kilogram": "/ˈkɪləɡræm/",
    "kilometer": "/ˈkɪləmiːtər/ /kɪˈlɒmɪtər/",
    "kind": "/kaɪnd/",
    "king": "/kɪŋ/",
    "kiss": "/kɪs/",
    "kitchen": "/ˈkɪtʃɪn/",
    "kite": "/kaɪt/",
    "knee": "/niː/",
    "knife": "/naɪf/",
    "knock": "/nɒk/",
    "know": "/nəʊ/",
    "knowledge": "/ˈnɒlɪdʒ/",
    "lab": "/læb/",
    "laboratory": "/ləˈbɒrətri/ /ˈlæbrətɔːri/",
    "lack": "/læk/",
    "lady": "/ˈleɪdi/",
    "lake": "/leɪk/",
    "lamp": "/læmp/",
    "land": "/lænd/",
    "language": "/ˈlæŋɡwɪdʒ/",
    "large": "/lɑːrdʒ/",
    "last": "/lɑːst/ /læst/",
    "late": "/leɪt/",
    "later": "/ˈleɪtər/",
    "laugh": "/lɑːf/ /læf/",
    "law": "/lɔː/",
    "lay": "/leɪ/",
    "lazy": "/ˈleɪzi/",
    "lead": "/liːd/ /led/",
    "leader": "/ˈliːdər/",
    "leaf": "/liːf/",
    "learn": "/lɜːrn/",
    "least": "/liːst/",
    "leave": "/liːv/",
    "left": "/left/",
    "leg": "/leɡ/",
    "lend": "/lend/",
    "length": "/leŋθ/ /leŋkθ/",
    "less": "/les/",
    "lesson": "/ˈlesn/",
    "let": "/let/",
    "letter": "/ˈletər/",
    "level": "/ˈlevl/",
    "library": "/ˈlaɪbrəri/ /ˈlaɪbreri/",
    "license": "/ˈlaɪsns/",
    "lie": "/laɪ/ /laɪ/",
    "life": "/laɪf/",
    "lift": "/lɪft/",
    "light": "/laɪt/",
    "lightning": "/ˈlaɪtnɪŋ/",
    "like": "/laɪk/",
    "line": "/laɪn/",
    "lion": "/ˈlaɪən/",
    "lip": "/lɪp/",
    "list": "/lɪst/",
    "listen": "/ˈlɪsn/",
    "literature": "/ˈlɪtrətʃər/ /ˈlɪtərətʃʊr/",
    "little": "/ˈlɪtl/",
    "live": "/lɪv/ /laɪv/",
    "living": "/ˈlɪvɪŋ/",
    "local": "/ˈləʊkl/",
    "lock": "/lɒk/",
    "lonely": "/ˈləʊnli/",
    "long": "/lɒŋ/ /lɔːŋ/",
    "look": "/lʊk/",
    "lose": "/luːz/",
    "lot": "/lɒt/ /lɑːt/",
    "loud": "/laʊd/",
    "loudly": "/ˈlaʊdli/",
    "love": "/lʌv/",
    "lovely": "/ˈlʌvli/",
    "low": "/ləʊ/",
    "luck": "/lʌk/",
    "lucky": "/ˈlʌki/",
    "lunch": "/lʌntʃ/",
    "machine": "/məˈʃiːn/",
    "mad": "/mæd/",
    "madam": "/ˈmædəm/",
    "magazine": "/ˌmæɡəˈziːn/",
    "magic": "/ˈmædʒɪk/",
    "mail": "/meɪl/",
    "main": "/meɪn/",
    "major": "/ˈmeɪdʒər/",
    "make": "/meɪk/",
    "male": "/meɪl/",
    "man": "/mæn/",
    "manage": "/ˈmænɪdʒ/",
    "manager": "/ˈmænɪdʒər/",
    "many": "/ˈmeni/",
    "map": "/mæp/",
    "maple": "/ˈmeɪpl/",
    "march": "/mɑːrtʃ/",
    "mark": "/mɑːrk/",
    "market": "/ˈmɑːrkɪt/",
    "marriage": "/ˈmærɪdʒ/",
    "marry": "/ˈmæri/",
    "match": "/mætʃ/",
    "material": "/məˈtɪəriəl/",
    "math": "/mæθ/",
    "mathematics": "/ˌmæθəˈmætɪks/",
    "maths": "/mæθs/",
    "matter": "/ˈmætər/",
    "may": "/meɪ/",
    "maybe": "/ˈmeɪbi/",
    "meal": "/miːl/",
    "mean": "/miːn/",
    "meaning": "/ˈmiːnɪŋ/",
    "meat": "/miːt/",
    "medical": "/ˈmedɪkl/",
    "medicine": "/ˈmedsn/ /ˈmedɪsn/",
    "meet": "/miːt/",
    "meeting": "/ˈmiːtɪŋ/",
    "member": "/ˈmembər/",
    "memory": "/ˈmeməri/",
    "mend": "/mend/",
    "mention": "/ˈmenʃn/",
    "menu": "/ˈmenjuː/",
    "message": "/ˈmesɪdʒ/",
    "metal": "/ˈmetl/",
    "meter": "/ˈmiːtər/",
    "method": "/ˈmeθəd/",
    "middle": "/ˈmɪdl/",
    "might": "/maɪt/",
    "mile": "/maɪl/",
    "milk": "/mɪlk/",
    "mind": "/maɪnd/",
    "mine": "/maɪn/",
    "mineral": "/ˈmɪnərl/ /ˈmɪnərəl/",
    "minute": "/ˈmɪnɪt/",
    "mirror": "/ˈmɪrər/",
    "miss": "/mɪs/",
    "missile": "/ˈmɪsaɪl/ /ˈmɪsl/",
    "missing": "/ˈmɪsɪŋ/",
    "mistake": "/mɪˈsteɪk/",
    "mix": "/mɪks/",
    "model": "/ˈmɒdl/ /ˈmɑːdl/",
    "modern": "/ˈmɒdn/ /ˈmɑːrdn/",
    "mom": "/mɒm/ /mɑːm/",
    "moment": "/ˈməʊmənt/",
    "monday": "/ˈmʌndeɪ/",
    "money": "/ˈmʌni/",
    "monkey": "/ˈmʌŋki/",
    "month": "/mʌnθ/",
    "moon": "/muːn/",
    "more": "/mɔːr/",
    "morning": "/ˈmɔːrnɪŋ/",
    "most": "/məʊst/",
    "mother": "/ˈmʌðər/",
    "mountain": "/ˈmaʊntən/",
    "mouse": "/maʊs/",
    "mouth": "/maʊθ/",
    "move": "/muːv/",
    "movie": "/ˈmuːvi/",
    "much": "/mʌtʃ/ /mətʃ/",
    "murder": "/ˈmɜːrdər/",
    "museum": "/mjuˈziːəm/",
    "music": "/ˈmjuːzɪk/",
    "must": "/mʌst/ /məst/",
    "my": "/maɪ/",
    "myself": "/maɪˈself/",
    "name": "/neɪm/",
    "narrow": "/ˈnærəʊ/",
    "nation": "/ˈneɪʃn/",
    "national": "/ˈnæʃnl/",
    "native": "/ˈneɪtɪv/",
    "natural": "/ˈnætʃrəl/ /ˈnætʃərəl/",
    "nature": "/ˈneɪtʃər/",
    "near": "/nɪr/",
    "nearly": "/ˈnɪərli/",
    "neat": "/niːt/",
    "necessary": "/ˈnesəseri/ /ˈnesɪsəri/",
    "neck": "/nek/",
    "need": "/niːd/",
    "neighbor": "/ˈneɪbər/",
    "neither": "/ˈnaɪðər/ /ˈniːðər/",
    "nephew": "/ˈnevjuː/ /ˈnefjuː/",
    "nervous": "/ˈnɜːrvəs/",
    "net": "/net/",
    "never": "/ˈnevər/",
    "new": "/nuː/ /njuː/",
    "news": "/nuːz/ /njuːz/",
    "newspaper": "/ˈnuːzpeɪpər/ /ˈnjuːzpeɪpər/",
    "next": "/nekst/",
    "nice": "/naɪs/",
    "niece": "/niːs/",
    "night": "/naɪt/",
    "nine": "/naɪn/",
    "nineteen": "/ˌnaɪnˈtiːn/",
    "ninety": "/ˈnaɪnti/",
    "ninth": "/naɪnθ/",
    "no": "/nəʊ/",
    "nobody": "/ˈnəʊbɒdi/ /ˈnəʊbɑːdi/",
    "nod": "/nɒd/",
    "noise": "/nɔɪz/",
    "none": "/nʌn/",
    "noodle": "/ˈnuːdl/",
    "noon": "/nuːn/",
    "nor": "/nɔːr/",
    "normal": "/ˈnɔːrml/",
    "north": "/nɔːrθ/",
    "northeast": "/ˌnɔːrθˈiːst/",
    "northern": "/ˈnɔːrðərn/",
    "northwest": "/ˌnɔːrθˈwest/",
    "nose": "/nəʊz/",
    "not": "/nɒt/ /nɑːt/",
    "note": "/nəʊt/",
    "notebook": "/ˈnəʊtbʊk/",
    "nothing": "/ˈnʌθɪŋ/",
    "notice": "/ˈnəʊtɪs/ /ˈnoʊtɪs/",
    "november": "/nəʊˈvembər/",
    "now": "/naʊ/",
    "nowhere": "/ˈnəʊwer/",
    "number": "/ˈnʌmbər/",
    "nurse": "/nɜːrs/",
    "object": "/ˈɒbdʒɪkt/ /əbˈdʒekt/",
    "occur": "/əˈkɜːr/",
    "ocean": "/ˈəʊʃn/",
    "october": "/ɒkˈtəʊbər/",
    "of": "/əv/ /ɒv/ /ʌv/",
    "off": "/ɒf/ /ɔːf/",
    "offer": "/ˈɒfər/ /ˈɔːfər/",
    "office": "/ˈɒfɪs/ /ˈɔːfɪs/",
    "officer": "/ˈɒfɪsər/ /ˈɔːfɪsər/",
    "often": "/ˈɒfn/ /ˈɔːfn/",
    "oil": "/ɔɪl/",
    "okay": "/əʊˈkeɪ/ /ˌəʊˈkeɪ/",
    "old": "/əʊld/",
    "olympic": "/əˈlɪmpɪk/",
    "on": "/ɒn/ /ɑːn/ /ən/ /ɒ/",
    "once": "/wʌns/",
    "one": "/wʌn/",
    "oneself": "/wʌnˈself/",
    "only": "/ˈəʊnli/",
    "onto": "/ˈɒntuː/",
    "open": "/ˈəʊpn/",
    "opposite": "/ˈɒpəzɪt/ /ˈɑːpəzɪt/",
    "or": "/ɔːr/ /ər/ /ɚ/",
    "orange": "/ˈɒrɪndʒ/ /ˈɔːrɪndʒ/",
    "order": "/ˈɔːrdər/",
    "ordinary": "/ˈɔːrdneri/ /ˈɔːrdnri/",
    "organize": "/ˈɔːrɡənaɪz/",
    "other": "/ˈʌðər/",
    "ought": "/ɔːt/",
    "our": "/ˈaʊər/ /ɑːr/",
    "ours": "/ˈaʊərz/",
    "ourselves": "/ˌaʊərˈselvz/",
    "out": "/aʊt/",
    "outside": "/ˌaʊtˈsaɪd/ /ˈaʊtsaɪd/",
    "over": "/ˈəʊvər/",
    "own": "/əʊn/",
    "owner": "/ˈəʊnər/",
    "page": "/peɪdʒ/",
    "pain": "/peɪn/",
    "paint": "/peɪnt/",
    "painter": "/ˈpeɪntər/",
    "pair": "/per/ /peər/",
    "palace": "/ˈpæləs/",
    "pale": "/peɪl/",
    "pancake": "/ˈpænkeɪk/",
    "panda": "/ˈpændə/",
    "paper": "/ˈpeɪpər/",
    "paragraph": "/ˈpærəɡrɑːf/ /ˈpærəɡræf/",
    "pardon": "/ˈpɑːrdn/",
    "parent": "/ˈperənt/ /ˈpeərənt/",
    "park": "/pɑːrk/",
    "part": "/pɑːrt/",
    "partner": "/ˈpɑːrtnər/",
    "party": "/ˈpɑːrti/",
    "pass": "/pɑːs/ /pæs/",
    "passage": "/ˈpæsɪdʒ/",
    "passenger": "/ˈpæsɪndʒər/",
    "passerby": "/ˌpɑːsəˈbaɪ/ /ˌpæsəˈbaɪ/",
    "passion": "/ˈpæʃn/",
    "passport": "/ˈpɑːspɔːrt/",
    "past": "/pɑːst/ /pæst/",
    "path": "/pɑːθ/ /pæθ/",
    "pay": "/peɪ/",
    "peace": "/piːs/",
    "pear": "/per/ /peər/",
    "pen": "/pen/",
    "pencil": "/ˈpensl/",
    "penny": "/ˈpeni/",
    "people": "/ˈpiːpl/",
    "percent": "/pərˈsent/",
    "perfect": "/ˈpɜːrfɪkt/ /pərˈfekt/",
    "perform": "/pərˈfɔːrm/ /pəˈfɔːrm/",
    "perhaps": "/pərˈhæps/ /pəˈhæps/",
    "period": "/ˈpɪəriəd/",
    "person": "/ˈpɜːrsn/",
    "personal": "/ˈpɜːrsənl/",
    "pet": "/pet/",
    "phone": "/fəʊn/",
    "photo": "/ˈfəʊtəʊ/",
    "photograph": "/ˈfəʊtəɡrɑːf/ /ˈfəʊtəɡræf/",
    "phrase": "/freɪz/",
    "physics": "/ˈfɪzɪks/",
    "piano": "/piˈænəʊ/",
    "pick": "/pɪk/",
    "picnic": "/ˈpɪknɪk/",
    "picture": "/ˈpɪktʃər/",
    "pie": "/paɪ/",
    "piece": "/piːs/",
    "pig": "/pɪɡ/",
    "pillow": "/ˈpɪləʊ/",
    "pilot": "/ˈpaɪlət/",
    "pin": "/pɪn/",
    "pink": "/pɪŋk/",
    "pioneer": "/ˌpaɪəˈnɪr/",
    "pipe": "/paɪp/",
    "pity": "/ˈpɪti/",
    "place": "/pleɪs/",
    "plain": "/pleɪn/",
    "plan": "/plæn/",
    "plane": "/pleɪn/",
    "planet": "/ˈplænɪt/",
    "plant": "/plɑːnt/ /plænt/",
    "plastic": "/ˈplæstɪk/",
    "plate": "/pleɪt/",
    "play": "/pleɪ/",
    "player": "/ˈpleɪər/",
    "playground": "/ˈpleɪɡraʊnd/",
    "pleasant": "/ˈpleznt/",
    "please": "/pliːz/",
    "pleased": "/pliːzd/",
    "pleasure": "/ˈpleʒər/",
    "plenty": "/ˈplenti/",
    "pocket": "/ˈpɒkɪt/",
    "poem": "/ˈpəʊɪm/ /ˈpoʊəm/",
    "point": "/pɔɪnt/",
    "poison": "/ˈpɔɪzn/",
    "pole": "/pəʊl/",
    "police": "/pəˈliːs/",
    "polite": "/pəˈlaɪt/",
    "pond": "/pɒnd/",
    "pool": "/puːl/",
    "poor": "/pʊr/ /pɔːr/",
    "pop": "/pɒp/",
    "popular": "/ˈpɒpjələr/ /ˈpɑːpjələr/",
    "population": "/ˌpɒpjuˈleɪʃn/",
    "pork": "/pɔːrk/",
    "position": "/pəˈzɪʃn/",
    "possible": "/ˈpɒsəbl/",
    "post": "/pəʊst/",
    "postcard": "/ˈpəʊstkɑːrd/",
    "postman": "/ˈpəʊstmən/",
    "potato": "/pəˈteɪtəʊ/",
    "pound": "/paʊnd/",
    "pour": "/pɔːr/ /pɔː/",
    "power": "/ˈpaʊər/",
    "practical": "/ˈpræktɪkl/",
    "practice": "/ˈpræktɪs/",
    "praise": "/preɪz/",
    "prefer": "/prɪˈfɜːr/",
    "prepare": "/prɪˈper/ /prɪˈpeər/",
    "present": "/ˈpreznt/ /prɪˈzent/",
    "president": "/ˈprezɪdənt/",
    "pretty": "/ˈprɪti/",
    "prevent": "/prɪˈvent/",
    "price": "/praɪs/",
    "pride": "/praɪd/",
    "primary": "/ˈpraɪmeri/ /ˈpraɪməri/",
    "print": "/prɪnt/",
    "prison": "/ˈprɪzn/",
    "private": "/ˈpraɪvɪt/",
    "prize": "/praɪz/",
    "probably": "/ˈprɒbəbli/ /ˈprɑːbəbli/",
    "problem": "/ˈprɒbləm/ /ˈprɑːbləm/",
    "process": "/ˈprəʊses/ /ˈprɑːses/",
    "produce": "/prəˈdjuːs/ /ˈprɑːduːs/",
    "product": "/ˈprɒdʌkt/ /ˈprɑːdʌkt/",
    "program": "/ˈprəʊɡræm/ /ˈproʊɡræm/",
    "progress": "/ˈprəʊɡres/ /ˈprɑːɡres/",
    "promise": "/ˈprɒmɪs/",
    "pronounce": "/prəˈnaʊns/",
    "pronunciation": "/prəˌnʌnsiˈeɪʃn/",
    "proper": "/ˈprɒpər/ /ˈprɑːpər/",
    "protect": "/prəˈtekt/",
    "proud": "/praʊd/",
    "prove": "/pruːv/",
    "provide": "/prəˈvaɪd/",
    "public": "/ˈpʌblɪk/",
    "pull": "/pʊl/",
    "punish": "/ˈpʌnɪʃ/",
    "pupil": "/ˈpjuːpl/",
    "push": "/pʊʃ/",
    "put": "/pʊt/",
    "quality": "/ˈkwɒləti/ /ˈkwɑːləti/",
    "quantity": "/ˈkwɒntəti/ /ˈkwɑːntəti/",
    "quarter": "/ˈkwɔːrtər/",
    "queen": "/kwiːn/",
    "question": "/ˈkwestʃən/",
    "quick": "/kwɪk/",
    "quickly": "/ˈkwɪkli/",
    "quiet": "/ˈkwaɪət/",
    "quite": "/kwaɪt/",
    "quiz": "/kwɪz/",
    "race": "/reɪs/",
    "radio": "/ˈreɪdiəʊ/",
    "rail": "/reɪl/",
    "railway": "/ˈreɪlweɪ/",
    "rain": "/reɪn/",
    "raincoat": "/ˈreɪnkəʊt/",
    "rainy": "/ˈreɪni/",
    "raise": "/reɪz/",
    "rapid": "/ˈræpid/",
    "rather": "/ˈrɑːðər/ /ˈræðər/",
    "reach": "/riːtʃ/",
    "read": "/riːd/ /red/",
    "ready": "/ˈredi/",
    "real": "/riːəl/ /rɪəl/",
    "realize": "/ˈriːəlaɪz/ /ˈrɪəlaɪz/",
    "really": "/ˈriːəli/ /ˈrɪəli/",
    "reason": "/ˈriːzn/",
    "receive": "/rɪˈsiːv/",
    "recent": "/ˈriːsnt/",
    "recently": "/ˈriːsntli/",
    "record": "/ˈrekɔːrd/ /rɪˈkɔːrd/",
    "recover": "/rɪˈkʌvər/",
    "red": "/red/",
    "reduce": "/rɪˈdjuːs/ /rɪˈduːs/",
    "refuse": "/rɪˈfjuːz/ /rɪˈfjuːz/",
    "regard": "/rɪˈɡɑːrd/ /rɪˈɡɑːrd/",
    "regret": "/rɪˈɡret/",
    "regular": "/ˈreɡjələr/ /ˈreɡjlər/",
    "reject": "/rɪˈdʒekt/",
    "relation": "/rɪˈleɪʃn/",
    "relationship": "/rɪˈleɪʃnʃɪp/",
    "relative": "/ˈrelətɪv/",
    "relax": "/rɪˈlæks/",
    "remain": "/rɪˈmeɪn/",
    "remember": "/rɪˈmembər/",
    "remind": "/rɪˈmaɪnd/",
    "remove": "/rɪˈmuːv/",
    "rent": "/rent/",
    "repair": "/rɪˈper/ /rɪˈpeər/",
    "repeat": "/rɪˈpiːt/",
    "replace": "/rɪˈpleɪs/",
    "reply": "/rɪˈplaɪ/",
    "report": "/rɪˈpɔːrt/",
    "request": "/rɪˈkwest/",
    "require": "/rɪˈkwaɪər/",
    "research": "/rɪˈsɜːrtʃ/ /riːˈsɜːrtʃ/",
    "resource": "/ˈriːsɔːrs/ /rɪˈsɔːrs/",
    "respect": "/rɪˈspekt/",
    "respond": "/rɪˈspɒnd/",
    "rest": "/rest/",
    "restaurant": "/ˈrestərɒnt/ /ˈrestərɑːnt/",
    "result": "/rɪˈzʌlt/",
    "return": "/rɪˈtɜːrn/",
    "review": "/rɪˈvjuː/",
    "reward": "/rɪˈwɔːrd/",
    "rice": "/raɪs/",
    "rich": "/rɪtʃ/",
    "ride": "/raɪd/",
    "right": "/raɪt/",
    "ring": "/rɪŋ/",
    "rise": "/raɪz/",
    "risk": "/rɪsk/",
    "river": "/ˈrɪvər/",
    "road": "/rəʊd/",
    "robot": "/ˈrəʊbɒt/ /ˈrəʊbɑːt/",
    "rock": "/rɒk/",
    "role": "/rəʊl/",
    "roll": "/rəʊl/",
    "roof": "/ruːf/",
    "room": "/ruːm/ /rʊm/",
    "root": "/ruːt/",
    "rose": "/rəʊz/",
    "rough": "/rʌf/",
    "round": "/raʊnd/",
    "row": "/rəʊ/ /raʊ/",
    "rub": "/rʌb/",
    "rubber": "/ˈrʌbər/",
    "rubbish": "/ˈrʌbɪʃ/",
    "rude": "/ruːd/",
    "rule": "/ruːl/",
    "ruler": "/ˈruːlər/",
    "run": "/rʌn/",
    "sad": "/sæd/",
    "safe": "/seɪf/",
    "safety": "/ˈseɪfti/",
    "sail": "/seɪl/",
    "salad": "/ˈsæləd/",
    "sale": "/seɪl/",
    "salt": "/sɔːlt/ /sælt/",
    "same": "/seɪm/",
    "sand": "/sænd/",
    "sandwich": "/ˈsænwɪtʃ/ /ˈsænwɪdʒ/",
    "satisfy": "/ˈsætɪsfaɪ/",
    "saturday": "/ˈsætərdeɪ/",
    "save": "/seɪv/",
    "say": "/seɪ/",
    "scared": "/skerd/ /skeəd/",
    "scene": "/siːn/",
    "school": "/skuːl/",
    "science": "/ˈsaɪəns/",
    "score": "/skɔːr/",
    "screen": "/skriːn/",
    "sea": "/siː/",
    "search": "/sɜːrtʃ/",
    "season": "/ˈsiːzn/",
    "seat": "/siːt/",
    "second": "/ˈsekənd/",
    "secret": "/ˈsiːkrət/",
    "secretary": "/ˈsekrəteri/ /ˈsekrətri/",
    "see": "/siː/",
    "seed": "/siːd/",
    "seem": "/siːm/",
    "sell": "/sel/",
    "send": "/send/",
    "sense": "/sens/",
    "sentence": "/ˈsentəns/",
    "separate": "/ˈseprət/ /ˈsepəreɪt/",
    "serious": "/ˈsɪəriəs/ /ˈsɪriəs/",
    "servant": "/ˈsɜːrvənt/ /ˈsɜːrvnt/",
    "serve": "/sɜːrv/ /sɜːv/",
    "service": "/ˈsɜːrvɪs/",
    "set": "/set/",
    "settle": "/ˈsetl/",
    "seven": "/ˈsevn/",
    "several": "/ˈsevrl/",
    "shake": "/ʃeɪk/",
    "shall": "/ʃæl/ /ʃəl/",
    "shame": "/ʃeɪm/",
    "shape": "/ʃeɪp/",
    "share": "/ʃer/ /ʃeər/",
    "shark": "/ʃɑːrk/",
    "sharp": "/ʃɑːrp/",
    "shave": "/ʃeɪv/",
    "she": "/ʃiː/ /ʃi/",
    "sheep": "/ʃiːp/",
    "shine": "/ʃaɪn/",
    "shirt": "/ʃɜːrt/",
    "shoe": "/ʃuː/",
    "shoot": "/ʃuːt/",
    "shop": "/ʃɒp/ /ʃɑːp/",
    "shore": "/ʃɔːr/",
    "short": "/ʃɔːrt/",
    "should": "/ʃʊd/ /ʃəd/",
    "shoulder": "/ˈʃəʊldər/",
    "shout": "/ʃaʊt/",
    "show": "/ʃəʊ/",
    "shower": "/ˈʃaʊər/",
    "shut": "/ʃʌt/",
    "shy": "/ʃaɪ/",
    "sick": "/sɪk/",
    "side": "/saɪd/",
    "sidewalk": "/ˈsaɪdwɔːk/",
    "silence": "/ˈsaɪləns/",
    "silent": "/ˈsaɪlənt/",
    "silk": "/sɪlk/",
    "silly": "/ˈsɪli/",
    "silver": "/ˈsɪlvər/",
    "simple": "/ˈsɪmpl/",
    "since": "/sɪns/",
    "sing": "/sɪŋ/",
    "single": "/ˈsɪŋɡl/",
    "sink": "/sɪŋk/",
    "sir": "/sɜːr/ /sər/",
    "sister": "/ˈsɪstər/",
    "sit": "/sɪt/",
    "situation": "/ˌsitʃuˈeɪʃn/",
    "size": "/saɪz/",
    "skill": "/skɪl/",
    "skin": "/skɪn/",
    "skirt": "/skɜːrt/",
    "sky": "/skaɪ/",
    "sleep": "/sliːp/",
    "slow": "/sləʊ/",
    "small": "/smɔːl/",
    "smart": "/smɑːrt/",
    "smell": "/smel/",
    "smile": "/smaɪl/",
    "smoke": "/sməʊk/",
    "smooth": "/smuːð/",
    "snake": "/sneɪk/",
    "snow": "/snəʊ/",
    "snowball": "/ˈsnəʊbɔːl/",
    "snowman": "/ˈsnəʊmæn/",
    "so": "/səʊ/ /soʊ/",
    "soap": "/səʊp/",
    "soccer": "/ˈsɒkər/ /ˈsɑːkər/",
    "social": "/ˈsəʊʃl/",
    "society": "/səˈsaɪəti/",
    "sock": "/sɒk/",
    "sofa": "/ˈsəʊfə/",
    "soft": "/sɒft/ /sɔːft/",
    "software": "/ˈsɒftwer/ /ˈsɔːftwer/",
    "soil": "/sɔɪl/",
    "soldier": "/ˈsəʊldʒər/",
    "solution": "/səˈluːʃn/",
    "solve": "/sɒlv/",
    "some": "/sʌm/ /səm/",
    "somebody": "/ˈsʌmbɒdi/ /ˈsʌmbɑːdi/",
    "someone": "/ˈsʌmwʌn/",
    "something": "/ˈsʌmθɪŋ/",
    "sometimes": "/ˈsʌmtaɪmz/",
    "somewhere": "/ˈsʌmwer/",
    "son": "/sʌn/",
    "song": "/sɒŋ/ /sɔːŋ/",
    "soon": "/suːn/",
    "sorry": "/ˈsɒri/ /ˈsɑːri/",
    "sort": "/sɔːrt/",
    "sound": "/saʊnd/",
    "soup": "/suːp/",
    "sour": "/ˈsaʊər/",
    "space": "/speɪs/",
    "speak": "/spiːk/",
    "speaker": "/ˈspiːkər/",
    "special": "/ˈspeʃl/",
    "speech": "/spiːtʃ/",
    "speed": "/spiːd/",
    "spell": "/spel/",
    "spelling": "/ˈspelɪŋ/",
    "spend": "/spend/",
    "spirit": "/ˈspɪrɪt/",
    "spoon": "/spuːn/",
    "sport": "/spɔːrt/ /spɔrt/",
    "spread": "/spred/",
    "square": "/skwer/ /skweər/",
    "stable": "/ˈsteɪbl/",
    "stand": "/stænd/",
    "star": "/stɑːr/ /stɑː/",
    "start": "/stɑːrt/",
    "state": "/steɪt/",
    "station": "/ˈsteɪʃn/",
    "stay": "/steɪ/",
    "step": "/step/",
    "stick": "/stɪk/",
    "still": "/stɪl/",
    "stomach": "/ˈstʌmək/",
    "stone": "/stəʊn/",
    "stop": "/stɒp/ /stɑːp/",
    "store": "/stɔːr/",
    "storm": "/stɔːrm/",
    "story": "/ˈstɔːri/",
    "straight": "/streɪt/",
    "strange": "/streɪndʒ/",
    "strength": "/streŋθ/ /streŋkθ/",
    "stress": "/stres/",
    "strict": "/strɪkt/",
    "strong": "/strɒŋ/ /strɔːŋ/",
    "student": "/ˈstuːdnt/ /ˈstjuːdnt/",
    "study": "/ˈstʌdi/",
    "stupid": "/ˈstjuːpɪd/ /ˈstuːpɪd/",
    "style": "/staɪl/",
    "subject": "/ˈsʌbdʒɪkt/",
    "succeed": "/səkˈsiːd/",
    "success": "/səkˈses/",
    "such": "/sʌtʃ/ /sətʃ/",
    "suddenly": "/ˈsʌdnli/",
    "sugar": "/ˈʃʊɡər/",
    "suggest": "/səˈdʒest/ /səˈdʒest/",
    "suggestion": "/səˈdʒestʃn/ /səˈdʒestʃn/",
    "suit": "/suːt/ /sjuːt/",
    "summer": "/ˈsʌmər/",
    "sun": "/sʌn/",
    "sunday": "/ˈsʌndeɪ/",
    "sunny": "/ˈsʌni/",
    "super": "/ˈsuːpər/",
    "supper": "/ˈsʌpər/",
    "support": "/səˈpɔːrt/",
    "suppose": "/səˈpəʊz/",
    "sure": "/ʃʊr/ /ʃɔːr/",
    "surprise": "/sərˈpraɪz/ /səˈpraɪz/",
    "surround": "/səˈraʊnd/",
    "survive": "/sərˈvaɪv/",
    "suspect": "/səˈspekt/ /ˈsʌspekt/",
    "sweet": "/swiːt/",
    "swim": "/swɪm/",
    "swing": "/swɪŋ/",
    "symbol": "/ˈsɪmbl/",
    "system": "/ˈsɪstəm/",
    "table": "/ˈteɪbl/",
    "tail": "/teɪl/",
    "take": "/teɪk/",
    "talent": "/ˈtælənt/",
    "talk": "/tɔːk/",
    "tall": "/tɔːl/",
    "tank": "/tæŋk/",
    "tape": "/teɪp/",
    "task": "/tɑːsk/ /tæsk/",
    "taxi": "/ˈtæksi/",
    "tea": "/tiː/",
    "teach": "/tiːtʃ/",
    "teacher": "/ˈtiːtʃər/",
    "team": "/tiːm/",
    "technology": "/tekˈnɒlədʒi/ /tekˈnɑːlədʒi/",
    "telephone": "/ˈtelɪfəʊn/",
    "tell": "/tel/",
    "temperature": "/ˈtemprətʃər/ /ˈtemprətʃʊr/",
    "ten": "/ten/",
    "text": "/tekst/",
    "than": "/ðæn/ /ðən/ /ðn/",
    "thank": "/θæŋk/",
    "that": "/ðæt/ /ðət/",
    "the": "/ðə/ /ðiː/ /ði/ /θə/ /θiː/ /θi/",
    "theater": "/ˈθiːətər/ /ˈθiətər/ /ˈθiːətə/ /ˈθɪətər/",
    "them": "/ðem/ /ðəm/ /əm/",
    "their": "/ðer/ /ðeər/",
    "theirs": "/ðerz/",
    "themselves": "/ðəmˈselvz/",
    "then": "/ðen/",
    "there": "/ðer/ /ðeər/",
    "these": "/ðiːz/",
    "they": "/ðei/ /ðeɪ/",
    "thick": "/θɪk/",
    "thin": "/θɪn/",
    "thing": "/θɪŋ/",
    "think": "/θɪŋk/",
    "third": "/θɜːrd/",
    "thirsty": "/ˈθɜːrsti/",
    "thirteen": "/ˌθɜːrˈtiːn/",
    "thirty": "/ˈθɜːrti/",
    "this": "/ðɪs/ /ðəs/",
    "those": "/ðəʊz/",
    "though": "/ðəʊ/ /ðəʊ/",
    "thought": "/θɔːt/",
    "thousand": "/ˈθaʊznd/",
    "three": "/θriː/",
    "through": "/θruː/ /θruː/",
    "throughout": "/θruːˈaʊt/",
    "throw": "/θrəʊ/",
    "thursday": "/ˈθɜːrzdeɪ/",
    "ticket": "/ˈtɪkɪt/",
    "tidy": "/ˈtaɪdi/",
    "tie": "/taɪ/",
    "tiger": "/ˈtaɪɡər/",
    "till": "/tɪl/",
    "time": "/taɪm/",
    "tiny": "/ˈtaɪni/",
    "tip": "/tɪp/",
    "tired": "/ˈtaɪərd/",
    "title": "/ˈtaɪtl/",
    "to": "/tuː/ /tə/ /tu/ /tᵿ/",
    "today": "/təˈdeɪ/",
    "together": "/təˈɡeðər/",
    "toilet": "/ˈtɔɪlɪt/",
    "tomato": "/təˈmeɪtəʊ/ /təˈmɑːtəʊ/",
    "tomorrow": "/təˈmɒrəʊ/ /təˈmɑːrəʊ/",
    "ton": "/tʌn/",
    "tonight": "/təˈnaɪt/",
    "too": "/tuː/",
    "tool": "/tuːl/",
    "tooth": "/tuːθ/",
    "top": "/tɒp/ /tɑːp/",
    "topic": "/ˈtɒpɪk/ /ˈtɑːpɪk/",
    "total": "/ˈtəʊtl/",
    "touch": "/tʌtʃ/",
    "tour": "/tʊr/ /tʊər/",
    "tourist": "tʊərɪst/ /ˈtʊrɪst/",
    "toward": "/təˈwɔːrd/ /təˈwɔːd/",
    "tower": "/ˈtaʊər/",
    "town": "/taʊn/",
    "toy": "/tɔɪ/",
    "tradition": "/trəˈdɪʃn/",
    "traditional": "/trəˈdɪʃənl/",
    "traffic": "/ˈtræfɪk/",
    "train": "/treɪn/",
    "translate": "/trænzˈleɪt/ /trænsˈleɪt/",
    "transport": "/ˈtrænspɔːrt/",
    "travel": "/ˈtrævl/",
    "tree": "/triː/",
    "trip": "/trɪp/",
    "trouble": "/ˈtrʌbl/",
    "truck": "/trʌk/",
    "true": "/truː/",
    "trust": "/trʌst/",
    "truth": "/truːθ/",
    "try": "/traɪ/",
    "tuesday": "/ˈtuːzdeɪ/ /ˈtjuːzdeɪ/",
    "turn": "/tɜːrn/",
    "tv": "/ˌtiːˈviː/",
    "twelfth": "/twelfθ/",
    "twelve": "/twelv/",
    "twenty": "/ˈtwenti/",
    "twice": "/twaɪs/",
    "two": "/tuː/",
    "type": "/taɪp/",
    "uncle": "/ˈʌŋkl/",
    "under": "/ˈʌndər/",
    "underground": "/ˌʌndərˈɡraʊnd/",
    "understand": "/ˌʌndərˈstænd/",
    "unit": "/ˈjuːnɪt/",
    "universe": "/ˈjuːnɪvɜːrs/",
    "university": "/ˌjuːnɪˈvɜːrsəti/",
    "unless": "/ənˈles/",
    "until": "/ənˈtɪl/ /ʌnˈtɪl/",
    "unusual": "/ʌnˈjuːʒuəl/",
    "up": "/ʌp/ /əp/",
    "upstairs": "/ˌʌpˈsterz/",
    "use": "/juːz/ /juːs/",
    "used": "/juːzd/ /juːst/",
    "useful": "/ˈjuːsfl/",
    "user": "/ˈjuːzər/",
    "usual": "/ˈjuːʒuəl/ /ˈjuːʒwl/",
    "usually": "/ˈjuːʒuəli/ /ˈjuːʒwəli/",
    "vacation": "/veɪˈkeɪʃn/ /vəˈkeɪʃn/",
    "value": "/ˈvæljuː/",
    "various": "/ˈveəriəs/ /ˈveriəs/",
    "vegetable": "/ˈvedʒtəbl/",
    "very": "/ˈveri/",
    "victory": "/ˈvɪktəri/",
    "video": "/ˈvɪdiəʊ/",
    "view": "/vjuː/",
    "village": "/ˈvɪlɪdʒ/",
    "visit": "/ˈvɪzɪt/",
    "visitor": "/ˈvɪzɪtər/",
    "volleyball": "/ˈvɒlibɔːl/",
    "voice": "/vɔɪs/",
    "volunteer": "/ˌvɒlənˈtɪər/",
    "vote": "/vəʊt/",
    "wait": "/weɪt/",
    "waiter": "/ˈweɪtər/",
    "waitress": "/ˈweɪtrəs/",
    "wake": "/weɪk/",
    "walk": "/wɔːk/",
    "wall": "/wɔːl/",
    "want": "/wɒnt/ /wɑːnt/",
    "war": "/wɔːr/",
    "warm": "/wɔːrm/",
    "warn": "/wɔːrn/",
    "wash": "/wɒʃ/ /wɔːʃ/",
    "waste": "/weɪst/",
    "watch": "/wɒtʃ/ /wɑːtʃ/",
    "water": "/ˈwɔːtər/ /ˈwɑːtər/",
    "wave": "/weɪv/",
    "way": "/weɪ/",
    "weak": "/wiːk/",
    "wealth": "/welθ/",
    "weather": "/ˈweðər/ /ˈweðər/",
    "web": "/web/",
    "website": "/ˈwebsaɪt/",
    "wednesday": "/ˈwenzdeɪ/ /ˈwenzdeɪ/",
    "week": "/wiːk/",
    "weekday": "/ˈwiːkdeɪ/",
    "weekend": "/ˌwiːkˈend/ /ˈwiːkend/",
    "weigh": "/weɪ/",
    "weight": "/weɪt/",
    "welcome": "/ˈwelkəm/",
    "well": "/wel/",
    "west": "/west/",
    "western": "/ˈwestərn/",
    "wet": "wet/",
    "whale": "/weɪl/",
    "what": "/wɒt/ /wɑːt/ /wʌt/ /wət/ /wɚt/",
    "whatever": "/wɒtˈevər/ /wɑːtˈevər/",
    "wheat": "/wiːt/",
    "wheel": "/wiːl/ /hwiːl/",
    "when": "/wen/",
    "whenever": "wenˈevər/",
    "where": "/wer/ /weər/",
    "whether": "/ˈweðər/",
    "which": "/wɪtʃ/ /wtʃ/",
    "while": "/waɪl/ /hwaɪl/",
    "white": "/waɪt/",
    "who": "/huː/ /hu/ /hʊ/",
    "whole": "/həʊl/",
    "whom": "/huːm/ /hum/",
    "whose": "/huːz/",
    "why": "/waɪ/",
    "wide": "/waɪd/",
    "wife": "/waɪf/",
    "wild": "/waɪld/",
    "will": "/wɪl/ /əl/ /l/",
    "win": "/wɪn/",
    "wind": "/wɪnd/ /waɪnd/",
    "window": "/ˈwɪndəʊ/",
    "windy": "/ˈwɪndi/",
    "wine": "/waɪn/",
    "wing": "/wɪŋ/",
    "winter": "/ˈwɪntər/",
    "wise": "/waɪz/",
    "wish": "/wɪʃ/",
    "with": "/wɪð/ /wɪθ/ /wəð/ /əð/ /əθ/",
    "within": "/wɪˈðɪn/ /wɪˈθɪn/",
    "without": "/wɪˈðaʊt/ /wɪˈθaʊt/",
    "wolf": "/wʊlf/",
    "woman": "/ˈwʊmən/",
    "women": "/ˈwɪmɪn/",
    "wonder": "/ˈwʌndər/",
    "wonderful": "/ˈwʌndərfl/",
    "wood": "/wʊd/",
    "wool": "/wʊl/",
    "word": "/wɜːrd/",
    "work": "/wɜːrk/",
    "worker": "/ˈwɜːrkər/",
    "world": "/wɜːrld/",
    "worried": "/ˈwʌrid/ /ˈwʌrid/",
    "worry": "/ˈwʌri/ /ˈwʌri/",
    "worse": "/wɜːrs/",
    "worst": "/wɜːrst/",
    "worth": "/wɜːrθ/",
    "would": "/wʊd/ /wəd/ /əd/ /d/",
    "wound": "/wuːnd/ /waʊnd/",
    "wrap": "/ræp/",
    "write": "/raɪt/",
    "wrong": "/rɒŋ/ /rɔːŋ/",
    "yard": "/jɑːrd/",
    "yeah": "/jeə/ /jæ/",
    "year": "/jɪr/ /jɜːr/",
    "yellow": "/ˈjeləʊ/",
    "yes": "/jes/",
    "yet": "/jet/",
    "yesterday": "/ˈjestərdeɪ/ /ˈjestərdeɪ/",
    "you": "/juː/ /jʊ/ /jə/",
    "young": "/jʌŋ/",
    "your": "/jɔːr/ /jʊr/ /jər/",
    "yours": "/jɔːrz/ /jʊrz/ /jərz/",
    "yourself": "/jɔːrˈself/ /jʊrˈself/ /jərˈself/",
    "yourselves": "/jɔːrˈselvz/ /jʊrˈselvz/",
    "zero": "/ˈzɪərəʊ/ /ˈzɪroʊ/",
    "zip": "/zɪp/",
    "zoo": "/zuː/",
    "zone": "/zəʊn/",
    
    # === Phrases commonly used in G8 textbooks ===
    "be able to": "/biː ˈeɪbl tuː/",
    "be up to": "/biː ʌp tuː/",
    "be used to": "/biː juːzd tuː/",
    "bring back to life": "/brɪŋ bæk tuː laɪf/",
    "by the time": "/baɪ ðə taɪm/",
    "by the way": "/baɪ ðə weɪ/",
    "call in": "/kɔːl ɪn/",
    "come up with": "/kʌm ʌp wɪð/",
    "cut down": "/kʌt daʊn/",
    "deal with": "/diːl wɪð/",
    "depend on": "/dɪˈpend ɒn/",
    "die down": "/daɪ daʊn/",
    "dress up": "/dres ʌp/",
    "due to": "/djuː tuː/",
    "end up": "/end ʌp/",
    "fall asleep": "/fɔːl əˈsliːp/",
    "fill with": "/fɪl wɪð/",
    "find out": "/faɪnd aʊt/",
    "full of": "/fʌl əv/",
    "get a ride to": "/ɡet eɪ raɪd tuː/",
    "give away": "/ɡɪv əˈweɪ/",
    "give...a lift": "/ɡɪv...ə lɪft/",
    "give out": "/ɡɪv aʊt/",
    "go off": "/ɡəʊ ɒf/",
    "hand out": "/hænd aʊt/",
    "have been to": "/hæv biːn tuː/",
    "have meaning to": "/hæv ˈmiːnɪŋ tuː/",
    "hear from": "/hɪr frɒm/",
    "hundreds of": "/ˈhʌndrədz əv/",
    "hurry up": "/ˈhʌri ʌp/",
    "in fact": "/ɪn fækt/",
    "in history": "/ɪn ˈhɪstri/",
    "in order to": "/ɪn ˈɔːrdər tuː/",
    "in the end": "/ɪn ðə end/",
    "in times of": "/ɪn taɪmz əv/",
    "instead of": "/ɪnˈsted əv/",
    "keep...to oneself": "/kiːp...tə wʌnˈself/",
    "look after": "/lʊk ˈɑːftər/",
    "look forward to": "/lʊk ˈfɔːrwərd tuː/",
    "look forward": "/lʊk ˈfɔːrwərd/",
    "lose weight": "/luːz weɪt/",
    "make it": "/meɪk ɪt/",
    "make one's way": "/meɪk wʌnz weɪ/",
    "make sure": "/meɪk ʃʊr/ /meɪk ʃʊər/",
    "make up one's mind": "/meɪk ʌp wʌnz maɪnd/",
    "no more": "/nəʊ mɔːr/",
    "of course": "/əv kɔːrs/ /əv kɔːrs/",
    "on the one hand": "/ɒn ðə wʌn hænd/",
    "on the other hand": "/ɒn ðə ʌðə hænd/",
    "pick up": "/pɪk ʌp/",
    "play a joke on": "/pleɪ eɪ dʒəʊk ɒn/",
    "play a trick on": "/pleɪ eɪ trɪk ɒn/",
    "plenty of": "/ˈplenti əv/",
    "put off": "/pʊt ɒf/ /pʊt ɔːf/",
    "put on": "/pʊt ɒn/ /pʊt ɔːn/",
    "put up": "/pʊt ʌp/",
    "run away": "/rʌn əˈweɪ/",
    "sell out": "/sel aʊt/",
    "set up": "/set ʌp/",
    "show up": "/ʃəʊ ʌp/",
    "take a trip": "/teɪk eɪ trɪp/",
    "take after": "/teɪk ˈɑːftər/",
    "take care of": "/teɪk keər əv/",
    "take off": "/teɪk ɒf/ /teɪk ɔːf/",
    "take part in": "/teɪk pɑːrt ɪn/",
    "take place": "/teɪk pleɪs/",
    "take sb's place": "/teɪk sʌbz pleɪs/",
    "take the place of": "/teɪk ðə pleɪs əv/",
    "tell the truth": "/tel ðə truːθ/",
    "the day before yesterday": "/ðə deɪ bɪˈfɔːr ˈjestərdeɪ/",
    "the marks of another man's feet": "/ðə mɑːrks əv əˈnʌðər mænz fiːt/",
    "the number of": "/ðə ˈnʌmbər əv/",
    "the opening of": "/ðə ˈəʊpənɪŋ əv/",
    "think of": "/θɪŋk əv/",
    "thousands of": "/ˈθaʊzndz əv/",
    "three quarters of": "/θriː ˈkwɔːrtərz əv/",
    "try one's best": "/traɪ wʌnz best/",
    "turn down": "/tɜːrn daʊn/",
    "turn off": "/tɜːrn ɒf/ /tɜːrn ɔːf/",
    "turn on": "/tɜːrn ɒn/ /tɜːrn ɔːn/",
    "used to": "/juːzd tuː/",
    "wait for": "/weɪt fɔːr/ /weɪt fɔːr/",
    "wait for": "/weɪt fɔːr/ /weɪt fɔːr/",
    "whether or not": "/ˈweðər ɔːr nɒt/ /'weðər ər nɑt/",
    "with pleasure": "/wɪð ˈpleʒər/",
    "work out": "/wɜːrk aʊt/",
    "write down": "/raɪt daʊn/",
}

def fix_phonetics(input_file, output_file):
    """Fix phonetics in dictation JSON file"""
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    fixed = 0
    missing = []
    
    for entry in data:
        word = entry['word'].split('/')[0].strip().lower()
        
        if word in PHONETIC_DICT:
            entry['phonetic'] = PHONETIC_DICT[word]
            fixed += 1
        else:
            missing.append(word)
            # Generate reasonable fallback: /word/
            entry['phonetic'] = f"/{word}/"
    
    # Write output
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    total = len(data)
    print(f"Total entries: {total}")
    print(f"Fixed with real IPA: {fixed} ({fixed/total*100:.1f}%)")
    print(f"Still using fallback: {len(missing)} ({len(missing)/total*100:.1f}%)")
    if missing:
        print(f"\nMissing words ({len(missing)}):")
        print(', '.join(sorted(missing)[:50]))
        if len(missing) > 50:
            print(f"... and {len(missing)-50} more")

if __name__ == '__main__':
    fix_phonetics('src/data/dictation_en_g8.json', 'src/data/dictation_en_g8.json')
