#!/usr/bin/env python3
"""
初中英语词库扩充脚本 - Part 1
将初二词库从800词扩充到约1500词（新增约1200词）
使用新的15个语法分类体系
"""

import json
import os
import sys

# ============== 路径配置 ==============
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
J2_FILE = os.path.join(PROJECT_ROOT, "src/data/words_network_j2.json")

# ============== 读取现有词库 ==============
with open(J2_FILE, "r", encoding="utf-8") as f:
    existing_data = json.load(f)

existing_words = set(existing_data["words"].keys())
print(f"现有初二词库: {len(existing_words)} 词")

# ============== 旧分类到新分类的映射 ==============
CATEGORY_MAP = {
    # 名词细分的映射
    "address": "noun_place", "accident": "noun_common", "adult": "noun_common",
    "advantage": "noun_abstract", "airplane": "noun_common", "apartment": "noun_place",
    "application": "noun_common", "argument": "noun_abstract", "balance": "noun_abstract",
    "bargain": "noun_common", "behavior": "noun_abstract", "capable": "adjective_opinion",
    "effect": "noun_abstract", "affect": "verb_action", "effort": "noun_abstract",
    "achieve": "verb_action", "addition": "noun_abstract", "agreement": "noun_abstract",
    "damage": "verb_action", "discovery": "noun_abstract", "feature": "noun_common",
    "general": "adjective_opinion", "habit": "noun_abstract", "health": "noun_abstract",
    "height": "noun_common", "humor": "noun_abstract", "introduction": "noun_common",
    "invention": "noun_academic", "lifestyle": "noun_common", "meaning": "noun_abstract",
    "mistake": "noun_common", "native": "adjective_opinion", "notebook": "noun_common",
    "organized": "adjective_opinion", "passenger": "noun_common", "positive": "adjective_opinion",
    "praise": "verb_action", "pressure": "noun_abstract", "process": "noun_common",
    "product": "noun_common", "program": "noun_common", "project": "noun_common",
    "publish": "verb_action", "punish": "verb_action", "quarter": "noun_common",
    "request": "verb_action", "responsibility": "noun_abstract", "reward": "noun_common",
    "safety": "noun_abstract", "service": "noun_common", "silence": "noun_abstract",
    "smoke": "noun_common", "stomach": "noun_common", "system": "noun_academic",
    "topic": "noun_common", "value": "noun_abstract", "view": "noun_common",
    "wealth": "noun_abstract", "weight": "noun_common", "wood": "noun_common",
    "education": "noun_academic",
}

def map_old_category(word, old_cat):
    """将旧分类映射到新分类"""
    if word in CATEGORY_MAP:
        return CATEGORY_MAP[word]
    if old_cat == "noun":
        return "noun_common"
    elif old_cat == "verb":
        return "verb_action"
    elif old_cat == "adjective":
        return "adjective_describe"
    elif old_cat == "adverb":
        return "adverb"
    elif old_cat == "expression":
        return "expression_phrase"
    elif old_cat == "preposition":
        return "preposition"
    elif old_cat == "conjunction":
        return "conjunction"
    elif old_cat == "pronoun":
        return "pronoun_personal"
    return old_cat


def make_entry(word, meaning, category, tier, freq, associations, confusables, example, tip):
    """创建标准词条字典"""
    return {
        "word": word,
        "meaning": meaning,
        "category": category,
        "tier": tier,
        "frequency": freq,
        "associations": associations,
        "confusables": confusables,
        "example": example,
        "memory_tip": tip
    }


# ============== 新增词汇数据 ==============
NEW_WORDS = []

# ============================================================
# P1: 七年级核心词汇 — 学校与学习 (~80词)
# ============================================================
P1_SCHOOL = [
    make_entry("achievement", "成就；成绩", "noun_common", 1, "high",
        ["success", "goal", "progress"], ["agreement"],
        "Getting good grades is a great achievement.", "achieve(动词)+ment→成就"),
    make_entry("album", "专辑；相册", "noun_common", 1, "medium",
        ["photo", "picture", "collection"], ["albumen"],
        "My mother keeps our family photos in an album.", "al+bum→相册像一本书"),
    make_entry("article", "文章；物品", "noun_common", 1, "high",
        ["essay", "report", "passage"], ["particle"],
        "I read an interesting article in the newspaper.", "arti(艺术)+cle→文章也是艺术"),
    make_entry("blackboard", "黑板", "noun_common", 1, "high",
        ["chalk", "classroom", "teacher"], ["blackberry"],
        "The teacher wrote the answer on the blackboard.", "黑色+board=黑板"),
    make_entry("calendar", "日历；日程表", "noun_common", 1, "medium",
        ["date", "schedule", "month"], ["calculator"],
        "Please check the calendar for the exam date.", "calend(日历)+ar"),
    make_entry("campus", "校园", "noun_place", 1, "medium",
        ["school", "university", "ground"], [],
        "Our campus is very beautiful in spring.", "camp(营地)+us→学校营地"),
    make_entry("certificate", "证书；证明", "noun_common", 1, "medium",
        ["award", "degree", "license"], ["certify"],
        "She got a certificate for English proficiency.", "cert(确定)+ificate→证明文件"),
    make_entry("chalk", "粉笔", "noun_common", 1, "medium",
        ["blackboard", "write", "teacher"], ["talk", "walk"],
        "The teacher uses chalk to write on the board.", "粉笔走起路来咔咔响"),
    make_entry("chapter", "章；回", "noun_common", 1, "high",
        ["part", "section", "story"], ["charter"],
        "We are studying Chapter Five today.", "chap(头)+ter→章节开头"),
    make_entry("classmate", "同学", "noun_common", 1, "high",
        ["student", "friend", "partner"], ["classroom"],
        "Tom is my classmate. We sit next to each other.", "class+mate→班级伙伴"),
    make_entry("composition", "作文；作曲", "noun_common", 1, "high",
        ["essay", "writing", "article"], [],
        "Our homework is to write a composition about my hobby.", "com(一起)+pos(放)+ition→组合文字"),
    make_entry("correction", "改正；纠正", "noun_common", 1, "medium",
        ["mistake", "fix", "improvement"], ["direction"],
        "The teacher made some corrections on my paper.", "correct(纠正)+ion"),
    make_entry("course", "课程；过程", "noun_common", 1, "high",
        ["class", "subject", "lesson"], ["cause"],
        "Which course do you like best?", "cours(跑)+e→课程一路跑下来"),
    make_entry("desk", "书桌", "noun_common", 1, "high",
        ["table", "chair", "study"], ["disk", "dish"],
        "There are many books on my desk.", "desk=书桌"),
    make_entry("dictionary", "词典；字典", "noun_common", 1, "high",
        ["word", "meaning", "book"], ["dictionery"],
        "I use a dictionary to look up new words.", "dict(说)+ion+ary→说话的工具"),
    make_entry("discussion", "讨论", "noun_common", 1, "high",
        ["talk", "debate", "conversation"], [],
        "We had a discussion about the project.", "discuss(讨论)+ion"),
    make_entry("exam", "考试；测验", "noun_common", 1, "high",
        ["test", "quiz", "check"], ["example"],
        "I have a math exam tomorrow.", "examination的缩写"),
    make_entry("exercise", "练习；锻炼", "noun_common", 1, "high",
        ["practice", "training", "sport"], ["excise"],
        "We do morning exercises every day.", "exerc(练习)+ise"),
    make_entry("explanation", "解释；说明", "noun_common", 1, "high",
        ["reason", "answer", "description"], ["explaination"],
        "Thank you for your explanation.", "explain(解释)+ation"),
    make_entry("grammar", "语法", "noun_academic", 1, "high",
        ["rule", "language", "structure"], ["drama"],
        "Grammar is important for learning English well.", "gramm(写)+ar→写作规则"),
    make_entry("graduation", "毕业", "noun_common", 1, "medium",
        ["finish", "ceremony", "degree"], ["gradient"],
        "My sister's graduation is next month.", "graduate(毕业)+ion"),
    make_entry("homework", "家庭作业", "noun_common", 1, "high",
        ["assignment", "work", "task"], ["housework"],
        "I finish my homework before dinner.", "home+work=家里的作业"),
    make_entry("knowledge", "知识；学问", "noun_academic", 1, "high",
        ["learning", "wisdom", "understanding"], ["know"],
        "Reading books can increase our knowledge.", "know(知道)+ledge→知识的积累"),
    make_entry("lecture", "演讲；讲座", "noun_common", 1, "medium",
        ["speech", "talk", "class"], ["literature"],
        "Professor Wang gave us a lecture on history.", "lect(读)+ure→朗读讲解"),
    make_entry("lesson", "课；教训", "noun_common", 1, "high",
        ["class", "course", "subject"], ["lessen"],
        "We have four lessons every morning.", "less(少)+on→一课一课学"),
    make_entry("library", "图书馆", "noun_place", 1, "high",
        ["book", "read", "quiet"], ["liberty"],
        "I often go to the library to read books.", "libr(书)+ary→存书的地方"),
    make_entry("mark", "分数；标记；符号", "noun_common", 1, "high",
        ["score", "grade", "sign"], ["park", "dark"],
        "I got full marks in the English test.", "mark=标记/分数"),
    make_entry("page", "页；页面", "noun_common", 1, "high",
        ["paper", "sheet", "book"], ["pack", "pace"],
        "Please turn to page twenty-five.", "page=页码"),
    make_entry("pen", "钢笔；笔", "noun_common", 1, "high",
        ["pencil", "write", "ink"], ["pin"],
        "May I borrow your pen?", "pen=笔"),
    make_entry("pencil", "铅笔", "noun_common", 1, "high",
        ["pen", "draw", "write"], [],
        "I write with a pencil so I can erase mistakes.", "pencil=铅笔"),
    make_entry("point", "要点；分数；点", "noun_common", 1, "high",
        ["score", "idea", "mark"], ["paint"],
        "That's a good point. Let me think about it.", "point=要点/得分点"),
    make_entry("project", "项目；课题", "noun_common", 1, "high",
        ["task", "work", "plan"], ["protect"],
        "We are working on a science project this term.", "proj(向前)+ect→投出去的计划"),
    make_entry("pronunciation", "发音", "noun_common", 1, "high",
        ["accent", "sound", "speak"], ["pronounce"],
        "Your pronunciation is getting better.", "pronounce(发音)+ation"),
    make_entry("question", "问题；疑问", "noun_common", 1, "high",
        ["problem", "ask", "answer"], ["quest"],
        "Do you have any questions?", "question(追问)+ion"),
    make_entry("quiz", "小测验", "noun_common", 1, "medium",
        ["test", "exam", "check"], ["quit", "quite"],
        "We have a quiz at the end of each week.", "quiz=小测试"),
    make_entry("reading", "阅读；读书", "noun_common", 1, "high",
        ["book", "understand", "study"], ["ready"],
        "Reading is a good habit.", "read(读)+ing"),
    make_entry("recite", "背诵；朗诵", "verb_action", 1, "medium",
        ["memorize", "learn", "repeat"], ["resite"],
        "We need to recite the poem by Friday.", "re(再)+cite(引用)→再次念出"),
    make_entry("review", "复习；回顾", "verb_action", 1, "high",
        ["study again", "check", "go over"], ["revive"],
        "You should review your lessons before the exam.", "re(再)+view(看)→再看一遍"),
    make_entry("rubber", "橡皮；橡胶", "noun_common", 1, "medium",
        ["eraser", "pencil", "erase"], ["rubbish", "robot"],
        "Can I use your rubber? I made a mistake.", "rub(擦)+ber→擦除工具"),
    make_entry("ruler", "尺子；统治者", "noun_common", 1, "high",
        ["measure", "inch", "centimeter"], ["rule"],
        "I draw straight lines with a ruler.", "rule(统治)+er→测量工具"),
    make_entry("score", "分数；得分", "noun_common", 1, "high",
        ["mark", "point", "goal"], ["scar"],
        "What was your score in the test?", "score=得分"),
    make_entry("semester", "学期", "noun_common", 1, "medium",
        ["term", "session", "year"], ["seminar"],
        "This semester ends in January.", "semi(半)+ester→半年为一个学期"),
    make_entry("sentence", "句子；判决", "noun_common", 1, "high",
        ["words", "grammar", "write"], ["sense"],
        "Please make a sentence with this word.", "sent(感觉)+ence→表达完整意思"),
    make_entry("skill", "技能；技巧", "noun_common", 1, "high",
        ["ability", "talent", "practice"], ["kill"],
        "Communication skills are important.", "skill=技能"),
    make_entry("spell", "拼写", "verb_action", 1, "high",
        ["write", "letters", "word"], ["spill"],
        "How do you spell your name?", "spell=拼写字母"),
    make_entry("spelling", "拼写；拼法", "noun_common", 1, "medium",
        ["letters", "word", "write"], [],
        "Pay attention to your spelling.", "spell(拼写)+ing"),
    make_entry("student", "学生", "noun_common", 1, "high",
        ["pupil", "learner", "study"], ["studio", "stadium"],
        "Every student should respect teachers.", "stud(学习)+ent→学习者"),
    make_entry("subject", "学科；科目；主题", "noun_academic", 1, "high",
        ["course", "topic", "lesson"], ["subtract"],
        "Math is my favorite subject.", "sub(下面)+ject(扔)→下面的主题"),
    make_entry("teacher", "教师", "noun_common", 1, "high",
        ["professor", "educator", "teach"], ["beach"],
        "Our teacher is very kind and patient.", "teach(教)+er→教的人"),
    make_entry("term", "学期；术语", "noun_common", 1, "high",
        ["semester", "word", "time"], ["team"],
        "This term we have eight subjects.", "term=学期/术语"),
    make_entry("text", "文本；课文", "noun_common", 1, "high",
        ["book", "passage", "reading"], ["next"],
        "Read the text and answer the questions.", "text=课文文本"),
    make_entry("textbook", "教科书；课本", "noun_common", 1, "high",
        ["book", "course", "lesson"], [],
        "Don't forget to bring your textbook.", "text(课本)+book"),
    make_entry("title", "标题；题目", "noun_common", 1, "medium",
        ["name", "heading", "subject"], ["little"],
        "What is the title of this book?", "title=标题"),
    make_entry("translation", "翻译；译文", "noun_common", 1, "medium",
        ["interpret", "language", "meaning"], ["relation"],
        "The translation of this poem is beautiful.", "trans(转移)+lation→转换语言"),
    make_entry("tutor", "家庭教师；导师", "noun_common", 1, "medium",
        ["teacher", "help", "guide"], [],
        "My parents hired a tutor for my math.", "tut(保护)+or→指导者"),
    make_entry("uniform", "校服；制服", "noun_common", 1, "medium",
        ["clothes", "wear", "school"], [],
        "All students must wear uniforms at school.", "uni(一个)+form(形式)→统一服装"),
    make_entry("vocabulary", "词汇；词汇量", "noun_academic", 1, "high",
        ["words", "language", "learning"], [],
        "Reading helps build your vocabulary.", "vocabul(词)+ary→词汇集合"),
    make_entry("website", "网站", "noun_common", 1, "medium",
        ["internet", "web", "page"], [],
        "You can find the information on our website.", "web(网)+site(地点)"),
]

NEW_WORDS.extend(P1_SCHOOL)
print(f"P1 学校与学习: {len(P1_SCHOOL)} 词")

# ============================================================
# P1: 家庭与社区 (~55词)
# ============================================================
P1_FAMILY = [
    make_entry("aunt", "阿姨；姑姑；婶婶", "noun_common", 1, "high",
        ["uncle", "cousin", "family"], ["auntie"],
        "My aunt lives in Shanghai.", "aunt=妈妈的姐妹或爸爸的姐妹"),
    make_entry("baby", "婴儿", "noun_common", 1, "high",
        ["child", "infant", "kid"], ["babby"],
        "The baby is sleeping now. Please be quiet.", "baby=婴儿"),
    make_entry("balcony", "阳台", "noun_place", 1, "medium",
        ["window", "apartment", "floor"], [],
        "There are flowers on the balcony.", "balco(梁)+ny→有横梁的地方"),
    make_entry("bathroom", "浴室；洗手间", "noun_place", 1, "high",
        ["toilet", "wash", "shower"], [],
        "Go to the bathroom and wash your hands.", "bath(洗澡)+room=浴室"),
    make_entry("bedroom", "卧室", "noun_place", 1, "high",
        ["sleep", "bed", "room"], [],
        "My bedroom is small but clean.", "bed(床)+room=睡觉的房间"),
    make_entry("brother", "兄弟", "noun_common", 1, "high",
        ["sister", "family", "sibling"], ["bother", "broth"],
        "I have an older brother.", "brother=兄弟"),
    make_entry("cousin", "堂/表兄弟姐妹", "noun_common", 1, "high",
        ["aunt", "uncle", "relative"], [],
        "My cousin is coming to visit us this weekend.", "cousin=堂表亲"),
    make_entry("dad", "爸爸", "noun_common", 1, "high",
        ["father", "parent", "family"], ["bad", "sad"],
        "Dad, can you help me with my homework?", "dad=爸爸"),
    make_entry("daughter", "女儿", "noun_common", 1, "high",
        ["son", "child"], ["doctor"],
        "Their daughter is very clever.", "daught(乳)+er→哺乳的孩子"),
    make_entry("elder", "年长的；长辈", "noun_common", 1, "medium",
        ["older", "grandparent", "senior"], ["elderly"],
        "We should respect our elders.", "old的比较级→更老→长辈"),
    make_entry("flat", "公寓；（adj）平坦的", "noun_common", 1, "medium",
        ["apartment", "room", "house"], ["fleet"],
        "They live in a small flat in the city center.", "flat=公寓/平的"),
    make_entry("garage", "车库", "noun_place", 1, "medium",
        ["car", "park", "house"], ["garbage"],
        "Dad parked the car in the garage.", "gara(保护)+ge→停放车辆处"),
    make_entry("gentleman", "先生；绅士", "noun_common", 1, "medium",
        ["man", "polite", "kind"], [],
        "He is a real gentleman.", "gentle(温和)+man→温和的人"),
    make_entry("grandchild", "孙/外孙", "noun_common", 1, "medium",
        ["grandparent", "family", "child"], [],
        "Grandma loves her grandchildren very much.", "grand(大)+child→大的孩子辈"),
    make_entry("grandfather", "爷爷；外公", "noun_common", 1, "high",
        ["grandparent", "elder", "family"], [],
        "My grandfather tells me stories every night.", "grand(祖父)+father"),
    make_entry("grandmother", "奶奶；外婆", "noun_common", 1, "high",
        ["grandparent", "elder", "family"], [],
        "Grandmother cooks delicious food.", "grand(祖母)+mother"),
    make_entry("husband", "丈夫", "noun_common", 1, "high",
        ["wife", "marry", "family"], ["husky"],
        "Her husband works in a bank.", "hus(房屋)+band→一家之主"),
    make_entry("kid", "小孩", "noun_common", 1, "high",
        ["child", "boy", "girl"], ["kit", "lid"],
        "The kids are playing in the park.", "kid=小孩"),
    make_entry("lady", "女士；夫人", "noun_common", 1, "high",
        ["woman", "gentleman", "miss"], ["lazy"],
        "Excuse me, lady. Is this seat taken?", "lady=女士"),
    make_entry("living room", "客厅；起居室", "noun_place", 1, "high",
        ["sofa", "TV", "relax"], [],
        "We watch TV in the living room.", "living(生活)+room=生活空间"),
    make_entry("mom", "妈妈", "noun_common", 1, "high",
        ["mother", "parent", "family"], ["some"],
        "Mom, I'm hungry.", "mom=mum=妈妈"),
    make_entry("neighbor", "邻居", "noun_common", 1, "high",
        ["next door", "live near", "community"], [],
        "My neighbor is a friendly old man.", "neigh(近)+bor→住在近处的人"),
    make_entry("nephew", "侄子；外甥", "noun_common", 1, "medium",
        ["uncle", "aunt", "family"], [],
        "My nephew is five years old this year.", "neph(孙子)+ew→下一代男性亲属"),
    make_entry("niece", "侄女；外甥女", "noun_common", 1, "medium",
        ["uncle", "aunt", "family"], ["piece", "nice"],
        "My niece likes drawing pictures.", "niec(孙女)+e→下一代女性亲属"),
    make_entry("parent", "父/母；家长", "noun_common", 1, "high",
        ["father", "mother", "family"], ["paint"],
        "Parents love their children.", "par(生)+ent→生育者"),
    make_entry("relative", "亲戚", "noun_common", 1, "medium",
        ["family", "aunt", "uncle"], [],
        "We visited our relatives during Spring Festival.", "relat(关系)+ive→有关系的人"),
    make_entry("roof", "屋顶", "noun_place", 1, "medium",
        ["house", "top", "cover"], ["room"],
        "There is a cat on the roof.", "roof=屋顶"),
    make_entry("sister", "姐妹", "noun_common", 1, "high",
        ["brother", "family", "sibling"], ["sitter"],
        "My sister is two years older than me.", "sister=姐妹"),
    make_entry("son", "儿子", "noun_common", 1, "high",
        ["daughter", "child", "family"], ["soon"],
        "They have two sons and one daughter.", "son=儿子"),
    make_entry("stairs/staircase", "楼梯", "noun_place", 1, "medium",
        ["up", "down", "floor"], ["stars", "stares"],
        "Walk up the stairs to the second floor.", "stairs=阶梯"),
    make_entry("uncle", "叔叔；伯伯；舅舅", "noun_common", 1, "high",
        ["aunt", "cousin", "family"], ["angle"],
        "Uncle Li gave me a birthday gift.", "uncle=父母的兄弟"),
    make_entry("wife", "妻子", "noun_common", 1, "high",
        ["husband", "marry", "woman"], ["life", "knife"],
        "His wife is a doctor.", "wife=妻子"),
    make_entry("yard", "院子；庭院", "noun_place", 1, "medium",
        ["garden", "house", "outside"], ["hard"],
        "The children are playing in the yard.", "yard=院子"),
    make_entry("younger", "较年轻的", "adjective_describe", 1, "high",
        ["junior", "small", "new"], [],
        "My younger brother is in primary school.", "young(年轻)+er比较级"),
]

NEW_WORDS.extend(P1_FAMILY)
print(f"P1 家庭与社区: {len(P1_FAMILY)} 词")

# ============================================================
# 购物与服务 (~45词)
# ============================================================
P1_SHOPPING = [
    make_entry("afford", "买得起；承担得起", "verb_action", 1, "high",
        ["buy", "pay", "expensive"], ["affect", "effort"],
        "I can't afford such an expensive phone.", "af(向)+ford(前方)→能向前走到→买得起"),
    make_entry("bargain", "便宜货；讨价还价", "noun_common", 1, "medium",
        ["deal", "cheap", "discount"], [],
        "I got a bargain at the market today.", "bargain=讨价还价"),
    make_entry("bill", "账单；钞票", "noun_common", 1, "high",
        ["money", "pay", "check"], ["bell", "hill"],
        "Can I have the bill, please?", "bill=账单"),
    make_entry("buyer", "买主；购买者", "noun_common", 1, "medium",
        ["customer", "shopper", "seller"], ["by"],
        "The buyer looked at several houses.", "buy(买)+er→购买者"),
    make_entry("cash", "现金", "noun_common", 1, "high",
        ["money", "pay", "coin"], ["catch"],
        "Do you accept cash or only credit cards?", "cash=现金"),
    make_entry("center", "中心；中央", "noun_place", 1, "high",
        ["middle", "downtown"], [],
        "Let's meet at the shopping center.", "centr(中心)+e→中间位置"),
    make_entry("cheap", "便宜的", "adjective_opinion", 1, "high",
        ["inexpensive", "low price", "bargain"], ["chip"],
        "This shirt is very cheap.", "cheap=便宜"),
    make_entry("checkout", "结账；收银台", "noun_common", 1, "medium",
        ["pay", "cashier", "counter"], [],
        "Please go to the checkout counter.", "check(检查)+out→结算离开"),
    make_entry("coin", "硬币", "noun_common", 1, "medium",
        ["money", "cash", "change"], ["corn"],
        "I need some coins for the vending machine.", "coin=硬币"),
    make_entry("cost", "花费；代价", "noun_common", 1, "high",
        ["price", "expense", "value"], ["cast", "most"],
        "The cost of living in big cities is high.", "cost=费用"),
    make_entry("coupon", "优惠券；票券", "noun_common", 1, "medium",
        ["discount", "save", "ticket"], [],
        "I have a coupon for ten percent off.", "coup(切)+on→可切割金额的小纸片"),
    make_entry("customer", "顾客；客户", "noun_common", 1, "high",
        ["buyer", "client", "shopper"], ["custom", "costume"],
        "The shop has many customers on weekends.", "custom(习惯)+er→常来的人"),
    make_entry("discount", "折扣", "noun_common", 1, "high",
        ["sale", "reduce price", "cheaper"], ["count", "account"],
        "There's a discount if you buy two.", "dis(去掉)+count(计数)→减少数目"),
    make_entry("expensive", "昂贵的", "adjective_opinion", 1, "high",
        ["dear", "costly", "not cheap"], ["experience", "expense"],
        "This watch is too expensive for me.", "ex(出)+pens(花费)+ive→花出去很多"),
    make_entry("fair", "公平的；集市", "adjective_opinion", 1, "high",
        ["just", "equal", "market"], ["fare", "fire"],
        "The price is fair and reasonable.", "fair=公平/市集"),
    make_entry("free", "免费的；自由的", "adjective_opinion", 1, "high",
        ["no cost", "liberate", "at no charge"], ["tree", "three"],
        "This book is free for students.", "free=免费"),
    make_entry("grocery", "食品杂货店", "noun_common", 1, "medium",
        ["shop", "food", "supermarket"], [],
        "Mom went to buy some groceries.", "gross(大量)+ery→大量商品处"),
    make_entry("label", "标签；商标", "noun_common", 1, "medium",
        ["tag", "mark", "name"], ["lab"],
        "Check the label for ingredients.", "lab(标签)+el→标识物"),
    make_entry("mall", "购物中心", "noun_place", 1, "high",
        ["shopping center", "store", "shop"], ["small", "ball"],
        "Let's go to the mall this afternoon.", "mall=商场"),
    make_entry("market", "市场；集市", "noun_place", 1, "high",
        ["shop", "store", "sell"], [],
        "My mother goes to the market every morning.", "market=市场"),
    make_entry("menu", "菜单", "noun_common", 1, "high",
        ["list", "food", "order"], ["men", "many"],
        "Let me see the menu first.", "menu=菜单"),
    make_entry("notice", "通知；注意到", "noun_common", 1, "high",
        ["announcement", "see", "sign"], [],
        "There's a notice on the board.", "not(知)+ice→让人知道的事"),
    make_entry("offer", "提供；报价", "verb_action", 1, "high",
        ["give", "provide", "supply"], ["office"],
        "They offered me a job.", "of(向)+fer(拿)→拿出来给对方"),
    make_entry("order", "订购；订单；命令", "verb_action", 1, "high",
        ["request", "command", "buy"], ["ordinary"],
        "I'd like to order a pizza, please.", "order=点餐/命令"),
    make_entry("pay", "支付；付钱", "verb_action", 1, "high",
        ["buy", "spend money", "cost"], ["say", "day"],
        "How would you like to pay?", "pay=付款"),
    make_entry("price", "价格；价钱", "noun_common", 1, "high",
        ["cost", "value", "money"], ["prize"],
        "What's the price of this bag?", "price=价格"),
    make_entry("product", "产品；产物", "noun_common", 1, "high",
        ["goods", "item", "make"], ["produce", "project"],
        "This company makes electronic products.", "pro(向前)+duct(引导)→生产出来的东西"),
    make_entry("receipt", "收据；收条", "noun_common", 1, "medium",
        ["proof", "bill", "paper"], ["receive"],
        "Keep the receipt in case you want to return it.", "receiv(接收)+et→接收凭证"),
    make_entry("refund", "退款", "noun_common", 1, "medium",
        ["return money", "give back", "repay"], ["refuse"],
        "Can I get a refund for this?", "re(回)+fund(资金)→资金退回"),
    make_entry("sale", "销售；降价出售", "noun_common", 1, "high",
        ["sell", "discount", "promotion"], ["sell", "scale"],
        "There's a big sale at the store this weekend.", "sell(卖)+ale→销售活动"),
    make_entry("sample", "样品；样本", "noun_common", 1, "medium",
        ["example", "model", "test"], ["simple"],
        "Here's a free sample of the new product.", "sam(相同)+ple→取相同的部分"),
    make_entry("shop", "商店；购物", "noun_common", 1, "high",
        ["store", "buy", "market"], ["ship", "stop"],
        "I go shopping every Saturday.", "shop=商店"),
    make_entry("shopping", "购物", "noun_common", 1, "high",
        ["buy", "store", "mall"], [],
        "I enjoy shopping with my friends.", "shop(商店)+ping→去商店的活动"),
    make_entry("size", "尺寸；大小", "noun_common", 1, "high",
        ["measurement", "big", "small"], ["site", "side"],
        "What size shoes do you wear?", "size=尺码"),
    make_entry("supermarket", "超级市场", "noun_place", 1, "high",
        ["shop", "store", "food"], [],
        "We buy food at the supermarket every week.", "super(超级)+market=大型市场"),
    make_entry("total", "总计；完全的", "adjective_quantity", 1, "high",
        ["whole", "all", "sum"], [],
        "The total cost is two hundred yuan.", "total=总共"),
    make_entry("worth", "值……的；值得", "adjective_opinion", 1, "high",
        ["valuable", "worthy", "deserve"], ["worse", "worst"],
        "This phone is worth three thousand yuan.", "worth=价值"),
]

NEW_WORDS.extend(P1_SHOPPING)
print(f"P1 购物与服务: {len(P1_SHOPPING)} 词")

# ============================================================
# 交通出行 (~40词)
# ============================================================
P1_TRANSPORT = [
    make_entry("airport", "机场；航空港", "noun_place", 1, "high",
        ["plane", "fly", "travel"], [],
        "We arrived at the airport two hours early.", "air(空气)+port(港口)→飞机港口"),
    make_entry("bridge", "桥；桥梁", "noun_place", 1, "high",
        ["cross", "river", "road"], ["brigade"],
        "The bridge across the river is very long.", "bridge=桥梁"),
    make_entry("captain", "队长；船长；机长", "noun_common", 1, "medium",
        ["leader", "head", "chief"], ["capital"],
        "The captain welcomed us aboard.", "cap(头)+tain→领头的人"),
    make_entry("car", "汽车；轿车", "noun_common", 1, "high",
        ["vehicle", "drive", "auto"], ["card", "care"],
        "My father drives a car to work.", "car=汽车"),
    make_entry("crossing", "十字路口；穿越", "noun_common", 1, "medium",
        ["intersection", "cross", "road"], [],
        "Be careful at the road crossing.", "cross(穿过)+ing→穿越之处"),
    make_entry("direction", "方向；指示", "noun_common", 1, "high",
        ["way", "route", "instruction"], ["direct", "dirt"],
        "Can you tell me the direction to the station?", "direct(直接)+ion→指明方向"),
    make_entry("distance", "距离；远处", "noun_common", 1, "medium",
        ["far away", "length", "space"], [],
        "The distance between two cities is 300 km.", "dis(分开)+stance(站)→站得很开→远"),
    make_entry("driver", "司机；驾驶员", "noun_common", 1, "high",
        ["drive", "car", "taxi"], ["diver"],
        "The bus driver is very friendly.", "driv(驾驶)+er→开车的人"),
    make_entry("engine", "引擎；发动机", "noun_common", 1, "medium",
        ["motor", "machine", "car"], ["engineer"],
        "The engine makes a strange sound.", "engin(才能)+e→产生动力的装置"),
    make_entry("exit", "出口；退出", "noun_common", 1, "high",
        ["door out", "leave", "way out"], ["exist"],
        "Where is the exit?", "ex(出)+it(走)→走出去的地方"),
    make_entry("flight", "航班；飞行", "noun_common", 1, "high",
        ["plane", "airplane", "fly"], ["fight"],
        "Our flight number is CA1234.", "flig(飞)+t→飞行"),
    make_entry("fuel", "燃料；燃油", "noun_common", 1, "medium",
        ["gas", "oil", "energy"], ["full"],
        "We need to stop for fuel.", "fuel=燃料"),
    make_entry("helicopter", "直升机", "noun_common", 1, "low",
        ["aircraft", "fly", "rotor"], [],
        "The helicopter landed on the roof.", "helic(螺旋)+opter→螺旋飞行器"),
    make_entry("highway", "高速公路", "noun_place", 1, "medium",
        ["road", "fast", "expressway"], [],
        "Don't drive too fast on the highway.", "high(高)+way(路)→高速路"),
    make_entry("journey", "旅行；旅程", "noun_common", 1, "high",
        ["trip", "travel", "tour"], ["journal"],
        "Have a safe journey!", "journ(日)+ey→一日行程→旅程"),
    make_entry("lane", "车道；小巷", "noun_place", 1, "medium",
        ["road", "path", "line"], ["lain", "loan"],
        "Change to the right lane before turning.", "lane=车道"),
    make_entry("licence/license", "执照；许可证", "noun_common", 1, "medium",
        ["permit", "document", "allow"], [],
        "Do you have a driving license?", "licen(允许)+se→许可文件"),
    make_entry("motorcycle", "摩托车", "noun_common", 1, "medium",
        ["bike", "motorbike", "ride"], [],
        "He rides a motorcycle to work.", "motor(马达)+cycle(车)→摩托车"),
    make_entry("passenger", "乘客；旅客", "noun_common", 1, "high",
        ["traveler", "rider", "customer"], ["passport"],
        "No passengers are allowed in the driver's seat.", "pass(经过)+enger→路过的人"),
    make_entry("pedestrian", "行人；步行者", "noun_common", 1, "medium",
        ["walker", "person on foot", "crossing"], [],
        "Pedestrians should use the crosswalk.", "ped(脚)+estrian→用脚走路的人"),
    make_entry("pilot", "飞行员；领航员", "noun_common", 1, "medium",
        ["driver", "fly", "captain"], ["pivot"],
        "My uncle is a pilot.", "pilot=飞行员"),
    make_entry("platform", "站台；平台", "noun_place", 1, "medium",
        ["station", "train", "stage"], ["plate"],
        "The train leaves from Platform Three.", "plat(平)+form(形)→平面场地→站台"),
    make_entry("port", "港口；口岸", "noun_place", 1, "medium",
        ["harbor", "ship", "dock"], ["part", "sport"],
        "Shanghai is a busy port city.", "port=港口"),
    make_entry("railway/railroad", "铁路", "noun_place", 1, "medium",
        ["train", "track", "station"], [],
        "The railway station is near my home.", "rail(铁轨)+way(路)=铁路"),
    make_entry("route", "路线；路程", "noun_common", 1, "medium",
        ["way", "path", "direction"], ["routine"],
        "What's the best route to the airport?", "route=路线"),
    make_entry("schedule", "时间表；日程安排", "noun_common", 1, "medium",
        ["timetable", "plan", "program"], ["scheme"],
        "Check the train schedule before leaving.", "sched(计划)+ule→计划表"),
    make_entry("speed", "速度；加速", "noun_common", 1, "high",
        ["fast", "quick", "rate"], ["spend", "seed"],
        "The speed limit here is 60 km/h.", "speed=速度"),
    make_entry("station", "车站；站点", "noun_place", 1, "high",
        ["train", "bus", "stop"], [],
        "I'll meet you at the bus station.", "stat(站立)+ion→停留处"),
    make_entry("taxi", "出租车", "noun_common", 1, "high",
        ["cab", "car", "ride"], [],
        "Let's take a taxi there.", "taxi=出租车"),
    make_entry("ticket", "票；入场券", "noun_common", 1, "high",
        ["pass", "entry", "fare"], ["thick"],
        "I bought two movie tickets online.", "tick(标记)+et→有标记的票据"),
    make_entry("traffic", "交通；车辆", "noun_common", 1, "high",
        ["vehicles", "cars", "transport"], ["tragic"],
        "There's heavy traffic this morning.", "trafic(道路)+fic→路上的事"),
    make_entry("train", "火车；训练", "noun_common", 1, "high",
        ["railway", "rail", "vehicle"], ["trail", "brain"],
        "The train arrives at 9 o'clock.", "train=火车/训练"),
    make_entry("transport", "交通运输", "noun_common", 1, "medium",
        ["carry", "traffic", "vehicle"], ["transform"],
        "Public transport is cheap and convenient.", "trans(跨越)+port(带)→跨地带运"),
    make_entry("travel", "旅行；游历", "verb_action", 1, "high",
        ["trip", "journey", "tour"], ["travail"],
        "I want to travel around the world.", "travel=旅行"),
    make_entry("trip", "旅行；旅途", "noun_common", 1, "high",
        ["journey", "travel", "tour"], ["trap", "tip"],
        "We had a wonderful trip to Hangzhou.", "trip=短途旅行"),
    make_entry("truck", "卡车；货车", "noun_common", 1, "medium",
        ["lorry", "vehicle", "carry"], ["trick", "track"],
        "A truck delivered the furniture.", "truck=卡车"),
    make_entry("wheel", "车轮；方向盘", "noun_common", 1, "medium",
        ["tire", "round", "steer"], ["while", "whale"],
        "One of the car wheels is flat.", "wheel=轮子"),
]

NEW_WORDS.extend(P1_TRANSPORT)
print(f"P1 交通出行: {len(P1_TRANSPORT)} 词")

# ============================================================
# 饮食健康 (~40词)
# ============================================================
P1_FOOD_HEALTH = [
    make_entry("beef", "牛肉", "noun_common", 1, "high",
        ["meat", "cow", "steak"], ["been", "beer"],
        "Would you like some beef noodles?", "beef=牛肉"),
    make_entry("biscuit", "饼干", "noun_common", 1, "medium",
        ["cookie", "snack", "cracker"], ["basket"],
        "I ate a biscuit with my tea.", "bis(二)+cuit(烤)→烘烤两次的饼"),
    make_entry("bottle", "瓶子", "noun_common", 1, "high",
        ["container", "drink", "water"], ["battle", "bottom"],
        "Drink plenty of water from your bottle.", "bottle=瓶"),
    make_entry("bowl", "碗", "noun_common", 1, "high",
        ["dish", "soup", "rice"], ["owl"],
        "Have a bowl of soup, please.", "bowl=碗"),
    make_entry("breakfast", "早餐", "noun_common", 1, "high",
        ["morning meal", "eat", "food"], [],
        "Breakfast is the most important meal of the day.", "break(中断)+fast(禁食)→停止禁食→吃早饭"),
    make_entry("butter", "黄油；奶油", "noun_common", 1, "medium",
        ["spread", "bread", "cream"], ["bitter"],
        "Put some butter on the bread.", "butter=黄油"),
    make_entry("cafe", "咖啡馆；小餐馆", "noun_place", 1, "medium",
        ["coffee", "restaurant", "drink"], ["case"],
        "Let's meet at the cafe after class.", "cafe=咖啡厅"),
    make_entry("cheese", "奶酪；干酪", "noun_common", 1, "medium",
        ["dairy", "milk", "pizza"], ["choose", "cheers"],
        "I'd like some cheese on my pizza.", "cheese=奶酪"),
    make_entry("chocolate", "巧克力", "noun_common", 1, "high",
        ["candy", "sweet", "dessert"], [],
        "Most kids love chocolate.", "chocolate=巧克力"),
    make_entry("coffee", "咖啡", "noun_common", 1, "high",
        ["drink", "caffeine", "cafe"], ["copy", "coffin"],
        "Would you like some coffee?", "coffee=咖啡"),
    make_entry("cook", "厨师；烹饪", "verb_action", 1, "high",
        ["prepare food", "chef", "kitchen"], ["cool", "look"],
        "Mom is cooking dinner in the kitchen.", "cook=做饭"),
    make_entry("cookie", "饼干；小甜饼", "noun_common", 1, "medium",
        ["biscuit", "sweet", "snack"], [],
        "Grandma baked some cookies for us.", "cook(烹制)+ie→小块食物"),
    make_entry("corn", "玉米；谷物", "noun_common", 1, "high",
        ["maize", "vegetable", "yellow"], [],
        "Corn is grown in many parts of China.", "corn=玉米"),
    make_entry("cup", "杯子；一杯", "noun_common", 1, "high",
        ["mug", "drink", "tea"], ["cap", "cut"],
        "Would you like another cup of tea?", "cup=杯"),
    make_entry("dairy", "乳制品；牛奶场", "noun_common", 1, "medium",
        ["milk", "cheese", "yogurt"], ["daily", "diary"],
        "Eat more dairy products for calcium.", "dairy=乳制品"),
    make_entry("delicious", "美味的；可口的", "adjective_opinion", 1, "high",
        ["tasty", "yummy", "good"], [],
        "This cake smells delicious!", "de(加强)+lic(吸引)+ious→非常诱人"),
    make_entry("diet", "饮食；日常饮食", "noun_common", 1, "medium",
        ["food", "eating", "health"], [],
        "A balanced diet is important.", "diet=日常饮食"),
    make_entry("dish", "菜肴；碟子", "noun_common", 1, "high",
        ["plate", "food", "serve"], ["disk", "dash"],
        "What's your favorite dish?", "dish=菜/盘子"),
    make_entry("drink", "饮料；喝", "verb_action", 1, "high",
        ["beverage", "water", "juice"], ["drunk"],
        "Drink plenty of water every day.", "drink=喝/饮料"),
    make_entry("fat", "脂肪；胖的", "noun_common", 1, "medium",
        ["oil", "overweight", "greasy"], ["fit", "fact"],
        "Too much fat is not good for health.", "fat=脂肪"),
    make_entry("fork", "叉子", "noun_common", 1, "medium",
        ["knife", "spoon", "eat"], ["folk", "work"],
        "Use the fork to eat the salad.", "fork=叉子"),
    make_entry("fresh", "新鲜的", "adjective_describe", 1, "high",
        ["new", "clean", "not old"], ["flesh", "fish"],
        "These vegetables are very fresh.", "fresh=新鲜"),
    make_entry("fruit", "水果", "noun_common", 1, "high",
        ["apple", "banana", "orange"], ["front"],
        "Eat fruit every day for vitamins.", "fruit=水果"),
    make_entry("hungry", "饥饿的", "adjective_describe", 1, "high",
        ["want food", "starving", "thirsty"], ["anger"],
        "I'm hungry. Let's get something to eat.", "hungr(饥饿)+y"),
    make_entry("ingredient", "原料；成分", "noun_common", 1, "medium",
        ["part", "element", "cooking"], [],
        "Check the ingredients on the package.", "ingredi(进入)+ent→放入的东西"),
    make_entry("juice", "果汁；蔬菜汁", "noun_common", 1, "high",
        ["drink", "fruit", "orange"], ["join"],
        "Would you like some orange juice?", "juice=果汁"),
    make_entry("knife", "刀；餐刀", "noun_common", 1, "medium",
        ["cut", "sharp", "tool"], ["knee", "knock"],
        "Pass me the knife, please.", "knife=刀"),
    make_entry("lunch", "午餐", "noun_common", 1, "high",
        ["noon meal", "midday", "eat"], ["launch"],
        "What did you have for lunch?", "lunch=午饭"),
    make_entry("meal", "一顿饭；膳食", "noun_common", 1, "high",
        ["breakfast", "lunch", "dinner"], ["mail", "mean"],
        "Three meals a day is healthy.", "meal=餐/饭"),
    make_entry("meat", "肉；肉类", "noun_common", 1, "high",
        ["beef", "pork", "food"], ["meet", "mat"],
        "I don't eat much meat.", "meat=肉"),
    make_entry("nutritious", "有营养的", "adjective_opinion", 1, "medium",
        ["healthy", "nourishing", "good"], [],
        "Vegetables are nutritious.", "nutri(营养)+tious→含营养的"),
    make_entry("pan", "平底锅", "noun_common", 1, "medium",
        ["pot", "cook", "fry"], ["plan"],
        "Heat some oil in the pan.", "pan=平底锅"),
    make_entry("pepper", "胡椒；辣椒", "noun_common", 1, "medium",
        ["spicy", "salt", "seasoning"], ["paper"],
        "Add a little pepper for flavor.", "pepper=胡椒/辣椒"),
    make_entry("plate", "盘子；碟子", "noun_common", 1, "high",
        ["dish", "serving", "food"], ["place", "plant"],
        "Put the food on a plate.", "plate=盘子"),
    make_entry("porridge", "粥；糊", "noun_common", 1, "medium",
        ["oatmeal", "breakfast", "hot"], [],
        "Chinese people often eat porridge for breakfast.", "porridge=粥"),
    make_entry("pot", "锅；壶", "noun_common", 1, "high",
        ["pan", "cook", "soup"], ["pat", "put"],
        "Boil the water in the pot.", "pot=锅"),
    make_entry("restaurant", "餐馆；餐厅", "noun_place", 1, "high",
        ["eat", "dinner", "food"], ["restriction"],
        "Let's try that new restaurant.", "restaur(恢复)+ant→恢复精力处"),
    make_entry("salad", "色拉；凉拌菜", "noun_common", 1, "medium",
        ["vegetable", "healthy", "fresh"], ["salary"],
        "I'll have a chicken salad.", "salad=沙拉"),
    make_entry("salt", "盐；食盐", "noun_common", 1, "medium",
        ["seasoning", "salty", "pepper"], ["sat", "slot"],
        "Don't add too much salt.", "salt=盐"),
    make_entry("sandwich", "三明治", "noun_common", 1, "high",
        ["bread", "filling", "lunch"], [],
        "I made a sandwich for lunch.", "sandwich=三明治"),
    make_entry("snack", "零食；点心", "noun_common", 1, "medium",
        ["food between meals", "candy", "cookie"], ["snake", "snap"],
        "Don't eat too many snacks.", "snack=零食"),
    make_entry("soup", "汤", "noun_common", 1, "high",
        ["bowl", "hot", "liquid"], ["soap", "sup"],
        "Would you like some soup?", "soup=汤"),
    make_entry("spoon", "勺子", "noun_common", 1, "medium",
        ["eat", "soup", "tool"], ["soon", "moon"],
        "Use a spoon to drink the soup.", "spoon=勺子"),
    make_entry("sugar", "糖；食糖", "noun_common", 1, "high",
        ["sweet", "candy", "add"], ["sure"],
        "Too much sugar is bad for teeth.", "sugar=糖"),
    make_entry("thirsty", "口渴的", "adjective_describe", 1, "high",
        ["want drink", "dry", "need water"], ["thirty"],
        "I'm thirsty. Can I have some water?", "thirs(渴)+ty"),
    make_entry("tomato", "番茄；西红柿", "noun_common", 1, "high",
        ["red", "vegetable", "sauce"], ["potato"],
        "Tomatoes are good for salads.", "tomato=西红柿"),
    make_entry("vegetable", "蔬菜", "noun_common", 1, "high",
        ["healthy", "green", "food"], [],
        "Eat more vegetables every day.", "vegetab(植物)+le→植物性食物"),
    make_entry("waiter", "服务员（男）", "noun_common", 1, "medium",
        ["server", "restaurant", "serve"], ["water"],
        "Waiter, could I have the menu?", "wait(等)+er→等候客人的人"),
    make_entry("waitress", "服务员（女）", "noun_common", 1, "medium",
        ["server", "restaurant", "female"], [],
        "The waitress brought us the bill.", "wait(等)+ress(女性)→女服务员"),
    make_entry("yogurt/yoghurt", "酸奶", "noun_common", 1, "medium",
        ["dairy", "healthy", "milk"], [],
        "Yogurt is good for digestion.", "yogurt=酸奶"),
]

NEW_WORDS.extend(P1_FOOD_HEALTH)
print(f"P1 饮食健康: {len(P1_FOOD_HEALTH)} 词")

# 保存第一部分进度
PART1_COUNT = len(NEW_WORDS)
print(f"\n=== 第一部分总计: {PART1_COUNT} 新词 ===")

# ============================================================
# 天气环境 (~30词)
# ============================================================
P1_WEATHER_ENV = [
    make_entry("beach", "海滩；沙滩", "noun_place", 1, "high",
        ["sand", "sea", "swim"], ["pitch"],
        "We spent the day at the beach.", "beach=海滩"),
    make_entry("cloud", "云；云朵", "noun_common", 1, "high",
        ["sky", "rain", "weather"], ["could"],
        "Look at those white clouds!", "cloud=云"),
    make_entry("cloudy", "多云的；阴天的", "adjective_describe", 1, "high",
        ["overcast", "not sunny", "gray sky"], [],
        "It's cloudy today. It might rain.", "cloud(云)+y→多云的"),
    make_entry("degree", "度数；程度；学位", "noun_common", 1, "high",
        ["temperature", "level", "amount"], ["decrease"],
        "It's thirty degrees outside.", "degre(步)+e→量度的步长"),
    make_entry("earthquake", "地震", "noun_common", 1, "medium",
        ["shake", "disaster", "ground"], [],
        "An earthquake shook the city last night.", "earth(地)+quake(震动)"),
    make_entry("environment", "环境", "noun_place", 1, "high",
        ["nature", "surroundings", "eco"], [],
        "We should protect our environment.", "environ(周围)+ment→周围的一切"),
    make_entry("fog/foggy", "雾；雾的", "noun_common", 1, "medium",
        ["mist", "cloudy", "can't see"], ["dog", "frog"],
        "Drive carefully in the fog.", "fog=雾"),
    make_entry("forest", "森林；树林", "noun_place", 1, "high",
        ["woods", "trees", "nature"], [],
        "There are many animals in the forest.", "for(外面)+est(最)→树木最多的地方"),
    make_entry("grass", "草；草地", "noun_common", 1, "high",
        ["green", "lawn", "field"], ["glass", "class"],
        "Don't walk on the grass.", "grass=草"),
    make_entry("lake", "湖；湖泊", "noun_place", 1, "high",
        ["water", "pond", "swim"], ["like", "late"],
        "The lake is very clear and blue.", "lake=湖泊"),
    make_entry("lightning", "闪电", "noun_common", 1, "medium",
        ["storm", "thunder", "flash"], [],
        "Lightning lit up the whole sky.", "light(光)+ning→发光现象"),
    make_entry("mountain", "山；山脉", "noun_place", 1, "high",
        ["hill", "peak", "climb"], ["fountain"],
        "The mountain is covered with snow.", "mount(山)+ain→山脉"),
    make_entry("nature", "自然；自然界", "noun_place", 1, "high",
        ["environment", "outdoors", "wild"], ["native", "mature"],
        "We should love nature.", "nat(出生)+ure→天然存在的"),
    make_entry("pool", "水池；游泳池", "noun_place", 1, "medium",
        ["swim", "water", "swimming"], ["fool", "cool"],
        "Let's go swimming in the pool.", "pool=水池/泳池"),
    make_entry("rain", "雨；下雨", "noun_common", 1, "high",
        ["water drops", "wet", "weather"], ["ran", "rang"],
        "It's going to rain soon.", "rain=雨"),
    make_entry("rainy", "下雨的；多雨的", "adjective_describe", 1, "high",
        ["wet", "raining", "showers"], [],
        "I don't like rainy days.", "rain(雨)+y→下雨的"),
    make_entry("river", "河；江", "noun_place", 1, "high",
        ["water", "flow", "stream"], ["driver", "diver"],
        "The river runs through the city.", "river=河流"),
    make_entry("rock", "岩石；石头", "noun_common", 1, "medium",
        ["stone", "hard", "mountain"], ["rocket", "rack"],
        "Sit on that rock and rest.", "rock=岩石"),
    make_entry("sand", "沙子；沙滩", "noun_common", 1, "medium",
        ["beach", "desert", "fine"], ["send"],
        "The children played in the sand.", "sand=沙子"),
    make_entry("sea/ocean", "海；海洋", "noun_place", 1, "high",
        ["water", "beach", "swim"], ["see", "say"],
        "The sea looks beautiful at sunset.", "sea=海洋"),
    make_entry("shore", "岸；滨", "noun_place", 1, "medium",
        ["beach", "coast", "water edge"], ["share", "short"],
        "We walked along the shore.", "shore=海岸"),
    make_entry("sky", "天空；天", "noun_place", 1, "high",
        ["blue", "clouds", "above"], ["ski", "spy"],
        "Look at the stars in the sky.", "sky=天空"),
    make_entry("snow", "雪；下雪", "noun_common", 1, "high",
        ["white", "cold", "winter"], ["slow", "show"],
        "Children love to play in the snow.", "snow=雪"),
    make_entry("snowy", "下雪的；多雪的", "adjective_describe", 1, "high",
        ["white", "cold", "winter weather"], [],
        "It's snowy outside. Wear warm clothes.", "snow(雪)+y→下雪的"),
    make_entry("storm", "暴风雨；风暴", "noun_common", 1, "medium",
        ["bad weather", "wind", "rain"], ["stamp", "steam"],
        "A storm is coming. Stay indoors.", "storm=暴风雨"),
    make_entry("sunny", "晴朗的；阳光充足的", "adjective_describe", 1, "high",
        ["bright", "shining", "clear"], ["funny"],
        "It's a sunny day. Let's go out!", "sun(太阳)+ny→有太阳的"),
    make_entry("temperature", "温度；气温", "noun_common", 1, "high",
        ["hot", "cold", "degrees"], [],
        "The temperature dropped to zero.", "temper(温度)+ature→温度状态"),
    make_entry("thunder", "雷；雷声", "noun_common", 1, "medium",
        ["loud noise", "storm", "lightning"], ["Sunday"],
        "Thunder scared the cat.", "thund(轰鸣)+er→雷声"),
    make_entry("weather", "天气；气象", "noun_common", 1, "high",
        ["sunny", "rainy", "climate"], ["whether"],
        "What's the weather like today?", "weath(风)+er→大气状态"),
    make_entry("wind", "风； windy", "noun_common", 1, "high",
        ["blow", "air", "breeze"], ["wine", "wing"],
        "The wind is blowing hard today.", "wind=风"),
    make_entry("windy", "有风的；风大的", "adjective_describe", 1, "high",
        ["breezy", "blowing", "not calm"], ["window"],
        "It's too windy to fly a kite.", "wind(风)+y→有风的"),
]

NEW_WORDS.extend(P1_WEATHER_ENV)
print(f"P1 天气环境: {len(P1_WEATHER_ENV)} 词")

# ============================================================
# P2: 中考高频动词 A-L (~200词)
# ============================================================
P2_VERBS_AL = [
    make_entry("accept", "接受；承认", "verb_action", 1, "high",
        ["agree", "take", "receive"], ["except", "access"],
        "I accept your invitation.", "ac(向)+cept(拿)→拿过来→接受"),
    make_entry("admire", "钦佩；赞赏", "verb_action", 1, "medium",
        ["respect", "look up to", "praise"], [],
        "I admire my teacher very much.", "ad(加强)+mire(惊奇)→令人惊叹→佩服"),
    make_entry("advise", "建议；劝告", "verb_action", 1, "high",
        ["suggest", "recommend", "tell"], ["advice", "advance"],
        "The doctor advised me to exercise more.", "ad(向)+vise(看)→让人看→建议"),
    make_entry("announce", "宣布；通告", "verb_action", 1, "medium",
        ["declare", "state", "tell"], [],
        "The teacher announced the test date.", "an(向)+nounce(报告)→向大家报告"),
    make_entry("apologize", "道歉；谢罪", "verb_action", 1, "high",
        ["say sorry", "regret", "excuse"], [],
        "You should apologize to her.", "apo(远离)+log(说)+ize→说开→道歉"),
    make_entry("apply", "申请；应用", "verb_action", 1, "high",
        ["request", "use", "put into practice"], ["apple"],
        "I want to apply for this job.", "ap(向)+ply(折叠)→折叠上去→申请"),
    make_entry("appreciate", "欣赏；感激", "verb_action", 1, "medium",
        ["thank", "value", "enjoy"], [],
        "I appreciate your help.", "ap(加强)+preci(价值)+ate→认可价值→感激"),
    make_entry("arrange", "安排；整理", "verb_action", 1, "high",
        ["organize", "plan", "prepare"], ["range"],
        "Let's arrange a meeting.", "ar(排列)+range(行)→排成行→安排"),
    make_entry("avoid", "避免；避开", "verb_action", 1, "high",
        ["stay away from", "prevent", "escape"], [],
        "You should avoid making the same mistake.", "a(出)+void(空)→使落空→避开"),
    make_entry("balance", "平衡；使均衡", "verb_action", 1, "medium",
        ["keep steady", "equal", "offset"], [],
        "Try to balance work and life.", "bal(双)+ance→两边相等"),
    make_entry("bear", "忍受；承受；熊", "verb_action", 1, "medium",
        ["stand", "tolerate", "carry"], ["bare", "pear"],
        "I can't bear the pain anymore.", "bear=忍受"),
    make_entry("beat", "打败；敲打；（心脏）跳动", "verb_action", 1, "high",
        ["win against", "hit", "pulse"], ["heat", "meat"],
        "Our team beat theirs 3-0.", "beat=击败"),
    make_entry("bite", "咬；叮", "verb_action", 1, "medium",
        ["cut with teeth", "sting", "nibble"], ["bit", "bait"],
        "The dog bit his leg.", "bite=咬"),
    make_entry("blow", "吹；刮风；爆炸", "verb_action", 1, "high",
        ["wind", "explode", "puff"], ["blue"],
        "The wind blew my hat off.", "blow=吹"),
    make_entry("boil", "煮沸；沸腾", "verb_action", 1, "medium",
        ["cook in water", "heat", "bubble"], ["boil", "oil"],
        "Boil some water for tea.", "boil=煮沸"),
    make_entry("bother", "打扰；烦恼", "verb_action", 1, "medium",
        ["disturb", "annoy", "trouble"], ["brother", "border"],
        "Sorry to bother you.", "both(两者)+er→两方面都烦→打扰"),
    make_entry("bounce", "弹跳；反弹", "verb_action", 1, "medium",
        ["spring back", "jump", "rebound"], ["bunch"],
        "The ball bounced off the wall.", "bounc(跳)+e→弹跳"),
    make_entry("burn", "燃烧；烧焦", "verb_action", 1, "high",
        ["fire", "flame", "hurt"], ["born", "turn"],
        "Be careful! Don't burn yourself.", "burn=燃烧"),
    make_entry("bury", "埋葬；隐藏", "verb_action", 1, "medium",
        ["hide underground", "cover", "dig"], ["busy", "berry"],
        "Dogs like to bury bones.", "bur(洞穴)+ry→藏进洞里"),
    make_entry("calculate", "计算；估算", "verb_action", 1, "medium",
        ["compute", "figure out", "count"], ["calendar"],
        "Calculate the total cost.", "calcul(小石子)+ate→用石子计算"),
    make_entry("cancel", "取消；撤销", "verb_action", 1, "high",
        ["call off", "stop", "delete"], ["cancer", "candle"],
        "The meeting was canceled.", "canc(擦掉)+el→擦掉→取消"),
    make_entry("celebrate", "庆祝；庆贺", "verb_action", 1, "high",
        ["party", "honor", "mark the day"], ["celebrity"],
        "We celebrate New Year with fireworks.", "celebr(隆重)+ate→隆重举行→庆祝"),
    make_entry("charge", "收费；指控；充电", "verb_action", 1, "high",
        ["ask for money", "accuse", "power up"], ["change", "charm"],
        "How much do you charge for this?", "charg(装载)+e→装载费用→收费"),
    make_entry("cheer", "欢呼；喝彩；使高兴", "verb_action", 1, "medium",
        ["shout happily", "encourage", "support"], ["cheek", "cheese"],
        "Everyone cheered when we won.", "cheer=欢呼"),
    make_entry("claim", "声称；索取", "verb_action", 1, "medium",
        ["state", "declare", "demand"], ["clam", "climb"],
        "He claims he didn't do it.", "clam(喊叫)→大声声明"),
    make_entry("collect", "收集；搜集", "verb_action", 1, "high",
        ["gather", "bring together", "accumulate"], ["correct", "connect"],
        "I collect stamps as a hobby.", "col(一起)+lect(选择)→选在一起→收集"),
    make_entry("compare", "比较；对比", "verb_action", 1, "high",
        ["contrast", "examine differences", "liken"], ["company", "compass"],
        "Compare these two products.", "com(共同)+pare(平等)→放一起看平等→对比"),
    make_entry("connect", "连接；联系", "verb_action", 1, "high",
        ["link", "join", "attach"], ["correct", "contact"],
        "Please connect to the WiFi.", "con(共同)+nect(绑)→绑在一起"),
    make_entry("consider", "考虑；认为", "verb_action", 1, "high",
        ["think about", "regard", "take into account"], ["consist"],
        "Please consider my suggestion.", "con(共同)+sider(星)→仔细看星星→深思"),
    make_entry("contain", "包含；容纳", "verb_action", 1, "medium",
        ["include", "hold", "have inside"], ["content", "contest"],
        "This box contains ten books.", "con(一起)+tain(保持)→保持在一起→包含"),
    make_entry("continue", "继续；持续", "verb_action", 1, "high",
        ["go on", "keep doing", "persist"], ["content"],
        "Please continue reading.", "con(一起)+tin(持)+ue→一直持有→继续"),
    make_entry("control", "控制；管理", "verb_action", 1, "high",
        ["manage", "direct", "be in charge of"], ["contrary"],
        "Try to control your anger.", "contra(反)+rol(滚)→反向滚动→控制住"),
    make_entry("convince", "说服；使确信", "verb_action", 1, "medium",
        ["persuade", "make believe", "assure"], [],
        "I convinced him to join us.", "con(彻底)+vince(征服)→彻底征服对方心意"),
    make_entry("copy", "复制；抄写；拷贝", "verb_action", 1, "high",
        ["duplicate", "imitate", "reproduce"], ["cop", "cap"],
        "Don't copy others' homework.", "copy=抄写/复制"),
    make_entry("correct", "改正；纠正", "verb_action", 1, "high",
        ["fix", "right", "amend"], ["collect"],
        "Please correct your mistakes.", "cor(正确)+rect(直)→改直→纠正"),
    make_entry("count", "数数；计算；重要", "verb_action", 1, "high",
        ["number", "calculate", "matter"], ["country"],
        "Count from one to ten.", "count=数数"),
    make_entry("cover", "覆盖；包括；报道", "verb_action", 1, "high",
        ["hide", "include", "report"], ["covet", "discover"],
        "Snow covered the ground.", "cov(盖)+er→遮盖"),
    make_entry("create", "创造；创建", "verb_action", 1, "high",
        ["make", "produce", "invent"], ["creative"],
        "Artists create beautiful paintings.", "cre(生长)+ate→生长出来→创造"),
    make_entry("cross", "穿过；交叉", "verb_action", 1, "high",
        ["go across", "intersect", "pass through"], [],
        "Look both ways before crossing the street.", "cross=穿过"),
    make_entry("cry", "哭；叫喊", "verb_action", 1, "high",
        ["weep", "shout", "sob"], ["try", "dry"],
        "Don't cry. Everything will be OK.", "cry=哭"),
    make_entry("damage", "损害；毁坏", "verb_action", 1, "high",
        ["harm", "destroy", "ruin"], [],
        "The storm damaged many houses.", "dam(损失)+age→造成损失"),
    make_entry("decide", "决定；决心", "verb_action", 1, "high",
        ["choose", "determine", "make up mind"], ["describe", "design"],
        "I decided to study harder.", "de(切断)+cide(切)→切下去→做决定"),
    make_entry("delay", "推迟；延误", "verb_action", 1, "high",
        ["postpone", "put off", "be late"], ["display"],
        "The flight was delayed by bad weather.", "de(向下)+lay(放置)→往下放→延后"),
    make_entry("deliver", "递送；发表（演讲）", "verb_action", 1, "high",
        ["bring", "give", "send"], ["delivery", "deliberate"],
        "The postman delivers letters every morning.", "de(自由)+liver(释放)→释放出来→递送"),
    make_entry("describe", "描述；形容", "verb_action", 1, "high",
        ["explain", "depict", "tell about"], ["design"],
        "Can you describe what happened?", "de(向下)+scrib(写)e→写下来→描述"),
    make_entry("design", "设计；构思", "verb_action", 1, "high",
        ["plan", "create", "draw"], ["desire"],
        "She designed a beautiful dress.", "de(标记)+sign(记号)→做记号→设计"),
    make_entry("develop", "发展；开发", "verb_action", 1, "high",
        ["grow", "improve", "create"], [],
        "China is developing rapidly.", "de(去掉)+velop(包裹)→解开包裹→发展"),
    make_entry("dig", "挖；掘", "verb_action", 1, "medium",
        ["excavate", "bury opposite", "shovel"], ["dog", "big"],
        "Dig a hole for the tree.", "dig=挖掘"),
    make_entry("disappear", "消失；不见", "verb_action", 1, "high",
        ["vanish", "go away", "fade"], [],
        "The sun disappeared behind clouds.", "dis(不)+appear(出现)→不再出现→消失"),
    make_entry("discover", "发现；发觉", "verb_action", 1, "high",
        ["find", "uncover", "realize"], ["recover", "cover"],
        "Columbus discovered America.", "dis(去掉)+cover(盖)→揭开盖子→发现"),
    make_entry("discuss", "讨论；商议", "verb_action", 1, "high",
        ["talk about", "debate", "consider"], ["disgust"],
        "Let's discuss the problem together.", "dis(分散)+cuss(敲)→各抒己见→讨论"),
    make_entry("divide", "分；划分；除", "verb_action", 1, "high",
        ["separate", "split", "share"], ["dividend"],
        "Divide the cake into four pieces.", "di(二)+vid(分割)+e→分成两份"),
    make_entry("double", "加倍；双重", "verb_action", 1, "medium",
        ["twice", "two times", "fold"], ["doubt"],
        "The population doubled in ten years.", "dou(二)+ble→两倍"),
    make_entry("drag", "拖；拉", "verb_action", 1, "medium",
        ["pull", "haul", "tow"], ["drug", "dragon"],
        "Drag the box to the corner.", "drag=拖拽"),
    make_entry("draw", "画；拖；拉；抽取", "verb_action", 1, "high",
        ["sketch", "paint", "pull"], [],
        "I like drawing pictures.", "draw=画画"),
    make_entry("dream", "做梦；梦想", "verb_action", 1, "high",
        ["have dreams", "hope", "imagine"], ["dress"],
        "I dream of becoming a scientist.", "dream=梦想"),
    make_entry("dress", "穿衣服；穿衣", "verb_action", 1, "high",
        ["put on clothes", "wear", "get dressed"], ["press"],
        "Get dressed quickly! We're late.", "dress=穿衣"),
    make_entry("drop", "落下；降低；放弃", "verb_action", 1, "high",
        ["fall", "lower", "abandon"], ["drove"],
        "Don't drop the glass!", "drop=掉落"),
    make_entry("earn", "赚得；挣得", "verb_action", 1, "high",
        ["get money", "gain", "deserve"], ["earnest", "earth"],
        "He earns a lot of money.", "earn=赚取"),
    make_entry("elect", "选举；推选", "verb_action", 1, "medium",
        ["choose", "vote for", "pick"], ["elegant"],
        "We elected him as class monitor.", "e(出)+lect(选)→选出来→选举"),
    make_entry("encourage", "鼓励；激励", "verb_action", 1, "high",
        ["support", "inspire", "urge"], ["courage", "encounter"],
        "Teachers encourage us to ask questions.", "en(使)+cour(心)+age→给勇气→鼓励"),
    make_entry("enter", "进入；加入", "verb_action", 1, "high",
        ["go in", "join", "start"], ["inter", "entire"],
        "Please enter quietly.", "enter=进入"),
    make_entry("escape", "逃跑；逃脱", "verb_action", 1, "medium",
        ["run away", "get free", "flee"], ["escalate", "estate"],
        "The bird escaped from the cage.", "es(出)+cape(斗篷)→脱下伪装→逃走"),
    make_entry("examine", "检查；审查", "verb_action", 1, "high",
        ["check", "inspect", "test"], ["example"],
        "The doctor examined me carefully.", "ex(出)+amine(检视)→仔细查看"),
    make_entry("exchange", "交换；兑换", "verb_action", 1, "medium",
        ["swap", "trade", "change"], ["excite", "change"],
        "Let's exchange gifts.", "ex(出)+change(换)→换出去→交换"),
    make_entry("exist", "存在；生存", "verb_state", 1, "medium",
        ["be", "live", "occur"], ["exit", "expect"],
        "Does life exist on other planets?", "ex(出)+ist(站)→站着→存在"),
    make_entry("expect", "期待；预料", "verb_action", 1, "high",
        ["anticipate", "hope for", "look forward to"], ["except", "expert"],
        "I expect to finish by Friday.", "ex(向外)+spect(看)→向外看→期待"),
    make_entry("explain", "解释；说明", "verb_action", 1, "high",
        ["make clear", "clarify", "describe"], ["explore", "explode"],
        "Can you explain this rule?", "ex(出)+plain(平整)→摊平→讲清楚→解释"),
    make_entry("explore", "探索；探测", "verb_action", 1, "medium",
        ["investigate", "search", "discover"], [],
        "Scientists explore outer space.", "ex(出)+plo(大声呼喊)+re→向外呼喊→探寻"),
    make_entry("express", "表达；表示", "verb_action", 1, "high",
        ["show", "state", "convey"], ["extra", "expect"],
        "I can't express how grateful I am.", "ex(出)+press(压)→挤压出来→表达感情"),
    make_entry("fail", "失败；不及格", "verb_action", 1, "high",
        ["not succeed", "lose", "be unsuccessful"], ["fall", "feel"],
        "Don't be afraid to fail.", "fail=失败"),
    make_entry("feed", "喂养；饲养", "verb_action", 1, "high",
        ["give food", "nourish", "raise"], ["feel", "feet"],
        "Please feed the cat.", "feed=喂食"),
    make_entry("fetch", "取来；接来", "verb_action", 1, "medium",
        ["go get", "bring back", "retrieve"], ["stretch"],
        "Fetch me some water, please.", "fetch=去拿来"),
    make_entry("fill", "填满；装满", "verb_action", 1, "high",
        ["make full", "occupy", "load"], ["full", "file"],
        "Fill in the form, please.", "fill=填充"),
    make_entry("fix", "修理；安装；固定", "verb_action", 1, "high",
        ["repair", "mend", "settle"], ["fox", "six"],
        "Can you fix my bike?", "fix=修理"),
    make_entry("float", "漂浮；浮动", "verb_action", 1, "medium",
        ["stay on water", "drift", "bob"], ["flat", "fleet"],
        "Wood floats on water.", "float=漂浮"),
    make_entry("flow", "流动；涌出", "verb_action", 1, "medium",
        ["stream", "run", "move smoothly"], ["flower"],
        "Water flows down the river.", "flow=流"),
    make_entry("fold", "折叠；合拢", "verb_action", 1, "medium",
        ["bend", "crease", "wrap"], ["folk", "hold"],
        "Fold the paper in half.", "fold=折叠"),
    make_entry("force", "强迫；迫使", "verb_action", 1, "high",
        ["make", "compel", "push"], ["fork", "forth"],
        "Don't force me to do it.", "forc(强)+e→强行推动"),
    make_entry("forgive", "原谅；宽恕", "verb_action", 1, "high",
        ["pardon", "excuse", "let go"], ["forget"],
        "I forgive you for your mistake.", "for(给予)+giv(给)+e→给予宽恕"),
    make_entry("freeze", "冻结；凝固", "verb_action", 1, "medium",
        ["turn to ice", "become solid", "stop"], ["frees"],
        "Water freezes at zero degrees.", "freeze=结冰"),
    make_entry("frighten", "使惊吓；吓唬", "verb_action", 1, "medium",
        ["scare", "terrify", "shock"], [],
        "Loud noises frighten the baby.", "fright(恐惧)+en→使恐惧"),
    make_entry("gather", "聚集；收集", "verb_action", 1, "high",
        ["collect", "assemble", "come together"], ["together"],
        "Gather around, everyone!", "gather=聚集"),
    make_entry("glue", "粘合；胶水", "verb_action", 1, "medium",
        ["stick", "paste", "attach"], ["blue", "clue"],
        "Glue the paper to the board.", "glue=胶水/粘贴"),
    make_entry("guess", "猜测；推测", "verb_action", 1, "high",
        ["estimate", "predict", "suppose"], ["guest", "guide"],
        "Guess what I got for my birthday!", "guess=猜"),
    make_entry("hang", "悬挂；吊", "verb_action", 1, "high",
        ["suspend", "put up", "attach"], ["hand"],
        "Hang your coat on the hook.", "hang=挂"),
    make_entry("hate", "憎恨；讨厌", "verb_action", 1, "high",
        ["dislike", "loathe", "detest"], ["hat", "had"],
        "I hate getting up early.", "hate=讨厌"),
    make_entry("heat", "加热；使变热", "verb_action", 1, "medium",
        ["warm up", "make hot", "cook"], ["heart", "eat"],
        "Heat the milk before drinking.", "heat=加热"),
    make_entry("hide", "躲藏；隐藏；隐瞒", "verb_action", 1, "high",
        ["conceal", "cover", "put away"], ["hid", "ride"],
        "Where did you hide my book?", "hide=藏"),
    make_entry("hit", "击打；撞击；命中", "verb_action", 1, "high",
        ["strike", "beat", "knock"], ["hat", "hot"],
        "The ball hit the window.", "hit=击中"),
    make_entry("hold", "握住；拿着；举办", "verb_action", 1, "high",
        ["grasp", "carry", "organize"], ["old", "cold"],
        "Hold my hand, please.", "hold=握住"),
    make_entry("hunt", "狩猎；搜寻", "verb_action", 1, "medium",
        ["search for", "chase", "seek"], ["hurt", "hint"],
        "Dogs hunt for rabbits.", "hunt=寻找/打猎"),
    make_entry("hurry", "匆忙；赶紧", "verb_action", 1, "high",
        ["rush", "speed up", "be quick"], ["happy"],
        "Hurry up! The bus is coming.", "hurry=赶快"),
    make_entry("identify", "识别；确认身份", "verb_action", 1, "medium",
        ["recognize", "point out", "name"], [],
        "Can you identify this bird?", "identi(同一)+fy→认出是同一个→确认"),
    make_entry("ignore", "忽视；不理睬", "verb_action", 1, "high",
        ["pay no attention to", "disregard", "overlook"], ["ignorant"],
        "Don't ignore the rules.", "ig(不)+nor(知道)+e→假装不知道→无视"),
    make_entry("imagine", "想象；设想", "verb_action", 1, "high",
        ["picture", "visualize", "suppose"], ["image", "magic"],
        "Can you imagine life without phones?", "imag(形象)+ine→在脑中形成形象"),
    make_entry("improve", "改善；提高；进步", "verb_action", 1, "high",
        ["make better", "enhance", "develop"], ["impress"],
        "You need to improve your pronunciation.", "im(向内)+prov(试用)+e→试着做得更好→改进"),
    make_entry("include", "包含；包括", "verb_action", 1, "high",
        ["contain", "involve", "have"], ["increase"],
        "The tour includes lunch and dinner.", "in(向内)+clude(关闭)→关在里面→包含"),
    make_entry("increase", "增加；增长", "verb_action", 1, "high",
        ["grow", "rise", "expand"], [],
        "The population increases every year.", "in(向内)+cre(生长)+ase→往里生长→增加"),
    make_entry("influence", "影响；对起作用", "verb_action", 1, "medium",
        ["affect", "impact", "shape"], [],
        "Parents influence their children greatly.", "in(流入)+flu(流)+ence→流入→产生影响"),
    make_entry("introduce", "介绍；引进", "verb_action", 1, "high",
        ["present", "bring in", "acquaint"], ["produce", "reduce"],
        "Let me introduce myself.", "intro(向内)+duce(引)→引入→介绍"),
    make_entry("invite", "邀请；招待", "verb_action", 1, "high",
        ["ask someone", "welcome", "request presence"], ["invent", "invest"],
        "She invited me to her party.", "in(向内)+vit(生命)+e→请进生命→邀请"),
    make_entry("join", "参加；加入；连接", "verb_action", 1, "high",
        ["take part in", "become member", "connect"], ["joy"],
        "I joined the basketball club.", "join=加入"),
    make_entry("judge", "判断；评判；审判", "verb_action", 1, "medium",
        ["evaluate", "decide", "assess"], ["just", "juggle"],
        "Don't judge a book by its cover.", "judg(判断)+e→做出判断"),
    make_entry("kick", "踢", "verb_action", 1, "high",
        ["strike with foot", "boot", "soccer"], ["pick", "lick"],
        "Don't kick the ball in the house.", "kick=踢"),
    make_entry("knock", "敲；击；撞", "verb_action", 1, "high",
        ["hit", "strike", "tap"], ["know", "none"],
        "Someone is knocking at the door.", "knock=敲门"),
    make_entry("lack", "缺乏；没有", "verb_action", 1, "medium",
        ["need", "be short of", "without"], ["luck", "lock"],
        "They lack enough money for travel.", "lack=缺少"),
    make_entry("last", "持续；维持", "verb_action", 1, "high",
        ["continue", "remain", "go on"], ["lost"],
        "The meeting lasted three hours.", "last=持续"),
    make_entry("laugh", "大笑；发笑", "verb_action", 1, "high",
        ["giggle", "chuckle", "smile"], ["launch", "taught"],
        "His joke made everyone laugh.", "laugh=笑"),
    make_entry("lead", "领导；带领；通向", "verb_action", 1, "high",
        ["guide", "direct", "head"], ["leaf", "lean"],
        "Who will lead the team?", "lead=带领"),
    make_entry("lean", "倾斜；依靠", "verb_action", 1, "medium",
        ["tilt", "rest against", "slant"], ["learn"],
        "Don't lean on the door.", "lean=倚靠"),
    make_entry("lend", "借出；借给", "verb_action", 1, "high",
        ["give temporarily", "loan (opposite borrow)"], ["land", "send"],
        "Can you lend me your dictionary?", "lend=借出"),
    make_entry("lift", "举起；抬起；电梯", "verb_action", 1, "high",
        ["raise", "pick up", "elevator"], ["left", "list"],
        "Can you help me lift this box?", "lift=抬起"),
    make_entry("limit", "限制；限定", "verb_action", 1, "high",
        ["restrict", "control", "set bounds"], ["lit"],
        "Please limit your talk to five minutes.", "limi(界限)+it→划定界限"),
    make_entry("lock", "锁上；锁定", "verb_action", 1, "medium",
        ["secure", "fasten", "bolt"], ["look", "luck"],
        "Don't forget to lock the door.", "lock=锁门"),
]

NEW_WORDS.extend(P2_VERBS_AL)
print(f"P2 高频动词A-L: {len(P2_VERBS_AL)} 词")

# ============================================================
# P2: 中考高频动词 M-Z (~150词)
# ============================================================
P2_VERBS_MZ = [
    make_entry("manage", "管理；设法做到", "verb_action", 1, "high",
        ["handle", "control", "succeed in"], ["manager", "message"],
        "How do you manage your time?", "man(手)+age→用手操作→管理"),
    make_entry("marry", "结婚；嫁娶", "verb_action", 1, "high",
        ["wed", "get married", "take as spouse"], ["merry", "worry"],
        "They got married last year.", "marry=结婚"),
    make_entry("matter", "要紧；有关系；物质", "verb_action", 1, "high",
        ["be important", "count", "signify"], ["master"],
        "It doesn't matter. Don't worry.", "matter=重要/事情"),
    make_entry("measure", "测量；衡量；措施", "verb_action", 1, "high",
        ["gauge", "calculate", "assess"], ["treasure", "pleasure"],
        "Measure the length of the table.", "measur(测量)+e→量度"),
    make_entry("mention", "提到；提及", "verb_action", 1, "high",
        ["refer to", "speak of", "note"], ["mental"],
        "Did he mention where he was going?", "ment(思想)+ion→提起想法→提及"),
    make_entry("mind", "介意；注意；头脑", "verb_action", 1, "high",
        ["care about", "object to", "brain"], ["mine", "find"],
        "Do you mind if I open the window?", "mind=介意"),
    make_entry("mix", "混合；混淆", "verb_action", 1, "high",
        ["combine", "blend", "stir"], ["milk", "much"],
        "Mix the flour and eggs together.", "mix=混合"),
    make_entry("move", "移动；搬家；感动", "verb_action", 1, "high",
        ["shift", "change place", "touch"], ["movie"],
        "Let's move the table to the corner.", "move=移动"),
    make_entry("nod", "点头；打瞌睡", "verb_action", 1, "medium",
        ["shake head yes", "signal agreement", "doze"], ["god", "not"],
        "She nodded when I asked.", "nod=点头"),
    make_entry("notice", "注意到；察觉", "verb_action", 1, "high",
        ["see", "observe", "become aware"], ["notable", "nation"],
        "Did you notice anything strange?", "not(知)+ice→知道了→注意到"),
    make_entry("obey", "服从；遵守", "verb_action", 1, "high",
        ["follow", "listen to", "comply with"], ["object"],
        "Students should obey school rules.", "ob(加强)+ey(听)→听进去→服从"),
    make_entry("operate", "操作；运转；做手术", "verb_action", 1, "medium",
        ["run", "work", "perform surgery"], ["operation"],
        "Doctors operate on patients.", "oper(工作)+ate→进行操作"),
    make_entry("organize", "组织；安排", "verb_action", 1, "high",
        ["arrange", "plan", "set up"], ["origin"],
        "Who organized this event?", "org(器官)+an+ize→使成整体→组织"),
    make_entry("own", "拥有；承认", "verb_action", 1, "high",
        ["have", "possess", "acknowledge"], ["owe", "town"],
        "She owns a big house.", "own=拥有"),
    make_entry("pack", "打包；收拾行李", "verb_action", 1, "medium",
        ["put in bag", "load", "bundle"], ["back", "pick"],
        "Pack your bags for the trip.", "pack=打包"),
    make_entry("paint", "绘画；油漆；涂料", "verb_action", 1, "high",
        ["draw", "color", "coat"], ["point", "print"],
        "She paints beautiful pictures.", "paint=绘画/刷漆"),
    make_entry("panic", "恐慌；惊慌", "verb_action", 1, "medium",
        ["freak out", "be terrified", "alarm"], ["picnic", "panel"],
        "Don't panic! Stay calm.", "panic=惊慌"),
    make_entry("park", "停车；公园", "verb_action", 1, "high",
        ["stop vehicle", "garden", "place"], ["dark", "mark"],
        "You can't park here.", "park=停车"),
    make_entry("pause", "暂停；中止", "verb_action", 1, "medium",
        ["stop briefly", "hesitate", "break"], ["cause"],
        "Pause the video, please.", "pause=暂停"),
    make_entry("perform", "表演；执行；表现", "verb_action", 1, "high",
        ["act", "do", "carry out"], ["perfect", "perhaps"],
        "They performed a play at school.", "per(通过)+form(形态)→通过某种形式展示→表演"),
    make_entry("persuade", "说服；劝说", "verb_action", 1, "medium",
        ["convince", "talk into", "win over"], ["pursue"],
        "I persuaded him to come with me.", "per(彻底)+suade(劝导)→彻底劝服"),
    make_entry("pick", "挑选；采摘；拾起", "verb_action", 1, "high",
        ["choose", "select", "gather"], ["pink", "kick"],
        "Pick your favorite color.", "pick=挑选"),
    make_entry("place", "放置；安置", "verb_action", 1, "high",
        ["put", "set", "position"], ["plane", "plan"],
        "Place the book on the desk.", "place=放置"),
    make_entry("point", "指向；指出", "verb_action", 1, "high",
        ["indicate", "show", "aim"], ["paint", "print"],
        "Point to the correct answer.", "point=指出"),
    make_entry("pour", "倒；倾泻；灌注", "verb_action", 1, "medium",
        ["flow", "stream", "empty"], ["poor", "four"],
        "Pour some juice into the glass.", "pour=倒"),
    make_entry("pray", "祈祷；恳求", "verb_action", 1, "medium",
        ["wish", "hope deeply", "beg"], ["prey", "play"],
        "Pray for good weather tomorrow.", "pray=祈祷"),
    make_entry("prepare", "准备；预备", "verb_action", 1, "high",
        ["get ready", "make arrangements", "plan"], ["presence"],
        "Prepare well for the exam.", "pre(前)+par(准备)+e→提前准备好"),
    make_entry("pretend", "假装；佯装", "verb_action", 1, "medium",
        ["make believe", "act", "fake"], ["pretty", "prevent"],
        "Don't pretend you didn't hear.", "pre(前面)+tend(伸展)→伸到面前→假装"),
    make_entry("prevent", "防止；预防；阻止", "verb_action", 1, "high",
        ["stop", "avoid", "hinder"], ["present"],
        "Wash hands to prevent illness.", "pre(前)+vent(来)→提前来到→预防"),
    make_entry("promise", "承诺；答应", "verb_action", 1, "high",
        ["pledge", "vow", "assure"], ["promote", "prompt"],
        "I promise I won't be late again.", "pro(向前)+mise(送)→送出保证→承诺"),
    make_entry("pronounce", "发音；宣布", "verb_action", 1, "high",
        ["say", "utter", "articulate"], [],
        "How do you pronounce this word?", "pro(向前)+nounc(宣告)+e→发出声音→发音"),
    make_entry("protect", "保护；防护", "verb_action", 1, "high",
        ["guard", "defend", "keep safe"], ["project", "protest"],
        "Wear a hat to protect from the sun.", "pro(前)+tect(覆盖)→提前盖上→保护"),
    make_entry("prove", "证明；证实", "verb_action", 1, "medium",
        ["show", "demonstrate", "confirm"], ["provide"],
        "Facts prove that he is innocent.", "prov(试探)+e→验证→证明"),
    make_entry("pull", "拉；拖；拔", "verb_action", 1, "high",
        ["drag", "draw", "tug"], ["push", "pool"],
        "Pull the door open.", "pull=拉"),
    make_entry("punish", "惩罚；处罚", "verb_action", 1, "medium",
        ["penalize", "discipline"], ["publish", "push"],
        "The teacher punished him for cheating.", "pun(惩罚)+ish→施加惩罚"),
    make_entry("push", "推；按；促进", "verb_action", 1, "high",
        ["shove", "press", "urge"], ["push"],
        "Push the door to open it.", "push=推"),
    make_entry("raise", "举起；提高；筹集；抚养", "verb_action", 1, "high",
        ["lift", "increase", "collect money"], ["rise", "rase"],
        "Raise your hand if you know.", "raise=举起/提高"),
    make_entry("reach", "到达；伸手；联系", "verb_action", 1, "high",
        ["arrive at", "extend hand", "contact"], ["read", "react"],
        "We reached the top of the mountain.", "reach=到达"),
    make_entry("realize", "意识到；实现", "verb_action", 1, "high",
        ["understand become aware", "achieve", "recognize"], ["really"],
        "I realized I forgot my homework.", "real(真实)+ize→变为现实→意识到"),
    make_entry("receive", "收到；接到；接待", "verb_action", 1, "high",
        ["get", "accept", "welcome"], ["believe", "relieve"],
        "I received a letter from my friend.", "re(回)+ceiv(拿)+e→拿回来→收到"),
    make_entry("recognize", "辨认出；承认；认可", "verb_action", 1, "high",
        ["identify", "know again", "acknowledge"], ["recommend"],
        "I recognized him from his voice.", "re(再)+cogn(知道)+ize→再次知道→认出"),
    make_entry("record", "记录；录音", "verb_action", 1, "high",
        ["write down", "tape", "register"], ["regard", "recover"],
        "Please record the meeting.", "re(再)+cord(心)→再次用心记下"),
    make_entry("reduce", "减少；缩小", "verb_action", 1, "high",
        ["decrease", "lessen", "cut"], ["reuse", "produce"],
        "We should reduce plastic waste.", "re(回)+duc(引)+e→引回去→减少"),
    make_entry("refuse", "拒绝；回绝", "verb_action", 1, "high",
        ["decline", "reject", "say no"], ["reuse"],
        "He refused my invitation.", "re(回)+fuse(倾倒)→倒回去→拒绝"),
    make_entry("regard", "视为；看待；问候", "verb_action", 1, "medium",
        ["consider", "view as", "think of"], ["regardless"],
        "I regard him as my best friend.", "re(再)+gard(注视)→反复注视→重视"),
    make_entry("regret", "后悔；遗憾；惋惜", "verb_action", 1, "medium",
        ["feel sorry", "rue", "lament"], ["great", "retreat"],
        "I regret not studying harder.", "re(再)+gret(哭)→再次哭泣→后悔"),
    make_entry("reject", "拒绝；驳回；丢弃", "verb_action", 1, "medium",
        ["refuse", "turn down", "discard"], ["rejoice", "relax"],
        "His application was rejected.", "re(回)+ject(扔)→扔回去→拒绝"),
    make_entry("relax", "放松；休息", "verb_action", 1, "high",
        ["rest", "unwind", "calm down"], ["relay", "release"],
        "Music helps me relax.", "re(再)+lax(松)→再次放松→休息"),
    make_entry("remain", "保持；仍然；留下", "verb_action", 1, "high",
        ["stay", "continue to be", "left"], ["remark"],
        "Please remain seated.", "re(再)+main(留)→继续留下→保持"),
    make_entry("remember", "记得；记住；回忆", "verb_action", 1, "high",
        ["recall", "keep in mind", "not forget"], ["member"],
        "Remember to lock the door.", "re(再)+memor(记忆)+er→再次记忆→记住"),
    make_entry("remind", "提醒；使想起", "verb_action", 1, "high",
        ["make remember", "prompt", "nudge"], ["mind"],
        "Remind me to call Mom.", "re(再)+mind(想)→再次想到→提醒"),
    make_entry("remove", "移开；去除；开除", "verb_action", 1, "high",
        ["take away", "eliminate", "delete"], ["rename", "renew"],
        "Remove your shoes before entering.", "re(再)+move(移动)→再次移开→去除"),
    make_entry("rent", "租用；出租", "verb_action", 1, "medium",
        ["hire", "lease", "let"], ["sent", "rant"],
        "They rent an apartment near school.", "rent=租"),
    make_entry("replace", "代替；替换；放回原处", "verb_action", 1, "high",
        ["substitute", "take place of", "change"], ["reply", "replay"],
        "Nothing can replace family.", "re(回)+place(位置)→放回原位→替代"),
    make_entry("require", "需要；要求；规定", "verb_action", 1, "high",
        ["need", "demand", "ask for"], ["acquire", "inquire"],
        "This task requires patience.", "re(反复)+quir(寻求)+e→反复索求→要求"),
    make_entry("respect", "尊重；尊敬", "verb_action", 1, "high",
        ["honor", "admire", "value"], ["inspect", "expect"],
        "We should respect our elders.", "re(再)+spect(看)→反复看→敬重"),
    make_entry("respond", "回答；回应；反应", "verb_action", 1, "medium",
        ["answer", "reply", "react"], ["response", "responsible"],
        "He didn't respond to my message.", "re(回)+spond(承诺)→回应承诺→答复"),
    make_entry("rest", "休息；剩余；倚靠", "verb_action", 1, "high",
        ["relax", "sleep", "remaining"], ["test", "best"],
        "Let's rest for a while.", "rest=休息"),
    make_entry("return", "返回；归还；回报", "verb_action", 1, "high",
        ["go back", "give back", "come back"], ["retain"],
        "When will you return home?", "re(回)+turn(转)→转回来→返回"),
    make_entry("ride", "骑；乘坐", "verb_action", 1, "high",
        ["cycle", "travel on", "sit on"], ["rise", "ripe"],
        "I ride my bike to school.", "ride=骑车"),
    make_entry("risk", "冒险；冒的风险", "verb_action", 1, "medium",
        ["danger", "chance", "gamble"], ["disk", "brisk"],
        "Don't risk your safety.", "risk=冒险"),
    make_entry("roll", "滚动；卷；摇摆", "verb_action", 1, "medium",
        ["turn", "rotate", "wrap"], ["rule", "role"],
        "The ball rolled down the hill.", "roll=滚动"),
    make_entry("rub", "摩擦；揉搓", "verb_action", 1, "medium",
        ["scrub", "wipe", "massage"], ["rob", "rib"],
        "Rub your hands together to stay warm.", "rub=摩擦"),
    make_entry("satisfy", "使满意；满足", "verb_action", 1, "high",
        ["please", "meet needs", "fulfill"], ["satisfied"],
        "This result satisfies me.", "satis(足够)+fy→足够了→满足"),
    make_entry("save", "节省；拯救；保存", "verb_action", 1, "high",
        ["keep", "rescue", "store"], ["safe", "same"],
        "Save water every day.", "save=节约/保存"),
    make_entry("scan", "扫描；浏览；细看", "verb_action", 1, "medium",
        ["look over", "skim", "examine"], ["skin", "span"],
        "Scan the document for errors.", "scan=扫描"),
    make_entry("search", "搜索；搜寻；探究", "verb_action", 1, "high",
        ["look for", "seek", "hunt"], ["research"],
        "Search for the answer online.", "search=搜索"),
    make_entry("shake", "摇动；握手；发抖", "verb_action", 1, "high",
        ["move quickly", "tremble", "shiver"], ["shape", "shade"],
        "Shake the bottle before drinking.", "shake=摇动"),
    make_entry("share", "分享；分担；共有", "verb_action", 1, "high",
        ["give part", "divide", "distribute"], ["shave", "shape"],
        "Share your toys with your brother.", "share=分享"),
    make_entry("shine", "照耀；发光；擦亮", "verb_action", 1, "medium",
        ["glow", "beam", "polish"], ["shin", "chine"],
        "The sun shines brightly today.", "shine=照耀"),
    make_entry("shoot", "射击；拍摄；发芽", "verb_action", 1, "medium",
        ["fire", "take photo", "grow"], ["shot", "shout"],
        "Don't shoot at birds.", "shoot=射/拍照"),
    make_entry("shout", "大喊；呼叫", "verb_action", 1, "high",
        ["yell", "call out loudly", "scream"], ["shoot", "short"],
        "Don't shout in the library.", "shout=大喊"),
    make_entry("shut", "关闭；合上", "verb_action", 1, "high",
        ["close", "slam", "lock"], ["shirt", "short"],
        "Shut the door, please.", "shut=关"),
    make_entry("sign", "签名；打手势；示意", "verb_action", 1, "high",
        ["write name", "gesture", "signal"], ["sing", "sin"],
        "Sign your name here.", "sign=签名"),
    make_entry("skip", "跳过；遗漏；跳绳", "verb_action", 1, "medium",
        ["omit", "miss", "jump"], ["skin", "ship"],
        "Don't skip breakfast.", "skip=跳过"),
    make_entry("slide", "滑动；滑落；幻灯片", "verb_action", 1, "medium",
        ["glide", "slip", "move smoothly"], ["slight"],
        "The kids slide down the hill.", "slide=滑"),
    make_entry("slip", "滑倒；溜走；纸条", "verb_action", 1, "medium",
        ["slide", "fall", "sneak"], ["sleep"],
        "Be careful not to slip on ice.", "slip=滑倒"),
    make_entry("solve", "解决；解答；处理", "verb_action", 1, "high",
        ["resolve", "work out", "find answer"], ["solved"],
        "Can you solve this math problem?", "solv(松开)+e→解开→解决"),
    make_entry("sort", "分类；整理；种类", "verb_action", 1, "medium",
        ["arrange", "organize", "type"], ["short", "shot"],
        "Sort the cards by color.", "sort=分类"),
    make_entry("spread", "传播；展开；涂；蔓延", "verb_action", 1, "high",
        ["extend", "scatter", "open out"], ["spray", "spring"],
        "Spread the news to everyone.", "spread=传播/展开"),
    make_entry("stand", "站立；忍受；位于", "verb_action", 1, "high",
        ["be upright", "endure", "bear"], ["strand", "stamp"],
        "Please stand up.", "stand=站立"),
    make_entry("steal", "偷；窃取", "verb_action", 1, "medium",
        ["take without permission", "rob", "thieve"], ["steel"],
        "Someone stole my wallet.", "steal=偷"),
    make_entry("stick", "刺；粘贴；坚持；棍子", "verb_action", 1, "high",
        ["attach", "adhere", "poke"], ["strict", "strike"],
        "Stick the note on the fridge.", "stick=粘贴/坚持"),
    make_entry("stress", "强调；使紧张；压力", "verb_action", 1, "medium",
        ["emphasize", "worry", "pressure"], ["street", "strict"],
        "Don't stress about the exam.", "stress=强调/压力"),
    make_entry("suit", "适合；合身；套装", "verb_action", 1, "medium",
        ["fit", "match", "become"], ["suite", "shit"],
        "This color suits you.", "suit=适合"),
    make_entry("support", "支持；支撑；养活", "verb_action", 1, "high",
        ["help", "back up", "hold up"], ["sport", "suppress"],
        "Family always supports me.", "sup(下面)+port(拿)→从下面托住→支撑"),
    make_entry("surprise", "使吃惊；使意外", "verb_action", 1, "high",
        ["shock", "amaze", "astonish"], ["suppress", "suppose"],
        "The news surprised everyone.", "sur(超)+pris(抓)+e→超乎预期抓住→惊讶"),
    make_entry("surround", "包围；环绕", "verb_action", 1, "medium",
        ["encircle", "enclose", "go around"], [],
        "Mountains surround the village.", "sur(周围)+round(圆圈)→围一圈→包围"),
    make_entry("survive", "幸存；存活；挺过", "verb_action", 1, "medium",
        ["live through", "stay alive", "endure"], ["survey", "survival"],
        "Few survived the accident.", "sur(超)+viv(活)+e→活下来→幸存"),
    make_entry("suspect", "怀疑；猜想", "verb_action", 1, "medium",
        ["doubt", "guess", "question"], ["expect", "inspect"],
        "I suspect he is lying.", "sus(下)+pect(看)→从下面看→怀疑"),
    make_entry("switch", "转换；开关；交换", "verb_action", 1, "medium",
        ["change", "toggle", "exchange"], ["which", "witch"],
        "Switch off the light when you leave.", "switch=切换/开关"),
    make_entry("tear", "撕破；撕裂；眼泪", "verb_action", 1, "medium",
        ["rip", "split", "pull apart"], ["tier", "rear"],
        "Don't tear the paper.", "tear=撕"),
    make_entry("tie", "系；捆绑；打平", "verb_action", 1, "high",
        ["bind", "knot", "equal score"], ["time", "tire"],
        "Tie your shoelaces.", "tie=系"),
    make_entry("tip", "给小费；倾斜；尖端；提示", "verb_action", 1, "medium",
        ["give gratuity", "tilt", "point"], ["tape", "top"],
        "Don't forget to tip the waiter.", "tip=小费/尖端"),
    make_entry("trade", "贸易；交易；交换", "verb_action", 1, "medium",
        ["exchange", "business", "deal"], ["tradition", "travel"],
        "Countries trade goods with each other.", "trade=交易/贸易"),
    make_entry("translate", "翻译；转化", "verb_action", 1, "medium",
        ["convert language", "interpret", "change"], ["transport", "transform"],
        "Can you translate this sentence?", "trans(转)+lat(搬)+e→搬运语言→翻译"),
    make_entry("treat", "对待；治疗；款待；请客", "verb_action", 1, "high",
        ["handle", "cure", "entertain"], ["threat", "great"],
        "Treat others as you want to be treated.", "treat=对待/治疗"),
    make_entry("trust", "信任；相信；信赖", "verb_action", 1, "high",
        ["believe in", "rely on", "have faith"], ["true", "truth"],
        "I trust you completely.", "trust=信任"),
    make_entry("turn", "转动；变成；轮流", "verb_action", 1, "high",
        ["rotate", "change", "become"], ["burn", "tune"],
        "Turn left at the corner.", "turn=转弯"),
    make_entry("type", "打字；类型；典型", "verb_action", 1, "medium",
        ["keyboard input", "kind", "category"], ["tape", "top"],
        "Type your essay on the computer.", "type=打字"),
    make_entry("warn", "警告；告诫；预先通知", "verb_action", 1, "high",
        ["caution", "alert", "advise"], ["war", "want"],
        "The doctor warned him not to smoke.", "war(注意)+n→引起注意→警告"),
    make_entry("wave", "挥手；波浪；波动", "verb_action", 1, "medium",
        ["signal with hand", "fluctuate", "swing"], ["waive", "way"],
        "Wave goodbye to your friend.", "wave=挥手/波动"),
    make_entry("weigh", "称重；权衡；重", "verb_action", 1, "medium",
        ["measure weight", "consider", "have mass"], ["wheel", "wheat"],
        "Weigh yourself on the scale.", "weigh=称重"),
    make_entry("whisper", "低语；耳语；秘密地说", "verb_action", 1, "medium",
        ["speak softly", "murmur", "secret talk"], [],
        "Don't whisper in class.", "whisper=耳语"),
    make_entry("wonder", "想知道；纳闷；奇迹", "verb_action", 1, "high",
        ["curious", "ask oneself", "marvel"], ["wander", "wound"],
        "I wonder why he didn't come.", "won(想)+der→想知道"),
    make_entry("worry", "担心；担忧；烦恼", "verb_action", 1, "high",
        ["be anxious", "concern", "fret"], ["sorry"],
        "Don't worry about the test.", "worry=担心"),
    make_entry("wrap", "包；裹；缠绕", "verb_action", 1, "medium",
        ["cover", "enclose", "coil around"], ["rap", "crap"],
        "Wrap the gift nicely.", "wrap=包装/包裹"),
    make_entry("graduate", "毕业", "verb_action", 1, "medium",
        ["finish school", "get degree", "complete"], ["grade", "gradual"],
        "She graduated from high school last year.", "gradu(步)+ate→完成学业步伐→毕业"),
    make_entry("admit", "承认；准许进入", "verb_action", 1, "medium",
        ["confess", "acknowledge", "allow in"], ["permit", "commit"],
        "He admitted he made a mistake.", "ad(向)+mit(送)→送到大家面前→承认"),
    make_entry("warn", "警告；告诫", "verb_action", 1, "high",
        ["caution", "alert", "advise"], ["warm", "wear"],
        "The teacher warned us not to cheat.", "warn=警告"),
    make_entry("attract", "吸引；引起", "verb_action", 1, "medium",
        ["draw", "interest", "pull"], ["track", "attack"],
        "The colorful display attracted many visitors.", "at(向)+tract(拉)→拉过来→吸引"),
    make_entry("blend", "混合；融合", "verb_action", 1, "medium",
        ["mix", "combine", "merge"], ["bend", "blind"],
        "Blend the milk and eggs together.", "blend=混合"),
    make_entry("brush", "刷；擦", "verb_action", 1, "high",
        ["scrub", "clean with brush", "paint"], ["rush", "crush"],
        "Brush your teeth twice a day.", "brush=刷"),
    make_entry("climb", "爬；攀登", "verb_action", 1, "high",
        ["ascend", "scale", "go up"], ["climb", "climb"],
        "We climbed to the top of the hill.", "climb=爬"),
    make_entry("clue", "线索；提示", "noun_common", 1, "medium",
        ["hint", "evidence", "sign"], ["blue", "glue"],
        "The police found an important clue.", "clue=线索"),
    make_entry("coach", "教练；指导", "verb_action", 1, "medium",
        ["train", "instruct", "teach"], ["couch", "poach"],
        "The coach trained the team every day.", "coach=教练/指导"),
    make_entry("compete", "竞争；比赛", "verb_action", 1, "medium",
        ["rival", "contest", "fight"], ["complete", "compete"],
        "Students compete for the scholarship.", "com(共同)+pet(追求)+e→共同追求→竞争"),
    make_entry("complain", "抱怨；投诉", "verb_action", 1, "medium",
        ["protest", "grumble", "object"], ["explain", "complain"],
        "She complained about the food.", "com(加强)+plain(抱怨)→加强抱怨"),
    make_entry("confuse", "使困惑；混淆", "verb_action", 1, "medium",
        ["puzzle", "mix up", " bewilder"], ["confuse"],
        "The question confused many students.", "con(共同)+fuse(倒)→倒在一起→困惑"),
    make_entry("consist", "由…组成；在于", "verb_state", 1, "medium",
        ["be made of", "be composed of", "include"], ["assist", "exist"],
        "The team consists of ten players.", "con(共同)+sist(站立)→站在一起→组成"),
    make_entry("construct", "建造；构建", "verb_action", 1, "medium",
        ["build", "create", "form"], ["instruct", "construct"],
        "They constructed a new bridge.", "con(共同)+struct(建造)→共同构建→建造"),
    make_entry("consume", "消耗；消费；吃光", "verb_action", 1, "medium",
        ["use up", "eat", "drink"], ["assume", "presume"],
        "This car consumes a lot of fuel.", "con(共同)+sum(拿)+e→全部拿走→消耗"),
    make_entry("contribute", "贡献；捐助；导致", "verb_action", 1, "medium",
        ["donate", "give", "add"], ["distribute", "attribute"],
        "Everyone can contribute to the project.", "con(共同)+tribute(给予)→共同给予→贡献"),
    make_entry("converse", "交谈；谈话", "verb_action", 1, "low",
        ["talk", "chat", "discuss"], ["converse", "reverse"],
        "They conversed in English.", "con(共同)+verse(转)→来回转动→交谈"),
    make_entry("cooperate", "合作；配合", "verb_action", 1, "medium",
        ["work together", "collaborate", "team up"], ["coordinate"],
        "All countries should cooperate to fight pollution.", "co(共同)+oper(工作)+ate→共同工作→合作"),
    make_entry("correspond", "通信；符合；相当于", "verb_action", 1, "low",
        ["write letters", "match", "equal"], ["respond", "correspond"],
        "They corresponded with each other for years.", "cor(共同)+respond(回应)→互应→通信"),
    make_entry("crash", "碰撞；坠毁；崩溃", "verb_action", 1, "medium",
        ["collision", "accident", "bang"], ["crush", "crash"],
        "A car crashed into the tree.", "crash=撞击/崩溃"),
    make_entry("cure", "治愈；治疗；治好", "verb_action", 1, "medium",
        ["heal", "treat", "fix"], ["pure", "sure"],
        "This medicine can cure your cold.", "cure=治愈"),
    make_entry("dare", "敢；胆敢", "verb_action", 1, "medium",
        ["have courage", "venture", "risk"], ["dark", "dare"],
        "I dare not go there alone.", "dare=敢/挑战"),
    make_entry("decline", "下降；衰落；婉拒", "verb_action", 1, "medium",
        ["refuse politely", "decrease", "go down"], ["incline", "include"],
        "He declined the invitation.", "de(向下)+cline(倾斜)→向下滑→衰落/婉拒"),
    make_entry("dedicate", "奉献；致力于", "verb_action", 1, "medium",
        ["devote", "give", "commit"], ["indicate", "dedicate"],
        "She dedicated her life to education.", "de(向下)+dic(说)+ate→宣布献身→奉献"),
    make_entry("define", "定义；规定；使明确", "verb_action", 1, "medium",
        ["explain meaning", "set limits", "describe"], ["refine", "define"],
        "How would you define happiness?", "de(向下)+fin(界限)+e→划定界限→定义"),
    make_entry("delay", "耽搁；延期", "verb_action", 1, "high",
        ["postpone", "put off", "be late"], ["relay"],
        "Don't delay. Start now.", "de(向下)+lay(放)→往后放→延误"),
    make_entry("delight", "使高兴；使欣喜", "verb_action", 1, "medium",
        ["please", "joy", "make happy"], ["delete", "delight"],
        "The gift delighted the child.", "de(加强)+light(光)→心中亮起来→高兴"),
    make_entry("demand", "需求；要求；强令", "verb_action", 1, "medium",
        ["require", "request", "insist"], ["command", "demand"],
        "The job demands patience and skill.", "de(下)+mand(命令)→下令要求→要求"),
    make_entry("deny", "否认；拒绝", "verb_action", 1, "medium",
        ["refuse", "reject", "say not"], ["rely", "deny"],
        "He denied stealing the money.", "de(不)+ny(说)→不说→否认"),
    make_entry("depart", "离开；出发", "verb_action", 1, "low",
        ["leave", "go away", "set off"], ["part", "depart"],
        "The train departs at 8 AM.", "de(离开)+part(分)→分开离开→出发"),
    make_entry("depend", "依靠；取决于", "verb_action", 1, "high",
        ["rely on", "count on", "trust"], ["defend", "spend"],
        "Health depends on good habits.", "de(下)+pend(挂)→挂在下面→依靠"),
    make_entry("deposit", "放置；存放；押金", "verb_action", 1, "medium",
        ["put money in", "store", "leave"], ["posit", "suppose"],
        "Deposit your bag in the locker.", "de(下)+posit(放)→放下→存放"),
    make_entry("depress", "压抑；使沮丧；按下", "verb_action", 1, "low",
        ["sadden", "press down", "reduce"], ["impress", "depress"],
        "The bad news depressed everyone.", "de(向下)+press(压)→往下压→压抑"),
    make_entry("derive", "获得；源于", "verb_action", 1, "low",
        ["obtain", "come from", "originate"], ["drive", "derive"],
        "Many English words derive from Latin.", "de(出)+riv(河)+e→从源头流出→源自"),
    make_entry("deserve", "值得；应得", "verb_action", 1, "medium",
        ["be worthy of", "merit", "earn"], ["serve", "conserve"],
        "You deserve a reward.", "de(加强)+serve(服务)→加强服务→应得回报"),
    make_entry("desire", "渴望；欲望；要求", "verb_action", 1, "medium",
        ["want", "wish", "long for"], ["desire", "design"],
        "I desire to travel around the world.", "desir(想要)+e→非常想要→渴望"),
    make_entry("despair", "绝望；丧失信心", "verb_action", 1, "low",
        ["lose hope", "give up", "be hopeless"], ["repair", "despair"],
        "Never despair in difficult times.", "de(去掉)+spair(希望)→失去希望→绝望"),
    make_entry("destroy", "破坏；摧毁；消灭", "verb_action", 1, "high",
        ["ruin", "damage", "eliminate"], ["destroy"],
        "The fire destroyed the whole building.", "de(去掉)+stroy(建造)→拆掉建造→摧毁"),
    make_entry("detail", "详细；详述；细节", "verb_action", 1, "medium",
        ["explain fully", "describe", "elaborate"], ["retail", "detail"],
        "He detailed the plan to everyone.", "de(分开)+tail(切)→切成小块→详述"),
    make_entry("detect", "发现；察觉；探测", "verb_action", 1, "medium",
        ["discover", "find out", "notice"], ["protect", "detect"],
        "The police detected a problem.", "de(去掉)+tect(覆盖)→揭开→发现"),
    make_entry("devote", "奉献；致力于", "verb_action", 1, "medium",
        ["dedicate", "commit", "give"], ["vote", "devote"],
        "She devoted herself to teaching.", "de(加强)+vote(发誓)→发誓做→奉献"),
    make_entry("differ", "不同；有区别", "verb_state", 1, "medium",
        ["be different", "vary", "disagree"], ["offer", "suffer"],
        "People differ in their opinions.", "dif(分开)+fer(带)→各带不同→有区别"),
    make_entry("digest", "消化；理解；摘要", "verb_action", 1, "low",
        ["absorb food", "understand", "summarize"], ["digital", "digest"],
        "Some foods are hard to digest.", "di(分开)+gest(携带)→分解携带→消化"),
    make_entry("disagree", "不同意；不一致", "verb_action", 1, "medium",
        ["differ", "dispute", "argue"], ["agree", "disagree"],
        "I disagree with your decision.", "dis(不)+agree(同意)→不同意"),
    make_entry("disappoint", "使失望；使沮丧", "verb_action", 1, "medium",
        ["let down", "sadden", "fail to meet expectations"], ["appoint"],
        "The results disappointed us.", "dis(不)+appoint(指定)→不符合期望→失望"),
    make_entry("disapprove", "不赞成；反对", "verb_action", 1, "medium",
        ["reject", "object to", "oppose"], ["approve", "improve"],
        "My parents disapproved of my plan.", "dis(不)+approve(批准)→不批准→反对"),
    make_entry("discourage", "使气馁；阻止", "verb_action", 1, "medium",
        ["demotivate", "stop", "dissuade"], ["encourage", "courage"],
        "Don't let failures discourage you.", "dis(不)+courage(勇气)→没有勇气→气馁"),
    make_entry("dislike", "不喜欢；厌恶", "verb_action", 1, "medium",
        ["hate", "not like", "be opposed to"], ["like", "alike"],
        "I dislike loud music.", "dis(不)+like(喜欢)→不喜欢"),
    make_entry("dismiss", "解散；解雇；不予理会", "verb_action", 1, "medium",
        ["fire", "send away", "reject"], ["miss", "admit"],
        "The teacher dismissed the class early.", "dis(分开)+miss(送)→分开发送→解散"),
    make_entry("display", "展示；陈列；显示器", "verb_action", 1, "medium",
        ["show", "exhibit", "demonstrate"], ["delay", "display"],
        "The museum displays ancient paintings.", "dis(分开)+play(折)→展开展示→陈列"),
    make_entry("dispute", "争论；争辩；质疑", "verb_action", 1, "medium",
        ["argue", "debate", "question"], ["repute", "dispute"],
        "They disputed the ownership of the land.", "dis(分开)+pute(想)→分开想→争论"),
    make_entry("dissolve", "溶解；解散；消失", "verb_action", 1, "medium",
        ["melt", "break up", "disappear"], ["resolve", "solve"],
        "Salt dissolves in water.", "dis(分开)+solve(松开)→松开分散→溶解"),
    make_entry("distinguish", "区分；辨别；使杰出", "verb_action", 1, "medium",
        ["tell apart", "recognize", "identify"], ["extinguish"],
        "Can you distinguish between the two sounds?", "di(分开)+stinguish(刺)→分别刺激→区分"),
]

NEW_WORDS.extend(P2_VERBS_MZ)
print(f"P2 高频动词M-Z: {len(P2_VERBS_MZ)} 词")

print(f"\n=== 第二部分动词总计: {len(NEW_WORDS) - PART1_COUNT} 新词 ===")
print(f"累计已生成: {len(NEW_WORDS)} 词")
