#!/usr/bin/env python3
"""
根据用户提供的课程大纲，重新生成听写词库。
规则：
1. 只分年级（4上4下合并为四年级，5上5下合并为五年级，6上6下合并为六年级）
2. 不分单元
3. 语文词库包含拼音和例句
4. 英语词库包含音标、释义和例句
"""

import json
import os

# ═══════════════════════════════════════════════════════════════
# 语文词库 - 基于用户提供的课程大纲
# 格式: (词语, 拼音, 例句)
# ═══════════════════════════════════════════════════════════════

cn_data = {
    4: {
        # 四年级上册
        "上册": [
            # 第1单元：江潮与自然
            ("潮水", "cháo shuǐ", "潮水退去后，沙滩上留下了很多贝壳。"),
            ("宽阔", "kuān kuò", "这条马路非常宽阔。"),
            ("笼罩", "lǒng zhào", "大雾笼罩着整个城市。"),
            ("薄雾", "bó wù", "清晨的薄雾慢慢散去。"),
            ("若隐若现", "ruò yǐn ruò xiàn", "远处的山峰若隐若现。"),
            ("人山人海", "rén shān rén hǎi", "节假日的公园里人山人海。"),
            ("据说", "jù shuō", "据说这座山上有珍贵的药材。"),
            ("横贯", "héng guàn", "大桥横贯江面。"),
            ("浩浩荡荡", "hào hào dàng dàng", "浩浩荡荡的队伍向前行进。"),
            ("山崩地裂", "shān bēng dì liè", "雷声如同山崩地裂一般。"),
            # 第2单元：思考与科技
            ("淘气", "táo qì", "弟弟很淘气，经常把家里弄得乱七八糟。"),
            ("填补", "tián bǔ", "我们需要填补这个空缺。"),
            ("坑坑洼洼", "kēng kēng wā wā", "这条路坑坑洼洼的，很难走。"),
            ("不容置疑", "bù róng zhì yí", "这个事实是不容置疑的。"),
            ("郁郁苍苍", "yù yù cāng cāng", "山上郁郁苍苍，长满了松树。"),
            ("牵", "qiān", "妈妈牵着孩子的手过马路。"),
            ("鹅", "é", "白鹅在水面上游来游去。"),
            # 第3单元：观察与发现
            ("灿烂", "càn làn", "阳光灿烂，万里无云。"),
            ("竹竿", "zhú gān", "爷爷用竹竿晾衣服。"),
            ("白茫茫", "bái máng máng", "下雪后，大地白茫茫一片。"),
            ("灿", "càn", "金灿灿的阳光洒在田野上。"),
            ("烂", "làn", "不要把食物放烂了。"),
            ("竿", "gān", "他拿了一根竹竿去钓鱼。"),
            # 第4单元：作家笔下的动物
            ("高傲", "gāo ào", "他总是用高傲的眼神看人。"),
            ("京剧", "jīng jù", "爷爷最喜欢看京剧了。"),
            ("滋味", "zī wèi", "这道菜的滋味真好。"),
            ("局促不安", "jú cù bù ān", "他第一次上台演讲，显得局促不安。"),
            ("从容不迫", "cóng róng bù pò", "面对困难，他从容不迫。"),
            ("颈", "jǐng", "长颈鹿的脖子很长。"),
            ("郑", "zhèng", "郑重其事地答应了。"),
            ("厉", "lì", "老师严厉地批评了他。"),
            # 第5单元：世界遗产
            ("崇山峻岭", "chóng shān jùn lǐng", "列车穿过崇山峻岭。"),
            ("气魄雄伟", "qì pò xióng wěi", "长城气魄雄伟，令人赞叹。"),
            ("金碧辉煌", "jīn bì huī huáng", "宫殿里金碧辉煌。"),
            ("神清气爽", "shén qīng qì shuǎng", "雨后空气清新，让人神清气爽。"),
            ("崇", "chóng", "崇山峻岭绵延不绝。"),
            ("旋", "xuán", "飞机在天空中盘旋。"),
            ("嘉", "jiā", "嘉宾纷纷到场。"),
            # 第6单元：人间真情
            ("突如其来", "tū rú qí lái", "一场突如其来的大雨淋湿了大家。"),
            ("谈何容易", "tán hé róng yì", "要做好这件事谈何容易。"),
            ("平安无事", "píng ān wú shì", "大家都平安无事地回来了。"),
            ("骨肉同胞", "gǔ ròu tóng bāo", "海内外骨肉同胞心连心。"),
            ("孟", "mèng", "孟母三迁的故事很感人。"),
            ("陵", "líng", "我们参观了中山陵。"),
            ("辞", "cí", "他写了一首辞别诗。"),
            # 第7单元：成长的故事
            ("帝国主义", "dì guó zhǔ yì", "中国人民反抗帝国主义侵略。"),
            ("风和日丽", "fēng hé rì lì", "今天风和日丽，适合郊游。"),
            ("耀武扬威", "yào wǔ yáng wēi", "他仗着人多势众，到处耀武扬威。"),
            ("得意扬扬", "dé yì yáng yáng", "他考了第一名，得意扬扬地回家了。"),
            ("崛", "jué", "祖国崛起，日益强大。"),
            ("帝", "dì", "古代的皇帝住在皇宫里。"),
            ("范", "fàn", "这篇范文写得很好。"),
            # 第8单元：科技成就
            ("呼风唤雨", "hū fēng huàn yǔ", "科技发展让人仿佛能呼风唤雨。"),
            ("出乎意料", "chū hū yì liào", "比赛结果出乎意料。"),
            ("腾云驾雾", "téng yún jià wù", "孙悟空能腾云驾雾。"),
            ("程控电话", "chéng kòng diàn huà", "程控电话方便了人们的生活。"),
            ("改", "gǎi", "他决定改掉坏习惯。"),
            ("程", "chéng", "这个程序的代码很长。"),
            ("赖", "lài", "我们不能依赖别人。"),
        ],
        # 四年级下册
        "下册": [
            # 第1单元：壮丽山河
            ("洞庭", "dòng tíng", "洞庭湖风景优美。"),
            ("江南", "jiāng nán", "江南水乡美如画。"),
            ("玩赏", "wán shǎng", "我们在公园里玩赏花草。"),
            ("波澜壮阔", "bō lán zhuàng kuò", "波澜壮阔的大海让人心旷神怡。"),
            ("水平如镜", "shuǐ píng rú jìng", "湖面水平如镜。"),
            ("峰峦雄伟", "fēng luán xióng wěi", "峰峦雄伟的泰山令人叹为观止。"),
            ("拔地而起", "bá dì ér qǐ", "一座高楼拔地而起。"),
            ("奇峰罗列", "qí fēng luó liè", "桂林的山奇峰罗列。"),
            ("亭", "tíng", "公园里有一座凉亭。"),
            ("庭", "tíng", "庭院里种满了花草。"),
            ("潭", "tán", "日月潭是台湾著名的景点。"),
            # 第2单元：以诚待人
            ("维持", "wéi chí", "警察在维持秩序。"),
            ("财富", "cái fù", "知识是一笔宝贵的财富。"),
            ("精湛", "jīng zhàn", "他的技艺非常精湛。"),
            ("将心比心", "jiāng xīn bǐ xīn", "做人要学会将心比心。"),
            ("闷闷不乐", "mèn mèn bù lè", "他今天闷闷不乐的。"),
            ("迷惑不解", "mí huò bù jiě", "他对这道题迷惑不解。"),
            ("面呈菜色", "miàn chéng cài sè", "他面呈菜色，显然很久没吃东西了。"),
            ("疲惫不堪", "pí bèi bù kān", "他疲惫不堪地回到了家。"),
            ("狼吞虎咽", "láng tūn hǔ yàn", "他饿坏了，狼吞虎咽地吃起来。"),
            ("骨瘦如柴", "gǔ shòu rú chái", "那个孩子骨瘦如柴。"),
            ("维", "wéi", "维持良好的学习习惯很重要。"),
            ("财", "cái", "不要贪财。"),
            ("属", "shǔ", "这本书属于我。"),
            # 第3单元：大自然的启示
            ("旅游", "lǚ yóu", "暑假我们全家去旅游了。"),
            ("幼龟", "yòu guī", "沙滩上有几只幼龟。"),
            ("沙滩", "shā tān", "孩子们在沙滩上玩耍。"),
            ("争先恐后", "zhēng xiān kǒng hòu", "同学们争先恐后地举手回答问题。"),
            ("若无其事", "ruò wú qí shì", "他若无其事地走了过去。"),
            ("鱼贯而出", "yú guàn ér chū", "学生们鱼贯而出地走出教室。"),
            ("愚不可及", "yú bù kě jí", "这种做法真是愚不可及。"),
            ("气喘吁吁", "qì chuǎn xū xū", "他跑得上气不接下气，气喘吁吁。"),
            ("响彻云霄", "xiǎng chè yún xiāo", "歌声响彻云霄。"),
            ("横七竖八", "héng qī shù bā", "地上横七竖八地放着几本书。"),
            ("幼", "yòu", "幼儿园里有很多小朋友。"),
            ("滩", "tān", "我们在海滩上捡贝壳。"),
            ("侦", "zhēn", "警察正在侦破案件。"),
            # 第4单元：战争与和平
            ("沉寂", "chén jì", "夜深了，四周一片沉寂。"),
            ("盘问", "pán wèn", "警察盘问了几个可疑的人。"),
            ("口哨", "kǒu shào", "他吹了一声口哨。"),
            ("知己知彼", "zhī jǐ zhī bǐ", "打仗要知己知彼，百战百胜。"),
            ("百战百胜", "bǎi zhàn bǎi shèng", "知己知彼才能百战百胜。"),
            ("围魏救赵", "wéi wèi jiù zhào", "围魏救赵是一个著名的战略。"),
            ("四面楚歌", "sì miàn chǔ gē", "项羽被困，四面楚歌。"),
            ("草木皆兵", "cǎo mù jiē bīng", "敌人吓破了胆，草木皆兵。"),
            ("风声鹤唳", "fēng shēng hè lì", "敌军风声鹤唳，惶恐不安。"),
            ("削", "xuē", "他用刀削铅笔。"),
            ("喂", "wèi", "她正在喂小鸡。"),
            ("哨", "shào", "哨兵站在门口。"),
            # 第5单元：热爱生命
            ("浓郁", "nóng yù", "花园里弥漫着浓郁的花香。"),
            ("流连", "liú lián", "美丽的景色让人流连忘返。"),
            ("小径", "xiǎo jìng", "我们沿着小径走进了树林。"),
            ("不假思索", "bù jiǎ sī suǒ", "他不假思索地回答了问题。"),
            ("怦然一震", "pēng rán yī zhèn", "听到这个消息，他怦然一震。"),
            ("多姿多彩", "duō zī duō cǎi", "校园生活多姿多彩。"),
            ("扰", "rǎo", "请不要打扰别人。"),
            ("欲", "yù", "他欲言又止。"),
            ("屈", "qū", "遇到困难不能屈服。"),
            # 第6单元：田园与乡村
            ("棚架", "péng jià", "葡萄藤爬满了棚架。"),
            ("风趣", "fēng qù", "这位老师说话很风趣。"),
            ("装饰", "zhuāng shì", "妈妈用鲜花装饰了房间。"),
            ("时令", "shí lìng", "这是时令蔬菜，非常新鲜。"),
            ("天高地阔", "tiān gāo dì kuò", "草原上天高地阔，一望无际。"),
            ("月明人静", "yuè míng rén jìng", "月明人静的夜晚，虫鸣声格外清晰。"),
            ("悠然自得", "yōu rán zì dé", "爷爷在院子里悠然自得地喝茶。"),
            ("棚", "péng", "工地上搭了一个大棚。"),
            ("饰", "shì", "她佩戴了很多装饰品。"),
            ("冠", "guān", "他获得了冠军。"),
            # 第7单元：人物品质
            ("辩论", "biàn lùn", "同学们进行了一场精彩的辩论。"),
            ("寻常", "xún cháng", "这不过是一件寻常的事。"),
            ("解答", "jiě dá", "老师耐心地解答了我们的问题。"),
            ("一干二净", "yī gān èr jìng", "他把碗洗得一干二净。"),
            ("莫名其妙", "mò míng qí miào", "他莫名其妙地笑了起来。"),
            ("胆大妄为", "dǎn dà wàng wéi", "他胆大妄为，做了很多坏事。"),
            ("清澈见底", "qīng chè jiàn dǐ", "小溪清澈见底。"),
            ("赏心悦目", "shǎng xīn yuè mù", "这幅画让人赏心悦目。"),
            ("执", "zhí", "他执着地追求自己的梦想。"),
            ("缸", "gāng", "水缸里装满了水。"),
            # 第8单元：故事长廊
            ("理睬", "lǐ cǎi", "他不理睬别人的嘲笑。"),
            ("肠胃", "cháng wèi", "不要吃太多，对肠胃不好。"),
            ("汤药", "tāng yào", "奶奶每天都要喝汤药。"),
            ("纪昌学射", "jì chāng xué shè", "纪昌学射的故事告诉我们熟能生巧。"),
            ("百发百中", "bǎi fā bǎi zhòng", "他射箭百发百中。"),
            ("聚精会神", "jù jīng huì shén", "同学们聚精会神地听老师讲课。"),
            ("无能为力", "wú néng wéi lì", "面对自然灾害，人类有时也无能为力。"),
            ("妻", "qī", "他的妻子很温柔。"),
            ("刺", "cì", "玫瑰花的刺很尖锐。"),
            ("绑", "bǎng", "坏人把人绑了起来。"),
        ],
    },
    5: {
        # 五年级上册
        "上册": [
            # 第1单元：我爱阅读
            ("担忧", "dān yōu", "妈妈总是担忧我的学习。"),
            ("惧怕", "jù pà", "他惧怕黑暗。"),
            ("鼓励", "gǔ lì", "老师鼓励我们要努力学习。"),
            ("倾盆大雨", "qīng pén dà yǔ", "倾盆大雨从天而降。"),
            ("毫不犹豫", "háo bù yóu yù", "他毫不犹豫地答应了。"),
            ("滚瓜烂熟", "gǔn guā làn shú", "他把课文背得滚瓜烂熟。"),
            ("津津有味", "jīn jīn yǒu wèi", "他津津有味地看故事书。"),
            ("囫囵吞枣", "hú lún tūn zǎo", "读书不能囫囵吞枣，要理解内容。"),
            ("如饥似渴", "rú jī sì kě", "他如饥似渴地阅读各种书籍。"),
            ("呕心沥血", "ǒu xīn lì xuè", "老师呕心沥血地教育我们。"),
            ("窃", "qiè", "他窃窃私语。"),
            ("炒", "chǎo", "妈妈炒了一盘青菜。"),
            ("锅", "guō", "锅里煮着汤。"),
            # 第2单元：月是故乡明
            ("漂泊", "piāo bó", "他在外漂泊了很多年。"),
            ("幽芳", "yōu fāng", "梅花散发着幽芳。"),
            ("风欺雪压", "fēng qī xuě yā", "梅花不怕风欺雪压。"),
            ("能书善画", "néng shū shàn huà", "他是一位能书善画的才子。"),
            ("顶天立地", "dǐng tiān lì dì", "我们要做顶天立地的人。"),
            ("低头折节", "dī tóu zhé jié", "做人不能低头折节。"),
            ("守望相助", "shǒu wàng xiāng zhù", "邻里之间守望相助。"),
            ("魂", "hún", "中华民族之魂永不灭。"),
            ("缕", "lǚ", "一缕阳光照进了窗户。"),
            ("幽", "yōu", "这里环境幽静。"),
            # 第3单元：说明性文章
            ("目前", "mù qián", "目前情况一切正常。"),
            ("上颚", "shàng è", "鲸的上颚有很多须板。"),
            ("哺乳", "bǔ rǔ", "鲸是哺乳动物。"),
            ("安然无恙", "ān rán wú yàng", "地震后，他们安然无恙。"),
            ("藕断丝连", "ǒu duàn sī lián", "他们虽然分开了，但藕断丝连。"),
            ("庞然大物", "páng rán dà wù", "恐龙是庞然大物。"),
            ("气象万千", "qì xiàng wàn qiān", "大自然气象万千。"),
            ("鲸", "jīng", "鲸是世界上最大的动物。"),
            ("猪", "zhū", "小猪在泥里打滚。"),
            ("腭", "è", "上颚和下颚组成口腔。"),
            # 第4单元：生活的启示
            ("捕捞", "bǔ lāo", "渔民在海上捕捞鱼虾。"),
            ("鱼饵", "yú ěr", "钓鱼需要准备好鱼饵。"),
            ("皎洁", "jiǎo jié", "皎洁的月光洒在湖面上。"),
            ("小心翼翼", "xiǎo xīn yì yì", "他小心翼翼地端着杯子。"),
            ("依依不舍", "yī yī bù shě", "同学们依依不舍地告别。"),
            ("不容争辩", "bù róng zhēng biàn", "这个道理是不容争辩的。"),
            ("水滴石穿", "shuǐ dī shí chuān", "只要坚持，水滴石穿。"),
            ("捞", "lāo", "他在河里捞鱼。"),
            ("饵", "ěr", "鱼饵挂好了。"),
            ("溅", "jiàn", "水花溅了一身。"),
            # 第6单元：父母之爱
            ("地震", "dì zhèn", "地震发生后，救援队迅速赶到。"),
            ("混乱", "hùn luàn", "现场一片混乱。"),
            ("安顿", "ān dùn", "妈妈安顿好了孩子才去上班。"),
            ("失魂落魄", "shī hún luò pò", "他失魂落魄地走在街上。"),
            ("震耳欲聋", "zhèn ěr yù lóng", "鞭炮声震耳欲聋。"),
            ("大吃一惊", "dà chī yī jīng", "这个消息让他大吃一惊。"),
            ("喋喋不休", "dié dié bù xiū", "妈妈喋喋不休地叮嘱他注意安全。"),
            ("忐忑不安", "tǎn tè bù ān", "他忐忑不安地等待考试结果。"),
            ("震", "zhèn", "大地震动了一下。"),
            ("昔", "xī", "昔日的战友又见面了。"),
            ("墟", "xū", "地震后变成了一片废墟。"),
            # 第7单元：民族精神
            ("估量", "gū liáng", "这笔损失无法估量。"),
            ("损失", "sǔn shī", "这次事故造成了巨大损失。"),
            ("殿堂", "diàn táng", "这座殿堂已有千年历史。"),
            ("举世闻名", "jǔ shì wén míng", "长城是举世闻名的建筑。"),
            ("众星拱月", "zhòng xīng gǒng yuè", "群星环绕月亮，众星拱月。"),
            ("玲珑剔透", "líng lóng tī tòu", "这件玉器玲珑剔透。"),
            ("同仇敌忾", "tóng chóu dí kài", "全国人民同仇敌忾，抵抗侵略。"),
            ("临危不惧", "lín wēi bù jù", "他临危不惧，勇救落水儿童。"),
            ("勇往直前", "yǒng wǎng zhí qián", "战士们勇往直前。"),
            ("前仆后继", "qián pū hòu jì", "革命先烈前仆后继。"),
            ("力挽狂澜", "lì wǎn kuáng lán", "他力挽狂澜，扭转了局势。"),
            ("大义凛然", "dà yì lǐn rán", "他大义凛然地拒绝了敌人的威胁。"),
            ("估", "gū", "我估计他不会来了。"),
            ("损", "sǔn", "这次损失很大。"),
            ("皇", "huáng", "故宫是明清两代的皇宫。"),
            # 第8单元：走近毛泽东
            ("典礼", "diǎn lǐ", "开学典礼在操场举行。"),
            ("协商", "xié shāng", "双方经过协商达成了协议。"),
            ("诞生", "dàn shēng", "新中国在1949年诞生。"),
            ("万水千山", "wàn shuǐ qiān shān", "红军走过万水千山。"),
            ("排山倒海", "pái shān dǎo hǎi", "浪潮排山倒海般涌来。"),
            ("夜以继日", "yè yǐ jì rì", "他夜以继日地工作。"),
            ("大公无私", "dà gōng wú sī", "他大公无私，深受大家爱戴。"),
            ("典", "diǎn", "这是一本经典名著。"),
            ("副", "fù", "他是一副热心肠。"),
            ("委", "wěi", "委员会做出了决定。"),
        ],
        # 五年级下册
        "下册": [
            # 第1单元：西部风情
            ("高歌", "gāo gē", "牧民们高歌一曲。"),
            ("绿毯", "lǜ tǎn", "草原像一块巨大的绿毯。"),
            ("柔美", "róu měi", "她的舞姿柔美动人。"),
            ("一碧千里", "yī bì qiān lǐ", "草原一碧千里，非常壮观。"),
            ("翠色欲流", "cuì sè yù liú", "草原翠色欲流，生机勃勃。"),
            ("襟飘带舞", "jīn piāo dài wǔ", "姑娘们襟飘带舞，欢快地跳着舞。"),
            ("美轮美奂", "měi lún měi huàn", "这座建筑美轮美奂。"),
            ("废寝忘食", "fèi qǐn wàng shí", "他废寝忘食地学习。"),
            ("毯", "tǎn", "她铺了一条毛毯。"),
            ("渲", "xuàn", "画家用笔渲染了天空。"),
            ("勒", "lè", "他勒住了马。"),
            # 第2单元：童年
            ("牧童", "mù tóng", "牧童骑在牛背上吹笛子。"),
            ("蓑衣", "suō yī", "渔翁穿着蓑衣在雨中钓鱼。"),
            ("鸡笼", "jī lóng", "鸡笼里关着几只母鸡。"),
            ("随心所欲", "suí xīn suǒ yù", "在公园里可以随心所欲地散步。"),
            ("运转自如", "yùn zhuǎn zì rú", "这台机器运转自如。"),
            ("翻来覆去", "fān lái fù qù", "他翻来覆去睡不着。"),
            ("绞尽脑汁", "jiǎo jìn nǎo zhī", "他绞尽脑汁地想答案。"),
            ("牧", "mù", "牧民在草原上放羊。"),
            ("蓑", "suō", "他披着蓑衣。"),
            ("遮", "zhē", "大树遮住了阳光。"),
            # 第3单元：语言的艺术
            ("侮辱", "wǔ rǔ", "他受到了侮辱。"),
            ("威风", "wēi fēng", "将军威风凛凛地骑着马。"),
            ("矮小", "ǎi xiǎo", "这座房子很矮小。"),
            ("实话实说", "shí huà shí shuō", "请你实话实说。"),
            ("面不改色", "miàn bù gǎi sè", "他面不改色地面对威胁。"),
            ("安居乐业", "ān jū lè yè", "百姓安居乐业。"),
            ("梁", "liáng", "桥梁横跨两岸。"),
            ("惠", "huì", "他受到了恩惠。"),
            ("诣", "yì", "他诣见国王。"),
            # 第4单元：感人的故事
            ("战役", "zhàn yì", "这场战役非常激烈。"),
            ("封锁", "fēng suǒ", "道路被封锁了。"),
            ("暂时", "zàn shí", "请暂时离开这里。"),
            ("精卫填海", "jīng wèi tián hǎi", "精卫填海是一个古老的传说。"),
            ("愚公移山", "yú gōng yí shān", "愚公移山的精神值得我们学习。"),
            ("含辛茹苦", "hán xīn rú kǔ", "母亲含辛茹苦地把我们养大。"),
            ("任劳任怨", "rèn láo rèn yuàn", "他任劳任怨地工作。"),
            ("艰苦卓绝", "jiān kǔ zhuó jué", "经过艰苦卓绝的奋斗，终于成功了。"),
            ("百折不挠", "bǎi zhé bù náo", "他百折不挠，终于实现了梦想。"),
            ("千里迢迢", "qiān lǐ tiáo tiáo", "他千里迢迢赶来参加比赛。"),
            ("肝胆相照", "gān dǎn xiāng zhào", "好朋友之间应该肝胆相照。"),
            ("妮", "nī", "小妮子跑过来了。"),
            ("役", "yì", "他服了两年兵役。"),
            ("硝", "xiāo", "战场上硝烟弥漫。"),
            # 第5单元：古典名著
            ("召集", "zhào jí", "校长召集老师们开会。"),
            ("商议", "shāng yì", "大家商议一下怎么办。"),
            ("隆重", "lóng zhòng", "开幕式非常隆重。"),
            ("无价之宝", "wú jià zhī bǎo", "这块玉是无价之宝。"),
            ("理直气壮", "lǐ zhí qì zhuàng", "他理直气壮地反驳了对方。"),
            ("完璧归赵", "wán bì guī zhào", "蔺相如完璧归赵。"),
            ("攻无不克", "gōng wú bù kè", "这支军队攻无不克。"),
            ("负荆请罪", "fù jīng qǐng zuì", "廉颇负荆请罪，将相和好。"),
            ("神机妙算", "shén jī miào suàn", "诸葛亮神机妙算。"),
            ("赵", "zhào", "赵国是战国七雄之一。"),
            ("璧", "bì", "和氏璧是一块美玉。"),
            ("召", "zhào", "国王召见了大臣。"),
            # 第7单元：鲜活的人物
            ("破绽", "pò zhàn", "他的谎言露出了破绽。"),
            ("咕咚", "gū dōng", "石头咕咚一声掉进了水里。"),
            ("侄子", "zhí zi", "他的侄子今年上小学。"),
            ("文质彬彬", "wén zhì bīn bīn", "他文质彬彬，很有礼貌。"),
            ("仪表堂堂", "yí biǎo táng táng", "他仪表堂堂，很有气质。"),
            ("虎背熊腰", "hǔ bèi xióng yāo", "他虎背熊腰，十分强壮。"),
            ("神采奕奕", "shén cǎi yì yì", "他神采奕奕地走进了会场。"),
            ("满面春风", "mǎn miàn chūn fēng", "他满面春风地回来了。"),
            ("垂头丧气", "chuí tóu sàng qì", "考试没考好，他垂头丧气。"),
            ("健步如飞", "jiàn bù rú fēi", "爷爷虽然年纪大了，但健步如飞。"),
            ("擞", "sǒu", "他精神抖擞。"),
            ("监", "jiān", "监考老师在教室里巡视。"),
            ("侄", "zhí", "我的侄子很可爱。"),
            # 第8单元：异域风情
            ("天性", "tiān xìng", "好奇心是孩子的天性。"),
            ("宇宙", "yǔ zhòu", "宇宙浩瀚无边。"),
            ("真切", "zhēn qiè", "我真切地感受到了他的关心。"),
            ("目不暇接", "mù bù xiá jiē", "商店里的商品让人目不暇接。"),
            ("耐人寻味", "nài rén xún wèi", "这句话耐人寻味。"),
            ("纵横交叉", "zòng héng jiāo chā", "城市的道路纵横交叉。"),
            ("操纵自如", "cāo zòng zì rú", "他操纵自如地驾驶着汽车。"),
            ("脊", "jǐ", "他的脊背挺得笔直。"),
            ("莞", "guǎn", "她莞尔一笑。"),
            ("锦", "jǐn", "前程似锦。"),
        ],
    },
    6: {
        # 六年级上册
        "上册": [
            # 第1单元：感受自然之美
            ("清爽", "qīng shuǎng", "雨后的空气非常清爽。"),
            ("吟诵", "yín sòng", "他低声吟诵着古诗。"),
            ("唱和", "chàng hè", "鸟儿在树上唱和。"),
            ("德高望重", "dé gāo wàng zhòng", "这位老教授德高望重。"),
            ("津津乐道", "jīn jīn lè dào", "大家津津乐道地谈论着比赛。"),
            ("别有深意", "bié yǒu shēn yì", "他的话别有深意。"),
            ("左冲右撞", "zuǒ chōng yòu zhuàng", "他在人群中左冲右撞。"),
            ("行色匆匆", "xíng sè cōng cōng", "人们行色匆匆地赶路。"),
            ("不拘一格", "bù jū yī gé", "他的写作风格不拘一格。"),
            ("邀", "yāo", "我邀请你来我家玩。"),
            ("俯", "fǔ", "他俯身捡起了地上的东西。"),
            ("瀑", "pù", "黄果树瀑布非常壮观。"),
            # 第2单元：祖国在我心中
            ("杰出", "jié chū", "他是一位杰出的科学家。"),
            ("修筑", "xiū zhù", "工人们正在修筑铁路。"),
            ("设计", "shè jì", "这座桥的设计很巧妙。"),
            ("悬崖峭壁", "xuán yá qiào bì", "悬崖峭壁上长着几棵松树。"),
            ("寝不安席", "qǐn bù ān xí", "他忧国忧民，寝不安席。"),
            ("思潮起伏", "sī cháo qǐ fú", "听到这个消息，他思潮起伏。"),
            ("可见一斑", "kě jiàn yī bān", "从这件事可见一斑。"),
            ("碧空如洗", "bì kōng rú xǐ", "天空碧空如洗。"),
            ("百折不回", "bǎi zhé bù huí", "他百折不回，终于成功了。"),
            ("施", "shī", "他乐于施舍。"),
            ("挠", "náo", "他抓耳挠腮地想答案。"),
            ("庸", "yōng", "他平庸无奇。"),
            # 第3单元：人间真情
            ("舒适", "shū shì", "这个沙发很舒适。"),
            ("搁板", "gē bǎn", "书放在搁板上。"),
            ("勉强", "miǎn qiǎng", "他勉强答应了。"),
            ("心惊肉跳", "xīn jīng ròu tiào", "看到那个场景，他心惊肉跳。"),
            ("自言自语", "zì yán zì yǔ", "他自言自语地说着什么。"),
            ("自作自受", "zì zuò zì shòu", "这是他自作自受。"),
            ("缝缝补补", "féng féng bǔ bǔ", "奶奶在灯下缝缝补补。"),
            ("流连忘返", "liú lián wàng fǎn", "这里的景色让人流连忘返。"),
            ("怒目圆睁", "nù mù yuán zhēng", "他怒目圆睁地瞪着对方。"),
            ("兴高采烈", "xìng gāo cǎi liè", "同学们兴高采烈地去春游。"),
            ("搁", "gē", "这件事先搁一搁。"),
            ("填", "tián", "请填写这张表格。"),
            ("怨", "yuàn", "他抱怨天气太热。"),
            # 第4单元：珍惜资源
            ("遥望", "yáo wàng", "他遥望着远方的家乡。"),
            ("晶莹", "jīng yíng", "露珠晶莹剔透。"),
            ("资源", "zī yuán", "我们要节约资源。"),
            ("和蔼可亲", "hé ǎi kě qīn", "老师和蔼可亲。"),
            ("闪闪发光", "shǎn shǎn fā guāng", "宝石闪闪发光。"),
            ("滔滔不绝", "tāo tāo bù jué", "他滔滔不绝地讲了起来。"),
            ("一泻千里", "yī xiè qiān lǐ", "瀑布一泻千里。"),
            ("纷至沓来", "fēn zhì tà lái", "游客纷至沓来。"),
            ("世外桃源", "shì wài táo yuán", "这里就像世外桃源一样。"),
            ("晶", "jīng", "水晶晶莹剔透。"),
            ("莹", "yíng", "他的眼睛晶莹明亮。"),
            ("蔼", "ǎi", "他和蔼可亲。"),
            # 第5单元：初识鲁迅
            ("厨房", "chú fáng", "妈妈在厨房做饭。"),
            ("刺猬", "cì wèi", "刺猬遇到危险就缩成一团。"),
            ("畜生", "chù shēng", "那个坏蛋简直是畜生。"),
            ("囫囵吞枣", "hú lún tūn zǎo", "读书不能囫囵吞枣。"),
            ("张冠李戴", "zhāng guān lǐ dài", "他把张冠李戴搞混了。"),
            ("恍然大悟", "huǎng rán dà wù", "听了老师的解释，他恍然大悟。"),
            ("饱经风霜", "bǎo jīng fēng shuāng", "爷爷的脸上饱经风霜。"),
            ("扭", "niǔ", "他扭头看了看。"),
            ("胯", "kuà", "他胯下骑着马。"),
            ("厨", "chú", "厨师做了一桌好菜。"),
            # 第7单元：人与动物
            ("塑料", "sù liào", "请减少使用塑料制品。"),
            ("饼干", "bǐng gān", "他吃了几块饼干。"),
            ("节奏", "jié zòu", "这首歌的节奏很快。"),
            ("抑扬顿挫", "yì yáng dùn cuò", "他抑扬顿挫地朗读课文。"),
            ("相依相随", "xiāng yī xiāng suí", "老两口相依相随。"),
            ("漫不经心", "màn bù jīng xīn", "他漫不经心地翻着书。"),
            ("震耳欲聋", "zhèn ěr yù lóng", "雷声震耳欲聋。"),
            ("浴血搏杀", "yù xuè bó shā", "战士们浴血搏杀。"),
            ("塑", "sù", "雕塑家创作了一座雕像。"),
            ("饼", "bǐng", "他买了一个烧饼。"),
            ("谱", "pǔ", "他照着乐谱弹琴。"),
            # 第8单元：艺术的魅力
            ("谱写", "pǔ xiě", "贝多芬谱写了许多名曲。"),
            ("幽静", "yōu jìng", "小巷里幽静而美丽。"),
            ("蜡烛", "là zhú", "停电了，我们点起了蜡烛。"),
            ("微波粼粼", "wēi bō lín lín", "湖面微波粼粼。"),
            ("有朝一日", "yǒu zhāo yī rì", "有朝一日，我会实现梦想。"),
            ("大洋彼岸", "dà yáng bǐ àn", "他远在大洋彼岸。"),
            ("不落窠臼", "bù luò kē jiù", "这幅画不落窠臼，很有创意。"),
            ("脍炙人口", "kuài zhì rén kǒu", "这首诗脍炙人口。"),
            ("妙笔生花", "miào bǐ shēng huā", "他妙笔生花，写出了精彩的文章。"),
            ("善", "shàn", "他心地善良。"),
            ("哉", "zāi", "善哉善哉。"),
            ("茵", "yīn", "绿草如茵。"),
        ],
        # 六年级下册
        "下册": [
            # 第1单元：民俗与生活
            ("腊月", "là yuè", "腊月里家家户户准备过年。"),
            ("展览", "zhǎn lǎn", "我们去参观了展览。"),
            ("蒜瓣", "suàn bàn", "奶奶剥了几瓣蒜。"),
            ("万象更新", "wàn xiàng gēng xīn", "春天来了，万象更新。"),
            ("张灯结彩", "zhāng dēng jié cǎi", "节日里大街小巷张灯结彩。"),
            ("截然不同", "jié rán bù tóng", "这两个方案截然不同。"),
            ("万不得已", "wàn bù dé yǐ", "不到万不得已，我不会放弃。"),
            ("醋", "cù", "他喜欢吃醋。"),
            ("饺", "jiǎo", "奶奶包的饺子很好吃。"),
            ("拌", "bàn", "妈妈拌了一盘凉菜。"),
            # 第2单元：异国风情
            ("剧种", "jù zhǒng", "京剧是中国的国粹剧种。"),
            ("面具", "miàn jù", "他戴着一个面具。"),
            ("激流", "jī liú", "小船在激流中前行。"),
            ("优哉游哉", "yōu zāi yóu zāi", "他优哉游哉地散步。"),
            ("一无所有", "yī wú suǒ yǒu", "他一无所有地来到这座城市。"),
            ("哄堂大笑", "hōng táng dà xiào", "他的话引得大家哄堂大笑。"),
            ("能歌善舞", "néng gē shàn wǔ", "少数民族的姑娘们能歌善舞。"),
            ("别无所求", "bié wú suǒ qiú", "他别无所求，只希望家人平安。"),
            ("蚀", "shí", "月蚀是一种天文现象。"),
            ("乏", "fá", "他累得筋疲力乏。"),
            ("雅", "yǎ", "这个房间布置得很雅致。"),
            # 第3单元：追忆革命先辈
            ("书籍", "shū jí", "图书馆里有很多书籍。"),
            ("含糊", "hán hú", "他说话含糊不清。"),
            ("尖锐", "jiān ruì", "他的目光很尖锐。"),
            ("一拥而入", "yī yōng ér rù", "人群一拥而入。"),
            ("怒气冲冲", "nù qì chōng chōng", "他怒气冲冲地走了出去。"),
            ("聚精会神", "jù jīng huì shén", "同学们聚精会神地听课。"),
            ("千钧一发", "qiān jūn yī fà", "千钧一发之际，他拉住了孩子。"),
            ("精兵简政", "jīng bīng jiǎn zhèng", "政府实行精兵简政。"),
            ("五湖四海", "wǔ hú sì hǎi", "朋友们来自五湖四海。"),
            ("籍", "jí", "他的户籍在北京。"),
            ("屉", "tì", "请打开抽屉。"),
            ("怖", "bù", "这部电影很恐怖。"),
            # 第4单元：外国名著名篇
            ("蜷缩", "quán suō", "小猫蜷缩在角落里。"),
            ("橱窗", "chú chuāng", "橱窗里摆满了漂亮的衣服。"),
            ("饥饿", "jī è", "他已经饥饿了一天。"),
            ("哆哆嗦嗦", "duō duō suō suō", "他冻得哆哆嗦嗦。"),
            ("天涯海角", "tiān yá hǎi jiǎo", "他走到了天涯海角。"),
            ("无济于事", "wú jì yú shì", "后悔也无济于事。"),
            ("乌合之众", "wū hé zhī zhòng", "这不过是一群乌合之众。"),
            ("与世隔绝", "yǔ shì gé jué", "他们住在深山里，与世隔绝。"),
            ("乖", "guāi", "这个孩子很乖。"),
            ("裙", "qún", "她穿了一条漂亮的裙子。"),
            ("兜", "dōu", "他的口袋里兜着糖果。"),
            # 第5单元：科学精神
            ("洗澡", "xǐ zǎo", "他每天晚上洗澡。"),
            ("机械", "jī xiè", "工厂里有很多机械设备。"),
            ("玫瑰", "méi guī", "花园里种了很多玫瑰。"),
            ("侃侃而谈", "kǎn kǎn ér tán", "他在台上侃侃而谈。"),
            ("想方设法", "xiǎng fāng shè fǎ", "老师想方设法帮助他。"),
            ("无独有偶", "wú dú yǒu ǒu", "无独有偶，我也遇到过类似的事。"),
            ("见微知著", "jiàn wēi zhī zhù", "他见微知著，发现了问题。"),
            ("锲而不舍", "qiè ér bù shě", "他锲而不舍地研究这个问题。"),
            ("澡", "zǎo", "他去澡堂洗澡。"),
            ("械", "xiè", "这个机械装置很复杂。"),
            ("逆", "nì", "他逆水行舟。"),
        ],
    },
}

# ═══════════════════════════════════════════════════════════════
# 英语词库 - 基于用户提供的课程大纲
# 格式: (单词, 释义, 音标, 例句)
# ═══════════════════════════════════════════════════════════════

en_data = {
    4: {
        "上册": [
            # Unit 1: 教室
            ("classroom", "教室", "/ˈklɑːsruːm/", "This is my classroom."),
            ("blackboard", "黑板", "/ˈblækbɔːrd/", "Look at the blackboard."),
            ("computer", "电脑", "/kəmˈpjuːtər/", "I have a new computer."),
            ("window", "窗户", "/ˈwɪndəʊ/", "Open the window, please."),
            ("door", "门", "/dɔːr/", "Close the door."),
            ("picture", "图画", "/ˈpɪktʃər/", "There is a picture on the wall."),
            ("light", "灯", "/laɪt/", "Turn on the light."),
            ("clean", "打扫", "/kliːn/", "Let me clean the classroom."),
            ("near", "在……旁边", "/nɪr/", "The TV is near the window."),
            ("where", "在哪里", "/wer/", "Where is the picture?"),
            ("there", "那里", "/ðer/", "There is a desk there."),
            ("help", "帮助", "/help/", "Let me help you."),
            # Unit 2: 书包
            ("schoolbag", "书包", "/ˈskuːlbæɡ/", "I have a new schoolbag."),
            ("notebook", "笔记本", "/ˈnəʊtbʊk/", "I need a notebook."),
            ("candy", "糖果", "/ˈkændi/", "I have some candy."),
            ("key", "钥匙", "/kiː/", "Here is the key."),
            ("toy", "玩具", "/tɔɪ/", "I have a toy bear."),
            ("heavy", "重的", "/ˈhevi/", "My schoolbag is heavy."),
            ("put", "放", "/pʊt/", "Put your book on the desk."),
            ("lost", "丢失", "/lɒst/", "I lost my pen."),
            # Unit 3: 我的朋友
            ("strong", "强壮的", "/strɒŋ/", "He is strong."),
            ("friendly", "友好的", "/ˈfrendli/", "She is very friendly."),
            ("quiet", "安静的", "/ˈkwaɪət/", "He is quiet."),
            ("hair", "头发", "/her/", "She has long hair."),
            ("glasses", "眼镜", "/ˈɡlɑːsɪz/", "He wears glasses."),
            ("shoe", "鞋", "/ʃuː/", "Take off your shoes."),
            # Unit 4: 我的家
            ("bedroom", "卧室", "/ˈbedruːm/", "This is my bedroom."),
            ("kitchen", "厨房", "/ˈkɪtʃɪn/", "Mom is in the kitchen."),
            ("fridge", "冰箱", "/frɪdʒ/", "The fridge is full."),
            ("sofa", "沙发", "/ˈsəʊfə/", "Sit on the sofa."),
            ("bathroom", "浴室", "/ˈbɑːθruːm/", "Go to the bathroom."),
            ("living room", "客厅", "/ˈlɪvɪŋ ruːm/", "Watch TV in the living room."),
            ("study", "书房", "/ˈstʌdi/", "He is in the study."),
            # Unit 5: 晚餐
            ("beef", "牛肉", "/biːf/", "I like beef."),
            ("soup", "汤", "/suːp/", "The soup is hot."),
            ("vegetables", "蔬菜", "/ˈvedʒtəblz/", "Eat more vegetables."),
            ("chopsticks", "筷子", "/ˈtʃɒpstɪks/", "Use chopsticks to eat."),
            ("bowl", "碗", "/bəʊl/", "A bowl of rice, please."),
            ("dinner", "晚餐", "/ˈdɪnər/", "What's for dinner?"),
            ("ready", "准备好的", "/ˈredi/", "Dinner is ready."),
            ("pass", "递给", "/pɑːs/", "Pass me the salt, please."),
            # Unit 6: 家人和职业
            ("parents", "父母", "/ˈpeərənts/", "My parents love me."),
            ("uncle", "叔舅", "/ˈʌŋkl/", "My uncle is a doctor."),
            ("aunt", "姑姨", "/ɑːnt/", "My aunt lives in Beijing."),
            ("doctor", "医生", "/ˈdɒktər/", "She is a doctor."),
            ("driver", "司机", "/ˈdraɪvər/", "He is a bus driver."),
            ("farmer", "农民", "/ˈfɑːrmər/", "My father is a farmer."),
            ("nurse", "护士", "/nɜːrs/", "The nurse is kind."),
            ("cook", "厨师", "/kʊk/", "He is a good cook."),
            ("job", "工作", "/dʒɒb/", "What's his job?"),
            ("people", "人们", "/ˈpiːpl/", "There are many people."),
        ],
        "下册": [
            # Unit 1: 我的学校
            ("library", "图书馆", "/ˈlaɪbrəri/", "The library is on the first floor."),
            ("playground", "操场", "/ˈpleɪɡraʊnd/", "We play on the playground."),
            ("teacher's office", "教师办公室", "/ˈtiːtʃərz ˈɒfɪs/", "The teacher's office is next to the library."),
            ("floor", "楼层", "/flɔːr/", "It's on the second floor."),
            ("garden", "花园", "/ˈɡɑːrdn/", "There is a garden in our school."),
            ("art room", "美术教室", "/ɑːrt ruːm/", "The art room is beautiful."),
            ("music room", "音乐教室", "/ˈmjuːzɪk ruːm/", "We sing in the music room."),
            ("gym", "体育馆", "/dʒɪm/", "We have PE in the gym."),
            # Unit 2: 时间
            ("breakfast", "早餐", "/ˈbrekfəst/", "I have breakfast at seven."),
            ("lunch", "午餐", "/lʌntʃ/", "It's time for lunch."),
            ("dinner", "晚餐", "/ˈdɪnər/", "Dinner is at six o'clock."),
            ("get up", "起床", "/ɡet ʌp/", "I get up at six thirty."),
            ("go to school", "上学", "/ɡəʊ tə skuːl/", "I go to school at seven."),
            ("go home", "回家", "/ɡəʊ həʊm/", "I go home at four."),
            ("go to bed", "上床睡觉", "/ɡəʊ tə bed/", "I go to bed at nine."),
            ("ready", "准备好的", "/ˈredi/", "Are you ready?"),
            ("hurry up", "快点", "/ˈhʌri ʌp/", "Hurry up! We are late."),
            # Unit 3: 天气
            ("warm", "温暖的", "/wɔːrm/", "It's warm in spring."),
            ("cool", "凉爽的", "/kuːl/", "It's cool in autumn."),
            ("sunny", "晴朗的", "/ˈsʌni/", "It's sunny today."),
            ("rainy", "下雨的", "/ˈreɪni/", "It's rainy outside."),
            ("cloudy", "多云的", "/ˈklaʊdi/", "It's cloudy today."),
            ("snowy", "下雪的", "/ˈsnəʊi/", "It's snowy in winter."),
            ("windy", "有风的", "/ˈwɪndi/", "It's windy today."),
            ("cold", "寒冷的", "/kəʊld/", "It's cold in winter."),
            ("hot", "炎热的", "/hɒt/", "It's hot in summer."),
            ("weather", "天气", "/ˈweðər/", "What's the weather like?"),
            # Unit 4: 农场
            ("tomato", "西红柿", "/təˈmeɪtəʊ/", "I like tomatoes."),
            ("carrot", "胡萝卜", "/ˈkærət/", "Rabbits like carrots."),
            ("horse", "马", "/hɔːrs/", "The horse is running."),
            ("cow", "奶牛", "/kaʊ/", "The cow gives us milk."),
            ("sheep", "绵羊", "/ʃiːp/", "There are many sheep."),
            ("hen", "母鸡", "/hen/", "The hen has chicks."),
            ("potato", "土豆", "/pəˈteɪtəʊ/", "I like potato chips."),
            ("green beans", "青豆", "/ɡriːn biːnz/", "These green beans are fresh."),
            # Unit 5: 服装
            ("dress", "连衣裙", "/dres/", "She wears a dress."),
            ("skirt", "短裙", "/skɜːrt/", "This skirt is pretty."),
            ("sweater", "毛衣", "/ˈswetər/", "Put on your sweater."),
            ("pants", "裤子", "/pænts/", "These pants are too long."),
            ("shirt", "衬衫", "/ʃɜːrt/", "He wears a white shirt."),
            ("coat", "外套", "/kəʊt/", "Wear your coat."),
            ("jacket", "夹克", "/ˈdʒækɪt/", "This jacket is cool."),
            ("shorts", "短裤", "/ʃɔːrts/", "I wear shorts in summer."),
            # Unit 6: 购物
            ("gloves", "手套", "/ɡlʌvz/", "Put on your gloves."),
            ("scarf", "围巾", "/skɑːrf/", "This scarf is beautiful."),
            ("umbrella", "雨伞", "/ʌmˈbrelə/", "Take your umbrella."),
            ("cheap", "便宜的", "/tʃiːp/", "This shirt is cheap."),
            ("expensive", "昂贵的", "/ɪkˈspensɪv/", "This bag is expensive."),
            ("nice", "好看的", "/naɪs/", "This dress is nice."),
            ("try on", "试穿", "/traɪ ɒn/", "Can I try on this shirt?"),
            ("size", "尺码", "/saɪz/", "What size do you wear?"),
            ("of course", "当然", "/əv kɔːrs/", "Of course you can."),
        ],
    },
    5: {
        "上册": [
            # Unit 1: 我的老师
            ("kind", "和蔼的", "/kaɪnd/", "Our teacher is very kind."),
            ("strict", "严格的", "/strɪkt/", "My father is strict."),
            ("polite", "有礼貌的", "/pəˈlaɪt/", "He is polite."),
            ("clever", "聪明的", "/ˈklevər/", "She is very clever."),
            ("helpful", "乐于助人的", "/ˈhelpfl/", "He is helpful."),
            ("shy", "害羞的", "/ʃaɪ/", "She is a shy girl."),
            ("young", "年轻的", "/jʌŋ/", "Our English teacher is young."),
            ("funny", "有趣的", "/ˈfʌni/", "He is funny."),
            ("old", "年老的", "/əʊld/", "Our math teacher is old."),
            # Unit 2: 一周生活
            ("Monday", "星期一", "/ˈmʌndeɪ/", "I have English on Monday."),
            ("Tuesday", "星期二", "/ˈtjuːzdeɪ/", "We have PE on Tuesday."),
            ("Wednesday", "星期三", "/ˈwenzdeɪ/", "Wednesday is my favorite day."),
            ("Thursday", "星期四", "/ˈθɜːrzdeɪ/", "I play football on Thursday."),
            ("Friday", "星期五", "/ˈfraɪdeɪ/", "Friday is the last day of school."),
            ("Saturday", "星期六", "/ˈsætərdeɪ/", "I go to the park on Saturday."),
            ("Sunday", "星期日", "/ˈsʌndeɪ/", "I rest on Sunday."),
            ("weekend", "周末", "/ˌwiːkˈend/", "What do you do on the weekend?"),
            ("do homework", "做作业", "/duː ˈhəʊmwɜːk/", "I do homework after dinner."),
            ("read books", "读书", "/riːd bʊks/", "I like to read books."),
            ("play football", "踢足球", "/pleɪ ˈfʊtbɔːl/", "We play football after school."),
            ("wash my clothes", "洗衣服", "/wɒʃ maɪ kləʊðz/", "I wash my clothes on Sunday."),
            # Unit 3: 饮食
            ("salad", "沙拉", "/ˈsæləd/", "I like fruit salad."),
            ("hamburger", "汉堡", "/ˈhæmbɜːrɡər/", "I'd like a hamburger."),
            ("fresh", "新鲜的", "/freʃ/", "The vegetables are fresh."),
            ("delicious", "美味的", "/dɪˈlɪʃəs/", "The food is delicious."),
            ("healthy", "健康的", "/ˈhelθi/", "Eat healthy food."),
            ("sweet", "甜的", "/swiːt/", "The cake is too sweet."),
            ("thirsty", "渴的", "/ˈθɜːrsti/", "I'm thirsty."),
            ("hungry", "饥饿的", "/ˈhʌŋɡri/", "I'm hungry."),
            ("favourite", "最喜欢的", "/ˈfeɪvərɪt/", "What's your favourite food?"),
            # Unit 4: 文娱活动
            ("sing", "唱歌", "/sɪŋ/", "I can sing English songs."),
            ("dance", "跳舞", "/dɑːns/", "She can dance very well."),
            ("draw", "画画", "/drɔː/", "I like to draw pictures."),
            ("swim", "游泳", "/swɪm/", "I can swim."),
            ("cook", "做饭", "/kʊk/", "My mother can cook well."),
            ("play the pipa", "弹琵琶", "/pleɪ ðə piːpɑː/", "She can play the pipa."),
            ("do kung fu", "练武术", "/duː kʌŋ fuː/", "He can do kung fu."),
            # Unit 5: 家居物品
            ("clock", "时钟", "/klɒk/", "There is a clock on the wall."),
            ("plant", "植物", "/plɑːnt/", "There is a plant near the door."),
            ("water bottle", "水瓶", "/ˈwɔːtər ˈbɒtl/", "This is my water bottle."),
            ("bike", "自行车", "/baɪk/", "I have a new bike."),
            ("photo", "照片", "/ˈfəʊtəʊ/", "This is a photo of my family."),
            ("front", "前面", "/frʌnt/", "There is a tree in front of the house."),
            ("beside", "在……旁边", "/bɪˈsaɪd/", "The ball is beside the desk."),
            ("behind", "在……后面", "/bɪˈhaɪnd/", "The cat is behind the sofa."),
            ("between", "在……之间", "/bɪˈtwiːn/", "The ball is between the two boxes."),
            ("above", "在……上面", "/əˈbʌv/", "The picture is above the bed."),
            # Unit 6: 自然公园
            ("forest", "森林", "/ˈfɒrɪst/", "There is a forest near the village."),
            ("river", "河流", "/ˈrɪvər/", "There is a river in the park."),
            ("lake", "湖泊", "/leɪk/", "The lake is very beautiful."),
            ("mountain", "高山", "/ˈmaʊntən/", "There is a mountain near our town."),
            ("hill", "小山", "/hɪl/", "There are some hills."),
            ("bridge", "桥", "/brɪdʒ/", "There is a bridge over the river."),
            ("building", "建筑物", "/ˈbɪldɪŋ/", "There are many tall buildings."),
            ("village", "村庄", "/ˈvɪlɪdʒ/", "The village is quiet."),
            ("nature park", "自然公园", "/ˈneɪtʃər pɑːrk/", "Let's go to the nature park."),
        ],
        "下册": [
            # Unit 1: 我的一天
            ("do morning exercises", "做早操", "/duː ˈmɔːrnɪŋ ˈeksərsaɪzɪz/", "I do morning exercises at 7:00."),
            ("eat breakfast", "吃早饭", "/iːt ˈbrekfəst/", "I eat breakfast at 7:30."),
            ("eat dinner", "吃晚饭", "/iːt ˈdɪnər/", "I eat dinner at 6:00."),
            ("usually", "通常", "/ˈjuːʒuəli/", "I usually go to school by bus."),
            ("often", "经常", "/ˈɒfn/", "I often read books."),
            ("sometimes", "有时候", "/ˈsʌmtaɪmz/", "Sometimes I walk to school."),
            ("always", "总是", "/ˈɔːlweɪz/", "I always get up early."),
            ("never", "从不", "/ˈnevər/", "I never go to school late."),
            # Unit 2: 最喜欢的季节
            ("spring", "春天", "/sprɪŋ/", "I like spring best."),
            ("summer", "夏天", "/ˈsʌmər/", "Summer is hot."),
            ("autumn", "秋天", "/ˈɔːtəm/", "Autumn is cool."),
            ("winter", "冬天", "/ˈwɪntər/", "It snows in winter."),
            ("season", "季节", "/ˈsiːzn/", "Which season do you like best?"),
            ("go on a picnic", "去野餐", "/ɡəʊ ɒn ə ˈpɪknɪk/", "Let's go on a picnic."),
            ("make a snowman", "堆雪人", "/meɪk ə ˈsnəʊmæn/", "I like to make a snowman."),
            ("go swimming", "去游泳", "/ɡəʊ ˈswɪmɪŋ/", "Let's go swimming."),
            # Unit 3: 校历
            ("January", "一月", "/ˈdʒænjuəri/", "New Year is in January."),
            ("February", "二月", "/ˈfebruəri/", "Spring Festival is in February."),
            ("March", "三月", "/mɑːrtʃ/", "Tree Planting Day is in March."),
            ("April", "四月", "/ˈeɪprəl/", "Easter is in April."),
            ("May", "五月", "/meɪ/", "May Day is in May."),
            ("June", "六月", "/dʒuːn/", "Children's Day is in June."),
            ("July", "七月", "/dʒuˈlaɪ/", "Summer holiday starts in July."),
            ("August", "八月", "/ˈɔːɡəst/", "It's hot in August."),
            ("September", "九月", "/sepˈtembər/", "School starts in September."),
            ("October", "十月", "/ɒkˈtəʊbər/", "National Day is in October."),
            ("November", "十一月", "/nəʊˈvembər/", "Thanksgiving is in November."),
            ("December", "十二月", "/dɪˈsembər/", "Christmas is in December."),
            ("school trip", "学校旅行", "/skuːl trɪp/", "We have a school trip in April."),
            ("sports meet", "运动会", "/spɔːrts miːt/", "When is the sports meet?"),
            # Unit 4: 生日
            ("first", "第一", "/fɜːrst/", "January is the first month."),
            ("second", "第二", "/ˈsekənd/", "February is the second month."),
            ("third", "第三", "/θɜːrd/", "March is the third month."),
            ("fourth", "第四", "/fɔːrθ/", "My birthday is on April 4th."),
            ("fifth", "第五", "/fɪfθ/", "May is the fifth month."),
            ("twelfth", "第十二", "/twelfθ/", "December is the twelfth month."),
            ("birthday", "生日", "/ˈbɜːrθdeɪ/", "When is your birthday?"),
            ("special", "特别的", "/ˈspeʃl/", "Today is a special day."),
            # Unit 5: 宠物/动物
            ("mine", "我的", "/maɪn/", "This book is mine."),
            ("yours", "你的", "/jɔːrz/", "Is this pen yours?"),
            ("his", "他的", "/hɪz/", "The bag is his."),
            ("hers", "她的", "/hɜːrz/", "The cat is hers."),
            ("theirs", "他们的", "/ðerz/", "The house is theirs."),
            ("climbing", "正在爬", "/ˈklaɪmɪŋ/", "The cat is climbing the tree."),
            ("eating", "正在吃", "/ˈiːtɪŋ/", "The dog is eating."),
            ("drinking", "正在喝", "/ˈdrɪŋkɪŋ/", "The bird is drinking water."),
            ("sleeping", "正在睡觉", "/ˈsliːpɪŋ/", "The baby is sleeping."),
            ("jumping", "正在跳", "/ˈdʒʌmpɪŋ/", "The rabbit is jumping."),
            ("running", "正在跑", "/ˈrʌnɪŋ/", "The horse is running."),
            # Unit 6: 规则
            ("keep to the right", "靠右", "/kiːp tə ðə raɪt/", "Keep to the right in the hallway."),
            ("keep your desk clean", "保持课桌干净", "/kiːp jɔːr desk kliːn/", "Keep your desk clean."),
            ("talk quietly", "安静说话", "/tɔːk ˈkwaɪətli/", "Talk quietly in the library."),
            ("no eating", "禁止吃东西", "/nəʊ ˈiːtɪŋ/", "No eating in class."),
        ],
    },
    6: {
        "上册": [
            # Unit 1: 问路
            ("science museum", "科学博物馆", "/ˈsaɪəns mjuːˈziːəm/", "Where is the science museum?"),
            ("bookstore", "书店", "/ˈbʊkstɔːr/", "I want to go to the bookstore."),
            ("hospital", "医院", "/ˈhɒspɪtl/", "The hospital is over there."),
            ("cinema", "电影院", "/ˈsɪnəmə/", "Let's go to the cinema."),
            ("post office", "邮局", "/pəʊst ˈɒfɪs/", "Where is the post office?"),
            ("go straight", "直走", "/ɡəʊ streɪt/", "Go straight for two minutes."),
            ("turn left", "左转", "/tɜːrn left/", "Turn left at the bookstore."),
            ("turn right", "右转", "/tɜːrn raɪt/", "Turn right at the hospital."),
            ("crossing", "十字路口", "/ˈkrɒsɪŋ/", "Turn left at the crossing."),
            # Unit 2: 交通方式
            ("by bus", "乘公交", "/baɪ bʌs/", "I come to school by bus."),
            ("on foot", "步行", "/ɒn fʊt/", "I go to school on foot."),
            ("by bike", "骑自行车", "/baɪ baɪk/", "He goes to work by bike."),
            ("by subway", "乘地铁", "/baɪ ˈsʌbweɪ/", "She goes to work by subway."),
            ("by train", "乘火车", "/baɪ treɪn/", "We go to Beijing by train."),
            ("by plane", "乘飞机", "/baɪ pleɪn/", "They go to Shanghai by plane."),
            ("slow down", "减速", "/sləʊ daʊn/", "Slow down and stop."),
            ("stop", "停下", "/stɒp/", "Stop at a red light."),
            ("wait", "等待", "/weɪt/", "Wait at a yellow light."),
            ("traffic lights", "交通灯", "/ˈtræfɪk laɪts/", "Look at the traffic lights."),
            # Unit 3: 周末计划
            ("visit my grandparents", "看望祖父母", "/ˈvɪzɪt maɪ ˈɡrænpeərənts/", "I'm going to visit my grandparents."),
            ("see a film", "看电影", "/siː ə fɪlm/", "We are going to see a film."),
            ("take a trip", "去旅行", "/teɪk ə trɪp/", "I'm going to take a trip."),
            ("go to the supermarket", "去超市", "/ɡəʊ tə ðə ˈsuːpərmɑːrkɪt/", "I'm going to the supermarket."),
            ("tonight", "今晚", "/təˈnaɪt/", "I'm going to read tonight."),
            ("tomorrow", "明天", "/təˈmɒrəʊ/", "What are you going to do tomorrow?"),
            ("next week", "下周", "/nekst wiːk/", "We are going camping next week."),
            ("dictionary", "词典", "/ˈdɪkʃəneri/", "I'm going to buy a dictionary."),
            ("comic book", "漫画书", "/ˈkɒmɪk bʊk/", "I'm going to buy a comic book."),
            ("word book", "单词本", "/wɜːrd bʊk/", "I need a new word book."),
            # Unit 4: 笔友
            ("hobby", "爱好", "/ˈhɒbi/", "What's your hobby?"),
            ("puzzle", "字谜", "/ˈpʌzl/", "I like doing puzzles."),
            ("hiking", "远足", "/ˈhaɪkɪŋ/", "He likes hiking."),
            ("pen pal", "笔友", "/pen pæl/", "I have a pen pal in Australia."),
            ("jasmine", "茉莉花", "/ˈdʒæzmɪn/", "Jasmine is my favorite flower."),
            ("idea", "主意", "/aɪˈdɪə/", "That's a good idea."),
            ("dancing", "跳舞", "/ˈdɑːnsɪŋ/", "She likes dancing."),
            ("singing", "唱歌", "/ˈsɪŋɪŋ/", "He likes singing."),
            ("reading stories", "读故事", "/ˈriːdɪŋ ˈstɔːriz/", "I like reading stories."),
            ("cooking Chinese food", "做中餐", "/ˈkʊkɪŋ tʃaɪˈniːz fuːd/", "She likes cooking Chinese food."),
            ("studying Chinese", "学中文", "/ˈstʌdiɪŋ tʃaɪˈniːz/", "He is studying Chinese."),
            # Unit 5: 职业
            ("factory worker", "工厂工人", "/ˈfæktəri ˈwɜːrkər/", "My father is a factory worker."),
            ("postman", "邮递员", "/ˈpəʊstmən/", "The postman delivers letters."),
            ("police officer", "警察", "/pəˈliːs ˈɒfɪsər/", "He wants to be a police officer."),
            ("businessman", "商人", "/ˈbɪznəsmæn/", "He is a businessman."),
            ("scientist", "科学家", "/ˈsaɪəntɪst/", "She wants to be a scientist."),
            ("pilot", "飞行员", "/ˈpaɪlət/", "He is a pilot."),
            ("coach", "教练", "/kəʊtʃ/", "He is a football coach."),
            ("fisherman", "渔民", "/ˈfɪʃərmən/", "He works as a fisherman."),
            ("reporter", "记者", "/rɪˈpɔːrtər/", "She is a reporter."),
            ("country", "国家", "/ˈkʌntri/", "Which country does he live in?"),
            # Unit 6: 情绪感受
            ("angry", "生气的", "/ˈæŋɡri/", "Don't be angry."),
            ("afraid", "害怕的", "/əˈfreɪd/", "I'm afraid of dogs."),
            ("worried", "担忧的", "/ˈwʌrid/", "I'm worried about the exam."),
            ("happy", "高兴的", "/ˈhæpi/", "I'm very happy today."),
            ("sad", "伤心的", "/sæd/", "She looks sad."),
            ("ill", "生病的", "/ɪl/", "He is ill today."),
            ("take a deep breath", "深吸一口气", "/teɪk ə diːp breθ/", "Take a deep breath."),
            ("count to ten", "数到十", "/kaʊnt tə ten/", "Count to ten when you are angry."),
            ("wear warm clothes", "穿暖和的衣服", "/wer wɔːrm kləʊðz/", "Wear warm clothes."),
            ("see a doctor", "看医生", "/siː ə ˈdɒktər/", "You should see a doctor."),
        ],
        "下册": [
            # Unit 1: 比较
            ("taller", "更高的", "/ˈtɔːlər/", "I'm taller than you."),
            ("shorter", "更矮的", "/ˈʃɔːrtər/", "She is shorter than me."),
            ("heavier", "更重的", "/ˈheviər/", "He is heavier than his brother."),
            ("thinner", "更瘦的", "/ˈθɪnər/", "She is thinner than before."),
            ("longer", "更长的", "/ˈlɒŋɡər/", "This ruler is longer."),
            ("bigger", "更大的", "/ˈbɪɡər/", "The elephant is bigger."),
            ("smaller", "更小的", "/ˈsmɔːlər/", "The mouse is smaller."),
            ("stronger", "更强壮的", "/ˈstrɒŋɡər/", "He is stronger than me."),
            ("younger", "更年轻的", "/ˈjʌŋɡər/", "I'm younger than you."),
            ("older", "更年长的", "/ˈəʊldər/", "She is older than me."),
            ("than", "比", "/ðæn/", "I'm taller than you."),
            ("dinosaur", "恐龙", "/ˈdaɪnəsɔːr/", "The dinosaur is very big."),
            ("shadow", "影子", "/ˈʃædəʊ/", "My shadow is longer in the afternoon."),
            ("lower", "更低的", "/ˈləʊər/", "The sun is lower in the evening."),
            # Unit 2: 过去式（一）
            ("cleaned my room", "打扫房间", "/kliːnd maɪ ruːm/", "I cleaned my room yesterday."),
            ("stayed at home", "待在家里", "/steɪd ət həʊm/", "I stayed at home last weekend."),
            ("watched TV", "看电视", "/wɒtʃt tiː viː/", "He watched TV last night."),
            ("washed my clothes", "洗衣服", "/wɒʃt maɪ kləʊðz/", "I washed my clothes on Sunday."),
            ("yesterday", "昨天", "/ˈjestərdeɪ/", "What did you do yesterday?"),
            ("last weekend", "上周末", "/lɑːst ˌwiːkˈend/", "I went fishing last weekend."),
            ("last night", "昨晚", "/lɑːst naɪt/", "I read a book last night."),
            ("last Monday", "上周一", "/lɑːst ˈmʌndeɪ/", "We had a test last Monday."),
            ("before", "以前", "/bɪˈfɔːr/", "I was short before."),
            # Unit 3: 过去式（二）
            ("went camping", "去野营", "/went ˈkæmpɪŋ/", "We went camping last weekend."),
            ("rode a bike", "骑自行车", "/rəʊd ə baɪk/", "I rode a bike in the park."),
            ("ate fresh food", "吃新鲜食物", "/eɪt freʃ fuːd/", "We ate fresh food."),
            ("took pictures", "拍照", "/tʊk ˈpɪktʃərz/", "She took many pictures."),
            ("bought gifts", "买礼物", "/bɔːt ɡɪfts/", "I bought gifts for my friends."),
            ("went swimming", "去游泳", "/went ˈswɪmɪŋ/", "We went swimming in the lake."),
            ("went fishing", "去钓鱼", "/went ˈfɪʃɪŋ/", "He went fishing with his dad."),
            ("hurt", "受伤", "/hɜːrt/", "He hurt his foot."),
            ("fell off", "从……摔下来", "/fel ɒf/", "I fell off my bike."),
            ("gift", "礼物", "/ɡɪft/", "This is a birthday gift."),
            # Unit 4: 过去与现在
            ("dining hall", "饭厅", "/ˈdaɪnɪŋ hɔːl/", "There is a new dining hall."),
            ("gym", "体育馆", "/dʒɪm/", "We have a big gym now."),
            ("ago", "以前", "/əˈɡəʊ/", "There was no gym five years ago."),
            ("grass", "草坪", "/ɡrɑːs/", "Don't walk on the grass."),
            ("star", "星星", "/stɑːr/", "I can see many stars."),
            ("easy", "容易的", "/ˈiːzi/", "This question is easy."),
            ("different", "不同的", "/ˈdɪfrənt/", "Things are different now."),
            ("active", "活跃的", "/ˈæktɪv/", "He is very active in class."),
            ("quiet", "安静的", "/ˈkwaɪət/", "She was quiet before."),
            ("look up", "查阅", "/lʊk ʌp/", "Look up the word in the dictionary."),
            ("Internet", "互联网", "/ˈɪntərnet/", "We can find information on the Internet."),
        ],
    },
}

# ═══════════════════════════════════════════════════════════════
# 生成 JSON
# ═══════════════════════════════════════════════════════════════

def gen_cn():
    result = []
    for grade, semesters in cn_data.items():
        idx = 1
        for semester, words in semesters.items():
            for word, pinyin, example in words:
                result.append({
                    "id": f"cn_g{grade}_{idx:03d}",
                    "word": word,
                    "pinyin": pinyin,
                    "grade": grade,
                    "semester": semester,
                    "example": example
                })
                idx += 1
    return result

def gen_en():
    result = []
    for grade, semesters in en_data.items():
        idx = 1
        for semester, words in semesters.items():
            for word, meaning, phonetic, example in words:
                result.append({
                    "id": f"en_g{grade}_{idx:03d}",
                    "word": word,
                    "meaning": meaning,
                    "grade": grade,
                    "semester": semester,
                    "phonetic": phonetic,
                    "example": example
                })
                idx += 1
    return result

cn_words = gen_cn()
en_words = gen_en()

print(f"语文词库: {len(cn_words)} 词")
for g in [4, 5, 6]:
    count = len([w for w in cn_words if w['grade'] == g])
    print(f"  {g}年级: {count} 词")

print(f"\n英语词库: {len(en_words)} 词")
for g in [4, 5, 6]:
    count = len([w for w in en_words if w['grade'] == g])
    print(f"  {g}年级: {count} 词")

# 写入文件
base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cn_path = os.path.join(base, 'src', 'data', 'dictation_cn_words.json')
en_path = os.path.join(base, 'src', 'data', 'dictation_en_words.json')

with open(cn_path, 'w', encoding='utf-8') as f:
    json.dump(cn_words, f, ensure_ascii=False, indent=2)
print(f"\n已写入: {cn_path}")

with open(en_path, 'w', encoding='utf-8') as f:
    json.dump(en_words, f, ensure_ascii=False, indent=2)
print(f"已写入: {en_path}")
