# -*- coding: utf-8 -*-
"""Part 2: Adjectives, Adverbs, Prepositions, Conjunctions, Pronouns"""

adj_data = [
("afraid","害怕的；担心的","adjective",1,"high",["fear","scared","nervous","brave"],["affect","offer"],"She is afraid of the dark.","a+fr(怕)+aid→害怕"),
("alive","活着的","adjective",1,"high",["live","dead","life","survive"],["living","life","lively"],"The old man is still alive.","a+live→活着的"),
("alone","独自的；单独的","adjective",1,"high",["lonely","single","independent"],["along","allow","alive"],"She lives alone.","a+one(一个)→独自的"),
("amazing","令人惊奇的","adjective",1,"high",["wonderful","surprising","incredible","boring"],["amuse","amount"],"The view from the mountain is amazing.","amaze+ing→令人惊奇的"),
("angry","生气的；愤怒的","adjective",1,"high",["mad","upset","furious","calm"],["anger","hungry","angle"],"Dont be angry with me.","an+gry→生气"),
("another","另一个；又一个","pronoun",1,"high",["other","one more","next"],["brother","mother"],"Would you like another cup of tea?","an+other→又一个"),
("anxious","焦虑的；担忧的","adjective",2,"medium",["worried","nervous","eager","calm"],["ancient","anger"],"She felt anxious about the exam results.","anx+ious→焦虑的"),
("available","可用的；有空的","adjective",2,"medium",["free","usable","ready","busy"],["acceptable","valuable"],"Are you available this weekend?","avail+able→可用的"),
("awake","醒着的","adjective",1,"high",["asleep","wake","sleep","conscious"],["aware","away"],"I was still awake at midnight.","a+wake→醒着的"),
("aware","意识到的；知道的","adjective",2,"medium",["realize","know","notice","conscious"],["awake","away"],"I was not aware of the danger.","a+ware(注意)→意识到的"),
("bad","坏的；差的","adjective",1,"high",["good","terrible","poor","wrong"],["bed","bag"],"Too much junk food is bad for you.","bad→坏的"),
("basic","基本的；基础的","adjective",1,"high",["simple","elementary","base","fundamental"],["basin","basket"],"These are the basic rules.","base+ic→基本的"),
("beautiful","美丽的；漂亮的","adjective",1,"high",["pretty","lovely","ugly","nice"],["beauty","beach"],"What a beautiful sunset!","beauty+ful→美丽的"),
("big","大的","adjective",1,"high",["large","huge","small","great"],["bag","dig"],"There is a big tree in front of our school.","big→大的"),
("bitter","苦的；痛苦的","adjective",2,"medium",["sweet","sour","sad","painful"],["better","butter"],"The medicine tastes bitter.","bitter→苦的"),
("bored","无聊的","adjective",1,"high",["boring","tired","uninterested","excited"],["boring","board"],"I felt bored during the long meeting.","bored→感到无聊的（修饰人）"),
("boring","无聊的；乏味的","adjective",1,"high",["bored","dull","interesting","exciting"],["bored","bearing"],"The movie was boring.","boring→令人无聊的（修饰物）"),
("born","出生的；天生的","adjective",1,"high",["birth","baby","bear"],["bore","burn"],"She was born in 2008.","born→出生"),
("brave","勇敢的","adjective",1,"high",["courage","bold","fearless","afraid"],["bread","break"],"The brave soldier saved many lives.","brave→勇敢的"),
("bright","明亮的；聪明的","adjective",1,"high",["light","smart","clever","dark"],["right","bring"],"The sun is very bright today.","bright→明亮的"),
("busy","忙的；繁忙的","adjective",1,"high",["free","occupied","work"],["bus","easy"],"I am busy preparing for the exam.","bus+y→忙的"),
("calm","平静的","adjective",1,"medium",["peaceful","quiet","nervous","angry"],["call","come"],"Please keep calm when there is a fire.","calm→平静的"),
("careful","小心的；仔细的","adjective",1,"high",["careless","attention","safe"],["careless","carefree"],"Be careful when you cross the road.","care+ful→小心的"),
("cheap","便宜的","adjective",1,"high",["expensive","low price","save"],["chip","cheat"],"This shirt is very cheap.","cheap→便宜的"),
("clean","干净的","adjective",1,"high",["dirty","wash","tidy","clear"],["clear","clever"],"Please keep your room clean.","clean→干净的"),
("clear","清楚的","adjective",1,"high",["clean","understand","obvious"],["clean","clever","close"],"The water in the river is clear.","clear→清楚的"),
("clever","聪明的","adjective",1,"high",["smart","bright","intelligent","stupid"],["clean","clear","climb"],"She is a clever girl.","clever→聪明的"),
("cold","冷的；感冒","adjective",1,"high",["hot","cool","warm","freezing"],["old","could","hold"],"It is very cold outside today.","cold→冷的"),
("comfortable","舒适的","adjective",1,"medium",["comfort","easy","cozy","uncomfortable"],["compare"],"This sofa is very comfortable.","comfort+able→舒适的"),
("confident","自信的","adjective",2,"medium",["sure","certain","nervous","shy"],["confidence","confuse"],"She is very confident about the exam.","confide+nt→自信的"),
("correct","正确的","adjective",1,"high",["right","wrong","fix","accurate"],["collect","connect"],"Your answer is correct.","cor+rect→正确的"),
("crazy","疯狂的","adjective",2,"medium",["mad","wild","insane","sane"],["cross","lazy"],"Are you crazy? That is too dangerous.","crazy→疯狂的"),
("dangerous","危险的","adjective",1,"high",["safe","risk","harm","danger"],["danger","delicious"],"It is dangerous to swim in the river alone.","danger+ous→危险的"),
("dark","黑暗的；深色的","adjective",1,"high",["light","night","black","bright"],["park","mark"],"The room is too dark.","dark→黑暗的"),
("dead","死的；无生命的","adjective",1,"high",["alive","die","death","living"],["dear","deal"],"The plant is dead.","dead→死的"),
("deaf","聋的","adjective",2,"medium",["blind","hear","disabled"],["death","deal"],"The old man is deaf.","deaf→聋的"),
("dear","亲爱的；贵的","adjective",1,"medium",["love","expensive","sweet"],["dead","near"],"Dear Mom, I miss you very much.","dear→亲爱的"),
("deep","深的","adjective",1,"high",["shallow","bottom","deeply"],["deer","keep","sleep"],"The river is very deep here.","deep→深的"),
("delicious","美味的","adjective",1,"high",["tasty","yummy","sweet","food"],["delicious","dangerous"],"The food here is delicious.","de+lici+ous→美味的"),
("different","不同的","adjective",1,"high",["same","various","similar","change"],["difficult","difference"],"We have different opinions.","dif+fer+ent→不同的"),
("difficult","困难的","adjective",1,"high",["hard","easy","tough","simple"],["different","difference"],"This math problem is very difficult.","difficult→困难的"),
("dirty","脏的","adjective",1,"high",["clean","wash","dust","mud"],["direct","dinner"],"Your hands are dirty.","dirty→脏的"),
("dry","干的；干燥的","adjective",1,"medium",["wet","rain","desert"],["cry","try","fly"],"The weather is very dry in winter.","dry→干的"),
("early","早的；提前","adjective",1,"high",["late","morning","first","before"],["ear","earth","earn"],"Please come to school early tomorrow.","early→早的"),
("easy","容易的","adjective",1,"high",["simple","difficult","hard"],["east","busy"],"This question is easy.","easy→容易的"),
("empty","空的","adjective",1,"high",["full","blank","nothing"],["enemy","enough"],"The box is empty.","empty→空的"),
("enough","足够的","adjective",1,"high",["sufficient","plenty","lack"],["though","tough","through"],"I have enough money to buy this book.","enough→足够的"),
("excellent","优秀的","adjective",1,"high",["great","wonderful","outstanding","perfect"],["except","excite"],"She did an excellent job.","ex+cell+ent→优秀的"),
("excited","兴奋的；激动的","adjective",1,"high",["exciting","happy","thrilled","nervous"],["exciting","excite"],"I am so excited about the trip.","excited→感到兴奋的（修饰人）"),
("exciting","令人兴奋的","adjective",1,"high",["excited","interesting","boring","amazing"],["excited","excite"],"The game was very exciting.","exciting→令人兴奋的（修饰物）"),
("expensive","昂贵的","adjective",1,"high",["cheap","costly","price","valuable"],["experience","express"],"This dress is too expensive.","expensive→昂贵的"),
("famous","著名的","adjective",1,"high",["well-known","popular","star","celebrity"],["family","frame"],"Lu Xun is a famous Chinese writer.","fam+ous→著名的"),
("far","远的","adjective",1,"high",["near","close","distance","away"],["for","farm"],"The school is not far from my home.","far→远的"),
("fast","快的","adjective",1,"high",["quick","rapid","slow","speed"],["first","last"],"He runs very fast.","fast→快的"),
("fat","胖的","adjective",1,"medium",["thin","heavy","weight","overweight"],["cat","hat","flat"],"You should eat less junk food.","fat→胖的"),
("favorite","最喜欢的","adjective",1,"high",["like","love","best","prefer"],["favor","flavor"],"My favorite subject is English.","favor+ite→最喜欢的"),
("final","最终的；决赛的","adjective",1,"high",["last","end","first","result"],["find","fine"],"What is your final decision?","final→最终的"),
("fit","健康的；适合的","adjective",1,"high",["healthy","suitable","exercise","size"],["fix","bit"],"She keeps fit by running every day.","fit→健康的"),
("flat","平坦的；公寓","adjective",1,"medium",["apartment","smooth","even","round"],["fat","flag"],"They live in a flat near the park.","flat→平坦的"),
("foreign","外国的","adjective",1,"high",["abroad","international","country","language"],["forest","forget"],"She can speak three foreign languages.","for+eign→外国的"),
("free","自由的；免费的","adjective",1,"high",["freedom","busy","no cost","liberty"],["tree","three","fee"],"The ticket is free for children.","free→自由的"),
("fresh","新鲜的","adjective",1,"medium",["new","clean","food","air"],["flash","flesh"],"The vegetables are very fresh.","fresh→新鲜的"),
("friendly","友好的","adjective",1,"high",["kind","nice","warm","unfriendly"],["friend","friendship"],"The people here are very friendly.","friend+ly→友好的"),
("full","满的；完整的","adjective",1,"high",["empty","complete","fill"],["fall","fill"],"The cup is full of water.","full→满的"),
("funny","有趣的；好笑的","adjective",1,"high",["fun","humorous","laugh","boring"],["fun","sunny","money"],"The story is very funny.","funny→好笑的"),
("gentle","温柔的","adjective",2,"medium",["kind","soft","mild","rough"],["gently","genius"],"She has a gentle voice.","gentle→温柔的"),
("glad","高兴的","adjective",1,"high",["happy","pleased","joyful","sad"],["glass","glob"],"I am glad to see you.","glad→高兴的"),
("good","好的","adjective",1,"high",["great","nice","well","bad"],["wood","food","foot"],"She is a good student.","good→好的"),
("great","伟大的；极好的","adjective",1,"high",["wonderful","big","excellent","good"],["green","greet"],"That is a great idea!","great→伟大的"),
("green","绿色的","adjective",1,"high",["color","grass","tree","environment"],["great","grey"],"The hills are green in spring.","green→绿色的"),
("happy","快乐的","adjective",1,"high",["glad","joyful","sad","pleased"],["happen","heavy"],"Happy New Year!","happy→快乐的"),
("hard","困难的；努力地","adjective",1,"high",["difficult","tough","easy","soft"],["card","hardly"],"This math problem is too hard.","hard→困难的"),
("hardly","几乎不","adverb",1,"high",["almost not","barely","scarcely"],["hard","hard"],"I can hardly believe my eyes.","hard+ly→几乎不"),
("healthy","健康的","adjective",1,"high",["health","fit","well","sick"],["health","wealthy"],"Eating vegetables keeps you healthy.","health+y→健康的"),
("heavy","重的","adjective",1,"high",["light","weight","fat","thin"],["head","hear"],"This box is too heavy for me to carry.","heavy→重的"),
("high","高的","adjective",1,"high",["tall","low","top","sky"],["height","night","right"],"The mountain is very high.","high→高的"),
("honest","诚实的","adjective",1,"medium",["truthful","lie","trust","dishonest"],["honor","hour"],"He is an honest person.","honest→诚实的"),
("horrible","可怕的","adjective",2,"medium",["terrible","awful","scary","bad"],["horrible","horror"],"The weather was horrible yesterday.","horror+ible→可怕的"),
("hot","热的","adjective",1,"high",["warm","cold","cool","heat"],["hit","hat"],"It is very hot in summer.","hot→热的"),
("huge","巨大的","adjective",1,"medium",["big","large","enormous","small"],["hug","age"],"The elephant is a huge animal.","huge→巨大的"),
("hungry","饥饿的","adjective",1,"high",["eat","food","starve","thirsty"],["hundred","anger"],"I am very hungry. Lets eat something.","hungry→饥饿的"),
("important","重要的","adjective",1,"high",["significant","key","unimportant","vital"],["import","impossible"],"English is an important subject.","import+ant→重要的"),
("impossible","不可能的","adjective",1,"medium",["possible","cannot","unlikely"],["possible","importance"],"Nothing is impossible.","im+possible→不可能的"),
("interesting","有趣的","adjective",1,"high",["boring","fun","exciting","dull"],["interest","internet"],"This book is very interesting.","interest+ing→有趣的"),
("kind","善良的；种类","adjective",1,"high",["nice","friendly","cruel","kindness"],["king","mind"],"She is a very kind person.","kind→善良的"),
("large","大的","adjective",1,"high",["big","huge","small","great"],["language","largely"],"China is a large country.","large→大的"),
("late","迟的；晚的","adjective",1,"high",["early","on time","delay","slow"],["gate","date","late"],"Sorry I am late.","late→迟的"),
("lazy","懒惰的","adjective",2,"medium",["hardworking","idle","busy","active"],["crazy","lady"],"Dont be so lazy.","lazy→懒惰的"),
("little","小的；少的","adjective",1,"high",["small","tiny","big","much"],["battle","bottle"],"There is a little water left.","little→小的"),
("lonely","孤独的；寂寞的","adjective",1,"high",["alone","sad","isolated","happy"],["long","lovely"],"She lives alone but she doesnt feel lonely.","lone+ly→孤独的"),
("long","长的","adjective",1,"high",["short","length","tall","wide"],["wrong","song"],"The river is very long.","long→长的"),
("loud","大声的","adjective",1,"medium",["noisy","quiet","soft","sound"],["cloud","proud"],"The music is too loud.","loud→大声的"),
("low","低的","adjective",1,"high",["high","short","deep","bottom"],["now","cow"],"The temperature is very low today.","low→低的"),
("lucky","幸运的","adjective",1,"medium",["fortunate","luck","unlucky","happy"],["luck","lazy"],"I was lucky to pass the exam.","luck+y→幸运的"),
("mad","疯的；生气的","adjective",2,"medium",["angry","crazy","insane","calm"],["bad","sad"],"Are you mad?","mad→生气的"),
("main","主要的","adjective",2,"medium",["major","important","primary","minor"],["man","many"],"This is the main reason.","main→主要的"),
("mental","精神的；心理的","adjective",2,"medium",["mind","physical","brain","think"],["mention","metal"],"Mental health is as important as physical health.","ment+al→精神的"),
("modern","现代的","adjective",1,"medium",["new","contemporary","old","ancient"],["model","manner"],"We live in a modern city.","modern→现代的"),
("narrow","狭窄的","adjective",2,"medium",["wide","thin","broad","small"],["arrow","sorrow"],"The road is too narrow.","narrow→狭窄的"),
("national","国家的；民族的","adjective",2,"medium",["country","international","nation"],["natural","native"],"It is a national holiday.","nation+al→国家的"),
("natural","自然的","adjective",2,"medium",["nature","artificial","normal"],["national","native"],"It is natural to make mistakes.","nature+al→自然的"),
("necessary","必要的","adjective",1,"medium",["important","essential","need","unnecessary"],["necessary","need"],"Sleep is necessary for good health.","necessary→必要的"),
("nervous","紧张的","adjective",1,"high",["anxious","worried","calm","scared"],["nerve","serious"],"She felt nervous before the exam.","nervous→紧张的"),
("new","新的","adjective",1,"high",["old","fresh","recent","modern"],["now","knew"],"I bought a new phone.","new→新的"),
("nice","好的；美好的","adjective",1,"high",["good","kind","pleasant","wonderful"],["nine","ice"],"She is a nice person.","nice→好的"),
("noisy","吵闹的","adjective",1,"medium",["loud","quiet","noise","peace"],["noise","no"],"The classroom is too noisy.","noisy→吵闹的"),
("normal","正常的","adjective",1,"high",["abnormal","usual","regular","strange"],["natural","formal"],"Everything is back to normal.","normal→正常的"),
("old","旧的；老的","adjective",1,"high",["new","young","ancient","age"],["cold","hold"],"The old man lives alone.","old→旧的"),
("only","唯一的；只","adjective",1,"high",["single","alone","just","one"],["open","own"],"He is the only child in his family.","only→唯一的"),
("open","开放的","adjective",1,"high",["close","shut","public"],["often","only"],"The door is open.","open→开放的"),
("ordinary","普通的","adjective",2,"medium",["normal","common","special","usual"],["order","organ"],"He is an ordinary student.","ordinary→普通的"),
("other","其他的","pronoun",1,"high",["another","else","different","same"],["another","bother"],"Do you have any other questions?","other→其他的"),
("outdoor","户外的","adjective",2,"medium",["outside","indoor","open","outside"],["door","outdoors"],"I like outdoor activities.","outdoor→户外的"),
("outside","外面的","adjective",1,"high",["inside","outdoor","external","indoor"],["outside","outdoors"],"It is cold outside.","outside→外面的"),
("own","自己的","adjective",1,"high",["possess","personal","have","belong"],["owe","own"],"I saw it with my own eyes.","own→自己的"),
("painful","痛苦的","adjective",2,"medium",["pain","hurt","ache","comfortable"],["paintful","careful"],"The injury was very painful.","pain+ful→痛苦的"),
("patient","耐心的；病人","adjective",1,"medium",["impatient","wait","calm","tolerant"],["patience","patient"],"Please be patient.","patient→耐心的"),
("perfect","完美的","adjective",1,"medium",["flawless","ideal","excellent","imperfect"],["perform","perhaps"],"The weather is perfect today.","per+fect(做)→完全做好→完美的"),
("personal","个人的","adjective",2,"medium",["private","own","individual","public"],["person","personnel"],"This is my personal opinion.","person+al→个人的"),
("pleasant","令人愉快的","adjective",2,"medium",["pleasant","enjoyable","comfortable","unpleasant"],["please","pleasure"],"We had a pleasant trip.","pleasant→令人愉快的"),
("pleased","高兴的","adjective",1,"medium",["happy","glad","pleasure","sad"],["please","pleased"],"I am pleased to meet you.","pleased→高兴的"),
("polite","有礼貌的","adjective",1,"high",["rude","impolite","manners","kind"],["police","politics"],"He is a polite boy.","polite→有礼貌的"),
("poor","贫穷的；可怜的","adjective",1,"high",["rich","poverty","bad","low"],["pool","door"],"The poor family needs help.","poor→贫穷的"),
("popular","受欢迎的","adjective",1,"high",["famous","well-liked","common","unpopular"],["population","popular"],"This song is very popular.","popular→受欢迎的"),
("possible","可能的","adjective",1,"high",["impossible","likely","probable","certain"],["impossible","possible"],"Everything is possible.","possible→可能的"),
("powerful","强大的","adjective",2,"medium",["strong","weak","mighty","force"],["power","wonderful"],"China is a powerful country.","power+ful→强大的"),
("precious","珍贵的","adjective",2,"medium",["valuable","treasure","rare","cheap"],["price","previous"],"Time is precious.","precious→珍贵的"),
("pretty","漂亮的","adjective",1,"high",["beautiful","lovely","ugly","cute"],["prepare","protect"],"She is very pretty.","pretty→漂亮的"),
("private","私人的","adjective",2,"medium",["public","personal","secret","own"],["previous","price"],"This is a private matter.","private→私人的"),
("probable","很可能的","adjective",2,"medium",["possible","likely","unlikely","certain"],["probably","possible"],"It is probable that it will rain.","probable→很可能的"),
("proper","合适的；正确的","adjective",2,"medium",["correct","suitable","right","wrong"],["property","propose"],"Please use the proper tool.","proper→合适的"),
("proud","骄傲的","adjective",1,"high",["pride","arrogant","ashamed","pleased"],["pride","prove"],"She is proud of her son.","proud→骄傲的"),
("public","公共的","adjective",1,"high",["private","open","common","people"],["publish","punish"],"This is a public park.","public→公共的"),
("pure","纯净的","adjective",2,"medium",["clean","clear","pure","mixed"],["sure","cure"],"The water is pure and clean.","pure→纯净的"),
("quiet","安静的","adjective",1,"high",["silent","noisy","calm","loud"],["quite","quarter"],"Please keep quiet.","quiet→安静的"),
("rapid","迅速的","adjective",2,"medium",["fast","quick","slow","speed"],["rare","rapid"],"There was rapid economic growth.","rapid→迅速的"),
("rare","稀有的","adjective",2,"medium",["common","unusual","scarce","often"],["rare","rate"],"This is a rare opportunity.","rare→稀有的"),
("ready","准备好的","adjective",1,"high",["prepare","set","go","done"],["already","really"],"Are you ready?","ready→准备好的"),
("real","真的；真实的","adjective",1,"high",["true","actual","fake","real"],["really","read"],"This is a real story.","real→真的"),
("regular","定期的；有规律的","adjective",2,"medium",["normal","usual","irregular","routine"],["regular","rule"],"He goes to school on a regular basis.","regular→定期的"),
("responsible","负责任的","adjective",2,"medium",["duty","blame","care","irresponsible"],["response","respect"],"He is a responsible person.","responsible→负责任的"),
("rich","富有的","adjective",1,"high",["poor","wealthy","money","poverty"],["reach","right"],"He is a rich businessman.","rich→富有的"),
("right","正确的；右边的","adjective",1,"high",["correct","wrong","left","true"],["write","night"],"You are right about that.","right→正确的"),
("rough","粗糙的；粗暴的","adjective",2,"medium",["smooth","tough","soft","gentle"],["round","tough"],"The road was rough.","rough→粗糙的"),
("round","圆的","adjective",1,"medium",["circle","ball","round","square"],["around","sound"],"The table is round.","round→圆的"),
("sad","伤心的","adjective",1,"high",["unhappy","upset","cry","happy"],["said","bad"],"The news made me very sad.","sad→伤心的"),
("safe","安全的","adjective",1,"high",["dangerous","protect","secure","risk"],["save","safe"],"Please keep safe.","safe→安全的"),
("satisfied","满意的","adjective",2,"medium",["pleased","happy","disappointed","content"],["satisfy","satisfied"],"She was satisfied with the result.","satisfied→满意的"),
("scared","害怕的","adjective",1,"high",["afraid","fear","brave","nervous"],["scarce","score"],"The little girl was scared of the dark.","scared→害怕的"),
("serious","严肃的；认真的","adjective",1,"high",["serious","earnest","silly","joke"],["series","service"],"This is a serious problem.","serious→严肃的"),
("several","几个","adjective",1,"high",["some","many","few","a few"],["severe","separate"],"I have been there several times.","several→几个"),
("short","短的；矮的","adjective",1,"high",["tall","long","brief","little"],["should","shoot"],"She has short hair.","short→短的"),
("shy","害羞的","adjective",1,"medium",["timid","nervous","bold","confident"],["sky","shy"],"She is too shy to speak in public.","shy→害羞的"),
("sick","生病的","adjective",1,"high",["ill","health","disease","well"],["sick","side"],"I feel sick today.","sick→生病的"),
("silent","沉默的","adjective",2,"medium",["quiet","noiseless","still","noisy"],["silence","silver"],"The room was completely silent.","silent→沉默的"),
("similar","相似的","adjective",2,"medium",["same","alike","different","like"],["simple","smile"],"Our ideas are quite similar.","similar→相似的"),
("simple","简单的","adjective",1,"high",["easy","difficult","complicated","plain"],["single","similar"],"The question is simple.","simple→简单的"),
("single","单一的","adjective",1,"medium",["alone","only","double","single"],["simple","since"],"She is still single.","single→单一的"),
("slight","轻微的","adjective",2,"medium",["small","minor","tiny","heavy"],["slight","slide"],"There is a slight difference.","slight→轻微的"),
("slow","慢的","adjective",1,"high",["fast","quick","rapid","speed"],["slow","snow"],"Please drive slowly.","slow→慢的"),
("small","小的","adjective",1,"high",["big","large","tiny","little"],["smell","smile"],"I have a small room.","small→小的"),
("smooth","光滑的","adjective",2,"medium",["rough","soft","even","flat"],["smile","snow"],"The road is smooth.","smooth→光滑的"),
("soft","柔软的","adjective",1,"high",["hard","tough","gentle","rough"],["soft","sold"],"The pillow is very soft.","soft→柔软的"),
("sorry","抱歉的","adjective",1,"high",["apologize","sad","regret","excuse"],["story","worry"],"I am sorry for being late.","sorry→抱歉的"),
("special","特别的","adjective",1,"high",["special","particular","ordinary","usual"],["specific","especially"],"Today is a special day.","special→特别的"),
("still","静止的；仍然","adjective",1,"high",["quiet","motionless","yet","calm"],["still","still"],"Please stand still.","still→静止的"),
("strange","奇怪的","adjective",1,"high",["odd","unusual","normal","familiar"],["string","strong"],"I heard a strange noise.","strange→奇怪的"),
("strict","严格的","adjective",1,"medium",["severe","tough","easy","loose"],["strike","straight"],"Our teacher is very strict.","strict→严格的"),
("strong","强壮的","adjective",1,"high",["weak","powerful","tough","feeble"],["string","strange"],"He is very strong.","strong→强壮的"),
("stupid","愚蠢的","adjective",2,"medium",["foolish","smart","clever","wise"],["study","student"],"That was a stupid mistake.","stupid→愚蠢的"),
("such","这样的","adjective",1,"high",["so","like","this","such"],["much","such"],"I have never seen such a beautiful place.","such→这样的"),
("suitable","合适的","adjective",2,"medium",["fit","proper","appropriate","right"],["suit","suitable"],"This dress is not suitable for the party.","suitable→合适的"),
("sure","确定的","adjective",1,"high",["certain","confident","doubt","positive"],["sure","sugar"],"I am sure about this.","sure→确定的"),
("surprised","惊讶的","adjective",1,"high",["amazed","shocked","surprise","excited"],["surprising","surprised"],"I was surprised by the news.","surprised→惊讶的"),
("surprising","令人惊讶的","adjective",1,"high",["surprised","amazing","unexpected","expected"],["surprising","surprised"],"The result was surprising.","surprising→令人惊讶的"),
("sweet","甜的","adjective",1,"high",["sour","bitter","delicious","sugar"],["sweat","sweep"],"The cake tastes sweet.","sweet→甜的"),
("tall","高的","adjective",1,"high",["short","high","long","height"],["tall","talk"],"He is a tall boy.","tall→高的"),
("terrible","可怕的","adjective",1,"high",["horrible","awful","bad","wonderful"],["terrible","terrific"],"The weather was terrible.","terrible→可怕的"),
("thick","厚的；粗的","adjective",1,"medium",["thin","fat","dense","heavy"],["thin","think"],"The book is very thick.","thick→厚的"),
("thin","薄的；瘦的","adjective",1,"high",["thick","fat","slim","narrow"],["thing","think"],"She is very thin.","thin→薄的"),
("thirsty","渴的","adjective",1,"high",["hungry","drink","water","dry"],["thirty","thirst"],"I am very thirsty.","thirsty→渴的"),
("tired","累的","adjective",1,"high",["exhausted","sleepy","energetic","rest"],["tried","tired"],"I am very tired after the long walk.","tired→累的"),
("tiny","极小的","adjective",2,"medium",["small","little","tiny","huge"],["tiny","tidy"],"There was a tiny hole in the wall.","tiny→极小的"),
("total","总的；全部的","adjective",2,"medium",["whole","complete","entire","partial"],["together","tall"],"The total cost is 200 yuan.","total→总的"),
("traditional","传统的","adjective",2,"medium",["modern","custom","culture","old"],["tradition","traditional"],"This is a traditional Chinese festival.","traditional→传统的"),
("true","真的；真实的","adjective",1,"high",["real","false","correct","wrong"],["trust","tree"],"Is this story true?","true→真的"),
("typical","典型的","adjective",2,"medium",["normal","usual","special","ordinary"],["type","typically"],"This is a typical example.","typical→典型的"),
("ugly","丑的","adjective",2,"medium",["beautiful","pretty","handsome","cute"],["ugly","bug"],"Dont say that. It is ugly.","ugly→丑的"),
("unable","不能的","adjective",1,"high",["able","can","possible","capable"],["unable","unusual"],"She was unable to come.","un+able→不能的"),
("uncomfortable","不舒服的","adjective",1,"medium",["comfortable","uneasy","comfort","pleasant"],["uncomfortable"],"This chair is uncomfortable.","uncomfortable→不舒服的"),
("unfair","不公平的","adjective",2,"medium",["fair","just","unjust","equal"],["unfair","unhappy"],"That is unfair.","unfair→不公平的"),
("unhappy","不开心的","adjective",1,"medium",["sad","unhappy","unhappy","glad"],["unhappy","unhealthy"],"She looks unhappy.","unhappy→不开心的"),
("unhealthy","不健康的","adjective",2,"medium",["healthy","sick","ill","well"],["unhealthy","unhappy"],"Junk food is unhealthy.","unhealthy→不健康的"),
("unlucky","不幸的","adjective",2,"medium",["lucky","fortunate","unfortunate","bad"],["unlucky","unlike"],"I was unlucky today.","unlucky→不幸的"),
("unusual","不寻常的","adjective",2,"medium",["usual","strange","common","normal"],["unusual","until"],"This is an unusual situation.","unusual→不寻常的"),
("upset","难过的；心烦的","adjective",1,"high",["sad","unhappy","angry","worried"],["set","upset"],"She was upset about the news.","upset→难过的"),
("useful","有用的","adjective",1,"high",["helpful","useless","valuable","practical"],["useful","usual"],"English is very useful.","use+ful→有用的"),
("useless","无用的","adjective",1,"medium",["useful","valuable","pointless","helpful"],["useless","useful"],"This tool is useless.","useless→无用的"),
("usual","通常的","adjective",1,"high",["normal","regular","unusual","common"],["usually","unusual"],"I will meet you at the usual time.","usual→通常的"),
("valuable","有价值的","adjective",2,"medium",["precious","value","worth","cheap"],["available","variable"],"Time is the most valuable thing.","value+able→有价值的"),
("various","各种各样的","adjective",2,"medium",["different","many","several","kind"],["various","obvious"],"There are various kinds of flowers.","various→各种各样的"),
("warm","温暖的","adjective",1,"high",["hot","cold","cool","heat"],["warm","warn"],"The water is warm.","warm→温暖的"),
("weak","弱的","adjective",1,"high",["strong","feeble","powerful","tough"],["week","wealth"],"He felt weak after the illness.","weak→弱的"),
("wealthy","富有的","adjective",2,"medium",["rich","poor","wealthy","money"],["healthy","wealthy"],"He comes from a wealthy family.","wealth+y→富有的"),
("wet","湿的","adjective",1,"high",["dry","water","rain","moist"],["west","wet"],"My clothes got wet in the rain.","wet→湿的"),
("whole","整个的","adjective",1,"high",["entire","complete","all","part"],["while","whose"],"The whole class went on a trip.","whole→整个的"),
("wide","宽的","adjective",1,"high",["broad","narrow","width","long"],["wild","wife"],"The road is very wide.","wide→宽的"),
("wild","野生的","adjective",1,"medium",["tame","crazy","natural","domestic"],["wild","will"],"There are wild animals in the forest.","wild→野生的"),
("wise","明智的","adjective",2,"medium",["smart","clever","foolish","stupid"],["wish","wide"],"She is a wise woman.","wise→明智的"),
("wonderful","精彩的","adjective",1,"high",["great","excellent","amazing","terrible"],["wonder","wonderful"],"The trip was wonderful.","wonder+ful→精彩的"),
("wooden","木制的","adjective",2,"medium",["wood","tree","material"],["would","wooden"],"This is a wooden table.","wooden→木制的"),
("worried","担心的","adjective",1,"high",["anxious","worry","nervous","calm"],["worry","sorry"],"She looked worried.","worried→担心的"),
("wrong","错误的","adjective",1,"high",["right","correct","mistake","error"],["write","long"],"What is wrong with you?","wrong→错误的"),
("young","年轻的","adjective",1,"high",["old","youth","new","aged"],["your","young"],"She is a young teacher.","young→年轻的"),
]

for d in adj_data:
    add(*d)
print(f"Part 2 loaded: {len(adj_data)} words, total: {len(words)}")
