#!/usr/bin/env python3
"""Generate words_network_j2.json - Part 2: Adjectives + Nouns (280 words)"""
import json

# Load part1
with open('/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/_part1_cache.json','r') as f:
    words = json.load(f)

def add(w, m, cat, tier, freq, assoc, conf, ex, tip):
    words[w] = {
        'word': w, 'meaning': m, 'category': cat,
        'tier': tier, 'frequency': freq,
        'associations': assoc, 'confusables': conf,
        'example': ex, 'memory_tip': tip
    }

A='adjective'; N='noun'; Adv='adverb'; Prep='preposition'
Conj='conjunction'; Pron='pronoun'; V='verb'

# === ADJECTIVES TIER 1 (100) ===
entries = [
("able","有能力的",A,1,"high",["capable","can","skill","unable"],["table","acceptable"],"She is able to speak three languages.","able→有能力的"),
("accident","事故；意外",N,1,"high",["crash","mistake","injury","safety"],["accidental","accidentally"],"He had a car accident.","accident→事故"),
("afraid","害怕的",A,1,"high",["scared","fear","brave","terrified"],["affect","afford"],"She is afraid of the dark.","afraid→害怕的"),
("alive","活着的",A,1,"high",["dead","living","life","well"],["life","like"],"The old man is still alive.","alive→活着的"),
("alone","独自的；单独的",A,1,"high",["lonely","single","together","only"],["along","allow"],"I was alone at home.","alone→独自的"),
("amazing","令人惊奇的",A,1,"high",["wonderful","surprising","great","incredible"],["amaze","amount"],"The view is amazing.","amazing→令人惊奇的"),
("angry","生气的",A,1,"high",["mad","furious","happy","calm"],["anger","angle"],"He was very angry.","angry→生气的"),
("another","另一个的",A,1,"high",["other","one more","different"],["other","brother"],"Would you like another cup?","an+other→另一个"),
("anxious","焦虑的；担心的",A,2,"medium",["worried","nervous","calm","eager"],["anxiety","ancient"],"She felt anxious about the exam.","anxious→焦虑的"),
("available","可用的；有空的",A,2,"medium",["free","usable","ready","busy"],["ability","acceptable"],"Are you available tomorrow?","available→可用的"),
("awake","醒着的",A,1,"medium",["sleep","wake","conscious"],["away","aware"],"I was still awake at midnight.","a+wake→醒着的"),
("bad","坏的；糟糕的",A,1,"high",["good","terrible","poor","wrong"],["bed","bag"],"The weather was bad yesterday.","bad→坏的"),
("beautiful","美丽的",A,1,"high",["pretty","lovely","ugly","handsome"],["beauty","beast"],"The garden is beautiful.","beautiful→美丽的"),
("big","大的",A,1,"high",["large","huge","small","little"],["pig","dig"],"Beijing is a very big city.","big→大的"),
("boring","无聊的",A,1,"high",["interesting","dull","tired","exciting"],["bore","born"],"The movie was boring.","boring→无聊的"),
("brave","勇敢的",A,1,"high",["courageous","bold","fear","coward"],["bread","break"],"He is a brave soldier.","brave→勇敢的"),
("bright","明亮的；聪明的",A,1,"high",["dark","smart","clever","light"],["bring","right"],"She is a bright student.","bright→明亮的"),
("busy","忙碌的",A,1,"high",["free","occupied","lazy","working"],["bus","buy"],"My mother is always busy.","busy→忙碌的"),
("calm","平静的",A,1,"high",["peaceful","quiet","nervous","still"],["call","came"],"Keep calm.","calm→平静的"),
("careful","小心的",A,1,"high",["careless","cautious","attention","safe"],["care","carry"],"Be careful when crossing the road.","care+ful→小心的"),
("careless","粗心的",A,1,"high",["careful","mistake","attention"],["care","careful"],"He made a careless mistake.","careless→粗心的"),
("cheap","便宜的",A,1,"high",["expensive","low price","costly"],["cheat","chair"],"This shirt is very cheap.","cheap→便宜的"),
("cheerful","快乐的；高兴的",A,2,"medium",["happy","glad","sad","cheer"],["cheer","cheap"],"She has a cheerful smile.","cheerful→快乐的"),
("clear","清楚的；晴朗的",A,1,"high",["obvious","clean","unclear","bright"],["clean","close"],"The water is very clear.","clear→清楚的"),
("clever","聪明的",A,1,"high",["smart","bright","stupid","wise"],["clear","climb"],"She is a clever girl.","clever→聪明的"),
("cold","冷的",A,1,"high",["hot","warm","cool","freeze"],["old","hold"],"It is very cold in winter.","cold→冷的"),
("comfortable","舒适的",A,1,"high",["comfort","uncomfortable","cozy","relax"],["comfort","compare"],"This sofa is very comfortable.","comfortable→舒适的"),
("common","普通的；共同的",A,1,"high",["usual","ordinary","rare","normal"],["come","company"],"This is a common mistake.","common→普通的"),
("communicate","交流；沟通",V,1,"high",["talk","speak","share","connect"],["communication","community"],"We communicate by email.","communicate→交流"),
("confident","自信的",A,2,"medium",["sure","certain","nervous","doubt"],["confidence","confuse"],"She is confident about the test.","confident→自信的"),
("confused","困惑的",A,2,"medium",["puzzled","understand","clear","mix"],["confuse","confident"],"I am confused about the math problem.","confused→困惑的"),
("consider","考虑",V,2,"medium",["think about","discuss","decide"],["considerable","consideration"],"Please consider my suggestion.","consider→考虑"),
("cool","凉爽的；酷的",A,1,"high",["cold","warm","hot","nice"],["cool","school"],"It is cool in autumn.","cool→凉爽的"),
("correct","正确的",A,1,"high",["right","wrong","accurate","mistake"],["collect","connect"],"Your answer is correct.","correct→正确的"),
("crazy","疯狂的",A,2,"medium",["mad","insane","sane","wild"],["crazy","lazy"],"That's a crazy idea.","crazy→疯狂的"),
("dangerous","危险的",A,1,"high",["safe","harmful","risky","careful"],["danger","delicious"],"Swimming in the river is dangerous.","dangerous→危险的"),
("dead","死的",A,1,"high",["alive","death","die","living"],["deal","dear"],"The plant is dead.","dead→死的"),
("deaf","聋的",A,2,"low",["blind","hear","mute","sound"],["dead","dear"],"The old man is deaf.","deaf→聋的"),
("dear","亲爱的；贵的",A,2,"medium",["expensive","love","cheap"],["dear","death"],"She is a dear friend.","dear→亲爱的"),
("deep","深的",A,1,"high",["shallow","profound","deeply"],["deer","keep"],"The river is very deep.","deep→深的"),
("delicious","美味的",A,1,"high",["tasty","yummy","delicious","awful"],["delicious","delicate"],"The food tastes delicious.","delicious→美味的"),
("different","不同的",A,1,"high",["same","various","similar","unlike"],["difference","difficult"],"We have different opinions.","different→不同的"),
("difficult","困难的",A,1,"high",["hard","easy","tough","simple"],["difficulty","different"],"This question is difficult.","difficult→困难的"),
("dirty","脏的",A,1,"high",["clean","filthy","messy"],["dirt","dinner"],"Your hands are dirty.","dirty→脏的"),
("dry","干的",A,1,"high",["wet","arid","moist"],["dry","try"],"The ground is dry.","dry→干的"),
("early","早的",A,1,"high",["late","first","morning"],["earth","easy"],"I get up early every day.","early→早的"),
("easy","容易的",A,1,"high",["difficult","hard","simple","tough"],["easy","east"],"This test is easy.","easy→容易的"),
("effective","有效的",A,2,"medium",["useful","efficient","result"],["effect","effort"],"This method is very effective.","effective→有效的"),
("either","两者之一",A,2,"medium",["neither","both","or","also"],["neither","ether"],"You can choose either one.","either→两者之一"),
("empty","空的",A,1,"high",["full","blank","vacant"],["enter","enemy"],"The box is empty.","empty→空的"),
("enormous","巨大的",A,2,"medium",["huge","big","small","tiny"],["normal","enough"],"The whale is enormous.","enormous→巨大的"),
("enough","足够的",A,1,"high",["sufficient","plenty","lack","adequate"],["though","touch"],"I have enough money.","enough→足够的"),
("especially","特别地；尤其",Adv,1,"high",["particularly","specially","especially","mainly"],["special","especial"],"I love fruit, especially apples.","especially→特别地"),
("excellent","极好的",A,1,"high",["great","wonderful","perfect","good"],["except","excite"],"She got an excellent grade.","excellent→极好的"),
("exciting","令人兴奋的",A,1,"high",["boring","thrilling","amazing","interesting"],["excite","excited"],"The trip was exciting.","exciting→令人兴奋的"),
("expensive","昂贵的",A,1,"high",["cheap","costly","price","dear"],["experience","explain"],"This phone is too expensive.","expensive→昂贵的"),
("experience","经验；经历",N,1,"high",["knowledge","practice","skill"],["experiment","experienced"],"She has a lot of teaching experience.","experience→经验"),
("expert","专家",N,2,"medium",["professional","specialist","beginner"],["expect","export"],"He is an expert in science.","expert→专家"),
("fair","公平的；合理的",A,1,"high",["unfair","just","equal","reasonable"],["fail","far"],"That is not fair.","fair→公平的"),
("famous","著名的",A,1,"high",["well-known","popular","unknown","great"],["fame","family"],"She is a famous singer.","famous→著名的"),
("fantastic","极好的；奇妙的",A,2,"medium",["wonderful","great","amazing","excellent"],["fantasy","fancy"],"You did a fantastic job.","fantastic→极好的"),
("fast","快的；快速的",A,1,"high",["quick","rapid","slow","speedy"],["last","past"],"He runs very fast.","fast→快的"),
("fat","胖的",A,1,"high",["thin","overweight","heavy"],["cat","hat"],"The cat is very fat.","fat→胖的"),
("favorite","最喜欢的",A,1,"high",["like best","prefer","love"],["favor","fair"],"What is your favorite color?","favorite→最喜欢的"),
("final","最后的；最终的",A,1,"high",["last","end","first","beginning"],["fine","find"],"This is my final decision.","final→最后的"),
("fine","好的；精美的",A,1,"high",["good","okay","well","nice"],["find","five"],"I am fine, thank you.","fine→好的"),
("fit","健康的；适合的",A,1,"high",["healthy","suitable","sick","proper"],["fix","bit"],"She keeps fit by running.","fit→健康的"),
("flat","平坦的；公寓",A,1,"high",["smooth","level","round"],["flag","float"],"The road is flat.","flat→平坦的"),
("foreign","外国的",A,1,"high",["international","abroad","domestic","home"],["forest","forget"],"She speaks three foreign languages.","foreign→外国的"),
("free","自由的；免费的",A,1,"high",["busy","freedom","cost","liberty"],["tree","three"],"The tickets are free.","free→自由的"),
("fresh","新鲜的",A,1,"high",["new","clean","stale","old"],["friend","front"],"These vegetables are fresh.","fresh→新鲜的"),
("friendly","友好的",A,1,"high",["kind","nice","unfriendly","warm"],["friend","friendship"],"She is very friendly.","friendly→友好的"),
("full","满的；完整的",A,1,"high",["empty","whole","complete"],["fill","fall"],"The glass is full.","full→满的"),
("funny","有趣的；好笑的",A,1,"high",["interesting","amusing","boring","serious"],["fun","fine"],"The joke was very funny.","funny→有趣的"),
("gentle","温柔的；轻柔的",A,2,"medium",["soft","kind","rough","mild"],["gentleman","general"],"She has a gentle voice.","gentle→温柔的"),
("glad","高兴的",A,1,"high",["happy","pleased","sad","sorry"],["glad","glass"],"I am glad to see you.","glad→高兴的"),
("good","好的",A,1,"high",["bad","great","nice","well"],["good","food"],"She is good at math.","good→好的"),
("great","伟大的；极好的",A,1,"high",["big","wonderful","terrible","huge"],["green","grow"],"Great idea!","great→伟大的"),
("handsome","英俊的",A,2,"medium",["beautiful","good-looking","ugly","pretty"],["hand","some"],"He is a handsome boy.","handsome→英俊的"),
("happy","快乐的",A,1,"high",["sad","glad","joyful","pleased"],["happen","hard"],"She looks very happy.","happy→快乐的"),
("hard","困难的；硬的",A,1,"high",["difficult","soft","easy","tough"],["hard","hardly"],"This test is hard.","hard→困难的"),
("healthy","健康的",A,1,"high",["health","sick","fit","well"],["health","heavy"],"We should eat healthy food.","healthy→健康的"),
("heavy","重的",A,1,"high",["light","weight","big","small"],["health","heart"],"This box is too heavy.","heavy→重的"),
("helpful","有帮助的",A,1,"high",["useful","kind","useless","kind"],["help","hope"],"Thank you for being so helpful.","helpful→有帮助的"),
("honest","诚实的",A,1,"high",["truthful","sincere","dishonest","lie"],["honor","honey"],"He is an honest person.","honest→诚实的"),
("huge","巨大的",A,1,"high",["big","large","enormous","tiny"],["huge","hug"],"The elephant is huge.","huge→巨大的"),
("humorous","幽默的",A,2,"medium",["funny","witty","serious","boring"],["humor","human"],"Our teacher is very humorous.","humorous→幽默的"),
("hungry","饥饿的",A,1,"high",["thirsty","food","eat","full"],["hunger","hunt"],"I am very hungry.","hungry→饥饿的"),
("ill","生病的",A,1,"high",["sick","unwell","healthy","disease"],["ill","will"],"She is ill today.","ill→生病的"),
("important","重要的",A,1,"high",["significant","necessary","unimportant","key"],["import","interest"],"This is an important meeting.","important→重要的"),
("impossible","不可能的",A,1,"high",["possible","unlikely","can't","able"],["possible","impress"],"Nothing is impossible.","impossible→不可能的"),
("incredible","难以置信的",A,2,"medium",["amazing","unbelievable","wonderful"],["incredible","innocent"],"The view is incredible.","incredible→难以置信的"),
("independent","独立的",A,2,"medium",["dependent","free","alone","rely"],["depend","independence"],"She is very independent.","independent→独立的"),
("influence","影响",N,1,"high",["effect","impact","affect","power"],["influence","information"],"Music has a great influence on people.","influence→影响"),
("interesting","有趣的",A,1,"high",["boring","fascinating","dull","fun"],["interest","internet"],"This book is very interesting.","interesting→有趣的"),
("international","国际的",A,1,"medium",["global","national","foreign","world"],["internet","interview"],"It is an international company.","international→国际的"),
("kind","善良的；种类",A,1,"high",["nice","friendly","cruel","sort"],["kind","king"],"She is a kind person.","kind→善良的"),
("known","已知的；著名的",A,2,"medium",["famous","unknown","well-known"],["know","knowledge"],"He is a known writer.","known→已知的"),
("large","大的",A,1,"high",["big","huge","small","great"],["last","late"],"Shanghai is a large city.","large→大的"),
("last","最后的",A,1,"high",["first","final","next","past"],["lost","least"],"This is my last chance.","last→最后的"),
("late","迟的；晚的",A,1,"high",["early","late","behind","slow"],["last","later"],"Sorry, I am late.","late→迟的"),
("lazy","懒惰的",A,1,"high",["hard-working","idle","busy","active"],["lady","lazy"],"Don't be so lazy.","lazy→懒惰的"),
("legal","合法的",A,2,"medium",["illegal","law","right","official"],["legal","level"],"Is this legal?","legal→合法的"),
("level","水平；级别",N,1,"high",["standard","degree","grade","rank"],["legal","lesson"],"Her English level is high.","level→水平"),
("likely","可能的",A,2,"medium",["unlikely","probable","possible","maybe"],["like","alive"],"It is likely to rain tomorrow.","likely→可能的"),
("little","小的；少的",A,1,"high",["small","big","much","tiny"],["little","let"],"There is little water left.","little→小的"),
("lonely","孤独的",A,1,"high",["alone","sad","happy","solitary"],["alone","long"],"She feels lonely.","lonely→孤独的"),
("loud","大声的",A,1,"high",["quiet","noisy","soft","low"],["loud","love"],"Don't be so loud.","loud→大声的"),
("lovely","可爱的；美丽的",A,1,"high",["beautiful","pretty","cute","wonderful"],["love","lovely"],"What a lovely day!","lovely→可爱的"),
("low","低的",A,1,"high",["high","short","tall","deep"],["low","slow"],"The temperature is very low.","low→低的"),
("lucky","幸运的",A,1,"high",["unlucky","fortune","luck","chance"],["luck","lucky"],"You are so lucky!","lucky→幸运的"),
("main","主要的",A,1,"high",["major","important","chief","primary"],["main","many"],"What is the main idea?","main→主要的"),
("major","主要的；重大的",A,2,"medium",["main","important","minor","big"],["major","mayor"],"This is a major problem.","major→主要的"),
("medical","医学的",A,2,"medium",["health","doctor","hospital","medicine"],["medicine","medium"],"She needs medical help.","medical→医学的"),
("mental","精神的；心理的",A,2,"medium",["physical","mind","brain","body"],["mention","metal"],"Mental health is important.","mental→精神的"),
("modern","现代的",A,1,"high",["ancient","new","old","contemporary"],["model","modern"],"Beijing is a modern city.","modern→现代的"),
("natural","自然的；天然的",A,1,"high",["artificial","nature","normal","wild"],["nature","national"],"It is natural to feel nervous.","natural→自然的"),
("necessary","必要的",A,1,"high",["important","essential","unnecessary","need"],["necessary","next"],"Exercise is necessary for health.","necessary→必要的"),
("nervous","紧张的",A,1,"high",["calm","anxious","worried","relaxed"],["never","nice"],"She felt nervous before the exam.","nervous→紧张的"),
("new","新的",A,1,"high",["old","fresh","recent","modern"],["new","now"],"I bought a new bike.","new→新的"),
("nice","好的；令人愉快的",A,1,"high",["kind","good","pleasant","fine"],["nine","night"],"It is nice to meet you.","nice→好的"),
("normal","正常的",A,1,"high",["abnormal","usual","regular","unusual"],["north","notice"],"Everything is normal.","normal→正常的"),
("obvious","明显的",A,2,"medium",["clear","apparent","hidden","evident"],["obviously","observation"],"The answer is obvious.","obvious→明显的"),
("old","老的；旧的",A,1,"high",["new","young","aged","ancient"],["old","cold"],"My grandfather is old.","old→老的"),
("only","唯一的；只",A,1,"high",["single","alone","just"],["one","open"],"She is my only friend.","only→唯一的"),
("ordinary","普通的",A,1,"high",["common","normal","unusual","special"],["order","organize"],"He is an ordinary student.","ordinary→普通的"),
("other","其他的",A,1,"high",["another","different","else","same"],["others","otherwise"],"Do you have any other questions?","other→其他的"),
("own","自己的",A,1,"high",["personal","belong","possess"],["own","owe"],"I saw it with my own eyes.","own→自己的"),
("particular","特别的；特定的",A,2,"medium",["special","specific","general","usual"],["particular","partner"],"Is there any particular reason?","particular→特别的"),
("patient","耐心的；病人",A,1,"high",["impatient","wait","calm","tolerant"],["patience","pattern"],"Please be patient.","patient→耐心的"),
("perfect","完美的",A,1,"high",["flawless","ideal","imperfect","excellent"],["perform","perhaps"],"The weather is perfect today.","perfect→完美的"),
("perhaps","也许；可能",Adv,1,"medium",["maybe","possibly","probably","certainly"],["perfect","period"],"Perhaps she will come tomorrow.","perhaps→也许"),
("personal","个人的；私人的",A,2,"medium",["private","public","own","individual"],["person","perfect"],"This is my personal opinion.","personal→个人的"),
("physical","身体的；物理的",A,2,"medium",["mental","body","sport","exercise"],["physics","physical"],"Physical exercise is important.","physical→身体的"),
("pleasant","令人愉快的",A,2,"medium",["nice","pleased","unpleasant","enjoyable"],["please","pleasure"],"We had a pleasant trip.","pleasant→令人愉快的"),
("polite","有礼貌的",A,1,"high",["rude","impolite","kind","manner"],["polite","politics"],"He is a polite boy.","polite→有礼貌的"),
("poor","贫穷的；可怜的",A,1,"high",["rich","wealthy","bad","needy"],["pool","pour"],"The family is very poor.","poor→贫穷的"),
("popular","受欢迎的",A,1,"high",["famous","common","unpopular","like"],["population","popular"],"This song is very popular.","popular→受欢迎的"),
("possible","可能的",A,1,"high",["impossible","likely","can","able"],["impossible","perhaps"],"Is it possible to finish today?","possible→可能的"),
("powerful","强大的",A,2,"medium",["strong","weak","mighty","force"],["power","powerful"],"He gave a powerful speech.","powerful→强大的"),
("pretty","漂亮的；相当",A,1,"high",["beautiful","lovely","ugly","fair"],["pretty","print"],"The dress is pretty.","pretty→漂亮的"),
("private","私人的",A,2,"medium",["public","personal","secret","own"],["pride","print"],"This is a private matter.","private→私人的"),
("probable","很可能的",A,2,"medium",["likely","possible","unlikely","probable"],["probably","problem"],"Rain is probable tonight.","probable→很可能的"),
("probably","大概；或许",Adv,1,"high",["maybe","perhaps","possibly","certainly"],["probable","problem"],"It will probably rain.","probably→大概"),
("proper","合适的；恰当的",A,2,"medium",["appropriate","correct","wrong","suitable"],["property","protect"],"Use proper language.","proper→合适的"),
("proud","骄傲的；自豪的",A,1,"high",["pride","arrogant","modest","honor"],["pride","produce"],"I am proud of you.","proud→骄傲的"),
("public","公共的",A,1,"high",["private","open","people"],["publish","pull"],"This is a public park.","public→公共的"),
("pure","纯洁的；纯粹的",A,2,"medium",["clean","mixed","clear"],["pure","purpose"],"The water is pure.","pure→纯洁的"),
("quick","快的；迅速的",A,1,"high",["fast","rapid","slow","swift"],["quiet","quite"],"Be quick!","quick→快的"),
("quiet","安静的",A,1,"high",["loud","noisy","silent","still"],["quite","quiet"],"Please keep quiet.","quiet→安静的"),
("rapid","迅速的",A,2,"medium",["fast","quick","slow","swift"],["rapid","rain"],"There was rapid growth.","rapid→迅速的"),
("rare","稀有的",A,2,"medium",["common","unusual","scarce","uncommon"],["rare","raise"],"This is a rare bird.","rare→稀有的"),
("raw","生的；未加工的",A,3,"low",["cooked","uncooked","natural"],["raw","run"],"Don't eat raw meat.","raw→生的"),
("ready","准备好的",A,1,"high",["prepared","set","unready"],["read","really"],"Are you ready?","ready→准备好的"),
("real","真实的",A,1,"high",["true","false","fake","actual"],["really","reason"],"Is this real gold?","real→真实的"),
("regular","定期的；有规律的",A,2,"medium",["irregular","usual","normal","often"],["regular","relax"],"He takes regular exercise.","regular→定期的"),
("responsible","负责任的",A,1,"high",["duty","careless","reliable"],["response","respect"],"She is a responsible student.","responsible→负责任的"),
("rich","富有的；丰富的",A,1,"high",["poor","wealthy","money","abundant"],["reach","rice"],"He comes from a rich family.","rich→富有的"),
("right","正确的；右边的",A,1,"high",["wrong","correct","left","true"],["write","bright"],"You are right.","right→正确的"),
("rough","粗糙的",A,2,"medium",["smooth","tough","soft","hard"],["round","route"],"The surface is rough.","rough→粗糙的"),
("sad","伤心的",A,1,"high",["happy","unhappy","sorry","upset"],["safe","said"],"She looks sad.","sad→伤心的"),
("safe","安全的",A,1,"high",["dangerous","unsafe","protect","risk"],["safe","save"],"It is safe to cross here.","safe→安全的"),
("same","相同的",A,1,"high",["different","similar","alike"],["some","name"],"We are in the same class.","same→相同的"),
("scared","害怕的",A,1,"high",["afraid","fear","brave","terrified"],["scarce","scale"],"The child was scared of dogs.","scared→害怕的"),
("serious","严肃的；严重的",A,1,"high",["silly","important","joking","solemn"],["serious","series"],"This is a serious problem.","serious→严肃的"),
("several","几个的",A,1,"high",["some","many","few","various"],["several","separate"],"I have read several books.","several→几个的"),
("shy","害羞的",A,1,"high",["timid","bold","quiet","nervous"],["shy","she"],"She is too shy to speak.","shy→害羞的"),
("sick","生病的",A,1,"high",["ill","unwell","healthy","disease"],["sick","side"],"She is sick today.","sick→生病的"),
("similar","相似的",A,1,"high",["same","different","like","alike"],["simple","single"],"Our ideas are similar.","similar→相似的"),
("simple","简单的",A,1,"high",["easy","difficult","complicated","plain"],["simple","since"],"The question is simple.","simple→简单的"),
("single","单一的；单身的",A,1,"high",["double","alone","married","one"],["simple","since"],"He is single.","single→单一的"),
("skill","技能；技巧",N,1,"high",["ability","talent","practice","train"],["skill","still"],"She has good writing skills.","skill→技能"),
("slim","苗条的",A,2,"medium",["thin","fat","slender"],["slim","slip"],"She has a slim figure.","slim→苗条的"),
("slow","慢的",A,1,"high",["fast","quick","rapid","speed"],["slow","snow"],"He walks very slowly.","slow→慢的"),
("small","小的",A,1,"high",["big","large","tiny","little"],["smell","smile"],"The room is small.","small→小的"),
("smart","聪明的",A,1,"high",["clever","bright","stupid","intelligent"],["smart","start"],"She is a smart student.","smart→聪明的"),
("smooth","光滑的；顺利的",A,2,"medium",["rough","flat","even","soft"],["smooth","smile"],"The road is smooth.","smooth→光滑的"),
("social","社会的",A,2,"medium",["society","public","community"],["social","special"],"Social media is popular.","social→社会的"),
("soft","柔软的",A,1,"high",["hard","tough","gentle","smooth"],["soft","sold"],"The pillow is soft.","soft→柔软的"),
("sorry","对不起",A,1,"high",["apologize","regret","sad"],["sort","soul"],"I am sorry for being late.","sorry→对不起"),
("special","特别的；特殊的",A,1,"high",["ordinary","particular","usual","normal"],["specific","especial"],"Today is a special day.","special→特别的"),
("standard","标准的",A,2,"medium",["normal","level","quality","criterion"],["stand","start"],"This is the standard size.","standard→标准的"),
("strange","奇怪的；陌生的",A,1,"high",["odd","unusual","familiar","normal"],["strong","straight"],"I heard a strange noise.","strange→奇怪的"),
("strict","严格的",A,1,"high",["tough","severe","easy","loose"],["strike","string"],"My father is very strict.","strict→严格的"),
("strong","强壮的；坚强的",A,1,"high",["weak","powerful","tough","fit"],["strong","straight"],"He has strong arms.","strong→强壮的"),
("stupid","愚蠢的",A,2,"medium",["smart","clever","wise","foolish"],["study","student"],"Don't be stupid.","stupid→愚蠢的"),
("suitable","合适的",A,2,"medium",["fit","proper","appropriate","right"],["suit","suggest"],"This dress is not suitable.","suitable→合适的"),
("sure","确定的；当然",A,1,"high",["certain","certainly","doubt","unsure"],["sure","survive"],"I am sure she will come.","sure→确定的"),
("surprised","吃惊的",A,1,"high",["amazed","shocked","surprising"],["surprise","supply"],"I was surprised by the news.","surprised→吃惊的"),
("sweet","甜的",A,1,"high",["sour","bitter","sugar","candy"],["sweet","swim"],"The cake is sweet.","sweet→甜的"),
("tall","高的",A,1,"high",["short","high","long"],["talk","tall"],"He is very tall.","tall→高的"),
("terrible","可怕的；糟糕的",A,1,"high",["awful","horrible","wonderful","bad"],["terrible","test"],"The weather was terrible.","terrible→糟糕的"),
("thick","厚的；浓的",A,1,"high",["thin","fat","wide"],["think","thing"],"This book is very thick.","thick→厚的"),
("thin","薄的；瘦的",A,1,"high",["thick","fat","slim","skinny"],["thing","think"],"The ice is too thin.","thin→薄的"),
("tidy","整洁的",A,2,"medium",["neat","clean","messy"],["tidy","tiny"],"Her room is always tidy.","tidy→整洁的"),
("tiny","极小的",A,2,"medium",["small","little","huge","big"],["tiny","tired"],"The baby is tiny.","tiny→极小的"),
("tired","疲倦的",A,1,"high",["exhausted","energetic","sleep","rest"],["tired","tired"],"I am so tired today.","tired→疲倦的"),
("traditional","传统的",A,2,"medium",["modern","custom","culture"],["tradition","traditional"],"It is a traditional festival.","traditional→传统的"),
("true","真的；真实的",A,1,"high",["false","real","correct","wrong"],["tree","try"],"Is this story true?","true→真的"),
("typical","典型的",A,2,"medium",["normal","usual","special","common"],["type","typically"],"This is a typical example.","typical→典型的"),
("ugly","丑陋的",A,2,"medium",["beautiful","pretty","handsome","bad"],["ugly","uncle"],"Don't say that, it's ugly.","ugly→丑陋的"),
("unable","不能的",A,2,"medium",["able","can't","capable","possible"],["unable","unfair"],"She was unable to come.","unable→不能的"),
("unfair","不公平的",A,2,"medium",["fair","just","equal","reasonable"],["unable","unhappy"],"The rule is unfair.","unfair→不公平的"),
("unhappy","不快乐的",A,1,"high",["happy","sad","unpleasant","upset"],["unhappy","uniform"],"She looked unhappy.","unhappy→不快乐的"),
("universal","普遍的；全球的",A,3,"low",["global","common","worldwide","general"],["universe","university"],"Music is a universal language.","universal→普遍的"),
("unusual","不寻常的",A,2,"medium",["usual","common","normal","strange"],["usually","unusual"],"This is an unusual situation.","unusual→不寻常的"),
("upset","难过的；心烦的",A,1,"high",["sad","angry","worried","calm"],["upset","use"],"She was upset about the news.","upset→难过的"),
("useful","有用的",A,1,"high",["helpful","useless","practical"],["use","usual"],"This is a useful tool.","useful→有用的"),
("useless","无用的",A,2,"medium",["useful","helpful","worthless"],["useless","usual"],"This old phone is useless.","useless→无用的"),
("usual","通常的",A,1,"high",["unusual","normal","regular","common"],["usually","use"],"She arrived at the usual time.","usual→通常的"),
("valuable","有价值的；贵重的",A,2,"medium",["precious","worthless","valuable","important"],["value","various"],"Time is valuable.","valuable→有价值的"),
("various","各种各样的",A,2,"medium",["different","many","several","kind"],["value","various"],"There are various kinds of flowers.","various→各种各样的"),
("warm","温暖的；热情的",A,1,"high",["cold","cool","hot","kind"],["warm","warn"],"The weather is warm today.","warm→温暖的"),
("weak","弱的",A,1,"high",["strong","powerful","frail","feeble"],["weak","week"],"She felt weak after illness.","weak→弱的"),
("wealthy","富有的",A,2,"medium",["rich","poor","money","wealth"],["health","weather"],"He grew up in a wealthy family.","wealthy→富有的"),
("wet","湿的",A,1,"high",["dry","water","moisture"],["wet","wait"],"My clothes got wet.","wet→湿的"),
("whole","整个的",A,1,"high",["part","all","complete","entire"],["who","while"],"The whole class was there.","whole→整个的"),
("wide","宽的；广泛的",A,1,"high",["narrow","broad","wide"],["wife","will"],"The road is very wide.","wide→宽的"),
("wild","野生的",A,1,"high",["tame","crazy","domestic","natural"],["will","win"],"There are wild animals in the forest.","wild→野生的"),
("wise","明智的；聪明的",A,1,"high",["clever","smart","foolish","stupid"],["wish","with"],"That was a wise decision.","wise→明智的"),
("wonderful","极好的；精彩的",A,1,"high",["great","fantastic","terrible","excellent"],["wonder","worry"],"We had a wonderful time.","wonderful→极好的"),
("worried","担心的",A,1,"high",["anxious","nervous","calm","worry"],["worry","worse"],"She is worried about her son.","worried→担心的"),
("worth","值得的",A,2,"medium",["valuable","worthy","worthless"],["worth","would"],"The book is worth reading.","worth→值得的"),
("wrong","错误的",A,1,"high",["right","correct","mistake"],["write","long"],"You are wrong.","wrong→错误的"),
("young","年轻的",A,1,"high",["old","youth","aged","new"],["your","young"],"She is very young.","young→年轻的"),
]

for e in entries:
    add(*e)

outpath = '/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/_part2_cache.json'
with open(outpath, 'w', encoding='utf-8') as f:
    json.dump(words, f, ensure_ascii=False, indent=2)

print(f'Part 2 done: {len(words)} words total')
