#!/usr/bin/env python3
"""生成初中语文7-9年级听写词库并追加到dictation_cn_words.json"""
import json
from collections import Counter

INPUT = 'src/data/dictation_cn_words.json'
OUTPUT = 'src/data/dictation_cn_words.json'

# ═══ 七年级上册 (50条) ═══
G7S1 = [
    {"id":"cn_g7_001","word":"朗润","pinyin":"lǎng rùn","grade":7,"semester":"上册","example":"山朗润起来了，水涨起来了，太阳的脸红起来了。"},
    {"id":"cn_g7_002","word":"酝酿","pinyin":"yùn niàng","grade":7,"semester":"上册","example":"风里带来些新翻的泥土的气息，都在微微湿润的空气里酝酿。"},
    {"id":"cn_g7_003","word":"嘹亮","pinyin":"liáo liàng","grade":7,"semester":"上册","example":"鸟儿高兴起来了，唱出嘹亮的曲子。"},
    {"id":"cn_g7_004","word":"烘托","pinyin":"hōng tuō","grade":7,"semester":"上册","example":"傍晚时一点点黄晕的光，烘托出一片安静而和平的夜。"},
    {"id":"cn_g7_005","word":"静谧","pinyin":"jìng mì","grade":7,"semester":"上册","example":"秋天的夜晚是那么静谧美好。"},
    {"id":"cn_g7_006","word":"高邈","pinyin":"gāo miǎo","grade":7,"semester":"上册","example":"雨的神情是高邈而深邃的。"},
    {"id":"cn_g7_007","word":"莅临","pinyin":"lì lín","grade":7,"semester":"上册","example":"冬天来临的时候，雨便化了妆，飘然莅临人间。"},
    {"id":"cn_g7_008","word":"吝啬","pinyin":"lìn sè","grade":7,"semester":"上册","example":"冬天的雨水显得格外吝啬。"},
    {"id":"cn_g7_009","word":"淅沥","pinyin":"xī lì","grade":7,"semester":"上册","example":"窗外淅沥沥地下着小雨。"},
    {"id":"cn_g7_010","word":"咄咄逼人","pinyin":"duō duō bī rén","grade":7,"semester":"上册","example":"他的目光咄咄逼人，让人不敢直视。"},
    {"id":"cn_g7_011","word":"慈善","pinyin":"cí shàn","grade":7,"semester":"上册","example":"这位老人一生都在做慈善事业，帮助了许多人。"},
    {"id":"cn_g7_012","word":"宽敞","pinyin":"kuān chǎng","grade":7,"semester":"上册","example":"我们的教室非常宽敞明亮，可以容纳五十个学生。"},
    {"id":"cn_g7_013","word":"贮蓄","pinyin":"zhù xù","grade":7,"semester":"上册","example":"济南的水在冬天也不结冰，反倒在绿萍上贮蓄着绿意。"},
    {"id":"cn_g7_014"," word":"澄清","pinyin":"chéng qīng","grade":7,"semester":"上册","example":"那水澄清见底，连水底的沙石都看得清清楚楚。"},
    {"id":"cn_g7_015","word":"地毯","pinyin":"dì tǎn","grade":7,"semester":"上册","example":"地上铺着一块红色的地毯，看起来非常温馨。"},
    {"id":"cn_g7_016","word":"湿润","pinyin":"shī rùn","grade":7,"semester":"上册","example":"雨后的空气十分湿润清新，深呼吸一口感觉真好。"},
    {"id":"cn_g7_017","word":"萧瑟","pinyin":"xiāo sè","grade":7,"semester":"上册","example":"秋风萧瑟，树叶纷纷落下，满地金黄。"},
    {"id":"cn_g7_018","word":"干涩","pinyin":"gān sè","grade":7,"semester":"上册","example":"他说话的声音听起来有些干涩沙哑。"},
    {"id":"cn_g7_019","word":"窒息","pinyin":"zhì xī","grade":7,"semester":"上册","example":"浓烟弥漫在整个房间里，让人几乎窒息。"},
    {"id":"cn_g7_020","word":"凄冷","pinyin":"qī lěng","grade":7,"semester":"上册","example":"深秋的夜晚显得格外凄冷，风呼呼地吹着。"},
    {"id":"cn_g7_021","word":"娇媚","pinyin":"jiāo mèi","grade":7,"semester":"上册","example":"春姑娘带着她那娇媚的面容来到了人间。"},
    {"id":"cn_g7_022","word":"粗犷","pinyin":"cū guǎng","grade":7,"semester":"上册","example":"北方的秋天有一种粗犷而豪放的美。"},
    {"id":"cn_g7_023","word":"端庄","pinyin":"duān zhuāng","grade":7,"semester":"上册","example":"她的举止端庄优雅，给人留下很好的印象。"},
    {"id":"cn_g7_024","word":"棱镜","pinyin":"léng jìng","grade":7,"semester":"上册","example":"阳光透过棱镜折射出了七彩的光芒。"},
    {"id":"cn_g7_025","word":"铃铛","pinyin":"líng dang","grade":7,"semester":"上册","example":"小猫脖子上挂着一个金色的铃铛，走起路来叮当响。"},
    {"id":"cn_g7_026","word":"睫毛","pinyin":"jié máo","grade":7,"semester":"上册","example":"小女孩长长的睫毛像两把小扇子一样好看。"},
    {"id":"cn_g7_027","word":"花蕾","pinyin":"huā lěi","grade":7,"semester":"上册","example":"春天来了，树枝上冒出了一个个小小的花蕾。"},
    {"id":"cn_g7_028","word":"衣裳","pinyin":"yī shang","grade":7,"semester":"上册","example":"她穿了一件漂亮的衣裳去参加聚会。"},
    {"id":"cn_g7_029","word":"淅淅沥沥","pinyin":"xī xī lì lì","grade":7,"semester":"上册","example":"窗外淅淅沥沥下了一整夜的雨，清晨才停下来。"},
    {"id":"cn_g7_030","word":"争先恐后","pinyin":"zhēng xiān kǒng hòu","grade":7,"semester":"上册","example":"同学们争先恐后地举手回答老师的问题。"},
    {"id":"cn_g7_031","word":"花枝招展","pinyin":"huā zhī zhāo zhǎn","grade":7,"semester":"上册","example":"春天的公园里花儿们花枝招展，争奇斗艳。"},
    {"id":"cn_g7_032","word":"混为一谈","pinyin":"hún wéi yī tán","grade":7,"semester":"上册","example":"这两件事性质不同，不能混为一谈。"},
    {"id":"cn_g7_033","word":"恍然大悟","pinyin":"huǎng rán dà wù","grade":7,"semester":"上册","example":"听了老师的解释，他才恍然大悟，明白了自己的错误。"},
    {"id":"cn_g7_034","word":"油然而生","pinyin":"yóu rán ér shēng","grade":7,"semester":"上册","example":"看到祖国的大好河山，一种自豪感油然而生。"},
    {"id":"cn_g7_035","word":"各得其所","pinyin":"gè dé qí suǒ","grade":7,"semester":"上册","example":"经过合理分工，大家各得其所，工作效率大大提高。"},
    {"id":"cn_g7_036","word":"不期而至","pinyin":"bù qī ér zhì","grade":7,"semester":"上册","example":"一场大雨不期而至，淋了大家一身。"},
    {"id":"cn_g7_037","word":"人迹罕至","pinyin":"rén jì hǎn zhì","grade":7,"semester":"上册","example":"这片原始森林人迹罕至，保存着最原始的生态环境。"},
    {"id":"cn_g7_038","word":"人声鼎沸","pinyin":"rén shēng dǐng fèi","grade":7,"semester":"上册","example":"集市上人来人往，人声鼎沸，热闹非凡。"},
    {"id":"cn_g7_039","word":"疲倦","pinyin":"pí juàn","grade":7,"semester":"上册","example":"工作了一天之后，他感到十分疲倦，只想好好休息。"},
    {"id":"cn_g7_040","word":"附和","pinyin":"fù hè","grade":7,"semester":"上册","example":"他没有自己的主见，总是随波逐流地附和别人。"},
    {"id":"cn_g7_041","word":"博学","pinyin":"bó xué","grade":7,"semester":"上册","example":"这位教授学识渊博，是一位博学的学者。"},
    {"id":"cn_g7_042","word":"探险","pinyin":"tàn xiǎn","grade":7,"semester":"上册","example":"他们组织了一次野外探险活动去寻找传说中的洞穴。"},
    {"id":"cn_g7_043","word":"感慨","pinyin":"gǎn kǎi","grade":7,"semester":"上册","example":"看到家乡的变化，老人感慨万千，热泪盈眶。"},
    {"id":"cn_g7_044","word":"确凿","pinyin":"què záo","grade":7,"semester":"上册","example":"警方已经掌握了确凿的证据，足以定罪。"},
    {"id":"cn_g7_045","word":"质朴","pinyin":"zhì pǔ","grade":7,"semester":"上册","example":"这个孩子性格质朴淳厚，深受大家的喜欢。"},
    {"id":"cn_g7_046","word":"绅士","pinyin":"shēn shì","grade":7,"semester":"上册","example":"他举止优雅，像一位真正的绅士一样有礼貌。"},
    {"id":"cn_g7_047","word":"恭敬","pinyin":"gōng jìng","grade":7,"semester":"上册","example":"学生对老师要始终保持恭敬的态度和礼貌。"},
    {"id":"cn_g7_048","word":"鉴赏","pinyin":"jiàn shǎng","grade":7,"semester":"上册","example":"这幅画的构图和色彩都值得细细鉴赏品味。"},
    {"id":"cn_g7_049","word":"慷慨","pinyin":"kāng kǎi","grade":7,"semester":"上册","example":"他对朋友向来慷慨大方，从不计较个人得失。"},
    {"id":"cn_g7_050"," word":"炫耀","pinyin":"xuàn yào","grade":7,"semester":"上册","example":"他总是在别人面前炫耀自己新买的手机。"},
]

# ═══ 七年级下册 (50条) ═══
G7S2 = [
    {"id":"cn_g7_051","word":"元勋","pinyin":"yuán xūn","grade":7,"semester":"下册","example":"邓稼先被誉为两弹元勋，为国家的国防事业做出了巨大贡献。"},
    {"id":"cn_g7_052","word":"奠基","pinyin":"diàn jī","grade":7,"semester":"下册","example":"他为中国的核物理研究事业奠定了坚实的基础。"},
    {"id":"cn_g7_053","word":"可歌可泣","pinyin":"kě gē kě qì","grade":7,"semester":"下册","example":"革命先烈们可歌可泣的英雄事迹永远激励着我们前进。"},
    {"id":"cn_g7_054","word":"鲜为人知","pinyin":"xiǎn wéi rén zhī","grade":7,"semester":"下册","example":"这位科学家的事迹鲜为人知，但他的贡献却不可磨灭。"},
    {"id":"cn_g7_055","word":"至死不懈","pinyin":"zhì sǐ bù xiè","grade":7,"semester":"下册","example":"他对科学研究的执着追求至死不懈，令人敬佩。"},
    {"id":"cn_g7_056","word":"鞠躬尽瘁","pinyin":"jū gōng jìn cuì","grade":7,"semester":"下册","example":"周总理为人民鞠躬尽瘁、死而后已的精神永垂不朽。"},
    {"id":"cn_g7_057","word":"当之无愧","pinyin":"dāng zhī wú kuì","grade":7,"semester":"下册","example":"他是当之无愧的冠军，实至名归，无人质疑。"},
    {"id":"cn_g7_058","word":"家喻户晓","pinyin":"jiā yù hù xiǎo","grade":7,"semester":"下册","example":"《西游记》中的孙悟空是一个家喻户晓的人物形象。"},
    {"id":"cn_g7_059","word":"截然不同","pinyin":"jié rán bù tóng","grade":7,"semester":"下册","example":"这对双胞胎兄弟的性格截然不同，一个内向一个外向。"},
    {"id":"cn_g7_060","word":"锋芒毕露","pinyin":"fēng máng bì lù","grade":7,"semester":"下册","example":"年轻人做事不要锋芒毕露，要学会低调谦虚做人。"},
    {"id":"cn_g7_061","word":"知人之明","pinyin":"zhī rén zhī míng","grade":7,"semester":"下册","example":"领导要有知人之明，善于发现和使用各类人才。"},
    {"id":"cn_g7_062","word":"波澜壮阔","pinyin":"bō lán zhuàng kuò","grade":7,"semester":"下册","example":"黄河入海口处江水奔涌而出，形成波澜壮阔的景象。"},
    {"id":"cn_g7_063","word":"仰慕","pinyin":"yǎng mù","grade":7,"semester":"下册","example":"我一直仰慕这位作家的才华和人品，视他为榜样。"},
    {"id":"cn_g7_064","word":"锲而不舍","pinyin":"qiè ér bù shě","grade":7,"semester":"下册","example":"学习需要锲而不舍的精神，不能半途而废。"},
    {"id":"cn_g7_065","word":"兀兀穷年","pinyin":"wù wù qióng nián","grade":7,"semester":"下册","example":"这位老学者兀兀穷年，致力于古籍整理工作数十年如一日。"},
    {"id":"cn_g7_066","word":"沥尽心血","pinyin":"lì jìn xīn xuè","grade":7,"semester":"下册","example":"为了完成这部著作，他沥尽心血耗尽了全部精力。"},
    {"id":"cn_g7_067","word":"潜心贯注","pinyin":"qián xīn guàn zhù","grade":7,"semester":"下册","example":"他潜心贯注于科学研究，几乎忘记了时间的流逝。"},
    {"id":"cn_g7_068","word":"心会神凝","pinyin":"xīn huì shén níng","grade":7,"semester":"下册","example":"读书时要心会神凝才能真正理解书中的深刻内涵。"},
    {"id":"cn_g7_069","word":"迥乎不同","pinyin":"jiǒng hū bù tóng","grade":7,"semester":"下册","example":"这两种方案的思路迥乎不同各有优劣需要仔细权衡。"},
    {"id":"cn_g7_070","word":"一反既往","pinyin":"yī fǎn jì wǎng","grade":7,"semester":"下册","example":"这次考试他一反既往的懒散态度，取得了优异成绩。"},
    {"id":"cn_g7_071","word":"慷慨淋漓","pinyin":"kāng kǎi lín lí","grade":7,"semester":"下册","example":"他在演讲台上慷慨淋漓地表达了自己对正义的追求。"},
    {"id":"cn_g7_072","word":"气冲斗牛","pinyin":"qì chōu dǒu niú","grade":7,"semester":"下册","example":"英雄烈士们气冲斗牛的壮志豪情感动了在场的每一个人。"},
    {"id":"cn_g7_073","word":"深邃","pinyin":"shēn suì","grade":7,"semester":"下册","example":"这篇文章的思想内涵十分深邃值得反复阅读思考。"},
    {"id":"cn_g7_074","word":"狂澜","pinyin":"kuáng lán","grade":7,"semester":"下册","example":"无数革命志士力挽狂澜挽救了国家危亡于水火之中。"},
    {"id":"cn_g7_075","word":"浊流","pinyin":"zhuó liú","grade":7,"semester":"下册","example":"我们要擦亮眼睛不被社会的浊流所裹挟而迷失方向。"},
    {"id":"cn_g7_076","word":"屏障","pinyin":"píng zhàng","grade":7,"semester":"下册","example":"茂密的森林是大天然的屏障，保护着水土不被流失。"},
    {"id":"cn_g7_077","word":"哺育","pinyin":"bǔ yù","grade":7,"semester":"下册","example":"黄河哺育了中华文明被称为中华民族的母亲河。"},
    {"id":"cn_g7_078","word":"浩浩荡荡","pinyin":"hào hào dàng dàng","grade":7,"semester":"下册","example":"游行队伍浩浩荡荡地走过大街场面非常壮观。"},
    {"id":"cn_g7_079","word":"坚忍","pinyin":"jiān rěn","grade":7,"semester":"下册","example":"面对困难他表现出惊人的坚忍意志从不轻言放弃。"},
    {"id":"cn_g7_080","word":"崇高","pinyin":"chóng gāo","grade":7,"semester":"下册","example":"消防员们崇高的精神值得我们每个人学习和敬仰。"},
    {"id":"cn_g7_081","word":"悲愤","pinyin":"bēi fèn","grade":7,"semester":"下册","example":"听到这个噩耗他感到无比悲愤和痛苦。"},
    {"id":"cn_g7_082","word":"烦琐","pinyin":"fán suǒ","grade":7,"semester":"下册","example":"这些烦琐的手续让每个人都感到头疼不已。"},
    {"id":"cn_g7_083","word":"疏懒","pinyin":"shū lǎn","grade":7,"semester":"下册","example":"他最近变得很疏懒工作和学习都不认真了。"},
    {"id":"cn_g7_084","word":"典范","pinyin":"diǎn fàn","grade":7,"semester":"下册","example":"这篇文章是说明文的典范之作值得我们认真学习。"},
    {"id":"cn_g7_085","word":"圣哲","pinyin":"shèng zhé","grade":7,"semester":"下册","example":"孔子是中国古代著名的圣哲之一其思想影响深远。"},
    {"id":"cn_g7_086","word":"谦逊","pinyin":"qiān xùn","grade":7,"semester":"下册","example":"他虽然成绩优秀但待人始终谦逊有礼从不骄傲自满。"},
    {"id":"cn_g7_087","word":"修润","pinyin":"xiū rùn","grade":7,"semester":"下册","example":"这篇文章经过老师的修润后变得更加通顺优美了。"},
    {"id":"cn_g7_088","word":"生疏","pinyin":"shēng shū","grade":7,"semester":"下册","example":"由于长时间没有练习我对钢琴已经感到有些生疏了。"},
    {"id":"cn_g7_089","word":"恳切","pinyin":"kěn qiè","grade":7,"semester":"下册","example":"他用恳切的语气请求老师再给他一次机会。"},
    {"id":"cn_g7_090","word":"朦胧","pinyin":"méng lóng","grade":7,"semester":"下册","example":"清晨的雾气中远处的山峰若隐若现显得十分朦胧。"},
    {"id":"cn_g7_091","word":"累赘","pinyin":"lèi zhui","grade":7,"semester":"下册","example":"这段文字太累赘了应该删减一些不必要的修饰语。"},
    {"id":"cn_g7_092","word":"别扭","pinyin":"biè niu","grade":7,"semester":"下册","example":"这句话读起来有点别扭语法上好像不太对劲。"},
    {"id":"cn_g7_093","word":"拖沓","pinyin":"tuō tà","grade":7,"semester":"下册","example":"他做事总是拖拖拉拉的一点也不干脆利落让人着急。"},
    {"id":"cn_g7_094","word":"妥帖","pinyin":"tuǒ tiē","grade":7,"semester":"下册","example":"这番话说得非常妥帖让大家都感到满意和舒服。"},
    {"id":"cn_g7_095","word":"诲人不倦","pinyin":"huì rén bù juàn","grade":7,"semester":"下册","example":"王老师诲人不倦的教学态度深受学生们的爱戴。"},
    {"id":"cn_g7_096","word":"不耻下问","pinyin":"bù chǐ xià wèn","grade":7,"semester":"下册","example":"学习中要不耻下问虚心向比自己差的人请教。"},
    {"id":"cn_g7_097","word":"颠沛流离","pinyin":"diān pèi liú lí","grade":7,"semester":"下册","example":"战争期间许多人被迫颠沛流离背井离乡四处逃难。"},
    {"id":"cn_g7_098","word":"以身作则","pinyin":"yǐ shēn zuò zé","grade":7,"semester":"下册","example":"作为班长他事事以身作则为大家树立了好榜样。"},
    {"id":"cn_g7_099","word":"深恶痛绝","pinyin":"shēn wù tòng jué","grade":7,"semester":"下册","example":"对于这种欺诈行为大家深恶痛绝一致要求严惩。"},
    {"id":"cn_g7_100","word":"不屈不挠","pinyin":"bù qū bù náo","grade":7,"semester":"下册","example":"他在逆境中不屈不挠最终实现了自己的梦想。"},
]

# ═══ 八年级上册 (50条) ═══
G8S1 = [
    {"id":"cn_g8_001","word":"溃退","pinyin":"kuì tuì","grade":8,"semester":"上册","example":"敌军在我军的猛烈攻势下开始溃退四散奔逃。"},
    {"id":"cn_g8_002","word":"泄气","pinyin":"xiè qì","grade":8,"semester":"上册","example":"遇到困难不要泄气要坚持到底才能成功。"},
    {"id":"cn_g8_003","word":"督战","pinyin":"dū zhàn","grade":8,"semester":"上册","example":"将军亲自到前线督战鼓舞士气指挥作战。"},
    {"id":"cn_g8_004","word":"摧枯拉朽","pinyin":"cuī kū lā xiǔ","grade":8,"semester":"上册","example":"我军势如破竹以摧枯拉朽之势击败了敌人。"},
    {"id":"cn_g8_005","word":"锐不可当","pinyin":"ruì bù kě dāng","grade":8,"semester":"上册","example":"这支球队的进攻锐不可当对手毫无还手之力。"},
    {"id":"cn_g8_006"," word":"业已","pinyin":"yè yǐ","grade":8,"semester":"上册","example":"大桥业已建成通车方便了两岸居民的出行。"},
    {"id":"cn_g8_007","word":"颁发","pinyin":"bān fā","grade":8,"semester":"上册","example":"学校举行了隆重的颁奖典礼给获奖学生颁发证书和奖品。"},
    {"id":"cn_g8_008","word":"遗嘱","pinyin":"yí zhǔ","grade":8,"semester":"上册","example":"按照父亲的遗嘱这笔钱将捐献给慈善机构。"},
    {"id":"cn_g8_009","word":"建树","pinyin":"jiàn shù","grade":8,"semester":"上册","example":"他在科学研究方面有很大建树发表了很多重要论文。"},
    {"id":"cn_g8_010","word":"仲裁","pinyin":"zhòng cái","grade":8,"semester":"上册","example":"双方发生争议后提交国际仲裁机构进行仲裁。"},
    {"id":"cn_g8_011","word":"巨大","pinyin":"jù dà","grade":8,"semester":"上册","example":"这场灾难造成了巨大的财产损失和人员伤亡。"},
    {"id":"cn_g8_012","word":"渗透","pinyin":"shèn tòu","grade":8,"semester":"上册","example":"雨水慢慢渗透进泥土中滋润着植物的生长。"},
    {"id":"cn_g8_013","word":"洋溢","pinyin":"yáng yì","grade":8,"semester":"上册","example":"节日的街头洋溢着欢乐喜庆的气氛到处张灯结彩。"},
    {"id":"cn_g8_014","word":"轻盈","pinyin":"qīng yíng","grade":8,"semester":"上册","example":"舞者在舞台上轻盈地旋转跳跃动作优美流畅。"},
    {"id":"cn_g8_015","word":"悄然","pinyin":"qiǎo rán","grade":8,"semester":"上册","example":"夜幕悄然降临城市渐渐安静下来进入梦乡。"},
    {"id":"cn_g8_016","word":"潇洒","pinyin":"xiāo sǎ","grade":8,"semester":"上册","example":"他写字的姿态非常潇洒有力让人赏心悦目。"},
    {"id":"cn_g8_017","word":"由衷","pinyin":"yóu zhōng","grade":8,"semester":"上册","example":"我对你的帮助表示由衷的感谢真心实意地感激你。"},
    {"id":"cn_g8_018","word":"一丝不苟","pinyin":"yī sī bù gǒu","grade":8,"semester":"上册","example":"王老师批改作业时总是一丝不苟连标点符号也不放过。"},
    {"id":"cn_g8_019","word":"白手起家","pinyin":"bái shǒu qǐ jiā","grade":8,"semester":"上册","example":"这位企业家白手起家经过多年努力终于成就了一番大事业。"},
    {"id":"cn_g8_020","word":"殚精竭虑","pinyin":"dān jīng jié lǜ","grade":8,"semester":"上册","example":"为了设计出最好的方案工程师们殚精竭虑废寝忘食。"},
    {"id":"cn_g8_021","word":"匿名","pinyin":"nì míng","grade":8,"semester":"上册","example":"这封信是匿名的不知道是谁寄来的内容很神秘。"},
    {"id":"cn_g8_022","word":"凌空","pinyin":"líng kōng","grade":8,"semester":"上册","example":"雄鹰凌空翱翔俯瞰大地展现出王者的风范。"},
    {"id":"cn_g8_023","word":"翘首","pinyin":"qiáo shǒu","grade":8,"semester":"上册","example":"人们翘首以盼等待着好消息的到来内心充满期待。"},
    {"id":"cn_g8_024","word":"酷似","pinyin":"kù sì","grade":8,"semester":"上册","example":"他和他的父亲长得酷似简直是一个模子里刻出来的。"},
    {"id":"cn_g8_025","word":"从容","pinyin":"cóng róng","grade":8,"semester":"上册","example":"面对突发情况他表现得镇定从容毫不慌乱。"},
    {"id":"cn_g8_026","word":"咆哮","pinyin":"páo xiào","grade":8,"semester":"上册","example":"大海在暴风雨中怒吼咆哮卷起千层巨浪惊天动地。"},
    {"id":"cn_g8_027","word":"紧绷","pinyin":"jǐn bēng","grade":8,"semester":"上册","example":"比赛前每个队员的神经都紧紧绷着不敢有一丝松懈。"},
    {"id":"cn_g8_028","word":"镌刻","pinyin":"juān kè","grade":8,"semester":"上册","example":"英雄的名字被镌刻在纪念碑上永垂不朽世代流传。"},
    {"id":"cn_g8_029","word":"凛冽","pinyin":"lǐn liè","grade":8,"semester":"上册","example":"寒冬腊月北风凛冽滴水成冰冷得让人发抖。"},
    {"id":"cn_g8_030","word":"一瞬间","pinyin":"yī shùn jiān","grade":8,"semester":"上册","example":"烟花绽放的一瞬间整个夜空都被照亮了美丽无比。"},
    {"id":"cn_g8_031","word":"屏息敛声","pinyin":"bǐng xī liǎn shēng","grade":8,"semester":"上册","example":"全场观众屏息敛声注视着运动员的每一个动作。"},
    {"id":"cn_g8_032","word":"眼花缭乱","pinyin":"yǎn huā liáo luàn","grade":8,"semester":"上册","example":"货架上琳琅满目的商品让人看得眼花缭乱目不暇接。"},
    {"id":"cn_g8_033","word":"如梦初醒","pinyin":"rú mèng chū xǐng","grade":8,"semester":"上册","example":"听到真相的那一刻他才如梦初醒意识到自己被骗了。"},
    {"id":"cn_g8_034","word":"震耳欲聋","pinyin":"zhèn ěr yù lóng","grade":8,"semester":"上册","example":"雷声震耳欲聋吓得孩子们赶紧捂住了耳朵。"},
    {"id":"cn_g8_035","word":"引人注目","pinyin":"yǐn rén zhù mù","grade":8,"semester":"上册","example":"橱窗里的这件衣服款式新颖特别引人注目。"},
    {"id":"cn_g8_036","word":"惨淡经营","pinyin":"cǎn dàn jīng yíng","grade":8,"semester":"上册","example":"鲁迅先生在极其困难的环境中惨淡经营着他的文学创作。"},
    {"id":"cn_g8_037","word":"抑扬顿挫","pinyin":"yì yáng dùn cuò","grade":8,"semester":"上册","example":"老教授朗读诗歌时声音抑扬顿挫极富感染力。"},
    {"id":"cn_g8_038","word":"深恶痛疾","pinyin":"shēn wù tòng jí","grade":8,"semester":"上册","example":"对于社会上的不良风气我们应当深恶痛疾坚决抵制。"},
    {"id":"cn_g8_039"," word":"油光可鉴","pinyin":"yóu guāng kě jiàn","grade":8,"semester":"上册","example":"他的头发梳得油光可鉴看起来十分精神帅气。"},
    {"id":"cn_g8_040","word":"杳无消息","pinyin":"yǎo wú xiāo xī","grade":8,"semester":"上册","example":"他离开后杳无消息家里人非常担心不知道他过得怎么样。"},
    {"id":"cn_g8_041","word":"正人君子","pinyin":"zhèng rén jūn zǐ","grade":8,"semester":"上册","example":"他表面上道貌岸然自称正人君子实际上内心阴暗虚伪。"},
    {"id":"cn_g8_042","word":"诘责","pinyin":"jié zé","grade":8,"semester":"上册","example":"老师严厉地诘责了那个违反纪律的学生让他认识到错误。"},
    {"id":"cn_g8_043","word":"管束","pinyin":"guǎn shù","grade":8,"semester":"上册","example":"父母对孩子既要有爱也要适当管束不能一味溺爱。"},
    {"id":"cn_g8_044","word":"凄然","pinyin":"qī rán","grade":8,"semester":"上册","example":"想到即将分别大家心中不禁有些凄然不舍。"},
    {"id":"cn_g8_045","word":"教诲","pinyin":"jiào huì","grade":8,"semester":"上册","example":"老师的谆谆教诲至今仍深深印在我的脑海里难以忘怀。"},
    {"id":"cn_g8_046","word":"颓唐","pinyin":"tuí táng","grade":8,"semester":"上册","example":"连续几次失败后他的神情变得十分颓唐失去了斗志。"},
    {"id":"cn_g8_047","word":"琐屑","pinyin":"suǒ xiè","grade":8,"semester":"上册","example":"妈妈每天都要处理很多家庭琐屑之事忙得不可开交。"},
    {"id":"cn_g8_048","word":"差使","pinyin":"chāi shi","grade":8,"semester":"上册","example":"父亲接到差使后不得不匆匆赶往南京去办事。"},
    {"id":"cn_g8_049","word":"狼藉","pinyin":"láng jí","grade":8,"semester":"上册","example":"宴会结束后餐桌上杯盘狼藉一片狼藉不堪入目。"},
    {"id":"cn_g8_050","word":"簌簌","pinyin":"sù sù","grade":8,"semester":"上册","example":"秋风起树叶簌簌落下一片金黄铺满了大地。"},
]

# ═══ 八年级下册 (50条) ═══
G8S2 = [
    {"id":"cn_g8_051","word":"归省","pinyin":"guī xǐng","grade":8,"semester":"下册","example":"春节临近在外打工的人们纷纷回省探望亲人团聚过年。"},
    {"id":"cn_g8_052","word":"撺掇","pinyin":"cuān duo","grade":8,"semester":"下册","example":"在小伙伴的撺掇下我终于鼓起勇气去尝试攀岩运动。"},
    {"id":"cn_g8_053","word":"凫水","pinyin":"fú shuǐ","grade":8,"semester":"下册","example":"乡下的孩子个个都会凫水在河里游来游去玩得很开心。"},
    {"id":"cn_g8_054","word":"橹","pinyin":"lǔ","grade":8,"semester":"下册","example":"船夫用力摇动船橹小船在河面上缓缓前行。"},
    {"id":"cn_g8_055"," word":"潺潺","pinyin":"chán chán","grade":8,"semester":"下册","example":"山间的小溪流水潺潺清澈见底鱼儿在水里自由自在地游。"},
    {"id":"cn_g8_056","word":"朦胧","pinyin":"méng lóng","grade":8,"semester":"下册","example":"月光透过薄雾洒在水面上一切都显得朦胧而美丽。"},
    {"id":"cn_g8_057","word":"屹立","pinyin":"yì lì","grade":8,"semester":"下册","example":"人民英雄纪念碑巍然屹立在天安门广场中央气势雄伟。"},
    {"id":"cn_g8_058","word":"亢奋","pinyin":"kàng fèn","grade":8,"semester":"下册","example":"听到获胜的消息全队队员都处于极度亢奋的状态欢呼雀跃。"},
    {"id":"cn_g8_059","word":"晦暗","pinyin":"huì àn","grade":8,"semester":"下册","example":"乌云密布的天空显得格外晦暗压抑让人喘不过气来。"},
    {"id":"cn_g8_060","word":"羁绊","pinyin":"jī bàn","grade":8,"semester":"下册","example":"传统观念的羁绊束缚了人们的思想解放和社会进步。"},
    {"id":"cn_g8_061","word":"冗杂","pinyin":"rǒng zá","grade":8,"semester":"下册","example":"这些冗杂的文件占用了太多的存储空间需要清理一下。"},
    {"id":"cn_g8_062","word":"震撼","pinyin":"zhèn hàn","grade":8,"semester":"下册","example":"这场地震的威力之大令人震撼不已难以置信。"},
    {"id":"cn_g8_063","word":"磅礴","pinyin":"páng bó","grade":8,"semester":"下册","example":"黄河壶口瀑布的水势磅礴壮观气势恢宏让人叹为观止。"},
    {"id":"cn_g8_064","word":"闭塞","pinyin":"bì sè","grade":8,"semester":"下册","example":"这个山村交通闭塞与外界联系很少信息很不灵通。"},
    {"id":"cn_g8_065","word":"蛮横","pinyin":"mán hèng","grade":8,"semester":"下册","example":"他蛮横的态度让周围的人都很反感不愿意和他交往。"},
    {"id":"cn_g8_066","word":"挑剔","pinyin":"tiāo ti","grade":8,"semester":"下册","example":"顾客对商品质量越来越挑剔了商家必须提高品质。"},
    {"id":"cn_g8_067","word":"大彻大悟","pinyin":"dà chè dà wù","grade":8,"semester":"下册","example":"经历了一次重大挫折后他大彻大悟重新审视了自己的人生。"},
    {"id":"cn_g8_068","word":"叹为观止","pinyin":"tàn wéi guān zhǐ","grade":8,"semester":"下册","example":"这座古建筑群的精美程度令人叹为观止巧夺天工。"},
    {"id":"cn_g8_069","word":"戛然而止","pinyin":"jiá rán ér zhǐ","grade":8,"semester":"下册","example":"美妙的音乐戛然而止大厅里一片寂静大家都还沉浸在旋律中。"},
    {"id":"cn_g8_070","word":"销声匿迹","pinyin":"xiāo shēng nì jì","grade":8,"semester":"下册","example":"这种动物已经销声匿迹多年被认为已经灭绝了。"},
    {"id":"cn_g8_071","word":"衰草连天","pinyin":"shuāi cǎo lián tiān","grade":8,"semester":"下册","example":"深秋的原野上一片衰草连天的景象显得萧瑟荒凉。"},
    {"id":"cn_g8_072","word":"风雪载途","pinyin":"fēng xuě zài tú","grade":8,"semester":"下册","example":"游子在风雪载途中艰难前行思念着远方的家人。"},
    {"id":"cn_g8_073","word":"周而复始","pinyin":"zhōu ér fù shǐ","grade":8,"semester":"下册","example":"四季更替周而复始这是大自然的规律不可改变。"},
    {"id":"cn_g8_074","word":"花香鸟语","pinyin":"huā xiāng niǎo yǔ","grade":8,"semester":"下册","example":"春天来了到处都是花香鸟语的景象生机勃勃。"},
    {"id":"cn_g8_075","word":"草长莺飞","pinyin":"cǎo zhǎng yīng fēi","grade":8,"semester":"下册","example":"江南二月草长莺飞正是踏青的好时节春意盎然。"},
    {"id":"cn_g8_076","word":"天衣无缝","pinyin":"tiān yī wú fèng","grade":8,"semester":"下册","example":"这个故事编得天衣无缝让人看不出任何破绽来。"},
    {"id":"cn_g8_077","word":"海枯石烂","pinyin":"hǎi kū shí làn","grade":8,"semester":"下册","example":"他们发誓即使海枯石烂也永不分离爱情忠贞不渝。"},
    {"id":"cn_g8_078","word":"目空一切","pinyin":"mù kōng yī qiè","grade":8,"semester":"下册","example":"取得一点成绩后就目空一切的人最终往往会摔得很惨。"},
    {"id":"cn_g8_079","word":"强词夺理","pinyin":"qiáng cí duó lǐ","grade":8,"semester":"下册","example":"明明是自己错了他却还在那里强词夺理不肯认错。"},
    {"id":"cn_g8_080","word":"平易近人","pinyin":"píng yì jìn rén","grade":8,"semester":"下册","example":"这位教授虽然学问很高但待人平易近人没有架子。"},
    {"id":"cn_g8_081","word":"相得益彰","pinyin":"xiāng dé yì zhāng","grade":8,"semester":"下册","example":"这两件作品放在一起展览相得益彰效果更好。"},
    {"id":"cn_g8_082","word":"不修边幅","pinyin":"bù xiū biān fú","grade":8,"semester":"下册","example":"这位科学家一心扑在研究上平时不修边幅不注重外表。"},
    {"id":"cn_g8_083","word":"分崩离析","pinyin":"fēn bēng lí xī","grade":8,"semester":"下册","example":"曾经强大的帝国最终分崩离析化为历史的尘埃。"},
    {"id":"cn_g8_084","word":"暴风骤雨","pinyin":"bào fēng zhòu yǔ","grade":8,"semester":"下册","example":"一场暴风骤雨过后天空又恢复了晴朗万里无云。"},
    {"id":"cn_g8_085","word":"担惊受怕","pinyin":"dān jīng shòu pà","grade":8,"semester":"下册","example":"父母每天都在为孩子在外面的安全担惊受怕寝食难安。"},
    {"id":"cn_g8_086"," word":"行将就木","pinyin":"xíng jiāng jiù mù","grade":8,"semester":"下册","example":"那些落后的生产方式早已行将就木必将被时代所淘汰。"},
    {"id":"cn_g8_087","word":"格物致知","pinyin":"gé wù zhì zhī","grade":8,"semester":"下册","example":"古人提倡格物致知的治学方法强调通过实践获得真知。"},
    {"id":"cn_g8_088","word":"袖手旁观","pinyin":"xiù shǒu páng guān","grade":8,"semester":"下册","example":"看到有人遇到困难我们不能袖手旁观应该主动伸出援手。"},
    {"id":"cn_g8_089","word":"不知所措","pinyin":"bù zhī suǒ cuò","grade":8,"semester":"下册","example":"突如其来的消息让他完全不知所措不知道该怎么办。"},
    {"id":"cn_g8_090","word":"自圆其说","pinyin":"zì yuán qí shuō","grade":8,"semester":"下册","example":"不管你怎么辩解都无法自圆其说漏洞百出。"},
    {"id":"cn_g8_091","word":"参差不齐","pinyin":"cēn cī bù qí","grade":8,"semester":"下册","example":"这些树苗长得参差不齐有的高有的矮。"},
    {"id":"cn_g8_092"," word":"风调雨顺","pinyin":"fēng tiáo yǔ shùn","grade":8,"semester":"下册","example":"今年风调雨顺农民伯伯们又迎来了一个丰收年。"},
    {"id":"cn_g8_093"," word":"周而复始","pinyin":"zhōu ér fù shǐ","grade":8,"semester":"下册","example":"历史的发展往往呈现出周而复始的规律性特征。"},
    {"id":"cn_g8_094","word":"草长莺飞","pinyin":"cǎo zhǎng yīng fēi","grade":8,"semester":"下册","example":"江南三月草长莺飞桃红柳绿一派迷人的春光。"},
    {"id":"cn_g8_095","word":"天衣无缝","pinyin":"tiān yī wú fèng","grade":8,"semester":"下册","example":"这个计划安排得天衣无缝每个环节都衔接得很好。"},
    {"id":"cn_g8_096","word":"变化多端","pinyin":"biàn huà duō duān","grade":8,"semester":"下册","example":"魔术师的手法变化多端让观众眼花缭乱目不暇接。"},
    {"id":"cn_g8_097","word":"喜出望外","pinyin":"xǐ chū wàng wài","grade":8,"semester":"下册","example":"收到大学录取通知书的那一刻他喜出望外激动得跳了起来。"},
    {"id":"cn_g8_098","word":"各具特色","pinyin":"gè jù tè sè","grade":8,"semester":"下册","example":"这些手工艺品各具特色每件都有自己独特的风格。"},
    {"id":"cn_g8_099","word":"交头接耳","pinyin":"jiāo tóu jiē ěr","grade":8,"semester":"下册","example":"课堂上两个学生在下面交头接耳被老师发现了。"},
    {"id":"cn_g8_100","word":"因地制宜","pinyin":"yīn dì zhì yí","grade":8,"semester":"下册","example":"发展农业要因地制宜根据当地的气候土壤条件选择合适的作物。"},
]

# ═══ 九年级 (70条) ═══
G9 = [
    {"id":"cn_g9_001"," word":"妖娆","pinyin":"yāo ráo","grade":9,"semester":"全册","example":"盛开的牡丹花姿妖娆引得游人驻足欣赏拍照留念。"},
    {"id":"cn_g9_002","word":"风骚","pinyin":"fēng sāo","grade":9,"semester":"全册","example":"唐诗宋词在中国文学史上独领风骚数百年影响深远。"},
    {"id":"cn_g9_003","word":"红装素裹","pinyin":"hóng zhuāng sù guǒ","grade":9,"semester":"全册","example":"雪后的北京城红装素裹分外妖娆美不胜收。"},
    {"id":"cn_g9_004"," word":"一代天骄","pinyin":"yī dài tiān jiāo","grade":9,"semester":"全册","example":"成吉思汗是一代天骄建立了横跨欧亚的蒙古帝国。"},
    {"id":"cn_g9_005","word":"滔滔不绝","pinyin":"tāo tāo bù jué","grade":9,"semester":"全册","example":"他讲起自己旅行时的见闻来滔滔不绝停不下来。"},
    {"id":"cn_g9_006","word":"唯命是从","pinyin":"wéi mìng shì cóng","grade":9,"semester":"全册","example":"一个有主见的人不会对任何人唯命是从要有独立判断。"},
    {"id":"cn_g9_007","word":"鞠躬尽瘁","pinyin":"jū gōng jìn cuì","grade":9,"semester":"全册","example":"周总理鞠躬尽瘁为人民服务的精神永远激励着我们前行。"},
    {"id":"cn_g9_008"," word":"佝偻","pinyin":"góu lóu","grade":9,"semester":"全册","example":"那位老人因常年劳作而背脊佝偻步履蹒跚。"},
    {"id":"cn_g9_009"," word":"憔悴","pinyin":"qiáo cuì","grade":9,"semester":"全册","example":"母亲因为操劳过度而面容憔悴让人心疼不已。"},
    {"id":"cn_g9_010","word":"旁骛","pinyin":"páng wù","grade":9,"semester":"全册","example":"学习时不能旁骛要专心致志一心一意。"},
    {"id":"cn_g9_011"," word":"亵渎","pinyin":"xiè dú","grade":9,"semester":"全册","example":"这种行为是对先烈的极大亵渎和不敬应当受到谴责。"},
    {"id":"cn_g9_012","word":"敬业乐群","pinyin":"jìng yè lè qún","grade":9,"semester":"全册","example":"敬业乐群是我们中华民族的传统美德应当发扬光大。"},
    {"id":"cn_g9_013","word":"断章取义","pinyin":"duān zhāng qǔ yì","grade":9,"semester":"全册","example":"你这是断章取义完全没有理解作者的本意和文章的主旨。"},
    {"id":"cn_g9_014"," word":"不二法门","pinyin":"bù èr fǎ mén","grade":9,"semester":"全册","example":"勤奋努力是成功的唯一途径可谓不二法门别无捷径。"},
    {"id":"cn_g9_015"," word":"言不及义","pinyin":"yán bù jí yì","grade":9,"semester":"全册","example":"有些人整天言不及义说的都是些无聊的话没有实际意义。"},
    {"id":"cn_g9_016","word":"强聒不舍","pinyin":"qiǎng guō bù shě","grade":9,"semester":"全册","example":"推销员强聒不舍地纠缠着路人让人十分厌烦反感。"},
    {"id":"cn_g9_017","word":"荡然无存","pinyin":"dàng rán wú cún","grade":9,"semester":"全册","example":"一场大火过后这座千年古寺已经荡然无存只剩下残垣断壁。"},
    {"id":"cn_g9_018","word":"富丽堂皇","pinyin":"fù lì táng huáng","grade":9,"semester":"全册","example":"宫殿内部装修富丽堂皇金碧辉煌令人叹为观止。"},
    {"id":"cn_g9_019"," word":"丰功伟绩","pinyin":"fēng gōng wěi jì","grade":9,"semester":"全册","example":"邓小平同志为中国改革开放做出的丰功伟绩永载史册。"},
    {"id":"cn_g9_020"," word":"矫揉造作","pinyin":"jiǎo róu zào zuò","grade":9,"semester":"全册","example":"写作文要真情流露不要矫揉造作故作姿态。"},
    {"id":"cn_g9_021","word":"附庸风雅","pinyin":"fù yōng fēng yǎ","grade":9,"semester":"全册","example":"他根本不懂艺术买画只是为了附庸风雅装点门面。"},
    {"id":"cn_g9_022","word":"扭捏作态","pinyin":"niǔ niē zuò tài","grade":9,"semester":"全册","example":"大方一点不要在众人面前扭捏作态显得不大方。"},
    {"id":"cn_g9_023"," word":"随机应变","pinyin":"suí jī yìng biàn","grade":9,"semester":"全册","example":"一个好的主持人必须具备随机应变的能力应对各种突发情况。"},
    {"id":"cn_g9_024","word":"自吹自擂","pinyin":"zì chuī zì léi","grade":9,"semester":"全册","example":"他这个人就喜欢自吹自擂其实能力一般没什么真本事。"},
    {"id":"cn_g9_025","word":"根深蒂固","pinyin":"gēn shēn dì gù","grade":9,"semester":"全册","example":"封建思想在某些人的头脑中仍然根深蒂固难以改变。"},
    {"id":"cn_g9_026","word":"行之有效","pinyin":"xíng zhī yǒu xiào","grade":9,"semester":"全册","example":"这种方法简单实用确实行之有效值得推广。"},
    {"id":"cn_g9_027"," word":"孜孜不倦","pinyin":"zī zī bù juàn","grade":9,"semester":"全册","example":"他孜孜不倦地钻研学术问题终于取得了重大突破。"},
    {"id":"cn_g9_028","word":"持之以恒","pinyin":"chí zhī yǐ héng","grade":9,"semester":"全册","example":"学习外语需要持之以恒的努力不能三天打鱼两天晒网。"},
    {"id":"cn_g9_029","word":"不言而喻","pinyin":"bù yán ér yù","grade":9,"semester":"全册","example":"健康的重要性是不言而喻的没有健康什么都无从谈起。"},
    {"id":"cn_g9_030","word":"轻而易举","pinyin":"qīng ér yì jǔ","grade":9,"semester":"全册","example":"这件事对他来说轻而易举因为他有丰富的经验。"},
    {"id":"cn_g9_031","word":"画龙点睛","pinyin":"huà lóng diǎn jīng","grade":9,"semester":"全册","example":"最后这句话真是画龙点睛让整篇文章的主题一下子升华了。"},
    {"id":"cn_g9_032","word":"自暴自弃","pinyin":"zì bào zì qì","grade":9,"semester":"全册","example":"遇到挫折不要自暴自弃要勇敢地站起来继续前进。"},
    {"id":"cn_g9_033","word":"山穷水尽","pinyin":"shān qióng shuǐ jìn","grade":9,"semester":"全册","example":"就在公司山穷水尽之际一笔意外的投资让它起死回生。"},
    {"id":"cn_g9_034","word":"走投无路","pinyin":"zǒu tóu wú lù","grade":9,"semester":"全册","example":"他被逼得走投无路只好向朋友求助渡过难关。"},
    {"id":"cn_g9_035","word":"豁然开朗","pinyin":"huò rán kāi lǎng","grade":9,"semester":"全册","example":"听完老师的讲解我顿时豁然开朗明白了这道题的解法。"},
    {"id":"cn_g9_036"," word":"众说纷纭","pinyin":"zhòng shuō fēn yún","grade":9,"semester":"全册","example":"关于UFO的存在社会上众说纷纭莫衷一是没有定论。"},
    {"id":"cn_g9_037","word":"刨根问底","pinyin":"páo gēn wèn dǐ","grade":9,"semester":"全册","example":"科学家具有刨根问底的探索精神不弄清楚绝不罢休。"},
    {"id":"cn_g9_038","word":"不以为然","pinyin":"bù yǐ wéi rán","grade":9,"semester":"全册","example":"对他的说法我不以为然觉得有很多漏洞站不住脚。"},
    {"id":"cn_g9_039","word":"味同嚼蜡","pinyin":"wèi tóng jiáo là","grade":9,"semester":"全册","example":"这篇作文写得干巴巴的读起来味同嚼蜡毫无趣味。"},
    {"id":"cn_g9_040","word":"寻章摘句","pinyin":"xún zhāng zhāi jù","grade":9,"semester":"全册","example":"写论文不能只是寻章摘句堆砌材料要有自己的独到见解。"},
    {"id":"cn_g9_041","word":"吹毛求疵","pinyin":"chuī máo qiú cī","grade":9,"semester":"全册","example":"对人不能太苛刻不能总是吹毛求疵找别人的毛病。"},
    {"id":"cn_g9_042","word":"咬文嚼字","pinyin":"yǎo wén jiáo zì","grade":9,"semester":"全册","example":"读书时要理解文章的主旨思想不要只顾咬文嚼字抠字眼。"},
    {"id":"cn_g9_043","word":"浮光掠影","pinyin":"fú guāng lüè yǐng","grade":9,"semester":"全册","example":"学习不能浮光掠影要深入理解每一个知识点掌握精髓。"},
    {"id":"cn_g9_044","word":"怀古伤今","pinyin":"huái gǔ shāng jīn","grade":9,"semester":"全册","example":"这首诗借怀古伤今表达了诗人对现实的忧虑和不满之情。"},
    {"id":"cn_g9_045","word":"埋头苦干","pinyin":"mái tóu kǔ gàn","grade":9,"semester":"全册","example":"中国的发展离不开无数科研人员埋头苦干的奉献精神。"},
    {"id":"cn_g9_046","word":"拼命硬干","pinyin":"pīn mìng yìng gàn","grade":9,"semester":"全册","example":"中国人民有着拼命硬干的奋斗精神和顽强意志力。"},
    {"id":"cn_g9_047"," word":"为民请命","pinyin":"wèi mín qǐng mìng","grade":9,"semester":"全册","example":"古代许多清官敢于为民请命受到百姓的爱戴和拥护。"},
    {"id":"cn_g9_048","word":"舍身求法","pinyin":"shě shēn qiú fǎ","grade":9,"semester":"全册","example":"玄奘法师舍身求法历经千辛万苦从印度取回佛经。"},
    {"id":"cn_g9_049","word":"前仆后继","pinyin":"qián pū hòu jì","grade":9,"semester":"全册","example":"无数革命先烈前仆后继用生命换来了今天的幸福生活。"},
    {"id":"cn_g9_050","word":"不足为据","pinyin":"bù zú wéi jù","grade":9,"semester":"全册","example":"这些传闻缺乏证据不足为据不能作为判断的依据。"},
    {"id":"cn_g9_051"," word":"阴晴圆缺","pinyin":"yín qíng yuán quē","grade":9,"semester":"全册","example":"人有悲欢离合月有阴晴圆缺此事古难全。"},
    {"id":"cn_g9_052"," word":"悲欢离合","pinyin":"bēi huān lí hé","grade":9,"semester":"全册","example":"人生充满了悲欢离合我们要学会坦然面对珍惜当下。"},
    {"id":"cn_g9_053","word":"醉翁之意不在酒","pinyin":"zuì wēng zhī yì bù zài jiǔ","grade":9,"semester":"全册","example":"他表面上是来参观工厂的实际上是醉翁之意不在酒另有所图。"},
    {"id":"cn_g9_054","word":"水落石出","pinyin":"shuǐ luò shí chū","grade":9,"semester":"全册","example":"随着调查的深入真相终将水落石出大白于天下。"},
    {"id":"cn_g9_055","word":"峰回路转","pinyin":"fēng huí lù zhuǎn","grade":9,"semester":"全册","example":"案件调查陷入僵局后突然峰回路转发现了新的关键线索。"},
    {"id":"cn_g9_056","word":"觥筹交错","pinyin":"gōng chóu jiāo cuò","grade":9,"semester":"全册","example":"宴会上觥筹交错宾主尽欢气氛热烈融洽。"},
    {"id":"cn_g9_057","word":"伛偻提携","pinyin":"yǔ lǚ tí xié","grade":9,"semester":"全册","example":"滁州太守出游时路上往来不绝的是伛偻提携的老少百姓。"},
    {"id":"cn_g9_058","word":"林壑尤美","pinyin":"lín hè yóu měi","grade":9,"semester":"全册","example":"琅琊山的景色秀丽林壑尤美吸引了许多游客前来游览观光。"},
    {"id":"cn_g9_059"," word":"蔚然深秀","pinyin":"wèi rán shēn xiù","grade":9,"semester":"全册","example":"远望去山林郁郁葱葱蔚然深秀一片苍翠欲滴的美景。"},
    {"id":"cn_g9_060","word":"泉香酒洌","pinyin":"quán xiāng jiǔ liè","grade":9,"semester":"全册","example":"酿泉水酿酒泉香酒洌味道醇厚回味悠长。"},
    {"id":"cn_g9_061","word":"繁阴","pinyin":"fán yīn","grade":9,"semester":"全册","example":"夏天树木长得茂密枝叶繁阴为行人遮阳挡雨。"},
    {"id":"cn_g9_062","word":"苍颜白发","pinyin":"cāng yán bái fà","grade":9,"semester":"全册","example":"太守虽已苍颜白发但仍精神矍铄地与民同乐。"},
    {"id":"cn_g9_063","word":"与民同乐","pinyin":"yǔ mín tóng lè","grade":9,"semester":"全册","example":"作为领导干部要时刻牢记与民同乐的执政理念全心全意为民服务。"},
    {"id":"cn_g9_064","word":"雾凇沆砀","pinyin":"wù sōng hàng dàng","grade":9,"semester":"全册","example":"冬日西湖的早晨雾凇沆砀宛如仙境般美丽动人。"},
    {"id":"cn_g9_065","word":"长堤一痕","pinyin":"cháng dī yī hén","grade":9,"semester":"全册","example":"远处的长堤一痕在茫茫白雪中若隐若现如同水墨画。"},
    {"id":"cn_g9_066"," word":"湖中人鸟声俱绝","pinyin":"hú zhōng rén niǎo shēng jù jué","grade":9,"semester":"全册","example":"大雪下了三天西湖中湖中人鸟声俱绝一片寂静安宁。"},
    {"id":"cn_g9_067"," word":"更有痴似相公者","pinyin":"gèng yǒu chī sì xiàng gōng zhě","grade":9,"semester":"全册","example":"莫说相公痴更有痴似相公者原来还有像我一样痴迷雪景的人。"},
    {"id":"cn_g9_068","word":"浩浩汤汤","pinyin":"hào hào shāng shāng","grade":9,"semester":"全册","example":"洞庭湖水面浩浩汤汤横无际涯气象万千。"},
    {"id":"cn_g9_069"," word":"朝晖夕阴","pinyin":"zhāo huī xī yīn","grade":9,"semester":"全册","example":"洞庭湖朝晖夕阴气象万千景色变化无穷令人陶醉。"},
    {"id":"cn_g9_070"," word":"心旷神怡","pinyin":"xīn kuàng shén yí","grade":9,"semester":"全册","example":"登上高山之巅俯瞰群山让人感到心旷神怡宠辱皆忘。"},
]


def main():
    # 读取现有数据
    with open(INPUT, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    print(f"读取现有词库: {len(existing)} 条")

    # 合并所有新数据
    all_new = G7S1 + G7S2 + G8S1 + G8S2 + G9

    # 检查重复ID
    existing_ids = {w['id'] for w in existing}
    dupes = [w for w in all_new if w['id'] in existing_ids]
    if dupes:
        print(f"⚠️ 跳过重复ID: {[w['id'] for w in dupes]}")
        all_new = [w for w in all_new if w['id'] not in existing_ids]

    merged = existing + all_new

    # 写入
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)

    print(f"\n✅ 写入完成!")
    print(f"   新增: {len(all_new)} 条")
    print(f"   总计: {len(merged)} 条")

    # 统计
    grades = Counter(w['grade'] for w in merged)
    print(f"\n按年级统计:")
    for g in sorted(grades.keys()):
        label = {7:'初一', 8:'初二', 9:'初三'}.get(g, f'{g}年级')
        print(f"  {label}({g}年级): {grades[g]}条")


if __name__ == '__main__':
    main()
