#!/usr/bin/env python3
"""Generate Grade 7 (初一) English dictation word list - Go for It! textbook."""

import json
import sys

words = []

def add(word, meaning, phonetic, example, semester):
    """Add a word entry."""
    idx = len(words) + 1
    words.append({
        "id": f"en_g7_{idx:03d}",
        "word": word,
        "meaning": meaning,
        "grade": 7,
        "semester": semester,
        "phonetic": phonetic,
        "example": example
    })

# ============================================================
# 上册 (First Semester)
# ============================================================

# --- Starter Units 1-3 ---
add("hello", "你好；喂", "/həˈləʊ/", "Hello, my name is Tom.", "上册")
add("hi", "嗨；你好（hello的 informal）", "/haɪ/", "Hi! How are you?", "上册")
add("good", "好的；令人满意的", "/ɡʊd/", "Good morning, class.", "上册")
add("morning", "早晨；上午", "/ˈmɔːnɪŋ/", "I get up early every morning.", "上册")
add("afternoon", "下午", "/ˌɑːftəˈnuːn/", "Good afternoon, everyone.", "上册")
add("evening", "晚上；傍晚", "/ˈiːvnɪŋ/", "Good evening, sir.", "上册")
add("how", "怎样；如何；多么", "/haʊ/", "How are you?", "上册")
add("are", "是（be的第二人称单复数形式）", "/ɑː(r)/", "You are a good student.", "上册")
add("you", "你；你们", "/juː/", "How are you today?", "上册")
add("I", "我", "/aɪ/", "I am fine, thanks.", "上册")
add("am", "是（be的第一人称单数形式）", "/æm/", "I am a student.", "上册")
add("fine", "健康的；美好的；（天气）晴朗的", "/faɪn/", "I'm fine, thank you.", "上册")
add("thanks", "感谢；谢谢", "/θæŋks/", "Thanks for your help.", "上册")
add("OK", "好；可以", "/ˌəʊˈkeɪ/", "OK, let's go!", "上册")
add("what", "什么；什么样的", "/wɒt/", "What is your name?", "上册")
add("is", "是（be的第三人称单数形式）", "/ɪz/", "This is a book.", "上册")
add("this", "这；这个", "/ðɪs/", "This is my friend, Alice.", "上册")
add("in", "在……里；用（语言等）；穿着", "/ɪn/", "What's this in English?", "上册")
add("English", "英语；英格兰的；英语的", "/ˈɪŋɡlɪʃ/", "We learn English at school.", "上册")
add("map", "地图", "/mæp/", "Look at the map of China.", "上册")
add("cup", "杯子", "/kʌp/", "This is a nice cup.", "上册")
add("ruler", "尺；直尺", "/ˈruːlə(r)/", "Can I borrow your ruler?", "上册")
add("pen", "钢笔；笔", "/pen/", "I need a pen to write.", "上册")
add("orange", "橙子；橙色的", "/ˈɒrɪndʒ/", "The orange is very sweet.", "上册")
add("jacket", "夹克衫；短上衣", "/ˈdʒækɪt/", "Put on your jacket, it's cold.", "上册")
add("key", "钥匙；关键", "/kiː/", "Where is the key to the door?", "上册")
add("quilt", "被子；床罩", "/kwɪlt/", "The quilt is warm and soft.", "上册")
add("it", "它", "/ɪt/", "It is a red apple.", "上册")
add("a", "一（个/件……）（用于以辅音音素开头的词前）", "/ə/", "It's a book.", "上册")
add("an", "一（个/件……）（用于以元音音素开头的词前）", "/ən/", "It's an orange.", "上册")
add("that", "那；那个", "/ðæt/", "What's that in English?", "上册")
add("spell", "用字母拼；拼写", "/spel/", "Can you spell your name?", "上册")
add("please", "请（礼貌用语）", "/pliːz/", "Please come in.", "上册")
add("color", "颜色", "/ˈkʌlə(r)/", "What color is your bag?", "上册")
add("red", "红色的；红色的", "/red/", "The red car looks nice.", "上册")
add("yellow", "黄色的；黄色的", "/ˈjeləʊ/", "I like the yellow dress.", "上册")
add("green", "绿色的；绿色的", "/ɡriːn/", "The trees are green in spring.", "上册")
add("blue", "蓝色的；蓝色的", "/bluː/", "The sky is blue today.", "上册")
add("black", "黑色的；黑色的", "/blæk/", "My cat has black fur.", "上册")
add("white", "白色的；白色的", "/waɪt/", "Snow is white and cold.", "上册")
add("purple", "紫色的；紫色的", "/ˈpɜːpl/", "She wears a purple hat.", "上册")
add("brown", "棕色的；褐色的", "/braʊn/", "His shoes are brown.", "上册")
add("the", "这（那）个；这（那）些（定冠词）", "/ðə/ /ðiː/", "The book is on the desk.", "上册")
add("now", "现在；目前", "/naʊ/", "I am busy now.", "上册")
add("see", "看见；看到；明白", "/siː/", "I can see a bird in the tree.", "上册")
add("say", "说；讲", "/seɪ/", "Please say it again.", "上册")
add("my", "我的", "/maɪ/", "This is my pencil box.", "上册")
add("your", "你的；你们的", "/jɔː(r)/", "What is your favorite color?", "上册")
add("teacher", "教师；老师", "/ˈtiːtʃə(r)/", "Our teacher is very kind.", "上册")
add("mom", "妈妈（非正式用语）", "/mɒm/", "Mom, I'm home!", "上册")
add("dad", "爸爸（非正式用语）", "/dæd/", "Dad, can you help me?", "上册")
add("parent", "父亲（或母亲）", "/ˈpeərənt/", "My parents love me very much.", "上册")
add("sister", "姐；妹", "/ˈsɪstə(r)/", "My sister is ten years old.", "上册")
add("brother", "兄；弟", "/ˈbrʌðə(r)/", "He is my younger brother.", "上册")
add("grandmother", "奶奶；外婆；（外）祖母", "/ˈɡrʌnmʌðə(r)/", "Grandmother tells me stories every night.", "上册")
add("grandpa", "爷爷；外公；（外）祖父", "/ˈɡrænpɑː/", "Grandpa likes reading newspapers.", "上册")
add("grandparent", "祖父；祖母；外祖父；外祖母", "/ˈɡænpeərənt/", "My grandparents live in the countryside.", "上册")
add("family", "家；家庭", "/ˈfæməli/", "I have a big family.", "上册")
add("those", "那些", "/ðəʊz/", "Those are my books.", "上册")
add("who", "谁；什么人", "/huː/", "Who is that girl over there?", "上册")
add("they", "他（她、它）们", "/ðeɪ/", "They are my classmates.", "上册")
add("have", "有；吃；喝", "/hæv/", "I have a new bike.", "上册")
add("well", "嗯；好吧；良好的", "/wel/", "Well, let me think about it.", "上册")
add("son", "儿子", "/sʌn/", "Their son goes to the same school.", "上册")
add("daughter", "女儿", "/ˈdɔːtə(r)/", "She is their only daughter.", "上册")
add("cousin", "堂兄弟姊妹；表兄弟姊妹", "/ˈkʌzn/", "My cousin lives in Beijing.", "上册")
add("uncle", "叔；伯；舅；姑父；姨父", "/ˈʌŋkl/", "Uncle Tom gave me a gift.", "上册")
add("aunt", "姑母；姨母；伯母；婶母；舅母", "/ɑːnt/", "Aunt Mary cooks delicious food.", "上册")
add("photo", "照片；相片", "/ˈfəʊtəʊ/", "Let me take a photo of you.", "上册")
add("here", "这里；在这里", "/hɪə(r)/", "Here is your book.", "上册")
add("picture", "照片；图画", "/ˈpɪktʃə(r)/", "This picture is beautiful.", "上册")
add("girl", "女孩", "/ɡɜːl/", "The girl is reading a book.", "上册")
add("dog", "狗", "/dɒɡ/", "My dog likes playing with balls.", "上册")

# --- Unit 1: My Name / Greetings ---
add("name", "名字；名称", "/neɪm/", "What's your name?", "上册")
add("nice", "令人愉快的；宜人的", "/naɪs/", "Nice to meet you!", "上册")
add("meet", "遇见；相逢", "/miːt/", "Nice to meet you, too.", "上册")
add("too", "也；又；太", "/tuː/", "I like apples, too.", "上册")
add("his", "他的", "/hɪz/", "This is his backpack.", "上册")
add("her", "她的", "/hɜː(r)/", "Her name is Mary.", "上册")
add("she", "她", "/ʃiː/", "She is from China.", "上册")
add("he", "他", "/hiː/", "He is twelve years old.", "上册")
add("yes", "是的；可以", "/jes/", "Yes, I agree with you.", "上册")
add("no", "不；不是；没有", "/nəʊ/", "No, I don't like coffee.", "上册")
add("not", "不；没有；不是", "/nɒt/", "I'm not ready yet.", "上册")
add("zero", "零", "/ˈzɪərəʊ/", "Zero comes before one.", "上册")
add("one", "一", "/wʌn/", "I have one sister and two brothers.", "上册")
add("two", "二", "/tuː/", "Two plus two equals four.", "上册")
add("three", "三", "/θriː/", "There are three apples on the table.", "上册")
add("four", "四", "/fɔː(r)/", "There are four seasons in a year.", "上册")
add("five", "五", "/faɪv/", "I get up at five o'clock.", "上册")
add("six", "六", "/sɪks/", "Six students are in our group.", "上册")
add("seven", "七", "/ˈsevn/", "Seven days make a week.", "上册")
add("eight", "八", "/eɪt/", "There are eight people in my family.", "上册")
add("nine", "九", "/naɪn/", "Nine plus one equals ten.", "上册")
add("telephone", "电话；电话机", "/ˈtelɪfəʊn/", "May I use your telephone?", "上册")
add("number", "号码；数字；数量", "/ˈnʌmbə(r)/", "What's your phone number?", "上册")
add("phone", "电话；电话机", "/fəʊn/", "Call me on my phone.", "上册")
add("first", "第一的；首先", "/fɜːst/", "January is the first month.", "上册")
add("last", "最后的；上一个的", "/lɑːst/", "December is the last month.", "上册")
add("friend", "朋友", "/frend/", "She is my best friend.", "上册")
add("China", "中国", "/ˈtʃaɪnə/", "I was born in China.", "上册")
add("middle", "中间的；中等的", "/ˈmɪdl/", "I go to No. 1 Middle School.", "上册")
add("school", "学校", "/skuːl/", "Our school is very beautiful.", "上册")
add("boy", "男孩", "/bɔɪ/", "That boy is very tall.", "上册")

# --- Unit 2: Is This Your Pencil? ---
add("pencil", "铅笔", "/ˈpensl/", "Use a pencil to do the homework.", "上册")
add("book", "书；本子", "/bʊk/", "This book is interesting.", "上册")
add("eraser", "橡皮擦", "/ɪˈreɪzə(r)/", "I need an eraser for my mistakes.", "上册")
add("box", "箱；盒", "/bɒks/", "Put your pencils in the box.", "上册")
add("schoolbag", "书包", "/ˈskuːlbæɡ/", "Don't forget your schoolbag.", "上册")
add("bag", "包；袋", "/bæɡ/", "She carries a pink bag.", "上册")
add("baseball", "棒球", "/ˈbeɪsbɔːl/", "He plays baseball after school.", "上册")
add("watch", "手表；观看", "/wɒtʃ/", "My watch shows eight o'clock.", "上册")
add("computer", "电脑；计算机", "/kəmˈpjuːtə(r)/", "I use my computer to study.", "上册")
add("game", "游戏；比赛", "/ɡeɪn/", "Let's play a game together.", "上册")
add("card", "卡片；牌", "/kɑːd/", "Show me your ID card.", "上册")
add("notebook", "笔记本", "/ˈnəʊtbʊk/", "Write down the notes in your notebook.", "上册")
add("ring", "戒指；环；铃声", "/rɪŋ/", "She wears a gold ring.", "上册")
add("library", "图书馆", "/ˈlaɪbrəri/", "I often read books in the library.", "上册")
add("some", "一些；某些；有些", "/sʌm/", "Would you like some water?", "上册")
add("find", "找到；发现", "/faɪnd/", "I can't find my keys.", "上册")
add("help", "帮助；帮忙", "/help/", "Can you help me?", "上册")
add("welcome", "欢迎", "/ˈwelkəm/", "Welcome to our school!", "上册")
add("lost", "丢失的；迷失的；迷路的", "/lɒst/", "I lost my wallet yesterday.", "上册")
add("must", "必须", "/mʌst/", "You must finish homework first.", "上册")
add("call", "打电话给……；称呼；呼唤", "/kɔːl/", "Please call me at six.", "上册")
add("at", "在（某处）；在（学习或工作时）；以；向", "/æt/ /ət/", "See you at five o'clock.", "上册")
add("set", "一套；一副；放置；设置", "/set/", "I have a set of pens.", "上册")
add("e-mail", "电子邮件", "/ˈiːmeɪl/", "Send me an e-mail tonight.", "上册")
add("ask", "请求；要求；询问", "/ɑːsk/", "Ask the teacher for help.", "上册")
add("excuse", "原谅；宽恕", "/ɪkˈskjuːz/", "Excuse me, where is the restroom?", "上册")
add("about", "关于；大约", "/əˈbaʊt/", "Tell me about yourself.", "上册")
add("dictionary", "字典；词典", "/ˈdɪkʃənri/", "Use a dictionary to look up new words.", "上册")
add("ours", "我们的（东西）", "/ˈaʊəz/", "This classroom is ours.", "上册")
add("mine", "我的（东西）", "/maɪn/", "This book is mine.", "上册")
add("yours", "你的（东西）；你们的（东西）", "/jɔːz/", "Is this pen yours?", "上册")
add("hers", "她的（东西）", "/hɜːz/", "That bag is hers.", "上册")
add("our", "我们的", "/ˈaʊə(r)/", "Our classroom is on the second floor.", "上册")
add("their", "他们的；她们的；它们的", "/ðeə(r)/", "Their house is near the park.", "上册")
add("classroom", "教室", "/ˈklɑːsruːm/", "Keep the classroom clean.", "上册")

# --- Unit 3: Do You Have a Soccer Ball? ---
add("soccer", "足球（英式football）", "/ˈsɒkə(r)/", "I play soccer with my friends.", "上册")
add("tennis", "网球", "/ˈtenɪs/", "She plays tennis very well.", "上册")
add("ball", "球；舞会", "/bɔːl/", "Throw the ball to me.", "上册")
add("ping-pong", "乒乓球", "/ˈpɪŋ pɒŋ/", "Let's play ping-pong after class.", "上册")
add("bat", "球棒；球拍；蝙蝠", "/bæt/", "He hit the ball with the bat.", "上册")
add("basketball", "篮球", "/ˈbɑːskɪtbɔːl/", "Basketball is popular in America.", "上册")
add("volleyball", "排球", "/ˈvɒlibɔːl/", "The girls play volleyball on the court.", "上册")
add("let", "让；允许", "/let/", "Let me help you carry that.", "上册")
add("us", "我们（we的宾格）", "/ʌs/ /əs/", "The teacher told us a story.", "上册")
add("go", "去；走；变为", "/ɡəʊ/", "Let's go home together.", "上册")
add("we", "我们", "/wiː/", "We are classmates.", "上册")
add("play", "参加（体育活动、比赛等）；玩耍；演奏", "/pleɪ/", "I play basketball every day.", "上册")
add("sound", "听起来好像；声音", "/saʊnd/", "That sounds great!", "上册")
add("sport", "体育运动", "/spɔːt/", "What sport do you like best?", "上册")
add("love", "爱；喜爱", "/lʌv/", "I love my family.", "上册")
add("like", "喜欢；像", "/laɪk/", "I like listening to music.", "上册")
add("interesting", "有趣的；引起兴趣的", "/ˈɪntrəstɪŋ/", "This book is very interesting.", "上册")
add("fun", "有趣的；使人快乐的；乐趣", "/fʌn/", "Swimming is fun in summer.", "上册")
add("boring", "无聊的；令人厌烦的", "/ˈbɔːrɪŋ/", "The movie was really boring.", "上册")
add("difficult", "困难的", "/ˈdɪfɪkəlt/", "Math is difficult for some students.", "上册")
add("easy", "容易的；不费力的", "/ˈiːzi/", "English grammar is easy for her.", "上册")
add("relaxing", "放松的；令人放松的", "/rɪˈlæksɪŋ/", "Music is relaxing after work.", "上册")
add("same", "相同的", "/seɪm/", "We are in the same class.", "上册")
add("only", "只；仅仅；唯一的", "/ˈəʊnli/", "I have only one brother.", "上册")
add("after", "在……之后；在……后面", "/ˈɑːftə(r)/", "Let's play after school.", "上册")
add("class", "课；班级；（一堂）课", "/klɑːs/", "Class begins at eight.", "上册")
add("classmate", "同班同学", "/ˈklɑːsmeɪt/", "Tom is my classmate.", "上册")
add("but", "但是；然而", "/bʌt/", "I like apples but not bananas.", "上册")
add("with", "和……在一起；带有；用", "/wɪð/", "I went to the cinema with my friends.", "上册")
add("them", "他（她、它）们（they的宾格）", "/ðem/ /ðəm/", "Please give them the books.", "上册")
add("has", "有（have的单三形式）", "/hæz/", "She has a new bicycle.", "上册")
add("get", "得到；取；到达；成为", "/ɡet/", "I get up early every day.", "上册")
add("great", "美妙的；伟大的", "/ɡreɪt/", "That's a great idea!", "上册")
add("doesn't", "does not 的缩写", "/ˈdʌznt/", "She doesn't like spicy food.", "上册")

# --- Unit 4: Where Is My Schoolbag? ---
add("where", "在哪里；到哪里", "/weə(r)/", "Where is my schoolbag?", "上册")
add("table", "桌子；表格", "/ˈteɪbl/", "Put the book on the table.", "上册")
add("bed", "床", "/bed/", "Go to bed early tonight.", "上册")
add("desk", "书桌；办公桌", "/desk/", "There is a computer on the desk.", "上册")
add("chair", "椅子", "/tʃeə(r)/", "Sit down on the chair.", "上册")
add("sofa", "长沙发", "/ˈsəʊfə/", "The cat sleeps on the sofa.", "上册")
add("room", "房间", "/ruːm/", "My room is small but clean.", "上册")
add("under", "在……下面", "/ˈʌndə(r)/", "The ball is under the chair.", "上册")
add("come", "来；来到", "/kʌm/", "Come here, please.", "上册")
add("think", "想；认为", "/θɪŋk/", "I think she is right.", "上册")
add("know", "知道；了解；认识", "/nəʊ/", "I don't know the answer.", "上册")
add("head", "头；头部", "/hed/", "Wash your head before bed.", "上册")
add("hat", "帽子", "/hæt/", "Put on your hat, it's sunny outside.", "上册")
add("tidy", "整洁的；整齐的；整理", "/ˈtaɪdi/", "Keep your room tidy.", "上册")
add("everywhere", "处处；到处；各个地方", "/ˈevriweə(r)/", "Toys are everywhere in his room.", "上册")

# --- Unit 5: Do You Like Bananas? ---
add("banana", "香蕉", "/bəˈnɑːnə/", "I eat a banana every morning.", "上册")
add("hamburger", "汉堡包", "/ˈhæmbɜːɡə(r)/", "Would you like a hamburger?", "上册")
add("tomato", "西红柿；番茄", "/təˈmɑːtəʊ/", "Cut the tomatoes for the salad.", "上册")
add("ice-cream", "冰淇淋", "/ˈaɪs kriːm/", "Kids love ice-cream in summer.", "上册")
add("salad", "沙拉", "/ˈsæləd/", "I'd like a fruit salad.", "上册")
add("strawberry", "草莓", "/ˈstrɔːbəri/", "Strawberries are sweet and juicy.", "上册")
add("pear", "梨", "/peə(r)/", "The pear tastes sweet.", "上册")
add("milk", "牛奶", "/mɪlk/", "Drink milk for strong bones.", "上册")
add("bread", "面包", "/bred/", "I have bread and eggs for breakfast.", "上册")
add("rice", "米饭；稻米", "/raɪs/", "Chinese people eat rice every day.", "上册")
add("food", "食物；食品", "/fuːd/", "Fast food is not healthy.", "上册")
add("fruit", "水果", "/fruːt/", "Eat more fruit for vitamins.", "上册")
add("vegetable", "蔬菜", "/ˈvedʒtəbl/", "Vegetables are good for health.", "上册")
add("breakfast", "早餐；早饭", "/ˈbrekfəst/", "I usually have milk and bread for breakfast.", "上册")
add("lunch", "午餐；午饭", "/lʌntʃ/", "What did you have for lunch?", "上册")
add("dinner", "正餐；晚餐；（正式的）宴会", "/ˈdɪnə(r)/", "Dinner is ready. Come and eat!", "上册")
add("week", "周；星期", "/wiːk/", "There are seven days in a week.", "上册")
add("fat", "肥胖的；肥肉；脂肪", "/fæt/", "Too much fat is unhealthy.", "上册")
add("healthy", "健康的", "/ˈhelθi/", "Eating vegetables keeps you healthy.", "上册")
add("really", "真正地；确实", "/ˈriːəli/", "I really like this song.", "上册")
add("want", "想要；需要", "/wɒnt/", "I want to drink some water.", "上册")
add("be", "是；成为（原形，am/is/are的原形）", "/biː/", "To be or not to be.", "上册")
add("star", "星星；明星；（指娱乐、体育界的）星", "/stɑː(r)/", "He wants to be a movie star.", "上册")
add("eat", "吃", "/iːt/", "We eat three meals a day.", "上册")
add("habit", "习惯", "/ˈhæbɪt/", "Reading before bed is a good habit.", "上册")
add("question", "问题；疑问；询问", "/ˈkwestʃən/", "Do you have any questions?", "上册")
add("then", "然后；那么；接着", "/ðen/", "Finish your homework, then you can play.", "上册")

# --- Unit 6: How Much Are These Socks? ---
add("much", "许多；多少；非常", "/mʌtʃ/", "How much is this shirt?", "上册")
add("sock", "短袜", "/sɒk/", "I need to buy some socks.", "上册")
add("T-shirt", "T恤衫", "/ˈtiːʃɜːt/", "This T-shirt is too small for me.", "上册")
add("short", "短的；矮的", "/ʃɔːt/", "These shorts are comfortable.", "上册")
add("shorts", "短裤", "/ʃɔːts/", "Wear shorts when it's hot.", "上册")
add("sweater", "毛衣", "/ˈswetə(r)/", "Put on a sweater, it's cold.", "上册")
add("trouser", "裤子（常用复数trousers）", "/ˈtraʊzə(r)/", "He needs a pair of trousers.", "上册")
add("trousers", "裤子", "/ˈtraʊzərz/", "These trousers fit me well.", "上册")
add("skirt", "女裙；裙子", "/skɜːt/", "She looks pretty in that skirt.", "上册")
add("dollar", "美元（货币单位）", "/ˈdɒlə(r)/", "This costs five dollars.", "上册")
add("big", "大的；巨大的", "/bɪɡ/", "This shirt is too big for me.", "上册")
add("small", "小的；小号的", "/smɔːl/", "Do you have this in small size?", "上册")
add("long", "长的；长时间的", "/lɒŋ/", "Her hair is long and black.", "上册")
add("woman", "女人；成年女子", "/ˈwʊmən/", "That woman is my mother.", "上册")
add("need", "需要", "/niːd/", "I need a new pen.", "上册")
add("look", "看；看起来；注视", "/lʊk/", "Look at the blackboard, please.", "上册")
add("take", "拿取；买下；花费；乘坐", "/teɪk/", "I'll take this one.", "上册")
add("pair", "一双；一对；一副", "/peə(r)/", "I need a pair of shoes.", "上册")
add("clothes", "衣服；服装", "/kləʊðz/", "Buy clothes at the store.", "上册")
add("shoe", "鞋", "/ʃuː/", "My shoes are dirty.", "上册")
add("store", "商店；店铺", "/stɔː(r)/", "Let's go to the clothes store.", "上册")
add("buy", "购买；买", "/baɪ/", "I want to buy a gift for Mom.", "上册")
add("sale", "出售；销售；特价销售", "/seɪn/", "Everything is on sale this weekend.", "上册")
add("very", "很；非常；极其", "/ˈveri/", "Thank you very much.", "上册")
add("price", "价格；价钱", "/praɪs/", "What's the price of this bag?", "上册")
add("all", "全部的；所有的", "/ɔːl/", "All students are here today.", "上册")
add("every", "每一；每个", "/ˈevri/", "Every student should read this book.", "上册")
add("anybody", "任何人", "/ˈenibɒdi/", "Is anybody here?", "上册")
add("cheap", "便宜的；廉价的", "/tʃiːp/", "These socks are cheap.", "上册")
add("expensive", "昂贵的；花钱多的", "/ɪkˈspensɪv/", "That watch is too expensive.", "上册")
add("sorry", "对不起；抱歉的", "/ˈsɒri/", "Sorry, I'm late.", "上册")
add("sir", "先生（对男性的尊称）", "/sɜː(r)/", "Yes, sir!", "上册")
add("madam", "女士；夫人（对女性的尊称）", "/ˈmædəm/", "May I help you, madam?", "上册")

# --- Unit 7: When Is Your Birthday? ---
add("when", "什么时候；何时", "/wen/", "When is your birthday?", "上册")
add("birthday", "生日", "/ˈbɜːθdeɪ/", "Happy birthday to you!", "上册")
add("month", "月；月份", "/mʌnθ/", "There are twelve months in a year.", "上册")
add("January", "一月", "/ˈdʒænjuəri/", "New Year's Day is in January.", "上册")
add("February", "二月", "/ˈfebruəri/", "February has twenty-eight or twenty-nine days.", "上册")
add("March", "三月", "/mɑːtʃ/", "March is the third month.", "上册")
add("April", "四月", "/ˈeɪprəl/", "April Fool's Day is fun.", "上册")
add("May", "五月", "/meɪ/", "May Day is a holiday.", "上册")
add("June", "六月", "/dʒuːn/", "Children's Day is in June.", "上册")
add("July", "七月", "/dʒuˈlaɪ/", "It is very hot in July.", "上册")
add("August", "八月", "/ˈɔːɡəst/", "School starts in August.", "上册")
add("September", "九月", "/sepˈtembə(r)/", "September is back-to-school season.", "上册")
add("October", "十月", "/ɒkˈtəʊbə(r)/", "National Day is in October.", "上册")
add("November", "十一月", "/nəʊˈvembə(r)/", "November is getting colder.", "上册")
add("December", "十二月", "/dɪˈsembə(r)/", "Christmas is in December.", "上册")
add("happy", "高兴的；幸福的", "/ˈhæpi/", "Happy New Year!", "上册")
add("old", "老的；旧的；……岁的", "/əʊld/", "How old are you?", "上册")
add("party", "聚会；派对；党派", "/ˈpɑːti/", "Come to my birthday party!", "上册")
add("trip", "旅行；旅游", "/trɪp/", "We are going on a school trip.", "上册")
add("art", "美术；艺术；艺术品", "/ɑːt/", "I like art class.", "上册")
add("festival", "节日；（音乐等的）会演节", "/ˈfestɪvl/", "Spring Festival is important in China.", "上册")
add("thing", "事情；东西", "/θɪŋ/", "One more thing, don't forget your ticket.", "上册")
add("student", "学生", "/ˈstjuːdnt/", "Every student should follow the rules.", "上册")
add("test", "考试；测验；试验", "/test/", "We have a math test tomorrow.", "上册")
add("time", "时间；次数；倍（数）", "/taɪm/", "What time is it now?", "上册")
add("busy", "忙的；繁忙的", "/ˈbɪzi/", "Mom is always busy on weekdays.", "上册")
add("term", "学期；术语；条款", "/tɜːm/", "The new term starts in September.", "上册")
add("there", "在那里；在那儿（与be连用表示存在）", "/ðeə(r)/", "There is a book on the desk.", "上册")
add("schedule", "日程表；计划表；时间表", "/ˈʃedjuːl/", "Look at my schedule for next week.", "上册")
add("favorite", "特别喜爱的（人或事物）", "/ˈfeɪvərɪt/", "My favorite color is blue.", "上册")
add("subject", "学科；科目；主题；主语", "/ˈsʌbdʒɪkt/", "Which subject do you like best?", "上册")
add("science", "科学；自然科学", "/ˈsaɪəns/", "Science teaches us about nature.", "上册")
add("P.E.", "体育（Physical Education的缩写）", "/ˌpiː ˈiː/", "We have P.E. on Friday afternoon.", "上册")
add("music", "音乐；乐曲", "/ˈmjuːzɪk/", "She loves music very much.", "上册")
add("math", "数学", "/mæθ/", "Math is my favorite subject.", "上册")
add("Chinese", "语文；中文；中国的；中国人", "/ˌtʃaɪˈniːz/", "We learn Chinese every day.", "上册")
add("geography", "地理；地理学", "/dʒiˈɒɡrəfi/", "Geography helps us understand the world.", "上册")
add("history", "历史；历史学", "/ˈhɪstri/", "History tells us about the past.", "上册")
add("because", "因为", "/bɪˈkɒz/", "I like music because it makes me happy.", "上册")
add("cool", "酷的；凉爽的", "/kuːl/", "Your bike looks cool!", "上册")
add("free", "空闲的；免费的", "/friː/", "Are you free tomorrow?", "上册")
add("Tuesday", "星期二", "/ˈtuːzdeɪ/", "We have English class on Tuesday.", "上册")
add("Wednesday", "星期三", "/ˈwenzdeɪ/", "Wednesday is the fourth day.", "上册")
add("Thursday", "星期四", "/ˈθɜːzdeɪ/", "Thursday comes after Wednesday.", "上册")
add("Friday", "星期五", "/ˈfraɪdeɪ/", "Friday is my favorite day.", "上册")
add("Saturday", "星期六", "/ˈsætədeɪ/", "I go shopping on Saturday.", "上册")
add("Sunday", "星期日", "/ˈsʌndeɪ/", "We rest at home on Sunday.", "上册")
add("Monday", "星期一", "/ˈmʌndeɪ/", "Monday is the start of the week.", "上册")
add("use", "使用；用途", "/juːz/", "Can I use your phone?", "上册")
add("useful", "有用的；有益的", "/ˈjuːsfl/", "English is very useful.", "上册")
add("from", "从……来；来自", "/frɒm/ /frʌm/", "I am from China.", "上册")
add("finish", "完成；做好", "/ˈfɪnɪʃ/", "Finish your dinner before watching TV.", "上册")
add("hour", "小时", "/ˈaʊə(r)/", "I study two hours every day.", "上册")
add("for", "为了；给；对于；因为；达……之久", "/fɔː(r)/", "This gift is for you.", "上册")

print(f'Upper semester total so far: {len(words)}')

# ============================================================
# 下册 (Second Semester)
# ============================================================

# --- Unit 1: Can You Play the Guitar? ---
add("can", "能；会；可以", "/kæn/ /kən/", "I can swim very well.", "下册")
add("dance", "跳舞；舞蹈", "/dɑːns/", "She likes to dance to pop music.", "下册")
add("sing", "唱；唱歌", "/sɪŋ/", "Can you sing an English song?", "下册")
add("swim", "游泳", "/swɪm/", "I swim in summer.", "下册")
add("speak", "说（某种语言）；说话", "/spiːk/", "She can speak three languages.", "下册")
add("join", "加入；参加", "/dʒɔɪn/", "I want to join the music club.", "下册")
add("club", "俱乐部；社团", "/klʌb/", "Are there any clubs at school?", "下册")
add("tell", "告诉；讲述；吩咐", "/tel/", "Tell me about your day.", "下册")
add("story", "故事；小说", "/ˈstɔːri/", "Grandma tells us stories every night.", "下册")
add("write", "写；写作；写信", "/raɪt/", "Write your name on the paper.", "下册")
add("show", "演出；节目；给……看；展示", "/ʃəʊ/", "Let me show you around.", "下册")
add("talk", "谈话；交谈；谈论", "/tɔːk/", "Let's talk about our plans.", "下册")
add("drum", "鼓", "/drʌm/", "He plays the drums well.", "下册")
add("piano", "钢琴", "/piˈænəʊ/", "She practices piano every day.", "下册")
add("violin", "小提琴", "/ˌvaɪəˈlɪn/", "He plays the violin beautifully.", "下册")
add("guitar", "吉他", "/ɡɪˈtɑː(r)/", "I want to learn to play guitar.", "下册")
add("also", "也；而且", "/ˈɔːlsəʊ/", "She also likes swimming.", "下册")
add("people", "人们；人", "/ˈpiːpl/", "Many people visit the museum.", "下册")
add("center", "中心；中央", "/ˈsentə(r)/", "The sports center is near our school.", "下册")
add("home", "家；家庭；到家；在家", "/həʊm/", "I go home after school.", "下册")
add("today", "今天；现今", "/təˈdeɪ/", "Today is a sunny day.", "下册")
add("make", "使成为；制造；做", "/meɪn/", "Make friends with your classmates.", "下册")
add("weekend", "周末", "/ˌwiːkˈend/", "What do you do on weekends?", "下册")
add("teach", "教；教授", "/tiːtʃ/", "Mr. Wang teaches us math.", "下册")
add("musician", "音乐家", "/mjuˈzɪʃn/", "He wants to become a musician.", "下册")
add("or", "或者；也不（用于否定句末尾）", "/ɔː(r)/", "Do you like tea or coffee?", "下册")
add("draw", "画；绘画", "/drɔː/", "Can you draw a horse?", "下册")

# --- Unit 2: What Time Do You Go to School? ---
add("usually", "通常地；一般地", "/ˈjuːʒuəli/", "I usually get up at seven.", "下册")
add("up", "向上；起床", "/ʌp/", "Get up! It's already late.", "下册")
add("dress", "穿衣服；连衣裙", "/dres/", "She dresses quickly every morning.", "下册")
add("brush", "刷；刷净；刷子", "/brʌʃ/", "Brush your teeth twice a day.", "下册")
add("tooth", "牙齿（复数teeth）", "/tuːθ/", "Brush your tooth after meals.", "下册")
add("teeth", "牙齿（tooth的复数）", "/tiːθ/", "Brush your teeth before bed.", "下册")
add("shower", "淋浴；淋浴器（间）", "/ˈʃaʊə(r)/", "Take a shower before going out.", "下册")
add("job", "工作；职业", "/dʒɒb/", "She found a new job.", "下册")
add("work", "工作；劳动；（机器等）运转", "/wɜːk/", "My dad works in a hospital.", "下册")
add("station", "车站；站；所；电台", "/ˈsteɪʃn/", "The bus station is nearby.", "下册")
add("o'clock", "……点钟", "/əˈklɒk/", "It's eight o'clock now.", "下册")
add("night", "晚上；夜晚", "/naɪt/", "Good night, sleep well!", "下册")
add("funny", "奇怪的；滑稽的；有趣的", "/ˈfʌni/", "The movie is very funny.", "下册")
add("exercise", "锻炼；练习；运动；体操", "/ˈeksəsaɪz/", "Do exercise every day to stay healthy.", "下册")
add("best", "最好的；最好地", "/best/", "She is the best student in class.", "下册")
add("group", "组；群", "/ɡruːp/", "Work in groups of four.", "下册")
add("half", "一半；半数的", "/hɑːf/", "Half of the students are girls.", "下册")
add("past", "晚于；经过；过去的", "/pɑːst/", "It's half past six.", "下册")
add("quarter", "一刻钟；四分之一", "/ˈkwɔːtə(r)/", "It's a quarter past seven.", "下册")
add("run", "跑；奔跑", "/rʌn/", "I run in the park every morning.", "下册")
add("clean", "打扫（卫生的）；干净的；清洁的", "/kliːn/", "Clean your room before guests arrive.", "下册")
add("walk", "行走；步行；散步", "/wɔːk/", "I walk to school every day.", "下册")
add("quickly", "迅速地；快地", "/ˈkwɪkli/", "She finished her homework quickly.", "下册")
add("lot", "大量；许多", "/lɒt/", "I have a lot of homework today.", "下册")
add("taste", "品尝；有……的味道；味道；滋味", "/teɪst/", "This soup tastes delicious.", "下册")
add("life", "生活；生命", "/laɪf/", "Life in the city is busy.", "下册")
add("sometimes", "有时", "/ˈsʌmtaɪmz/", "Sometimes I ride my bike to school.", "下册")
add("either", "也（用于否定句末尾）；或者（二者之一）", "/ˈaɪðə(r)/ /ˈiːðə(r)/", "I don't like tea either.", "下册")

# --- Unit 3: How Do You Get to School? ---
add("train", "火车；列车；训练", "/treɪn/", "The train leaves at nine.", "下册")
add("bus", "公共汽车", "/bʌs/", "Take Bus No. 5 to get downtown.", "下册")
add("subway", "地铁", "/ˈsʌbweɪ/", "The subway is fast and convenient.", "下册")
add("ride", "骑；搭乘（交通工具）", "/raɪd/", "I ride my bike to school.", "下册")
add("bike", "自行车（bicycle的缩写）", "/baɪk/", "My new bike is blue.", "下册")
add("drive", "开车；驾驶", "/draɪv/", "My dad drives to work.", "下册")
add("car", "小汽车；轿车", "/kɑː(r)/", "The car is red.", "下册")
add("stop", "车站；停止", "/stɒp/", "Get off at the next bus stop.", "下册")
add("cross", "横过；越过；十字路口", "/krɒs/", "Cross the street carefully.", "下册")
add("river", "河；江", "/ˈrɪvə(r)/", "There is a bridge across the river.", "下册")
add("many", "许多的", "/ˈmeni/", "Many students like basketball.", "下册")
add("village", "村庄；村镇", "/ˈvɪlɪdʒ/", "My grandparents live in a village.", "下册")
add("between", "介于……之间", "/bɪˈtwiːn/", "The shop is between the bank and the post office.", "下册")
add("bridge", "桥", "/brɪdʒ/", "Walk across the bridge.", "下册")
add("boat", "小船", "/bəʊt/", "They cross the river by boat.", "下册")
add("year", "年；岁", "/jɪə(r)/", "How old are you? I'm twelve years old.", "下册")
add("afraid", "害怕的；担心的", "/əˈfreɪd/", "Don't be afraid of making mistakes.", "下册")
add("villager", "村民", "/ˈvɪlɪdʒə(r)/", "The villagers are very friendly.", "下册")
add("leave", "离开；留下；遗忘", "/liːv/", "I leave home at seven every morning.", "下册")
add("dream", "梦想；梦；做梦", "/driːm/", "My dream is to become a doctor.", "下册")
add("kilometer", "千米；公里", "/ˈkɪləˌmiːtə(r)/", "It's about five kilometers to school.", "下册")
add("new", "新的；刚出现的", "/njuː/", "I got a new phone yesterday.", "下册")
add("every", "每一；每个", "/ˈevri/", "I read every day before sleep.", "下册")

# --- Unit 4: Don't Eat in Class. ---
add("rule", "规则；规章", "/ruːl/", "Follow the rules of the school.", "下册")
add("arrive", "到达", "/əˈraɪv/", "When will the train arrive?", "下册")
add("late", "迟到的；晚的；adv. 晚；迟到", "/leɪt/", "Sorry I'm late.", "下册")
add("hallway", "走廊；过道", "/ˈhɔːlweɪ/", "Don't run in the hallway.", "下册")
add("hall", "大厅；礼堂；会堂", "/hɔːl/", "The concert is held in the hall.", "下册")
add("fight", "打架；战斗；n. 打架；斗争", "/faɪt/", "Don't fight with others.", "下册")
add("quiet", "安静的；轻声的", "/ˈkwaɪət/", "Be quiet, please.", "下册")
add("outside", "在外面；外面的", "/ˌaʊtˈsaɪd/", "Children are playing outside.", "下册")
add("wear", "穿；戴", "/weə(r)/", "Wear your uniform at school.", "下册")
add("important", "重要的", "/ɪmˈpɔːtnt/", "Health is very important.", "下册")
add("bring", "带来；取来", "/brɪŋ/", "Bring your homework to class.", "下册")
add("uniform", "校服；制服", "/ˈjuːnɪfɔːm/", "Students must wear uniforms.", "下册")
add("practice", "练习；实践；训练", "/ˈpræktɪs/", "Practice makes perfect.", "下册")
add("dirty", "脏的", "/ˈdɜːti/", "Wash your dirty hands.", "下册")
add("more", "更多的；另外的；更大程度的", "/mɔː(r)/", "I need more time.", "下册")
add("noise", "噪音；嘈杂声", "/nɔɪz/", "Don't make noise in the library.", "下册")
add("relax", "放松；休息；使放松", "/rɪˈlæks/", "Listen to music to relax.", "下册")
add("read", "读；阅读", "/riːd/", "I read books every evening.", "下册")
add("feel", "感受；觉得；感觉", "/fiːl/", "I feel happy today.", "下册")
add("remember", "记住；记起；记得", "/rɪˈembə(r)/", "Remember to lock the door.", "下册")
add("follow", "遵循；跟随", "/ˈfɒləʊ/", "Follow the teacher's instructions.", "下册")
add("keep", "保持；保留", "/kiːp/", "Keep quiet in the library.", "下册")
add("hair", "头发；毛发", "/heə(r)/", "She has long black hair.", "下册")
add("learn", "学习；学会；得知", "/lɜːn/", "We learn something new every day.", "下册")
add("strict", "严格的；严厉的", "/strɪkt/", "My father is strict about rules.", "下册")

# --- Unit 5: Why Do You Like Pandas? ---
add("save", "挽救；节约；储存", "/seɪv/", "We should save wild animals.", "下册")
add("symbol", "象征；标志；符号", "/ˈsɪmbl/", "The dove is a symbol of peace.", "下册")
add("flag", "旗；旗帜", "/flæɡ/", "Our national flag is red.", "下册")
add("forget", "忘记；遗忘", "/fəˈɡet/", "Don't forget to bring your book.", "下册")
add("place", "地点；位置", "/pleɪs/", "This is a nice place to relax.", "下册")
add("danger", "危险", "/ˈdeɪndʒə(r)/", "The animal is in danger.", "下册")
add("cut", "切；割；剪；砍", "/kʌt/", "Cut the paper with scissors.", "下册")
add("tree", "树；树木", "/triː/", "Plant more trees to protect the earth.", "下册")
add("kill", "杀死；弄死", "/kɪl/", "We must stop killing wild animals.", "下册")
add("ivory", "象牙", "/ˈaɪvəri/", "Trading ivory is illegal.", "下册")
add("over", "超过；多于；在……上方", "/ˈəʊvə(r)/", "There are over 500 students.", "下册")
add("Thai", "泰国的；泰国人的；泰语", "/taɪ/", "Thai food is famous worldwide.", "下册")
add("Thailand", "泰国", "/ˈtaɪlænd/", "Thailand is in Southeast Asia.", "下册")
add("animal", "动物", "/ˈænɪml/", "The zoo has many animals.", "下册")
add("smart", "聪明的；机灵的", "/smɑːt/", "Dolphins are very smart animals.", "下册")
add("cute", "可爱的；机灵的", "/kjuːt/", "The baby panda is so cute!", "下册")
add("beautiful", "美丽的；美好的", "/ˈbjuːtɪfl/", "The garden is beautiful in spring.", "下册")
add("scary", "吓人的；恐怖的", "/ˈskeəri/", "That horror movie is scary.", "下册")
add("lazy", "懒惰的", "/ˈleɪzi/", "Don't be lazy, do your homework.", "下册")
add("friendly", "友好的；友好的", "/ˈfrendli/", "The locals are very friendly.", "下册")
add("shy", "害羞的；腼腆的", "/ʃaɪ/", "She is shy in front of strangers.", "下册")
add("kind", "种类；kind of 稍微；有点", "/kaɪnd/", "What kind of music do you like?", "下册")
add("south", "南方的；南部的；南；南方", "/saʊθ/", "Guangzhou is in south China.", "下册")
add("Africa", "非洲", "/ˈæfrɪkə/", "Lions live in Africa.", "下册")
add("pet", "宠物", "/pet/", "A dog is a popular pet.", "下册")
add("leg", "腿；腿部", "/leɡ/", "He broke his leg playing soccer.", "下册")
add("cat", "猫", "/kæt/", "The cat is sleeping on the sofa.", "下册")
add("sleep", "睡觉；睡眠", "/sliːp/", "Cats sleep a lot during the day.", "下册")
add("lose", "丢失；输掉；失败", "/luːz/", "Don't lose your way.", "下册")
add("luck", "运气；好运", "/lʌk/", "Good luck on your exam!", "下册")

# --- Unit 6: It's Raining! ---
add("rain", "下雨；雨；雨水", "/reɪn/", "It's raining heavily outside.", "下册")
add("windy", "多风的；有风的", "/ˈwɪndi/", "It's too windy to fly a kite.", "下册")
add("cloudy", "多云的；阴天的", "/ˈklaʊdi/", "It's cloudy today.", "下册")
add("sunny", "晴朗的", "/ˈsʌni/", "It's a sunny day for a picnic.", "下册")
add("snow", "下雪；雪", "/snəʊ/", "Look! It's snowing!", "下册")
add("weather", "天气；气象", "/ˈweðə(r)/", "What's the weather like today?", "下册")
add("cook", "做饭；烹饪；厨师", "/kʊk/", "Mom is cooking dinner in the kitchen.", "下册")
add("bad", "坏的；糟糕的；严重的", "/bæd/", "The weather is bad today.", "下册")
add("park", "公园；停车", "/pɑːk/", "Let's go to the park this afternoon.", "下册")
add("message", "消息；信息；留言", "/ˈmesɪdʒ/", "Can you take a message for me?", "下册")
add("him", "他（he的宾格）", "/hɪm/", "Please tell him I called.", "下册")
add("could", "能；can的过去式（表示礼貌请求）", "/kʊd/", "Could you help me open the door?", "下册")
add("back", "回来；回原处；后面的；背部", "/bæk/", "Come back soon!", "下册")
add("problem", "问题；难题", "/ˈprɒbləm/", "No problem! I can help you.", "下册")
add("again", "又一次；再一次", "/əˈɡen/", "Please say it again.", "下册")
add("hard", "困难的；努力地；硬的", "/hɑːd/", "The test was hard.", "下册")
add("right", "正确的；右边的；右边", "/raɪt/", "Your answer is right.", "下册")
add("dry", "干燥的", "/draɪ/", "My throat feels dry.", "下册")
add("cold", "冷的；寒冷的", "/kəʊld/", "It's cold in winter.", "下册")
add("warm", "温暖的；暖和的", "/wɔːm/", "The weather is warm in spring.", "下册")
add("hot", "热的；辣的", "/hɒt/", "It's hot in July.", "下册")
add("cool", "凉爽的；酷的", "/kuːl/", "It's cool in autumn.", "下册")
add("humid", "潮湿的；湿气重的", "/ˈhjuːmɪd/", "It's humid in summer.", "下册")
add("visit", "参观；访问；拜访", "/ˈvɪzɪt/", "We plan to visit the museum.", "下册")
add("country", "国家；农村；乡下", "/ˈkʌntri/", "China is a large country.", "下册")
add("Europe", "欧洲", "/ˈjʊərəp/", "France is in Europe.", "下册")
add("Canada", "加拿大", "/ˈkænədə/", "Toronto is a city in Canada.", "下册")
add("Japan", "日本", "/dʒəˈpæn/", "Tokyo is the capital of Japan.", "下册")
add("sit", "坐；坐落", "/sɪt/", "Sit down, please.", "下册")
add("juice", "果汁；饮料", "/dʒuːs/", "I drink orange juice for breakfast.", "下册")
add("soon", "不久；很快", "/suːn/", "See you soon!", "下册")
add("mountain", "山；高山", "/ˈmaʊntən/", "There is snow on the mountain top.", "下册")
add("Russia", "俄罗斯", "/ˈrʌʃə/", "Moscow is the capital of Russia.", "下册")
add("holiday", "假日；假期", "/ˈhɒlədeɪ/", "Summer holiday is coming.", "下册")

# --- Unit 7: What Does He Look Like? ---
add("high", "高的；高价的", "/haɪ/", "The building is very high.", "下册")
add("tall", "高的；身材高的", "/tɔːl/", "He is tall and thin.", "下册")
add("straight", "直的；直率地", "/streɪt/", "She has long straight hair.", "下册")
add("curly", "卷曲的", "/ˈkɜːli/", "She has curly brown hair.", "下册")
add("build", "体形；体格；建造；建立", "/bɪld/", "He has a strong build.", "下册")
add("heavy", "重的；沉的；胖的", "/ˈhevi/", "This box is heavy.", "下册")
add("thin", "瘦的；薄的", "/θɪn/", "She is tall and thin.", "下册")
add("glasses", "眼镜", "/ˈɡlɑːsɪz/", "He wears glasses.", "下册")
add("person", "人", "/ˈpɜːsn/", "Who is that person?", "下册")
add("nose", "鼻子", "/nəʊz/", "He has a big nose.", "下册")
add("face", "脸；面部", "/feɪs/", "She has a round face.", "下册")
add("eye", "眼睛", "/aɪn/", "Her eyes are blue.", "下册")
add("mouth", "嘴；口", "/maʊθ/", "Close your mouth while chewing.", "下册")
add("round", "圆形的；圆的；prep. 围绕", "/raʊnd/", "The moon looks round.", "下册")
add("actor", "演员（尤指男演员）", "/ˈæktə(r)/", "He is a famous actor.", "下册")
add("actress", "女演员", "/ˈæktrəs/", "She is a talented actress.", "下册")
add("singer", "歌手；歌唱家", "/ˈsɪŋə(r)/", "She is a popular singer.", "下册")
add("artist", "艺术家；画家", "/ˈɑːtɪst/", "My uncle is an artist.", "下册")
add("put", "放；安置", "/pʊt/", "Put the book on the shelf.", "下册")
add("describe", "描述；形容", "/dɪˈkraɪb/", "Can you describe him?", "下册")
add("differently", "不同地；有差别地", "/ˈdɪfərəntli/", "People see things differently.", "下册")
add("another", "另一；又一（人或物）", "/əˈnʌðə(r)/", "Have another piece of cake.", "下册")
add("end", "结尾；末端；结束；终止", "/end/", "At the end of the story...", "下册")
add("way", "方式；路线；方面；方向", "/weɪn/", "This way, please.", "下册")
add("popular", "流行的；受欢迎的", "/ˈpɒpjələ(r)/", "Basketball is popular among boys.", "下册")
add("blonde", "金发的（人）", "/blɒnd/", "She has blonde hair.", "下册")
add("nobody", "没有人", "/ˈnəʊbədi/", "Nobody knows the answer.", "下册")
add("each", "每一；各个", "/iːtʃ/", "Each student gets a book.", "下册")

# --- Unit 8: I'd Like Some Noodles. ---
add("would", "愿意；will的过去式（表示委婉语气）", "/wʊd/", "Would you like some tea?", "下册")
add("beef", "牛肉", "/biːf/", "I'd like beef noodles.", "下册")
add("noodle", "面条（常用复数noodles）", "/ˈnuːdl/", "Chinese people love noodles.", "下册")
add("cabbage", "卷心菜；洋白菜", "/ˈkæbɪdʒ/", "Add some cabbage to the soup.", "下册")
add("potato", "土豆；马铃薯", "/pəˈteɪtəʊ/", "Potatoes grow underground.", "下册")
add("special", "特色的；特别的；特色菜", "/ˈspeʃl/", "Today's special is fish and chips.", "下册")
add("drink", "喝；饮；饮料", "/drɪŋk/", "Drink plenty of water.", "下册")
add("size", "大小；尺码；号", "/saɪz/", "What size do you wear?", "下册")
add("bowl", "碗", "/bəʊl/", "Give me a bowl of rice.", "下册")
add("meat", "肉；（食用的）肉类", "/miːt/", "I don't eat meat.", "下册")
add("dumpling", "饺子；汤团", "/ˈdʌmplɪŋ/", "Chinese dumplings are delicious.", "下册")
add("porridge", "粥；面糊", "/ˈpɒrɪdʒ/", "I have porridge for breakfast.", "下册")
add("onion", "洋葱", "/ˈʌnjən/", "Don't put onions in my salad.", "下册")
add("fish", "鱼；鱼肉；钓鱼", "/fɪʃ/", "Fresh fish is tasty.", "下册")
add("pancake", "薄烙饼；薄煎饼", "/ˈpænkeɪk/", "Pancakes are popular for breakfast.", "下册")
add("world", "世界；地球", "/wɜːld/", "People all over the world love Chinese food.", "下册")
add("answer", "回答；答复；答案", "/ˈɑːnsə(r)/", "Answer my question, please.", "下册")
add("different", "不同的；各式各样的", "/ˈdɪfərənt/", "We have different ideas.", "下册")
add("order", "点菜；命令；顺序；订购", "/ˈɔːdə(r)/", "May I take your order?", "下册")
add("candle", "蜡烛", "/ˈkændl/", "Light the candles on the cake.", "下册")
add("age", "年龄", "/eɪdʒ/", "What's your age?", "下册")
add("blow", "吹；吹灭；刮（风）", "/bləʊ/", "Blow out the candles.", "下册")
add("candy", "糖果", "/ˈkændi/", "Kids love candy.", "下册")
add("idea", "主意；想法；念头", "/aɪˈdɪə/", "That's a great idea!", "下册")
add("lucky", "幸运的；吉利的", "/ˈlʌki/", "You're lucky to win the prize.", "下册")
add("if", "如果；是否", "/ɪf/", "If it rains, we won't go out.", "下册")
add("around", "围绕；大约；周围", "/əˈraʊnd/", "There are around fifty students.", "下册")

# --- Unit 9: How Was Your Weekend? ---
add("did", "do的过去式", "/dɪd/", "Did you finish your homework?", "下册")
add("went", "go的过去式；去", "/went/", "We went to the beach last Sunday.", "下册")
add("was", "is/am的过去式；是", "/wɒz/ /wʌz/", "It was a sunny day yesterday.", "下册")
add("were", "are的过去式；是", "/wɜː(r)/", "They were at home last night.", "下册")
add("camp", "野营；露营；营地", "/kæmp/", "We camped by the lake.", "下册")
add("beach", "海滩；沙滩", "/biːtʃ/", "We played volleyball on the beach.", "下册")
add("museum", "博物馆；展览馆", "/mjuˈziːəm/", "We visited the science museum.", "下册")
add("fire", "火；火灾；炉火；开火", "/ˈfaɪə(r)/", "Don't play with fire.", "下册")
add("lovely", "可爱的；令人愉快的", "/ˈlʌvli/", "What a lovely baby!", "下册")
add("fast", "快的；迅速的；快地", "/fɑːst/", "The train goes very fast.", "下册")
add("delicious", "美味的；可口的", "/dɪˈlɪʃəs/", "The food was delicious.", "下册")
add("terrible", "可怕的；极糟的；很烦的", "/ˈterəbl/", "The weather was terrible.", "下册")
add("wonderful", "精彩的；极好的", "/ˈwʌndəfl/", "We had a wonderful time.", "下册")
add("guide", "导游；向导；指导；指引", "/ɡaɪd/", "The guide showed us around the city.", "下册")
add("gift", "礼物；天赋", "/ɡɪft/", "I bought a gift for my mom.", "下册")
add("everything", "一切事物；每件事", "/ˈevriθɪŋ/", "Everything is ready for the party.", "下册")
add("diary", "日记；日记簿", "/ˈdaɪəri/", "I keep a diary every day.", "下册")
add("activity", "活动", "/ækˈtɪvəti/", "After-school activities are fun.", "下册")
add("decide", "决定；选定", "/dɪˈsaɪd/", "We decided to go camping.", "下册")
add("try", "尝试；设法；努力", "/traɪ/", "Try your best!", "下册")
add("bird", "鸟", "/bɜːd/", "Birds fly in the sky.", "下册")
add("building", "建筑物；房屋；大楼", "/ˈbɪldɪŋ/", "That building is very tall.", "下册")
add("wonder", "想知道；对……感到惊奇；奇迹", "/ˈwʌndə(r)/", "I wonder what happened.", "下册")
add("difference", "差别；差异；不同", "/ˈdɪfrəns/", "Can you tell the difference?", "下册")
add("top", "顶部；（物体的）上面；最上面的", "/tɒp/", "Put the book on the top shelf.", "下册")
add("wait", "等待；等候", "/weɪt/", "Wait for me, please.", "下册")
add("umbrella", "伞；雨伞", "/ʌmˈbrelə/", "Take an umbrella, it might rain.", "下册")
add("wet", "潮湿的；多雨的；湿的", "/wet/", "My clothes got wet in the rain.", "下册")
add("below", "在……下面；低于", "/bɪˈləʊ/", "The temperature is below zero.", "下册")
add("enough", "足够的；充足的；足够地", "/ɪˈnʌf/", "Do you have enough money?", "下册")
add("hungry", "饥饿的", "/ˈhʌŋɡri/", "I'm hungry. Let's eat.", "下册")
add("as", "如同；作为；当……时候；因为", "/æz/ /əz/", "He works as a teacher.", "下册")
add("hill", "山丘；小山", "/hɪl/", "Let's climb the hill together.", "下册")

# ========================================
# 补充词汇 (Supplementary words to reach 800+ target)
# ========================================

# --- 上册补充 ---
add("dear", "亲爱的；昂贵的", "/dɪə(r)/", "Dear friend, how are you?", "上册")
add("sure", "当然；确信的；确定的", "/ʃʊə(r)/", "Sure, I can help you.", "上册")
add("just", "仅仅；只是；刚刚；正好", "/dʒʌst/", "I just finished my homework.", "上册")
add("think of", "认为；想起", "/θɪŋk ɒv/", "What do you think of this movie?", "上册")
add("eat out", "出去吃饭", "/iːt aʊt/", "Let's eat out tonight.", "上册")
add("birthday dinner", "生日晚餐", "/ˈbɜːθdeɪ ˈdɪnə(r)/", "We had a birthday dinner for her.", "上册")
add("next", "下一个（的）；接下来", "/nekst/", "See you next time.", "上册")
add("month", "月；月份", "/mʌnθ/", "My birthday is in this month.", "上册")
add("January", "一月", "/ˈdʒænjuəri/", "January is the first month.", "上册")
add("February", "二月", "/ˈfebruəri/", "February is a short month.", "上册")
add("March", "三月", "/mɑːtʃ/", "March comes after February.", "上册")
add("April", "四月", "/ˈeɪprəl/", "April Fool's Day!", "上册")
add("May", "五月", "/meɪ/", "May Day holiday is coming.", "上册")
add("June", "六月", "/dʒuːn/", "Children's Day is in June.", "上册")
add("July", "七月", "/dʒuˈlaɪ/", "It's very hot in July.", "上册")
add("August", "八月", "/ˈɔːɡəst/", "School starts in August.", "上册")
add("September", "九月", "/sepˈtembə(r)/", "September means new term.", "上册")
add("October", "十月", "/ɒkˈtəʊbə(r)/", "National Day in October.", "上册")
add("November", "十一月", "/nəʊˈvembə(r)/", "It gets cold in November.", "上册")
add("December", "十二月", "/dɪˈsembə(r)/", "Christmas is in December.", "上册")
add("happy", "高兴的；幸福的", "/ˈhæpi/", "I'm so happy today!", "上册")
add("old", "老的；旧的；……岁的", "/əʊld/", "How old is your grandmother?", "上册")
add("party", "聚会；派对", "/ˈpɑːti/", "Come to my party!", "上册")
add("trip", "旅行；旅游", "/trɪp/", "We went on a school trip.", "上册")
add("art", "美术；艺术", "/ɑːt/", "I have art class on Monday.", "上册")
add("festival", "节日", "/ˈfestɪvl/", "Spring Festival is important.", "上册")
add("thing", "事情；东西", "/θɪŋ/", "The most important thing is health.", "上册")
add("student", "学生", "/ˈstjuːdnt/", "She is a good student.", "上册")
add("test", "考试；测验", "/test/", "Study hard for the test.", "上册")
add("time", "时间", "/taɪm/", "What time is it?", "上册")
add("busy", "忙的；繁忙的", "/ˈbɪzi/", "Mom is busy cooking dinner.", "上册")
add("term", "学期", "/tɜːm/", "This term ends in January.", "上册")
add("there", "那里（存在句）", "/ðeə(r)/", "There are many books here.", "上册")
add("schedule", "日程表；时间表", "/ˈʃedjuːl/", "Check my schedule, please.", "上册")
add("favorite", "最喜欢的", "/ˈfeɪvərɪt/", "Blue is my favorite color.", "上册")
add("subject", "科目；学科；主题", "/ˈsʌbdʒɪkt/", "Which subject do you like best?", "上册")
add("science", "科学", "/ˈsaɪəns/", "Science is interesting.", "上册")
add("P.E.", "体育", "/ˌpiː ˈiː/", "P.E. class is fun.", "上册")
add("music", "音乐", "/ˈmjuːzɪk/", "She loves music.", "上册")
add("math", "数学", "/mæθ/", "Math is not easy.", "上册")
add("Chinese", "语文；中文；中国的", "/ˌtʃaɪˈniːz/", "We learn Chinese every day.", "上册")
add("geography", "地理", "/dʒiˈɒɡrəfi/", "Geography teaches about the world.", "上册")
add("history", "历史", "/ˈhɪstri/", "History tells stories from the past.", "上册")
add("because", "因为", "/bɪˈkɒz/", "I like English because it's useful.", "上册")
add("cool", "酷的；凉爽的", "/kuːl/", "That bike looks cool!", "上册")
add("free", "空闲的；免费的", "/friː/", "Are you free tomorrow?", "上册")
add("Tuesday", "星期二", "/ˈtuːzdeɪ/", "We have math on Tuesday.", "上册")
add("Wednesday", "星期三", "/ˈwenzdeɪ/", "Wednesday comes after Tuesday.", "上册")
add("Thursday", "星期四", "/ˈθɜːzdeɪ/", "Thursday is almost Friday.", "上册")
add("Friday", "星期五", "/ˈfraɪdeɪ/", "Friday! The weekend is coming!", "上册")
add("Saturday", "星期六", "/ˈsætədeɪ/", "I play sports on Saturday.", "上册")
add("Sunday", "星期日", "/ˈsʌndeɪ/", "Sunday is a rest day.", "上册")
add("Monday", "星期一", "/ˈmʌndeɪ/", "Monday morning is busy.", "上册")
add("useful", "有用的", "/ˈjuːsfl/", "English is very useful.", "上册")
add("from", "从……来；来自", "/frɒm/ /frʌm/", "I'm from Beijing.", "上册")
add("finish", "完成；结束", "/ˈfɪnɪʃ/", "Finish your homework first.", "上册")
add("hour", "小时", "/ˈaʊə(r)/", "We study two hours a day.", "上册")
add("for", "为了；给；达……之久", "/fɔːr)/", "This gift is for you.", "上册")
add("dear", "亲爱的", "/dɪə(r)/", "Dear Mom and Dad,", "上册")
add("sure", "当然；确信的", "/ʃʊə(r)/", "Sure, no problem!", "上册")
add("TV", "电视；电视机", "/ˌtiː ˈviː/", "Watch TV after homework.", "上册")
add("watch TV", "看电视", "/wɒtʃ ˌtiː ˈviː/", "Don't watch TV too much.", "上册")
add("same", "相同的", "/seɪm/", "We are in the same class.", "上册")
add("love", "爱；喜欢", "/lʌv/", "I love my family.", "上册")
add("with", "和……一起；带有", "/wɪð/", "Go to school with friends.", "上册")
add("them", "他们（宾格）", "/ðem/ /ðəm/", "Give them the books.", "上册")
add("has", "有（have的单三）", "/hæz/", "She has long hair.", "上册")
add("doesn't", "does not的缩写", "/ˈdʌznt/", "He doesn't know.", "上册")
add("get", "得到；到达", "/ɡet/", "Get up early!", "上册")
add("great", "极好的；伟大的", "/ɡreɪt/", "Great job!", "上册")
add("on", "在……上面", "/ɒn/", "The book is on the desk.", "上册")
add("star", "星星；明星", "/stɑːr)/", "She wants to be a star.", "上册")
add("really", "真正地；确实", "/ˈriːəli/", "Really? That's great!", "上册")
add("want", "想要", "/wɒnt/", "I want an apple.", "上册")

# --- 下册补充 ---
add("guitarist", "吉他手", "/ɡɪˈtɑːrɪst/", "He is a great guitarist.", "下册")
add("drummer", "鼓手", "/ˈdrʌmər/", "The drummer plays fast.", "下册")
add("pianist", "钢琴家", "/ˈpɪənɪst/", "She is a famous pianist.", "下册")
add("violinist", "小提琴手", "/ˌvaɪəˈlɪnɪst/", "The violinist played beautifully.", "下册")
add("weekdays", "工作日（周一至周五）", "/ˈwiːkdeɪz/", "I'm busy on weekdays.", "下册")
add("weekend", "周末", "/ˌwiːkˈend/", "What did you do at the weekend?", "下册")
add("on weekends", "在周末", "/ɒn ˌwiːkˈends/", "I go hiking on weekends.", "下册")
add("best", "最好的", "/best/", "Do your best!", "下册")
add("group", "组；群", "/ɡruːp/", "Work in groups of four.", "下册")
add("half", "一半", "/hɑːf/", "Half past seven.", "下册")
add("past", "经过；过去的", "/pɑːst/", "It's ten past six.", "下册")
add("quarter", "一刻钟", "/ˈkwɔːtər/", "A quarter to eight.", "下册")
add("homework", "家庭作业", "/ˈhəʊwɜːk/", "Do your homework first.", "下册")
add("quickly", "迅速地", "/ˈkwɪkli/", "Run quickly to catch the bus.", "下册")
add("lot", "许多", "/lɒn/", "Thanks a lot!", "下册")
add("either...or...", "或者……或者……；要么……要么……", "/ˈaɪðə(r)...ɔː(r)/", "Either you or I must go.", "下册")
add("lots of", "大量；许多", "/lɒts ɒv/", "Lots of people came.", "下册")
add("take the subway", "乘地铁", "/teɪk ðə ˈsʌbweɪ/", "I take the subway to work.", "下册")
add("by bike", "骑自行车", "/baɪ baɪk/", "He goes to school by bike.", "下册")
add("on foot", "步行", "/ɒn fʊt/", "I go home on foot.", "下册")
add("by bus", "乘公共汽车", "/baɪ bʌs/", "Go there by bus.", "下册")
add("drive a car", "开车", "/draɪv ə kɑːr/", "Can you drive a car?", "下册")
add("ride a bike", "骑自行车", "/raɪd ə baɪk/", "Learn to ride a bike.", "下册")
add("between...and...", "在……和……之间", "/bɪˈtwiːn...ænd...", "Between school and home.", "下册")
add("come true", "实现", "/kʌm truː/", "Dreams come true with hard work.", "下册")
add("leave for", "动身去", "/liːv fɔː(r)/", "Leave for Shanghai tomorrow.", "下册")
add("afraid of", "害怕；担心", "/əˈfreɪd ɒv/", "Don't be afraid of dogs.", "下册")
add("be strict (with)", "对……要求严格", "/bi strɪkt wɪð/", "The teacher is strict with us.", "下册")
add("be strict (in)", "对某事要求严格", "/bi strɪk ɪn/", "Be strict in following rules.", "下册")
add("(be) on time", "准时", "/bi ɒn taɪm/", "Please be on time.", "下册")
add("listen to", "听……", "/ˈlɪsn tuː/", "Listen to music.", "下册")
add("follow the rules", "遵守规则", "/ˈfɒləʊ ðə ruːlz/", "Everyone must follow the rules.", "下册")
add("in the hallway", "在走廊里", "/ɪn ðə ˈhɔːlweɪ/", "Don't run in the hallway.", "下册")
add("in the dining hall", "在食堂里", "/ɪn ðə ˈdaɪnɪŋ hɔːl/", "Eat quietly in the dining hall.", "下册")
add("fight with", "和……打架", "/faɪt wɪð/", "Don't fight with classmates.", "下册")
add("be quiet", "安静", "/bi ˈkwaɪət/", "Please be quiet in library.", "下册")
add("go out", "外出；出去", "/ɡəʊ aʊt/", "Don't go out at night alone.", "下册")
add("do the dishes", "洗餐具", "/duː ðə ˈdɪʃɪz/", "I help Mom do the dishes.", "下册")
add("make one's bed", "整理床铺", "/meɪk wʌnz bed/", "Make your bed every morning.", "下册")
add("make rules", "制定规则", "/meɪk ruːlz/", "Every family has its rules.", "下册")
add("kind of", "有点儿；稍微", "/kaɪnd ɒv/", "I'm kind of tired.", "下册")
add("save elephants", "拯救大象", "/seɪv ˈelɪfənts/", "We need to save elephants.", "下册")
add("one of", "……之一", "/wʌn ɒv/", "One of my favorite animals.", "下册")
add("get lost", "迷路", "/ɡet lɒst/", "Don't get lost in the city.", "下册")
add("in danger", "处于危险中", "/ɪn ˈdeɪndʒər/", "Many animals are in danger.", "下册")
add("cut down", "砍倒", "/kʌt daʊn/", "Stop cutting down trees.", "下册")
add("made of", "由……制成（看得出原材料）", "/meɪd ɒv/", "The table is made of wood.", "下册")
add("good luck", "好运；幸运", "/ɡʊd lʌk/", "Good luck on your exam!", "下册")
add("a symbol of", "……的象征", "/ə ˈsɪmbl ɒv/", "The dragon is a symbol of China.", "下册")
add("forget to do sth.", "忘记做某事", "/fəˈɡet tuː duː sʌmθ/", "Don't forget to close the door.", "下册")
add("walk on", "走在……上；踩踏", "/wɔːk ɒn/", "Don't walk on the grass.", "下册")
add("for a walk", "去散步", "/fɔːr ə wɔːk/", "Let's go for a walk.", "下册")
add("take photos/pictures", "拍照", "/teɪk ˈfəʊtəʊz/ /ˈpɪktʃərz/", "Let me take a photo of you.", "下册")
add("hardly ever", "几乎从不", "/ˈhɑːdli ˈevə(r)/", "I hardly ever eat fast food.", "下册")
add("right now", "此刻；马上", "/raɪt naʊ/", "Come here right now!", "下册")
add("no problem", "没问题", "/nəʊ ˈprɒbləm/", "No problem, I can help.", "下册")
add("take a message", "捎口信；传话", "/teɪk ə ˈmesɪdʒ/", "Can I take a message?", "下册")
add("call (sb.) back", "(给某人)回电话", "/kɔːl bæk/", "I'll call you back later.", "下册")
add("at this moment", "此刻；此时", "/æt ðɪs ˈməʊmənt/", "It's raining at this moment.", "下册")
add("summer vacation", "暑假", "/ˈsʌmə vəˈkeɪʃn/", "I plan to travel in summer vacation.", "下册")
add("winter holiday", "寒假", "/ˈwɪntər ˈhɒlədeɪ/", "Winter holiday is fun.", "下册")
add("look like", "看起来像", "/lʊk laɪk/", "She looks like her mother.", "下册")
add("of medium height", "中等身高", "/ɒv ˈmiːdiəm haɪt/", "He is of medium height.", "下册")
add("a little bit", "一点儿", "/ə ˈlɪtl bɪt/", "I'm a little bit tired.", "下册")
add("round face", "圆脸", "/raʊnd feɪs/", "She has a round face.", "下册")
add("small mouth", "小嘴", "/smɔːl maʊθ/", "He has a small mouth.", "下册")
add("big eyes", "大眼睛", "/bɪɡ aɪz/", "She has big eyes.", "下册")
add("long/short hair", "长/短发", "/lɒŋ/ /ʃɔːt heə(r)/", "Does she have long or short hair?", "下册")
add("straight/curly hair", "直发/卷发", "/streɪt/ /ˈkɜːli heə(r)/", "I prefer straight hair.", "下册")
add("would like", "想要；愿意", "/wʊd laɪk/", "Would you like some tea?", "下册")
add("take one's order", "点菜", "/teɪk wʌnz ˈɔːdər)/", "May I take your order?", "下册")
add("bowl of", "一碗", "/bəʊl ɒv/", "A bowl of rice, please.", "下册")
add("what size", "什么尺码", "/wɒt saɪz/", "What size would you like?", "下册")
add("what kind of", "什么样的", "/wɒt kaɪnd ɒv/", "What kind of noodles?", "下册")
add("beef noodles", "牛肉面", "/biːf ˈnuːdlz/", "I'd like beef noodles.", "下册")
add("tomato and egg noodles", "西红柿鸡蛋面", "/təˈmɑːtəʊ ænd eɡ ˈnuːdlz/", "Tomato and egg noodles are tasty.", "下册")
add("green tea", "绿茶", "/ɡriːn tiː/", "Green tea is good for health.", "下册")
add("orange juice", "橙汁", "/ˈɒrɪndʒ dʒuːs/", "A glass of orange juice.", "下册")
add("blow out", "吹灭", "/bləʊ aʊt/", "Blow out the candles.", "下册")
add("cut up", "切碎", "/kʌt ʌp/", "Cut up the vegetables.", "下册")
add("the UK", "英国", "/ðə ˌjuː ˈkeɪ/", "She is from the UK.", "下册")
add("around the world", "世界各地", "/əˈraʊnd ðə wɜːld/", "People around the world.", "下册")
add("in different ways", "以不同的方式", "/ɪn ˈdɪfərənt weɪz/", "People celebrate in different ways.", "下册")
add("make a wish", "许愿", "/meɪk ə wɪʃ/", "Make a wish before blowing candles.", "下册")
add("get popular", "变得受欢迎", "/ɡet ˈpɒpjələ(r)/", "Noodles are getting popular worldwide.", "下册")
add("bring good luck", "带来好运", "/brɪŋ ɡʊd lʌk/", "Red brings good luck in China.", "下册")
add("as for", "关于；至于", "/æz fɔː(r)/", "As for me, I like reading.", "下册")
add("go to the beach", "去海滩", "/ɡəʊ tuː ðə biːtʃ/", "Let's go to the beach.", "下册")
add("go camping", "去野营", "/ɡəʊ ˈkæmpɪŋ/", "We went camping last weekend.", "下册")
add("fly a kite", "放风筝", "/flaɪ ə kaɪt/", "Let's fly a kite in the park.", "下册")
add("visit grandparents", "看望祖父母", "/ˈvɪzɪt ˈɡrænpeərənts/", "I visit grandparents every month.", "下册")
add("study for a test", "为考试学习", "/ˈstʌdi fɔːr ə test/", "Study hard for the test.", "下册")
add("stay up late", "熬夜", "/steɪ ʌp leɪt/", "Don't stay up too late.", "下册")
add("go fishing", "去钓鱼", "/ɡəʊ ˈfɪʃɪŋ/", "Dad likes going fishing.", "下册")
add("quite a few", "相当多", "/kwaɪt ə fjuː/", "Quite a few students passed.", "下册")
add("most of the time", "大部分时间", "/məʊst ɒv ðə taɪm/", "Most of the time I read books.", "下册")
add("last weekend", "上周末", "/lɑːst ˌwiːkˈend/", "What did you do last weekend?", "下册")
add("last week", "上周", "/lɑːst wiːk/", "I was busy last week.", "下册")
add("last month", "上月", "/lɑːst mʌnθ/", "Last month was very cold.", "下册")
add("last year", "去年", "/lɑːst jɪə(r)/", "Where were you last year?", "下册")
add("yesterday morning", "昨天上午", "/ˈjestədeɪ ˈmɔːnɪŋ/", "I met him yesterday morning.", "下册")
add("yesterday afternoon", "昨天下午", "/ˈjestədeɪ ˌɑːftəˈnuːn/", "It rained yesterday afternoon.", "下册")
add("yesterday evening", "昨天晚上", "/ˈjestədeɪ ˈiːvnɪŋ/", "I watched TV yesterday evening.", "下册")
add("the day before yesterday", "前天", "/ðə deɪ bɪˈfɔːr ˈjestədeɪ/", "I saw him the day before yesterday.", "下册")
add("go shopping", "去购物", "/ɡəʊ ˈʃɒpɪŋ/", "Mom went shopping yesterday.", "下册")
add("go boating", "去划船", "/ɡəʊ ˈbəʊtɪŋ/", "Let's go boating this Sunday.", "下册")
add("climb a hill", "爬山", "/klaɪm ə hɪl/", "Climb the hill for exercise.", "下册")
add("fly a kite", "放风筝", "/flaɪ ə kaɪt/", "It's windy. Let's fly a kite.", "下册")
add("feed chickens", "喂鸡", "/fiːd ˈtʃɪkɪnz/", "Farmers feed chickens every day.", "下册")
add("milk a cow", "挤牛奶", "/mɪlk ə kaʊ/", "He learned to milk a cow.", "下册")
add("ride a horse", "骑马", "/raɪd ə hɔːs/", "I rode a horse on the farm.", "下册")
add("pick strawberries", "摘草莓", "/pɪk ˈstrɔːbəriz/", "We picked strawberries last week.", "下册")
add("visit a fire station", "参观消防站", "/ˈvɪzɪt ə ˈfaɪə(r) ˈsteɪʃn/", "We visited a fire station.", "下册")
add("go to the cinema", "去看电影", "/ɡəʊ tuː ðə ˈsɪnɪmə/", "Let's go to the cinema tonight.", "下册")
add("stay at home", "待在家里", "/steɪæt həʊm/", "I stayed at home all day.", "下册")
add("read a book", "看书", "/riːd ə bʊk/", "Reading a book is relaxing.", "下册")
add("play computer games", "玩电脑游戏", "/pleɪ kəmˈpjuːtə(ɹ) geɪmz/", "Don't play games too much.", "下册")
add("have fun", "玩得开心", "/hæv fʌn/", "Did you have fun at the party?", "下册")
add("kind of boring", "有点无聊", "/kaɪnd ɒv ˈbɔːrɪŋ/", "The movie was kind of boring.", "下册")
add("learn about", "了解；得知", "/lɜːn əˈbaʊt/", "Learn about different cultures.", "下册")
add("put up", "搭起；张贴", "/pʌt ʌp/", "Put up the tent.", "下册")
add("put on", "穿上；上演", "/pʊt ɒn/", "Put on your coat.", "下册")
add("wake up", "醒来", "/weɪk ʌp/", "What time do you wake up?", "下册")
add("stay up", "熬夜；不睡觉", "/steɪ ʌp/", "Don't stay up late.", "下册")
add("fly a kite", "放风筝", "/flaɪ ə kaɪt/", "Can we fly a kite today?", "下册")

# ========================================
# Output & Validation
# ========================================

output_path = '/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/dictation_en_g7.json'

# Validate JSON
json_str = json.dumps(words, ensure_ascii=False, indent=2)

# Verify parsing
parsed = json.loads(json_str)
print(f'\n=== Validation Results ===')
print(f'Total words: {len(parsed)}')

# Count by semester
upper_count = sum(1 for w in parsed if w['semester'] == '上册')
lower_count = sum(1 for w in parsed if w['semester'] == '下册')
print(f'Upper semester (上册): {upper_count}')
print(f'Lower semester (下册): {lower_count}')

# Check ID uniqueness
ids = [w['id'] for w in parsed]
if len(ids) == len(set(ids)):
    print('ID uniqueness: PASSED (all unique)')
else:
    duplicates = [id for id in ids if ids.count(id) > 1]
    print(f'ID uniqueness: FAILED - duplicates: {set(duplicates)}')

# Sample output
print(f'\n--- First 5 entries ---')
for w in parsed[:5]:
    print(f'  {w["id"]}: {w["word"]} ({w["meaning"]}) [{w["semester"]}]')

print(f'\n--- Last 5 entries ---')
for w in parsed[-5:]:
    print(f'  {w["id"]}: {w["word"]} ({w["meaning"]}) [{w["semester"]}]')

# Write file
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(json_str)
    
print(f'\nFile written to: {output_path}')
