# -*- coding: utf-8 -*-
"""Part 1: Tier 1 Verbs (250)"""
V="verb"; N="noun"; A="adjective"; Adv="adverb"; Prep="preposition"; Conj="conjunction"; Pron="pronoun"

verb_data = [
("advice","建议；忠告",N,1,"high",["suggest","opinion","recommend","idea"],["advise","advantage"],"Can you give me some advice?","advise动词→advice名词"),
("agree","同意；赞成",V,1,"high",["disagree","accept","approve","nod"],["argue","allow"],"I agree with you on this matter.","a+gree(高兴)→同意"),
("allow","允许；准许",V,1,"high",["permit","forbid","let","approve"],["alone","almost"],"My parents dont allow me to play games.","al+low→允许"),
("appear","出现；似乎",V,1,"high",["disappear","seem","show","emerge"],["appeal","apply"],"A rainbow appeared in the sky.","ap+pear(看见)→出现"),
("argue","争论；争辩",V,1,"high",["discuss","fight","debate","agree"],["agree","anger"],"They argued about the plan.","arg(火)+ue→争论"),
("arrive","到达；抵达",V,1,"high",["reach","get to","leave","depart"],["around","alive"],"We arrived at the airport early.","ar+rive→到达"),
("beat","打败；敲打",V,1,"high",["win","defeat","hit","heart"],["eat","heat","meat"],"Our team beat theirs.","beat→打败"),
("become","变成；成为",V,1,"high",["turn into","grow","change","develop"],["because","before"],"She wants to become a doctor.","be+come→成为"),
("begin","开始",V,1,"high",["start","commence","end","finish"],["began","begun"],"Lets begin our class.","be+gin(进)→开始"),
("believe","相信；认为",V,1,"high",["trust","doubt","faith","think"],["belief","belong"],"I believe you can do it.","be+lieve(爱)→相信"),
("belong","属于",V,1,"high",["own","member","group"],["believe","below"],"This book belongs to the library.","be+long(长久)→属于"),
("borrow","借入",V,1,"high",["lend","keep","return"],["sorrow","tomorrow"],"Can I borrow your pen?","borrow→借入"),
("break","打破；休息",V,1,"high",["fix","repair","rest","broken"],["brake","bread"],"Be careful not to break the cup.","break→打破"),
("bring","带来；拿来",V,1,"high",["take","fetch","carry","send"],["brink","boring"],"Please bring your textbook.","bring→带来"),
("build","建造；建设",V,1,"high",["construct","create","house","make"],["built","building"],"They are building a new school.","build→建造"),
("burn","燃烧；烧伤",V,1,"medium",["fire","hot","flame","heat"],["born","turn"],"The pan is burning.","burn→燃烧"),
("buy","买；购买",V,1,"high",["sell","shop","pay","cheap"],["by","bye"],"I want to buy a new phone.","buy→买"),
("call","叫；打电话",V,1,"high",["phone","ring","name","shout"],["calm","fall","tall"],"Please call me when you get home.","call→叫；打电话"),
("carry","携带；搬运",V,1,"high",["bring","take","lift","hold"],["candy","hurry"],"Can you help me carry these bags?","carry→携带"),
("catch","抓住；赶上",V,1,"high",["grab","miss","hold","throw"],["watch","match"],"Hurry up, or you will miss the bus.","catch→抓住"),
("cause","导致",V,1,"high",["reason","result","because","effect"],["because","course"],"What caused the accident?","cause→导致"),
("change","改变；变化",V,1,"high",["different","alter","modify","same"],["chance","charge"],"The weather can change quickly.","change→改变"),
("check","检查；核对",V,1,"high",["examine","test","verify","confirm"],["chick","cheek"],"Please check your answers.","check→检查"),
("choose","选择",V,1,"high",["pick","select","decide","choice"],["choice","chose"],"You can choose any color.","choose→选择"),
("climb","攀登；爬",V,1,"medium",["mountain","tree","hike","top"],["climate","claim"],"They climbed the mountain.","climb→攀登"),
("close","关闭",V,1,"high",["open","shut","near"],["cloth","cloud"],"Please close the window.","close→关闭"),
("collect","收集；聚集",V,1,"high",["gather","pick","save","collection"],["connect","correct"],"He likes collecting stamps.","col+lect(选择)→收集"),
("come","来；来到",V,1,"high",["go","arrive","return","here"],["some","become"],"Come here, please.","come→来"),
("compare","比较；对比",V,1,"high",["contrast","difference","similar"],["company","compete"],"Compare the two pictures.","com+pare(平等)→比较"),
("complete","完成；完整的",V,1,"high",["finish","end","whole","done"],["compete","company"],"I have completed my homework.","com+plete(充满)→完成"),
("communicate","交流；沟通",V,2,"medium",["talk","speak","message","connect"],["community","company"],"It is important to communicate with your parents.","commun+ic+ate→交流"),
("continue","继续；持续",V,1,"high",["go on","keep","stop","resume"],["control","contain"],"Please continue reading.","con+tin(拿)→继续"),
("control","控制；管理",V,1,"high",["manage","power","rule","lose"],["continue","contrast"],"You should control your temper.","control→控制"),
("cook","做饭",V,1,"high",["food","kitchen","meal","recipe"],["book","look"],"My mother cooks dinner.","cook→做饭"),
("copy","抄写；复制",V,1,"high",["write","paste","duplicate"],["coffee","happy"],"Please copy these words.","copy→复制"),
("correct","纠正",V,1,"high",["right","wrong","fix","accurate"],["collect","connect"],"Your answer is correct.","cor+rect(直)→纠正"),
("cost","花费；成本",V,1,"high",["price","pay","spend","buy"],["lost","most"],"How much does this bike cost?","cost→花费"),
("count","数数；计算",V,1,"high",["number","calculate","important"],["country","couple"],"Can you count from one to ten?","count→数数"),
("cover","覆盖；盖子",V,1,"high",["hide","protect","top","uncover"],["discover","recover"],"Snow covered the ground.","cover→覆盖"),
("create","创造；创作",V,1,"high",["make","invent","produce","design"],["creature","creative"],"She created a beautiful painting.","cre(生长)+ate→创造"),
("cross","穿过；交叉",V,1,"high",["across","road","bridge","pass"],["across","crazy"],"Be careful when you cross the road.","cross→穿过"),
("cry","哭；叫喊",V,1,"high",["tears","sad","shout","laugh"],["dry","fly","try"],"The baby is crying.","cry→哭"),
("cut","切；割；剪",V,1,"high",["knife","scissors","slice"],["cat","cup"],"Please cut the cake into pieces.","cut→切"),
("dance","跳舞",V,1,"high",["music","song","party","sing"],["danger","chance"],"She loves dancing.","dance→跳舞"),
("decide","决定",V,1,"high",["determine","choice","choose","mind"],["declare","decline"],"I decided to learn a new language.","de+cide(切)→决定"),
("depend","依赖；取决于",V,1,"high",["rely","independent","need","trust"],["defend","depth"],"It depends on the weather.","de+pend(挂)→依赖"),
("describe","描述；描写",V,1,"high",["explain","tell","words","detail"],["design","despite"],"Can you describe what happened?","de+scribe(写)→描述"),
("develop","发展；开发",V,1,"high",["grow","improve","progress","build"],["depend","envelop"],"China has developed rapidly.","de+velop(包)→发展"),
("die","死；死亡",V,1,"high",["dead","death","alive","live"],["diet","dirt"],"Many people die from accidents.","die→死亡"),
("discuss","讨论；商议",V,1,"high",["talk","argue","conversation","agree"],["disgust","discovery"],"Lets discuss this problem.","dis+cuss(敲)→讨论"),
("discover","发现",V,1,"high",["find","explore","uncover","invent"],["cover","recover"],"Columbus discovered America.","dis+cover(盖子)→发现"),
("divide","分开；除",V,1,"medium",["separate","split","part","multiply"],["decide","provide"],"The teacher divided the class.","di+vide(分开)→分开"),
("do","做；干",V,1,"high",["make","work","action"],["did","done"],"What do you usually do on weekends?","do→做"),
("draw","画；拉",V,1,"high",["paint","picture","sketch","write"],["drawer","drawing"],"She is good at drawing.","draw→画"),
("dream","梦想；做梦",N,1,"high",["hope","wish","sleep","goal"],["cream","team"],"My dream is to become a scientist.","dream→梦想"),
("drink","喝；饮料",V,1,"high",["water","juice","tea","eat"],["drunk","drive"],"Would you like something to drink?","drink→喝"),
("drive","开车",V,1,"high",["car","road","driver","license"],["dive","dream"],"My father drives to work.","drive→开车"),
("drop","落下；掉落",V,1,"high",["fall","miss","rise"],["crop","drip"],"Be careful not to drop the glass.","drop→落下"),
("earn","赚；挣得",V,1,"medium",["money","work","pay","salary"],["learn","yearn"],"He earns a lot of money.","earn→赚"),
("eat","吃",V,1,"high",["food","drink","meal","hungry"],["east","heat"],"We usually eat lunch at school.","eat→吃"),
("encourage","鼓励；激励",V,1,"high",["support","motivate","inspire","courage"],["courage","discourage"],"My teacher always encourages me.","en+courage(勇气)→鼓励"),
("enjoy","享受；喜欢",V,1,"high",["like","love","pleasure","fun"],["enter","enemy"],"I enjoy reading books.","en+joy(高兴)→享受"),
("enter","进入",V,1,"high",["go in","exit","leave","door"],["center","inter"],"Please enter the room quietly.","enter→进入"),
("expect","期望；预料",V,1,"high",["hope","wait","anticipate","surprise"],["except","accept"],"I expect to see you at the party.","ex+pect(看)→期待"),
("explain","解释；说明",V,1,"high",["describe","tell","understand","reason"],["experience","explore"],"Can you explain this word?","ex+plain(平坦)→解释"),
("explore","探索；探险",V,2,"medium",["discover","adventure","travel","search"],["explain","express"],"Scientists are exploring the deep sea.","ex+plore(喊)→探索"),
("express","表达",V,2,"medium",["say","show","feel","feeling"],["explain","expect"],"I cant express how thankful I am.","ex+press(压)→表达"),
("fail","失败；不及格",V,1,"high",["pass","succeed","lose","try"],["fall","feel","fill"],"He failed the math exam.","fail→失败"),
("fall","跌倒；秋天",V,1,"high",["drop","autumn","down","rise"],["fail","fill","feel"],"Be careful not to fall down.","fall→跌倒"),
("feed","喂养；饲养",V,1,"medium",["food","eat","animal","hungry"],["feel","feet"],"She feeds her cat twice a day.","feed→喂养"),
("feel","感觉；觉得",V,1,"high",["think","sense","touch","emotion"],["fill","fell"],"I feel happy today.","feel→感觉"),
("fight","打架；战斗",V,1,"high",["battle","argue","struggle","peace"],["right","night"],"We should fight against pollution.","fight→打架"),
("fill","填满；装满",V,1,"high",["full","empty","pour"],["feel","fail"],"Please fill in the form.","fill→填满"),
("find","找到；发现",V,1,"high",["look for","discover","search","lose"],["fine","fund"],"I found my lost wallet.","find→找到"),
("finish","完成；结束",V,1,"high",["end","complete","done","start"],["fine","fire"],"I finished my homework.","finish→完成"),
("fix","修理；固定",V,1,"high",["repair","broken","solve"],["fit","six"],"Can you fix my bike?","fix→修理"),
("fly","飞；飞行",V,1,"high",["bird","air","plane","wing"],["cry","try"],"Birds can fly in the sky.","fly→飞"),
("follow","跟随；遵循",V,1,"high",["lead","after","behind","rule"],["fellow","allow"],"Please follow me.","follow→跟随"),
("forget","忘记",V,1,"high",["remember","memory","lose","mind"],["forgive","forbid"],"Dont forget to bring your homework.","for+get→忘记"),
("forgive","原谅；宽恕",V,2,"medium",["pardon","sorry","apologize"],["forget"],"Please forgive me for being late.","for+give(给)→原谅"),
("form","形式；表格",N,1,"high",["shape","type","fill","table"],["from","firm"],"Please fill in this form.","form→形式"),
("found","建立；创办",V,2,"medium",["create","build","start","establish"],["find","fund"],"The school was founded in 1950.","found→建立"),
("freeze","结冰；冻结",V,2,"medium",["ice","cold","snow","melt"],["breeze","freedom"],"Water freezes at zero degrees.","freeze→结冰"),
("get","得到；变得",V,1,"high",["receive","obtain","become","take"],["got","gate"],"I got a letter from my pen pal.","get→得到"),
("give","给；给予",V,1,"high",["take","receive","offer","send"],["gift","live"],"Please give me a hand.","give→给"),
("go","去",V,1,"high",["come","leave","walk","travel"],["do","no"],"Lets go to school.","go→去"),
("grow","生长；增长",V,1,"high",["plant","increase","develop","big"],["group","grew"],"Trees grow taller every year.","grow→生长"),
("guess","猜测；猜想",V,1,"high",["think","suppose","wonder","know"],["guest","guide"],"Can you guess the answer?","guess→猜测"),
("hang","悬挂；挂起",V,2,"medium",["put up","hold","drop"],["hand","bang"],"She hung the picture on the wall.","hang→悬挂"),
("happen","发生",V,1,"high",["occur","take place","event","accident"],["happy","hard"],"What happened yesterday?","happen→发生"),
("hate","讨厌；恨",V,1,"high",["dislike","love","angry"],["gate","late"],"I hate rainy days.","hate→讨厌"),
("have","有；拥有",V,1,"high",["own","get","possess","hold"],["has","had"],"I have a beautiful bike.","have→有"),
("hear","听见",V,1,"high",["listen","sound","ear","noise"],["heart","here"],"I can hear someone singing.","hear→听见"),
("help","帮助",V,1,"high",["assist","support","aid","save"],["held","hide"],"Can you help me?","help→帮助"),
("hide","隐藏；躲藏",V,1,"medium",["seek","cover","find","show"],["help","ride"],"The cat is hiding behind the sofa.","hide→隐藏"),
("hit","打；击中",V,1,"medium",["beat","strike","hurt","miss"],["hot","hat"],"The ball hit the window.","hit→打"),
("hold","拿着；举行",V,1,"high",["keep","grasp","hand","catch"],["old","cold"],"Please hold this for me.","hold→拿着"),
("hope","希望；期望",V,1,"high",["wish","expect","dream","believe"],["home","hop"],"I hope you have a good time.","hope→希望"),
("hurry","匆忙；赶快",V,1,"medium",["rush","fast","quick","slow"],["hungry","carry"],"Hurry up, or we will be late.","hurry→匆忙"),
("hurt","伤害；疼痛",V,1,"high",["pain","harm","injure","ache"],["heart","hunt"],"My legs hurt after running.","hurt→伤害"),
("imagine","想象；设想",V,1,"high",["think","dream","picture","create"],["image","immediate"],"Can you imagine life without water?","imagine→想象"),
("improve","改善；提高",V,1,"high",["better","develop","progress","increase"],["prove","impress"],"I want to improve my English.","im+prove(证明)→提高"),
("include","包括；包含",V,1,"high",["contain","consist","exclude","have"],["increase","conclude"],"The price includes breakfast.","in+clude(关)→包括"),
("increase","增加；增长",V,1,"high",["grow","rise","decrease","add"],["include","decrease"],"The population continues to increase.","in+crease(增长)→增加"),
("influence","影响",V,2,"medium",["affect","impact","effect","change"],["information","influenza"],"Parents have a great influence on their children.","in+flu(流)+ence→影响"),
("inform","通知；告知",V,2,"medium",["tell","notify","let know","message"],["form","perform"],"Please inform me of any changes.","in+form(形状)→通知"),
("insist","坚持；坚决要求",V,2,"medium",["persist","demand","maintain"],["inside","insect"],"He insisted on paying for the meal.","in+sist(站)→坚持"),
("interest","使感兴趣",V,1,"high",["interesting","curious","fascinate","bore"],["interesting","interior"],"This book interests me a lot.","interest→使感兴趣"),
("introduce","介绍",V,1,"high",["present","meet","recommend","name"],["introduction","produce"],"Let me introduce myself.","intro+duce(引)→介绍"),
("invent","发明",V,1,"medium",["create","discover","design","make"],["invest","invite"],"Edison invented the light bulb.","in+vent(来)→发明"),
("invite","邀请",V,1,"high",["ask","welcome","invitation"],["invent","invest"],"She invited me to her birthday party.","in+vite(来)→邀请"),
("join","参加；加入",V,1,"high",["enter","participate","group","club"],["joint","joke"],"I want to join the English club.","join→加入"),
("judge","判断；审判",V,2,"medium",["decide","determine","evaluate"],["just","jug"],"Dont judge a person by appearance.","judge→判断"),
("jump","跳；跳跃",V,1,"high",["leap","hop","run","high"],["dump","pump"],"The cat jumped onto the table.","jump→跳"),
("keep","保持；保留",V,1,"high",["hold","stay","continue","save"],["key","keen"],"Keep quiet, please.","keep→保持"),
("kick","踢",V,1,"medium",["hit","foot","ball","soccer"],["pick","tick"],"He kicked the ball into the goal.","kick→踢"),
("know","知道；了解",V,1,"high",["understand","learn","find","realize"],["now","new"],"I know the answer.","know→知道"),
("laugh","笑；大笑",V,1,"high",["smile","cry","funny","joke"],["cough","tough"],"They laughed at the funny joke.","laugh→笑"),
("learn","学习",V,1,"high",["study","know","teach","education"],["earn","lean"],"I learn English every day.","learn→学习"),
("leave","离开；留下",V,1,"high",["arrive","stay","go","depart"],["leaf","live"],"He left home at seven.","leave→离开"),
("lend","借出",V,1,"high",["borrow","give","loan"],["send","spend"],"Can you lend me your dictionary?","lend→借出"),
("let","让；允许",V,1,"high",["allow","permit","make"],["left","set"],"Let me help you.","let→让"),
("lie","躺；撒谎",V,1,"high",["rest","truth","false","down"],["tie","die"],"Dont lie to me.","lie→撒谎"),
("lift","举起；抬起",V,2,"medium",["raise","carry","pick up"],["left","gift"],"Can you help me lift this box?","lift→举起"),
("like","喜欢",V,1,"high",["love","enjoy","dislike","hate"],["live","line"],"I like playing basketball.","like→喜欢"),
("limit","限制",V,2,"medium",["restrict","control","boundary"],["lit","line"],"We should limit the use of plastic bags.","limit→限制"),
("listen","听",V,1,"high",["hear","sound","music","ear"],["lesson","letter"],"Please listen to the teacher.","listen→听"),
("live","生活；居住",V,1,"high",["stay","alive","life","exist"],["leave","love","give"],"I live in Beijing.","live→居住"),
("lock","锁；锁上",V,2,"medium",["key","door","unlock","safe"],["luck","rock"],"Dont forget to lock the door.","lock→锁"),
("look","看",V,1,"high",["see","watch","find","observe"],["book","cook"],"Look at the blackboard.","look→看"),
("lose","丢失；输",V,1,"high",["find","miss","win","fail"],["loose","loss"],"I lost my keys yesterday.","lose→丢失"),
("love","爱；喜爱",V,1,"high",["like","hate","heart","care"],["live","move"],"I love my family.","love→爱"),
("make","制作；使",V,1,"high",["create","build","do","produce"],["take","lake"],"She made a cake for me.","make→制作"),
("manage","管理；设法",V,2,"medium",["control","run","organize","handle"],["manager","mange"],"She manages the company well.","man+age→管理"),
("marry","结婚",V,2,"medium",["wedding","husband","wife","love"],["merry","carry"],"They got married last year.","marry→结婚"),
("matter","要紧；事情",N,1,"high",["thing","problem","important","issue"],["master","material"],"It doesnt matter.","matter→要紧"),
("mean","意思是；意味着",V,1,"high",["meaning","signify","intend","purpose"],["meat","means"],"What does this word mean?","mean→意思是"),
("meet","遇见；见面",V,1,"high",["see","greet","encounter"],["meat","mean"],"Nice to meet you.","meet→遇见"),
("mention","提到；提及",V,2,"medium",["refer","say","talk about"],["mental","mission"],"He didnt mention the plan.","mention→提到"),
("mind","介意；头脑",V,1,"high",["brain","care","think","object"],["find","mine"],"Do you mind if I open the window?","mind→介意"),
("miss","想念；错过",V,1,"high",["lose","hit","forget","catch"],["kiss","mass"],"I missed the bus this morning.","miss→错过"),
("mix","混合",V,2,"medium",["blend","combine","stir"],["fix","six"],"Mix the flour and water together.","mix→混合"),
("move","移动；搬家",V,1,"high",["go","change","shift","stay"],["more","moon"],"We are going to move to a new house.","move→移动"),
("multiply","乘；繁殖",V,2,"low",["divide","add","number"],["multiple","multiply"],"Three multiplied by four is twelve.","multi(多)+ply(倍)→乘"),
("name","命名；名字",V,1,"high",["call","title","name"],["same","game"],"Can you name all the colors?","name→命名"),
("need","需要",V,1,"high",["want","require","must","demand"],["knee","feed"],"I need to buy a new pen.","need→需要"),
("notice","注意；通知",V,1,"high",["observe","see","attention","note"],["notion","novice"],"I noticed a strange noise.","notice→注意"),
("offer","提供；提议",V,1,"high",["give","provide","suggest","accept"],["office","often"],"He offered to help me.","offer→提供"),
("open","打开；开放的",V,1,"high",["close","shut","begin"],["often","only"],"Please open the door.","open→打开"),
("order","命令；订购",V,1,"high",["command","request","buy","arrange"],["older","ordinary"],"I ordered a cup of coffee.","order→订购"),
("own","拥有；自己的",V,1,"high",["have","possess","belong","property"],["owe","own"],"I own a small bookstore.","own→拥有"),
("pack","打包",V,2,"medium",["bag","luggage","travel","unpack"],["back","pick"],"Have you packed your bags?","pack→打包"),
("paint","画画；油漆",V,2,"medium",["draw","color","picture","brush"],["print","point"],"She is painting a picture of the sunset.","paint→画画"),
("pass","通过；传递",V,1,"high",["fail","give","go by","success"],["past","glass"],"Please pass me the salt.","pass→传递"),
("pay","支付",V,1,"high",["money","cost","buy","spend"],["say","lay","day"],"I paid 50 yuan for this book.","pay→支付"),
("pick","挑选；采摘",V,1,"high",["choose","select","collect"],["kick","tick"],"She picked a beautiful flower.","pick→挑选"),
("place","放置；地方",V,1,"high",["put","set","position","location"],["plan","play"],"Place the books on the shelf.","place→放置"),
("plan","计划",V,1,"high",["idea","arrange","prepare","scheme"],["plant","play"],"We are planning a trip.","plan→计划"),
("play","玩；播放",V,1,"high",["game","sport","fun","music"],["plan","place"],"Lets play soccer.","play→玩"),
("please","请；使高兴",V,1,"high",["glad","happy","satisfy"],["place","peace"],"Please sit down.","please→请"),
("point","指；指向",V,1,"high",["direct","show","finger","aim"],["print","paint"],"He pointed at the map.","point→指向"),
("pollute","污染",V,2,"medium",["dirty","contaminate","clean","environment"],["population","polite"],"Factories pollute the air and water.","pollute→污染"),
("post","张贴；邮寄",V,2,"medium",["mail","send","letter"],["past","cost"],"I posted a letter to my friend.","post→邮寄"),
("pour","倒；灌",V,2,"medium",["spill","flow","liquid","water"],["four","door"],"She poured some milk into the glass.","pour→倒"),
("practice","练习",V,1,"high",["exercise","train","do","repeat"],["practise","praise"],"You need to practice English every day.","practice→练习"),
("praise","表扬；赞扬",V,2,"medium",["compliment","criticize","encourage","admire"],["price","prison"],"The teacher praised him for his hard work.","praise→表扬"),
("prefer","更喜欢",V,1,"high",["like better","choose","favor"],["perfect","prepare"],"I prefer tea to coffee.","pre+fer(带来)→更喜欢"),
("prepare","准备",V,1,"high",["get ready","plan","arrange","do"],["prefer","presence"],"I am preparing for the exam.","pre+pare(准备)→提前准备"),
("present","呈现；礼物",V,2,"medium",["show","give","gift","display"],["prevent","president"],"She presented her ideas clearly.","pre+sent(送)→呈现"),
("prevent","预防；阻止",V,1,"high",["stop","avoid","block","allow"],["present","pretend"],"We should prevent the spread of disease.","pre+vent(来)→预防"),
("print","打印；印刷",V,2,"medium",["copy","write","paper"],["point","paint"],"Please print this document.","print→打印"),
("produce","生产；制造",V,2,"medium",["make","create","manufacture","grow"],["product","program"],"This factory produces cars.","pro+duce(引导)→生产"),
("progress","进步；前进",V,1,"medium",["improve","develop","advance","grow"],["process","project"],"She is progressing in her studies.","pro+gress(走)→进步"),
("promise","承诺；保证",V,1,"high",["word","agree","swear","vow"],["price","prison"],"I promise I will come on time.","promise→承诺"),
("protect","保护",V,1,"high",["defend","guard","save","safe"],["protest","project"],"We should protect the environment.","pro+tect(覆盖)→保护"),
("provide","提供；供应",V,1,"high",["give","supply","offer","support"],["prove","produce"],"The school provides free lunch.","pro+vide(看)→提供"),
("prove","证明",V,2,"medium",["show","demonstrate","evidence","test"],["provide","produce"],"Can you prove that you are right?","prove→证明"),
("publish","出版；发表",V,3,"low",["print","book","write","release"],["public","punish"],"He published his first book.","pub(公开)+lish→出版"),
("pull","拉",V,1,"high",["push","drag","draw","tug"],["pool","full"],"Pull the door open.","pull→拉"),
("punish","惩罚",V,2,"medium",["penalty","reward","discipline"],["publish","push"],"The teacher punished him for cheating.","punish→惩罚"),
("push","推",V,1,"high",["pull","shove","press"],["pull","put"],"Push the door, please.","push→推"),
("put","放；放置",V,1,"high",["place","set","lay"],["but","cut"],"Put your books on the desk.","put→放"),
("raise","举起；饲养",V,1,"high",["lift","rise","grow","increase"],["rise","arise"],"Please raise your hand.","raise→举起"),
("reach","到达；伸手",V,1,"high",["arrive","get to","touch","hand"],["read","react"],"We reached the hotel at noon.","reach→到达"),
("read","读；阅读",V,1,"high",["book","write","learn","study"],["red","ready"],"I read a story every night.","read→阅读"),
("realize","意识到；实现",V,1,"high",["understand","recognize","know","achieve"],["real","really"],"I realized I had left my bag.","real+ize→意识到"),
("receive","收到；接收",V,1,"high",["get","accept","send","give"],["believe","relieve"],"I received a letter.","re+ceive(拿)→收到"),
("record","记录；唱片",V,2,"medium",["write down","note","document"],["recover","remember"],"Please record your name on the list.","re+cord(心)→记录"),
("reduce","减少；降低",V,2,"medium",["decrease","less","cut","increase"],["produce","introduce"],"We should reduce the use of plastic.","re+duce(引导)→减少"),
("refuse","拒绝",V,1,"high",["reject","decline","accept","agree"],["confuse","reuse"],"She refused to go with us.","re+fuse(倒)→拒绝"),
("regret","后悔；遗憾",V,2,"medium",["sorry","wish","remorse"],["great","greet"],"I regret not studying harder.","regret→后悔"),
("reject","拒绝；驳回",V,2,"medium",["refuse","decline","accept","approve"],["relate","relax"],"He rejected my offer.","re+ject(扔)→拒绝"),
("relate","联系；有关",V,2,"medium",["connect","link","associate"],["relax","release"],"This story relates to our daily life.","re+late(放)→联系"),
("relax","放松",V,1,"high",["rest","calm","easy","tense"],["relate","release"],"I like to relax on weekends.","re+lax(松)→放松"),
("remain","保持；仍然是",V,2,"medium",["stay","keep","leave"],["remind","remember"],"Please remain seated.","re+main(保持)→仍然是"),
("remember","记住",V,1,"high",["forget","recall","memory","mind"],["remind","member"],"Please remember to bring your homework.","re+member(成员)→记住"),
("remove","移除；去掉",V,2,"medium",["take away","delete","move","add"],["remain","remind"],"Please remove your shoes.","re+move(动)→移除"),
("repair","修理",V,1,"high",["fix","mend","broken","damage"],["repeat","repay"],"Can you repair my bike?","re+pair(配对)→修理"),
("repeat","重复",V,1,"high",["say again","do again","copy"],["repair","replace"],"Can you repeat that?","re+peat(说)→重复"),
("replace","替代；替换",V,2,"medium",["change","substitute","instead"],["repeat","repair"],"Nothing can replace a mothers love.","re+place(放)→替换"),
("reply","回复",V,1,"high",["answer","respond","write back"],["rely","report"],"Please reply to my email.","re+ply(折)→回复"),
("report","报告；报道",V,1,"high",["tell","announce","news"],["replay","repeat"],"She reported the accident.","re+port(带)→报告"),
("request","请求；要求",V,2,"medium",["ask","demand","require"],["question","require"],"She requested a day off.","request→请求"),
("require","需要；要求",V,1,"high",["need","demand","must","ask"],["request","acquire"],"This job requires patience.","re+quire(寻求)→要求"),
("respect","尊重",V,1,"high",["honor","admire","polite"],["expect","inspect"],"We should respect our teachers.","re+spect(看)→尊重"),
("rest","休息",V,1,"high",["relax","sleep","break","work"],["best","test"],"You should take a good rest.","rest→休息"),
("result","结果",N,1,"high",["outcome","effect","cause","consequence"],["insult","consult"],"The result will come out tomorrow.","re+sult(跳)→结果"),
("return","归还；返回",V,1,"high",["come back","give back","leave"],["retain","reveal"],"I will return the book next week.","re+turn(转)→返回"),
("review","复习；回顾",V,1,"high",["study again","go over","check"],["revive","reveal"],"I need to review my lessons.","re+view(看)→复习"),
("reward","奖励",V,2,"medium",["prize","award","punish","give"],["reward","award"],"They rewarded him for his bravery.","reward→奖励"),
("ride","骑；乘坐",V,1,"high",["bike","horse","car","drive"],["rise","road"],"She rides her bike to school.","ride→骑"),
("rise","上升；升起",V,1,"high",["increase","go up","fall","sun"],["raise","arise"],"The sun rises in the east.","rise→上升"),
("risk","冒险；风险",V,1,"medium",["danger","chance","safe","brave"],["rise","disk"],"We should not risk our lives.","risk→冒险"),
("rob","抢劫",V,3,"low",["steal","thief","crime"],["rod","rob"],"The bank was robbed last night.","rob→抢劫"),
("rock","摇滚；岩石",N,2,"medium",["stone","roll","music"],["rocket","rope"],"The kids love rock music.","rock→岩石；摇滚"),
("roll","滚动；卷",V,2,"medium",["turn","round","rotate"],["rock","role"],"The ball rolled down the hill.","roll→滚动"),
("ruin","毁坏",V,2,"medium",["destroy","damage","spoil"],["rain","run"],"The heavy rain ruined our picnic.","ruin→毁坏"),
("rule","统治；规则",V,1,"high",["govern","law","control","king"],["ruler","rude"],"The king ruled the country.","rule→统治"),
("run","跑",V,1,"high",["walk","sprint","fast","race"],["ran","ruler"],"He runs very fast.","run→跑"),
("rush","冲；匆忙",V,2,"medium",["hurry","quick","dash","slow"],["run","brush"],"Dont rush.","rush→冲"),
("save","节省；救",V,1,"high",["money","rescue","keep","waste"],["safe","same"],"We should save water.","save→节省"),
("say","说",V,1,"high",["tell","speak","talk"],["day","way"],"What did you say?","say→说"),
("score","得分；比分",N,1,"high",["point","goal","mark","test"],["store","storm"],"What was the final score?","score→得分"),
("search","搜索；搜寻",V,1,"high",["look for","find","seek","explore"],["research","reach"],"I searched everywhere for my keys.","search→搜索"),
("see","看见",V,1,"high",["look","watch","observe","notice"],["sea","she"],"I saw a beautiful bird.","see→看见"),
("seem","似乎；好像",V,1,"high",["appear","look like","feel"],["seen","seed"],"She seems happy today.","seem→似乎"),
("sell","卖",V,1,"high",["buy","shop","price","market"],["tell","well"],"They sell fresh fruit here.","sell→卖"),
("send","发送；寄",V,1,"high",["receive","post","mail","deliver"],["spend","sand"],"I sent an email to my friend.","send→发送"),
("separate","分开；分离的",V,2,"medium",["divide","split","apart","together"],["several","operate"],"Please separate the white clothes from the colored ones.","se(分开)+par(准备)+ate→分离"),
("serve","服务；端上",V,1,"high",["help","provide","service","food"],["serious","several"],"She served us a delicious dinner.","serve→服务"),
("set","设置；放",V,1,"high",["put","place","lay"],["sit","sat"],"She set the table for dinner.","set→设置"),
("shake","摇动",V,1,"medium",["move","tremble","hand"],["shape","share"],"Shake the bottle before opening.","shake→摇动"),
("share","分享",V,1,"high",["divide","give","part","together"],["shake","shame"],"We should share our food.","share→分享"),
("shoot","射击；拍摄",V,2,"medium",["gun","fire","film","hit"],["shout","shut"],"Dont shoot! Put the gun down.","shoot→射击"),
("shout","喊叫",V,1,"high",["cry","call","yell","quiet"],["shoot","shut"],"Dont shout at me!","shout→喊叫"),
("show","展示；给……看",V,1,"high",["display","reveal","see","tell"],["shoe","shut"],"Can you show me the way?","show→展示"),
("shut","关闭",V,1,"high",["close","open","door"],["shout","shoot"],"Shut the door, please.","shut→关闭"),
("sign","签名；标志",V,1,"high",["write","name","mark","signal"],["sing","sigh"],"Please sign your name here.","sign→签名"),
("silence","沉默；安静",N,2,"medium",["quiet","silent","noise","peace"],["science","sentence"],"There was complete silence in the room.","silence→沉默"),
("sing","唱歌",V,1,"high",["song","music","voice","dance"],["sign","sang"],"She sings beautifully.","sing→唱歌"),
("sit","坐",V,1,"high",["seat","stand","chair"],["set","six"],"Please sit down.","sit→坐"),
("sleep","睡觉",V,1,"high",["rest","bed","dream","wake"],["sheep","slip"],"I usually sleep at ten oclock.","sleep→睡觉"),
("slide","滑动；滑梯",V,2,"medium",["slip","glide","smooth"],["slight","smile"],"The children love the slide.","slide→滑动"),
("smell","闻；气味",V,1,"high",["nose","scent","fragrant"],["small","smile"],"The flowers smell wonderful.","smell→闻"),
("smile","微笑",V,1,"high",["laugh","happy","grin"],["small","smell"],"She gave me a warm smile.","smile→微笑"),
("smoke","吸烟；烟",V,2,"medium",["cigarette","fire","health"],["snake","snore"],"Smoking is bad for your health.","smoke→吸烟"),
("solve","解决",V,1,"high",["answer","figure out","problem","resolve"],["love","show"],"Can you solve this math problem?","solve→解决"),
("sort","分类；整理",V,2,"medium",["organize","arrange","group","classify"],["short","soft"],"Please sort the books by subject.","sort→分类"),
("sound","听起来；声音",V,1,"high",["noise","hear","voice","listen"],["south","found"],"That sounds like a great idea!","sound→听起来"),
("speak","说（语言）",V,1,"high",["talk","say","tell","language"],["break","steak"],"Can you speak English?","speak→说"),
("speed","速度",N,2,"medium",["fast","quick","slow","velocity"],["spend","spell"],"The speed limit is 60 km per hour.","speed→速度"),
("spend","花费；度过",V,1,"high",["money","time","cost","pay"],["send","stand"],"I spent 100 yuan on this book.","spend→花费"),
("spread","传播；展开",V,2,"medium",["extend","expand","share","news"],["spring","speak"],"The news spread quickly.","spread→传播"),
("stand","站；忍受",V,1,"high",["sit","rise","stay","bear"],["start","state"],"Please stand up.","stand→站"),
("start","开始",V,1,"high",["begin","commence","end","stop"],["star","state"],"School starts at eight.","start→开始"),
("stay","停留；保持",V,1,"high",["remain","keep","live","leave"],["say","study"],"I stayed at home all day.","stay→停留"),
("steal","偷",V,2,"medium",["rob","thief","take","crime"],["steel","steam"],"Someone stole my wallet.","steal→偷"),
("step","步骤；脚步",N,1,"high",["walk","foot","stage","process"],["stop","steep"],"Follow these steps.","step→步骤"),
("stick","粘贴；棍子",V,2,"medium",["attach","glue","paste","wood"],["still","stock"],"Stick the stamp on the envelope.","stick→粘贴"),
("stop","停止",V,1,"high",["start","end","cease","begin"],["step","store"],"The bus stopped in front of the school.","stop→停止"),
("store","商店；储存",N,1,"high",["shop","keep","save","supermarket"],["storm","story"],"I bought this in a store.","store→商店"),
("study","学习",V,1,"high",["learn","read","review","homework"],["student","studio"],"I study English every day.","study→学习"),
("succeed","成功",V,1,"high",["fail","achieve","success","win"],["success","suggest"],"If you work hard, you will succeed.","suc+ceed(走)→成功"),
("suggest","建议；暗示",V,1,"high",["advise","propose","recommend","idea"],["succeed","support"],"I suggest we go by bus.","sug+gest(带)→建议"),
("supply","供应",V,2,"medium",["provide","give","offer","demand"],["support","suppose"],"The government supplies food to the poor.","supply→供应"),
("support","支持",V,1,"high",["help","back","agree","encourage"],["supply","suppose"],"My family supports my decision.","sup+port(带)→支持"),
("suppose","假设；认为",V,1,"high",["think","guess","believe","imagine"],["support","supply"],"I suppose you are right.","sup+pose(放)→假设"),
("surprise","使惊奇",V,1,"high",["shock","amaze","unexpected"],["surprising","surprised"],"The news surprised everyone.","sur+prise(抓)→惊奇"),
("survive","幸存；存活",V,2,"medium",["live","alive","death","exist"],["surprise","serve"],"Only a few people survived.","sur+vive(活)→幸存"),
("sweep","打扫",V,2,"medium",["clean","brush","floor"],["sweet","swim"],"She sweeps the floor every day.","sweep→打扫"),
("swim","游泳",V,1,"high",["water","pool","sea","sport"],["sweet","swing"],"I like swimming in summer.","swim→游泳"),
("swing","摇摆；秋千",V,2,"medium",["rock","hang","move"],["swim","sing"],"The children are playing on the swing.","swing→摇摆"),
("take","拿；带",V,1,"high",["bring","carry","get","give"],["make","lake"],"Take your umbrella with you.","take→拿"),
("talk","谈话",V,1,"high",["speak","say","tell","chat"],["walk","take"],"Lets talk about the plan.","talk→谈话"),
("teach","教",V,1,"high",["learn","study","student","class"],["reach","team"],"She teaches English.","teach→教"),
("tear","撕；眼泪",V,2,"medium",["rip","break","cry"],["bear","wear"],"Dont tear the paper.","tear→撕"),
("tell","告诉",V,1,"high",["say","speak","talk","inform"],["tall","bell"],"Tell me the truth.","tell→告诉"),
("test","测试；考试",V,1,"high",["exam","check","quiz"],["text","tent"],"We will have a math test.","test→测试"),
("thank","感谢",V,1,"high",["grateful","appreciate","you"],["that","think"],"Thank you for your help.","thank→感谢"),
("think","想；认为",V,1,"high",["believe","consider","opinion","mind"],["thick","thing"],"I think you are right.","think→想"),
("throw","扔；投",V,1,"high",["catch","hit","toss","ball"],["through","though"],"Dont throw rubbish on the ground.","throw→扔"),
("tidy","整理；整洁的",V,2,"medium",["clean","neat","organize","messy"],["tiny","tide"],"Please tidy your room.","tidy→整理"),
("tie","系；绑",V,2,"medium",["knot","bind","rope"],["die","lie"],"Tie your shoelaces, please.","tie→系"),
("tip","小费；建议；尖端",N,2,"medium",["advice","top","end"],["tape","tap"],"Here is a useful tip for learning English.","tip→建议；尖端"),
("touch","触摸",V,1,"high",["feel","hand","contact","reach"],["tough","much"],"Please dont touch the painting.","touch→触摸"),
("trade","贸易；交易",V,2,"medium",["business","buy","sell","exchange"],["tradition","train"],"China trades with many countries.","trade→贸易"),
("train","训练；火车",V,1,"high",["practice","exercise","coach"],["rain","trail"],"He trains hard every day.","train→训练"),
("travel","旅行",V,1,"high",["trip","journey","tour","visit"],["trail","trouble"],"I love traveling.","travel→旅行"),
("treat","对待；治疗",V,2,"medium",["handle","deal","cure","medical"],["threat","great"],"Doctors treat patients in the hospital.","treat→治疗"),
("try","尝试；努力",V,1,"high",["attempt","effort","test"],["cry","fly","dry"],"I will try my best.","try→尝试"),
("turn","转；翻转",V,1,"high",["rotate","spin","change","round"],["burn","return"],"Turn left at the corner.","turn→转"),
("type","打字；类型",V,2,"medium",["write","keyboard","computer"],["typical","tape"],"She can type very fast.","type→打字"),
("understand","理解",V,1,"high",["know","comprehend","realize","learn"],["understand","undertake"],"I understand what you mean.","under+stand→理解"),
("unite","联合；团结",V,2,"medium",["join","together","united","divide"],["unit","universe"],"We should unite to fight pollution.","unite→联合"),
("unlock","开锁",V,3,"low",["lock","key","door","open"],["luck","block"],"Please unlock the door.","un+lock→开锁"),
("use","使用",V,1,"high",["utilize","apply","employ"],["useful","usual"],"Can I use your pen?","use→使用"),
("visit","参观；拜访",V,1,"high",["tour","see","travel","call"],["vista","vital"],"We visited the museum.","visit→参观"),
("wait","等待",V,1,"high",["stay","expect","patient"],["wake","want"],"Wait for me at the school gate.","wait→等待"),
("wake","醒来",V,1,"high",["sleep","awake","alarm"],["walk","wait"],"I woke up at six this morning.","wake→醒来"),
("walk","步行",V,1,"high",["run","step","go","stroll"],["talk","wake"],"I walk to school every day.","walk→步行"),
("want","想要",V,1,"high",["need","wish","desire","like"],["went","what"],"I want a cup of tea.","want→想要"),
("warn","警告",V,2,"medium",["caution","danger","alert"],["warm","worm"],"The teacher warned us not to be late.","warn→警告"),
("wash","洗",V,1,"high",["clean","water","soap"],["wish","watch"],"Please wash your hands.","wash→洗"),
("waste","浪费",V,1,"high",["save","spend","rubbish"],["taste","paste"],"Dont waste food.","waste→浪费"),
("watch","观看；手表",V,1,"high",["see","look","observe","time"],["wash","water"],"I watched a movie last night.","watch→观看"),
("water","浇水；水",V,1,"medium",["drink","plant","river","sea"],["watch","waste"],"Please water the plants.","water→浇水"),
("wear","穿；戴",V,1,"high",["put on","clothes","dress","hat"],["bear","war"],"She is wearing a red dress.","wear→穿"),
("weigh","称重量",V,2,"medium",["weight","heavy","light","measure"],["weigh","height"],"The baby weighs three kilograms.","weigh→称重量"),
("welcome","欢迎",V,1,"high",["greet","invite","hello"],["well","welfare"],"Welcome to our school!","welcome→欢迎"),
("win","赢；获胜",V,1,"high",["lose","beat","victory","success"],["won","wind"],"Our team won the game.","win→赢"),
("wish","祝愿；希望",V,1,"high",["hope","want","dream","desire"],["wash","which"],"I wish you a happy birthday.","wish→希望"),
("wonder","想知道；惊奇",V,1,"high",["think","curious","amaze"],["wander","wonderful"],"I wonder what will happen next.","wonder→想知道"),
("work","工作",V,1,"high",["job","labor","study","do"],["word","world"],"He works in a hospital.","work→工作"),
("worry","担心",V,1,"high",["anxious","concern","nervous"],["sorry","angry"],"Dont worry about it.","worry→担心"),
("wrap","包；裹",V,3,"low",["cover","pack","paper","gift"],["rap","crap"],"She wrapped the gift in red paper.","wrap→包；裹"),
("write","写",V,1,"high",["read","pen","paper","book"],["right","white"],"I write in my diary every day.","write→写"),
("wrong","错误的",V,1,"high",["right","correct","mistake","error"],["write","long"],"What is wrong with you?","wrong→错误的"),
]

for d in verb_data:
    add(*d)
print(f"Part 1 loaded: {len(verb_data)} words, total: {len(words)}")
