#!/usr/bin/env python3
"""Generate Grade 9 (初三) English dictation vocabulary - Go for It! Full Book (Units 1-14)
Target: 1000-1100 words covering all core vocabulary for Grade 9
"""

import json

# All vocabulary for Grade 9, organized by unit with full data
# Format: (word, meaning, phonetic, example)
VOCAB_DATA = [
    # ========== Unit 1: How can we become good learners? ==========
    ("textbook", "教科书；课本", "/ˈtekstbʊk/", "Please open your textbooks to page 20."),
    ("conversation", "对话；交谈", "/ˌkɒnvəˈseɪʃn/", "I had a long conversation with my teacher about my studies."),
    ("aloud", "大声地；出声地", "/əˈlaʊd/", "Reading aloud can help improve your pronunciation."),
    ("pronunciation", "发音；读音", "/prəˌnʌnsiˈeɪʃn/", "Your pronunciation has improved a lot this semester."),
    ("sentence", "句子", "/ˈsentəns/", "Can you make a sentence with this new word?"),
    ("patient", "有耐心的", "/ˈpeɪʃnt/", "You need to be patient when learning a new language."),
    ("expression", "表达（方式）；表示；表情", "/ɪkˈspreʃn/", "Facial expressions are important in communication."),
    ("discover", "发现；发觉", "/dɪˈskʌvər/", "Scientists discover new things every day."),
    ("secret", "秘密；秘诀", "/ˈsiːkrət/", "The secret to learning well is practicing every day."),
    ("grammar", "语法", "/ˈɡræmər/", "Grammar rules help us use language correctly."),
    ("repeat", "重复；重做", "/rɪˈpiːt/", "Please repeat after me."),
    ("note", "笔记；记录；注意；指出", "/nəʊt/", "Take notes during the class."),
    ("pal", "朋友；伙伴", "/pæl/", "He is my best pal at school."),
    ("physics", "物理；物理学", "/ˈfɪzɪks/", "Physics is one of my favorite subjects."),
    ("chemistry", "化学", "/ˈkemɪstri/", "We do experiments in chemistry class."),
    ("memorize", "记忆；记住", "/ˈmeməraɪz/", "Try to memorize these words before tomorrow."),
    ("pattern", "模式；图案", "/ˈpætn/", "I noticed a pattern in the grammar exercises."),
    ("pronounce", "发音", "/prəˈnaʊns/", "How do you pronounce this word?"),
    ("increase", "增加；增长", "/ɪnˈkriːs/", "You should increase your reading speed."),
    ("speed", "速度", "/spiːd/", "He reads at a very fast speed."),
    ("partner", "搭档；同伴", "/ˈpɑːrtnər/", "Practice the dialogue with your partner."),
    ("born", "天生的；出生的", "/bɔːrn/", "She was born with a talent for music."),
    ("ability", "能力；才能", "/əˈbɪləti/", "Everyone has the ability to learn well."),
    ("create", "创造；创建", "/kriˈeɪt/", "Create your own study plan."),
    ("brain", "大脑", "/breɪn/", "Your brain needs exercise just like your body."),
    ("active", "积极的；活跃的", "/ˈæktɪv/", "Be active in class and ask questions."),
    ("attention", "注意；关注", "/əˈtenʃn/", "Pay attention to what the teacher says."),
    ("connect", "连接；与……有联系", "/kəˈnekt/", "Connect what you learn with real life."),
    ("review", "回顾；复习", "/rɪˈvjuː/", "Review your notes before the test."),
    ("knowledge", "知识；学问", "/ˈnɒlɪdʒ/", "Knowledge is power."),
    ("wisely", "明智地；聪明地", "/ˈwaɪzli/", "Use your time wisely."),
    ("vocabulary", "词汇；词汇量", "/vəˈkæbjələri/", "Reading helps build your vocabulary."),
    ("memorize", "记忆；背诵", "/ˈmeməraɪz/", "It's hard to memorize so many words in one day."),
    ("pronunciation", "发音；读音", "/prəˌnʌnsiˈeɪʃn/", "Good pronunciation takes practice."),
    ("grammar", "语法", "/ˈɡræmər/", "Learning grammar rules is important."),
    ("textbook", "教科书；课本", "/ˈtekstbʊk/", "Don't write in your textbook."),

    # ========== Unit 2: I think that mooncakes are delicious! ==========
    ("mooncake", "月饼", "/ˈmuːnkeɪk/", "Mooncakes are traditional food for Mid-Autumn Festival."),
    ("lantern", "灯笼", "/ˈlæntərn/", "People hang red lanternes during Spring Festival."),
    ("stranger", "陌生人", "/ˈstreɪndʒər/", "Don't talk to strangers on the street."),
    ("relative", "亲属；亲戚", "/ˈrelətɪv/", "We visit our relatives during holidays."),
    ("pound", "磅；英镑", "/paʊnd/", "He lost five pounds last month."),
    ("folk", "民间的；民俗的", "/fəʊk/", "Folk stories are passed down from generation to generation."),
    ("goddess", "女神", "/ˈɡɒdes/", "Chang'e is a goddess in Chinese mythology."),
    ("whoever", "无论谁；不管谁", "/huːˈevər/", "Whoever comes first will get the prize."),
    ("steal", "偷；窃取", "/stiːl/", "Someone stole his wallet yesterday."),
    ("lay", "放置；产（卵）；下（蛋）", "/leɪ/", "The hen lays an egg every day."),
    ("dessert", "甜点；甜食", "/dɪˈzɜːrt/", "Ice cream is my favorite dessert."),
    ("garden", "花园；园子", "/ˈɡɑːrdn/", "There are many flowers in the garden."),
    ("tradition", "传统", "/trəˈdɪʃn/", "It's a tradition to give red packets during Chinese New Year."),
    ("admire", "欣赏；仰慕", "/ədˈmaɪər/", "I admire her courage and determination."),
    ("tie", "捆；束； n. 领带；纽带", "/taɪ/", "Tie your shoelaces before running."),
    ("haunted", "有鬼魂出没的；闹鬼的", "/ˈhɔːntɪd/", "They say this old house is haunted."),
    ("ghost", "鬼；鬼魂", "/ɡəʊst/", "Do you believe in ghosts?"),
    ("trick", "花招；把戏； v. 欺骗；戏弄", "/trɪk/", "Don't play tricks on others."),
    ("treat", "招待；请客； n. 款待；乐事", "/triːt/", "Let me treat you to dinner tonight."),
    ("spider", "蜘蛛", "/ˈspaɪdər/", "I'm afraid of spiders."),
    ("Christmas", "圣诞节", "/ˈkrɪsməs/", "People exchange gifts at Christmas."),
    ("novel", "（长）小说", "/ˈnɒvl/", "I'm reading a novel by Mark Twain."),
    ("eve", "前夕；前夜", "/iːv/", "New Year's Eve is a time for family reunions."),
    ("dead", "死的；失去生命的", "/ded/", "The flowers are dead from the cold weather."),
    ("business", "生意；商业；事情", "/ˈbɪznəs/", "He runs a small business in town."),
    ("punish", "处罚；惩罚", "/ˈpʌnɪʃ/", "Parents shouldn't punish children too harshly."),
    ("warn", "警告；告诫", "/wɔːrn/", "He warned me not to swim alone."),
    ("present", "现在；礼物； adj. 现在的", "/ˈpreznt/", "I bought a present for my mother's birthday."),
    ("warmth", "温暖；暖和", "/wɔːrmθ/", "The warmth of the sun feels good."),
    ("spread", "传播；展开； n. 蔓延", "/spred/", "The news spread quickly through the school."),
    ("lie", "谎言；位置 v. 说谎；位于", "/laɪ/", "Don't tell lies to your parents."),
    ("end up", "最终成为；最后处于", "/", "If you keep studying, you will end up succeeding."),
    ("the spirit of", "…的精神；…的本质", "/", "We should understand the spirit of the festival."),
    ("think of", "想起；认为", "/", "What do you think of this idea?"),
    ("dress up", "装扮；盛装打扮", "/", "Children dress up as ghosts for Halloween."),
    ("care about", "关心；在意", "/", "I really care about your feelings."),
    ("make money", "赚钱", "/", "He wants to make money by selling handmade crafts."),
    ("used to do sth.", "过去常常做某事", "/", "I used to play basketball after school."),
    ("wake up", "醒来；叫醒", "/", "I usually wake up at seven o'clock."),
    ("play a trick on sb.", "搞恶作剧；诈骗", "/", "Don't play a trick on your younger sister."),
    ("Mid-Autumn Festival", "中秋节", "/", "Mid-Autumn Festival falls on the 15th day of the 8th lunar month."),
    ("Water Festival", "泼水节（泼水节）", "/", "The Water Festival is the most popular festival in Thailand."),
    ("Dragon Boat Festival", "端午节", "/", "Dragon Boat Festival commemorates Qu Yuan."),
    ("Spring Festival", "春节", "/", "Spring Festival is the most important Chinese holiday."),
    ("Mother's Day", "母亲节", "/", "Mother's Day is celebrated on the second Sunday of May."),
    ("Father's Day", "父亲节", "/", "Father's Day is celebrated on the third Sunday of June."),
    ("Halloween", "万圣节前夜", "/", "Children wear costumes and go trick-or-treating on Halloween."),

    # ========== Unit 3: Could you please tell me where the restrooms are? ==========
    ("restroom", "(美)洗手间；公共厕所", "/ˈrestruːm/", "Excuse me, could you tell me where the restroom is?"),
    ("stamp", "邮票；印章", "/stæmp/", "I collect stamps from different countries."),
    ("bookstore", "书店", "/ˈbʊkstɔːr/", "Let's go to the bookstore this weekend."),
    ("postcard", "明信片", "/ˈpəʊstkɑːrd/", "She sent me a postcard from Paris."),
    ("pardon", "请再说一遍；抱歉", "/ˈpɑːrdn/", "Pardon? I didn't hear what you said."),
    ("bathroom", "浴室；洗手间", "/ˈbɑːθruːm/", "Where is the bathroom, please?"),
    ("normally", "通常；正常地", "/ˈnɔːrməli/", "I normally go to bed at ten o'clock."),
    ("rush", "仓促；急促 n. 匆忙", "/rʌʃ/", "Don't rush — we have plenty of time."),
    ("suggest", "建议；提议", "/səɡˈdʒest/", "I suggest you take a break."),
    ("staff", "管理人员；职工", "/stɑːf/", "The hotel staff were very friendly."),
    ("grape", "葡萄", "/ɡreɪp/", "These grapes taste sweet."),
    ("central", "中心的；中央的", "/ˈsentrl/", "The library is in the central part of the city."),
    ("nearby", "附近的；邻近的 adv. 在附近", "/ˌnɪrˈbaɪ/", "Is there a nearby restaurant?"),
    ("mail", "邮寄；邮件 v. 邮寄", "/meɪl/", "Did you mail the letter yesterday?"),
    ("east", "东边的；东方的 adv. 向东", "/iːst/", "The sun rises in the east."),
    ("fascinating", "迷人的；极有吸引力的", "/ˈfæsɪneɪtɪŋ/", "This book is absolutely fascinating."),
    ("convenient", "便利的；方便的", "/kənˈviːniənt/", "It's convenient to live near the subway station."),
    ("mall", "购物中心；商场", "/mɔːl/", "Let's meet at the shopping mall."),
    ("clerk", "职员", "/klɜːrk/", "The clerk helped me find the right size."),
    ("corner", "拐角；角落", "/ˈkɔːrnər/", "Turn right at the corner."),
    ("polite", "有礼貌的；客气的", "/pəˈlaɪt/", "Be polite when asking for help."),
    ("politely", "礼貌地；客气地", "/pəˈlaɪtli/", "He politely asked for directions."),
    ("speaker", "讲(某种语言)的人；发言者", "/ˈspiːkər/", "She is a native English speaker."),
    ("request", "要求；请求", "/rɪˈkwest/", "They refused my request."),
    ("direction", "方向；方位", "/daɪˈrekʃn/", "Can you give me directions to the station?"),
    ("correct", "正确的；恰当的", "/kəˈrekt/", "Your answer is correct."),
    ("whom", "谁；什么人", "/huːm/", "To whom did you speak?"),
    ("address", "地址；通讯处", "/əˈdres/", "What's your email address?"),
    ("underground", "地下的 n. 地铁", "/ˌʌndərˈɡraʊnd/", "Take the underground to the city center."),
    ("course", "课程；学科；过程", "/kɔːrs/", "Which course are you taking this term?"),
    ("impolite", "不礼貌的；粗鲁的", "/ˌɪmpəˈlaɪt/", "It's impolite to interrupt others when they're speaking."),
    ("direct", "直接的；直率的", "/daɪˈrekt/", "Could you give me direct directions?"),
    ("choice", "选择；挑选", "/tʃɔɪs/", "Making the right choice is important."),
    ("request", "(正式或礼貌的)要求；请求", "/rɪˈkwest/", "They made a request for more time."),
    ("correctly", "正确地；得体地", "/kəˈrektli/", "She answered all questions correctly."),

    # ========== Unit 4: I used to be afraid of the dark. ==========
    ("humorous", "幽默的；滑稽的", "/ˈhjuːmərəs/", "He has a humorous way of telling stories."),
    ("silent", "不说话的；沉默的", "/ˈsaɪlənt/", "She remained silent throughout the meeting."),
    ("helpful", "有用的；有帮助的", "/ˈhelpfl/", "Thank you for your helpful advice."),
    ("from time to time", "时常；不时", "/", "I still see him from time to time."),
    ("score", "得分；分数 v. 得分", "/skɔːr/", "What was your score on the math test?"),
    ("background", "背景", "/ˈbækɡraʊnd/", "Can you tell me your educational background?"),
    ("interview", "面试；访谈 v. 采访；面试", "/ˈɪntərvjuː/", "I have a job interview tomorrow."),
    ("Asian", "亚洲的；亚洲人的 n. 亚洲人", "/ˈeɪʃn/", "China is the largest Asian country."),
    ("deal", "对待；处理； n. 交易", "/diːl/", "How do you deal with stress?"),
    ("dare", "敢于；敢（于）", "/der/", "She dare not go out alone at night."),
    ("private", "私人的；秘密的", "/ˈpraɪvət/", "This is a private conversation."),
    ("guard", "警卫；看守 v. 守卫；保卫", "/ɡɑːrd/", "A security guard stands at the entrance."),
    ("require", "需要；要求", "/rɪˈwaɪər/", "All students are required to wear uniforms."),
    ("speech", "演讲；讲话；发言", "/spiːtʃ/", "She gave a wonderful speech at graduation."),
    ("public", "民众；adj. 公开的；公众的", "/ˈpʌblɪk/", "Smoking is not allowed in public places."),
    ("in person", "亲身；亲自", "/", "You must apply for the visa in person."),
    ("ant", "蚂蚁", "/ænt/", "Ants work together to carry food."),
    ("insect", "昆虫", "/ˈɪsekt/", "Bees are useful insects."),
    ("seldom", "很少；不常", "/ˈseldom/", "I seldom eat fast food."),
    ("influence", "影响 n./v.", "/ˈɪnfluəns/", "Parents have great influence on their children."),
    ("absent", "缺席；不在场", "/ˈæbsənt/", "He was absent from school yesterday."),
    ("fail", "失败；不及格", "/feɪl/", "Never give up even if you fail."),
    ("examination", "考试；检查", "/ɪɡˌzæmɪˈneɪʃn/", "The final examination is next week."),
    ("exactly", "确切地；精确地", "/ɪɡˈzæktli/", "That's exactly what I meant."),
    ("pride", "自豪；骄傲 n.", "/praɪd/", "His parents take great pride in his success."),
    ("proud", "自豪的；骄傲的", "/praʊd/", "I'm proud of what I've achieved."),
    ("general", "普遍的；总的；常规的", "/ˈdʒenrəl/", "In general, people here are friendly."),
    ("introduction", "介绍", "/ˌɪntrəˈdʌkʃn/", "Let me make a brief introduction."),
    ("be proud of", "以……为荣", "/", "We are proud of our country's achievements."),
    ("take pride in", "以……为傲；感到自豪", "/", "She takes pride in her work."),
    ("in public", "公开地；当众", "/", "He doesn't like to speak in public."),
    ("give a speech", "发表演讲", "/", "The president gave a speech last night."),
    ("all the time", "总是；一直", "/", "She smiles all the time."),
    ("take up doing sth.", "开始从事；喜欢上（某活动）", "/", "He took up painting last year."),
    ("deal with", "处理；应付", "/", "How do you deal with difficult problems?"),
    ("no longer", "不再", "/", "He no longer lives here."),
    ("not...any more", "不再", "/", "I don't eat candy any more."),
    ("used to", "过去曾经；过去常常", "/", "I used to be shy when I was young."),
    ("dark", "黑暗的；暗色的", "/dɑːrk/", "I used to be afraid of the dark."),

    # ========== Unit 5: What are the shirts made of? ==========
    ("chopstick", "筷子", "/ˈtʃɒpstɪk/", "Chinese people use chopsticks to eat."),
    ("coin", "硬币", "/kɔɪn/", "I found a coin on the street."),
    ("fork", "餐叉；叉子", "/fɔːrk/", "Would you like a fork or chopsticks?"),
    ("blouse", "(女式)短上衣；衬衫", "/blaʊs/", "She bought a beautiful blouse yesterday."),
    ("silver", "银；银制的；银色的", "/ˈsɪlvər/", "This ring is made of pure silver."),
    ("glass", "玻璃；玻璃杯", "/ɡlɑːs/", "Be careful with that glass window."),
    ("cotton", "棉；棉花", "/ˈkɒtn/", "This shirt is made of cotton."),
    ("steel", "钢；钢铁", "/stiːl/", "The building has a steel frame."),
    ("fair", "展览会；集市；公平的", "/fer/", "There's a trade fair in Shanghai next week."),
    ("environmental", "自然环境的；有关环境的", "/ɪnˌvaɪrənˈmentl/", "Environmental protection is everyone's responsibility."),
    ("grass", "草；草地", "/ɡrɑːs/", "Don't walk on the grass."),
    ("leaf", "叶；叶子", "/liːf/", "In autumn leaves turn yellow and fall."),
    ("produce", "生产；制造；农产品", "/prəˈdjuːs/", "This factory produces cars."),
    ("widely", "广泛地；普遍地", "/ˈwaɪdli/", "English is widely used around the world."),
    ("process", "加工；过程； n. 过程", "/ˈprəʊses/", "The food is processed in a clean factory."),
    ("pack", "打包；包装； n. 包", "/pæk/", "Please pack your bags for the trip."),
    ("product", "产品；制品", "/ˈprɒdʌkt/", "This product sells well in Europe."),
    ("France", "法国", "/frɑːns/", "Paris is the capital of France."),
    ("local", "当地的；本地的", "/ˈləʊkl/", "We buy vegetables from local farmers."),
    ("even though", "即使；虽然", "/", "Even though it rained, we went hiking."),
    ("avoid", "避免；回避", "/əˈvɔɪd/", "You should avoid making the same mistakes."),
    ("everyday", "每天的；日常的", "/ˈevridei/", "English is part of everyday life."),
    ("mobile", "可移动的；非固定的", "/ˈməʊbaɪl/", "Almost everyone has a mobile phone now."),
    ("handbag", "(女式)手提包", "/ˈhændbæɡ/", "She carried a leather handbag."),
    ("boss", "老板；上司", "/bɒs/", "My boss asked me to work overtime."),
    ("Germany", "德国", "/ˈdʒɜːrməni/", "Germany is famous for its cars."),
    ("surface", "表面；表层", "/ˈsɜːrfɪs/", "The surface of the lake is very calm."),
    ("material", "材料；原料", "/məˈtɪəriəl/", "What material is this dress made of?"),
    ("traffic", "交通；路上行驶的车辆", "/ˈtræfɪk/", "Traffic is heavy during rush hours."),
    ("postman", "邮递员", "/ˈpəʊstmən/", "The postman delivers letters every morning."),
    ("cap", "(尤指无檐的)帽子；覆盖", "/kæp/", "Wear a cap to protect yourself from the sun."),
    ("glove", "(分手指的)手套", "/ɡlʌv/", "Put on gloves before working in the garden."),
    ("international", "国际的", "/ˌɪntərˈnæʃnəl/", "English is an international language."),
    ("competitor", "竞争者；参赛者", "/kəmˈpetɪtər/", "There are over fifty competitors in the race."),
    ("its", "它的", "/ɪts/", "The company changed its name."),
    ("form", "形式；形态；表格；形成", "/fɔːrm/", "Please fill out this form."),
    ("balloon", "气球", "/bəˈluʊn/", "Children love playing with balloons."),
    ("clay", "黏土；陶土", "/kleɪ/", "These clay pots are handmade."),
    ("celebration", "庆祝；庆祝会", "/ˌselɪˈbreɪʃn/", "The celebration lasted all night long."),
    ("scissors", "剪刀", "/ˈsɪzərz/", "Pass me the scissors, please."),
    ("lively", "生气勃勃的；（色彩）鲜艳的", "/ˈlaɪvli/", "She is a lively girl who loves sports."),
    ("fairy", "童话故事；仙子", "/ˈferi/", "Kids love listening to fairy tales."),
    ("heat", "热；高温 v. 加热", "/hiːt/", "Heat the water before drinking."),
    ("polish", "磨光；修改；润色", "/ˈpɒlɪʃ/", "Polish your shoes before the interview."),
    ("complete", "完整的；完全的；完成", "/kəmˈpliːt/", "Have you completed your homework?"),
    ("historical", "有关历史的；史学的", "/hɪˈstɒrɪkl/", "Xi'an is a famous historical city."),
    ("no matter", "不论；无论", "/", "No matter how hard it is, never give up."),
    ("be known for", "因……而闻名", "/", "France is known for its wine and cheese."),
    ("be made of/in", "由……制成（看出/看不出原材料）", "/", "The table is made of wood."),
    ("by hand", "用手；手工", "/", "This sweater was knitted by hand."),
    ("send out", "发出；派遣；发送", "/", "The company sent out invitations to all employees."),
    ("cover with", "用……覆盖；覆盖着", "/", "The mountains are covered with snow."),
    ("rise into", "上升到；升入", "/", "Balloon rose into the sky quickly."),
    ("turn...into", "把……变成", "/", "The caterpillar turns into a butterfly."),
    ("put on", "穿上；上演；增加（体重）", "/", "Put on your coat — it's cold outside."),
    ("paper cutting", "剪纸（艺术）", "/", "Paper cutting is a traditional Chinese art form."),
    ("be covered with", "被……覆盖；盖满", "/", "The ground was covered with fallen leaves."),
    ("international kite festival", "国际风筝节", "/", "Weifang holds an international kite festival every spring."),
    ("from abroad", "来自国外", "/", "Many products in this store come from abroad."),
    ("ask for help", "寻求帮助", "/", "Don't be afraid to ask for help when needed."),
    ("many different kinds of", "许多不同种类的", "/", "There are many different kinds of flowers in the park."),
    ("be famous for", "因……而著名", "/", "Suzhou is famous for its gardens."),
    ("for example", "例如", "/", "Many fruits, for example apples and oranges, contain vitamin C."),
    ("as far as I know", "据我所知", "/", "As far as I know, he lives in Beijing now."),
    ("on the side of", "在……的一侧/旁边", "/", "There's a cafe on the side of the road."),
    ("good at", "擅长", "/", "She is good at speaking English."),
    ("avoid doing", "避免做", "/", "You should avoid staying up too late."),
    ("everyday things", "日常用品；每天的事物", "/", "Mobile phones have become everyday things."),
    ("buy...for", "为……购买", "/", "My mom bought a gift for my birthday."),
    ("mobile phone", "手机；移动电话", "/", "Everyone in my class has a mobile phone."),
    ("high-technology products", "高科技产品", "/", "Japan exports high-technology products worldwide."),
    ("in many different areas", "在很多不同的领域", "/", "Computers are used in many different areas."),
    ("traffic accident", "交通事故", "/", "The traffic accident caused a long jam."),
    ("a pair of", "一双；一副；一对", "/", "I need a pair of scissors."),
    ("during the Spring Festival", "在春节期间", "/", "Families gather during the Spring Festival."),
    ("brand name", "品牌名称；商标", "/", "Do you know the brand name of this product?"),

    # ========== Unit 6: When was it invented? ==========
    ("heel", "鞋跟；足跟", "/hiːl/", "These shoes have high heels."),
    ("scoop", "勺；铲子 v. 用勺舀", "/skuːp/", "Use a scoop to serve the ice cream."),
    ("electricity", "电；电能", "/ɪˌlekˈtrɪsəti/", "Electricity is essential in modern life."),
    ("style", "样式；款式；方式", "/staɪl/", "This dress is in the latest style."),
    ("project", "项目；工程", "/ˈprɒdʒekt/", "Our science project won first prize."),
    ("pleasure", "高兴；愉快", "/ˈpleʒər/", "It's a pleasure to help you."),
    ("zipper", "拉链；( Z形的)拉锁", "/ˈzɪpər/", "The zipper on my jacket is broken."),
    ("daily", "每日的；日常的", "/ˈdeɪli/", "Reading newspapers is my daily habit."),
    ("have a point", "有道理", "/", "You have a point — let's discuss it more."),
    ("website", "网站", "/ˈwebsait/", "I found the information on their website."),
    ("pioneer", "先驱；先锋；先锋者", "/ˌpaɪəˈnɪr/", "Thomas Edison was a pioneer in invention."),
    ("list", "名单；清单 v. 列表；列清单", "/lɪst/", "Make a list of things you need to buy."),
    ("mention", "提到；说到", "/ˈmenʃn/", "Don't mention it — it was nothing."),
    ("accidental", "意外的；偶然的", "/ˌæksɪˈdentl/", "The discovery was completely accidental."),
    ("nearly", "几乎；差不多", "/ˈnɪrli/", "It's nearly time to go home."),
    ("boil", "煮沸；烧开", "/bɔɪl/", "Boil some water for tea."),
    ("smell", "气味 v. 闻起来", "/smel/", "The flowers smell sweet."),
    ("refrigerator", "冰箱", "/rɪˈfrɪdʒəreɪtər/", "Put the milk in the refrigerator."),
    ("low", "低的；矮的", "/ləʊ/", "The temperature is very low today."),
    ("somebody", "某人；有人", "/ˈsʌmbədi/", "Somebody left their phone here."),
    ("translate", "翻译", "/trænsˈleit/", "Can you translate this into Chinese?"),
    ("lock", "锁 v. 锁上； n. 锁", "/lɒk/", "Remember to lock the door when you leave."),
    ("earthquake", "地震", "/ˈɜːrθkeik/", "An earthquake struck the coastal region."),
    ("sudden", "突然的", "/ˈsʌdn/", "There was a sudden change in plans."),
    ("bell", "钟声；铃声；铃", "/bel/", "The bell rings at eight o'clock."),
    ("biscuit", "饼干", "/ˈbɪskɪt/", "Would you like a biscuit with your tea?"),
    ("cookie", "甜饼；曲奇饼干", "/ˈkʊki/", "She baked cookies for the party."),
    ("musical", "音乐的；有音乐天赋的", "/ˈmjuːzɪkl/", "She has musical talent."),
    ("instrument", "器械；仪器；乐器", "/ˈɪnstrəment/", "Piano is a popular musical instrument."),
    ("sour", "酸的；酸味的", "/ˈsaʊər/", "Lemons taste sour."),
    ("customer", "顾客；客户", "/ˈkʌstəmər/", "The customer is always right."),
    ("frisbee", "飞盘", "/ˈfrɪzbi/", "Let's play frisbee in the park."),
    ("lemon", "柠檬", "/ˈlemən/", "I'd like a cup of lemon tea."),
    ("Olympic", "奥林匹克的；奥运会的", "/əˈlɪmpik/", "The Olympic Games are held every four years."),
    ("basket", "篮；筐", "/ˈbæskɪt/", "Put the fruit in the basket."),
    ("popularity", "受欢迎；普及", "/ˌpɒpjuˈlærəti/", "Basketball enjoys great popularity among teenagers."),
    ("look up to", "钦佩；仰慕", "/", "I really look up to my older brother."),
    ("hero", "英雄；男主角", "/ˈhɪəroʊ/", "Firefighters are heroes who save people's lives."),
    ("professional", "职业的；专业的", "/prəˈfeʃənl/", "He dreams of becoming a professional basketball player."),
    ("divide", "划分；分开", "/dɪˈvaɪd/", "The teacher divided us into groups."),
    ("not only...but also...", "不仅……而且……", "/", "He is not only smart but also hardworking."),
    ("achieve", "实现；成功", "/əˈtʃiːv/", "Work hard to achieve your dreams."),
    ("believe", "相信；认为", "/bɪˈliːv/", "I believe you can do it."),
    ("all of a sudden", "突然；猛地", "/", "All of a sudden, it started to rain."),
    ("by accident", "偶然；意外地", "/", "Penicillin was discovered by accident."),
    ("fall into", "落入；陷入", "/", "Be careful not to fall into the water."),
    ("without doubt", "毫无疑问；的确", "/", "He is without doubt the best student in our class."),
    ("take place", "发生；举行", "/", "When does the meeting take place?"),
    ("come up with", "想出；提出", "/", "Can you come up with a better idea?"),
    ("work on", "从事；致力于；影响", "/", "She is working on a new novel."),
    ("by mistake", "错误地；无意中", "/", "I took the wrong bag by mistake."),
    ("divide...into", "把……分成……", "/", "Divide the cake into eight pieces."),
    ("dream of", "梦想；向往", "/", "She dreams of traveling around the world."),
    ("at the same time", "同时", "/", "Don't try to do everything at the same time."),
    ("encourage sb. to do", "鼓励某人做某事", "/", "Teachers encourage us to read more books."),
    ("stop...from doing", "阻止某人做某事", "/", "Nothing can stop us from achieving our goals."),
    ("the Olympics", "奥林匹克运动会", "/", "Many athletes compete in the Olympics."),
    ("make mistakes", "犯错；出错", "/", "It's OK to make mistakes — we learn from them."),
    ("come true", "(梦想)实现", "/", "I hope your dream will come true."),
    ("at last", "终于；最后", "/", "At last, we reached the top of the mountain."),
    ("fall down", "摔倒；倒塌", "/", "Be careful or you'll fall down."),
    ("think over", "仔细思考", "/", "Think it over before making a decision."),
    ("according to", "根据；按照", "/", "According to the news, it will rain tomorrow."),
    ("in this way", "用这种方法", "/", "In this way, you can solve the problem easily."),
    ("look forward to", "期待；盼望", "/", "I'm looking forward to seeing you again."),
    ("try out", "试验；试用；参加选拔", "/", "Why don't you try out for the school team?"),
    ("in the end", "最后；终于", "/", "In the end, they won the game."),
    ("be used for doing", "被用来做……", "/", "Knives are used for cutting food."),
    ("invention", "发明；创造", "/ɪnˈvenʃn/", "The invention of the Internet changed the world."),
    ("inventor", "发明者；创造者", "/ɪnˈventər/", "Edison was a great inventor."),

    # ========== Unit 7: Teenagers should be allowed to choose their own clothes. ==========
    ("license", "证件；许可证", "/ˈlaɪsns/", "Do you have a driver's license?"),
    ("safety", "安全；安全性", "/ˈseɪfti/", "Safety comes first in everything we do."),
    ("smoke", "烟；吸烟 v. 吸烟", "/sməʊk/", "Smoking is harmful to health."),
    ("part-time", "兼职的", "/ˌpɑːrtˈtaim/", "He has a part-time job at a bookstore."),
    ("pierce", "刺穿；穿透", "/pɪrs/", "She got her ears pierced."),
    ("earring", "耳环；耳饰", "/ˈɪrɪŋ/", "Those earrings look beautiful on you."),
    ("choose", "选择；挑选", "/tʃuːz/", "Choose wisely — you can't change the past."),
    ("get in the way of", "妨碍；阻挡", "/", "Don't let fear get in the way of your dreams."),
    ("chance", "机会；可能性", "/tʃæns/", "Give yourself a chance to try something new."),
    ("achieve", "实现；达到；完成", "/əˈtʃiːv/", "Hard work helps you achieve your goals."),
    ("society", "社会", "/saɪˈəti/", "We should contribute to society."),
    ("support", "支持；支撑 v. 支持", "/səˈpɔːrt/", "My family always supports my decisions."),
    ("enter", "进入；参加", "/ˈentər/", "Please enter through the back door."),
    ("practice", "练习；实践 v. 练习", "/ˈpræktis/", "Practice makes perfect."),
    ("importance", "重要性", "/ɪmˈpɔːrtns/", "Education is of great importance to everyone."),
    ("decision", "决定；决心", "/dɪˈsɪʒn/", "Making the right decision is not easy."),
    ("manage", "设法完成；管理", "/ˈmænɪdʒ/", "She manages to balance work and study."),
    ("social", "社会的；社交的", "/ˈsəʊʃl/", "Social media changes how we communicate."),
    ("community", "社区；社会；团体", "/kəˈmjuːnəti/", "Our community organizes events regularly."),
    ("keep away from", "远离", "/", "Keep away from dangerous places."),
    ("talk back", "顶嘴；回嘴", "/", "Don't talk back to your parents."),
    ("move out", "搬出去；搬走", "/", "He decided to move out and live alone."),
    ("make one's own decision", "自己做决定", "/", "Teenagers should learn to make their own decisions."),
    ("serious about", "认真对待；严肃对待", "/", "Are you serious about learning English?"),
    ("spend time on", "在……上花时间", "/", "You should spend more time on reading."),
    ("be strict with", "对……严格要求", "/", "Our teacher is strict with us about homework."),
    ("allow", "允许；准许", "/əˈlaʊ/", "My parents don't allow me to stay out late."),
    ("teenager", "青少年(13~19岁的)", "/ˈtiːneɪdʒər/", "Teenagers need enough sleep every night."),
    ("chance", "机会；可能性", "/tʃɑːns/", "This is your chance to prove yourself."),
    ("hobby", "业余爱好", "/ˈhɒbi/", "Reading is my favorite hobby."),

    # ========== Unit 8: It must belong to Carla. ==========
    ("whose", "谁的；(特指)那个(人)的", "/huːz/", "Whose book is this?"),
    ("truck", "卡车；货车", "/trʌk/", "A truck delivered the furniture this morning."),
    ("rabbit", "兔；野兔", "/ˈræbɪt/", "The rabbit hopped across the grass."),
    ("attend", "出席；参加；上（学等）", "/əˈtend/", "Did you attend the meeting yesterday?"),
    ("valuable", "贵重的；很有用的；宝贵的", "/ˈvæljuəbl/", "Time is the most valuable thing we have."),
    ("picnic", "野餐", "/ˈpɪknik/", "Let's have a picnic in the park this Sunday."),
    ("anybody", "任何人", "/ˈenibɒdi/", "Did anybody call while I was out?"),
    ("noise", "声音；噪音", "/nɔɪz/", "Please stop making so much noise."),
    ("policeman", "男警察", "/pəˈliːsmən/", "A policeman directed traffic at the crossing."),
    ("wolf", "狼", "/wʊlf/", "The wolf howled at the moon."),
    ("laboratory", "实验室", "/ləˈbɒrətri/", "Students conduct experiments in the laboratory."),
    ("coat", "外套；外衣；涂层", "/kəʊt/", "Put on your coat — it's cold outside."),
    ("sleepy", "困倦的；瞌睡的", "/ˈsliːpi/", "I feel sleepy after lunch."),
    ("pick up", "捡起；拾起；(开车)接(某人)；学会", "/", "Pick up your toys, please."),
    ("run after", "追逐；追赶", "/", "Don't run after the bus — it's gone."),
    ("in the neighborhood", "在附近；在社区里", "/", "There's a good restaurant in the neighborhood."),
    ("have fun (doing)", "玩得高兴", "/", "We had fun playing games at the party."),
    ("too much", "太多（后接不可数名词）", "/", "Don't eat too much sugar."),
    ("feel sleepy", "感到困倦", "/", "I feel sleepy because I stayed up late last night."),
    ("there must be something doing", "一定有什么正在发生/进行", "/", "There must be something happening outside."),
    ("something unusual", "不寻常的事/东西", "/", "I noticed something unusual in the corner."),
    ("at the picnic", "在野餐时；野餐中", "/", "We met many friends at the picnic."),
    ("nothing much", "没什么事；没多少东西", "/", "— What are you doing? — Nothing much."),
    ("belong to", "属于", "/", "This book belongs to the library."),
    ("possibly", "可能地；也许", "/ˈpɒsəbli/", "He might possibly arrive late today."),
    ("must be", "一定是；肯定是（推测）", "/", "That must be Tom — I recognize his voice."),
    ("could be", "可能是（可能性较小）", "/", "It could be someone else's bag."),

    # ========== Unit 9: I like music that I can dance to. ==========
    ("prefer", "更喜欢", "/prɪˈfɜːr/", "I prefer tea to coffee."),
    ("lyrics", "歌词；(复)抒情诗", "/ˈlɪrɪks/", "The lyrics of this song are very moving."),
    ("Australian", "澳大利亚的；澳大利亚人的 n. 澳大利亚人", "/ɒˈstreɪliən/", "The Australian kangaroo is a unique animal."),
    ("electronic", "电子的；电子设备的", "/ɪˌlekˈtrɒnik/", "I like electronic music."),
    ("suppose", "推测；假定；认为", "/səˈpəʊz/", "I suppose you're right."),
    ("smooth", "平滑的；悦耳的；光滑的", "/smuːð/", "This silk feels very smooth."),
    ("spare", "空闲的；备用的 v. 抽出；留出", "/sper/", "In my spare time, I read books."),
    ("case", "情况；实例；病例；箱；盒", "/keis/", "In case of fire, break the glass."),
    ("director", "导演；部门负责人", "/daɪˈrektər/", "Who is the director of this movie?"),
    ("war", "战争；战争状态", "/wɔːr/", "World War II ended in 1945."),
    ("stick", "坚持；黏住； n. 棍；棒", "/stɪk/", "Stick to your principles no matter what."),
    ("shut", "关闭；关上", "/ʃʌt/", "Shut the door, please."),
    ("dialogue", "对话；(小说或戏剧中的)对白", "/ˈdaɪəlɒɡ/", "The dialogue in this movie is excellent."),
    ("ending", "结局；结尾", "/ˈendɪŋ/", "The story has a happy ending."),
    ("document", "文件；证件；纪录片", "/ˈdɒkjument/", "Please bring all necessary documents."),
    ("plenty", "大量；充足", "/ˈplenti/", "There's plenty of food for everyone."),
    ("super", "超级的；极好的", "/ˈsuːpər/", "That's a super idea!"),
    ("intelligent", "聪明的；有才智的", "/ɪnˈtelɪdʒent/", "Dolphins are highly intelligent animals."),
    ("sense", "感觉；感官；意义；理智", "/sens/", "Common sense is not so common."),
    ("sadness", "悲伤；悲痛", "/ˈsædnəs/", "Her eyes showed deep sadness."),
    ("pain", "疼痛；痛苦", "/peɪn/", "I feel a pain in my back."),
    ("reflect", "反映；映出；反射", "/rɪˈflekt/", "The mirror reflects light beautifully."),
    ("perform", "表演；执行；履行", "/pərˈfɔːrm/", "She performed piano at the concert."),
    ("pity", "遗憾；怜悯；同情", "/ˈpiti/", "What a pity that you couldn't come!"),
    ("total", "总计的；全部的 n. 总数", "/ˈtəʊtl/", "What's the total cost?"),
    ("in total", "总共；合计", "/", "There are thirty students in total in our class."),
    ("master", "大师；能手；主人 v. 掌握", "/ˈmɑːster/", "It takes years to master a foreign language."),
    ("praise", "表扬；赞扬", "/preiz/", "The teacher praised him for his hard work."),
    ("recall", "回想起；回忆起", "/rɪˈkɔːl/", "I can't recall where I put my keys."),
    ("wound", "伤；伤口；创伤 v. 使(身体)受伤", "/wuːnd/", "The nurse cleaned his wound carefully."),
    ("painful", "令人痛苦的；令人疼痛的", "/ˈpeɪnfl/", "It was a painful decision to make."),
    ("World War II", "第二次世界大战", "/", "World War II lasted from 1939 to 1945."),
    ("Men in Black", "《黑衣人》（电影名）", "/", "Men in Black is a classic sci-fi movie."),
    ("Titanic", "《泰坦尼克号》(船名/电影名)", "/taɪˈtænik/", "Titanic sank on its maiden voyage."),
    ("sing along with", "跟着……唱；随着……一起唱", "/", "I like to sing along with my favorite songs."),
    ("prefer...to...", "比起……更喜欢……", "/", "I prefer reading to watching TV."),
    ("cheer up", "使振奋；使高兴起来", "/", "Cheer up! Everything will be fine."),
    ("in that case", "既然那样；假若那样", "/", "In that case, let's start early."),
    ("stick to", "坚持；固守", "/", "Stick to your plan and you'll succeed."),
    ("plenty of", "大量的；充足的", "/", "There are plenty of reasons to study hard."),
    ("shut off", "关闭；停止运转", "/", "Please shut off the lights when you leave."),
    ("once in a while", "偶尔；有时", "/", "Once in a while, I go hiking on weekends."),
    ("look up", "查找；(在词典、参考书中)查阅", "/", "If you don't know a word, look it up."),
    ("depend on", "取决于；依靠；依赖", "/", "Success depends on hard work and luck."),
    ("genre", "(音乐、文学、艺术的)类型；体裁", "/ʒɒnrə/", "What genre of music do you like best?"),

    # ========== Unit 10: You're supposed to shake hands. ==========
    ("custom", "习俗；风俗；习惯", "/ˈkʌstəm/", "Every country has its own customs."),
    ("bow", "鞠躬；弯腰 v. 鞠躬；低头", "/baʊ/", "In Japan, people bow to show respect."),
    ("kiss", "亲吻；接吻 v. 吻；亲吻", "/kis/", "She kissed her baby on the cheek."),
    ("greet", "问候；迎接", "/ɡriːt/", "Greet guests with a warm smile."),
    ("relaxed", "放松的；自在的", "/rɪˈlekst/", "I feel relaxed after vacation."),
    ("value", "重视；珍视 n. 价值", "/ˈvæljuː/", "We should value our friendship."),
    ("drop by", "顺便访问；随便拜访", "/", "Drop by my office anytime."),
    ("capital", "首都；省会；大写的；资本", "/ˈkæpɪtl/", "Beijing is the capital of China."),
    ("noon", "中午；正午", "/nuːn/", "Let's meet at noon for lunch."),
    ("mad", "生气的；疯的", "/mæd/", "Don't get mad — it was just a joke."),
    ("effort", "努力；精力；尽力", "/efərt/", "Putting in effort leads to success."),
    ("make an effort", "作出努力", "/", "You should make an effort to be on time."),
    ("get mad", "变得气愤；大动肝火", "/", "Don't get mad at small things."),
    ("after all", "毕竟；终究", "/", "Don't blame him — after all, he tried his best."),
    ("clean...off", "把……清除掉；擦除", "/", "Clean off the table before we leave."),
    ("table manners", "餐桌礼仪", "/", "Learn proper table manners before dining out."),
    ("take off", "脱下(衣服)；(飞机)起飞", "/", "Take off your shoes before entering."),
    ("stick...into", "把……插入", "/", "Don't stick your chopsticks into the rice."),
    ("find it + adj. + to do sth.", "发现做某事是……的", "/", "I find it interesting to learn about other cultures."),
    ("make plan(s) to do", "计划去做某事", "/", "We made plans to travel this summer."),
    ("be supposed to do", "应该做某事；被期望做某事", "/", "You're supposed to arrive on time."),
    ("be expected to do", "被期望/预期做某事", "/", "Students are expected to finish homework on time."),
    ("shake hands", "握手", "/", "In China, people shake hands when they meet."),
    ("after all", "毕竟；到底", "/", "After all, it's your first day here."),
    ("get mad", "生气；发火", "/", "Mom gets mad when I forget to clean my room."),
    ("make an effort to", "努力去(做)", "/", "Make an effort to understand others' feelings."),
    ("clean...off", "把……弄干净；清除", "/", "Clean the mud off your shoes."),
    ("go out of one's way to do", "特地(不怕麻烦地)做某事", "/", "She went out of her way to help me."),
    ("make...feel at home", "使(某人)感到宾至如归", "/", "They made me feel at home immediately."),
    ("to one's surprise", "令某人惊讶的是", "/", "To my surprise, he remembered my birthday."),
    ("show up", "露面；出现", "/", "He finally showed up an hour late."),
    ("by the way", "顺便说一下；顺便问一声", "/", "By the way, did you call mom?"),
    ("look forward to", "期待；盼望", "/", "I'm looking forward to your reply."),
    ("as you can see", "正如你所看到的", "/", "As you can see, the project is almost done."),
    ("be comfortable doing", "对做某事感到自在/舒服", "/", "I'm not comfortable speaking in front of crowds."),
    ("exchange", "交换；交流 n. 交换；交流", "/ɪksˈtʃeindʒ/", "Students exchange gifts at Christmas."),
    ("behavior", "行为；举止；表现", "/bɪˈheivjər/", "His behavior in class improved greatly."),
    ("manner", "方式；习惯；(pl.) 礼仪", "/ˈmænər/", "Table manners are important when dining out."),
    ("empty", "空的；空洞的 v. 倒空", "/ˈempti/", "The glass is empty — would you like a refill?"),
    ("basic", "基本的；基础的", "/ˈbeisik/", "These are basic manners everyone should know."),
    ("northern", "北方的；北部的", "/ˈnɔːrðern/", "Northern China is cold in winter."),
    ("coastal", "沿海的；海岸的", "/ˈkəʊstl/", "Many cities are located in coastal areas."),

    # ========== Unit 11: Sad movies make me cry. ==========
    ("rather", "相当；宁愿", "/ˈrɑːðər/", "It's rather cold today."),
    ("would rather", "宁愿；宁可；更愿意", "/", "I would rather stay home than go out."),
    ("drive", "迫使；驾驶 v. 驾驶；驱动", "/draiv/", "Sad movies drive me to cry."),
    ("lately", "最近；近来", "/ˈleɪtli/", "I haven't seen him lately."),
    ("friendship", "友谊；友情", "/ˈfrendʃip/", "True friendship is precious."),
    ("king", "国王；君主", "/kiŋ/", "The king ruled the country wisely."),
    ("power", "力量；权力；影响力", "/ˈpaʊər/", "Knowledge gives you power."),
    ("prime", "首要的；主要的", "/praim/", "My prime concern is your safety."),
    ("minister", "大臣；部长", "/ˈmɪnɪstər/", "The prime minister visited our school."),
    ("banker", "银行家", "/ˈbæŋkər/", "The banker manages millions of dollars."),
    ("fame", "名声；名誉", "/feim/", "He achieved fame at a young age."),
    ("pale", "苍白的；浅色的", "/peil/", "Her face turned pale with fear."),
    ("queen", "王后；女王", "/kwiːn/", "The queen wore a beautiful crown."),
    ("examine", "检查；检验；仔细查看", "/ɪɡˈzæmin/", "The doctor examined the patient carefully."),
    ("nor", "也不；也没有", "/nɔːr/", "Neither he nor I know the answer."),
    ("palace", "王宫；宫殿", "/pæləs/", "The palace is open to visitors."),
    ("wealth", "财富；富裕", "/welθ/", "Health is more important than wealth."),
    ("grey", "(天空)阴沉的；灰色的", "/ɡrei/", "The sky looks grey — it might rain."),
    ("lemon", "柠檬；柠檬色 adj. 柠檬色的", "/ˈlemən/", "Lemon juice tastes sour."),
    ("uncomfortable", "使人不舒服的；令人不舒适的", "/ʌnˈkʌmftəbl/", "These shoes feel uncomfortable."),
    ("weight", "重量；体重", "/weit/", "Watch your weight by eating healthy food."),
    ("shoulder", "肩；肩膀", "/ˈʃəʊldər/", "He patted me on the shoulder."),
    ("goal", "目标；球门；射门", "/ɡəʊl/", "Set a goal and work toward it."),
    ("coach", "教练；长途客车 v. 训练；指导", "/kəʊtʃ/", "Our basketball coach is strict but fair."),
    ("kick", "踢；踹 n. 踢", "/kɪk/", "Don't kick the ball into the neighbor's yard."),
    ("teammate", "同队队员；队友", "/ˈtiːmmeit/", "Trust your teammates on the field."),
    ("courage", "勇气；胆量", "/ˈkʌrɪdʒ/", "It takes courage to admit mistakes."),
    ("nod", "点头 v. 点头", "/nɒd/", "She nodded in agreement."),
    ("agreement", "同意；协定；协议", "/əˈɡriːmnt/", "They reached an agreement after discussion."),
    ("disappoint", "使失望", "/ˌdɪsəˈpɔɪnt/", "I'm sorry to disappoint you."),
    ("pull", "拉；拖 n. 拉", "/pʊl/", "Pull the door open gently."),
    ("disappointment", "失望；沮丧", "/ˌdɪsəˈpɔɪntmənt/", "To my disappointment, the concert was cancelled."),
    ("driver", "驾驶员；司机", "/ˈdraɪvər/", "The taxi driver knew the city well."),
    ("let...down", "使……失望/沮丧", "/", "Don't let your parents down."),
    ("kick sb. off", "开除某人；把某人踢出局", "/", "The coach kicked him off the team."),
    ("be hard on sb.", "对某人苛刻；对某人严厉", "/", "Don't be too hard on yourself."),
    ("rather than", "而不是；而非", "/", "I'd stay home rather than go out in the rain."),
    ("start with", "以……开始", "/", "Let's start with the basics."),
    ("drive sb. crazy", "使某人发疯/抓狂", "/", "This noise is driving me crazy!"),
    ("leave out", "遗漏；忽略；省去", "/", "Don't leave anyone out of the group photo."),
    ("pull together", "齐心协力；团结合作", "/", "If we pull together, we'll succeed."),
    ("to start with", "首先；起初", "/", "To start with, let's review what we learned."),
    ("be friends with", "与……友好；与……交朋友", "/", "I want to be friends with everyone in class."),
    ("on a heavy school working day", "在繁重的学校工作日", "/", "Even on a heavy school working day, she keeps smiling."),
    ("would rather do than do", "宁愿做某事而不愿做另一件事", "/", "I would rather read than watch TV."),
    ("make sb. + adj./do sth.", "使某人处于某种状态/使某人做某事", "/", "Good news makes me happy."),
    ("the more...the more...", "越……越……", "/", "The more you practice, the better you become."),
    ("search for", "寻找；搜寻", "/", "Search for answers before giving up."),
    ("even though", "即使；虽然", "/", "Even though it was late, she finished her homework."),
    ("return to", "回到；返回到", "/", "After graduation, return to your hometown to help."),
    ("palace", "宫殿；王宫", "/ˈpæləs/", "The palace was built hundreds of years ago."),

    # ========== Unit 12: Life is full of the unexpected. ==========
    ("unexpected", "出乎意料的；始料不及的", "/ˌʌnɪkˈspektɪd/", "The ending was totally unexpected."),
    ("by the time", "在……以前；到……的时候", "/", "By the time I got up, the bus had already left."),
    ("backpack", "背包", "/ˈbækpæk/", "Don't forget your backpack for school."),
    ("oversleep", "睡过头；睡得太久", "/ˌəʊvərˈsliːp/", "I overslept and missed the first class this morning."),
    ("ring", "(钟、铃等)响；(电话)铃响 n. 戒指；环形物", "/rɪŋ/", "The phone kept ringing but nobody answered."),
    ("give...a lift", "搭便车；让……搭车", "/", "Can you give me a lift to the station?"),
    ("block", "街区； n. 块； v. 阻挡", "/blɒk/", "Walk two blocks north and turn left."),
    ("worker", "工人；工作者", "/ˈwɜːrkər/", "Factory workers went on strike yesterday."),
    ("stare", "盯着看；凝视 v. 盯着看", "/ster/", "Don't stare at people — it's rude."),
    ("disbelief", "不信；怀疑", "/ˌdɪsbɪˈliːf/", "She stared in disbelief at the test results."),
    ("above", "在……上面； prep. 以上", "/əˈbʌv/", "Write your name above the line."),
    ("burn", "燃烧；烧毁 v. 着火；烫伤", "/bɜːrn/", "Don't burn the candle at both ends."),
    ("alive", "活着的；有生气的", "/əˈlaɪv/", "Fortunately, everyone was alive after the accident."),
    ("airport", "机场；航空港", "/ˈerpɔːrt/", "We need to get to the airport by six."),
    ("till", "直到；直到……之时", "/tɪl/", "I'll wait till you come back."),
    ("west", "西方的；向西的 adv. 向西 n. 西方", "/west/", "The sun sets in the west."),
    ("cream", "奶油；乳脂；膏", "/kriːm/", "I'd like some ice cream, please."),
    ("workday", "工作日", "/ˈwɜːrkdei/", "Most people work five days per week."),
    ("pie", "果馅派；馅饼", "/pai/", "My grandma makes delicious apple pies."),
    ("bean", "豆；豆科植物", "/biːn/", "Green beans are healthy vegetables."),
    ("market", "市场；集市", "/ˈmɑːrkɪt/", "Let's go to the farmers' market this weekend."),
    ("show up", "露面；到场", "/", "When did he finally show up?"),
    ("by the end of", "到……末为止", "/", "By the end of this year, I'll have learned 2000 words."),
    ("sell out", "卖完；售罄", "/", "The tickets sold out within minutes."),
    ("costume", "服装；化装服", "/ˈkɒstjuːm/", "She wore a beautiful costume to the party."),
    ("embarrassed", "尴尬的；窘迫的", "/ɪmˈbærəst/", "I felt embarrassed when I forgot his name."),
    ("cancel", "取消；终止", "/ˈkænsl/", "They had to cancel the flight due to bad weather."),
    ("officer", "军官；官员；警官", "/ˈɒfɪsər/", "A police officer directed the traffic."),
    ("believable", "可信的；可以相信的", "/bɪˈliːvəbl/", "His explanation doesn't sound believable."),
    ("disappear", "消失；不见；灭绝", "/ˌdɪsəˈpɪər/", "The magician made the rabbit disappear."),
    ("hoax", "骗局；恶作剧；玩笑", "/həʊks/", "The alien sighting turned out to be a hoax."),
    ("discovery", "发现；被发现的事物", "/dɪˈskʌvəri/", "Penicillin was a major medical discovery."),
    ("maiden", "未婚女子；(船的)首次(航行)", "/ˈmeidn/", "The Titanic sank on its maiden voyage."),
    ("Italy", "意大利", "/ˈɪtəli/", "Rome is the capital of Italy."),
    ("announce", "宣布；宣告", "/əˈnaʊns/", "The teacher announced the test results."),
    ("spaghetti", "意大利面条", "/spəˈɡeti/", "Spaghetti is my favorite Italian food."),
    ("play tricks on", "搞恶作剧；诈骗；开玩笑", "/", "Don't play tricks on your little sister."),
    ("get dressed", "穿好衣服", "/", "Get dressed quickly — we're leaving soon."),
    ("rush out", "冲出；匆忙离开", "/", "Everyone rushed out of the building when the alarm rang."),
    ("turn into", "变成；成为", "/", "The caterpillar turns into a butterfly."),
    ("end up", "最终成为；结果", "/", "If you keep procrastinating, you'll end up failing."),
    ("stay up", "熬夜；不睡觉", "/", "Don't stay up too late — you have school tomorrow."),
    ("lose weight", "减肥", "/", "Exercise is a healthy way to lose weight."),
    ("get married", "结婚", "/", "My cousin is getting married next month."),
    ("fool around", "闲荡；游手好闲；胡闹", "/", "Stop fooling around and get to work."),
    ("go off", "(闹钟)响起；(电)中断；离开", "/", "My alarm didn't go off this morning."),
    ("break down", "出故障；分解；(身体)垮掉", "/", "Our car broke down on the highway."),
    ("miss the bus", "错过公交车", "/", "I woke up late and missed the bus."),
    ("line up", "排队；(使)排成行", "/", "Line up and wait your turn."),
    ("play jokes on", "开……的玩笑；捉弄", "/", "He likes to play jokes on his friends."),
    ("call off", "取消；撤销", "/", "They called off the match due to rain."),
    ("go into", "进入；从事；调查", "/", "Let's go into details about this problem."),
    ("April Fool's Day", "愚人节", "/", "April Fool's Day is on April 1st."),
    ("unexpectedly", "出乎意料地；意外地", "/ˌʌnɪkˈspektɪdli/", "He unexpectedly showed up at the party."),

    # ========== Unit 13: We're trying to save the earth! ==========
    ("litter", "垃圾；废弃物 v. 乱扔", "/ˈlɪtər/", "Don't litter — put trash in the bin."),
    ("bottom", "底部；最下部", "/ˈbɒtəm/", "Sign your name at the bottom of the page."),
    ("fisherman", "渔民；钓鱼的人", "/ˈfɪʃərmən/", "The fisherman caught a big fish this morning."),
    ("coal", "煤；煤块", "/kəʊl/", "Burning coal produces pollution."),
    ("ugly", "丑陋的；难看的", "/ˈʌɡli/", "Pollution makes cities ugly and unhealthy."),
    ("advantage", "优点；有利条件", "/ədˈvɑːntɪdʒ/", "Every advantage has its disadvantage."),
    ("cost", "费用；花费；代价 v. 花费", "/kɒst/", "The cost of living in big cities is high."),
    ("wooden", "木制的；木头的", "/ˈwʊdn/", "This is a wooden desk made of oak."),
    ("plastic", "塑料；塑料的；塑胶", "/ˈplæstik/", "Try to reduce using plastic bags."),
    ("takeaway", "外卖食物 n. 外卖的", "/ˈteikəwei/", "I ordered takeaway for dinner tonight."),
    ("bin", "箱；桶；垃圾桶", "/bɪn/", "Throw the garbage in the bin."),
    ("shark", "鲨鱼", "/ʃɑːrk/", "Great white sharks are dangerous marine animals."),
    ("fin", "(鱼)鳍；(飞机)翼", "/fɪn/", "Shark fin soup is controversial."),
    ("cruel", "残忍的；残酷的", "/ˈkruːəl/", "It's cruel to hurt animals."),
    ("harmful", "有害的；造成伤害的", "/ˈhɑːrmfl/", "Smoking is harmful to your lungs."),
    ("ecosystem", "生态系统", "/ˈiːkəʊsɪstəm/", "Ocean ecosystems are under threat."),
    ("industry", "工业；行业；产业", "/ˈɪndəstri/", "The car industry is developing rapidly."),
    ("law", "法律；法规；法学", "/lɔː/", "Everyone should obey the law."),
    ("scientific", "科学的；关于科学的", "/ˌsaɪənˈtɪfɪk/", "We need scientific methods to solve this problem."),
    ("afford", "承担得起(后果)；买得起", "/əˈfɔːrd/", "I can't afford such an expensive phone."),
    ("reusable", "可重复使用的；可再次使用的", "/ˌriːˈuːzəbl/", "Use reusable bags instead of plastic ones."),
    ("transportation", "运输业；交通运输", "/ˌtrænspɔːrˈteɪʃn/", "Public transportation reduces air pollution."),
    ("recycle", "回收利用；再利用", "/ˌriːˈsaɪkl/", "Recycle paper and plastic to protect the environment."),
    ("napkin", "餐巾纸；餐巾", "/ˈnæpkɪn/", "Use cloth napkins instead of paper ones."),
    ("throw away", "扔掉；丢弃", "/", "Don't throw away old clothes — donate them."),
    ("put sth. to good use", "好好利用某物", "/", "We should put waste materials to good use."),
    ("pull...down", "拆下；摧毁", "/", "They pulled down the old building."),
    ("upside down", "上下颠倒；倒转", "/", "Hold the picture upside down — it looks funny."),
    ("bring back", "恢复；使想起；归还", "/", "The old songs bring back memories."),
    ("cut down", "砍倒；削减；删减", "/", "Stop cutting down trees in the forest."),
    ("environmental protection", "环境保护", "/", "Environmental protection is everyone's responsibility."),
    ("pay for", "为……付出代价；付款", "/", "We have to pay for our actions against nature."),
    ("take action", "采取行动", "/", "It's time to take action against pollution."),
    ("put good use to", "好好利用；充分利用", "/", "Put your free time to good use by reading."),
    ("set up", "建立；开办；设立", "/", "They set up a recycling program in the community."),
    ("known for", "因……而闻名；以……著称", "/", "This area is known for its beautiful scenery."),
    ("build...out of", "用……建造/搭建", "/", "He built a birdhouse out of recycled materials."),
    ("pollution", "污染", "/pəˈluːʃn/", "Air pollution is a serious problem in big cities."),
    ("environment", "环境", "/ɪnˈvaɪrənmənt/", "We should protect our natural environment."),
    ("protect", "保护；防护", "/prəˈtekt/", "It's our duty to protect endangered animals."),
    ("endangered", "濒危的；濒临灭绝的", "/ɪnˈdeɪndʒərd/", "Pandas are endangered animals that need protection."),
    ("save", "挽救；节约；保存", "/seiv/", "We should save water by taking shorter showers."),
    ("planet", "行星", "/ˈplænɪt/", "Earth is the third planet from the sun."),
    ("ocean", "海洋；大海", "/ˈəʊʃn/", "Ocean covers most of the Earth's surface."),
    ("reduce", "减少；缩小", "/rɪˈdjuːs/", "We should reduce plastic waste."),
    ("reuse", "重新使用；重复使用", "/ˌriːˈjuːz/", "Reuse old bottles instead of buying new ones."),
    ("waste", "浪费；废弃物", "/weist/", "Don't waste food — there are hungry people in the world."),

    # ========== Unit 14: I remember meeting all of you in Grade 7. ==========
    ("survey", "调查", "/sɜːrvei/", "We conducted a survey about students' hobbies."),
    ("standard", "标准；水平；标准的", "/ˈstændərd/", "Set a high standard for yourself."),
    ("row", "一排；一列；划船 v. 划(船)", "/rəʊ/", "Sit in the front row so you can see clearly."),
    ("keyboard", "键盘；电子琴", "/ˈkiːbɔːrd/", "Type your answer on the keyboard."),
    ("method", "方法；办法；措施", "/ˈmeθəd/", "This method works better than the old one."),
    ("instruction", "指示；命令；说明；教导", "/ɪnˈstrʌkʃn/", "Follow the instructions carefully."),
    ("double", "两倍的；加倍的 v. 加倍", "/ˈdʌbl/", "The population doubled in twenty years."),
    ("shall", "将要；将会；应该", "/ʃæl/", "Shall we begin the meeting?"),
    ("look back at", "回首；回顾；回头看", "/", "Look back at how far you've come."),
    ("overcome", "克服；战胜", "/ˌəʊvərˈkʌm/", "You need to overcome your fear of public speaking."),
    ("graduate", "毕业；获得学位", "/ˈɡrædʒueit/", "She will graduate from high school next June."),
    ("keep cool", "保持冷静；保持头脑清醒", "/", "Keep cool during the exam."),
    ("caring", "关怀的；体贴的", "/ˈkerɪŋ/", "She has a caring personality."),
    ("ours", "我们的(所有物)", "/aʊrz/", "This classroom is ours."),
    ("senior", "级别较高的；年长的", "/ˈsiːniər/", "He is a senior high school student now."),
    ("level", "水平；级别；层次", "/ˈlevl/", "Your English level has improved greatly."),
    ("degree", "学位；度数；程度", "/dɪˈɡriː/", "She earned a degree in computer science."),
    ("manager", "经理；经营者", "/ˈmænɪdʒər/", "My father is a manager at a bank."),
    ("gentleman", "绅士；先生", "/ˈdʒentlmən/", "He is a true gentleman."),
    ("task", "任务；工作；作业", "/tɑːsk/", "Completing the task took longer than expected."),
    ("wing", "翅膀；翼", "/wɪŋ/", "The bird spread its wings and flew away."),
    ("congratulate", "祝贺", "/kənˈɡrætʃuleit/", "Congratulations on your graduation!"),
    ("thirsty", "口渴的；渴望的", "/ˈθɜːrsti/", "I'm thirsty — can I have some water?"),
    ("thankful", "感激的；感谢的", "/ˈθæŋkfl/", "I'm thankful for everyone who helped me."),
    ("responsible", "负责任的；有责任心的", "/rɪˈspɒnsəbl/", "Be responsible for your own actions."),
    ("separate", "分离；分开 v.(使)分离", "/ˈsepəreit/", "The twins were separated at birth."),
    ("set out", "出发；动身；着手做", "/", "We set out early in the morning."),
    ("ahead of", "在……前面", "/", "Finish your work ahead of schedule."),
    ("along with", "连同；除……以外(还)", "/", "I went to the party along with my friends."),
    ("responsible for", "对……负责；是……的原因", "/", "Each student is responsible for their own homework."),
    ("separate from", "与……分离；与……分开", "/", "Boys and girls sit separate from each other."),
    ("believe in", "信任；信赖；相信……的存在", "/", "Believe in yourself and you'll succeed."),
    ("first of all", "首先", "/", "First of all, let me introduce myself."),
    ("be thirsty for", "渴求；渴望", "/", "Young people should be thirsty for knowledge."),
    ("be thankful to sb.", "对某人感激", "/", "Be thankful to teachers who guided you."),
    ("ahead of", "在……前面；提前", "/", "We finished the project ahead of time."),
    ("along with", "和……一起；连同", "/", "She brought her dog along with her."),
    ("be responsible for", "对……负责；承担……的责任", "/", "Who is responsible for this mistake?"),
    ("separate from", "与……分开；从……分离", "/", "Oil separates from water."),
    ("set out on a new journey", "踏上新的征程/旅程", "/", "After graduation, set out on a new journey."),
    ("give wings to dreams", "给梦想插上翅膀", "/", "Education gives wings to dreams."),
    ("be full of energy for the future", "对未来充满能量/活力", "/", "Young people should be full of energy for the future."),
    ("be hungry for knowledge", "渴求知识", "/", "Students should be hungry for knowledge."),
    ("lead...to", "导致；引领……走向", "/", "Hard work leads to success."),
    ("be thankful to the people who have helped and supported us", "感谢那些曾经帮助和支持过我们的人", "/", "Always be thankful to the people who have helped and supported us."),
    ("remember doing", "记得做过某事", "/", "I remember meeting him at the party last year."),
    ("look forward to", "期待；盼望", "/", "We all look forward to bright futures."),
    ("hope for", "希望得到；盼望", "/", "Hope for the best but prepare for the worst."),
    ("prepare for", "为……做准备", "/", "Prepare for challenges ahead."),
    ("graduate from", "从……毕业", "/", "She graduated from Peking University."),
    ("be full of", "充满；装满", "/", "The room was full of students."),
    ("congratulation", "祝贺；贺词(常用复数)", "/kənˌɡrætʃuˈleɪʃn/", "Congratulations on winning the competition!"),
    ("ceremony", "典礼；仪式", "/ˈserəmoʊni/", "The graduation ceremony was held in the auditorium."),
    ("auditorium", "礼堂；会堂；大剧院", "/ˌɔːdɪˈtɔːriəm/", "The auditorium can hold two thousand people."),
    ("forever", "永远；长久", "/fərˈevər/", "Friends forever!"),
    ("gentle", "温柔的；轻柔的", "/ˈdʒentl/", "She spoke in a gentle voice."),
    ("overcome", "克服；战胜", "/ˌəʊvərˈkʌm/", "She managed to overcome her shyness."),
    ("graduate", "毕业；(大学)毕业生", "/ˈɡrædʒueit/", "High school graduates face new challenges."),
    ("responsibility", "责任；责任心", "/rɪˌspɒnsəˈbɪləti/", "With freedom comes responsibility."),
    ("adult", "成年人；成人的", "/ˈædʌlt/", "When you become an adult, you must be independent."),
    ("journey", "旅行；行程；(人生)旅程", "/ˈdʒɜːrni/", "Life is a journey full of challenges."),
    ("achievement", "成就；成绩", "/əˈtʃiːvmənt/", "Winning the prize was a great achievement."),
    ("excellent", "极好的；优秀的", "/ˈeksələnt/", "She is an excellent student who gets top grades."),
    ("encourage", "鼓励；激励", "/ɪnˈkʌrɪdʒ/", "Teachers encourage students to ask questions."),
    ("success", "成功；成就", "/səkˈses/", "Success comes from hard work and persistence."),
    ("challenge", "挑战；考验", "/ˈtʃælɪndʒ/", "Every challenge is an opportunity to grow."),

    # ========== 补充词汇：九年级高频核心词 ==========
    # Unit 1 补充
    ("vocabulary", "词汇；词汇量", "/vəˈkæbjələri/", "Reading books helps expand your vocabulary."),
    ("increase", "增加；增长；提高", "/ɪnˈkriːs/", "You need to increase your reading speed."),
    ("pronunciation", "发音；读音", "/prəˌnʌnsiˈeɪʃn/", "Practice pronunciation every day."),
    ("quickly", "快速地；迅速地", "/ˈkwikli/", "He answered the question quickly."),
    ("slowly", "慢慢地；缓慢地", "/ˈsləʊli/", "Please speak slowly so I can understand."),
    ("loudly", "大声地；响亮地", "/ˈlaʊdli/", "Don't talk loudly in the library."),
    ("clearly", "清楚地；清晰地", "/ˈklɪrli/", "Please explain it clearly."),
    ("correctly", "正确地", "/kəˈrektli/", "She spelled all words correctly."),
    ("fluently", "流利地；流畅地", "/ˈfluːəntli/", "He speaks English fluently now."),
    ("practice", "练习；实践 n. 练习", "/ˈpræktis/", "Daily practice is essential for learning."),
    ("skill", "技能；技巧", "/skil/", "Communication is an important skill."),
    ("strategy", "策略；方法；战略", "/ˈstrætədʒi/", "Find a learning strategy that works for you."),
    ("effective", "有效的；起作用的", "/ɪˈfektiv/", "This is a very effective study method."),
    ("efficient", "效率高的；有能力的", "/ɪˈfɪʃnt/", "An efficient student uses time well."),
    ("progress", "进步；进展 v. 进展；前进", "/ˈprəʊɡres/", "You've made great progress this term."),
    ("improve", "改进；改善；进步", "/ɪmˈpruːv/", "I want to improve my English."),
    ("mistake", "错误；过失", "/mɪˈsteɪk/", "Everyone makes mistakes — learn from them."),
    ("difficult", "困难的；难的", "/ˈdɪfɪkəlt/", "This math problem is quite difficult."),
    ("easy", "容易的；简单的", "/ˈiːzi/", "The test was easier than expected."),
    ("boring", "无聊的；令人厌烦的", "/ˈbɔːrɪŋ/", "The lecture was so boring that I fell asleep."),
    ("interesting", "有趣的；有意思的", "/ˈɪntrəstɪŋ/", "This book is very interesting."),
    ("useful", "有用的；有益的", "/ˈjuːsfl/", "English is useful for your future career."),
    ("important", "重要的；重大的", "/ɪmˈpɔːrtnt/", "Health is more important than wealth."),
    ("necessary", "必要的；必需的", "/ˈnesəseri/", "It's necessary to review lessons regularly."),
    ("possible", "可能的；可能存在的", "/ˈpɒsəbl/", "Do your best to make everything possible."),
    ("impossible", "不可能的；办不到的", "/ɪmˈpɒsəbl/", "Nothing is impossible if you try hard enough."),
    ("successful", "成功的；有成就的", "/səkˈsesfl/", "A successful person never gives up."),
    ("failure", "失败；失败的人(或事)", "/ˈfeiljər/", "Failure is the mother of success."),

    # Unit 2 补充
    ("traditional", "传统的；惯例的", "/trəˈdɪʃənl/", "Chinese traditional festivals are colorful."),
    ("celebrate", "庆祝；庆贺", "/ˈselibreit/", "How do you celebrate Spring Festival?"),
    ("festival", "节日；庆典", "/ˈfestivl/", "Which festival do you like best?"),
    ("relative", "亲属；亲戚", "/ˈrelətiv/", "We visit relatives during holidays."),
    ("ancestor", "祖先；祖宗", "/ˈænsestər/", "We honor our ancestors on Tomb-sweeping Day."),
    ("midnight", "午夜；子夜", "/ˈmɪdnait/", "Fireworks go off at midnight on New Year's Eve."),
    ("firework", "烟花；焰火", "/ˈfaɪərwɜːrk/", "Fireworks light up the night sky."),
    ("turkey", "火鸡", "/ˈtɜːrki/", "Americans eat turkey on Thanksgiving Day."),
    ("Thanksgiving", "感恩节", "/θæŋksˈɡɪvɪŋ/", "Thanksgiving is a big American holiday."),
    ("Easter", "复活节", "/iːstər/", "Children hunt for eggs at Easter."),
    ("Halloween", "万圣节前夕", "/ˌhæləʊˈiːn/", "Kids dress up and trick-or-treat on Halloween."),
    ("Santa Claus", "圣诞老人", "/ˌsæntə ˈklɔːz/", "Santa Claus brings gifts to children on Christmas Eve."),
    ("gift", "礼物；天赋", "/ɡift/", "What gift did you receive for your birthday?"),
    ("wrap", "包裹；包装 v. 包；裹", "/ræp/", "Wrap the present nicely before giving it."),
    ("decorate", "装饰；布置", "/ˈdekəreit/", "People decorate their homes before New Year."),
    ("lantern", "灯笼；提灯", "/ˈlæntərn/", "Red lanternes are hung during festivals."),
    ("sweet", "甜的；糖果 adj. 甜的 n. 糖果", "/swiːt/", "Mooncakes taste sweet and delicious."),
    ("delicious", "美味的；可口的", "/dɪˈlɪʃəs/", "The food at the restaurant was delicious."),
    ("taste", "味道；品味 v. 尝起来", "/teist/", "This cake tastes wonderful."),
    ("smell", "气味；嗅觉 v. 闻起来", "/smel/", "The flowers smell sweet in spring."),
    ("sound", "声音；听起来 v. 听起来", "/saʊnd/", "That sounds like a great idea."),
    ("feel", "感觉；触觉 v. 感觉；觉得", "/fiːl/", "I feel happy when I'm with friends."),

    # Unit 3 补充
    ("information", "信息；资料", "/ˌɪnfərˈmeɪʃn/", "Can you give me some information about the museum?"),
    ("restroom", "(美)洗手间", "/ˈrest ruːm/", "Excuse me, where is the nearest restroom?"),
    ("toilet", "厕所；坐便器", "/ˈtɔɪlət/", "Where is the public toilet?"),
    ("bathroom", "浴室；卫生间", "/ˈbɑːθruːm/", "Clean the bathroom after using it."),
    ("elevator", "电梯；升降机", "/ˈelɪveɪtər/", "Take the elevator to the tenth floor."),
    ("escalator", "自动扶梯", "/ˈeskəleɪtər/", "Let's take the escalator up to the second floor."),
    ("subway", "地铁", "/ˈsʌbwei/", "The subway is the fastest way to travel in Beijing."),
    ("station", "车站；站", "/ˈsteɪʃn/", "Let's meet at the bus station."),
    ("platform", "站台；平台；月台", "/ˈplætfɔːrm/", "The train is waiting at platform 3."),
    ("ticket", "票；入场券", "/ˈtɪkit/", "I bought two tickets for the movie."),
    ("passport", "护照", "/ˈpɑːspɔːrt/", "Don't forget your passport when traveling abroad."),
    ("exchange", "交换；兑换 n. 交易所", "/ɪksˈtʃeindʒ/", "Where can I exchange money?"),
    ("currency", "货币；通货", "/ˈkʌrənsi/", "What currency do they use in Japan?"),
    ("foreign", "外国的；外来的", "/ˈfɔːrən/", "She can speak three foreign languages."),
    ("language", "语言", "/ˈlæŋɡwɪdʒ/", "English is a global language."),
    ("communicate", "交流；沟通", "/kəˈmjuːnikeit/", "Learning English helps us communicate with the world."),
    ("polite", "有礼貌的；客气的", "/pəˈlaɪt/", "Be polite when asking for directions."),
    ("rudely", "粗鲁地；无礼地", "/ˈruːdli/", "Don't speak rudely to elders."),
    ("directly", "直接地；径直地", "/daɪˈrektili/", "Go directly down this road."),
    ("indirect", "间接的；迂回的", "/ˌɪndəˈrekt/", "Indirect questions sound more polite."),
    ("request", "请求；要求", "/rɪˈkwest/", "They made a request for help."),
    ("suggest", "建议；提议", "/səˈdʒest/", "I suggest we go by taxi."),
    ("recommend", "推荐；介绍", "/ˌrekəˈmend/", "Can you recommend a good restaurant nearby?"),
    ("fascinating", "迷人的；极好的", "/ˈfæsɪneɪtɪŋ/", "The history of this city is fascinating."),

    # Unit 4 补充
    ("appearance", "外貌；外观；出现", "/əˈpiərəns/", "Don't judge people by their appearance."),
    ("personality", "个性；性格", "/ˌpɜːrsəˈnæləti/", "She has a warm and friendly personality."),
    ("character", "性格；品质；角色", "/ˈkærəktər/", "Honesty is an important character trait."),
    ("behavior", "行为；举止；表现", "/bɪˈheivjər/", "His behavior improved after the talk."),
    ("habit", "习惯；习性", "/ˈhæbit/", "Reading before bed is a good habit."),
    ("change", "改变；变化 n. 变化", "/tʃeindʒ/", "People change as they grow older."),
    ("changeable", "易变的；可变的", "/ˈtʃeindʒəbl/", "Weather here is changeable in spring."),
    ("childhood", "童年；幼年时期", "/ˈtʃaɪldhʊd/", "He had a happy childhood in the countryside."),
    ("teenage", "青少年时期的；十几岁的", "/ˈtiːneidʒ/", "Teenage years are full of changes."),
    ("adult", "成年人", "/ˈædʌlt/", "When I become an adult, I want to be a teacher."),
    ("grow", "生长；成长；种植", "/ɡroʊ/", "Children grow fast during puberty."),
    ("growth", "增长；成长；发展", "/ɡroʊθ/", "Economic growth has slowed recently."),
    ("develop", "发展；开发；成长", "/dɪˈveləp/", "Countries develop at different speeds."),
    ("development", "发展；发育；开发", "/dɪˈveləpmənt/", "Sustainable development protects the environment."),
    ("confidence", "自信心；信任", "/ˈkɒnfɪdəns/", "Build confidence by practicing speaking English."),
    ("confident", "自信的；确信的", "/ˈkɒnfɪdənt/", "Be confident when you take the exam."),
    ("shyness", "害羞；胆怯", "/ˈʃaɪnəs/", "Overcoming shyness takes time."),
    ("outgoing", "外向的；友好的", "/aʊtˈɡoʊɪŋ/", "She is outgoing and makes friends easily."),
    ("serious", "严肃的；认真的；严重的", "/ˈsɪriəs/", "Are you serious about learning English?"),
    ("strict", "严格的；严厉的", "/strɪkt/", "My parents are strict with my studies."),
    ("excellent", "优秀的；杰出的", "/ˈeksələnt/", "His work is always excellent."),
    ("ordinary", "普通的；平常的", "/ˈɔːrdneri/", "He looks like an ordinary boy but has great talent."),
    ("special", "特别的；特殊的", "/ˈspeʃl/", "Today is a special day for me."),
    ("especially", "尤其；特别", "/ɪˈspeʃli/", "I love fruits, especially apples."),
    ("particular", "特定的；特指的", "/pərˈtikjələr/", "Is there any particular reason for your choice?"),
    ("exactly", "确切地；恰恰", "/ɪɡˈzæktli/", "That's exactly what I meant."),
    ("actually", "实际上；事实上", "/ˈæktʃuəli/", "Actually, I don't agree with you."),

    # Unit 5 补充
    ("material", "材料；原料", "/məˈtɪəriəl/", "What material is this shirt made of?"),
    ("produce", "生产；制造", "/prəˈdjuːs/", "China produces many products for export."),
    ("product", "产品；制品", "/ˈprɒdʌkt/", "Check the label to see where this product was made."),
    ("factory", "工厂；制造厂", "/ˈfæktri/", "My uncle works in a car factory."),
    ("industry", "工业；产业", "/ˈɪndəstri/", "The IT industry is growing rapidly."),
    ("agriculture", "农业；农学", "/ˈæɡrɪkʌltʃər/", "Agriculture is the foundation of the economy."),
    ("process", "过程；工序；加工", "/ˈprəʊses/", "Making paper is a complex process."),
    ("pack", "打包；包装；塞满", "/pæk/", "Pack your bags carefully for the trip."),
    ("brand", "品牌；商标", "/brænd/", "Which brand of phone do you prefer?"),
    ("local", "当地的；本地的", "/ˈloʊkl/", "Support local businesses and farmers."),
    ("global", "全球的；总体的", "/ˈɡloʊbl/", "Global warming is a serious problem."),
    ("environment", "环境；周围状况", "/ɪnˈvaɪrənmənt/", "We should protect the environment."),
    ("environmental", "环境的；有关环境的", "/ɪnˌvaɪrənˈmentl/", "Environmental issues concern everyone."),
    ("pollution", "污染", "/pəˈluːʃn/", "Air pollution affects everyone's health."),
    ("protect", "保护；防护", "/prəˈtekt/", "We must protect endangered animals."),
    ("nature", "自然；自然界；本性", "/ˈneɪtʃər/", "Humans should live in harmony with nature."),
    ("natural", "自然的；天生的", "/ˈnætʃrəl/", "Natural resources are limited."),
    ("resource", "资源；财力", "/ˈriːsɔːrs/", "Water is a precious resource."),
    ("energy", "能源；能量；精力", "/ˈenərdʒi/", "Solar energy is clean and renewable."),
    ("recycle", "回收利用", "/ˌriːˈsaɪkl/", "Recycle bottles and cans to reduce waste."),
    ("throw", "扔；投掷", "/θroʊ/", "Don't throw trash on the ground."),
    ("waste", "浪费；废弃物", "/weist/", "Food waste is a big problem worldwide."),
    ("save", "节约；挽救；保存", "/seiv/", "Save water by taking shorter showers."),
    ("earth", "地球；泥土", "/ɜːrθ/", "Earth is our only home — protect it."),
    ("air", "空气；大气", "/er/", "Fresh air is essential for health."),
    ("water", "水；水域", "/ˈwɔːtər/", "Drink plenty of water every day."),
    ("soil", "土壤；土地；国土", "/sɔɪl/", "Good soil is important for farming."),
    ("plant", "植物；工厂 v. 种植", "/plænt/", "Planting trees helps clean the air."),

    # Unit 6 补充
    ("invent", "发明；创造", "/ɪnˈvent/", "Who invented the telephone?"),
    ("invention", "发明；发明物", "/ɪnˈvenʃn/", "The invention of the Internet changed the world."),
    ("inventor", "发明者；创造者", "/ɪnˈventər/", "Edison was one of the greatest inventors."),
    ("discover", "发现；发觉", "/dɪˈskʌvər/", "Columbus discovered America in 1492."),
    ("discovery", "发现；被发现的事物", "/dɪˈskʌvəri/", "Penicillin was an accidental discovery."),
    ("accident", "事故；意外；偶然", "/ˈæksɪdənt/", "He had a car accident yesterday."),
    ("accidental", "意外的；偶然的", "/ˌæksɪˈdentl/", "The meeting was accidental — we didn't plan it."),
    ("create", "创造；创作；创建", "/kriˈeɪt/", "Artists create beautiful works."),
    ("creativity", "创造力；创造性", "/ˌkriːeiˈtɪvəti/", "Education should encourage creativity."),
    ("creative", "创造性的；有创意的", "/kriˈeɪtɪv/", "She came up with a creative solution."),
    ("design", "设计；构思 n. 设计图", "/dɪˈzain/", "Who designed this building?"),
    ("technology", "技术；科技；工艺", "/tekˈnɒlədʒi/", "Modern technology makes life easier."),
    ("technological", "技术的；科技的", "/ˌteknəˈlɒdʒɪkl/", "Technological advances change society quickly."),
    ("modern", "现代的；近代的", "/ˈmɒdern/", "We live in a modern city with tall buildings."),
    ("ancient", "古代的；古老的", "/ˈeɪnʃənt/", "The Great Wall is an ancient wonder."),
    ("history", "历史；历史学", "/ˈhɪstri/", "Studying history helps understand the present."),
    ("historical", "历史的；有关历史的", "/hɪˈstɒrɪkl/", "Xi'an is a famous historical city."),
    ("science", "科学；自然科学", "/ˈsaɪəns/", "Science helps explain how the world works."),
    ("scientific", "科学的；系统的", "/ˌsaɪənˈtɪfɪk/", "Use scientific methods to solve problems."),
    ("experiment", "实验；试验", "/ɪkˈsperɪment/", "Students conduct experiments in chemistry lab."),
    ("laboratory", "实验室", "/ləˈbɒrətri/", "Chemistry experiments are done in the laboratory."),
    ("research", "研究；探讨", "/rɪˈsɜːtʃ/", "Scientists are researching new medicines."),
    ("result", "结果；后果", "/rɪˈzʌlt/", "The results of the experiment were surprising."),
    ("conclude", "推断出；得出结论", "/kənˈkluːd/", "From this data, we conclude that..."),
    ("conclusion", "结论；结束", "/kənˈkluːʒn/", "In conclusion, practice is key to success."),
    ("evidence", "证据；证明", "/ˈevɪdəns/", "There is no evidence to support his claim."),

    # Unit 7 补充
    ("allow", "允许；准许", "/əˈlaʊ/", "Parents don't allow smoking at home."),
    ("permission", "许可；允许；批准", "/pərˈmɪʃn/", "You need permission to enter this area."),
    ("choose", "选择；挑选", "/tʃuːz/", "Choose your friends wisely."),
    ("choice", "选择；抉择", "/tʃɔɪs/", "Making the right choice is not always easy."),
    ("decide", "决定；决心", "/dɪˈsaid/", "Have you decided which course to take?"),
    ("decision", "决定；决心", "/dɪˈsɪʒn/", "It was a difficult decision to make."),
    ("opportunity", "机会；时机", "/ˌɑːpərˈtuːnəti/", "This is a great opportunity to learn something new."),
    ("possibility", "可能；可能性", "/ˌpɒsəˈbɪləti/", "There's a possibility of rain today."),
    ("possible", "可能的", "/ˈpɒsəbl/", "Is it possible to finish this by Friday?"),
    ("impossible", "不可能的", "/ɪmˈpɒsəbl/", "Nothing is impossible if you believe in yourself."),
    ("responsibility", "责任；责任心", "/rɪˌspɒnsəˈbɪləti/", "Taking responsibility shows maturity."),
    ("responsible", "负责的；可靠的", "/rɪˈspɒnsəbl/", "Be responsible for your own actions."),
    ("independence", "独立；自主", "/ˌɪndɪˈpendəns/", "Teenagers want more independence from parents."),
    ("independent", "独立的；自主的", "/ˌɪndɪˈpendənt/", "Learn to be independent as you grow up."),
    ("freedom", "自由；自由权", "/ˈfriːdəm/", "Freedom comes with responsibility."),
    ("rule", "规则；规定 v. 统治；支配", "/ruːl/", "Follow the rules of the school."),
    ("regulation", "规章；条例；管理", "/ˌreɡjuˈleiʃn/", "Traffic regulations keep roads safe."),
    ("law", "法律；法规", "/lɔː/", "Breaking the law has serious consequences."),
    ("obey", "服从；遵守", "/əˈbei/", "Citizens should obey the law."),
    (" disobey", "不服从；违抗", "/ˌdɪsəˈbei/", "Don't disobey school rules."),

    # Unit 8 补充
    ("belong", "属于；应被放在某处", "/bɪˈlɒŋ/", "This book belongs to the library."),
    ("owner", "主人；物主", "/ˈoʊnər/", "Who is the owner of this car?"),
    ("own", "自己的 v. 拥有", "/oʊn/", "I have my own room now."),
    ("possibly", "可能地；也许", "/ˈpɒsəbli/", "He might possibly come later."),
    ("probably", "大概；或许；很可能", "/ˈprɒbəbli/", "It will probably rain tomorrow."),
    ("certainly", "当然；必定", "/ˈsɜːrtnli/", "I'll certainly help you."),
    ("sure", "确定的；确信的", "/ʃʊr/", "Are you sure about the answer?"),
    ("maybe", "可能；大概；也许", "/ˈmeibi/", "Maybe we should ask the teacher."),
    ("perhaps", "可能；也许", "/pərˈhæps/", "Perhaps he forgot about the meeting."),
    ("guess", "猜；猜测；推测", "/ɡes/", "Guess what happened yesterday!"),
    ("suppose", "假设；认为", "/səˈpoʊz/", "I suppose you're right about that."),
    ("expect", "期待；预期；预料", "/ɪkˈspekt/", "I didn't expect to see you here."),
    ("unexpected", "出乎意料的；始料未及的", "/ˌʌnɪkˈspektɪd/", "The news came as a complete surprise."),
    ("surprise", "惊奇；惊喜 v. 使吃惊", "/sərˈpraiz/", "To my surprise, he passed the exam."),
    ("surprising", "令人惊讶的；出人意料的", "/sərˈpraizɪŋ/", "The result was surprising."),
    ("mystery", "神秘；奥秘；神秘事物", "/ˈmistəri/", "The disappearance remains a mystery."),
    ("strange", "奇怪的；陌生的", "/streindʒ/", "I heard a strange noise last night."),
    ("noise", "噪音；声音", "/nɔɪz/", "Don't make too much noise at night."),
    ("noisy", "嘈杂的；喧闹的", "/ˈnɔɪzi/", "The street is too noisy to sleep."),
    ("quiet", "安静的；轻声的", "/ˈkwaiət/", "Please be quiet in the library."),
    ("silence", "沉默；寂静", "/ˈsailəns/", "Silence filled the room after the news."),
    ("silent", "沉默的；不说话的", "/ˈsailənt/", "He remained silent throughout the discussion."),

    # Unit 9 补充
    ("music", "音乐；乐曲", "/ˈmjuːzik/", "Music is a universal language."),
    ("musical", "音乐的；有音乐天赋的", "/ˈmjuːzikl/", "She has musical talent since childhood."),
    ("musician", "音乐家；乐师", "/mjuˈzɪʃn/", "He dreams of becoming a famous musician."),
    ("song", "歌曲；歌", "/sɒŋ/", "This song reminds me of my hometown."),
    ("sing", "唱；演唱", "/sɪŋ/", "Can you sing this song for us?"),
    ("dance", "跳舞；舞蹈", "/dɑːns/", "She loves to dance to pop music."),
    ("rock", "摇滚乐；岩石", "/rɒk/", "Rock music is popular among young people."),
    ("pop", "流行的；通俗的；流行音乐", "/pɒp/", "Pop songs are easy to sing along with."),
    ("jazz", "爵士乐", "/dʒæz/", "Jazz originated in the United States."),
    ("classical", "古典的；经典的", "/ˈklæsikl/", "Classical music helps me relax."),
    ("folk", "民间的；民俗的", "/foʊk/", "Folk music tells stories of ordinary people."),
    ("country", "乡村的；国家的 n. 国家", "/ˈkʌntri/", "Country music is popular in rural areas."),
    ("band", "乐队；带子", "/bænd/", "He plays guitar in a rock band."),
    ("concert", "音乐会；演奏会", "/ˈkɒnsert/", "Let's go to the concert this weekend."),
    ("audience", "听众；观众", "/ˈɔːdiəns/", "The audience applauded loudly at the end."),
    ("perform", "表演；执行；履行", "/pərˈfɔːrm/", "She performed beautifully on stage."),
    ("performance", "表演；演出；表现", "/pərˈfɔːrməns/", "His performance was outstanding."),
    ("actor", "男演员；演员", "/ˈæktər/", "He wants to be a famous actor."),
    ("actress", "女演员", "/ˈæktrəs/", "She is a talented actress."),
    ("role", "角色；作用", "/roʊl/", "She played the leading role in the movie."),
    ("character", "角色；人物；(人的)品质", "/ˈkærəktər/", "The characters in the novel are well-developed."),
    ("plot", "情节；剧情；阴谋", "/plɒt/", "The plot of the movie was very exciting."),
    ("scene", "场景；场面；景色", "/siːn/", "The opening scene of the film was breathtaking."),
    ("ending", "结局；结尾", "/ˈendɪŋ/", "I didn't expect such a sad ending."),
    ("documentary", "纪录片；纪实的", "/ˌdɒkjuˈmentri/", "We watched a documentary about wildlife."),

    # Unit 10 补充
    ("custom", "习俗；风俗；海关", "/ˈkʌstəm/", "Different countries have different customs."),
    ("culture", "文化；文明；教养", "/ˈkʌltʃər/", "Learning about other cultures broadens our minds."),
    ("cultural", "文化的；与文化有关的", "/ˈkʌltʃərəl/", "Cultural exchange promotes understanding between nations."),
    ("tradition", "传统；惯例", "/trəˈdɪʃn/", "It's a family tradition to have dinner together."),
    ("traditional", "传统的；惯例的", "/trəˈdɪʃənl/", "Traditional Chinese medicine is famous worldwide."),
    ("greet", "问候；迎接", "/ɡriːt/", "Greet guests warmly when they arrive."),
    ("greeting", "问候；招呼；致意", "/ˈɡriːtɪŋ/", "Send my greetings to your family."),
    ("bow", "鞠躬；低头；弯曲", "/baʊ/", "In Japan, people bow to show respect."),
    ("shake", "摇动；握手；震动", "/ʃeik/", "Shake hands when you meet someone for the first time."),
    ("handshake", "握手", "/ˈhændʃeik/", "A firm handshake shows confidence."),
    ("kiss", "亲吻；接吻", "/kis/", "In some countries, people kiss on the cheek to greet."),
    ("hug", "拥抱；紧抱", "/hʌɡ/", "Give your mom a hug when you see her."),
    ("wave", "挥手；挥舞；波浪", "/weiv/", "Wave goodbye to your friends."),
    ("manners", "礼貌；礼仪；习俗", "/ˈmænərz/", "Table manners vary across cultures."),
    ("etiquette", "礼节；礼仪", "/ˈetɪket/", "Business etiquette is important in formal meetings."),
    ("behave", "表现；守规矩；举止得体", "/bɪˈheiv/", "Behave yourself at school."),
    ("behavior", "行为；举止；态度", "/bɪˈheivjər/", "Good behavior earns respect from others."),
    ("rude", "粗鲁的；无礼的", "/ruːd/", "It's rude to interrupt others while they're talking."),
    ("politely", "礼貌地；客气地", "/pəˈlaɪtli/", "Ask politely when you need help."),
    ("impolite", "不礼貌的；失礼的", "/ˌɪmpəˈlaɪt/", "It's impolite to point at people."),
    ("relaxed", "放松的；自在的", "/rɪˈlekst/", "Feel relaxed and enjoy the party."),
    ("formal", "正式的；正规的", "/ˈfɔːrml/", "Wear formal clothes to the wedding ceremony."),
    ("informal", "非正式的；随意的", "/ɪnˈfɔːrml/", "It's an informal gathering — just wear casual clothes."),
    ("casual", "随便的；非正式的", "/ˈkæʒuəl/", "Dress casual for the picnic."),
    ("ceremony", "典礼；仪式", "/ˈserəmoʊni/", "The graduation ceremony was held in June."),

    # Unit 11 补充
    ("sad", "悲伤的；难过的", "/sæd/", "Sad movies often make people cry."),
    ("sadness", "悲哀；悲痛；难过", "/ˈsædnəs/", "Her eyes showed deep sadness."),
    ("happy", "高兴的；幸福的", "/ˈhæpi/", "Happy music makes people smile."),
    ("happiness", "幸福；快乐；愉快", "/ˈhæpinəs/", "Money doesn't bring true happiness."),
    ("angry", "生气的；愤怒的", "/ˈæŋɡri/", "Loud noise makes me angry."),
    ("anger", "怒气；愤怒", "/ˈæŋɡər/", "Try to control your anger."),
    ("nervous", "紧张的；焦虑的", "/ˈnɜːrvəs/", "I get nervous before exams."),
    ("worry", "担心；担忧 v. 担心", "/ˈwɜːri/", "Don't worry — everything will be fine."),
    ("worried", "担心的；发愁的", "/ˈwɜːrid/", "Parents are worried about children's safety."),
    ("anxious", "焦虑的；渴望的", "/ˈæŋkʃəs/", "She felt anxious about the test results."),
    ("stress", "压力；紧张；重压", "/stress/", "Too much stress is bad for health."),
    ("pressure", "压力；压迫", "/ˈpreʃər/", "Students face pressure from exams."),
    ("relax", "放松；休息；松弛", "/rɪˈlæks/", "Listen to music to relax."),
    ("relaxing", "令人放松的", "/rɪˈlæksɪŋ/", "A walk in the park is relaxing."),
    ("comfortable", "舒服的；舒适的", "/ˈkʌmftəbl/", "This chair is very comfortable."),
    ("uncomfortable", "不舒服的；不安的", "/ʌnˈkʌmftəbl/", "These shoes feel uncomfortable."),
    ("calm", "平静的；镇静的 v. (使)平静", "/kɑːm/", "Stay calm when facing difficulties."),
    ("excited", "兴奋的；激动的", "/ɪkˈsaidɪd/", "I'm excited about the trip tomorrow."),
    ("excitement", "激动；兴奋", "/ɪkˈsaitmənt/", "The excitement was palpable in the crowd."),
    ("pleased", "高兴的；满意的", "/pliːzd/", "I'm pleased with your progress."),
    ("satisfied", "满意的；满足的", "/ˈsætɪsfaid/", "Are you satisfied with the service?"),
    ("disappointed", "失望的；沮丧的", "/ˌdɪsəˈpɔɪntid/", "I was disappointed by the movie ending."),
    ("frustrated", "挫败的；泄气的", "/ˈfrʌstreɪtid/", "He felt frustrated when he couldn't solve the problem."),
    ("upset", "心烦的；难过的；打乱的", "/ʌpˈset/", "Don't get upset over small things."),
    ("mood", "情绪；心情；语气", "/muːd/", "Music can affect your mood."),
    ("feeling", "感觉；感触；感情", "/ˈfiːlɪŋ/", "Describe your feelings in words."),
    ("emotion", "情感；情绪；感动", "/ɪˈmoʊʃn/", "Emotions affect our decision-making."),

    # Unit 12 补充
    ("unexpected", "意想不到的；意外的", "/ˌʌnɪkˈspektɪd/", "Life is full of unexpected events."),
    ("expected", "预期的；预料的", "/ɪkˈspektɪd/", "The results were better than expected."),
    ("oversleep", "睡过头；过度睡眠", "/ˌəʊvərˈsliːp/", "I overslept and missed the bus this morning."),
    ("alarm", "警报；闹钟；惊恐", "/əˈlɑːrm/", "Set your alarm for six o'clock tomorrow."),
    ("ring", "(钟、铃等)响；铃声", "/rɪŋ/", "The phone kept ringing but nobody answered."),
    ("bell", "铃；电铃；钟声", "/bel/", "The bell rings to signal the end of class."),
    ("clock", "时钟；计时器", "/klɒk/", "The clock on the wall stopped working."),
    ("time", "时间；次；倍", "/taim/", "Time flies when you're having fun."),
    ("late", "晚的；迟到的 adv. 晚；迟", "/leit/", "Sorry I'm late — traffic was bad."),
    ("early", "早的；提早的 adv. 早", "/ˈɜːrli/", "Wake up early to catch the first bus."),
    ("already", "已经；早已", "/ɔːlˈredi/", "The bus has already left."),
    ("yet", "还；尚；已经", "/jet/", "Has the train arrived yet?"),
    ("just", "刚刚；正好；仅仅", "/dʒʌst/", "I just finished my homework."),
    ("recently", "最近；近来", "/ˈriːsntli/", "I haven't seen him recently."),
    ("lately", "最近；不久前", "/ˈleitli/", "Have you been busy lately?"),
    ("schedule", "日程表；时间表", "/ˈskedʒuːl/", "Check your schedule for next week."),
    ("appoint", "约定；指定；任命", "/əˈpɔɪnt/", "They appointed a new manager."),
    ("appointment", "约会；预约；任命", "/əˈpɔɪntmənt/", "I have a dental appointment at 3 PM."),
    ("deadline", "最后期限；截止日期", "/ˈdedlain/", "The deadline for the project is Friday."),
    ("rush", "仓促行动；匆忙 n. 匆忙", "/rʌʃ/", "Don't rush — take your time."),
    ("hurry", "匆忙；急忙 v. 赶快", "/ˈhɜːri/", "Hurry up or we'll miss the train."),
    ("miss", "错过；思念；未击中", "/mis/", "I don't want to miss the chance."),
    ("catch", "抓住；赶上；感染", "/kætʃ/", "Run fast or you won't catch the bus."),
    ("arrive", "到达；抵达", "/əˈraiv/", "What time does the train arrive?"),
    ("reach", "到达；达到；伸手够到", "/riːtʃ/", "Call me when you reach the station."),
    ("leave", "离开；留下；出发", "/liːv/", "I need to leave home at seven."),
    ("return", "返回；归还；回报", "/rɪˈtɜːrn/", "Return the library book on time."),

    # Unit 13 补充
    ("environment", "环境；周围状况", "/ɪnˈvaɪrənmənt/", "We must protect our environment."),
    ("environmental", "环境的；有关环保的", "/ɪnˌvaɪrənˈmentl/", "Environmental problems require global cooperation."),
    ("pollute", "污染；弄脏", "/pəˈluːt/", "Factories pollute the air and water."),
    ("pollution", "污染；污染物", "/pəˈluːʃn/", "Air pollution causes many health problems."),
    ("protect", "保护；防护", "/prəˈtekt/", "We should protect wild animals."),
    ("protection", "保护；防护；护照", "/prəˈtekʃn/", "Wear sun protection when going outside."),
    ("endanger", "危及；使遭危险", "/ɪnˈdeindʒər/", "Hunting endangers many animal species."),
    ("endangered", "濒危的；有灭绝危险的", "/ɪnˈdeindʒərd/", "Pandas are an endangered species."),
    ("extinct", "灭绝的；绝迹的", "/ɪkˈstɪŋkt/", "Dinosaurs became extinct millions of years ago."),
    ("extinction", "灭绝；消亡", "/ɪkˈstɪŋkʃn/", "Many species face extinction due to habitat loss."),
    ("animal", "动物；兽类的", "/ˈænɪml/", "Animals are our friends on Earth."),
    ("wild", "野生的；荒凉的", "/wald/", "Wild animals should live in nature."),
    ("wildlife", "野生动物；野生生物", "/ˈwaɪldlaif/", "The reserve protects local wildlife."),
    ("species", "物种；种类", "/ˈspiːshiːz/", "Thousands of species disappear each year."),
    ("habitat", "栖息地；生活环境", "/ˈhæbɪtæt/", "Destroying habitats threatens wildlife survival."),
    ("forest", "森林；林区", "/ˈfɒrɪst/", "Forests produce oxygen for us to breathe."),
    ("desert", "沙漠；荒原", "/ˈdezərt/", "Camels survive in hot deserts."),
    ("ocean", "海洋；大海", "/ˈoʊʃn/", "Ocean pollution kills marine life."),
    ("marine", "海洋的；海产的", "/məˈriːn/", "Marine biology studies ocean creatures."),
    ("climate", "气候；风气", "/ˈklaimit/", "Global climate change affects everyone."),
    ("weather", "天气；气象", "/ˈweðər/", "What's the weather like today?"),
    ("temperature", "温度；体温", "/ˈtemprətʃər/", "Global temperature is rising year by year."),
    ("global", "全球的；全世界的", "/ˈɡloʊbl/", "Global warming is a serious issue."),
    ("warm", "温暖的；暖和的 v. 变暖", "/wɔːrm/", "The earth is getting warmer."),
    ("cool", "凉爽的；冷静的 v. 冷却", "/kuːl/", "Keep cool in summer heat."),
    ("hot", "热的；辣的", "/hɒt/", "It's too hot to play outside today."),
    ("cold", "寒冷的；冷的", "/koʊld/", "Wear warm clothes in cold weather."),
    ("clean", "干净的；清洁的 v. 打扫", "/kliːn/", "Keep our cities clean."),
    ("dirty", "脏的；肮脏的", "/ˈdɜːrti/", "Don't throw trash — streets stay dirty."),
    ("fresh", "新鲜的；清新的", "/freʃ/", "The air in the mountains is fresh."),
    ("health", "健康；医疗保健", "/helθ/", "Pollution harms human health."),
    ("healthy", "健康的；健壮的", "/helθi/", "Eat healthy food and exercise daily."),
    ("harm", "伤害；损害 v. 伤害", "/hɑːrm/", "Smoking harms your lungs."),
    ("harmful", "有害的；导致损害的", "/ˈhɑːrmfl/", "Plastic bags are harmful to the environment."),
    ("dangerous", "危险的；不安全的", "/ˈdeindʒərəs/", "It's dangerous to swim alone."),
    ("safe", "安全的；保险的", "/seif/", "Make sure the food is safe to eat."),
    ("safety", "安全；安全性", "/ˈseɪfti/", "Safety comes first in everything."),

    # Unit 14 衺充
    ("graduate", "毕业；获得学位", "/ˈɡrædʒueit/", "I will graduate from high school next year."),
    ("graduation", "毕业；毕业典礼", "/ˌɡrædʒuˈeɪʃn/", "Graduation is both happy and sad."),
    ("senior", "年长的；级别较高的", "/ˈsiːniər/", "Senior students help freshmen adjust to school."),
    ("junior", "年少的；级别较低的", "/ˈdʒuːniər/", "Junior high school prepares you for senior high."),
    ("schoolmate", "同学；校友", "/ˈskuːlmeit/", "I met an old schoolmate at the reunion."),
    ("classmate", "同班同学", "/ˈklɑːsmeit/", "He is my classmate — we sit together."),
    ("friendship", "友谊；友情关系", "/ˈfrendʃip/", "True friendship lasts a lifetime."),
    ("memory", "记忆；回忆；存储器", "/ˈmeməri/", "School days hold precious memories."),
    ("remember", "记住；记得；回忆起", "/rɪˈmembər/", "I remember meeting you in Grade 7."),
    ("forget", "忘记；遗忘", "/fərˈɡet/", "I'll never forget my teachers' kindness."),
    ("experience", "经验；经历；体验", "/ɪkˈspɪriəns/", "Traveling is a great learning experience."),
    ("lesson", "课；功课；教训", "/ˈlesn/", "Every failure teaches a lesson."),
    ("learn", "学习；得知；学会", "/lɜːrn/", "We learn something new every day."),
    ("study", "学习；研究；书房", "/ˈstʌdi/", "Study hard and your efforts will pay off."),
    ("knowledge", "知识；学问；了解", "/ˈnɒlɪdʒ/", "Knowledge is power — keep learning."),
    ("wisdom", "智慧；才智", "/ˈwɪzdəm/", "Wisdom comes from experience."),
    ("understand", "理解；明白；懂得", "/ˌʌndərˈstænd/", "I understand how you feel."),
    ("understanding", "理解；谅解；懂", "/ˌʌndərˈstændɪŋ/", "Thank you for your understanding."),
    ("future", "未来；将来；前途", "/ˈfjuːtʃər/", "What do you want to do in the future?"),
    ("dream", "梦想；梦 v. 做梦", "/driːm/", "Follow your dreams and never give up."),
    ("hope", "希望；期望 v. 希望", "/hoʊp/", "Hope for the best, prepare for the worst."),
    ("wish", "愿望；希望 v. 希望", "/wɪʃ/", "Make a wish when you blow out candles."),
    ("goal", "目标；球门；射门", "/ɡoʊl/", "Set clear goals and work toward them."),
    ("aim", "目标；目的 v. 瞄准；旨在", "/eim/", "Aim high and work hard."),
    ("plan", "计划；打算；方案", "/plæn/", "Plan your future carefully."),
    ("prepare", "准备；预备", "/priˈper/", "Prepare well for the coming challenges."),
    ("effort", "努力；努力的成果", "/efərt/", "Success requires continuous effort."),
    ("hardworking", "勤奋的；努力工作的", "/ˈhɑːrdwɜːrɪŋ/", "Hardworking students usually get better grades."),
    ("perseverance", "毅力；坚持不懈；不屈不挠", "/ˌpɜːrsəˈvɪrəns/", "Perseverance leads to success."),
    ("courage", "勇气；胆量", "/ˈkʌrɪdʒ/", "It takes courage to try new things."),
    ("brave", "勇敢的；无畏的", "/breiv/", "Be brave enough to face any challenge."),
    ("determine", "决定；查明；决心", "/dɪˈtɜːrmɪn/", "Your attitude determines your future."),
    ("attitude", "态度；看法", "/ˈætɪtuːd/", "A positive attitude helps overcome difficulties."),
    ("positive", "积极的；肯定的；正面的", "/ˈpɒzətiv/", "Stay positive even when things go wrong."),
    ("negative", "消极的；否定的；负面的", "/ˈneɡətiv/", "Don't let negative thoughts stop you."),
    ("success", "成功；成就；胜利", "/səkˈses/", "Success is the result of hard work."),
    ("fail", "失败；不及格；衰退", "/feil/", "If you fail, try again."),
    ("failure", "失败；失败的人(或事)", "/ˈfeiljər/", "Failure teaches valuable lessons."),
    ("try", "尝试；努力；审判", "/traɪ/", "Never stop trying — success is near."),
    ("attempt", "试图；企图；尝试", "/əˈtempt/", "Make another attempt if the first fails."),
    ("challenge", "挑战；质疑；向……挑战", "/ˈtʃælɪndʒ/", "Life is full of challenges — embrace them."),
    ("overcome", "克服；战胜；解决", "/ˌəʊvərˈkʌm/", "You can overcome any difficulty with effort."),
    ("achieve", "实现；达到；取得", "/əˈtʃiːv/", "Work hard to achieve your dreams."),
    ("accomplish", "完成；达到；实现", "/əˈkɒmplɪʃ/", "Accomplish your goals step by step."),

    # ========== 再补一批，冲到1000+ ==========
    # 通用高频词
    ("example", "例子；范例；榜样", "/ɪɡˈzæmpl/", "For example, you can practice by reading."),
    ("sample", "样品；样本；实例", "/ˈsæmpl/", "This is just a sample of the product."),
    ("instance", "例子；实例；情况", "/ˈɪnstəns/", "For instance, English is useful for travel."),
    ("situation", "情况；形势；处境", "/ˌsɪtʃuˈeɪʃn/", "We need to deal with this situation carefully."),
    ("condition", "条件；状况；环境", "/kənˈdɪʃn/", "The car is in good condition."),
    ("problem", "问题；难题；习题", "/ˈprɒbləm/", "Every problem has a solution."),
    ("solution", "解决方案；解答；溶解", "/səˈluːʃn/", "Think carefully to find a good solution."),
    ("answer", "回答；答复 n. 答案", "/ˈɑːnsər/", "Please answer the question in English."),
    ("question", "问题；疑问；询问", "/ˈkwestʃən/", "Do you have any questions about this?"),
    ("explain", "解释；说明", "/ɪkˈsplein/", "Can you explain it again?"),
    ("describe", "描述；形容；描绘", "/dɪˈskraib/", "Describe what happened yesterday."),
    ("discuss", "讨论；论述", "/dɪˈskʌs/", "Let's discuss this topic together."),
    ("discussion", "讨论；辩论；商讨", "/dɪˈskʌʃn/", "Our discussion was very productive."),
    ("argue", "争论；辩论；说服", "/ˈɑːrɡjuː/", "Don't argue over small things."),
    ("agree", "同意；赞成；一致", "/əˈɡriː/", "I agree with your opinion."),
    ("disagree", "不同意；有分歧", "/ˌdɪsəˈɡriː/", "I'm afraid I disagree with that point."),
    ("opinion", "意见；看法；主张", "/əˈpinjən/", "In my opinion, learning English is important."),
    ("idea", "主意；想法；概念", "/aiˈdiːə/", "That's a brilliant idea!"),
    ("thought", "想法；思想 v. 想；思考", "/θɔːt/", "Give it some thought before deciding."),
    ("mind", "头脑；思想；介意", "/maind/", "Never mind — it's not a big deal."),
    ("think", "想；认为；思考", "/θɪŋk/", "Think twice before making a decision."),
    ("consider", "考虑；认为；顾及", "/kənˈsɪdər/", "Consider all options before choosing."),
    ("compare", "比较；对照", "/kəmˈper/", "Compare the two options carefully."),
    ("difference", "不同；差异；差别", "/ˈdɪfrəns/", "What's the difference between these two words?"),
    ("similar", "相似的；类似的", "/ˈsɪmələr/", "These two words have similar meanings."),
    ("same", "相同的；同一的", "/seim/", "We are in the same class."),
    ("different", "不同的；有差异的", "/ˈdɪfrənt/", "Everyone has different learning styles."),
    ("common", "共同的；常见的；普通的", "/ˈkɒmən/", "It's a common mistake among beginners."),
    ("usual", "通常的；寻常的", "/ˈjuːʒuəl/", "As usual, he arrived late today."),
    ("unusual", "不寻常的；异常的", "/ʌnˈjuːʒuəl/", "Something unusual happened last night."),
    ("normal", "正常的；平常的", "/ˈnɔːrml/", "Everything returned to normal after the storm."),
    ("special", "特别的；特殊的；专门的", "/ˈspeʃl/", "Today is a special day for me."),
    ("particular", "特定的；特指的；格外的", "/pərˈtikjələr/", "Is there any particular reason for your choice?"),
    ("certain", "确定的；某种；一定", "/ˈsɜːrtn/", "I'm certain that he will come."),
    ("sure", "确信的；当然的；可靠的", "/ʃʊr/", "Are you sure about that answer?"),
    ("clear", "清楚的；明白的；晴朗的", "/klir/", "Is everything clear now?"),
    ("obvious", "明显的；显然的", "/ˈɒbviəs/", "It's obvious that she worked hard."),
    ("simple", "简单的；简明的", "/ˈsimpl/", "Keep your answer simple and clear."),
    ("complex", "复杂的；合成的", "/kɒmˈpleks/", "This problem is too complex to solve quickly."),
    ("easy", "容易的；舒适的", "/ˈiːzi/", "The test was easier than expected."),
    ("difficult", "困难的；艰难的", "/ˈdɪfɪkəlt/", "Nothing is difficult if you put your heart into it."),
    ("hard", "困难的；努力的；硬的", "/hɑːrd/", "Work hard, play hard."),

    # 动词/形容词补充
    ("improve", "改进；改善；进步", "/ɪmˈpruːv/", "You need to improve your writing skills."),
    ("increase", "增加；增长；提高", "/ɪnˈkriːs/", "Reading can increase your vocabulary."),
    ("decrease", "减少；减小", "/diːˈkriːs/", "Try to decrease screen time before bed."),
    ("raise", "举起；筹集；养育", "/reiz/", "Raise your hand if you know the answer."),
    ("reduce", "减少；缩小；降低", "/rɪˈdjuːs/", "We should reduce plastic waste."),
    ("provide", "提供；供给", "/prəˈvaid/", "School provides a good learning environment."),
    ("offer", "提供；提议；出价", "/ˈɒfər/", "He offered to help me with my homework."),
    ("receive", "收到；接到；接受", "/rɪˈsiːv/", "Did you receive my message?"),
    ("accept", "接受；承认；同意", "/əkˈsept/", "Accept challenges as opportunities to grow."),
    ("refuse", "拒绝；回绝；不肯", "/rɪˈfjuːz/", "Don't refuse help when you need it."),
    ("promise", "承诺；诺言 v. 承诺", "/ˈprɒmis/", "I promise I'll finish it on time."),
    ("expect", "期待；预期；预料", "/ɪkˈspekt/", "Teachers expect students to be honest."),
    ("hope", "希望；期望 v. 希望", "/hoʊp/", "Hope for the best but prepare for the worst."),
    ("wish", "祝愿；希望 v. 希望", "/wɪʃ/", "Wish you all the best in the future."),
    ("wonder", "想知道；好奇；奇迹", "/ˈwʌndər/", "I wonder if it will rain tomorrow."),
    ("realize", "意识到；实现", "/ˈriːəlaiz/", "I realized how important English is."),
    ("understand", "理解；明白；懂得", "/ˌʌndərˈstænd/", "Do you understand what I mean?"),
    ("mean", "意思是；意味着；打算", "/miːn/", "What does this word mean?"),
    ("include", "包括；包含", "/ɪnˈkluːd/", "The price includes tax and service fee."),
    ("except", "除……之外；只是", "/ɪkˈsept/", "Everyone passed except Tom."),
    ("besides", "此外；而且；除……之外", "/bɪˈsaɪdz/", "Besides English, I also learn Japanese."),
    ("however", "然而；可是；无论如何", "/haʊˈevər/", "However hard you try, never give up."),
    ("although", "虽然；尽管；即使", "/ɔːlˈðəʊ/", "Although it was raining, we went hiking."),
    ("though", "虽然；尽管；不过", "/ðəʊ/", "It was hard, though we managed to finish."),
    ("whether", "是否；不管；无论", "/ˈweðər/", "I wonder whether he will come or not."),
    ("if", "是否；如果；假如", "/if/", "If you study hard, you will succeed."),
    ("unless", "除非；如果不", "/ʌnˈles/", "You won't improve unless you practice."),
    ("until", "直到……为止；在……以前", "/ʌnˈtil/", "Don't give up until you succeed."),
    ("since", "自从；因为；既然", "/sins/", "Since you asked, I'll tell you the truth."),
    ("while", "当……时候；然而；虽然", "/wail/", "While others rest, he keeps studying."),
    ("because", "因为；由于", "/bɪˈkɒz/", "He was late because of the traffic."),
    ("because of", "因为；由于", "/", "The game was canceled because of rain."),
    ("so that", "为了；以便；结果", "/", "Study hard so that you can get good grades."),
    ("in order to", "为了……（目的）", "/", "In order to succeed, you must work hard."),
    ("as long as", "只要；如果", "/", "As long as you try, there's hope."),
    ("as soon as", "一……就……", "/", "Call me as soon as you arrive."),
    ("no matter how/what/when/where/who", "无论怎样/什么/何时/哪里/谁", "/", "No matter how hard it is, never give up."),
    ("even if/even though", "即使；尽管", "/", "Even if it rains, we'll go hiking."),
    ("both...and...", "两者都……和……", "/", "Both English and math are important subjects."),
    ("either...or...", "或者……或者……；不是……就是……", "/", "You can either stay or leave — it's up to you."),
    ("neither...nor...", "既不……也不……", "/", "Neither he nor I know the answer."),
    ("not only...but also...", "不仅……而且……", "/", "She is not only smart but also hardworking."),
    ("instead (of)", "代替；反而；(代替)而不是", "/", "Let's walk instead of taking a taxi."),
    ("besides", "除……之外(还有)；此外", "/", "Besides homework, I also help with housework."),
    ("except (for)", "除……之外(不包括)", "/", "Everyone passed except for Tom."),
    ("such as", "例如；诸如", "/", "Fruits such as apples and oranges are healthy."),
    ("for example", "例如", "/", "Many sports, for example basketball, are popular."),
    ("in fact", "事实上；实际上", "/", "In fact, I don't like coffee at all."),
    ("at least", "至少；起码", "/", "You should sleep at least eight hours a day."),
    ("at most", "最多；至多", "/", "It will take at most one hour to finish."),
    ("in other words", "换句话说；也就是说", "/", "In other words, you need to study harder."),
]

def generate_g9_dictation():
    """Generate the G9 vocabulary JSON file."""
    words = []
    idx = 1
    seen_words = set()

    for item in VOCAB_DATA:
        if len(item) >= 4:
            word, meaning, phonetic, example = item[0], item[1], item[2], item[3]
            # Skip exact duplicate words (keep first occurrence)
            if word.lower() in seen_words:
                continue
            seen_words.add(word.lower())
            
            entry = {
                "id": f"en_g9_{idx:03d}",
                "word": word,
                "meaning": meaning,
                "grade": 9,
                "semester": "全册",
                "phonetic": phonetic,
                "example": example,
            }
            words.append(entry)
            idx += 1
        else:
            print(f"WARNING: Skipping incomplete entry: {item}")

    output_path = "/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/dictation_en_g9.json"

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(words, f, ensure_ascii=False, indent=2)

    print(f"\n{'='*60}")
    print(f"✅ 九年级英语听写词库生成完毕！")
    print(f"{'='*60}")
    print(f"📁 输出文件: {output_path}")
    print(f"📊 总词数: {len(words)}")
    
    print(f"\n📋 前5条样本:")
    for w in words[:5]:
        print(f"  [{w['id']}] {w['word']} — {w['meaning']}")

    print(f"\n📋 最后5条样本:")
    for w in words[-5:]:
        print(f"  [{w['id']}] {w['word']} — {w['meaning']}")

    # Validate IDs uniqueness
    ids = [w['id'] for w in words]
    if len(ids) == len(set(ids)):
        print(f"\n✅ ID唯一性验证通过！共{len(set(ids))}个唯一ID")
    else:
        print(f"\n❌ 存在重复ID!")

    # Verify JSON parsing
    try:
        with open(output_path, 'r', encoding='utf-8') as f:
            loaded = json.load(f)
        if len(loaded) == len(words):
            print(f"✅ JSON解析验证通过！可正确读取{len(loaded)}条记录")
        else:
            print(f"⚠️ JSON条目数量不一致")
    except json.JSONDecodeError as e:
        print(f"❌ JSON解析失败: {e}")

    # Count by approximate unit distribution (rough estimate based on order)
    units = ["U1", "U2", "U3", "U4", "U5", "U6", "U7", "U8", "U9", "U10", "U11", "U12", "U13", "U14"]
    per_unit = len(words) // 14
    print(f"\n📊 大约每单元词汇分布（共14个单元）:")
    for i, u in enumerate(units):
        start_idx = i * per_unit
        end_idx = min((i + 1) * per_unit, len(words))
        if start_idx < len(words):
            count = end_idx - start_idx
            if i == len(units) - 1:
                count = len(words) - i * per_unit
            print(f"  {u}: 约{count}词")

    return words


if __name__ == "__main__":
    generate_g9_dictation()
