#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
初二（8年级）英语听写词库生成脚本
从 words_network_j2.json (1276词) -> dictation_en_g8.json
"""

import json, re

INPUT_FILE = '/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/words_network_j2.json'
OUTPUT_FILE = '/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/dictation_en_g8.json'

# ============================================================
# IPA音标字典 - 全部使用双引号字符串
# ============================================================
PHONETIC_DICT = {}

def add_phonetic(word_list, phonetic):
    for w in word_list:
        PHONETIC_DICT[w] = phonetic

# Unit 1 上册: vacation
add_phonetic(['anyone'], "/'eniwʌn/")
add_phonetic(['anywhere'], "/'eniweə(r)/")
add_phonetic(['wonderful'], "/'wʌndəfl/")
add_phonetic(['few'], "/fjuː/")
add_phonetic(['most'], "/məʊst/")
add_phonetic(['myself'], "/maɪ'self/")
add_phonetic(['yourself'], "/jɔː'self/")
add_phonetic(['hen'], "/hen/")
add_phonetic(['seem'], "/siːm/")
add_phonetic(['bored'], "/bɔːd/")
add_phonetic(['activity'], "/æk'tɪvəti/")
add_phonetic(['decide'], "/dɪ'saɪd/")
add_phonetic(['try'], "/traɪ/")
add_phonetic(['paragliding'], "/'pærəɡlaɪdɪŋ/")
add_phonetic(['bird'], "/bɜːd/")
add_phonetic(['building'], "/'bɪldɪŋ/")
add_phonetic(['wonder'], "/'wʌndə(r)/")
add_phonetic(['difference'], "/'dɪfrəns/")
add_phonetic(['top'], "/tɒp/")
add_phonetic(['wait'], "/weɪt/")
add_phonetic(['umbrella'], "/ʌm'brelə/")
add_phonetic(['wet'], "/wet/")
add_phonetic(['below'], "/bɪ'ləʊ/")
add_phonetic(['enough'], "/ɪ'nʌf/")
add_phonetic(['hungry'], "/'hʌŋɡri/")
add_phonetic(['as'], "/æz; əz/")
add_phonetic(['hill'], "/hɪl/")
add_phonetic(['diary'], "/'daɪəri/")
add_phonetic(['enjoy'], "/ɪn'dʒɔɪ/")
add_phonetic(['dislike'], "/dɪs'laɪk/")

# Unit 2 上册: exercise
add_phonetic(['housework'], "/'haʊswɜːk/")
add_phonetic(['hardly'], "/'hɑːdli/")
add_phonetic(['ever'], "/'evə(r)/")
add_phonetic(['once'], "/wʌns/")
add_phonetic(['twice'], "/twaɪs/")
add_phonetic(['internet'], "/'ɪntənet/")
add_phonetic(['program'], "/'prəʊɡræm/")
add_phonetic(['full'], "/fʊl/")
add_phonetic(['swing'], "/swɪŋ/")
add_phonetic(['maybe'], "/'meɪbi/")
add_phonetic(['least'], "/liːst/")
add_phonetic(['junk'], "/dʒʌŋk/")
add_phonetic(['coffee'], "/'kɒfi/")
add_phonetic(['health'], "/helθ/")
add_phonetic(['result'], "/rɪ'zʌlt/")
add_phonetic(['percent'], "/pə'sent/")
add_phonetic(['although'], "/ɔːl'ðəʊ/")
add_phonetic(['through'], "/θruː/")
add_phonetic(['such'], "/sʌtʃ/")
add_phonetic(['together'], "/tə'ɡeðə(r)/")
add_phonetic(['die'], "/daɪ/")
add_phonetic(['writer'], "/'raɪtə(r)/")
add_phonetic(['magazine'], "/ˌmæɡə'ziːn/")
add_phonetic(['however'], "/haʊ'evə(r)/")
add_phonetic(['than'], "/ðæn; ðn/")
add_phonetic(['almost'], "/'ɔːlməʊst/")
add_phonetic(['none'], "/nʌn/")
add_phonetic(['less'], "/les/")
add_phonetic(['point'], "/pɔɪnt/")

# Unit 3 上册: sister comparison
add_phonetic(['outgoing'], "/'aʊtgəʊɪŋ/")
add_phonetic(['better'], "/'betə(r)/")
add_phonetic(['loudly'], "/'laʊdli/")
add_phonetic(['quietly'], "/'kwaɪətli/")
add_phonetic(['hard-working'], "/ˌhɑːd'wɜːkɪŋ/")
add_phonetic(['competition'], "/ˌkɒmpə'tɪʃn/")
add_phonetic(['fantastic'], "/fæn'tæstɪk/")
add_phonetic(['clearly'], "/'klɪəli/")
add_phonetic(['win'], "/wɪn/")
add_phonetic(['though'], "/ðəʊ/")
add_phonetic(['care'], "/keə(r)/")
add_phonetic(['talented'], "/'tæləntɪd/")
add_phonetic(['truly'], "/'truːli/")
add_phonetic(['necessary'], "/'nesəsəri/")
add_phonetic(['both'], "/bəʊθ/")
add_phonetic(['which'], "/wɪtʃ/")
add_phonetic(['grade'], "/ɡreɪd/")
add_phonetic(['should'], "/ʃʊd; ʃəd/")
add_phonetic(['bring'], "/brɪŋ/")
add_phonetic(['information'], "/ˌɪnfə'meɪʃn/")
add_phonetic(['touch'], "/tʌtʃ/")
add_phonetic(['heart'], "/hɑːt/")
add_phonetic(['break'], "/breɪk/")
add_phonetic(['arm'], "/ɑːm/")
add_phonetic(['laugh'], "/lɑːf/")
add_phonetic(['similar'], "/'sɪmɪlə(r)/")
add_phonetic(['share'], "/ʃeə(r)/")
add_phonetic(['loud'], "/laʊd/")
add_phonetic(['primary'], "/'praɪməri/")
add_phonetic(['reach'], "/riːtʃ/")
add_phonetic(['hand'], "/hænd/")
add_phonetic(['kid'], "/kɪd/")
add_phonetic(['fact'], "/fækt/")

# Unit 4 上册: movie theater
add_phonetic(['theater'], "/'θɪətə(r)/")
add_phonetic(['comfortable'], "/'kʌmftəbl/")
add_phonetic(['screen'], "/skriːn/")
add_phonetic(['close'], "/kləʊs/")
add_phonetic(['ticket'], "/'tɪkɪt/")
add_phonetic(['worst'], "/wɜːst/")
add_phonetic(['cheaply'], "/'tʃiːpli/")
add_phonetic(['song'], "/sɒŋ/")
add_phonetic(['choose'], "/tʃuːz/")
add_phonetic(['action'], "/'ækʃn/")
add_phonetic(['role'], "/rəʊl/")
add_phonetic(['simple'], "/'simpl/")
add_phonetic(['report'], "/rɪ'pɔːt/")
add_phonetic(['service'], "/'sɜːvɪs/")
add_phonetic(['pretty'], "/'prɪti/")
add_phonetic(['meal'], "/miːl/")
add_phonetic(['fresh'], "/freʃ/")
add_phonetic(['creativity'], "/ˌkriːeɪ'tɪvəti/")
add_phonetic(['performer'], "/pə'fɔːmə(r)/")
add_phonetic(['crowd'], "/kraʊd/")
add_phonetic(['poor'], "/pɔː(r); pʊə(r)/")
add_phonetic(['give'], "/ɡɪv/")
add_phonetic(['seat'], "/siːt/")
add_phonetic(['menu'], "/'menjuː/")
add_phonetic(['act'], "/ækt/")
add_phonetic(['without'], "/wɪ'ðaʊt/")
add_phonetic(['discuss'], "/dɪ'skʌs/")

# Unit 5 上册: TV shows
add_phonetic(['situation'], "/ˌsɪtʃu'eɪʃn/")
add_phonetic(['expect'], "/ɪk'spekt/")
add_phonetic(['happen'], "/'hæpn/")
add_phonetic(['cartoon'], "/kɑː'tuːn/")
add_phonetic(['culture'], "/'kʌltʃə(r)/")
add_phonetic(['famous'], "/'feɪməs/")
add_phonetic(['appear'], "/ə'pɪə(r)/")
add_phonetic(['become'], "/bɪ'kʌm/")
add_phonetic(['rich'], "/rɪtʃ/")
add_phonetic(['successful'], "/sək'sesfl/")
add_phonetic(['might'], "/maɪt/")
add_phonetic(['main'], "/meɪn/")
add_phonetic(['reason'], "/'riːzn/")
add_phonetic(['film'], "/fɪlm/")
add_phonetic(['unluckily'], "/ʌn'lʌkɪli/")
add_phonetic(['lose'], "/luːz/")
add_phonetic(['ready'], "/'redi/")
add_phonetic(['character'], "/'kærəktə(r)/")
add_phonetic(['army'], "/'ɑːmi/")
add_phonetic(['face'], "/feɪs/")
add_phonetic(['own'], "/əʊn/")
add_phonetic(['art'], "/ɑːt/")
add_phonetic(['paint'], "/peɪnt/")
add_phonetic(['create'], "/kri'eɪt/")
add_phonetic(['describe'], "/dɪ'skraɪb/")
add_phonetic(['look'], "/lʊk/")
add_phonetic(['educational'], "/ˌedʒu'keɪʃənl/")
add_phonetic(['plan'], "/plæn/")
add_phonetic(['joke'], "/dʒəʊk/")
add_phonetic(['meaningless'], "/'miːnɪŋləs/")
add_phonetic(['enjoyable'], "/ɪn'dʒɔɪəbl/")

# Unit 6 上册: future plans
add_phonetic(['grow'], "/ɡrəʊ/")
add_phonetic(['computer'], "/kəm'pjuːtə(r)/")
add_phonetic(['programmer'], "/'prəʊɡræmə(r)/")
add_phonetic(['cook'], "/kʊk/")
add_phonetic(['doctor'], "/'dɒktə(r)/")
add_phonetic(['engineer'], "/ˌendʒɪ'niə(r)/")
add_phonetic(['violinist'], "/ˌvaɪə'lɪnɪst/")
add_phonetic(['driver'], "/'draɪvə(r)/")
add_phonetic(['pilot'], "/'paɪlət/")
add_phonetic(['pianist'], "/'piænɪst/")
add_phonetic(['scientist'], "/'saɪəntist/")
add_phonetic(['college'], "/'kɒlɪdʒ/")
add_phonetic(['education'], "/ˌedʒu'keɪʃn/")
add_phonetic(['medicine'], "/'medsn; 'medɪsn/")
add_phonetic(['university'], "/ˌjuːnɪ'vɜːsəti/")
add_phonetic(['article'], "/'ɑːtɪkl/")
add_phonetic(['send'], "/send/")
add_phonetic(['resolution'], "/ˌrezə'luːʃn/")
add_phonetic(['team'], "/tiːm/")
add_phonetic(['foreign'], "/'fɒrən/")
add_phonetic(['able'], "/'eɪbl/")
add_phonetic(['question'], "/'kwestʃən/")
add_phonetic(['meaning'], "/'miːnɪŋ/")
add_phonetic(['promise'], "/'prɒmɪs/")
add_phonetic(['beginning'], "/bɪ'ɡɪnɪŋ/")
add_phonetic(['improve'], "/ɪm'pruːv/")
add_phonetic(['physical'], "/'fɪzɪkl/")
add_phonetic(['self-improvement'], "/ˌself ɪm'pruːvmənt/")
add_phonetic(['hobby'], "/'hɒbi/")
add_phonetic(['weekly'], "/'wiːkli/")
add_phonetic(['schoolwork'], "/'skuːlwɜːk/")
add_phonetic(['personal'], "/'pɜːsənl/")
add_phonetic(['relationship'], "/rɪ'leɪʃnʃɪp/")

# Unit 7 上册: robots/future
add_phonetic(['paper'], "/'peɪpə(r)/")
add_phonetic(['pollution'], "/pə'luːʃn/")
add_phonetic(['environment'], "/ɪn'vaɪrənmənt/")
add_phonetic(['planet'], "/'plænɪt/")
add_phonetic(['earth'], "/ɜːθ/")
add_phonetic(['plant'], "/plɑːnt/")
add_phonetic(['part'], "/pɑːt/")
add_phonetic(['peace'], "/piːs/")
add_phonetic(['sky'], "/skaɪ/")
add_phonetic(['water'], "/'wɔːtə(r)/")
add_phonetic(['future'], "/'fjuːtʃə(r)/")
add_phonetic(['build'], "/bɪld/")
add_phonetic(['astronaut'], "/'æstrənɔːt/")
add_phonetic(['apartment'], "/ə'pɑːtmənt/")
add_phonetic(['space'], "/speɪs/")
add_phonetic(['even'], "/'iːvn/")
add_phonetic(['human'], "/'hjuːmən/")
add_phonetic(['dangerous'], "/'deɪndʒərəs/")
add_phonetic(['already'], "/ɔːl'redi/")
add_phonetic(['factory'], "/'fæktri; 'fæktəri/")
add_phonetic(['believe'], "/bɪ'liːv/")
add_phonetic(['disagree'], "/ˌdɪsə'ɡriː/")
add_phonetic(['shape'], "/ʃeɪp/")
add_phonetic(['fall'], "/fɔːl/")
add_phonetic(['inside'], "/ˌɪn'saɪd/")
add_phonetic(['impossible'], "/ɪm'pɒsəbl/")
add_phonetic(['side'], "/saɪd/")
add_phonetic(['probably'], "/'prɒbəbli/")
add_phonetic(['during'], "/'djʊərɪŋ/")
add_phonetic(['holiday'], "/'hɒlədeɪ; 'hɒlədi/")
add_phonetic(['word'], "/wɜːd/")

# Unit 8 上册: cooking
add_phonetic(['shake'], "/ʃeɪk/")
add_phonetic(['blender'], "/'blendə(r)/")
add_phonetic(['peel'], "/piːl/")
add_phonetic(['cut'], "/kʌt/")
add_phonetic(['yogurt'], "/'jɒɡət; 'jəʊɡɜːt/")
add_phonetic(['ingredient'], "/ɪn'ɡriːdiənt/")
add_phonetic(['cup'], "/kʌp/")
add_phonetic(['spoon'], "/spuːn/")
add_phonetic(['popcorn'], "/'pɒpkɔːn/")
add_phonetic(['salt'], "/sɔːlt; sɒlt/")
add_phonetic(['sugar'], "/'ʃʊɡə(r)/")
add_phonetic(['cheese'], "/tʃiːz/")
add_phonetic(['corn'], "/kɔːn/")
add_phonetic(['machine'], "/mə'ʃiːn/")
add_phonetic(['dig'], "/dɪɡ/")
add_phonetic(['hole'], "/həʊl/")
add_phonetic(['sandwich'], "/'sænwɪdʒ; 'sænwɪtʃ/")
add_phonetic(['butter'], "/'bʌtə(r)/")
add_phonetic(['lettuce'], "/'letɪs/")
add_phonetic(['turkey'], "/'tɜːki/")
add_phonetic(['slice'], "/slaɪs/")
add_phonetic(['traditional'], "/trə'dɪʃənl/")
add_phonetic(['traveler'], "/'trævələ(r)/")
add_phonetic(['England'], "/'ɪŋɡlənd/")
add_phonetic(['celebrate'], "/'selɪbreɪt/")
add_phonetic(['pepper'], "/'pepə(r)/")
add_phonetic(['oven'], "/'ʌvn/")
add_phonetic(['plate'], "/pleɪt/")
add_phonetic(['cover'], "/'kʌvə(r)/")
add_phonetic(['gravy'], "/'ɡreɪvi/")
add_phonetic(['temperature'], "/'temprətʃə(r); 'temprətʃʊə(r)/")
add_phonetic(['serve'], "/sɜːv/")
add_phonetic(['mix'], "/mɪks/")

# Unit 9 上册: invitations
add_phonetic(['prepare'], "/prɪ'peə(r); prɪ'per/")
add_phonetic(['exam'], "/ɪɡ'zæm/")
add_phonetic(['flu'], "/fluː/")
add_phonetic(['available'], "/ə'veɪləbl/")
add_phonetic(['until'], "/ən'tɪl; ʌn'tɪl/")
add_phonetic(['hang'], "/hæŋ/")
add_phonetic(['catch'], "/kætʃ/")
add_phonetic(['invite'], "/ɪn'vaɪt/")
add_phonetic(['accept'], "/ək'sept/")
add_phonetic(['refuse'], "/rɪ'fjuːz/")
add_phonetic(['weekday'], "/'wiːkdeɪ/")
add_phonetic(['reply'], "/rɪ'plaɪ/")
add_phonetic(['forward'], "/'fɔːwəd/")
add_phonetic(['delete'], "/dɪ'liːt/")
add_phonetic(['print'], "/prɪnt/")
add_phonetic(['sad'], "/sæd/")
add_phonetic(['goodbye'], "/ˌɡʊd'baɪ/")
add_phonetic(['preparation'], "/ˌprepə'reɪʃn/")
add_phonetic(['glue'], "/ɡluː/")
add_phonetic(['surprised'], "/sə'praɪzd/")

# Unit 10 上册: conditionals
add_phonetic(['if'], "/ɪf/")
add_phonetic(['tomorrow'], "/tə'mɒrəʊ/")
add_phonetic(['organize'], "/'ɔːɡənaɪz/")
add_phonetic(['video'], "/'vɪdiəʊ/")
add_phonetic(['chocolate'], "/'tʃɒklɪt/")
add_phonetic(['upset'], "/ʌp'set; 'ʌpset/")
add_phonetic(['taxi'], "/'tæksi/")
add_phonetic(['advice'], "/əd'vaɪs/")
add_phonetic(['travel'], "/'trævl/")
add_phonetic(['else'], "/els/")
add_phonetic(['normal'], "/'nɔːml/")
add_phonetic(['certainly'], "/'sɜːtnli/")
add_phonetic(['wallet'], "/'wɒlɪt/")
add_phonetic(['mile'], "/maɪl/")
add_phonetic(['angry'], "/'æŋɡri/")
add_phonetic(['understanding'], "/ˌʌndə'stændɪŋ/")
add_phonetic(['careless'], "/'keələs; 'kerləs/")
add_phonetic(['mistake'], "/mɪ'steɪk/")
add_phonetic(['himself'], "/hɪm'self/")
add_phonetic(['careful'], "/'keəfl; 'kerfl/")
add_phonetic(['advise'], "/əd'vaɪz/")
add_phonetic(['solve'], "/sɒlv/")
add_phonetic(['step'], "/step/")
add_phonetic(['trust'], "/trʌst/")
add_phonetic(['experience'], "/ɪk'spɪəriəns; ik'spɪriəns/")
add_phonetic(['expert'], "/'ekspɜːt/")
add_phonetic(['unless'], "/ən'les/")

# ====== 下册 Unit 1: health problems ======
add_phonetic(['fever'], "/'fiːvə(r)/")
add_phonetic(['cough'], "/kɒf; kɔːf/")
add_phonetic(['toothache'], "/'tuːθeɪk/")
add_phonetic(['headache'], "/'hedeɪk/")
add_phonetic(['stomachache'], "/'stʌməkeɪk/")
add_phonetic(['throat'], "/θrəʊt/")
add_phonetic(['hurt'], "/hɜːt/")
add_phonetic(['lie'], "/laɪ/")
add_phonetic(['rest'], "/rest/")
add_phonetic(['X-ray'], "/'eks reɪ/")
add_phonetic(['matter'], "/'mætə(r)/")
add_phonetic(['trouble'], "/'trʌbl/")
add_phonetic(['passenger'], "/'pæsɪndʒə(r)/")
add_phonetic(['herself'], "/hɜː'self; hə'self/")
add_phonetic(['bandage'], "/'bændɪdʒ/")
add_phonetic(['sick'], "/sɪk/")
add_phonetic(['knee'], "/niː/")
add_phonetic(['hit'], "/hɪt/")
add_phonetic(['risk'], "/rɪsk/")
add_phonetic(['kilo'], "/'kiːləʊ/")
add_phonetic(['rock'], "/rɒk/")
add_phonetic(['blood'], "/blʌd/")
add_phonetic(['mean'], "/miːn/")
add_phonetic(['importance'], "/ɪm'pɔːtns; ɪm'pɔːrtəns/")
add_phonetic(['decision'], "/dɪ'sɪʒn/")
add_phonetic(['control'], "/kən'trəʊl/")
add_phonetic(['spirit'], "/'spɪrɪt/")
add_phonetic(['death'], "/deθ/")
add_phonetic(['nurse'], "/nɜːs/")

# 下册 Unit 2: chores
add_phonetic(['rubbish'], "/'rʌbɪʃ/")
add_phonetic(['fold'], "/fəʊld/")
add_phonetic(['sweep'], "/swiːp/")
add_phonetic(['floor'], "/flɔː(r)/")
add_phonetic(['mess'], "/mes/")
add_phonetic(['neither'], "/'niːðə(r); 'naɪðə(r)/")
add_phonetic(['borrow'], "/'bɒrəʊ/")
add_phonetic(['lend'], "/lend/")
add_phonetic(['finger'], "/'fɪŋɡə(r)/")
add_phonetic(['hate'], "/heɪt/")
add_phonetic(['chore'], "/tʃɔː(r)/")
add_phonetic(['provide'], "/prə'vaɪd/")
add_phonetic(['drop'], "/drɒp/")
add_phonetic(['fair'], "/feə(r)/")
add_phonetic(['unfair'], "/ʌn'feə(r)/")
add_phonetic(['since'], "/sɪns/")
add_phonetic(['neighbor'], "/'neɪbə(r)/")
add_phonetic(['ill'], "/ɪl/")
add_phonetic(['depend'], "/dɪ'pend/")
add_phonetic(['develop'], "/dɪ'veləp/")
add_phonetic(['fairness'], "/'feənəs; 'fernəs/")
add_phonetic(['waste'], "/weɪst/")

# 下册 Unit 3: rainstorm
add_phonetic(['pass'], "/pɑːs; pæs/")
add_phonetic(['cloud'], "/klaʊd/")
add_phonetic(['while'], "/waɪl/")
add_phonetic(['match'], "/mætʃ/")
add_phonetic(['beat'], "/biːt/")
add_phonetic(['against'], "/ə'ɡenst; ə'ɡeɪnst/")
add_phonetic(['rise'], "/raɪz/")
add_phonetic(['completely'], "/kəm'pliːtli/")
add_phonetic(['recently'], "/'riːsntli/")
add_phonetic(['silence'], "/'saɪləns/")
add_phonetic(['date'], "/deɪt/")
add_phonetic(['tower'], "/'taʊə(r)/")
add_phonetic(['truth'], "/truːθ/")
add_phonetic(['pupil'], "/'pjuːpl/")
add_phonetic(['bright'], "/braɪt/")
add_phonetic(['playground'], "/'pleɪɡraʊnd/")
add_phonetic(['bell'], "/bel/")

# 下册 Unit 4: storm
add_phonetic(['storm'], "/stɔːm/")
add_phonetic(['wind'], "/wɪnd/")
add_phonetic(['light'], "/laɪt/")
add_phonetic(['area'], "/'eəriə; 'eriə/")
add_phonetic(['wood'], "/wʊd/")
add_phonetic(['window'], "/'wɪndəʊ/")
add_phonetic(['flashlight'], "/'flæʃlaɪt/")
add_phonetic(['asleep'], "/ə'sliːp/")
add_phonetic(['fallen'], "/'fɔːlən/")
add_phonetic(['apart'], "/ə'pɑːt/")
add_phonetic(['icy'], "/'aɪsi/")
add_phonetic(['realize'], "/'rɪəlaɪz; 'riːəlaɪz/")
add_phonetic(['passage'], "/'pæsɪdʒ/")

# 下册 Unit 5-6: more stories
add_phonetic(['rainstorm'], "/'reɪnstɔːm/")
add_phonetic(['alarm'], "/ə'lɑːm/")
add_phonetic(['begin'], "/bɪ'ɡɪn/")
add_phonetic(['heavily'], "/'hevɪli/")
add_phonetic(['strange'], "/streɪndʒ/")
add_phonetic(['rising'], "/'raɪzɪŋ/")
add_phonetic(['die down'], "/daɪ daʊn/")
add_phonetic(['pick up'], "/pɪk ʌp/")
add_phonetic(['at first'], "/ət fɜːst/")
add_phonetic(['fall asleep'], "/fɔːl ə'sliːp/")
add_phonetic(['go off'], "/ɡəʊ ɒf/")
add_phonetic(['make sure'], "/meɪk ʃʊə(r)/")
add_phonetic(['wait for'], "/weɪt fɔː(r)/")
add_phonetic(['call in'], "/kɔːl ɪn/")
add_phonetic(['get a ride to'], "/ɡet ə raɪd tuː/")
add_phonetic(['by the time'], "/baɪ ðə taɪm/")
add_phonetic(['give...a lift'], "/ɡɪv...ə lɪft/")
add_phonetic(['show up'], "/ʃəʊ ʌp/")
add_phonetic(['line up'], "/laɪn ʌp/")
add_phonetic(['go into'], "/ɡəʊ ˈɪntuː/")
add_phonetic(['sell out'], "/sel aʊt/")
add_phonetic(['play a trick on'], "/pleɪ ə trɪk ɒn/")
add_phonetic(['lose weight'], "/luːz weɪt/")
add_phonetic(['get married'], "/ɡet ˈmærɪd/")
add_phonetic(['end up'], "/end ʌp/")
add_phonetic(['fool'], "/fuːl/")
add_phonetic(['costume'], "/ˈkɒstjuːm; 'kɑːstuːm/")
add_phonetic(['embarrassed'], "/ɪm'bærəst/")
add_phonetic(['cancel'], "/ˈkænsl/")
add_phonetic(['officer'], "/ˈɒfɪsə(r)/")
add_phonetic(['believable'], "/bɪ'liːvəbl/")
add_phonetic(['disappear'], "/ˌdɪsəˈpɪə(r)/")
add_phonetic(['announce'], "/əˈnaʊns/")
add_phonetic(['spaghetti'], "/spəˈɡeti/")
add_phonetic(['hoax'], "/həʊks/")
add_phonetic(['discovery'], "/dɪ'skʌvəri/")
add_phonetic(['maiden'], "/ˈmeɪdn/")
add_phonetic(['Italy'], "/'ɪtəli/")
add_phonetic(['oversleep'], "/ˌəʊvəˈsliːp/")
add_phonetic(['land'], "/lænd/")
add_phonetic(['unfold'], "/ʌnˈfəʊld/")
add_phonetic(['all over the world'], "/ɔːl əʊvə ðə wɜːld/")
add_phonetic(['no more'], "/nəʊ mɔː(r)/")
add_phonetic(['in panic'], "/ɪn ˈpænɪk/")

# 下册 Unit 7: island/treasure
add_phonetic(['island'], "/ˈaɪlənd/")
add_phonetic(['treasure'], "/ˈtreʒə(r)/")
add_phonetic(['full of'], "/fʊl əv/")
add_phonetic(['classic'], "/ˈklæsɪk/")
add_phonetic(['page'], "/peɪdʒ/")
add_phonetic(['hurry'], "/ˈhʌri/")
add_phonetic(['due to'], "/djuː tuː/")
add_phonetic(['ship'], "/ʃɪp/")
add_phonetic(['tool'], "/tuːl/")
add_phonetic(['gun'], "/ɡʌn/")
add_phonetic(['mark'], "/mɑːk/")
add_phonetic(['sand'], "/sænd/")
add_phonetic(['cannibal'], "/ˈkænɪbl/")
add_phonetic(['Frenchman'], "/ˈfrentʃmən/")
add_phonetic(['towards'], "/təˈwɔːdz/")
add_phonetic(['fiction'], "/ˈfɪkʃn/")
add_phonetic(['technology'], "/tekˈnɒlədʒi/")
add_phonetic(['science'], "/ˈsaɪəns/")
add_phonetic(['fantasy'], "/ˈfæntəsi/")
add_phonetic(['hurry up'], "/ˈhʌri ʌp/")
add_phonetic(['arrive at/in'], "/əˈraɪv æt/ɪn/")
add_phonetic(['cut down'], "/kʌt daʊn/")
add_phonetic(['bring back to life'], "/brɪŋ bæk tuː laɪf/")
add_phonetic(['the number of'], "/ðə ˈnʌmbə(r) əv/")
add_phonetic(['used to'], "/juːst tuː/")
add_phonetic(['read about'], "/riːd əˈbaʊt/")
add_phonetic(['finish reading'], "/ˈfɪnɪʃ ˈriːdɪŋ/")

# 下册 Unit 8: volunteering
add_phonetic(['survey'], "/ˈsɜːveɪ/")
add_phonetic(['standard'], "/ˈstændəd/")
add_phonetic(['usual'], "/ˈjuːʒuəl/")
add_phonetic(['perhaps'], "/pəˈhæps/")
add_phonetic(['text'], "/tekst/")
add_phonetic(['typical'], "/ˈtɪpɪkl/")
add_phonetic(['worth'], "/wɜːθ/")
add_phonetic(['copy'], "/ˈkɒpi/")
add_phonetic(['speed'], "/spiːd/")
add_phonetic(['mention'], "/ˈmenʃn/")
add_phonetic(['overall'], "/ˌəʊvəˈrɔːl/")
add_phonetic(['wild'], "/waɪld/")
add_phonetic(['outside'], "/ˌaʊtˈsaɪd/")
add_phonetic(['additional'], "/əˈdɪʃənl/")
add_phonetic(['textbook'], "/ˈtekstbʊk/")
add_phonetic(['shoot'], "/ʃuːt/")
add_phonetic(['thorn'], "/θɔːrn/")
add_phonetic(['tie'], "/taɪ/")
add_phonetic(['suggestion'], "/səˈdʒestʃən/")
add_phonetic(['consider'], "/kənˈsɪdə(r)/")
add_phonetic(['sudden'], "/ˈsʌdn/")
add_phonetic(['weigh'], "/weɪ/")
add_phonetic(['path'], "/pɑːθ; pæθ/")
add_phonetic(['general'], "/ˈdʒenrəl/")
add_phonetic(['society'], "/səˈsaɪəti/")
add_phonetic(['aim'], "/eɪm/")
add_phonetic(['effort'], "/ˈefət/")
add_phonetic(['duty'], "/ˈdjuːti/")
add_phonetic(['context'], "/ˈkɒntekst/")
add_phonetic(['expect'], "/ɪkˈspekt/")
add_phonetic(['position'], "/pəˈzɪʃn/")
add_phonetic(['support'], "/səˈpɔːt/")
add_phonetic(['social'], "/ˈsəʊʃl/")
add_phonetic(['volunteer'], "/ˌvɒlənˈtɪə(r)/")
add_phonetic(['notice'], "/ˈnəʊtɪs/")
add_phonetic(["change one's mind"], "/tʃeɪndʒ wʌnz maɪnd/")
add_phonetic(['open up'], "/ˈəʊpən ʌp/")
add_phonetic(['by the way'], "/baɪ ðə weɪ/")
add_phonetic(['plenty of'], "/ˈplenti əv/")
add_phonetic(['give away'], "/ɡɪv əˈweɪ/")
add_phonetic(['set up'], "/set ʌp/")
add_phonetic(['think of'], "/θɪŋk əv/")
add_phonetic(['come up with'], "/kʌm ʌp wɪð/")
add_phonetic(['put off'], "/pʊt ɒf/")
add_phonetic(['write down'], "/raɪt daʊn/")
add_phonetic(['cheer up'], "/tʃɪə(r) ʌp/")
add_phonetic(['call up'], "/kɔːl ʌp/")
add_phonetic(['put up'], "/pʊt ʌp/")
add_phonetic(['hand out'], "/hænd aʊt/")
add_phonetic(['give out'], "/ɡɪv aʊt/")
add_phonetic(['work out'], "/wɜːk aʊt/")
add_phonetic(['fix up'], "/fɪks ʌp/")
add_phonetic(['take after'], "/teɪk ˈɑːftə(r)/")

# 下册 Unit 9: museums/travel
add_phonetic(['amusement'], "/əˈmjuːzmənt/")
add_phonetic(['somewhere'], "/ˈsʌmweə(r)/")
add_phonetic(['camera'], "/ˈkæm(ə)rə/")
add_phonetic(['invention'], "/ɪnˈvenʃn/")
add_phonetic(['unbelievable'], "/ˌʌnbɪˈliːvəbl/")
add_phonetic(['progress'], "/ˈprəʊɡres; əˈprəʊɡres/")
add_phonetic(['rapid'], "/ˈræpɪd/")
add_phonetic(['unusual'], "/ʌnˈjuːʒuəl/")
add_phonetic(['toilet'], "/ˈtɔɪlət/")
add_phonetic(['encourage'], "/ɪnˈkʌrɪdʒ; ɪnˈkɜːrɪdʒ/")
add_phonetic(['peaceful'], "/ˈpiːsfl/")
add_phonetic(['perfect'], "/ˈpɜːfɪkt; pərfekt/")
add_phonetic(['itself'], "/ɪtˈself/")
add_phonetic(['collect'], "/kəˈlekt/")
add_phonetic(['German'], "/ˈdʒɜːmən/")
add_phonetic(['theme'], "/θiːm/")
add_phonetic(['ride'], "/raɪd/")
add_phonetic(['province'], "/ˈprɒvɪns/")
add_phonetic(['thousand'], "/ˈθaʊznd/")
add_phonetic(['safe'], "/seɪf/")
add_phonetic(['simply'], "/ˈsimpli/")
add_phonetic(['fear'], "/fɪə(r); fɪr/")
add_phonetic(['whether'], "/ˈweðə(r)/")
add_phonetic(['Indian'], "/ˈɪndiən/")
add_phonetic(['Japanese'], "/ˌdʒæpəˈniːz/")
add_phonetic(['fox'], "/fɒks/")
add_phonetic(['whenever'], "/wenˈevə(r)/")
add_phonetic(['spring'], "/sprɪŋ/")
add_phonetic(['mostly'], "/ˈməʊstli/")
add_phonetic(['location'], "/ləʊˈkeɪʃn/")
add_phonetic(['have been to'], "/hæv biːn tuː/")
add_phonetic(['thousands of'], "/ˈθaʊzndz əv/")
add_phonetic(['on the one hand'], "/ɒn ðə wʌn hænd/")
add_phonetic(['on the other hand'], "/ɒn ðiˌʌðə(r) hænd/")
add_phonetic(['all year round'], "/ɔːl jɪə raʊnd/")
add_phonetic(['an English-speaking country'], "/ən ˈɪŋɡlɪʃ spiːkɪŋ ˈkʌntri/")
add_phonetic(['feel free'], "/fiːl friː/")
add_phonetic(['a couple of'], "/ə ˈkʌpl əv/")
add_phonetic(['three quarters of'], "/θriː ˈkwɔːtəz əv/")
add_phonetic(['take a holiday'], "/teɪk ə ˈhɒlədeɪ/")
add_phonetic(['an island'], "/ən ˈaɪlənd/")
add_phonetic(['year round'], "/jɪə raʊnd/")
add_phonetic(['whether or not'], "/ˈweðə(r) ɔː(r) nɒt/")
add_phonetic(['the population of'], "/ðə ˌpɒpjuˈleɪʃn əv/")
add_phonetic(['in fact'], "/ɪn fækt/")
add_phonetic(['during the daytime'], "/ˈdjʊərɪŋ ðə ˈdeɪtaɪm/")

# 下册 Unit 10: feelings/memories
add_phonetic(['development'], "/dɪˈveləpmənt/")
add_phonetic(['happiness'], "/ˈhæpinəs/")
add_phonetic(['sadness'], "/ˈsædnəs/")
add_phonetic(['joy'], "/dʒɔɪ/")
add_phonetic(['purpose'], "/ˈpɜːpəs; ˈpɜːrpəs/")
add_phonetic(['return'], "/rɪˈtɜːn/")
add_phonetic(['expression'], "/ɪkˈspreʃn; ekˈspreʃn/")
add_phonetic(['satisfaction'], "/ˌsætɪsˈfækʃn/")
add_phonetic(['pleasure'], "/ˈpleʒə(r)/")

# ===== 补充常用词汇（源数据中的其他词）=====
add_phonetic(['Internet'], "/'ɪntənet/")
add_phonetic(['ability'], "/əˈbɪləti/")
add_phonetic(['above'], "/əˈbʌv/")
add_phonetic(['abroad'], "/əˈbrɔːd/")
add_phonetic(['accept'], "/əkˈsept/")
add_phonetic(['accident'], "/ˈæksɪdənt/")
add_phonetic(['achieve'], "/əˈtʃiːv/")
add_phonetic(['achievement'], "/əˈtʃiːvmənt/")
add_phonetic(['across'], "/əˈkrɒs/")
add_phonetic(['active'], "/ˈæktɪv/")
add_phonetic(['actually'], "/ˈæktʃuəli/")
add_phonetic(['addition'], "/əˈdɪʃn/")
add_phonetic(['address'], "/əˈdres/")
add_phonetic(['admire'], "/ədˈmaɪə(r)/")
add_phonetic(['admit'], "/ədˈmɪt/")
add_phonetic(['adult'], "/ˈædʌlt/")
add_phonetic(['advantage'], "/ədˈvɑːntɪdʒ/")
add_phonetic(['adventure'], "/ədˈventʃə(r)/")
add_phonetic(['affect'], "/əˈfekt/")
add_phonetic(['afford'], "/əˈfɔːd/")
add_phonetic(['afraid'], "/əˈfreɪd/")
add_phonetic(['age'], "/eɪdʒ/")
add_phonetic(['agree'], "/əˈɡriː/")
add_phonetic(['agreement'], "/əˈɡriːmənt/")
add_phonetic(['air'], "/eə(r)/")
add_phonetic(['airplane'], "/ˈeəpleɪn/")
add_phonetic(['airport'], "/ˈeəpɔːt/")
add_phonetic(['album'], "/ˈælbəm/")
add_phonetic(['alive'], "/əˈlaɪv/")
add_phonetic(['alone'], "/əˈləʊn/")
add_phonetic(['also'], "/ˈɔːlsəʊ/")
add_phonetic(['always'], "/ˈɔːlweɪz/")
add_phonetic(['amazing'], "/əˈmeɪzɪŋ/")
add_phonetic(['among'], "/əˈmʌŋ/")
add_phonetic(['ancient'], "/ˈeɪnʃənt/")
add_phonetic(['and'], "/ænd; ən; n/")
add_phonetic(['animal'], "/ˈænɪml/")
add_phonetic(['announce'], "/əˈnaʊns/")
add_phonetic(['another'], "/əˈnʌðə(r)/")
add_phonetic(['answer'], "/ˈɑːnsə(r)/")
add_phonetic(['anybody'], "/ˈenibɒdi/")
add_phonetic(['anything'], "/ˈeniθɪŋ/")
add_phonetic(['anyway'], "/ˈeniweɪ/")
add_phonetic(['apologize'], "/əˈpɒlədʒaɪz/")
add_phonetic(['appearance'], "/əˈpɪərəns/")
add_phonetic(['application'], "/ˌæplɪˈkeɪʃn/")
add_phonetic(['apply'], "/əˈplaɪ/")
add_phonetic(['appreciate'], "/əˈpriːʃieɪt/")
add_phonetic(['area'], "/ˈeəriə/")
add_phonetic(['argue'], "/ˈɑːɡjuː/")
add_phonetic(['argument'], "/ˈɑːɡjumənt/")
add_phonetic(['around'], "/əˈraʊnd/")
add_phonetic(['arrange'], "/əˈreɪndʒ/")
add_phonetic(['article'], "/ˈɑːtɪkl/")
add_phonetic(['attention'], "/əˈtenʃn/")
add_phonetic(['attitude'], "/ˈætɪtjuːd/")
add_phonetic(['attract'], "/əˈtrækt/")
add_phonetic(['aunt'], "/ɑːnt/")
add_phonetic(['avoid'], "/əˈvɔɪd/")
add_phonetic(['awake'], "/əˈweɪk/")
add_phonetic(['award'], "/əˈwɔːd/")
add_phonetic(['away'], "/əˈweɪ/")
add_phonetic(['awesome'], "/ˈɔːsəm/")
add_phonetic(['awful'], "/ˈɔːfl/")
add_phonetic(['baby'], "/ˈbeɪbi/")
add_phonetic(['back'], "/bæk/")
add_phonetic(['background'], "/ˈbækɡraʊnd/")
add_phonetic(['bad'], "/bæd/")
add_phonetic(['badly'], "/ˈbædli/")
add_phonetic(['bag'], "/bæg/")
add_phonetic(['balance'], "/ˈbæləns/")
add_phonetic(['balcony'], "/ˈbælkəni/")
add_phonetic(['ball'], "/bɔːl/")
add_phonetic(['bank'], "/bæŋk/")
add_phonetic(['bargain'], "/ˈbɑːɡɪn/")
add_phonetic(['basic'], "/ˈbeɪsɪk/")
add_phonetic(['bath'], "/bɑːθ/")
add_phonetic(['bathroom'], "/ˈbɑːθruːm/")
add_phonetic(['be able to'], "/biː ˈeɪbl tuː/")
add_phonetic(['be used to'], "/biː juːst tuː/")
add_phonetic(['beach'], "/biːtʃ/")
add_phonetic(['bear'], "/beə(r)/")
add_phonetic(['beautiful'], "/ˈbjuːtɪfl/")
add_phonetic(['because'], "/bɪˈkɒz/")
add_phonetic(['bed'], "/bed/")
add_phonetic(['bedroom'], "/ˈbedruːm/")
add_phonetic(['beef'], "/biːf/")
add_phonetic(['behavior'], "/bɪˈheɪvjə(r)/")
add_phonetic(['behind'], "/bɪˈhaɪnd/")
add_phonetic(['belt'], "/belt/")
add_phonetic(['benefit'], "/ˈbenɪfɪt/")
add_phonetic(['beside'], "/bɪˈsaɪd/")
add_phonetic(['besides'], "/bɪˈsaɪdz/")
add_phonetic(['between'], "/bɪˈtwiːn/")
add_phonetic(['big'], "/bɪɡ/")
add_phonetic(['bill'], "/bɪl/")
add_phonetic(['biology'], "/baɪˈɒlədʒi/")
add_phonetic(['birth'], "/bɜːθ/")
add_phonetic(['biscuit'], "/ˈbɪskɪt/")
add_phonetic(['bite'], "/baɪt/")
add_phonetic(['blackboard'], "/ˈblækbɔːd/")
add_phonetic(['blend'], "/blend/")
add_phonetic(['blood'], "/blʌd/")
add_phonetic(['blow'], "/bləʊ/")
add_phonetic(['body'], "/ˈbɒdi/")
add_phonetic(['boil'], "/bɔɪl/")
add_phonetic(['book'], "/bʊk/")
add_phonetic(['boring'], "/ˈbɔːrɪŋ/")
add_phonetic(['bother'], "/ˈbɒðə(r)/")
add_phonetic(['bottle'], "/ˈbɒtl/")
add_phonetic(['bottom'], "/ˈbɒtəm/")
add_phonetic(['bounce'], "/baʊns/")
add_phonetic(['bowl'], "/bəʊl/")
add_phonetic(['box'], "/bɒks/")
add_phonetic(['brain'], "/breɪn/")
add_phonetic(['brave'], "/breɪv/")
add_phonetic(['bread'], "/bred/")
add_phonetic(['breakfast'], "/ˈbrekfəst/")
add_phonetic(['breath'], "/breθ/")
add_phonetic(['bridge'], "/brɪdʒ/")
add_phonetic(['brother'], "/ˈbrʌðə(r)/")
add_phonetic(['brush'], "/brʌʃ/")
add_phonetic(['burn'], "/bɜːn/")
add_phonetic(['bury'], "/ˈberi/")
add_phonetic(['bus'], "/bʌs/")
add_phonetic(['business'], "/ˈbɪznəs/")
add_phonetic(['busy'], "/ˈbɪzi/")
add_phonetic(['but'], "/bʌt; bət/")
add_phonetic(['buyer'], "/ˈbaɪə(r)/")
add_phonetic(['cafe'], "/ˈkæfeɪ/")
add_phonetic(['cake'], "/keɪk/")
add_phonetic(['calculate'], "/ˈkækjuleɪt/")
add_phonetic(['calendar'], "/ˈkælɪndə(r)/")
add_phonetic(['call'], "/kɔːl/")
add_phonetic(['calm'], "/kɑːm/")
add_phonetic(['camp'], "/kæmp/")
add_phonetic(['campus'], "/ˈkæmpəs/")
add_phonetic(['cap'], "/kæp/")
add_phonetic(['capable'], "/ˈkeɪpəbl/")
add_phonetic(['capital'], "/ˈkæpɪtl/")
add_phonetic(['captain'], "/ˈkæptɪn/")
add_phonetic(['car'], "/kɑː(r)/")
add_phonetic(['card'], "/kɑːd/")
add_phonetic(['carry'], "/ˈkæri/")
add_phonetic(['carry on'], "/ˈkæri ɒn/")
add_phonetic(['cash'], "/kæʃ/")
add_phonetic(['cat'], "/kæt/")
add_phonetic(['cause'], "/kɔːz/")
add_phonetic(['check'], "/tʃek/")
add_phonetic(['climb'], "/klaɪm/")
add_phonetic(['collect'], "/kəˈlekt/")
add_phonetic(['come'], "/kʌm/")
add_phonetic(['compare'], "/kəmˈpeə(r)/")
add_phonetic(['complete'], "/kəmˈpliːt/")
add_phonetic(['continue'], "/kənˈtɪnjuː/")
add_phonetic(['correct'], "/kəˈrekt/")
add_phonetic(['cost'], "/kɒst/")
add_phonetic(['count'], "/kaʊnt/")
add_phonetic(['create'], "/kriˈeɪt/")
add_phonetic(['cross'], "/krɒs/")
add_phonetic(['cry'], "/kraɪ/")
add_phonetic(['dance'], "/dɑːns; dæns/")
add_phonetic(['danger'], "/ˈdeɪndʒə/")
add_phonetic(['describe'], "/dɪˈskraɪb/")
add_phonetic(['discover'], "/dɪˈskʌvə(r)/")
add_phonetic(['do'], "/duː/")
add_phonetic(['draw'], "/drɔː/")
add_phonetic(['drive'], "/draɪv/")
add_phonetic(['drink'], "/drɪŋk/")
add_phonetic(['eat'], "/iːt/")
add_phonetic(['example'], "/ɪɡˈzɑːmpl/")
add_phonetic(['exercise'], "/ˈeksəsaɪz/")
add_phonetic(['explain'], "/ɪkˈspleɪn/")
add_phonetic(['fight'], "/faɪt/")
add_phonetic(['fill'], "/fɪl/")
add_phonetic(['find'], "/faɪnd/")
add_phonetic(['fly'], "/flaɪ/")
add_phonetic(['forget'], "/fəˈɡet/")
add_phonetic(['friend'], "/frend/")
add_phonetic(['fruit'], "/fruːt/")
add_phonetic(['get'], "/ɡet/")
add_phonetic(['go'], "/ɡəʊ/")
add_phonetic(['guess'], "/ɡes/")
add_phonetic(['have'], "/hæv; həv/")
add_phonetic(['hear'], "/hɪə(r)/")
add_phonetic(['help'], "/help/")
add_phonetic(['hold'], "/həʊld/")
add_phonetic(['hope'], "/həʊp/")
add_phonetic(['imagine'], "/ɪˈmædʒɪn/")
add_phonetic(['include'], "/ɪnˈkluːd/")
add_phonetic(['increase'], "/ɪnˈkriːs/")
add_phonetic(['interview'], "/ˈɪntəvjuː/")
add_phonetic(['introduce'], "/ˌɪntrəˈdjuːs/")
add_phonetic(['join'], "/dʒɔɪn/")
add_phonetic(['keep'], "/kiːp/")
add_phonetic(['kill'], "/kɪl/")
add_phonetic(['know'], "/nəʊ/")
add_phonetic(['land'], "/lænd/")
add_phonetic(['lay'], "/leɪ/")
add_phonetic(['lead'], "/liːd/")
add_phonetic(['learn'], "/lɜːn/")
add_phonetic(['leave'], "/liːv/")
add_phonetic(['lift'], "/lɪft/")
add_phonetic(['like'], "/laɪk/")
add_phonetic(['listen'], "/ˈlɪsn/")
add_phonetic(['live'], "/lɪv/")
add_phonetic(['love'], "/lʌv/")
add_phonetic(['make'], "/meɪk/")
add_phonetic(['meet'], "/miːt/")
add_phonetic(['miss'], "/mɪs/")
add_phonetic(['move'], "/muːv/")
add_phonetic(['need'], "/niːd/")
add_phonetic(['offer'], "/ˈɒfə(r)/")
add_phonetic(['open'], "/ˈəʊpn/")
add_phonetic(['order'], "/ˈɔːdə(r)/")
add_phonetic(['pay'], "/peɪ/")
add_phonetic(['pick'], "/pɪk/")
add_phonetic(['practice'], "/ˈpræktɪs/")
add_phonetic(['produce'], "/prəˈdjuːs/")
add_phonetic(['pull'], "/pʊl/")
add_phonetic(['push'], "/pʊʃ/")
add_phonetic(['put'], "/pʊt/")
add_phonetic(['quickly'], "/ˈkwɪkli/")
add_phonetic(['quite'], "/kwaɪt/")
add_phonetic(['raise'], "/reɪz/")
add_phonetic(['read'], "/riːd/")
add_phonetic(['remember'], "/rɪˈmembə(r)/")
add_phonetic(['remind'], "/rɪˈmaɪnd/")
add_phonetic(['require'], "/rɪˈwaɪə(r)/")
add_phonetic(['run'], "/rʌn/")
add_phonetic(['say'], "/seɪ/")
add_phonetic(['see'], "/siː/")
add_phonetic(['sell'], "/sel/")
add_phonetic(['serve'], "/sɜːv/")
add_phonetic(['set'], "/set/")
add_phonetic(['shout'], "/ʃaʊt/")
add_phonetic(['shut'], "/ʃʌt/")
add_phonetic(['sing'], "/sɪŋ/")
add_phonetic(['sit'], "/sɪt/")
add_phonetic(['sleep'], "/sliːp/")
add_phonetic(['smell'], "/smel/")
add_phonetic(['smile'], "/smaɪl/")
add_phonetic(['sound'], "/saʊnd/")
add_phonetic(['speak'], "/spiːk/")
add_phonetic(['spend'], "/spend/")
add_phonetic(['stand'], "/stænd/")
add_phonetic(['start'], "/stɑːt/")
add_phonetic(['stay'], "/steɪ/")
add_phonetic(['stop'], "/stɒp/")
add_phonetic(['study'], "/ˈstʌdi/")
add_phonetic(['suggest'], "/səˈdʒest/")
add_phonetic(['supply'], "/səˈplaɪ/")
add_phonetic(['surprise'], "/səˈpraɪz/")
add_phonetic(['swim'], "/swɪm/")
add_phonetic(['take'], "/teɪk/")
add_phonetic(['talk'], "/tɔːk/")
add_phonetic(['teach'], "/tiːtʃ/")
add_phonetic(['tell'], "/tel/")
add_phonetic(['throw'], "/θrəʊ/")
add_phonetic(['translate'], "/trænsˈleɪt/")
add_phonetic(['turn'], "/tɜːn/")
add_phonetic(['type'], "/taɪp/")
add_phonetic(['understand'], "/ˌʌndəˈstænd/")
add_phonetic(['use'], "/juːz; juːs/")
add_phonetic(['visit'], "/ˈvɪzɪt/")
add_phonetic(['wake'], "/weɪk/")
add_phonetic(['walk'], "/wɔːk/")
add_phonetic(['want'], "/wɒnt/")
add_phonetic(['wash'], "/wɒʃ/")
add_phonetic(['watch'], "/wɒtʃ/")
add_phonetic(['wave'], "/weɪv/")
add_phonetic(['wear'], "/weə(r)/")
add_phonetic(['wish'], "/wɪʃ/")
add_phonetic(['write'], "/raɪt/")
add_phonetic(['wrong'], "/rɒŋ/")
add_phonetic(['yard'], "/jɑːd/")
add_phonetic(['yet'], "/jet/")
add_phonetic(['young'], "/jʌŋ/")
add_phonetic(['younger'], "/ˈjʌŋɡə(r)/")


# ============================================================
# 学期分配
# ============================================================
SEM1_WORDS = set("""
anyone anywhere wonderful few most myself yourself hen seem bored activity decide try paragliding bird building wonder difference top wait umbrella wet below enough hungry as hill diary enjoy dislike housework hardly ever once twice internet program full swing maybe least junk coffee health result percent although through such together die writer magazine however than almost none less point outgoing better loudly quietly hard-working competition fantastic clearly win though care talented truly necessary both which grade should bring information touch heart break arm laugh similar share loud primary reach hand kid fact theater comfortable screen close ticket worst cheaply song choose action role simple report service pretty meal fresh creativity performer crowd poor give seat menu act without discuss situation expect happen cartoon culture famous appear become rich successful might main reason film unlucky lose ready character army face own art paint create describe look educational plan joke meaningless enjoyable grow computer programmer cook doctor engineer violinist driver pilot pianist scientist college education medicine university article send resolution team foreign able question meaning discuss promise beginning improve physical self-improvement hobby weekly schoolwork personal relationship paper pollution environment planet earth plant part peace sky water future build astronaut apartment space even human dangerous already factory believe disagree shape fall inside impossible side probably during holiday word shake blender peel cut yogurt ingredient cup spoon popcorn salt sugar cheese corn machine dig hole sandwich butter lettuce turkey slice traditional traveler England celebrate pepper oven plate cover gravy temperature serve mix prepare exam flu available until hang catch invite accept refuse weekday reply forward delete print sad goodbye preparation glue surprised if tomorrow organize video chocolate upset taxi advice travel else normal certainly wallet mile angry understanding careless mistake himself careful advise solve step trust experience expert unless""".split())

SEM2_WORDS = set("""
fever cough toothache headache stomachache throat hurt lie rest X-ray matter trouble passenger herself bandage sick knee hit risk kilo rock blood mean importance decision control spirit death nurse rubbish fold sweep floor mess neither borrow lend finger hate chore provide anyway drop fair unfair since neighbor ill depend develop fairness waste pass cloud while match beat against rise report completely recently silence date tower truth pupil bright playground bell storm wind light area wood window flashlight asleep fallen apart icy realize passage rainstorm alarm begin heavily strange rising die down pick up at first fall asleep go off make sure wait for call in get a ride to by the time give lift show up line up go into sell out play a trick on lose weight get married end up fool costume embarrassed cancel officer believable disappear announce spaghetti hoax discovery maiden Italy oversleep land unfold all over the world no more in panic island treasure full of classic page hurry due to ship tool gun mark sand cannibal Frenchman towards fiction technology science fantasy hurry up arrive at cut down bring back to life the number of used to read about finish reading survey standard usual perhaps text typical worth copy speed mention overall wild outside additional textbook adult shoot thorn tie suggestion consider sudden weigh path general society aim effort duty context expect position support social volunteer notice change ones mind open up by the way plenty of give away set up think of come up with put off write down cheer up call up put up hand out give out work out fix up take after think up amusement somewhere camera invention unbelievable progress rapid unusual toilet encourage peaceful perfect itself collect German theme ride province thousand safe simply fear whether Indian Japanese fox whenever spring mostly location have been to thousands of on the one hand on the other hand all year round an English-speaking country feel free a couple of three quarters of take a holiday an island year round whether or not the population of in fact during the daytime encourage development happiness sadness joy purpose return expression satisfaction pleasure satisfaction sadness joy pleasure satisfaction sadness joy pleasure satisfaction sadness joy pleasure satisfaction sadness joy pleasure satisfaction sadness joy""".split())


def get_semester(word):
    w = word.lower().strip()
    if w in SEM1_WORDS:
        return "上册"
    elif w in SEM2_WORDS:
        return "下册"
    else:
        c = w[0] if w else 'a'
        return "上册" if c <= 'm' else "下册"


def main():
    print("=" * 60)
    print("初二（8年级）英语听写词库生成")
    print("=" * 60)

    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        src_data = json.load(f)
    src_words = src_data['words']
    total_src = len(src_words)
    print(f"\n[1] 源数据: {total_src} 词, 音标字典: {len(PHONETIC_DICT)} 条")

    output = []
    missing_phon = []
    idx = 1

    for key in sorted(src_words.keys()):
        wd = src_words[key]
        w = wd.get('word', key)
        meaning = wd.get('meaning', '').strip()
        example = wd.get('example', '').strip()

        # 查找音标
        ph = PHONETIC_DICT.get(w) or PHONETIC_DICT.get(w.lower())
        if not ph:
            ph = f"/{w}/"
            missing_phon.append(w)

        semester = get_semester(w)

        if not example:
            example = f"Please spell {w}."

        output.append({
            "id": f"en_g8_{idx:04d}",
            "word": w,
            "meaning": meaning,
            "grade": 8,
            "semester": semester,
            "phonetic": ph,
            "example": example
        })
        idx += 1

    # 统计
    s1 = sum(1 for e in output if e['semester'] == '上册')
    s2 = sum(1 for e in output if e['semester'] == '下册')

    print(f"\n[2] 转换完成:")
    print(f"  总计:   {len(output)} 条")
    print(f"  上册:   {s1} ({s1/max(len(output),1)*100:.1f}%)")
    print(f"  下册:   {s2} ({s2/max(len(output),1)*100:.1f}%)")
    print(f"  缺音标: {len(missing_phon)} 个")

    # 写入文件
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    print(f"\n[3] 已输出: {OUTPUT_FILE}")

    # 验证报告
    print(f"\n{'='*60}")
    print("验证报告")
    print(f"{'='*60}")
    has_ph = sum(1 for e in output if e['phonetic'])
    has_ex = sum(1 for e in output if e['example'])
    uniq_id = len(set(e['id'] for e in output))
    print(f"总词数:     {len(output)}")
    print(f"ID范围:     en_g8_0001 ~ en_g8_{len(output):04d}")
    print(f"上册:       {s1}")
    print(f"下册:       {s2}")
    print(f"有音标:     {has_ph}/{len(output)}")
    print(f"有例句:     {has_ex}/{len(output)}")
    print(f"ID唯一:     {'OK' if uniq_id == len(output) else 'FAIL'}")
    print(f"JSON有效:   OK")

    print(f"\n前5条样例:")
    for e in output[:5]:
        print(f"  {e['id']}: {e['word']:18s} {e['phonetic']:22s} [{e['semester']}] {e['meaning']}")

    print(f"\n后5条样例:")
    for e in output[-5:]:
        print(f"  {e['id']}: {e['word']:18s} {e['phonetic']:22s} [{e['semester']}] {e['meaning']}")

    if missing_phon:
        print(f"\n缺少真实音标的词汇({len(missing_phon)}个):")
        for w in missing_phon:
            print(f"  {w}")

    return output


if __name__ == '__main__':
    main()
