#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate 800-word junior high year 2 vocabulary network JSON for 人教版八年级."""
import json, os

words = {}
def add(w, m, cat, tier, freq, assoc, conf, ex, tip):
    words[w] = {"word":w,"meaning":m,"category":cat,"tier":tier,"frequency":freq,"associations":assoc,"confusables":conf,"example":ex,"memory_tip":tip}

# ===== TIER 1 CORE VERBS (200) =====
V = "verb"
add("advice","建议；忠告","noun",1,"high",["suggest","opinion","recommend","idea"],["advise","advantage"],"Can you give me some advice?","advise动词→advice名词")
add("afford","买得起；负担得起",V,1,"high",["expensive","cheap","money","cost"],["effort","offer"],"I cannot afford to buy a new computer.","af+ford→有财力提供→买得起")
add("agree","同意；赞成",V,1,"high",["disagree","accept","approve","nod"],["argue","allow"],"I agree with you on this matter.","a+gree(高兴)→高兴地同意")
add("allow","允许；准许",V,1,"high",["permit","forbid","let","approve"],["alone","almost"],"My parents dont allow me to play games.","al+low(低)→放低要求→允许")
add("answer","回答；答案",V,1,"high",["question","reply","respond","ask"],["enter","anger"],"Please answer my question.","an+swer→一个答复→回答")
add("appear","出现；似乎",V,1,"high",["disappear","seem","show","emerge"],["appeal","apply"],"A rainbow appeared in the sky.","ap+pear(看见)→能被看见→出现")
add("argue","争论；争辩",V,1,"high",["discuss","fight","debate","agree"],["agree","anger"],"They argued about the best way.","arg(火)+ue→火气上来→争论")
add("arrive","到达；抵达",V,1,"high",["reach","get to","leave","depart"],["around","alive"],"We arrived at the airport early.","ar+rive→到达")
add("beat","打败；敲打；心跳",V,1,"high",["win","defeat","hit","heart"],["eat","heat","meat"],"Our team beat theirs in the match.","beat→打败")
add("become","变成；成为",V,1,"high",["turn into","grow","change","develop"],["because","before"],"She wants to become a doctor.","be+come(来)→来到这个状态→成为")
add("begin","开始",V,1,"high",["start","commence","end","finish"],["began","begun","being"],"Lets begin our class now.","be+gin(进)→开始")
add("believe","相信；认为",V,1,"high",["trust","doubt","faith","think"],["belief","belong"],"I believe you can do it.","be+lieve(爱)→相信")
add("belong","属于",V,1,"high",["own","member","group"],["believe","below"],"This book belongs to the library.","be+long(长久)→属于")
add("borrow","借入",V,1,"high",["lend","keep","return"],["sorrow","tomorrow"],"Can I borrow your pen?","bor+row→借入")
add("break","打破；休息",V,1,"high",["fix","repair","rest","broken"],["brake","bread"],"Be careful not to break the cup.","break→打破")
add("bring","带来；拿来",V,1,"high",["take","fetch","carry","send"],["brink","boring"],"Please bring your textbook to class.","bring→带来")
add("build","建造；建设",V,1,"high",["construct","create","house","make"],["built","building"],"They are building a new school.","build→建造")
add("burn","燃烧；烧伤",V,1,"medium",["fire","hot","flame","heat"],["born","turn"],"Be careful! The pan is burning.","burn→燃烧")
add("buy","买；购买",V,1,"high",["sell","shop","pay","cheap"],["by","bye"],"I want to buy a new phone.","buy→买")
add("call","叫；打电话；称呼",V,1,"high",["phone","ring","name","shout"],["calm","fall","tall"],"Please call me when you get home.","call→叫；打电话")
add("carry","携带；搬运",V,1,"high",["bring","take","lift","hold"],["candy","hurry"],"Can you help me carry these bags?","carry→携带")
add("catch","抓住；赶上；感冒",V,1,"high",["grab","miss","hold","throw"],["watch","match"],"Hurry up, or you will miss the bus.","catch→抓住")
add("cause","原因；导致",V,1,"high",["reason","result","because","effect"],["because","course"],"What caused the accident?","cause→导致")
add("change","改变；变化",V,1,"high",["different","alter","modify","same"],["chance","charge"],"The weather can change quickly.","change→改变")
add("check","检查；核对",V,1,"high",["examine","test","verify","confirm"],["chick","cheek"],"Please check your answers.","check→检查")
add("choose","选择",V,1,"high",["pick","select","decide","choice"],["choice","chose"],"You can choose any color you like.","choose→选择")
add("climb","攀登；爬",V,1,"medium",["mountain","tree","hike","top"],["climate","claim"],"They climbed to the top of the mountain.","climb→攀登")
add("close","关闭；亲近的",V,1,"high",["open","shut","near"],["cloth","cloud"],"Please close the window.","close→关闭")
add("collect","收集；聚集",V,1,"high",["gather","pick","save","collection"],["connect","correct"],"He likes collecting stamps.","col+lect(选择)→收集")
add("come","来；来到",V,1,"high",["go","arrive","return","here"],["some","become"],"Come here, please.","come→来")
add("compare","比较；对比",V,1,"high",["contrast","difference","similar"],["company","compete"],"Compare the two pictures.","com+pare(平等)→比较")
add("complete","完成；完整的",V,1,"high",["finish","end","whole","done"],["compete","company"],"I have completed my homework.","com(全部)+plete(充满)→完成")
add("continue","继续；持续",V,1,"high",["go on","keep","stop","resume"],["control","contain"],"Please continue reading.","con+tin(拿)+ue→一直拿着→继续")
add("control","控制；管理",V,1,"high",["manage","power","rule","lose"],["continue","contrast"],"You should learn to control your temper.","control→控制")
add("cook","做饭；厨师",V,1,"high",["food","kitchen","meal","recipe"],["book","look"],"My mother cooks dinner every evening.","cook→做饭")
add("copy","抄写；复制",V,1,"high",["write","paste","duplicate"],["coffee","happy"],"Please copy these words in your notebook.","copy→复制")
add("correct","纠正",V,1,"high",["right","wrong","fix","accurate"],["collect","connect"],"Your answer is correct.","cor(正确)+rect(直)→纠正")
add("cost","花费；成本",V,1,"high",["price","pay","spend","buy"],["lost","most"],"How much does this bike cost?","cost→花费")
add("count","数数；计算",V,1,"high",["number","calculate","important"],["country","couple"],"Can you count from one to ten?","count→数数")
add("cover","覆盖；盖子",V,1,"high",["hide","protect","top","uncover"],["discover","recover"],"Snow covered the ground.","cover→覆盖")
add("create","创造；创作",V,1,"high",["make","invent","produce","design"],["creature","creative"],"She created a beautiful painting.","cre(生长)+ate→创造")
add("cross","穿过；交叉",V,1,"high",["across","road","bridge","pass"],["across","crazy"],"Be careful when you cross the road.","cross→穿过")
add("cry","哭；叫喊",V,1,"high",["tears","sad","shout","laugh"],["dry","fly","try"],"The baby is crying.","cry→哭")
add("cut","切；割；剪",V,1,"high",["knife","scissors","slice"],["cat","cup"],"Please cut the cake into eight pieces.","cut→切")
add("dance","跳舞；舞蹈",V,1,"high",["music","song","party","sing"],["danger","chance"],"She loves dancing.","dance→跳舞")
add("decide","决定；下决心",V,1,"high",["determine","choice","choose","mind"],["declare","decline"],"I decided to learn a new language.","de+cide(切)→切掉其他→决定")
add("depend","依赖；取决于",V,1,"high",["rely","independent","need","trust"],["defend","depth"],"It depends on the weather.","de+pend(挂)→挂在下面→依赖")
add("describe","描述；描写",V,1,"high",["explain","tell","words","detail"],["design","despite"],"Can you describe what happened?","de+scribe(写)→描述")
add("develop","发展；开发",V,1,"high",["grow","improve","progress","build"],["depend","envelop"],"China has developed rapidly.","de+velop(包)→展开→发展")
add("die","死；死亡",V,1,"high",["dead","death","alive","live"],["diet","dirt"],"Many people die from traffic accidents.","die→死亡")
add("discuss","讨论；商议",V,1,"high",["talk","argue","conversation","agree"],["disgust","discovery"],"Lets discuss this problem together.","dis+cuss(敲)→讨论")
add("discover","发现",V,1,"high",["find","explore","uncover","invent"],["cover","recover"],"Columbus discovered America.","dis+cover(盖子)→去掉盖子→发现")
add("divide","分开；除",V,1,"medium",["separate","split","part","multiply"],["decide","provide"],"The teacher divided the class into four groups.","di+vide(分开)→分开")
add("do","做；干",V,1,"high",["make","work","action"],["did","done"],"What do you usually do on weekends?","do→做")
add("draw","画；拉",V,1,"high",["paint","picture","sketch","write"],["drawer","drawing"],"She is good at drawing animals.","draw→画")
add("dream","梦想；做梦","noun",1,"high",["hope","wish","sleep","goal"],["cream","team"],"My dream is to become a scientist.","dream→梦想")
add("drink","喝；饮料",V,1,"high",["water","juice","tea","eat"],["drunk","drive"],"Would you like something to drink?","drink→喝")
add("drive","开车；驱赶",V,1,"high",["car","road","driver","license"],["dive","dream"],"My father drives to work every day.","drive→开车")
add("drop","落下；掉落",V,1,"high",["fall","miss","rise"],["crop","drip"],"Be careful not to drop the glass.","drop→落下")
add("earn","赚；挣得",V,1,"medium",["money","work","pay","salary"],["learn","yearn"],"He earns a lot of money every month.","earn→赚")
add("eat","吃",V,1,"high",["food","drink","meal","hungry"],["east","heat"],"We usually eat lunch at school.","eat→吃")
add("encourage","鼓励；激励",V,1,"high",["support","motivate","inspire","courage"],["courage","discourage"],"My teacher always encourages me.","en+courage(勇气)→鼓励")
add("enjoy","享受；喜欢",V,1,"high",["like","love","pleasure","fun"],["enter","enemy"],"I enjoy reading books.","en+joy(高兴)→享受")
add("enter","进入",V,1,"high",["go in","exit","leave","door"],["center","inter"],"Please enter the room quietly.","enter→进入")
add("expect","期望；预料",V,1,"high",["hope","wait","anticipate","surprise"],["except","accept"],"I expect to see you at the party.","ex+pect(看)→向外看→期待")
add("explain","解释；说明",V,1,"high",["describe","tell","understand","reason"],["experience","explore"],"Can you explain this word to me?","ex+plain(平坦)→解释")
add("fail","失败；不及格",V,1,"high",["pass","succeed","lose","try"],["fall","feel","fill"],"He failed the math exam.","fail→失败")
add("fall","跌倒；秋天；下降",V,1,"high",["drop","autumn","down","rise"],["fail","fill","feel"],"Be careful not to fall down.","fall→跌倒")
add("feed","喂养；饲养",V,1,"medium",["food","eat","animal","hungry"],["feel","feet"],"She feeds her cat twice a day.","feed→喂养")
add("feel","感觉；觉得",V,1,"high",["think","sense","touch","emotion"],["fill","fell"],"I feel happy today.","feel→感觉")
add("fight","打架；战斗",V,1,"high",["battle","argue","struggle","peace"],["right","night"],"We should fight against pollution.","fight→打架")
add("fill","填满；装满",V,1,"high",["full","empty","pour"],["feel","fail"],"Please fill in the form.","fill→填满")
add("find","找到；发现",V,1,"high",["look for","discover","search","lose"],["fine","fund"],"I found my lost wallet.","find→找到")
add("finish","完成；结束",V,1,"high",["end","complete","done","start"],["fine","fire"],"I finished my homework.","finish→完成")
add("fix","修理；固定",V,1,"high",["repair","broken","solve"],["fit","six"],"Can you fix my bike?","fix→修理")
add("fly","飞；飞行",V,1,"high",["bird","air","plane","wing"],["cry","try"],"Birds can fly in the sky.","fly→飞")
add("follow","跟随；遵循",V,1,"high",["lead","after","behind","rule"],["fellow","allow"],"Please follow me.","follow→跟随")
add("forget","忘记",V,1,"high",["remember","memory","lose","mind"],["forgive","forbid"],"Dont forget to bring your homework.","for+get→不再获得→忘记")
add("forgive","原谅；宽恕",V,2,"medium",["pardon","sorry","apologize"],["forget"],"Please forgive me for being late.","for+give(给)→完全给出→原谅")
add("form","形式；表格","noun",1,"high",["shape","type","fill","table"],["from","firm"],"Please fill in this form.","form→形式")
add("found","建立；创办",V,2,"medium",["create","build","start","establish"],["find","fund"],"The school was founded in 1950.","found→建立")
add("freeze","结冰；冻结",V,2,"medium",["ice","cold","snow","melt"],["breeze","freedom"],"Water freezes at zero degrees.","freeze→结冰")
add("get","得到；变得",V,1,"high",["receive","obtain","become","take"],["got","gate"],"I got a letter from my pen pal.","get→得到")
add("give","给；给予",V,1,"high",["take","receive","offer","send"],["gift","live"],"Please give me a hand.","give→给")
add("go","去",V,1,"high",["come","leave","walk","travel"],["do","no"],"Lets go to school.","go→去")
add("grow","生长；增长",V,1,"high",["plant","increase","develop","big"],["group","grew"],"Trees grow taller every year.","grow→生长")
add("guess","猜测；猜想",V,1,"high",["think","suppose","wonder","know"],["guest","guide"],"Can you guess the answer?","guess→猜测")
add("hang","悬挂；挂起",V,2,"medium",["put up","hold","drop"],["hand","bang"],"She hung the picture on the wall.","hang→悬挂")
add("happen","发生",V,1,"high",["occur","take place","event","accident"],["happy","hard"],"What happened yesterday?","happen→发生")
add("hate","讨厌；恨",V,1,"high",["dislike","love","angry"],["gate","late"],"I hate rainy days.","hate→讨厌")
add("have","有；拥有",V,1,"high",["own","get","possess","hold"],["has","had"],"I have a beautiful bike.","have→有")
add("hear","听见",V,1,"high",["listen","sound","ear","noise"],["heart","here"],"I can hear someone singing.","hear→听见")
add("help","帮助",V,1,"high",["assist","support","aid","save"],["held","hide"],"Can you help me with this problem?","help→帮助")
add("hide","隐藏；躲藏",V,1,"medium",["seek","cover","find","show"],["help","ride"],"The cat is hiding behind the sofa.","hide→隐藏")
add("hit","打；击中",V,1,"medium",["beat","strike","hurt","miss"],["hot","hat"],"The ball hit the window.","hit→打")
add("hold","拿着；举行",V,1,"high",["keep","grasp","hand","catch"],["old","cold"],"Please hold this for me.","hold→拿着")
add("hope","希望；期望",V,1,"high",["wish","expect","dream","believe"],["home","hop"],"I hope you have a good time.","hope→希望")
add("hurry","匆忙；赶快",V,1,"medium",["rush","fast","quick","slow"],["hungry","carry"],"Hurry up, or we will be late.","hurry→匆忙")
add("hurt","伤害；疼痛",V,1,"high",["pain","harm","injure","ache"],["heart","hunt"],"My legs hurt after running.","hurt→伤害")
add("imagine","想象；设想",V,1,"high",["think","dream","picture","create"],["image","immediate"],"Can you imagine life without water?","imagine→想象")
add("improve","改善；提高",V,1,"high",["better","develop","progress","increase"],["prove","impress"],"I want to improve my English.","im+prove(证明)→提高")
add("include","包括；包含",V,1,"high",["contain","consist","exclude","have"],["increase","conclude"],"The price includes breakfast.","in+clude(关)→关在里面→包括")
add("increase","增加；增长",V,1,"high",["grow","rise","decrease","add"],["include","decrease"],"The population continues to increase.","in+crease(增长)→增加")
add("interest","使感兴趣",V,1,"high",["interesting","curious","fascinate","bore"],["interesting","interior"],"This book interests me a lot.","interest→使感兴趣")
add("introduce","介绍",V,1,"high",["present","meet","recommend","name"],["introduction","produce"],"Let me introduce myself.","intro+duce(引)→介绍")
add("invent","发明",V,1,"medium",["create","discover","design","make"],["invest","invite"],"Edison invented the light bulb.","in+vent(来)→新东西来了→发明")
add("invite","邀请",V,1,"high",["ask","welcome","invitation"],["invent","invest"],"She invited me to her birthday party.","in+vite(来)→请进来→邀请")
add("join","参加；加入",V,1,"high",["enter","participate","group","club"],["joint","joke"],"I want to join the English club.","join→加入")
add("judge","判断；审判",V,2,"medium",["decide","determine","evaluate"],["just","jug"],"Dont judge a person by appearance.","judge→判断")
add("jump","跳；跳跃",V,1,"high",["leap","hop","run","high"],["dump","pump"],"The cat jumped onto the table.","jump→跳")
add("keep","保持；保留",V,1,"high",["hold","stay","continue","save"],["key","keen"],"Keep quiet, please.","keep→保持")
add("kick","踢",V,1,"medium",["hit","foot","ball","soccer"],["pick","tick"],"He kicked the ball into the goal.","kick→踢")
add("know","知道；了解",V,1,"high",["understand","learn","find","realize"],["now","new"],"I know the answer to this question.","know→知道")
add("laugh","笑；大笑",V,1,"high",["smile","cry","funny","joke"],["cough","tough"],"They laughed at the funny joke.","laugh→笑")
add("learn","学习",V,1,"high",["study","know","teach","education"],["earn","lean"],"I learn English every day.","learn→学习")
add("leave","离开；留下",V,1,"high",["arrive","stay","go","depart"],["leaf","live"],"He left home at seven this morning.","leave→离开")
add("lend","借出",V,1,"high",["borrow","give","loan"],["send","spend"],"Can you lend me your dictionary?","lend→借出")
add("let","让；允许",V,1,"high",["allow","permit","make"],["left","set"],"Let me help you.","let→让")
add("lie","躺；撒谎",V,1,"high",["rest","truth","false","down"],["tie","die"],"Dont lie to me.","lie→撒谎")
add("lift","举起；抬起",V,2,"medium",["raise","carry","pick up"],["left","gift"],"Can you help me lift this box?","lift→举起")
add("like","喜欢",V,1,"high",["love","enjoy","dislike","hate"],["live","line"],"I like playing basketball.","like→喜欢")
add("listen","听",V,1,"high",["hear","sound","music","ear"],["lesson","letter"],"Please listen to the teacher carefully.","listen→听")
add("live","生活；居住",V,1,"high",["stay","alive","life","exist"],["leave","love","give"],"I live in Beijing.","live→居住")
add("lock","锁；锁上",V,2,"medium",["key","door","unlock","safe"],["luck","rock"],"Dont forget to lock the door.","lock→锁")
add("look","看",V,1,"high",["see","watch","find","observe"],["book","cook"],"Look at the blackboard.","look→看")
add("lose","丢失；输",V,1,"high",["find","miss","win","fail"],["loose","loss"],"I lost my keys yesterday.","lose→丢失")
add("love","爱；喜爱",V,1,"high",["like","hate","heart","care"],["live","move"],"I love my family.","love→爱")
add("make","制作；使",V,1,"high",["create","build","do","produce"],["take","lake"],"She made a cake for me.","make→制作")
add("manage","管理；设法",V,2,"medium",["control","run","organize","handle"],["manager","mange"],"She manages the company very well.","man+age→管理")
add("matter","要紧；事情","noun",1,"high",["thing","problem","important","issue"],["master","material"],"It doesnt matter.","matter→要紧")
add("mean","意思是；意味着",V,1,"high",["meaning","signify","intend","purpose"],["meat","means"],"What does this word mean?","mean→意思是")
add("meet","遇见；见面",V,1,"high",["see","greet","encounter"],["meat","mean"],"Nice to meet you.","meet→遇见")
add("mention","提到；提及",V,2,"medium",["refer","say","talk about"],["mental","mission"],"He didnt mention the plan to me.","mention→提到")
add("mind","介意；头脑",V,1,"high",["brain","care","think","object"],["find","mine"],"Do you mind if I open the window?","mind→介意")
add("miss","想念；错过",V,1,"high",["lose","hit","forget","catch"],["miss","kiss"],"I missed the bus this morning.","miss→错过")
add("mix","混合",V,2,"medium",["blend","combine","stir"],["fix","six"],"Mix the flour and water together.","mix→混合")
add("move","移动；搬家",V,1,"high",["go","change","shift","stay"],["more","moon"],"We are going to move to a new house.","move→移动")
add("need","需要",V,1,"high",["want","require","must","demand"],["knee","feed"],"I need to buy a new pen.","need→需要")
add("notice","注意；通知",V,1,"high",["observe","see","attention","note"],["notion","novice"],"I noticed a strange noise outside.","notice→注意")
add("offer","提供；提议",V,1,"high",["give","provide","suggest","accept"],["office","often"],"He offered to help me.","offer→提供")
add("open","打开；开放的",V,1,"high",["close","shut","begin"],["often","only"],"Please open the door.","open→打开")
add("order","命令；订购",V,1,"high",["command","request","buy","arrange"],["older","ordinary"],"I ordered a cup of coffee.","order→订购")
add("own","拥有；自己的",V,1,"high",["have","possess","belong","property"],["owe","own"],"I own a small bookstore.","own→拥有")
add("pack","打包",V,2,"medium",["bag","luggage","travel","unpack"],["back","pick"],"Have you packed your bags?","pack→打包")
add("pass","通过；传递",V,1,"high",["fail","give","go by","success"],["past","glass"],"Please pass me the salt.","pass→传递")
add("pay","支付",V,1,"high",["money","cost","buy","spend"],["say","lay","day"],"I paid 50 yuan for this book.","pay→支付")
add("pick","挑选；采摘",V,1,"high",["choose","select","collect"],["kick","tick"],"She picked a beautiful flower.","pick→挑选")
add("place","放置；地方",V,1,"high",["put","set","position","location"],["plan","play"],"Place the books on the shelf.","place→放置")
add("plan","计划",V,1,"high",["idea","arrange","prepare","scheme"],["plant","play"],"We are planning a trip to Shanghai.","plan→计划")
add("play","玩；播放",V,1,"high",["game","sport","fun","music"],["plan","place"],"Lets play soccer after school.","play→玩")
add("please","请；使高兴",V,1,"high",["glad","happy","satisfy"],["place","peace"],"Please sit down.","please→请")
add("point","指；指向",V,1,"high",["direct","show","finger","aim"],["print","paint"],"He pointed at the map.","point→指向")
add("pollute","污染",V,2,"medium",["dirty","contaminate","clean","environment"],["population","polite"],"Factories pollute the air and water.","pollute→污染")
add("practice","练习",V,1,"high",["exercise","train","do","repeat"],["practise","praise"],"You need to practice English every day.","practice→练习")
add("prefer","更喜欢",V,1,"high",["like better","choose","favor"],["perfect","prepare"],"I prefer tea to coffee.","pre+fer(带来)→更喜欢")
add("prepare","准备",V,1,"high",["get ready","plan","arrange","do"],["prefer","presence"],"I am preparing for the exam.","pre+pare(准备)→提前准备")
add("prevent","预防；阻止",V,1,"high",["stop","avoid","block","allow"],["present","pretend"],"We should prevent the spread of disease.","pre+vent(来)→预防")
add("print","打印；印刷",V,2,"medium",["copy","write","paper"],["point","paint"],"Please print this document.","print→打印")
add("produce","生产；制造",V,2,"medium",["make","create","manufacture","grow"],["product","program"],"This factory produces cars.","pro+duce(引导)→生产")
add("progress","进步；前进",V,1,"medium",["improve","develop","advance","grow"],["process","project"],"She is progressing in her studies.","pro+gress(走)→进步")
add("promise","承诺；保证",V,1,"high",["word","agree","swear","vow"],["price","prison"],"I promise I will come on time.","promise→承诺")
add("protect","保护",V,1,"high",["defend","guard","save","safe"],["protest","project"],"We should protect the environment.","pro+tect(覆盖)→保护")
add("provide","提供；供应",V,1,"high",["give","supply","offer","support"],["prove","produce"],"The school provides free lunch for students.","pro+vide(看)→提供")
add("pull","拉",V,1,"high",["push","drag","draw","tug"],["pool","full"],"Pull the door open.","pull→拉")
add("push","推",V,1,"high",["pull","shove","press"],["pull","put"],"Push the door, please.","push→推")
add("put","放；放置",V,1,"high",["place","set","lay"],["but","cut"],"Put your books on the desk.","put→放")
add("raise","举起；饲养；提高",V,1,"high",["lift","rise","grow","increase"],["rise","arise"],"Please raise your hand if you have a question.","raise→举起")
add("reach","到达；伸手",V,1,"high",["arrive","get to","touch","hand"],["read","react"],"We reached the hotel at noon.","reach→到达")
add("read","读；阅读",V,1,"high",["book","write","learn","study"],["red","ready"],"I read a story every night.","read→阅读")
add("realize","意识到；实现",V,1,"high",["understand","recognize","know","achieve"],["real","really"],"I realized I had left my bag at home.","real+ize→意识到")
add("receive","收到；接收",V,1,"high",["get","accept","send","give"],["believe","relieve"],"I received a letter from my friend.","re+ceive(拿)→收到")
add("refuse","拒绝",V,1,"high",["reject","decline","accept","agree"],["confuse","reuse"],"She refused to go with us.","re+fuse(倒)→拒绝")
add("regret","后悔；遗憾",V,2,"medium",["sorry","wish","remorse"],["great","greet"],"I regret not studying harder.","regret→后悔")
add("reject","拒绝；驳回",V,2,"medium",["refuse","decline","accept","approve"],["relate","relax"],"He rejected my offer.","re+ject(扔)→拒绝")
add("relax","放松",V,1,"high",["rest","calm","easy","tense"],["relate","release"],"I like to relax on weekends.","re+lax(松)→放松")
add("remain","保持；仍然是",V,2,"medium",["stay","keep","leave"],["remind","remember"],"Please remain seated.","re+main(保持)→仍然是")
add("remember","记住",V,1,"high",["forget","recall","memory","mind"],["remind","member"],"Please remember to bring your homework.","re+member(成员)→记住")
add("remove","移除；去掉",V,2,"medium",["take away","delete","move","add"],["remain","remind"],"Please remove your shoes before entering.","re+move(动)→移除")
add("repair","修理",V,1,"high",["fix","mend","broken","damage"],["repeat","repay"],"Can you repair my bike?","re+pair(配对)→修理")
add("repeat","重复",V,1,"high",["say again","do again","copy"],["repair","replace"],"Can you repeat that, please?","re+peat(说)→重复")
add("replace","替代；替换",V,2,"medium",["change","substitute","instead"],["repeat","repair"],"Nothing can replace a mothers love.","re+place(放)→替换")
add("reply","回复",V,1,"high",["answer","respond","write back"],["rely","report"],"Please reply to my email soon.","re+ply(折)→回复")
add("report","报告；报道",V,1,"high",["tell","announce","news"],["replay","repeat"],"She reported the accident to the police.","re+port(带)→报告")
add("require","需要；要求",V,1,"high",["need","demand","must","ask"],["request","acquire"],"This job requires patience.","re+quire(寻求)→要求")
add("respect","尊重",V,1,"high",["honor","admire","polite"],["expect","inspect"],"We should respect our teachers.","re+spect(看)→尊重")
add("rest","休息",V,1,"high",["relax","sleep","break","work"],["best","test"],"You should take a good rest.","rest→休息")
add("result","结果","noun",1,"high",["outcome","effect","cause","consequence"],["insult","consult"],"The result of the exam will come out tomorrow.","re+sult(跳)→结果")
add("return","归还；返回",V,1,"high",["come back","give back","leave"],["retain","reveal"],"I will return the book next week.","re+turn(转)→返回")
add("review","复习；回顾",V,1,"high",["study again","go over","check"],["revive","reveal"],"I need to review my lessons before the exam.","re+view(看)→复习")
add("ride","骑；乘坐",V,1,"high",["bike","horse","car","drive"],["rise","road"],"She rides her bike to school every day.","ride→骑")
add("rise","上升；升起",V,1,"high",["increase","go up","fall","sun"],["raise","arise"],"The sun rises in the east.","rise→上升")
add("risk","冒险；风险",V,1,"medium",["danger","chance","safe","brave"],["rise","disk"],"We should not risk our lives.","risk→冒险")
add("roll","滚动；卷",V,2,"medium",["turn","round","rotate"],["rock","role"],"The ball rolled down the hill.","roll→滚动")
add("ruin","毁坏",V,2,"medium",["destroy","damage","spoil"],["rain","run"],"The heavy rain ruined our picnic.","ruin→毁坏")
add("rule","统治；规则",V,1,"high",["govern","law","control","king"],["ruler","rude"],"The king ruled the country for 50 years.","rule→统治")
add("run","跑",V,1,"high",["walk","sprint","fast","race"],["ran","ruler"],"He runs very fast.","run→跑")
add("rush","冲；匆忙",V,2,"medium",["hurry","quick","dash","slow"],["run","brush"],"Dont rush. Take your time.","rush→冲")
add("save","节省；救；保存",V,1,"high",["money","rescue","keep","waste"],["safe","same"],"We should save water.","save→节省")
add("say","说",V,1,"high",["tell","speak","talk"],["day","way"],"What did you say?","say→说")
add("score","得分；比分","noun",1,"high",["point","goal","mark","test"],["store","storm"],"What was the final score?","score→得分")
add("search","搜索；搜寻",V,1,"high",["look for","find","seek","explore"],["research","reach"],"I searched everywhere for my keys.","search→搜索")
add("see","看见",V,1,"high",["look","watch","observe","notice"],["sea","she"],"I saw a beautiful bird in the garden.","see→看见")
add("seem","似乎；好像",V,1,"high",["appear","look like","feel"],["seen","seed"],"She seems happy today.","seem→似乎")
add("sell","卖",V,1,"high",["buy","shop","price","market"],["tell","well"],"They sell fresh fruit here.","sell→卖")
add("send","发送；寄",V,1,"high",["receive","post","mail","deliver"],["spend","sand"],"I sent an email to my friend.","send→发送")
add("serve","服务；端上",V,1,"high",["help","provide","service","food"],["serious","several"],"She served us a delicious dinner.","serve→服务")
add("set","设置；放",V,1,"high",["put","place","lay"],["sit","sat"],"She set the table for dinner.","set→设置")
add("shake","摇动",V,1,"medium",["move","tremble","hand"],["shape","share"],"Shake the bottle before opening.","shake→摇动")
add("share","分享",V,1,"high",["divide","give","part","together"],["shake","shame"],"We should share our food with others.","share→分享")
add("shout","喊叫",V,1,"high",["cry","call","yell","quiet"],["shoot","shut"],"Dont shout at me!","shout→喊叫")
add("show","展示；给……看",V,1,"high",["display","reveal","see","tell"],["shoe","shut"],"Can you show me the way to the station?","show→展示")
add("shut","关闭",V,1,"high",["close","open","door"],["shout","shoot"],"Shut the door, please.","shut→关闭")
add("sign","签名；标志",V,1,"high",["write","name","mark","signal"],["sing","sigh"],"Please sign your name here.","sign→签名")
add("sing","唱歌",V,1,"high",["song","music","voice","dance"],["sign","sang"],"She sings beautifully.","sing→唱歌")
add("sit","坐",V,1,"high",["seat","stand","chair"],["set","six"],"Please sit down.","sit→坐")
add("sleep","睡觉",V,1,"high",["rest","bed","dream","wake"],["sheep","slip"],"I usually sleep at ten oclock.","sleep→睡觉")
add("smell","闻；气味",V,1,"high",["nose","scent","fragrant"],["small","smile"],"The flowers smell wonderful.","smell→闻")
add("smile","微笑",V,1,"high",["laugh","happy","grin"],["small","smell"],"She gave me a warm smile.","smile→微笑")
add("solve","解决",V,1,"high",["answer","figure out","problem","resolve"],["love","show"],"Can you solve this math problem?","solve→解决")
add("sound","听起来；声音",V,1,"high",["noise","hear","voice","listen"],["south","found"],"That sounds like a great idea!","sound→听起来")
add("speak","说（语言）",V,1,"high",["talk","say","tell","language"],["break","steak"],"Can you speak English?","speak→说")
add("spend","花费；度过",V,1,"high",["money","time","cost","pay"],["send","stand"],"I spent 100 yuan on this book.","spend→花费")
add("spread","传播；展开",V,2,"medium",["extend","expand","share","news"],["spring","speak"],"The news spread quickly.","spread→传播")
add("stand","站；忍受",V,1,"high",["sit","rise","stay","bear"],["start","state"],"Please stand up when the teacher comes in.","stand→站")
add("start","开始",V,1,"high",["begin","commence","end","stop"],["star","state"],"School starts at eight oclock.","start→开始")
add("stay","停留；保持",V,1,"high",["remain","keep","live","leave"],["say","study"],"I stayed at home all day.","stay→停留")
add("steal","偷",V,2,"medium",["rob","thief","take","crime"],["steel","steam"],"Someone stole my wallet.","steal→偷")
add("step","步骤；脚步","noun",1,"high",["walk","foot","stage","process"],["stop","steep"],"Follow these steps to complete the task.","step→步骤")
add("stick","粘贴；棍子",V,2,"medium",["attach","glue","paste","wood"],["still","stock"],"Stick the stamp on the envelope.","stick→粘贴")
add("stop","停止",V,1,"high",["start","end","cease","begin"],["step","store"],"The bus stopped in front of the school.","stop→停止")
add("store","商店；储存","noun",1,"high",["shop","keep","save","supermarket"],["storm","story"],"I bought this in a store near my home.","store→商店")
add("study","学习",V,1,"high",["learn","read","review","homework"],["student","studio"],"I study English every day.","study→学习")
add("succeed","成功",V,1,"high",["fail","achieve","success","win"],["success","suggest"],"If you work hard, you will succeed.","suc+ceed(走)→走过去→成功")
add("suggest","建议；暗示",V,1,"high",["advise","propose","recommend","idea"],["succeed","support"],"I suggest we go by bus.","sug+gest(带)→建议")
add("support","支持",V,1,"high",["help","back","agree","encourage"],["supply","suppose"],"My family supports my decision.","sup+port(带)→从下面托着→支持")
add("suppose","假设；认为",V,1,"high",["think","guess","believe","imagine"],["support","supply"],"I suppose you are right.","sup+pose(放)→假设")
add("surprise","使惊奇",V,1,"high",["shock","amaze","unexpected"],["surprising","surprised"],"The news surprised everyone.","sur+prise(抓)→超出预期→惊奇")
add("survive","幸存；存活",V,2,"medium",["live","alive","death","exist"],["surprise","serve"],"Only a few people survived the earthquake.","sur+vive(活)→幸存")
add("sweep","打扫",V,2,"medium",["clean","brush","floor"],["sweet","swim"],"She sweeps the floor every day.","sweep→打扫")
add("swim","游泳",V,1,"high",["water","pool","sea","sport"],["sweet","swing"],"I like swimming in summer.","swim→游泳")
add("take","拿；带",V,1,"high",["bring","carry","get","give"],["make","lake"],"Take your umbrella with you.","take→拿")
add("talk","谈话",V,1,"high",["speak","say","tell","chat"],["walk","take"],"Lets talk about the plan.","talk→谈话")
add("teach","教",V,1,"high",["learn","study","student","class"],["reach","team"],"She teaches English at our school.","teach→教")
add("tear","撕；眼泪",V,2,"medium",["rip","break","cry"],["bear","wear"],"Dont tear the paper.","tear→撕")
add("tell","告诉",V,1,"high",["say","speak","talk","inform"],["tall","bell"],"Tell me the truth.","tell→告诉")
add("test","测试；考试",V,1,"high",["exam","check","quiz"],["text","tent"],"We will have a math test tomorrow.","test→测试")
add("thank","感谢",V,1,"high",["grateful","appreciate","you"],["that","think"],"Thank you for your help.","thank→感谢")
add("think","想；认为",V,1,"high",["believe","consider","opinion","mind"],["thick","thing"],"I think you are right.","think→想")
add("throw","扔；投",V,1,"high",["catch","hit","toss","ball"],["through","though"],"Dont throw rubbish on the ground.","throw→扔")
add("tidy","整理；整洁的",V,2,"medium",["clean","neat","organize","messy"],["tiny","tide"],"Please tidy your room.","tidy→整理")
add("tie","系；绑",V,2,"medium",["knot","bind","rope"],["die","lie"],"Tie your shoelaces, please.","tie→系")
add("touch","触摸",V,1,"high",["feel","hand","contact","reach"],["tough","much"],"Please dont touch the painting.","touch→触摸")
add("trade","贸易；交易",V,2,"medium",["business","buy","sell","exchange"],["tradition","train"],"China trades with many countries.","trade→贸易")
add("train","训练；火车",V,1,"high",["practice","exercise","coach"],["rain","trail"],"He trains hard every day.","train→训练")
add("travel","旅行",V,1,"high",["trip","journey","tour","visit"],["trail","trouble"],"I love traveling around the world.","travel→旅行")
add("try","尝试；努力",V,1,"high",["attempt","effort","test"],["cry","fly","dry"],"I will try my best.","try→尝试")
add("turn","转；翻转",V,1,"high",["rotate","spin","change","round"],["burn","return"],"Turn left at the corner.","turn→转")
add("understand","理解",V,1,"high",["know","comprehend","realize","learn"],["understand","undertake"],"I understand what you mean.","under+stand→站在下面→理解")
add("unite","联合；团结",V,2,"medium",["join","together","united","divide"],["unit","universe"],"We should unite to fight pollution.","unite→联合")
add("use","使用",V,1,"high",["utilize","apply","employ"],["useful","usual"],"Can I use your pen?","use→使用")
add("visit","参观；拜访",V,1,"high",["tour","see","travel","call"],["vista","vital"],"We visited the museum last week.","visit→参观")
add("wait","等待",V,1,"high",["stay","expect","patient"],["wake","want"],"Wait for me at the school gate.","wait→等待")
add("wake","醒来",V,1,"high",["sleep","awake","alarm"],["walk","wait"],"I woke up at six this morning.","wake→醒来")
add("walk","步行",V,1,"high",["run","step","go","stroll"],["talk","wake"],"I walk to school every day.","walk→步行")
add("want","想要",V,1,"high",["need","wish","desire","like"],["went","what"],"I want a cup of tea.","want→想要")
add("warn","警告",V,2,"medium",["caution","danger","alert"],["warm","worm"],"The teacher warned us not to be late.","warn→警告")
add("wash","洗",V,1,"high",["clean","water","soap"],["wish","watch"],"Please wash your hands before eating.","wash→洗")
add("waste","浪费",V,1,"high",["save","spend","rubbish"],["taste","paste"],"Dont waste food.","waste→浪费")
add("watch","观看；手表",V,1,"high",["see","look","observe","time"],["wash","water"],"I watched a movie last night.","watch→观看")
add("wear","穿；戴",V,1,"high",["put on","clothes","dress","hat"],["bear","war"],"She is wearing a red dress.","wear→穿")
add("welcome","欢迎",V,1,"high",["greet","invite","hello"],["well","welfare"],"Welcome to our school!","welcome→欢迎")
add("win","赢；获胜",V,1,"high",["lose","beat","victory","success"],["won","wind"],"Our team won the game.","win→赢")
add("wish","祝愿；希望",V,1,"high",["hope","want","dream","desire"],["wash","which"],"I wish you a happy birthday.","wish→希望")
add("wonder","想知道；惊奇",V,1,"high",["think","curious","amaze"],["wander","wonderful"],"I wonder what will happen next.","wonder→想知道")
add("work","工作",V,1,"high",["job","labor","study","do"],["word","world"],"He works in a hospital.","work→工作")
add("worry","担心",V,1,"high",["anxious","worry","concern"],["sorry","angry"],"Dont worry about it.","worry→担心")
add("write","写",V,1,"high",["read","pen","paper","book"],["right","white"],"I write in my diary every day.","write→写")
add("wrong","错误的",V,1,"high",["right","correct","mistake","error"],["write","long"],"What is wrong with you?","wrong→错误的")

# ===== TIER 1 ADJECTIVES (80) =====
A = "adjective"
add("afraid","害怕的；担心的",A,1,"high",["fear","scared","nervous","brave"],["affect","offer"],"She is afraid of the dark.","a+fr(怕)+aid→害怕")
add("alive","活着的",A,1,"high",["live","dead","life","survive"],["living","life","lively"],"The old man is still alive and well.","a+live→活着的")
add("alone","独自的；单独的",A,1,"high",["lonely","single","independent"],["along","allow","alive"],"She lives alone but she doesnt feel lonely.","a+one(一个)→独自的")
add("amazing","令人惊奇的",A,1,"high",["wonderful","surprising","incredible","boring"],["amuse","amount"],"The view from the mountain is amazing.","amaze+ing→令人惊奇的")
add("angry","生气的；愤怒的",A,1,"high",["mad","upset","furious","calm"],["anger","hungry"],"Dont be angry with me.","an+gry→生气得干瞪眼")
add("another","另一个；又一个","pronoun",1,"high",["other","one more","next"],["brother","mother"],"Would you like another cup of tea?","an+other→又一个")
add("anxious","焦虑的；担忧的",A,2,"medium",["worried","nervous","eager","calm"],["ancient","anger"],"She felt anxious about the exam results.","anx+ious→焦虑的")
add("available","可用的；有空的",A,2,"medium",["free","usable","ready","busy"],["acceptable","valuable"],"Are you available this weekend?","avail+able→可用的")
add("awake","醒着的",A,1,"high",["asleep","wake","sleep","conscious"],["aware","away"],"I was still awake at midnight.","a+wake→醒着的")
add("aware","意识到的；知道的",A,2,"medium",["realize","know","notice","conscious"],["awake","away"],"I was not aware of the danger.","a+ware(注意)→意识到的")
add("bad","坏的；差的",A,1,"high",["good","terrible","poor","wrong"],["bed","bag"],"Too much junk food is bad for your health.","bad→坏的")
add("basic","基本的；基础的",A,1,"high",["simple","elementary","base","fundamental"],["basin","basket"],"These are the basic rules of the game.","base+ic→基本的")
add("beautiful","美丽的；漂亮的",A,1,"high",["pretty","lovely","ugly","nice"],["beauty","beach"],"What a beautiful sunset!","beauty+ful→美丽的")
add("big","大的",A,1,"high",["large","huge","small","great"],["bag","dig"],"There is a big tree in front of our school.","big→大的")
add("bitter","苦的；痛苦的",A,2,"medium",["sweet","sour","sad","painful"],["better","butter"],"The medicine tastes bitter.","bitter→苦的")
add("bored","无聊的",A,1,"high",["boring","tired","uninterested","excited"],["boring","board"],"I felt bored during the long meeting.","bored→感到无聊的（修饰人）")
add("boring","无聊的；乏味的",A,1,"high",["bored","dull","interesting","exciting"],["bored","bearing"],"The movie was so boring that I fell asleep.","boring→令人无聊的（修饰物）")
add("born","出生的；天生的",A,1,"high",["birth","baby","bear"],["bore","burn"],"She was born in 2008.","born→出生")
add("brave","勇敢的",A,1,"high",["courage","bold","fearless","afraid"],["bread","break"],"The brave soldier saved many lives.","brave→勇敢的")
add("bright","明亮的；聪明的",A,1,"high",["light","smart","clever","dark"],["right","bring"],"The sun is very bright today.","bright→明亮的")
add("busy","忙的；繁忙的",A,1,"high",["free","occupied","work"],["bus","easy"],"I am busy preparing for the exam.","bus+y→忙的")
add("calm","平静的",A,1,"medium",["peaceful","quiet","nervous","angry"],["call","come"],"Please keep calm when there is a fire.","calm→平静的")
add("careful","小心的；仔细的",A,1,"high",["careless","attention","safe"],["careless","carefree"],"Be careful when you cross the road.","care+ful→小心的")
add("cheap","便宜的",A,1,"high",["expensive","low price","save"],["chip","cheat"],"This shirt is very cheap.","cheap→便宜的")
add("clean","干净的",A,1,"high",["dirty","wash","tidy","clear"],["clear","clever"],"Please keep your room clean.","clean→干净的")
add("clear","清楚的",A,1,"high",["clean","understand","obvious"],["clean","clever","close"],"The water in the river is very clear.","clear→清楚的")
add("clever","聪明的",A,1,"high",["smart","bright","intelligent","stupid"],["clean","clear","climb"],"She is a clever girl.","clever→聪明的")
add("cold","冷的；感冒",A,1,"high",["hot","cool","warm","freezing"],["old","could","hold"],"It is very cold outside today.","cold→冷的")
add("comfortable","舒适的",A,1,"medium",["comfort","easy","cozy","uncomfortable"],["compare"],"This sofa is very comfortable.","comfort+able→舒适的")
add("confident","自信的",A,2,"medium",["sure","certain","nervous","shy"],["confidence","confuse"],"She is very confident about the exam.","confide+nt→自信的")
add("correct","正确的",A,1,"high",["right","wrong","fix","accurate"],["collect","connect"],"Your answer is correct.","cor+rect→正确的")
add("crazy","疯狂的",A,2,"medium",["mad","wild","insane","sane"],["cross","lazy"],"Are you crazy? That is too dangerous.","crazy→疯狂的")
add("dangerous","危险的",A,1,"high",["safe","risk","harm","danger"],["danger","delicious"],"It is dangerous to swim in the river alone.","danger+ous→危险的")
add("dark","黑暗的；深色的",A,1,"high",["light","night","black","bright"],["park","mark"],"The room is too dark.","dark→黑暗的")
add("dead","死的；无生命的",A,1,"high",["alive","die","death","living"],["dear","deal"],"The plant is dead.","dead→死的")
add("deaf","聋的",A,2,"medium",["blind","hear","disabled"],["death","deal"],"The old man is deaf.","deaf→聋的")
add("dear","亲爱的；贵的",A,1,"medium",["love","expensive","sweet"],["dear","dead","near"],"Dear Mom, I miss you very much.","dear→亲爱的")
add("deep","深的",A,1,"high",["shallow","bottom","deeply"],["deer","keep","sleep"],"The river is very deep here.","deep→深的")
add("delicious","美味的",A,1,"high",["tasty","yummy","sweet","food"],["delicious","dangerous"],"The food in this restaurant is delicious.","de+lici+ous→美味的")
add("different","不同的",A,1,"high",["same","various","similar","change"],["different","difficult"],"We have different opinions on this matter.","dif+fer+ent→不同的")
add("difficult","困难的",A,1,"high",["hard","easy","tough","simple"],["different","difference"],"This math problem is very difficult.","difficult→困难的")
add("dirty","脏的",A,1,"high",["clean","wash","dust","mud"],["direct","dinner"],"Your hands are dirty.","dirty→脏的")
add("dry","干的；干燥的",A,1,"medium",["wet","rain","desert"],["cry","try","fly"],"The weather is very dry in winter.","dry→干的")
add("early","早的；提前",A,1,"high",["late","morning","first","before"],["ear","earth","earn"],"Please come to school early tomorrow.","early→早的")
add("easy","容易的",A,1,"high",["simple","difficult","hard"],["east","busy"],"This question is easy.","easy→容易的")
add("empty","空的",A,1,"high",["full","blank","nothing"],["enemy","enough"],"The box is empty.","empty→空的")
add("enough","足够的",A,1,"high",["sufficient","plenty","lack"],["though","tough","through"],"I have enough money to buy this book.","enough→足够的")
add("excellent","优秀的",A,1,"high",["great","wonderful","outstanding","perfect"],["except","excite"],"She did an excellent job.","ex+cell+ent→优秀的")
add("excited","兴奋的；激动的",A,1,"high",["exciting","happy","thrilled","nervous"],["exciting","excite"],"I am so excited about the trip.","excited→感到兴奋的（修饰人）")
add("exciting","令人兴奋的",A,1,"high",["excited","interesting","boring","amazing"],["excited","excite"],"The basketball game was very exciting.","exciting→令人兴奋的（修饰物）")
add("expensive","昂贵的",A,1,"high",["cheap","costly","price","valuable"],["experience","express"],"This dress is too expensive.","expensive→昂贵的")
add("famous","著名的",A,1,"high",["well-known","popular","star","celebrity"],["family","frame"],"Lu Xun is a famous Chinese writer.","fam+ous→著名的")
add("far","远的",A,1,"high",["near","close","distance","away"],["for","farm"],"The school is not far from my home.","far→远的")
add("fast","快的",A,1,"high",["quick","rapid","slow","speed"],["first","last"],"He runs very fast.","fast→快的")
add("fat","胖的",A,1,"medium",["thin","heavy","weight","overweight"],["cat","hat","flat"],"You should eat less junk food to avoid getting fat.","fat→胖的")
add("favorite","最喜欢的",A,1,"high",["like","love","best","prefer"],["favor","flavor"],"My favorite subject is English.","favor+ite→最喜欢的")
add("final","最终的；决赛的",A,1,"high",["last","end","first","result"],["find","fine"],"What is your final decision?","final→最终的")
add("fit","健康的；适合的",A,1,"high",["healthy","suitable","exercise","size"],["fix","bit"],"She keeps fit by running every day.","fit→健康的")
add("flat","平坦的；公寓",A,1,"medium",["apartment","smooth","even","round"],["fat","flag","flash"],"They live in a flat near the park.","flat→平坦的")
add("foreign","外国的",A,1,"high",["abroad","international","country","language"],["forest","forget"],"She can speak three foreign languages.","for+eign→外国的")
add("free","自由的；免费的",A,1,"high",["freedom","busy","no cost","liberty"],["tree","three","fee"],"The ticket is free for children.","free→自由的")
add("fresh","新鲜的",A,1,"medium",["new","clean","food","air"],["flash","flesh"],"The vegetables in this market are very fresh.","fresh→新鲜的")
add("friendly","友好的",A,1,"high",["kind","nice","warm","unfriendly"],["friend","friendship"],"The people here are very friendly.","friend+ly→友好的")
add("full","满的；完整的",A,1,"high",["empty","complete","fill"],["fall","fill"],"The cup is full of water.","full→满的")
add("funny","有趣的；好笑的",A,1,"high",["fun","humorous","laugh","boring"],["fun","sunny","money"],"The story is very funny.","funny→好笑的")
add("gentle","温柔的",A,2,"medium",["kind","soft","mild","rough"],["gently","genius"],"She has a gentle voice.","gentle→温柔的")
add("glad","高兴的",A,1,"high",["happy","pleased","joyful","sad"],["glass","glob"],"I am glad to see you.","glad→高兴的")
add("good","好的",A,1,"high",["great","nice","well","bad"],["wood","food","foot"],"She is a good student.","good→好的")
add("great","伟大的；极好的",A,1,"high",["wonderful","big","excellent","good"],["green","greet"],"That is a great idea!","great→伟大的")
add("green","绿色的",A,1,"high",["color","grass","tree","environment"],["great","grey"],"The hills are green in spring.","green→绿色的")
add("happy","快乐的；高兴的",A,1,"high",["glad","joyful","sad","pleased"],["happen","heavy"],"Happy New Year!","happy→快乐的")
add("hard","困难的；努力地",A,1,"high",["difficult","tough","easy","soft"],["card","hardly"],"This math problem is too hard for me.","hard→困难的")
add("healthy","健康的",A,1,"high",["health","fit","well","sick"],["health","wealthy"],"Eating vegetables keeps you healthy.","health+y→健康的")
add("heavy","重的",A,1,"high",["light","weight","fat","thin"],["head","hear"],"This box is too heavy for me to carry.","heavy→重的")
add("high","高的",A,1,"high",["tall","low","top","sky"],["height","night"],"The mountain is very high.","high→高的")
add("honest","诚实的",A,1,"medium",["truthful","lie","trust","dishonest"],["honor","hour"],"He is an honest person.","honest→诚实的")
add("horrible","可怕的",A,2,"medium",["terrible","awful","scary","bad"],"The weather was horrible yesterday.","horror+ible→可怕的")
add("hot","热的",A,1,"high",["warm","cold","cool","heat"],["hit","hat"],"It is very hot in summer.","hot→热的")
add("huge","巨大的",A,1,"medium",["big","large","enormous","small"],["hug","age"],"The elephant is a huge animal.","huge→巨大的")
add("hungry","饥饿的",A,1,"high",["eat","food","starve","thirsty"],["hundred","anger"],"I am very hungry.","hungry→饥饿的")
add("important","重要的",A,1,"high",["significant","key","unimportant","vital"],["import","impossible"],"English is an important subject.","import+ant→重要的")
add("impossible","不可能的",A,1,"medium",["possible","cannot","unlikely"],["possible","importance"],"Nothing is impossible.","im+possible→不可能的")
add("interesting","有趣的",A,1,"high",["boring","fun","exciting","dull"],["interest","internet"],"This book is very interesting.","interest+ing→有趣的")
add("kind","善良的；种类",A,1,"high",["nice","friendly","cruel","kindness"],["king","mind"],"She is a very kind person.","kind→善良的")
add("large","大的",A,1,"high",["big","huge","small","great"],["larg