#!/usr/bin/env python3
"""Generate words_network_j2.json - Part 3: Nouns, Adverbs, Prepositions, Expressions + Tier 2/3 (304 words)"""
import json

with open('/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/_part2_cache.json','r') as f:
    words = json.load(f)

def add(w, m, cat, tier, freq, assoc, conf, ex, tip):
    words[w] = {
        'word': w, 'meaning': m, 'category': cat,
        'tier': tier, 'frequency': freq,
        'associations': assoc, 'confusables': conf,
        'example': ex, 'memory_tip': tip
    }

A='adjective'; N='noun'; Adv='adverb'; Prep='preposition'
Conj='conjunction'; Pron='pronoun'; V='verb'

# === NOUNS TIER 1 (120) ===
entries = [
("ability","能力",N,1,"high",["skill","power","able","talent"],["able","ability"],"She has the ability to sing well.","ability→能力"),
("accident","事故；意外",N,1,"high",["crash","injury","danger","safe"],["accident","accidental"],"He had a car accident.","accident→事故"),
("action","行动；行为",N,1,"high",["act","do","movement","activity"],["action","active"],"Actions speak louder than words.","action→行动"),
("adventure","冒险；奇遇",N,1,"high",["brave","danger","exciting","journey"],["advance","advantage"],"They had an exciting adventure.","ad(去)+venture(冒险)→冒险"),
("advice","建议；忠告",N,1,"high",["suggest","opinion","recommend","idea"],["advise","advantage"],"Can you give me some advice?","advise动词→advice名词"),
("age","年龄；时代",N,1,"high",["old","young","year","period"],["age","ago"],"What is your age?","age→年龄"),
("air","空气",N,1,"high",["sky","breathe","wind","fresh"],["air","area"],"The air is fresh in the morning.","air→空气"),
("animal","动物",N,1,"high",["pet","dog","cat","zoo"],["animal","answer"],"I love animals.","animal→动物"),
("answer","回答；答案",N,1,"high",["question","reply","respond"],["anger","another"],"Do you know the answer?","answer→回答"),
("area","地区；区域",N,1,"high",["region","place","zone","district"],["area","air"],"This area is very quiet.","area→地区"),
("arm","手臂",N,1,"high",["hand","leg","body","shoulder"],["arm","art"],"He broke his arm.","arm→手臂"),
("attention","注意力",N,1,"high",["focus","notice","care","concentrate"],["attention","attract"],"Please pay attention.","attention→注意力"),
("aunt","阿姨；姑姑",N,1,"medium",["uncle","cousin","family","relative"],["aunt","autumn"],"My aunt lives in Shanghai.","aunt→阿姨"),
("back","背部；后面",N,1,"high",["front","behind","return","spine"],["back","bag"],"He hurt his back.","back→背部"),
("bag","包；袋子",N,1,"high",["pack","bag","carry","luggage"],["bag","bad"],"Put your books in the bag.","bag→包"),
("ball","球",N,1,"high",["play","round","throw","catch"],["ball","call"],"Let's play with the ball.","ball→球"),
("bank","银行；河岸",N,1,"high",["money","river","save","loan"],["bank","bath"],"I went to the bank.","bank→银行"),
("bath","洗澡",N,2,"medium",["shower","wash","clean","water"],["bath","both"],"She takes a bath every evening.","bath→洗澡"),
("beach","海滩",N,1,"high",["sea","sand","shore","ocean"],["beach","bear"],"We played on the beach.","beach→海滩"),
("bed","床",N,1,"high",["sleep","room","rest","wake"],["bed","bad"],"Go to bed early.","bed→床"),
("belly","肚子",N,3,"low",["stomach","food","eat","hungry"],["belly","below"],"My belly is full.","belly→肚子"),
("bird","鸟",N,1,"high",["fly","sky","sing","feather"],["bird","birth"],"The bird is singing.","bird→鸟"),
("birth","出生",N,2,"medium",["born","baby","birthday","life"],["birth","bird"],"What is your date of birth?","birth→出生"),
("blood","血",N,2,"medium",["body","heart","red","health"],["blood","blow"],"He gave blood at the hospital.","blood→血"),
("body","身体",N,1,"high",["health","head","arm","leg"],["body","boy"],"Exercise is good for your body.","body→身体"),
("bone","骨头",N,3,"low",["body","skeleton","dog","hard"],["bone","bone"],"The dog buried a bone.","bone→骨头"),
("book","书；预订",N,1,"high",["read","write","story","library"],["book","boot"],"I am reading a book.","book→书"),
("bottle","瓶子",N,1,"medium",["water","drink","glass","cup"],["bottle","bottom"],"Give me a bottle of water.","bottle→瓶子"),
("bottom","底部",N,2,"medium",["top","base","low","under"],["bottle","bottom"],"The answer is at the bottom.","bottom→底部"),
("box","盒子",N,1,"high",["container","pack","open","close"],["box","boy"],"Put it in the box.","box→盒子"),
("brain","大脑",N,1,"high",["mind","think","head","smart"],["brain","rain"],"The human brain is amazing.","brain→大脑"),
("bread","面包",N,1,"high",["food","eat","bake","wheat"],["bread","break"],"I had bread for breakfast.","bread→面包"),
("breakfast","早餐",N,1,"high",["meal","morning","eat","food"],["break","fast"],"What did you have for breakfast?","break+fast→早餐"),
("breath","呼吸",N,2,"medium",["breathe","air","lung","deep"],["bread","break"],"Take a deep breath.","breath→呼吸"),
("bridge","桥",N,1,"high",["river","cross","road","connect"],["bridge","bright"],"We walked across the bridge.","bridge→桥"),
("brother","兄弟",N,1,"high",["sister","family","son","parent"],["brother","both"],"I have an older brother.","brother→兄弟"),
("building","建筑物",N,1,"high",["house","school","office","tall"],["build","building"],"That is a tall building.","building→建筑物"),
("bus","公共汽车",N,1,"high",["car","train","transport","ride"],["bus","busy"],"I take the bus to school.","bus→公共汽车"),
("business","生意；商业",N,1,"high",["company","trade","work","money"],["business","busy"],"He runs his own business.","business→生意"),
("cage","笼子",N,3,"low",["bird","animal","trap","lock"],["cage","cake"],"The bird is in a cage.","cage→笼子"),
("cake","蛋糕",N,1,"high",["birthday","food","sweet","eat"],["cake","cage"],"She made a chocolate cake.","cake→蛋糕"),
("camp","营地；露营",N,2,"medium",["tent","outdoor","fire","sleep"],["camp","cap"],"We set up camp by the river.","camp→营地"),
("cap","帽子",N,2,"medium",["hat","wear","head"],["cap","cap"],"He is wearing a cap.","cap→帽子"),
("capital","首都；资本",N,2,"medium",["city","money","important","country"],["capital","captain"],"Beijing is the capital of China.","capital→首都"),
("car","汽车",N,1,"high",["drive","road","bus","vehicle"],["car","cat"],"My father has a car.","car→汽车"),
("card","卡片",N,1,"high",["paper","credit","game","send"],["car","care"],"Send me a birthday card.","card→卡片"),
("care","关心；照顾",N,1,"high",["careful","worry","health","love"],["care","car"],"She takes good care of her grandma.","care→关心"),
("castle","城堡",N,3,"low",["palace","king","old","tower"],["castle","cattle"],"The old castle is on the hill.","castle→城堡"),
("cat","猫",N,1,"high",["pet","dog","animal","mouse"],["cat","car"],"I have a cute cat.","cat→猫"),
("cattle","牛",N,3,"low",["cow","farm","animal","milk"],["cattle","castle"],"There are many cattle on the farm.","cattle→牛"),
("cause","原因",N,1,"high",["reason","result","because","effect"],["cause","course"],"What was the cause of the fire?","cause→原因"),
("celebration","庆祝",N,2,"medium",["party","festival","happy","ceremony"],["celebrate","center"],"We had a big celebration.","celebration→庆祝"),
("center","中心",N,1,"high",["middle","central","around","core"],["center","century"],"The library is in the city center.","center→中心"),
("century","世纪",N,2,"medium",["hundred","year","time","period"],["center","certain"],"We live in the 21st century.","century→世纪"),
("chair","椅子",N,1,"high",["sit","table","furniture","seat"],["chair","chain"],"Please take a chair.","chair→椅子"),
("chance","机会",N,1,"high",["opportunity","luck","risk","possibility"],["change","channel"],"Don't miss this chance.","chance→机会"),
("change","零钱；变化",N,1,"high",["money","difference","coin","alter"],["chance","charge"],"Keep the change.","change→零钱"),
("channel","频道；渠道",N,2,"medium",["TV","program","watch","media"],["channel","chapter"],"Which channel is the news on?","channel→频道"),
("chapter","章节",N,2,"medium",["book","part","section","read"],["chapter","channel"],"Read chapter three for homework.","chapter→章节"),
("charity","慈善",N,3,"low",["donate","help","poor","kind"],["charity","chapter"],"She donated money to charity.","charity→慈善"),
("chess","象棋",N,2,"medium",["game","play","board","strategy"],["chess","chest"],"Do you know how to play chess?","chess→象棋"),
("chest","胸部；箱子",N,3,"low",["body","box","breath","heart"],["chest","chess"],"He has a pain in his chest.","chest→胸部"),
("child","孩子",N,1,"high",["children","kid","baby","young"],["child","chill"],"Every child needs education.","child→孩子"),
("chocolate","巧克力",N,1,"high",["candy","sweet","food","brown"],["chocolate","choice"],"I love chocolate.","chocolate→巧克力"),
("church","教堂",N,2,"medium",["religion","pray","God","building"],["church","choose"],"They go to church every Sunday.","church→教堂"),
("circle","圆；圈子",N,2,"medium",["round","shape","group","ring"],["circle","certain"],"Stand in a circle.","circle→圆"),
("citizen","公民",N,2,"medium",["country","people","city","right"],["city","citizen"],"Every citizen should obey the law.","citizen→公民"),
("city","城市",N,1,"high",["town","urban","capital","village"],["city","citizen"],"Beijing is a big city.","city→城市"),
("class","班级；课",N,1,"high",["student","teacher","lesson","school"],["class","glass"],"We have English class today.","class→班级"),
("classroom","教室",N,1,"high",["class","school","student","desk"],["class","room"],"The classroom is very clean.","classroom→教室"),
("clothes","衣服",N,1,"high",["wear","dress","shirt","put on"],["cloth","close"],"She bought new clothes.","clothes→衣服"),
("cloud","云",N,1,"high",["sky","rain","weather","white"],["cloud","could"],"There are many clouds today.","cloud→云"),
("club","俱乐部",N,1,"high",["group","join","member","team"],["club","class"],"I joined the music club.","club→俱乐部"),
("coat","外套",N,1,"high",["wear","cold","jacket","clothes"],["coat","boat"],"Put on your coat.","coat→外套"),
("coffee","咖啡",N,1,"high",["drink","tea","cup","morning"],["coffee","copy"],"Would you like some coffee?","coffee→咖啡"),
("coin","硬币",N,2,"medium",["money","change","metal","pay"],["coin","corner"],"She found a coin on the ground.","coin→硬币"),
("college","大学",N,1,"high",["university","school","student","study"],["college","collect"],"She goes to college next year.","college→大学"),
("comfort","舒适；安慰",N,2,"medium",["comfortable","ease","relax","warm"],["comfort","command"],"He found comfort in music.","comfort→舒适"),
("company","公司",N,1,"high",["business","work","office","firm"],["company","compare"],"She works for a big company.","company→公司"),
("complaint","投诉；抱怨",N,3,"low",["complain","unhappy","problem","angry"],["complaint","company"],"He made a complaint.","complaint→投诉"),
("computer","电脑",N,1,"high",["internet","technology","program","screen"],["computer","complete"],"I use the computer every day.","computer→电脑"),
("congratulation","祝贺",N,2,"medium",["congratulate","celebrate","success","happy"],["congratulation","connection"],"Congratulations on your success!","congratulation→祝贺"),
("connection","连接；关系",N,2,"medium",["connect","link","relation","internet"],["connection","collection"],"The internet connection is fast.","connection→连接"),
("conversation","对话；谈话",N,1,"high",["talk","chat","discuss","communication"],["conversation","conversation"],"We had a long conversation.","conversation→对话"),
("corner","角落；拐角",N,1,"high",["turn","angle","street","edge"],["corner","correct"],"Turn left at the corner.","corner→角落"),
("cotton","棉花",N,3,"low",["cloth","soft","fabric","material"],["cotton","country"],"This shirt is made of cotton.","cotton→棉花"),
("country","国家；乡村",N,1,"high",["nation","city","countryside","land"],["country","count"],"China is a large country.","country→国家"),
("courage","勇气",N,1,"high",["brave","fear","bold","encourage"],["courage","encourage"],"He showed great courage.","courage→勇气"),
("course","课程；过程",N,1,"high",["class","study","lesson","of course"],["course","cause"],"Of course you can come.","course→课程"),
("cousin","堂（表）兄弟",N,1,"medium",["uncle","aunt","family","relative"],["cousin","council"],"My cousin is two years older.","cousin→堂兄弟"),
("cow","奶牛",N,1,"medium",["milk","farm","animal","cattle"],["cow","how"],"The cow gives us milk.","cow→奶牛"),
("cream","奶油",N,3,"low",["ice cream","milk","sweet","white"],["cream","cream"],"I like ice cream.","cream→奶油"),
("crop","庄稼；作物",N,3,"low",["farm","plant","grow","harvest"],["crop","drop"],"The crops grew well this year.","crop→庄稼"),
("crossing","十字路口",N,2,"medium",["road","cross","street","corner"],["crossing","cross"],"Be careful at the crossing.","crossing→十字路口"),
("crowd","人群",N,2,"medium",["people","group","many","crowded"],["crowd","cloud"],"There was a big crowd.","crowd→人群"),
("cruel","残忍的",A,2,"medium",["kind","mean","cruel","heartless"],["cruel","cruise"],"Don't be cruel to animals.","cruel→残忍的"),
("culture","文化",N,1,"high",["tradition","art","custom","society"],["culture","courage"],"Chinese culture is very rich.","culture→文化"),
("cup","杯子",N,1,"high",["glass","drink","tea","mug"],["cup","cut"],"Give me a cup of tea.","cup→杯子"),
("customer","顾客",N,2,"medium",["shop","buy","service","client"],["custom","customer"],"The customer was satisfied.","customer→顾客"),
("danger","危险",N,1,"high",["safe","risk","harm","fear"],["danger","dangerous"],"Stay away from danger.","danger→危险"),
("daughter","女儿",N,1,"high",["son","child","parent","sister"],["daughter","daughter"],"They have two daughters.","daughter→女儿"),
("day","天；白天",N,1,"high",["night","today","date","time"],["day","say"],"What day is it today?","day→天"),
("death","死亡",N,2,"medium",["die","dead","life","alive"],["death","deaf"],"His death made everyone sad.","death→死亡"),
("decision","决定",N,1,"high",["decide","choice","plan"],["decision","declaration"],"She made a wise decision.","decision→决定"),
("degree","度数；学位",N,2,"medium",["temperature","university","level","angle"],["degree","depend"],"Water boils at 100 degrees.","degree→度数"),
("dentist","牙医",N,3,"low",["teeth","doctor","hospital"],["dentist","dependent"],"I need to see a dentist.","dentist→牙医"),
("desert","沙漠",N,2,"medium",["sand","dry","hot","empty"],["desert","deserve"],"Camels live in the desert.","desert→沙漠"),
("design","设计",N,2,"medium",["plan","create","art","pattern"],["design","desire"],"The design of the building is modern.","design→设计"),
("desk","书桌",N,1,"high",["table","chair","school","office"],["desk","discuss"],"There are many books on the desk.","desk→书桌"),
("dictionary","字典",N,1,"high",["word","meaning","look up","language"],["dictionary","direction"],"Look it up in the dictionary.","dictionary→字典"),
("dinner","晚餐",N,1,"high",["meal","eat","evening","food"],["dinner","dining"],"What's for dinner?","dinner→晚餐"),
("direction","方向",N,1,"high",["way","left","right","north"],["dictionary","director"],"Which direction should I go?","direction→方向"),
("director","导演；主任",N,2,"medium",["movie","film","leader","manage"],["direction","director"],"He is a famous film director.","director→导演"),
("disaster","灾难",N,2,"medium",["accident","danger","terrible","destroy"],["disaster","discover"],"The earthquake was a terrible disaster.","disaster→灾难"),
("disease","疾病",N,2,"medium",["illness","sick","health","hospital"],["disease","disgust"],"He caught a serious disease.","disease→疾病"),
("distance","距离",N,2,"medium",["far","near","long","meter"],["distance","instance"],"The distance between two cities is 100 km.","distance→距离"),
("doctor","医生",N,1,"high",["hospital","patient","medicine","health"],["doctor","document"],"The doctor said I need rest.","doctor→医生"),
("document","文件",N,2,"medium",["paper","file","write","official"],["document","doctor"],"Please sign the document.","document→文件"),
("door","门",N,1,"high",["open","close","enter","room"],["door","floor"],"Close the door, please.","door→门"),
("dream","梦想",N,1,"high",["hope","wish","sleep","goal"],["cream","dream"],"My dream is to travel the world.","dream→梦想"),
("dress","连衣裙；衣服",N,1,"high",["clothes","wear","skirt","outfit"],["dress","dream"],"She wore a beautiful dress.","dress→连衣裙"),
("duty","责任；义务",N,2,"medium",["responsibility","job","task","must"],["duty","dusty"],"It is our duty to protect the environment.","duty→责任"),
("earth","地球；土地",N,1,"high",["world","planet","ground","nature"],["earth","early"],"The earth goes around the sun.","earth→地球"),
("education","教育",N,1,"high",["school","learn","teach","study"],["education","educate"],"Education is very important.","education→教育"),
("email","电子邮件",N,1,"high",["internet","message","send","computer"],["email","emotion"],"I received your email.","email→电子邮件"),
("emotion","情感；情绪",N,2,"medium",["feeling","happy","sad","love"],["emotion","motion"],"She couldn't control her emotions.","emotion→情感"),
("end","结束；尽头",N,1,"high",["finish","beginning","start","stop"],["end","enemy"],"At the end of the story...","end→结束"),
("enemy","敌人",N,2,"medium",["friend","fight","hate","oppose"],["enemy","energy"],"He has many enemies.","enemy→敌人"),
("energy","能量；精力",N,1,"high",["power","strength","electricity","tired"],["enemy","engine"],"She has a lot of energy.","energy→能量"),
("engine","引擎；发动机",N,3,"low",["machine","car","power","motor"],["engine","energy"],"The car engine is very loud.","engine→引擎"),
("environment","环境",N,1,"high",["nature","protect","pollution","green"],["environment","government"],"We should protect the environment.","environment→环境"),
("exam","考试",N,1,"high",["test","question","pass","fail"],["exam","example"],"I have a math exam tomorrow.","exam→考试"),
("example","例子",N,1,"high",["sample","model","instance","case"],["exam","except"],"Can you give me an example?","example→例子"),
("exercise","锻炼；练习",N,1,"high",["sport","health","practice","run"],["exercise","excellent"],"Exercise is good for you.","exercise→锻炼"),
("exit","出口",N,2,"medium",["enter","door","leave","way"],["exist","expect"],"Where is the exit?","exit→出口"),
("expectation","期望",N,2,"medium",["expect","hope","wish","anticipate"],["expect","except"],"He has high expectations.","expectation→期望"),
("expense","费用；开支",N,3,"low",["cost","money","spend","pay"],["expense","experience"],"Travel expenses can be high.","expense→费用"),
("experience","经验；经历",N,1,"high",["practice","knowledge","skill"],["experiment","expert"],"She has rich experience.","experience→经验"),
("experiment","实验",N,2,"medium",["science","test","lab","try"],["experiment","experience"],"We did an experiment in class.","experiment→实验"),
("expert","专家",N,2,"medium",["professional","specialist","skill"],["expect","export"],"He is an expert in history.","expert→专家"),
("explanation","解释",N,2,"medium",["explain","reason","understand"],["explain","examination"],"Can you give me an explanation?","explanation→解释"),
("eye","眼睛",N,1,"high",["see","look","watch","sight"],["eye","ear"],"She has beautiful eyes.","eye→眼睛"),
("face","脸；面对",N,1,"high",["look","eye","smile","mouth"],["face","fact"],"She has a round face.","face→脸"),
("fact","事实",N,1,"high",["truth","real","actually","opinion"],["face","factory"],"It is a fact that the earth is round.","fact→事实"),
("factory","工厂",N,1,"high",["worker","produce","machine","company"],["fact","factory"],"My father works in a factory.","factory→工厂"),
("failure","失败",N,2,"medium",["fail","success","lose","mistake"],["failure","fallure"],"Failure is the mother of success.","failure→失败"),
("faith","信仰；信任",N,2,"medium",["believe","trust","religion","hope"],["fail","fair"],"I have faith in you.","faith→信仰"),
("family","家庭",N,1,"high",["parent","child","home","love"],["family","famous"],"I love my family.","family→家庭"),
("fan","风扇；粉丝",N,1,"high",["cool","wind","support","like"],["fan","fun"],"I am a big fan of basketball.","fan→粉丝"),
("farm","农场",N,1,"high",["farmer","animal","plant","crop"],["farm","form"],"My uncle has a farm.","farm→农场"),
("fear","恐惧；害怕",N,1,"high",["afraid","scared","brave","danger"],["fear","fair"],"She has a fear of heights.","fear→恐惧"),
("feeling","感觉",N,1,"high",["emotion","touch","happy","sad"],["feel","feet"],"What are your feelings about this?","feeling→感觉"),
("festival","节日",N,1,"high",["holiday","celebrate","party","tradition"],["festival","final"],"Spring Festival is important in China.","festival→节日"),
("field","田野；领域",N,1,"high",["farm","area","land","play"],["field","fill"],"They are working in the field.","field→田野"),
("fight","战斗；打架",N,1,"high",["battle","war","argue","conflict"],["fight","right"],"He got into a fight.","fight→战斗"),
("finger","手指",N,1,"high",["hand","touch","point","thumb"],["finger","figure"],"She pointed her finger at me.","finger→手指"),
("fire","火",N,1,"high",["burn","hot","flame","heat"],["fire","fire"],"Don't play with fire.","fire→火"),
("fish","鱼",N,1,"high",["water","sea","swim","food"],["fish","dish"],"I caught a big fish.","fish→鱼"),
("flag","旗",N,2,"medium",["country","red","national","wave"],["flag","flat"],"The national flag is red.","flag→旗"),
("floor","地板；楼层",N,1,"high",["ground","room","building","clean"],["floor","door"],"The floor is very clean.","floor→地板"),
("flower","花",N,1,"high",["plant","garden","beautiful","bloom"],["flower","floor"],"The flowers are beautiful.","flower→花"),
("fog","雾",N,3,"low",["cloud","weather","thick","mist"],["fog","dog"],"Driving in the fog is dangerous.","fog→雾"),
("food","食物",N,1,"high",["eat","meal","hungry","cook"],["food","foot"],"Chinese food is delicious.","food→食物"),
("foot","脚",N,1,"high",["leg","walk","shoe","toe"],["food","foot"],"He hurt his foot.","foot→脚"),
("football","足球",N,1,"high",["sport","play","ball","team"],["foot","food"],"I like playing football.","football→足球"),
("force","力量；武力",N,2,"medium",["power","strong","push","army"],["force","foreign"],"Don't use force.","force→力量"),
("foreigner","外国人",N,2,"medium",["foreign","country","abroad","visit"],["foreign","forest"],"Many foreigners visit China.","foreigner→外国人"),
("forest","森林",N,1,"high",["tree","wood","nature","green"],["foreign","forest"],"There is a big forest near our town.","forest→森林"),
("fork","叉子",N,2,"medium",["knife","spoon","eat","table"],["fork","form"],"Use a fork to eat the salad.","fork→叉子"),
("foundation","基础",N,3,"low",["base","beginning","ground","build"],["foundation","function"],"Trust is the foundation of friendship.","foundation→基础"),
("freedom","自由",N,2,"medium",["free","liberty","right","independence"],["free","freeze"],"We value our freedom.","freedom→自由"),
("friend","朋友",N,1,"high",["friendly","pal","classmate","mate"],["friend","free"],"She is my best friend.","friend→朋友"),
("fruit","水果",N,1,"high",["apple","banana","healthy","eat"],["fruit","front"],"Eat more fruit.","fruit→水果"),
("function","功能；作用",N,2,"medium",["purpose","role","work","use"],["function","foundation"],"What is the function of this button?","function→功能"),
("future","未来",N,1,"high",["past","present","tomorrow","hope"],["future","furniture"],"What do you want to be in the future?","future→未来"),
("game","游戏；比赛",N,1,"high",["play","sport","fun","win"],["game","name"],"Let's play a game.","game→游戏"),
("garden","花园",N,1,"high",["flower","plant","tree","park"],["garden","guarden"],"She is working in the garden.","garden→花园"),
("gate","大门",N,1,"high",["door","enter","school","exit"],["gate","game"],"Wait for me at the school gate.","gate→大门"),
("gift","礼物",N,1,"high",["present","birthday","give","surprise"],["gift","give"],"Thank you for the gift.","gift→礼物"),
("girl","女孩",N,1,"high",["boy","woman","female","young"],["girl","give"],"She is a lovely girl.","girl→女孩"),
("goal","目标；球门",N,1,"high",["aim","target","dream","score"],["goal","gold"],"My goal is to study hard.","goal→目标"),
("gold","金子",N,1,"medium",["metal","yellow","valuable","money"],["gold","goal"],"Gold is very expensive.","gold→金子"),
("government","政府",N,2,"medium",["country","leader","law","rule"],["government","movement"],"The government made a new law.","government→政府"),
("grade","年级；成绩",N,1,"high",["class","score","mark","student"],["grade","grade"],"She is in Grade 8.","grade→年级"),
("grain","谷物",N,3,"low",["wheat","rice","farm","food"],["grain","grand"],"Farmers grow grain.","grain→谷物"),
("grandparent","祖父母",N,2,"medium",["grandmother","grandfather","family","old"],["grand","grant"],"My grandparents live in the countryside.","grandparent→祖父母"),
("grass","草",N,1,"high",["green","plant","ground","field"],["grass","glass"],"The grass is green.","grass→草"),
("ground","地面",N,1,"high",["floor","earth","land","field"],["ground","group"],"The book fell on the ground.","ground→地面"),
("group","组；群",N,1,"high",["team","team","class","together"],["group","ground"],"We are in the same group.","group→组"),
("growth","增长；成长",N,2,"medium",["grow","increase","develop","progress"],["group","grow"],"The growth of the city is rapid.","growth→增长"),
("guest","客人",N,2,"medium",["visitor","host","invite","welcome"],["guest","guess"],"We have a guest today.","guest→客人"),
("guide","导游；指南",N,2,"medium",["lead","show","tour","direction"],["guide","guess"],"The guide showed us around.","guide→导游"),
("guitar","吉他",N,2,"medium",["music","play","instrument","song"],["guitar","guard"],"She plays the guitar well.","guitar→吉他"),
]

for e in entries:
    add(*e)

outpath = '/Volumes/ORICO/xinwen/claudecode/chinese-learn/src/data/_part3_cache.json'
with open(outpath, 'w', encoding='utf-8') as f:
    json.dump(words, f, ensure_ascii=False, indent=2)

print(f'Part 3 done: {len(words)} words total')
