#!/usr/bin/env python3
"""补充初二词库至1200+词"""
import json

with open('src/data/words_network_j2.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

existing = set(data['words'].keys())
print(f"当前: {len(existing)} 词")

new_words = [
    # === 形容词 opinion (大量补充) ===
    ("awful", "可怕的；糟糕的", "adjective_opinion", 1, "medium",
     ["terrible", "horrible", "dreadful"], ["awhile"],
     "The weather was awful yesterday.", "a+wful → 啊！完蛋了→糟糕的"),
    ("awesome", "令人敬畏的；极好的", "adjective_opinion", 1, "medium",
     ["wonderful", "amazing", "excellent"], ["awful"],
     "The view from the mountain is awesome.", "awe(敬畏)+some→令人敬畏的"),
    ("boring", "无聊的；乏味的", "adjective_opinion", 1, "high",
     ["dull", "tedious", "uninteresting"], ["bowling"],
     "This movie is so boring.", "bore(厌烦)+ing→让人厌烦的"),
    ("brave", "勇敢的；无畏的", "adjective_opinion", 1, "high",
     ["courageous", "fearless", "bold"], ["grave"],
     "The brave firefighter saved the child.", "b(不)+rave(咆哮)→不退缩→勇敢"),
    ("careful", "小心的；仔细的", "adjective_opinion", 1, "high",
     ["cautious", "attentive"], ["career"],
     "Be careful when you cross the street.", "care(关心)+ful→关心细节的→仔细的"),
    ("cheap", "便宜的；廉价的", "adjective_opinion", 1, "medium",
     ["inexpensive", "low-priced"], ["cheat"],
     "This pen is very cheap.", "c+heap(堆)→一堆便宜货"),
    ("clever", "聪明的；机灵的", "adjective_opinion", 1, "high",
     ["smart", "bright", "intelligent"], ["cleaver"],
     "She gave a clever answer.", "cleav(劈开)+er→脑子能劈开问题→聪明的"),
    ("comfortable", "舒适的；自在的", "adjective_opinion", 1, "high",
     ["cozy", "pleasant", "relaxing"], [],
     "This chair is very comfortable.", "comfort(舒适)+able→舒适的"),
    ("convenient", "方便的；便利的", "adjective_opinion", 1, "medium",
     ["handy", "easy to use"], ["convention"],
     "The bus stop is convenient for me.", "con(共同)+veni(来)+ent→走到一起→方便的"),
    ("dangerous", "危险的", "adjective_opinion", 1, "high",
     ["risky", "unsafe", "hazardous"], ["dance"],
     "It is dangerous to swim alone.", "danger(危险)+ous→危险的"),
    ("difficult", "困难的；艰难的", "adjective_opinion", 1, "high",
     ["hard", "tough", "challenging"], ["difference"],
     "The exam was very difficult.", "dif(分开)+fic(做)→很难做→困难的"),
    ("eager", "渴望的；热切的", "adjective_opinion", 1, "medium",
     ["keen", "anxious", "enthusiastic"], ["eagle"],
     "She is eager to learn English.", "eagle(鹰)→像鹰一样渴望→热切的"),
    ("exciting", "令人兴奋的；刺激的", "adjective_opinion", 1, "high",
     ["thrilling", "amazing"], ["excite"],
     "The game was really exciting!", "excit(兴奋)+ing→令人兴奋的"),
    ("expensive", "昂贵的；花钱多的", "adjective_opinion", 1, "medium",
     ["costly", "pricey", "dear"], ["experience"],
     "This car is too expensive for me.", "ex(出)+pens(花费)→花出去很多→昂贵的"),
    ("famous", "著名的；出名的", "adjective_opinion", 1, "high",
     ["well-known", "celebrated", "renowned"], ["famine"],
     "Beijing is famous for the Great Wall.", "fame(名声)+ous→有名声的"),
    ("fantastic", "极好的；奇异的", "adjective_opinion", 1, "medium",
     ["wonderful", "marvelous", "great"], ["fan"],
     "The food here is fantastic!", "fantasy(幻想)+tic→像幻想一样好的"),
    ("favorite", "最喜欢的；宠爱的", "adjective_opinion", 1, "high",
     ["preferred", "beloved", "most-liked"], ["flavor"],
     "What is your favorite color?", "favor(偏爱)+ite→最偏爱的"),
    ("funny", "有趣的；滑稽的", "adjective_opinion", 1, "high",
     ["amusing", "humorous", "comical"], ["fan"],
     "He told a funny joke.", "fun(乐趣)+ny→有乐趣的→滑稽的"),
    ("gentle", "温和的；温柔的", "adjective_opinion", 1, "medium",
     ["soft", "kind", "mild"], [],
     "She has a gentle voice.", "gent(优雅)+le→优雅温和的"),
    ("helpful", "有帮助的；乐于助人的", "adjective_opinion", 1, "high",
     ["useful", "supportful"], [],
     "Thank you for being so helpful.", "help(帮助)+ful→有帮助的"),
    ("important", "重要的；重大的", "adjective_opinion", 1, "high",
     ["significant", "major", "crucial"], ["import"],
     "Health is more important than money.", "im(进入)+port(拿)→拿进来的→重要的"),
    ("interesting", "有趣的；引起兴趣的", "adjective_opinion", 1, "high",
     ["fascinating", "engaging"], ["interest"],
     "This book is very interesting.", "interest(兴趣)+ing→有兴趣的"),
    ("lucky", "幸运的；吉利的", "adjective_opinion", 1, "medium",
     ["fortunate"], [],
     "You are lucky to have such a good teacher.", "luck(运气)+y→幸运的"),
    ("necessary", "必要的；必需的", "adjective_opinion", 1, "high",
     ["essential", "required", "needed"], [],
     "Water is necessary for life.", "ne(需要)+cess(走)→必须走的路→必要的"),
    ("perfect", "完美的；理想的", "adjective_opinion", 1, "high",
     ["flawless", "ideal", "excellent"], ["prefer"],
     "Your pronunciation is almost perfect.", "per(完全)+fect(做)→完全做好了→完美的"),
    ("popular", "流行的；受欢迎的", "adjective_opinion", 1, "high",
     ["well-liked", "fashionable", "common"], ["population"],
     "Basketball is popular among teenagers.", "popul(人民)+ar→人民都喜欢的→流行的"),
    ("pretty", "漂亮的；相当", "adjective_opinion", 1, "high",
     ["beautiful", "quite", "fairly"], [],
     "The flowers are pretty.", "pr(漂亮)+etty(女孩)→漂亮的女孩"),
    ("serious", "严肃的；严重的；认真的", "adjective_opinion", 1, "high",
     ["solemn", "severe", "earnest"], ["series"],
     "This is a serious problem.", "seri(严肃)+ous→严肃的"),
    ("strange", "奇怪的；陌生的", "adjective_opinion", 1, "medium",
     ["odd", "unusual", "weird"], ["range"],
     "I heard a strange noise last night.", "strange本身→奇怪"),

    # === 形容词 describe (补充) ===
    ("deep", "深的；深奥的", "adjective_describe", 1, "high",
     ["profound", "thick", "low"], ["deer"],
     "The river is very deep here.", "d+eep(eep很深)→深的"),
    ("empty", "空的；空虚的", "adjective_describe", 1, "high",
     ["vacant", "hollow", "unfilled"], ["entry"],
     "The bottle is empty.", "em(无)+pty→什么都没有→空的"),
    ("heavy", "重的；沉重的", "adjective_describe", 1, "high",
     ["weighty", "burdensome"], ["healthy"],
     "This box is too heavy to carry.", "heav(y重)+y→重的"),
    ("light", "轻的；明亮的", "adjective_describe", 1, "high",
     ["weightless", "bright", "pale"], [],
     "This bag is light enough to carry.", "light本身→轻的"),
    ("long", "长的；长时间的", "adjective_describe", 1, "high",
     ["lengthy", "extended"], [],
     "The river is very long.", "long本身→长的"),
    ("short", "短的；矮的", "adjective_describe", 1, "high",
     ["brief", "low"], ["shirt"],
     "She has short hair.", "short本身→短的"),
    ("wide", "宽的；广阔的", "adjective_describe", 1, "medium",
     ["broad", "spacious", "extensive"], ["wife"],
     "The road is wide enough for two cars.", "wide本身→宽的"),
    ("young", "年轻的；幼小的", "adjective_describe", 1, "high",
     ["youthful", "junior"], [],
     "He is too young to drive.", "young本身→年轻的"),
    ("round", "圆的；圆形的", "adjective_describe", 1, "medium",
     ["circular", "spherical"], ["around"],
     "The table is round.", "round本身→圆的"),

    # === 形容词 quantity (补充) ===
    ("enough", "足够的；充分的", "adjective_quantity", 1, "high",
     ["sufficient", "adequate", "plenty of"], ["rough"],
     "Do we have enough food?", "en(使)+ough(够)→使它够了→足够的"),
    ("extra", "额外的；特大的", "adjective_quantity", 1, "medium",
     ["additional", "more", "spare"], ["expert"],
     "Can I have some extra time?", "ex(出)+tra(拉)→额外拉出来的→额外的"),
    ("whole", "整个的；全部的", "adjective_quantity", 1, "high",
     ["entire", "total", "complete"], ["hole"],
     "I spent the whole day reading.", "wh(全)+ole(整体)→整体的"),
    ("main", "主要的；最重要的", "adjective_quantity", 1, "high",
     ["chief", "primary", "major"], [],
     "What is the main idea?", "main本身→主要的"),
    ("public", "公共的；公众的", "adjective_quantity", 1, "high",
     ["open", "communal"], ["publish"],
     "Don't smoke in public places.", "pub(大众)+lic→大众的→公共的"),

    # === 名词 academic (补充) ===
    ("ability", "能力；才能", "noun_academic", 1, "high",
     ["skill", "capability", "talent"], [],
     "She has great ability in math.", "abil(能)+ity→能力的名词形式"),
    ("advantage", "优势；有利条件", "noun_academic", 1, "medium",
     ["benefit", "strong point", "edge"], ["advance"],
     "Speaking English is a big advantage.", "ad(加强)+vant(价值)→有价值的东西→优势"),
    ("attention", "注意；关注；专心", "noun_academic", 1, "high",
     ["focus", "concentration", "notice"], ["attend"],
     "Please pay attention!", "at(向)+tent(伸)→伸向...→注意力"),
    ("choice", "选择；抉择", "noun_academic", 1, "high",
     ["option", "selection", "decision"], ["choose"],
     "Making the right choice is important.", "choos(e选择)+ce→选择(名词)"),
    ("condition", "条件；状况；环境", "noun_academic", 1, "medium",
     ["situation", "state", "requirement"], [],
     "The car is in good condition.", "cond(条件)+ition→条件"),
    ("culture", "文化；文明；修养", "noun_academic", 1, "high",
     ["civilization", "customs", "tradition"], ["cultivate"],
     "Chinese culture has a long history.", "cult(耕作)+ure→耕耘出来的→文化"),
    ("environment", "环境；周围状况", "noun_academic", 1, "high",
     ["surroundings", "nature", "ecology"], [],
     "We should protect our environment.", "en(在)+viron(周围)→周围的东西→环境"),
    ("experience", "经验；经历；体验", "noun_academic", 1, "high",
     ["practice", "background", "knowledge"], ["experiment"],
     "She has five years of teaching experience.", "ex(出)+peri(尝试)→试出来的→经验"),
    ("goal", "目标；目的；球门", "noun_academic", 1, "high",
     ["aim", "target", "objective"], [],
     "My goal is to get into university.", "goal本身→目标"),
    ("habit", "习惯；习性", "noun_academic", 1, "high",
     ["custom", "routine", "practice"], [],
     "Reading every day is a good habit.", "hab(住)+it→住在里面→习惯"),
    ("method", "方法；办法；条理", "noun_academic", 1, "medium",
     ["way", "technique", "approach"], ["mode"],
     "This method works well.", "meth(方式)+od→方法"),
    ("opportunity", "机会；时机", "noun_academic", 1, "high",
     ["chance", "possibility", "opening"], [],
     "Don't miss this opportunity!", "op(朝向)+portun(港口)→朝向港口→机会"),
    ("progress", "进步；进展；前进", "noun_academic", 1, "high",
     ["development", "improvement", "advance"], ["program"],
     "You've made great progress.", "pro(向前)+gress(走)→向前走→进步"),
    ("reason", "原因；理由；道理", "noun_academic", 1, "high",
     ["cause", "basis", "logic"], [],
     "Give me a reason why you were late.", "reason本身→原因"),
    ("result", "结果；后果；成绩", "noun_academic", 1, "high",
     ["outcome", "effect", "consequence"], [],
     "Hard work brings good results.", "re(回)+sult(跳)→跳回来→结果"),
    ("success", "成功；成就；胜利", "noun_academic", 1, "high",
     ["achievement", "victory", "accomplishment"], ["suggest"],
     "Practice is the key to success.", "succ(下面)+cess(走)→一直走下去→成功"),
    ("technology", "技术；科技；工艺", "noun_academic", 1, "high",
     ["tech", "science", "engineering"], ["technical"],
     "Technology changes our lives fast.", "techn(技术)+ology→技术的学问"),

    # === 短语动词 verb_phrasal (新增分类) ===
    ("take off", "起飞；脱下", "verb_phrasal", 1, "medium",
     ["lift off", "remove", "depart"], [],
     "The plane will take off soon.", "take(拿)+off(脱下)→脱下/起飞"),
    ("put on", "穿上；上演", "verb_phrasal", 1, "high",
     ["wear", "dress in", "add"], [],
     "Put on your coat.", "put(放)+on(上)→穿上去"),
    ("look after", "照顾；照料", "verb_phrasal", 1, "high",
     ["take care of", "watch over"], [],
     "Can you look after my cat?", "look(看)+after(之后)→之后还看着→照顾"),
    ("give up", "放弃；投降", "verb_phrasal", 1, "high",
     ["surrender", "quit", "stop trying"], [],
     "Never give up on your dreams!", "give(给)+up(向上)→交出去→放弃"),
    ("turn on", "打开（电器）", "verb_phrasal", 1, "high",
     ["switch on", "start"], [],
     "Please turn on the lights.", "turn(转)+on(开)→转开"),
    ("turn off", "关闭（电器）", "verb_phrasal", 1, "high",
     ["switch off", "shut down"], [],
     "Turn off the TV before bed.", "turn(转)+off(关)→关掉"),
    ("pick up", "捡起；接人；学会", "verb_phrasal", 1, "high",
     ["lift", "collect", "learn quickly"], [],
     "Can you pick me up at 5?", "pick(捡)+up(起)→捡起来"),
    ("set up", "建立；设立；安装", "verb_phrasal", 1, "medium",
     ["establish", "create", "install"], [],
     "They set up a new company.", "set(放置)+up(向上)→建立"),
    ("make up", "组成；编造；化妆", "verb_phrasal", 1, "medium",
     ["compose", "invent", "apply makeup"], [],
     "Don't make up stories.", "make(做)+up(编出来)→编造"),
    ("break down", "出故障；分解；崩溃", "verb_phrasal", 1, "medium",
     ["fail", "stop working", "collapse"], [],
     "My car broke down.", "break(破)+down(向下)→坏掉→故障"),
    ("carry on", "继续；坚持", "verb_phrasal", 1, "medium",
     ["continue", "keep going", "persist"], [],
     "Carry on with your work.", "carry(带)+on(继续)→带着继续"),
    ("come across", "偶然遇见", "verb_phrasal", 1, "medium",
     ["meet by chance", "find", "encounter"], [],
     "I came across an old photo.", "come(来)+across(穿过)→穿过遇到"),
    ("find out", "查明；发现", "verb_phrasal", 1, "high",
     ["discover", "learn", "figure out"], [],
     "Please find out who did it.", "find(找)+out(出来)→找出来"),
    ("get along", "相处融洽", "verb_phrasal", 1, "medium",
     ["get on well", "have a good relationship"], [],
     "I get along well with my classmates.", "get(得)+along(一起)→一起相处"),
    ("go over", "复习；仔细检查", "verb_phrasal", 1, "medium",
     ["review", "check", "examine"], [],
     "Let's go over the lesson again.", "go(走)+over(越过)→从头过一遍→复习"),
    ("hang out", "闲逛；出去玩", "verb_phrasal", 1, "medium",
     ["hang around", "spend time together"], [],
     "We like to hang out at the mall.", "hang(挂)+out(外面)→挂在外面玩"),
    ("show up", "出现；露面", "verb_phrasal", 1, "medium",
     ["appear", "arrive", "turn up"], [],
     "He didn't show up at the meeting.", "show(展示)+up(上来)→现身"),
]

added = 0; dup = 0
for entry in new_words:
    w = entry[0].lower()
    if w not in data['words']:
        data['words'][w] = {
            'word': w,
            'meaning': entry[1],
            'category': entry[2],
            'tier': entry[3],
            'frequency': entry[4],
            'associations': entry[5],
            'confusables': entry[6],
            'example': entry[7],
            'memory_tip': entry[8]
        }
        added += 1
    else:
        dup += 1

# 清理自引用和重叠
sr = 0; ol = 0
for w, obj in data['words'].items():
    ass = set(obj.get('associations',[]) or [])
    conf = set(obj.get('confusables',[]) or [])
    new_ass = [a for a in ass if a != w]
    new_conf = [c for c in conf if c != w and c not in set(new_ass)]
    if len(new_ass) < len(ass): sr += 1
    if len(new_conf) < len(conf): sr += 1
    oc = len(set(new_conf) & set(new_ass))
    if oc > 0: ol += 1
    obj['associations'] = new_ass
    obj['confusables'] = new_conf

with open('src/data/words_network_j2.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\n=== 补充完成 ===")
print(f"新增: {added} | 跳过重复: {dup}")
print(f"总词数: {len(data['words'])}")
print(f"自引用修复: {sr} | 重叠修复: {ol}")
